export default {
  root: "grid min-w-0 gap-2",
  header: "flex min-w-0 flex-wrap items-start justify-between gap-2",
  titleBlock: "grid min-w-0 gap-0.5",
  title: "min-w-0 [font-size:var(--vui-font-xs)] font-[820] leading-tight text-[var(--fg-primary)]",
  summary: "min-w-0 max-w-[70ch] [font-size:var(--vui-font-2xs)] leading-snug text-[var(--fg-secondary)]",
  actions: "flex shrink-0 flex-wrap items-center gap-1",
  metrics: "min-w-0",
  evidence: "grid min-w-0 grid-cols-2 gap-1 sm:grid-cols-5",
  evidenceItem: "grid min-w-0 gap-1 rounded border border-[var(--vui-border-subtle)] bg-[var(--vui-surface-raised)] px-1.5 py-1",
  evidenceLabel: "min-w-0 truncate [font-size:var(--vui-font-2xs)] font-[720] text-[var(--fg-secondary)]",
  evidenceStatus: "min-w-0",
  evidenceLocator: "min-w-0 truncate [font-size:10px] text-[var(--fg-tertiary)]",
  blockers: "min-w-0 rounded border border-[color-mix(in_srgb,var(--state-warning)_35%,var(--vui-border-subtle))] bg-[color-mix(in_srgb,var(--state-warning)_7%,transparent)] px-2 py-1.5 [font-size:var(--vui-font-2xs)] text-[var(--fg-secondary)]",
  blockersSummary: "cursor-pointer select-none font-[720] text-[var(--fg-primary)]",
  blockerList: "m-0 mt-1.5 grid max-h-28 min-w-0 gap-1 overflow-y-auto pl-4",
  blocker: "min-w-0 break-words whitespace-pre-wrap leading-snug",
  blockerMore: "mt-1 text-[var(--fg-tertiary)]",
  boundary: "min-w-0 break-words rounded border border-[var(--vui-border-subtle)] bg-[var(--vui-surface-toolbar)] px-2 py-1.5 [font-size:var(--vui-font-2xs)] leading-snug text-[var(--fg-secondary)]",
  errorDetail: "line-clamp-2 min-w-0 break-words whitespace-pre-wrap",
} as const;
