export default {
  root: "grid min-w-0 gap-2",
  header: "flex min-w-0 flex-wrap items-start justify-between gap-2",
  titleBlock: "grid min-w-0 gap-0.5",
  title: "min-w-0 [font-size:var(--vui-font-xs)] font-[820] leading-tight text-[var(--fg-primary)]",
  summary: "min-w-0 max-w-[74ch] [font-size:var(--vui-font-2xs)] leading-snug text-[var(--fg-secondary)]",
  headerActions: "flex shrink-0 flex-wrap items-center gap-1",
  gateToolbar: "flex min-w-0 flex-wrap items-center gap-2 rounded border border-[var(--vui-border-subtle)] bg-[var(--vui-surface-toolbar)] px-2 py-1.5",
  gateSelect: "w-44 max-w-full",
  gateSequence: "min-w-0 break-words [font-size:var(--vui-font-2xs)] text-[var(--fg-tertiary)]",
  gateItem: "font-mono text-[10px]",
  gateActive: "font-mono text-[10px] font-bold text-[var(--accent-cool)]",
  metrics: "min-w-0",
  progressMeta: "flex min-w-0 flex-wrap justify-between gap-x-3 gap-y-1 [font-size:var(--vui-font-2xs)] text-[var(--fg-secondary)]",
  observability: "grid min-w-0 gap-1 rounded border border-[var(--vui-border-subtle)] bg-[var(--vui-surface-raised)] px-2 py-1.5 [font-size:var(--vui-font-2xs)]",
  observabilityHeader: "flex min-w-0 flex-wrap items-center justify-between gap-x-2 gap-y-0.5 text-[var(--fg-primary)]",
  observabilityRow: "flex min-w-0 flex-wrap items-center gap-x-3 gap-y-1 text-[var(--fg-secondary)]",
  obsItem: "flex min-w-0 items-center gap-1",
  obsLabel: "shrink-0 text-[var(--fg-tertiary)]",
  obsValue: "min-w-0 break-words font-mono text-[10px]",
  obsToneNeutral: "min-w-0 break-words text-[var(--fg-secondary)]",
  obsToneSuccess: "min-w-0 break-words text-[var(--state-success)]",
  obsToneWarning: "min-w-0 break-words text-[var(--state-warning)]",
  obsToneDanger: "min-w-0 break-words text-[var(--state-error)]",
  stopReasonLine: "min-w-0 break-words text-[var(--fg-secondary)]",
  empty: "grid min-w-0 gap-1 rounded border border-[var(--vui-border-subtle)] bg-[var(--vui-surface-raised)] px-2 py-2 [font-size:var(--vui-font-2xs)] leading-snug text-[var(--fg-secondary)]",
  boundary: "grid min-w-0 gap-0.5 rounded border border-[color-mix(in_srgb,var(--state-warning)_38%,var(--vui-border-subtle))] bg-[color-mix(in_srgb,var(--state-warning)_7%,transparent)] px-2 py-1.5 [font-size:var(--vui-font-2xs)] leading-snug text-[var(--fg-secondary)]",
  authorizationMeta: "break-all font-mono text-[10px] text-[var(--fg-tertiary)]",
  blockers: "grid min-w-0 gap-0.5 rounded border border-[color-mix(in_srgb,var(--state-error)_35%,var(--vui-border-subtle))] bg-[color-mix(in_srgb,var(--state-error)_7%,transparent)] px-2 py-1.5 [font-size:var(--vui-font-2xs)] leading-snug text-[var(--state-error)]",
  actions: "flex min-w-0 flex-wrap items-center gap-2",
  pollingHint: "min-w-0 break-words [font-size:var(--vui-font-2xs)] text-[var(--fg-tertiary)]",
  events: "grid min-w-0 gap-1 rounded border border-[var(--vui-border-subtle)] bg-[var(--vui-surface-raised)] px-2 py-1.5 [font-size:var(--vui-font-2xs)]",
  eventsHeader: "flex min-w-0 flex-wrap items-baseline justify-between gap-x-2 gap-y-0.5 text-[var(--fg-primary)]",
  eventEmpty: "min-w-0 break-words leading-snug text-[var(--fg-tertiary)]",
  eventList: "m-0 grid max-h-24 min-w-0 gap-0.5 overflow-y-auto pl-4 leading-snug text-[var(--fg-secondary)] [&>li]:break-words",
  confirmBody: "grid min-w-0 gap-1 [font-size:var(--vui-font-2xs)] leading-snug text-[var(--fg-secondary)]",
} as const;
