export default {
  root: "flex h-full min-h-0 flex-col gap-3 overflow-auto p-3",
  fill: "h-full min-h-0",
  error: "rounded border border-[var(--vui-border-subtle)] bg-[var(--vui-surface-raised)] px-2 py-1.5 [font-size:var(--vui-font-2xs)] text-[var(--fg-primary)]",
  header: "flex items-start justify-between gap-2",
  eyebrow: "text-[10px] uppercase tracking-wide text-[var(--fg-tertiary)]",
  title: "mt-1 block [font-size:var(--vui-font-xs)] text-[var(--fg-primary)]",
  program: "grid gap-3 rounded border border-[var(--vui-border-subtle)] bg-[var(--vui-surface-row)] p-3",
  programHeader: "flex flex-wrap items-center justify-between gap-2 [font-size:var(--vui-font-2xs)] text-[var(--fg-secondary)]",
  contractMeta: "flex flex-wrap gap-x-3 gap-y-1 [font-size:var(--vui-font-2xs)] text-[var(--fg-secondary)]",
  metrics: "grid grid-cols-3 gap-2 [font-size:var(--vui-font-2xs)]",
  metric: "rounded border border-[var(--vui-border-subtle)] px-2 py-1.5",
  metricLabel: "text-[var(--fg-tertiary)]",
  metricValue: "[font-size:var(--vui-font-lg)] font-semibold text-[var(--fg-primary)]",
  catalog: "break-all rounded bg-[var(--vui-control-muted)] px-2 py-1.5 font-mono text-[10px] text-[var(--fg-secondary)]",
  experimentGrid: "grid gap-2",
  experimentCard: "grid gap-1 rounded border border-[var(--vui-border-subtle)] bg-[var(--vui-surface-raised)] p-2 [font-size:var(--vui-font-2xs)]",
  experimentHeader: "flex flex-wrap items-start justify-between gap-2 text-[var(--fg-primary)]",
  experimentIds: "break-all font-mono text-[10px] text-[var(--fg-secondary)]",
  boundary: "grid gap-1 rounded border border-[var(--vui-border-subtle)] px-2 py-1.5 [font-size:var(--vui-font-2xs)] text-[var(--fg-secondary)]",
  notice: "rounded border border-[color-mix(in_srgb,var(--state-warning)_42%,var(--vui-border-subtle))] px-2 py-1.5 [font-size:var(--vui-font-2xs)] text-[var(--state-warning)]",
  readiness: "grid gap-2 rounded border border-[var(--vui-border-subtle)] bg-[var(--vui-surface-row)] p-3",
  devControls: "grid gap-3 rounded border border-[var(--vui-border-subtle)] bg-[var(--vui-surface-row)] p-3",
  devRow: "grid gap-1.5 rounded border border-[var(--vui-border-subtle)] bg-[var(--vui-surface-raised)] p-2",
  devRowHeader: "flex flex-wrap items-center justify-between gap-2 [font-size:var(--vui-font-2xs)] text-[var(--fg-primary)]",
  devMeta: "break-all font-mono text-[10px] text-[var(--fg-secondary)]",
  gateList: "m-0 list-none space-y-1 p-0",
  gateItem: "flex flex-wrap items-center gap-2 [font-size:var(--vui-font-2xs)] text-[var(--fg-secondary)]",
  gateId: "font-mono text-[10px] text-[var(--fg-secondary)]",
  gateDetail: "min-w-0 flex-1 break-all text-[10px]",
  actions: "flex flex-wrap items-center gap-2",
  gateRow: "flex flex-wrap gap-2",
  locator: "break-all font-mono text-[10px] text-[var(--fg-secondary)]",
  questionSection: "grid gap-2",
  sectionHeader: "flex flex-wrap items-center justify-between gap-2 [font-size:var(--vui-font-2xs)] text-[var(--fg-secondary)] [&>strong]:text-[var(--fg-primary)]",
  empty: "h-auto w-full border-0 bg-transparent",
  list: "m-0 list-none space-y-1 p-0",
  item: "flex items-center justify-between gap-2 rounded border border-[var(--vui-border-subtle)] px-2 py-1.5 [font-size:var(--vui-font-2xs)]",
  itemText: "min-w-0",
  itemTitle: "font-medium break-all text-[var(--fg-primary)]",
  itemMeta: "break-all text-[var(--fg-secondary)]",
} as const;
