export default {
  root: "flex h-full min-h-0 flex-col gap-3 overflow-auto p-3",
  fill: "h-full min-h-0",
  error: "rounded border border-[var(--vui-border-subtle)] bg-[var(--vui-surface-raised)] px-2 py-1.5 text-xs text-[var(--fg-primary)]",
  header: "flex items-center justify-between gap-2",
  eyebrow: "text-[10px] uppercase tracking-wide text-[var(--fg-tertiary)]",
  metrics: "grid grid-cols-3 gap-2 text-xs",
  metric: "rounded border border-[var(--vui-border-subtle)] px-2 py-1.5",
  metricLabel: "text-[var(--fg-tertiary)]",
  metricValue: "text-lg font-semibold text-[var(--fg-primary)]",
  empty: "h-auto w-full border-0 bg-transparent",
  list: "m-0 list-none space-y-1 p-0",
  item: "flex items-center justify-between gap-2 rounded border border-[var(--vui-border-subtle)] px-2 py-1.5 text-xs",
  itemText: "min-w-0",
  itemTitle: "font-medium break-all text-[var(--fg-primary)]",
  itemMeta: "break-all text-[var(--fg-secondary)]",
} as const;
