export default {
  note: "text-sm leading-relaxed text-[var(--fg-secondary)]",
  header: "flex items-center justify-between gap-2",
  eyebrow: "text-xs font-medium text-[var(--fg-tertiary)]",
  empty: "h-auto w-full border-0 bg-transparent",
  section: "grid gap-1",
  list: "m-0 list-none space-y-1 p-0",
  item: "rounded border border-[var(--vui-border-subtle)] px-2 py-1.5 text-sm leading-relaxed",
  itemTitle: "font-medium break-words text-[var(--fg-primary)]",
  itemDetail: "break-words text-[var(--fg-secondary)]",
  relationEmpty: "m-0 text-sm leading-relaxed text-[var(--fg-secondary)]",
  relation: "rounded border border-[var(--vui-border-subtle)] px-2 py-1.5 text-sm leading-relaxed break-words text-[var(--fg-primary)]",
  root: "flex h-full min-h-0 flex-col gap-3 overflow-auto p-3",
  fill: "h-full min-h-0",
  error: "rounded border border-[var(--vui-border-subtle)] bg-[var(--vui-surface-raised)] px-2 py-1.5 text-sm leading-relaxed text-[var(--fg-primary)]",
} as const;
