export default {
  header: "flex items-center justify-between gap-2",
  eyebrow: "text-[10px] uppercase tracking-wide text-[var(--fg-tertiary)]",
  empty: "h-auto w-full border-0 bg-transparent",
  section: "grid gap-1",
  list: "m-0 list-none space-y-1 p-0",
  item: "rounded border border-[var(--border-subtle)] px-2 py-1.5 text-xs",
  itemTitle: "font-medium break-all text-[var(--fg-primary)]",
  itemDetail: "break-all text-[var(--fg-secondary)]",
  relationEmpty: "m-0 text-xs text-[var(--fg-secondary)]",
  relation: "rounded border border-[var(--border-subtle)] px-2 py-1.5 text-xs break-all text-[var(--fg-primary)]",
  root: "flex h-full min-h-0 flex-col gap-3 overflow-auto p-3",
  fill: "h-full min-h-0",
  error: "rounded border border-[var(--border-subtle)] bg-[var(--bg-elevated)] px-2 py-1.5 text-xs text-[var(--fg-primary)]",
} as const;
