const styles = {
  panel: "flex min-w-0 flex-col gap-3 p-3",
  stage: "text-[10px] uppercase tracking-wide text-[var(--fg-tertiary)]",
  title: "m-0 [font-size:var(--vui-font-md)] font-semibold text-[var(--fg-primary)]",
  description: "m-0 [font-size:var(--vui-font-xs)] text-[var(--fg-secondary)]",
  facts: "flex flex-col gap-1.5",
  factLabel: "text-[var(--fg-tertiary)]",
  envelope: "m-0 whitespace-pre-wrap break-all [font-size:var(--vui-font-2xs)] text-[var(--fg-secondary)]",
  actions:
    "-mx-1 flex flex-wrap items-center gap-2 border-t border-[var(--vui-border-subtle)] bg-[var(--vui-surface-panel)] px-1 py-3",
  secondary: "mt-auto flex flex-wrap items-center gap-2 pt-2",
  status: "m-0 [font-size:var(--vui-font-xs)] text-[var(--fg-secondary)]",
  commandWrap: "flex flex-col items-start gap-1",
  commandDetail: "[font-size:var(--vui-font-2xs)] text-[var(--fg-secondary)]",
  stageSummary: "flex flex-col gap-1 rounded-[var(--vui-radius-sm)] border border-[color:var(--vui-border-subtle)] bg-[color:var(--vui-surface-raised)] p-3",
  candidateChecklist: "grid gap-2 rounded-[var(--vui-radius-sm)] border border-[var(--vui-border-subtle)] bg-[var(--vui-surface-inset)] p-3",
  candidateChecklistSummary: "flex flex-wrap items-center justify-between gap-1 [font-size:var(--vui-font-xs)] text-[var(--fg-secondary)]",
  candidateChecklistList: "m-0 grid list-none gap-2 p-0",
  candidateChecklistItem: "grid grid-cols-[minmax(0,1fr)_auto_auto] items-center gap-2 rounded-[var(--vui-radius-panel-soft)] border border-[var(--vui-border-subtle)] bg-[var(--vui-surface-card)] p-2",
  candidateChecklistIdentity: "grid min-w-0 max-w-full gap-0.5 overflow-hidden [font-size:var(--vui-font-xs)] text-[var(--fg-secondary)] [&>strong]:min-w-0 [&>strong]:max-w-full [&>strong]:truncate [&>strong]:text-[var(--fg-tertiary)] [&>span]:min-w-0 [&>span]:truncate",
  sourceError: "[font-size:var(--vui-font-2xs)] text-[var(--fg-danger)]",
  history: "grid gap-2 border-t border-[var(--vui-border-subtle)] pt-3",
  historySummary: "flex flex-wrap items-center justify-between gap-2",
  historyList: "m-0 grid list-none gap-2 p-0",
  historyItem: "grid gap-1.5 rounded-[var(--vui-radius-panel-soft)] border border-[var(--vui-border-subtle)] bg-[var(--vui-surface-card)] p-3",
  historyTopline: "flex items-center justify-between gap-2 [font-size:var(--vui-font-sm)]",
  historyCopy: "m-0 [font-size:var(--vui-font-xs)] leading-5 text-[var(--fg-secondary)]",
  historyRetry: "w-fit rounded-full bg-[var(--vui-surface-inset)] px-2 py-0.5 [font-size:var(--vui-font-2xs)] text-[var(--fg-tertiary)]",
  task: "flex min-h-0 flex-col gap-3",
  fill: "h-full",
  bulletedList: "m-0 grid list-disc gap-1 pl-4",
  gateFold: "m-0 [font-size:var(--vui-font-xs)] text-[var(--fg-secondary)] [&>summary]:cursor-pointer [&>summary]:text-[var(--fg-tertiary)] [&>ul]:mt-2",
} as const;

export default styles;
