export default {
  title: "m-0 [font-size:var(--vui-font-2xs)] font-semibold",
  subtitle: "mt-2 [font-size:var(--vui-font-2xs)] font-semibold text-[var(--fg-secondary)]",
  details: "mt-1 grid grid-cols-[56px_1fr] gap-x-2 gap-y-1 [font-size:var(--vui-font-2xs)]",
  label: "text-[var(--fg-tertiary)]",
  value: "m-0",
  valueBreak: "m-0 break-all",
  empty: "mt-1 [font-size:var(--vui-font-2xs)] text-[var(--fg-secondary)]",
  rootSession: "mt-1",
  children: "mt-3 border-t border-[var(--border-subtle)] pt-2",
  retryNote: "mt-1 [font-size:var(--vui-font-2xs)] text-[var(--fg-secondary)]",
  childList: "mt-1 grid gap-2",
  child: "rounded-[var(--radius-control)] border border-[var(--border-subtle)] p-2",
  childHeader: "flex min-w-0 items-center justify-between gap-2 [font-size:var(--vui-font-2xs)]",
  candidate: "min-w-0 truncate",
  status: "shrink-0 text-[var(--fg-secondary)]",
  degraded: "mt-2 [font-size:var(--vui-font-2xs)] text-[var(--fg-secondary)]",
  action: "mt-2",
} as const;
