export const nodeInspectorOpsCardStyles = {
  header: "nio-header",
  stage: "nio-stage",
  titleRow: "nio-title-row",
  title: "nio-title",
  identity: "nio-identity",
  identityCopy: "nio-identity-copy",
  avatar: "nio-avatar",
  avatarEmpty: "nio-avatar-empty",
  name: "nio-name",
  modelTrigger: "nio-model-trigger grid w-full",
  modelRail: "nio-model-rail",
  modelBody: "nio-model-body",
  modelKicker: "nio-model-kicker",
  modelName: "nio-model-name",
  modelMeta: "nio-model-meta",
  picker: "nio-picker",
  pickerSearch: "nio-picker-search",
  pickerList: "nio-picker-list",
  pickerItem: "nio-picker-item grid w-full",
  pickerAgentItem: "nio-picker-agent-item grid w-full",
  pickerItemActive: "nio-picker-item-active",
  pickerItemCopy: "nio-picker-item-copy",
  pickerAvatar: "nio-picker-avatar",
  budget: "nio-budget",
  meter: "nio-meter",
  meterHead: "nio-meter-head",
  meterTrack: "nio-meter-track",
  meterFill: "nio-meter-fill",
  meterWarn: "nio-meter-warn",
  actions: "nio-actions",
  iconLink: "nio-icon-link",
  notice: "nio-notice",
} as const;
