export default {
  root: "flex min-h-0 flex-col gap-3 p-1 [font-size:var(--vui-font-xs)]",
  header: "flex flex-wrap items-center justify-between gap-2",
  eyebrow: "text-[10px] uppercase tracking-wide text-[var(--fg-tertiary)]",
  segmentChips: "flex flex-wrap items-center gap-2",
  section: "grid gap-1.5",
  sectionTitle: "text-[11px] font-semibold text-[var(--fg-primary)]",
  timeline: "m-0 list-none space-y-1.5 p-0",
  timelineItem:
    "grid grid-cols-[10px_minmax(0,1fr)] items-start gap-2 rounded border border-[var(--vui-border-subtle)] px-2 py-1.5",
  timelineMarker: "mt-1.5 size-1.5 rounded-full bg-[var(--fg-tertiary)] opacity-75",
  timelineTopline: "flex flex-wrap items-center gap-2",
  eventKind: "font-medium text-[var(--fg-primary)]",
  eventMeta: "break-all text-[var(--fg-tertiary)]",
  eventReason: "break-words text-[var(--fg-secondary)]",
  cardGrid: "grid gap-1.5 sm:grid-cols-2",
  card: "grid gap-1 rounded border border-[var(--vui-border-subtle)] px-2 py-1.5",
  cardTitle: "break-all font-medium text-[var(--fg-primary)]",
  chipRow: "flex flex-wrap items-center gap-1.5",
  detail: "break-all text-[var(--fg-secondary)]",
  edgeList: "m-0 list-none space-y-1 p-0",
  edge: "break-all rounded border border-[var(--vui-border-subtle)] px-2 py-1 text-[var(--fg-primary)]",
  missingHint: "text-[var(--fg-secondary)]",
  more: "text-[var(--fg-tertiary)]",
  empty: "h-auto w-full border-0 bg-transparent",
  fill: "min-h-24",
} as const;
