/** Typed workflow events emitted by the canonical Run SSE stream. */
export const RESEARCH_WORKFLOW_SSE_EVENT_TYPES = [
  "run_created",
  "command_accepted",
  "command_failed",
  "node_starting",
  "node_running",
  "node_waiting_human",
  "node_succeeded",
  "node_failed",
  "node_blocked",
  "handoff_ready",
  "handoff_accepted",
  "handoff_rejected",
  "budget_reserved",
  "budget_settled",
  "execution_anchor_bound",
  "artifact_verified",
  "run_forked",
  "run_blocked",
  "run_succeeded",
  "reconciliation_required",
] as const;
