/** Typed workflow events emitted by the canonical Run SSE stream. */
export const RESEARCH_WORKFLOW_SSE_EVENT_TYPES = [
  "run.queued",
  "LeaseAcquired",
  "LeaseHeartbeat",
  "LeaseExpired",
  "ActionIssued",
  "ObservationRecorded",
  "CommandReceiptRecorded",
  "ArtifactProduced",
  "ArtifactReused",
  "BudgetReserved",
  "BudgetSettled",
  "BudgetExceeded",
  "QualityGateEvaluated",
  "NodeRunTransitioned",
  "HumanDecisionRecorded",
  "RunForked",
  "RunSuperseded",
  "TaskBundleCancelled",
  "binding.rebind_node",
  "session_binding.bound",
  "node.command.applied",
] as const;
