export default {
  root: "flex flex-col gap-2 p-2",
  header: "flex flex-wrap items-start justify-between gap-2",
  titleBlock: "flex min-w-0 flex-col gap-0.5",
  title: "[font-size:var(--vui-font-sm)] text-[var(--fg-primary)]",
  summary: "text-[var(--fg-tertiary)] [font-size:var(--vui-font-2xs)]",
  headerActions: "flex shrink-0 flex-wrap items-center gap-1.5",
  batchError: "text-[var(--fg-danger)] [font-size:var(--vui-font-2xs)]",
  list: "m-0 flex list-none flex-col p-0",
  row: "flex items-start gap-3 border-b border-[var(--border-subtle)] py-2 last:border-b-0",
  rowMain: "flex min-w-0 flex-1 flex-col gap-1",
  rowTop: "flex flex-wrap items-center gap-1.5",
  scope: "[font-size:var(--vui-font-xs)] font-[650] text-[var(--fg-primary)]",
  reasonLine: "flex min-w-0 flex-wrap items-center gap-1",
  reason: "min-w-0 truncate text-[var(--fg-secondary)] [font-size:var(--vui-font-xs)]",
  detailsToggle: "!h-6 !min-h-0 px-1.5 [font-size:var(--vui-font-xs)]",
  detail: "m-0 flex flex-col gap-1 rounded border border-[var(--border-subtle)] p-2",
  detailLine: "m-0 flex gap-2",
  detailLabel: "w-[52px] shrink-0 text-[var(--fg-tertiary)] [font-size:var(--vui-font-2xs)]",
  detailValue: "m-0 min-w-0 break-words text-[var(--fg-secondary)] [font-size:var(--vui-font-2xs)]",
  detailCode: "m-0 min-w-0 break-all font-mono text-[var(--fg-tertiary)] [font-size:var(--vui-font-2xs)]",
  rowAction: "flex shrink-0 flex-col items-end gap-1",
  actionConfirm: "flex items-center gap-1.5",
  actionWait: "py-1 text-right [font-size:var(--vui-font-2xs)] text-[var(--fg-tertiary)]",
  actionError: "max-w-[220px] text-right [font-size:var(--vui-font-2xs)] text-[var(--fg-danger)]",
  footer: "flex items-center",
  entryWrap: "flex items-center justify-end px-1 pb-1.5",
} as const;
