export default {
  root: "flex h-full min-h-0 flex-col overflow-hidden border-0 !rounded-none",
  header: "grid shrink-0 gap-2 border-b border-[var(--vui-border-subtle)] p-3",
  headingRow: "flex min-w-0 items-center justify-between gap-2",
  title: "m-0 truncate [font-size:var(--vui-font-sm)] font-[760] text-[var(--fg-primary)]",
  summaryGrid: "grid grid-cols-2 gap-1.5",
  summaryItem: "grid gap-0.5 rounded-[var(--radius-control)] bg-[var(--vui-control-muted)] px-2 py-1.5",
  summaryLabel: "[font-size:var(--vui-font-2xs)] text-[var(--fg-tertiary)]",
  summaryValue: "[font-size:var(--vui-font-xs)] font-[720] text-[var(--fg-primary)]",
  progressTrack: "h-1.5 overflow-hidden rounded-full bg-[var(--vui-control-muted)]",
  progressFill: "h-full rounded-full bg-[var(--fg-primary)] transition-[width] motion-reduce:transition-none",
  body: "min-h-0 flex-1 overflow-y-auto p-2 [scrollbar-gutter:stable]",
  stageList: "grid gap-2",
  stage: "grid gap-1.5",
  stageButton: "!w-full !justify-start !px-2 !py-2 text-left",
  stageButtonBody: "grid min-w-0 flex-1 gap-1",
  stageTopLine: "flex min-w-0 items-center justify-between gap-2",
  stageLabel: "min-w-0 truncate [font-size:var(--vui-font-xs)] font-[720] text-[var(--fg-primary)]",
  stageCount: "shrink-0 [font-size:var(--vui-font-2xs)] text-[var(--fg-tertiary)]",
  statusContent: "inline-flex min-w-0 items-center gap-1",
  nodes: "grid gap-1 border-l border-[var(--vui-border-subtle)] pl-2",
  nodeButton: "!min-h-7 !w-full !justify-start !gap-1.5 !px-2 !py-1 text-left",
  nodeLabel: "min-w-0 flex-1 truncate [font-size:var(--vui-font-2xs)]",
  nodeStatus: "shrink-0 [font-size:10px] text-[var(--fg-tertiary)]",
  state: "grid min-h-40 content-center gap-2 px-3 py-6 text-center",
  stateIcon: "mx-auto text-[var(--fg-tertiary)]",
  stateTitle: "m-0 [font-size:var(--vui-font-sm)] font-[720] text-[var(--fg-primary)]",
  stateDetail: "m-0 [font-size:var(--vui-font-xs)] leading-relaxed text-[var(--fg-secondary)]",
  skeleton: "grid gap-2",
} as const;
