export default {
  root: "space-y-3 border-[var(--vui-border-subtle)] bg-[var(--vui-surface-inset)]",
  header: "flex min-w-0 items-baseline justify-between gap-3",
  title: "[font-size:var(--vui-font-xs)] font-semibold text-[var(--fg-primary)]",
  total: "shrink-0 [font-size:var(--vui-font-2xs)] font-semibold tabular-nums text-[var(--fg-secondary)]",
  presets: "flex flex-wrap gap-1.5",
  preset: "rounded-[var(--radius-control)]",
  stages: "space-y-1.5",
  stage: "grid grid-cols-[minmax(0,1fr)_7.25rem] items-center gap-2 rounded-[var(--radius-control)] border border-[var(--vui-border-subtle)] bg-[var(--vui-surface-card)] px-2.5 py-2",
  stageName: "min-w-0 truncate [font-size:var(--vui-font-xs)] font-medium text-[var(--fg-primary)]",
  stageInput: "h-8 text-right font-semibold tabular-nums",
  summary: "rounded-[var(--radius-control)] bg-[var(--vui-surface-row)] px-2.5 py-2 [font-size:var(--vui-font-2xs)] font-medium text-[var(--fg-secondary)]",
  advanced: "grid grid-cols-3 gap-2 max-[420px]:grid-cols-1",
  advancedField: "grid min-w-0 gap-1 [font-size:var(--vui-font-2xs)] font-medium text-[var(--fg-secondary)]",
  advancedInput: "h-8 text-right tabular-nums",
} as const;
