export default {
  root: "space-y-3 border-vui-border-subtle bg-vui-surface-inset",
  header: "flex min-w-0 items-baseline justify-between gap-3",
  title: "text-sm font-semibold text-vui-fg-primary",
  total: "shrink-0 text-xs font-semibold tabular-nums text-vui-fg-secondary",
  presets: "flex flex-wrap gap-1.5",
  preset: "rounded-[var(--radius-control)]",
  stages: "space-y-1.5",
  stage: "grid grid-cols-[minmax(0,1fr)_7.25rem] items-center gap-2 rounded-[var(--radius-control)] border border-vui-border-subtle bg-vui-surface-card px-2.5 py-2",
  stageName: "min-w-0 truncate text-sm font-medium text-vui-fg-primary",
  stageInput: "h-8 text-right font-semibold tabular-nums",
  summary: "rounded-[var(--radius-control)] bg-vui-surface-row px-2.5 py-2 text-xs font-medium text-vui-fg-secondary",
  advanced: "grid grid-cols-3 gap-2 max-[420px]:grid-cols-1",
  advancedField: "grid min-w-0 gap-1 text-xs font-medium text-vui-fg-secondary",
  advancedInput: "h-8 text-right tabular-nums",
} as const;
