export default {
  root: "flex h-full min-h-0 min-w-0 flex-1 flex-col overflow-hidden",
  body: "grid min-h-0 flex-1 content-start gap-2.5 overflow-auto p-2.5",
  currentCard: "grid gap-2",
  kicker: "[font-size:var(--vui-font-xs)] font-[700] tracking-[0.04em] text-[var(--fg-tertiary)]",
  currentTitle: "m-0 [font-size:var(--vui-font-sm)] font-[760] leading-[var(--vui-line-tight)] text-[var(--fg-primary)]",
  currentDetail: "m-0 [font-size:var(--vui-font-xs)] leading-[var(--vui-line-readable)] text-[var(--fg-secondary)]",
  currentMeta: "flex min-w-0 items-center justify-between gap-2",
  currentStage: "min-w-0 truncate [font-size:var(--vui-font-xs)] text-[var(--fg-tertiary)]",
  action: "w-full",
  stageSection: "grid gap-1.5",
  sectionLabel: "m-0 [font-size:var(--vui-font-xs)] font-[760] text-[var(--fg-primary)]",
  stageList: "grid gap-1.5",
  stageItem: "grid gap-1 rounded-[var(--radius-control)] border border-transparent px-2 py-1.5",
  stageItemActive: "grid gap-1 rounded-[var(--radius-control)] border border-[var(--vui-border-subtle)] bg-[var(--vui-surface-row)] px-2 py-1.5",
  stageHeader: "flex min-w-0 items-center justify-between gap-2",
  stageTitle: "min-w-0 truncate [font-size:var(--vui-font-sm)] font-[720] text-[var(--fg-primary)]",
  stageMeta: "shrink-0 [font-size:var(--vui-font-2xs)] text-[var(--fg-tertiary)]",
  nodeList: "grid gap-1",
  nodeItem: "!grid h-auto w-full min-w-0 grid-cols-[minmax(0,1fr)_auto] gap-x-2 gap-y-0.5 rounded-[var(--radius-control)] border border-transparent px-2 py-1.5 text-left !whitespace-normal",
  nodeItemSelected: "!grid h-auto w-full min-w-0 grid-cols-[minmax(0,1fr)_auto] gap-x-2 gap-y-0.5 rounded-[var(--radius-control)] border border-[var(--vui-border-subtle)] bg-[var(--vui-surface-row)] px-2 py-1.5 text-left !whitespace-normal",
  nodeCopy: "grid min-w-0 gap-0.5",
  nodeTitle: "min-w-0 truncate [font-size:var(--vui-font-xs)] font-[700] text-[var(--fg-primary)]",
  nodeDescription: "min-w-0 truncate [font-size:var(--vui-font-2xs)] leading-[var(--vui-line-readable)] text-[var(--fg-tertiary)]",
  empty: "m-0 rounded-[var(--radius-control)] border border-dashed border-[var(--vui-border-subtle)] px-2.5 py-2 [font-size:var(--vui-font-xs)] leading-[var(--vui-line-readable)] text-[var(--fg-tertiary)]",
} as const;
