export default {
  root: "flex flex-col gap-2 p-2",
  header: "flex flex-wrap items-start justify-between gap-2",
  titleBlock: "flex min-w-0 flex-col gap-0.5",
  title: "[font-size:var(--vui-font-sm)] text-[var(--fg-primary)]",
  summary: "text-[var(--fg-tertiary)] [font-size:var(--vui-font-2xs)]",
  headerActions: "flex shrink-0 flex-wrap items-center gap-1.5",
  empty: "min-h-0",
  groups: "flex min-h-0 flex-col gap-2",
  group: "flex flex-col gap-1",
  groupHeader: "flex items-center gap-1.5",
  list: "m-0 flex list-none flex-col gap-1 p-0",
  row: "m-0 p-0",
  rowButton: "w-full flex-col items-stretch gap-1 border border-[var(--border-subtle)] bg-[var(--bg-surface)] p-2 text-left",
  rowPlain: "flex flex-col gap-1 border border-[var(--border-subtle)] p-2",
  itemTop: "flex flex-wrap items-center gap-x-2 gap-y-0.5",
  kindLabel: "font-[650] [font-size:var(--vui-font-xs)] text-[var(--fg-primary)]",
  scope: "text-[var(--fg-secondary)] [font-size:var(--vui-font-2xs)]",
  lastSeen: "text-[var(--fg-tertiary)] [font-size:var(--vui-font-2xs)]",
  itemSummary: "text-[var(--fg-secondary)] [font-size:var(--vui-font-xs)]",
  recommendation: "text-[var(--fg-tertiary)] [font-size:var(--vui-font-2xs)]",
  cta: "flex flex-col gap-1 border border-[var(--border-strong)] bg-[var(--bg-subtle)] p-2",
  ctaAmount: "flex flex-wrap items-center gap-1.5",
  ctaAmountValue: "font-[650] [font-size:var(--vui-font-xs)] text-[var(--fg-primary)]",
  ctaConfirmHint: "text-[var(--fg-tertiary)] [font-size:var(--vui-font-2xs)]",
  ctaError: "text-[var(--fg-danger)] [font-size:var(--vui-font-2xs)]",
  footer: "flex items-center",
} as const;
