/**
 * Compose SC stage modules, board chrome, and inject controller after presentation.
 * Phase R2-k extract from useTeamsScComposition (behavior-conserving).
 */
import {
  buildSourceCollectionBoardChrome,
  buildSourceCollectionCompletionFlowNodes,
  buildSourceCollectionStageModules,
  buildSourceCollectionStandaloneStageModules,
} from "./source-collection/stageModulesModel";
import type { BuildSourceCollectionStageModulesInput } from "./source-collection/stageModulesModel";
import {
  createSourceCollectionController,
  createSourceCollectionStageAdvance,
} from "./source-collection/createSourceCollectionController";
import type { SourceCollectionControllerContext } from "./source-collection/createSourceCollectionController";
import { sourceCollectionPageSlice } from "./teamSourceCollectionShellModel";

/** Keys compose creates internally before feeding the builders/controller. */
type ComposeInternallyCreatedKeys =
  | "startSourceCollectionStageSessionTask"
  | "sourceCollectionStageModules"
  | "sourceCollectionBoardNextStepLabel"
  | "sourceCollectionPipelineGraphHealth"
  | "sourceCollectionFindingStageCompact";

export type ComposeSourceCollectionStageSurfacesInput = Omit<
  SourceCollectionControllerContext & BuildSourceCollectionStageModulesInput,
  ComposeInternallyCreatedKeys
>;

/** Merge presentation bag + shell helpers, then build stage chrome/controller surfaces. */
export function composeSourceCollectionStageSurfaces(input: ComposeSourceCollectionStageSurfacesInput) {
  const {
    lang,
    navigate,
    selectedTeam,
    selectedSourceCollectionRunEffectiveId,
    startSourceCollectionStageSessionTaskMutation,
    resetResearchProjectSourceCollectionMutation,
    setSourceCollectionStageAdvanceFailure,
    teamWorkflowKnowledgeIngestionStatus,
    sourceCollectionProjectedCollectedCount,
    sourceCollectionCollectedCount,
    sourceCollectionProjectedApprovedCount,
    sourceCollectionRunApprovedCount,
    sourceCollectionDisplayedCandidateCount,
    teamWorkflowCandidateGraph,
    candidateGraphNodeCount,
    sourceCollectionProjectedGraphNodeCount,
    candidateGraphEdgeCount,
    sourceCollectionProjectedGraphEdgeCount,
    sourceCollectionFindingDisplayState,
    sourceCollectionExtractionDisplayState,
    sourceCollectionRelationsDisplayState,
    sourceCollectionStageActionReadinessFor,
    openSourceCollectionStage,
    sourceCollectionStageAgentChatState,
    repairSelectedWorkflowTeamAgentsIfNeeded,
    knowledgeExpansionWorkflowTeamSelected,
    sourceCollectionCanStart,
    selectedTeamStartSourceCollectionPending,
    startSourceCollectionRunMutation,
    sourceCollectionDraft,
    researchStageCanLaunch,
    selectedTeamStartResearchStagePending,
    startResearchStageRoundMutation,
    sourceCollectionStageReturnRoute,
    sourceCollectionStageChatReturnLabel,
    sourceCollectionOwnerAgentId,
    sourceCollectionStageTaskClickKey,
    sourceCollectionStageFormalRetryRequired,
    selectedSourceCollectionRun,
    selectedSourceCollectionStageId,
    sourceCollectionProjectedCollectedCountLabel,
    sourceCollectionProjectedCollectedCountText,
    sourceCollectionProjectedAssessedCountText,
    sourceCollectionProjectedApprovedCountText,
    sourceCollectionProjectedCandidateCountLabel,
    sourceCollectionProjectedCandidateCountText,
    sourceCollectionCurrentCandidateCountText,
    sourceCollectionQueryCountLabel,
    sourceCollectionQueryCountText,
    sourceCollectionSearchOpenAssignmentCount,
    sourceCollectionPrimaryDataLoading,
    sourceCollectionFindingDisplayLoading,
    sourceCollectionExtractionDisplayLoading,
    sourceCollectionRelationsDisplayLoading,
    sourceCollectionIngestionDisplayLoading,
    sourceCollectionScreeningDataLoading,
    sourceCollectionLoadingSummary,
    sourceCollectionDataSyncText,
    sourceCollectionSourceSyncStatusText,
    sourceCollectionCandidateSyncStatusText,
    sourceCollectionCollectionProjection,
    sourceCollectionExtractionProjection,
    sourceCollectionGraphProjection,
    sourceCollectionMemoryProjection,
    sourceCollectionIngestionDisplayState,
    sourceCollectionSearchStepState,
    sourceCollectionExtractionStepState,
    sourceCollectionGraphStepState,
    sourceCollectionMemoryStepState,
    sourceCollectionExtractionNeedsAgentMaterial,
    sourceCollectionExtractionAgentMaterialCount,
    sourceCollectionExtractionCanProceedAfterExclusions,
    sourceCollectionExtractionProceedableSummary,
    sourceCollectionExtractionExcludedRecoveryState,
    sourceCollectionExtractionLoadingMetric,
    sourceCollectionExtractionMaterialMetric,
    sourceCollectionExtractionLoadingOutputLabel,
    sourceCollectionRunPendingScreeningCount,
    sourceCollectionRunPendingScreeningCountText,
    sourceCollectionProjectedFormalKnowledgeCount,
    sourceCollectionProjectedStewardPackCount,
    sourceCollectionPrecheckCandidateCount,
    knowledgePendingReviewCount,
    sourceCollectionIngestionReadyForExperiment,
    sourceCollectionCollectionActionLabel,
    sourceCollectionCandidateExtractionButtonText,
    sourceCollectionGraphActionLabel,
    sourceCollectionMemoryActionLabel,
    selectedTeamExtractSourceCollectionCandidatesPending,
    selectedTeamSourceQualityPending,
    sourceCollectionExperimentPlanningRoute,
    sourceCollectionStageFocusLabel,
    selectedTeamKnowledgeCollectionWorkRun,
    sourceCollectionStageLaunchActive,
    sourceCollectionStageLaunchSummary,
    sourceCollectionStageUserSummary,
    sourceCollectionStageDisplayState,
    sourceCollectionStageDisplayStatus,
    sourceCollectionStepStatusText,
    sourceCollectionStageActionLabelFor,
    sourceCollectionActionDisabledTitle,
    openSourceCollectionStageAgentChat,
    sourceCollectionFilteredRecords,
    sourceCollectionResultPageByStage,
    sourceCollectionStageAgentBindings,
    agentSummaryQuery,
    selectedTeamReturnRoute,
    sourceCollectionSourceFilter,
    setSourceCollectionSourceFilter,
    sourceCollectionLoadingText,
    setSourceCollectionResultPageByStage,
    sourceCollectionRuns,
    sourceCollectionHistoricalRunWithRecords,
    sourceCollectionShowingHistoricalRunByDefault,
    sourceCollectionRecordsDataLoading,
    sourceCollectionRunStatus,
    setSelectedSourceCollectionRunId,
    sourceCollectionRecords,
    sourceCollectionRawRecordCount,
    sourceCollectionRecordClickableSourceCount,
    sourceCollectionRecordLocalFileCount,
    setSourceCollectionDraft,
    sourceCollectionCollectedCountLabel,
    selectedSourceCollectionStorageArtifacts,
    sourceCollectionRecordFilterCounts,
    sourceCollectionCollectedCountText,
    sourceCollectionDisplayedCandidateCountText,
    sourceCollectionPendingCandidateImportCount,
    sourceCollectionRecordMissingSourceCount,
    sourceCollectionCandidatesByRecordId,
    selectedSourceCollectionCandidateId,
    selectSourceCollectionCandidate,
    selectedSourceCollectionStorageOpenPending,
    selectedSourceCollectionStorageOpenResult,
    selectedSourceCollectionStorageOpenError,
    openSourceCollectionStorageTarget,
    selectedSourceCollectionCandidate,
    selectedSourceCollectionCandidateTrace,
    selectedSourceCollectionCandidateStorageArtifacts,
    workflowQualityToneBound,
    sourceCollectionFilteredRunCandidates,
    sourceCollectionCountText,
    sourceCollectionFocusedPanelId,
    sourceCollectionExpandedPanelId,
    setSourceCollectionExpandedPanelId,
    sourceCollectionExtractionDefaultPanelId,
    sourceCollectionScreeningStepState,
    sourceCollectionDisplayedCandidateFilterCounts,
    sourceCollectionEvidenceReadyCandidateCount,
    sourceCollectionMissingEvidenceAnchorCount,
    runSourceCollectionScreeningAction,
    sourceCollectionScreeningDisabled,
    sourceCollectionScreeningActionReadiness,
    sourceCollectionScreeningButtonText,
    sourceCollectionScreeningButtonTitle,
    sourceCollectionScreeningStatusText,
    sourceCollectionQualityBatchFeedback,
    openSourceCollectionScreeningPanel,
    teamWorkflowSourceQualityStatus,
    teamWorkflowSourceQualityStatusQuery,
    workflowIngestionToneBound,
    selectedTeamSourceQualityError,
    selectedTeamAssessSourceQualityPending,
    assessSourceQualityMutation,
    selectedTeamPlanPaperNoteChunksPending,
    planPaperNoteChunksMutation,
    teamWorkflowCandidatesById,
    teamWorkflowCandidateGraphQuery,
    selectedTeamBuildCandidateGraphError,
    sourceCollectionCandidateFilterCounts,
    formalKnowledgeItemCount,
    sourceCollectionApprovedCount,
    teamWorkflowKnowledgeIngestionStatusQuery,
    sourceCollectionDraftHydratedRunIdRef,
    sourceCollectionDraftHydratedSearchPlanRef,
    activeSourceCollectionResearchProject,
    sourceCollectionFreshProjectDraftIdRef,
    sourceCollectionResetResearchProjectId,
    sourceCollectionResetAvailable,
    selectedResearchProjectSourceCollectionResetPending,
    selectedResearchProjectSourceCollectionResetError,
    sourceCollectionOutputDraft,
    setSourceCollectionOutputDraft,
    sourceCollectionAssignments,
    selectedSourceCollectionAssignment,
    canRecordSourceCollectionOutput,
    selectedTeamRecordSourceCollectionOutputPending,
    sourceCollectionOutputHasRecord,
    recordSourceCollectionOutputMutation,
    sourceCollectionControlPanelRef,
    sourceCollectionFindingRunOptions,
    sourceCollectionFindingAssignments,
    sourceCollectionFindingQueries,
    selectedTeamKnowledgeCollectionIngestResult,
    selectedTeamKnowledgeCollectionIngestError,
    selectedTeamStartSourceCollectionError,
    selectedTeamRecordSourceCollectionOutputError,
    selectedTeamExecuteSourceCollectionSearchError,
    selectedTeamStartSourceCollectionStageTaskError,
    sourceCollectionStageAdvanceFailure,
    selectedTeamExecuteSourceCollectionSearchResult,
    selectedTeamRecordSourceCollectionOutputResult,
    repairChallengeCupTeamAgentsMutation,
    sourceCollectionStagePrimaryAgentBinding,
    sourceCollectionCandidateProjection,
    sourceCollectionCandidateStepState,
    runSourceCollectionCandidateExtractionAction,
    sourceCollectionCandidateExtractionActionReadiness,
    sourceCollectionUnverifiableCandidateIds,
    excludeUnverifiableSourceCollectionCandidates,
    selectSourceCollectionStage,
  } = input;

  const startSourceCollectionStageSessionTask = createSourceCollectionStageAdvance({
    lang,
    navigate,
    selectedTeam,
    selectedSourceCollectionRunEffectiveId,
    startSourceCollectionStageSessionTaskMutation,
    resetResearchProjectSourceCollectionMutation,
    setSourceCollectionStageAdvanceFailure,
    teamWorkflowKnowledgeIngestionStatus,
    sourceCollectionProjectedCollectedCount,
    sourceCollectionCollectedCount,
    sourceCollectionProjectedApprovedCount,
    sourceCollectionRunApprovedCount,
    sourceCollectionDisplayedCandidateCount,
    teamWorkflowCandidateGraph,
    candidateGraphNodeCount,
    sourceCollectionProjectedGraphNodeCount,
    candidateGraphEdgeCount,
    sourceCollectionProjectedGraphEdgeCount,
    sourceCollectionFindingDisplayState,
    sourceCollectionExtractionDisplayState,
    sourceCollectionRelationsDisplayState,
    sourceCollectionStageActionReadinessFor,
    openSourceCollectionStage,
    sourceCollectionStageAgentChatState,
    repairSelectedWorkflowTeamAgentsIfNeeded,
    knowledgeExpansionWorkflowTeamSelected,
    sourceCollectionCanStart,
    selectedTeamStartSourceCollectionPending,
    startSourceCollectionRunMutation,
    sourceCollectionDraft,
    researchStageCanLaunch,
    selectedTeamStartResearchStagePending,
    startResearchStageRoundMutation,
    sourceCollectionStageReturnRoute,
    sourceCollectionStageChatReturnLabel,
    sourceCollectionOwnerAgentId,
    sourceCollectionStageTaskClickKey,
    sourceCollectionStageFormalRetryRequired,
  });

  const stageLang: "zh" | "en" = lang === "en" ? "en" : "zh";
  const sourceCollectionStageModules = buildSourceCollectionStageModules({
    lang: stageLang,
    selectedSourceCollectionRun,
    selectedSourceCollectionStageId,
    sourceCollectionProjectedCollectedCountLabel,
    sourceCollectionProjectedCollectedCountText,
    sourceCollectionProjectedCollectedCount,
    sourceCollectionProjectedAssessedCountText,
    sourceCollectionProjectedApprovedCountText,
    sourceCollectionProjectedCandidateCountLabel,
    sourceCollectionProjectedCandidateCountText,
    sourceCollectionCurrentCandidateCountText,
    sourceCollectionQueryCountLabel,
    sourceCollectionQueryCountText,
    sourceCollectionSearchOpenAssignmentCount,
    sourceCollectionPrimaryDataLoading,
    sourceCollectionFindingDisplayLoading,
    sourceCollectionExtractionDisplayLoading,
    sourceCollectionRelationsDisplayLoading,
    sourceCollectionIngestionDisplayLoading,
    sourceCollectionScreeningDataLoading,
    sourceCollectionLoadingSummary,
    sourceCollectionDataSyncText,
    sourceCollectionSourceSyncStatusText,
    sourceCollectionCandidateSyncStatusText,
    sourceCollectionCollectionProjection,
    sourceCollectionExtractionProjection,
    sourceCollectionGraphProjection,
    sourceCollectionMemoryProjection,
    sourceCollectionFindingDisplayState,
    sourceCollectionExtractionDisplayState,
    sourceCollectionRelationsDisplayState,
    sourceCollectionIngestionDisplayState,
    sourceCollectionSearchStepState,
    sourceCollectionExtractionStepState,
    sourceCollectionGraphStepState,
    sourceCollectionMemoryStepState,
    sourceCollectionExtractionNeedsAgentMaterial,
    sourceCollectionExtractionAgentMaterialCount,
    sourceCollectionExtractionCanProceedAfterExclusions,
    sourceCollectionExtractionProceedableSummary,
    sourceCollectionExtractionExcludedRecoveryState,
    sourceCollectionExtractionLoadingMetric,
    sourceCollectionExtractionMaterialMetric,
    sourceCollectionExtractionLoadingOutputLabel,
    sourceCollectionDisplayedCandidateCount,
    sourceCollectionRunPendingScreeningCount,
    sourceCollectionRunPendingScreeningCountText,
    sourceCollectionProjectedGraphNodeCount,
    sourceCollectionProjectedGraphEdgeCount,
    sourceCollectionProjectedFormalKnowledgeCount,
    sourceCollectionProjectedStewardPackCount,
    sourceCollectionPrecheckCandidateCount,
    knowledgePendingReviewCount,
    sourceCollectionIngestionReadyForExperiment,
    sourceCollectionCollectionActionLabel,
    sourceCollectionCandidateExtractionButtonText,
    sourceCollectionGraphActionLabel,
    sourceCollectionMemoryActionLabel,
    selectedTeamExtractSourceCollectionCandidatesPending,
    selectedTeamSourceQualityPending,
    sourceCollectionExperimentPlanningRoute,
    sourceCollectionStageFocusLabel,
    selectedTeamKnowledgeCollectionWorkRun,
    sourceCollectionStageLaunchActive,
    sourceCollectionStageLaunchSummary,
    sourceCollectionStageUserSummary,
    sourceCollectionStageDisplayState,
    sourceCollectionStageDisplayStatus,
    sourceCollectionStepStatusText,
    sourceCollectionStageActionLabelFor,
    sourceCollectionStageActionReadinessFor,
    sourceCollectionActionDisabledTitle,
    startSourceCollectionStageSessionTask,
    openSourceCollectionStage,
    openSourceCollectionStageAgentChat,
    navigate,
  });
  const sourceCollectionPipelineGraphHealth = {
    nodeCount: Number(
      teamWorkflowCandidateGraph?.summary?.nodeCount
      ?? candidateGraphNodeCount
      ?? sourceCollectionProjectedGraphNodeCount
      ?? 0,
    ),
    edgeCount: Number(
      teamWorkflowCandidateGraph?.summary?.edgeCount
      ?? candidateGraphEdgeCount
      ?? sourceCollectionProjectedGraphEdgeCount
      ?? 0,
    ),
    missingLinkCount: Number(
      teamWorkflowCandidateGraph?.summary?.missingLinkCount
      ?? teamWorkflowCandidateGraph?.missingLinks?.length
      ?? teamWorkflowKnowledgeIngestionStatus?.summary?.missingLinkCount
      ?? 0,
    ),
  };
  const { sourceCollectionBoardCurrentModule, sourceCollectionBoardNextStepLabel } = buildSourceCollectionBoardChrome({
    lang: stageLang,
    sourceCollectionStageModules,
    sourceCollectionStageFocusLabel,
    graphHealth: sourceCollectionPipelineGraphHealth,
  });
  const sourceCollectionCompletionFlow = selectedTeamKnowledgeCollectionWorkRun?.flowVisualization ?? null;
  const sourceCollectionCompletionFlowNodes = buildSourceCollectionCompletionFlowNodes({
    selectedTeamKnowledgeCollectionWorkRun,
    sourceCollectionStageModules,
  });
  const sourceCollectionStandaloneStageModules = buildSourceCollectionStandaloneStageModules({
    lang: stageLang,
    sourceCollectionStageModules,
    selectedSourceCollectionStageId,
    sourceCollectionStageActionReadinessFor,
    sourceCollectionActionDisabledTitle,
  });

  const sourceCollectionFindingHasVisibleRecords =
    sourceCollectionPageSlice(
      sourceCollectionFilteredRecords,
      sourceCollectionResultPageByStage.finding ?? 1,
    ).items.length > 0;
  const sourceCollectionFindingStageCompact =
    selectedSourceCollectionStageId === "finding"
    && !sourceCollectionFindingHasVisibleRecords;

  const {
    renderSourceCollectionStageAgents,
    renderSourceCollectionFilterBar,
    sourceCollectionPageItems,
    setSourceCollectionResultPage,
    stopSourceCollectionPaginationEvent,
    renderSourceCollectionPagination,
    renderSourceCollectionRunSwitcher,
    renderSourceCollectionConversation,
    renderSourceCollectionStorageActions,
    renderSourceCollectionSelectedSourcePanel,
    renderSourceCollectionScreeningPanel,
    renderSourceCollectionGraphPanel,
    renderSourceCollectionMemoryPanel,
    renderSourceCollectionModeFields,
    renderSourceCollectionSearchBrief,
    renderSourceCollectionManualWritebackPanel,
    renderSourceCollectionControlsPanel,
    renderSourceCollectionActiveStagePanel,
    runSourceCollectionProjectReset,
      renderStandalonePage: renderSourceCollectionStandalonePage,
  } = createSourceCollectionController({
    startSourceCollectionStageSessionTask,
    lang,
    sourceCollectionStageAgentBindings,
    agentSummaryQuery,
    selectedTeam,
    selectedTeamReturnRoute,
    sourceCollectionSourceFilter,
    setSourceCollectionSourceFilter,
    sourceCollectionLoadingText,
    sourceCollectionResultPageByStage,
    setSourceCollectionResultPageByStage,
    sourceCollectionRuns,
    selectedSourceCollectionRun,
    selectedSourceCollectionRunEffectiveId,
    sourceCollectionHistoricalRunWithRecords,
    sourceCollectionShowingHistoricalRunByDefault,
    sourceCollectionRecordsDataLoading,
    sourceCollectionRunStatus,
    setSelectedSourceCollectionRunId,
    sourceCollectionFilteredRecords,
    sourceCollectionRecords,
    sourceCollectionRawRecordCount,
    sourceCollectionRecordClickableSourceCount,
    sourceCollectionRecordLocalFileCount,
    sourceCollectionStageModules,
    sourceCollectionStageActionReadinessFor,
    sourceCollectionDraft,
    setSourceCollectionDraft,
    sourceCollectionCollectedCountLabel,
    selectedSourceCollectionStorageArtifacts,
    sourceCollectionBoardNextStepLabel,
    sourceCollectionActionDisabledTitle,
    sourceCollectionRecordFilterCounts,
    sourceCollectionCollectedCountText,
    sourceCollectionDisplayedCandidateCountText,
    sourceCollectionPendingCandidateImportCount,
    sourceCollectionRecordMissingSourceCount,
    sourceCollectionCandidatesByRecordId,
    selectedSourceCollectionCandidateId,
    selectSourceCollectionCandidate,
    selectedSourceCollectionStorageOpenPending,
    selectedSourceCollectionStorageOpenResult,
    selectedSourceCollectionStorageOpenError,
    openSourceCollectionStorageTarget,
    selectedSourceCollectionCandidate,
    selectedSourceCollectionCandidateTrace,
    selectedSourceCollectionCandidateStorageArtifacts,
    workflowQualityToneBound,
    sourceCollectionFilteredRunCandidates,
    sourceCollectionDisplayedCandidateCount,
    sourceCollectionCountText,
    sourceCollectionPrimaryDataLoading,
    sourceCollectionDataSyncText,
    sourceCollectionFocusedPanelId,
    selectedSourceCollectionStageId,
    sourceCollectionExpandedPanelId,
    setSourceCollectionExpandedPanelId,
    sourceCollectionExtractionDefaultPanelId,
    sourceCollectionScreeningStepState,
    sourceCollectionDisplayedCandidateFilterCounts,
    sourceCollectionProjectedAssessedCountText,
    sourceCollectionProjectedApprovedCountText,
    sourceCollectionRunPendingScreeningCountText,
    sourceCollectionEvidenceReadyCandidateCount,
    sourceCollectionMissingEvidenceAnchorCount,
    runSourceCollectionScreeningAction,
    sourceCollectionScreeningDisabled,
    selectedTeamSourceQualityPending,
    sourceCollectionScreeningActionReadiness,
    sourceCollectionScreeningButtonText,
    sourceCollectionScreeningButtonTitle,
    sourceCollectionScreeningStatusText,
    sourceCollectionQualityBatchFeedback,
    sourceCollectionExtractionNeedsAgentMaterial,
    sourceCollectionRunPendingScreeningCount,
    sourceCollectionProjectedApprovedCount,
    openSourceCollectionScreeningPanel,
    teamWorkflowSourceQualityStatus,
    teamWorkflowSourceQualityStatusQuery,
    workflowIngestionToneBound,
    selectedTeamSourceQualityError,
    selectedTeamAssessSourceQualityPending,
    assessSourceQualityMutation,
    selectedTeamPlanPaperNoteChunksPending,
    planPaperNoteChunksMutation,
    sourceCollectionGraphProjection,
    sourceCollectionProjectedGraphNodeCount,
    sourceCollectionProjectedGraphEdgeCount,
    teamWorkflowCandidateGraph,
    teamWorkflowCandidatesById,
    sourceCollectionGraphStepState,
    teamWorkflowCandidateGraphQuery,
    selectedTeamBuildCandidateGraphError,
    teamWorkflowKnowledgeIngestionStatus,
    sourceCollectionMemoryStepState,
    sourceCollectionCandidateFilterCounts,
    knowledgePendingReviewCount,
    formalKnowledgeItemCount,
    sourceCollectionApprovedCount,
    teamWorkflowKnowledgeIngestionStatusQuery,
    knowledgeExpansionWorkflowTeamSelected,
    sourceCollectionDraftHydratedRunIdRef,
    sourceCollectionDraftHydratedSearchPlanRef,
    activeSourceCollectionResearchProject,
    sourceCollectionFreshProjectDraftIdRef,
    sourceCollectionResetResearchProjectId,
    resetResearchProjectSourceCollectionMutation,
    sourceCollectionResetAvailable,
    selectedResearchProjectSourceCollectionResetPending,
    selectedResearchProjectSourceCollectionResetError,
    sourceCollectionCanStart,
    selectedTeamStartSourceCollectionPending,
    startSourceCollectionRunMutation,
    sourceCollectionOutputDraft,
    setSourceCollectionOutputDraft,
    sourceCollectionAssignments,
    selectedSourceCollectionAssignment,
    canRecordSourceCollectionOutput,
    selectedTeamRecordSourceCollectionOutputPending,
    sourceCollectionOutputHasRecord,
    recordSourceCollectionOutputMutation,
    sourceCollectionControlPanelRef,
    sourceCollectionStageFocusLabel,
    sourceCollectionFindingRunOptions,
    sourceCollectionFindingAssignments,
    sourceCollectionFindingQueries,
    selectedTeamKnowledgeCollectionIngestResult,
    selectedTeamKnowledgeCollectionIngestError,
    selectedTeamStartSourceCollectionError,
    selectedTeamRecordSourceCollectionOutputError,
    selectedTeamExecuteSourceCollectionSearchError,
    selectedTeamStartSourceCollectionStageTaskError,
    sourceCollectionStageAdvanceFailure,
    sourceCollectionPipelineGraphHealth,
    selectedTeamExecuteSourceCollectionSearchResult,
    selectedTeamRecordSourceCollectionOutputResult,
    candidateGraphNodeCount,
    candidateGraphEdgeCount,
    sourceCollectionPrecheckCandidateCount,
    sourceCollectionStageAgentChatState,
    repairChallengeCupTeamAgentsMutation,
    sourceCollectionStagePrimaryAgentBinding,
    openSourceCollectionStageAgentChat,
    sourceCollectionFindingStageCompact,
    sourceCollectionCandidateProjection,
    sourceCollectionRunApprovedCount,
    sourceCollectionCandidateStepState,
    sourceCollectionExtractionExcludedRecoveryState,
    runSourceCollectionCandidateExtractionAction,
    sourceCollectionCandidateExtractionActionReadiness,
    sourceCollectionExtractionCanProceedAfterExclusions,
    sourceCollectionUnverifiableCandidateIds,
    excludeUnverifiableSourceCollectionCandidates,
    selectSourceCollectionStage,
  });

  return {
    startSourceCollectionStageSessionTask,
    sourceCollectionStageModules,
    sourceCollectionPipelineGraphHealth,
    sourceCollectionBoardCurrentModule,
    sourceCollectionBoardNextStepLabel,
    sourceCollectionCompletionFlow,
    sourceCollectionCompletionFlowNodes,
    sourceCollectionStandaloneStageModules,
    sourceCollectionFindingStageCompact,
    renderSourceCollectionStageAgents,
    renderSourceCollectionFilterBar,
    sourceCollectionPageItems,
    setSourceCollectionResultPage,
    stopSourceCollectionPaginationEvent,
    renderSourceCollectionPagination,
    renderSourceCollectionRunSwitcher,
    renderSourceCollectionConversation,
    renderSourceCollectionStorageActions,
    renderSourceCollectionSelectedSourcePanel,
    renderSourceCollectionScreeningPanel,
    renderSourceCollectionGraphPanel,
    renderSourceCollectionMemoryPanel,
    renderSourceCollectionModeFields,
    renderSourceCollectionSearchBrief,
    renderSourceCollectionManualWritebackPanel,
    renderSourceCollectionControlsPanel,
    renderSourceCollectionActiveStagePanel,
    runSourceCollectionProjectReset,
    renderSourceCollectionStandalonePage,
  };
}
