export default {
  content: "flex w-full flex-col gap-3",
  templateList: "flex min-h-0 flex-col gap-2 overflow-y-auto",
  templateCard: "flex w-full cursor-pointer items-start gap-3 rounded-lg border border-[var(--vui-border-subtle)] bg-[var(--vui-surface-row)] p-3 text-left transition-colors hover:border-[var(--vui-border-strong)]",
  templateCardSelected: "border-[var(--vui-border-strong)] !bg-[var(--vui-surface-active)]",
  templateIcon: "mt-0.5 shrink-0 text-[var(--fg-secondary)]",
  templateCopy: "flex min-w-0 flex-col gap-0.5",
  templateName: "[font-size:var(--vui-font-sm)] font-medium text-[var(--fg-primary)]",
  templateMeta: "[font-size:var(--vui-font-2xs)] text-[var(--fg-secondary)]",
  nameField: "flex flex-col gap-1.5",
  nameLabel: "[font-size:var(--vui-font-xs)] font-medium text-[var(--fg-secondary)]",
  actions: "mt-2 flex items-center justify-end gap-2",
  backAction: "mr-auto",
  error: "text-[var(--fg-danger,crimson)] [font-size:var(--vui-font-xs)]",
  success: "flex items-start gap-3 py-2",
  successCopy: "flex flex-col gap-1",
  successActions: "mt-4 flex items-center justify-end gap-2",
  confirmation: "flex flex-col gap-2",
  confirmationActions: "mt-2 flex items-center justify-end gap-2",
} as const;
