export default {
  content: "flex w-full flex-col gap-4",
  lockedNotice:
    "rounded-md border border-[var(--vui-border-subtle)] bg-[var(--vui-surface-row)] px-3 py-2 [font-size:var(--vui-font-2xs)] text-[var(--fg-secondary)]",
  section: "flex min-w-0 flex-col gap-2",
  sectionHeading: "[font-size:var(--vui-font-xs)] font-semibold uppercase tracking-wide text-[var(--fg-secondary)]",
  sectionHint: "[font-size:var(--vui-font-2xs)] text-[var(--fg-secondary)]",
  fieldGrid: "grid grid-cols-1 gap-3",
  field: "flex flex-col gap-1.5",
  fieldLabel: "[font-size:var(--vui-font-xs)] font-medium text-[var(--fg-secondary)]",
  memberList: "flex min-w-0 flex-col gap-2",
  memberRow:
    "flex min-w-0 flex-col gap-2 rounded-lg border border-[var(--vui-border-subtle)] bg-[var(--vui-surface-row)] p-2.5",
  memberRowMarkedRemove: "opacity-60",
  memberMeta: "flex min-w-0 flex-wrap items-center gap-2",
  memberRole: "[font-size:var(--vui-font-xs)] font-medium text-[var(--fg-primary)]",
  memberAgent: "[font-size:var(--vui-font-2xs)] text-[var(--fg-secondary)]",
  memberActions: "flex min-w-0 flex-wrap items-center gap-2",
  rebindSelect: "min-w-[180px] flex-1",
  modelChip: "shrink-0",
  modelLink: "shrink-0",
  iconAction: "shrink-0",
  addRow: "flex min-w-0 flex-wrap items-center gap-2 rounded-lg border border-dashed border-[var(--vui-border-subtle)] p-2.5",
  addRoleInput: "w-[160px] shrink-0",
  addAgentSelect: "min-w-[180px] flex-1",
  roomRow: "flex min-w-0 flex-wrap items-center gap-2 rounded-lg border border-[var(--vui-border-subtle)] bg-[var(--vui-surface-row)] p-2.5",
  roomTitle: "[font-size:var(--vui-font-xs)] font-medium text-[var(--fg-primary)]",
  roomMeta: "[font-size:var(--vui-font-2xs)] text-[var(--fg-secondary)]",
  error: "text-[var(--fg-danger,crimson)] [font-size:var(--vui-font-xs)]",
  actions: "mt-1 flex items-center justify-end gap-2",
} as const;
