/** SC presentation derive phase (R2-s close-out). Core re-exports thin entry. */
/**
 * Source-collection presentation + action adapters for Teams.
 * Extracted from TeamsRoute (behavior-conserving).
 *
 * R02/R2-q: typed without @ts-nocheck — input bag lives in useSourceCollectionPresentationTypes.
 */
import { useMemo } from "react";

import {
  buildSourceCollectionWriteMutationSurface,
  buildTeamsRouteMutationSurface,
} from "./teamMutationSurface";
import {
  sourceCollectionActionDisabledTitle as sourceCollectionActionDisabledTitlePure,
  sourceCollectionActionReadinessOf,
  sourceCollectionLoadingChrome,
} from "./source-collection/actionChrome";
import {
  type SourceCollectionStepState,
} from "./source-collection/runModel";
import {
  type SourceCollectionActionReadiness,
  type SourceCollectionStageModuleId,
} from "./source-collection/stageProjection";
import {
  deriveSourceCollectionExtractionRecoveryMetrics,
  sourceCollectionStageFocusLabel as sourceCollectionStageFocusLabelPure,
} from "./source-collection/presentationExtractionMetrics";
import { buildSourceCollectionActionReadinessBag } from "./source-collection/presentationActionReadiness";
import {
  buildSourceCollectionPipelineStepStates,
  sourceCollectionStepStatusText as sourceCollectionStepStatusTextPure,
} from "./source-collection/presentationStepStates";
import { createSourceCollectionActionHandlers } from "./source-collection/createSourceCollectionActionHandlers";
import { createSourceCollectionStageActionHelpers } from "./source-collection/createSourceCollectionStageActionHelpers";
import { useSourceCollectionPresentationEffects } from "./source-collection/useSourceCollectionPresentationEffects";
import { deriveSourceCollectionListMetrics } from "./source-collection/deriveSourceCollectionListMetrics";
import { deriveSourceCollectionDisplayLabels } from "./source-collection/deriveSourceCollectionDisplayLabels";
import { deriveSourceCollectionDownstreamMetrics } from "./source-collection/deriveSourceCollectionDownstreamMetrics";
import { deriveSourceCollectionStageDisplaySurfaces } from "./source-collection/deriveSourceCollectionStageDisplaySurfaces";
import { deriveSourceCollectionSelectionPresentation } from "./source-collection/deriveSourceCollectionSelectionPresentation";
import { deriveSourceCollectionSummaryProjection } from "./source-collection/deriveSourceCollectionSummaryProjection";
import { deriveSourceCollectionOperationFlags } from "./source-collection/deriveSourceCollectionOperationFlags";
import { researchWorkspaceStageRoute } from "./researchWorkspaceModel";
import { RESEARCH_TEAM_ID } from "../TeamsRoute.canvasData";
import type { UseSourceCollectionPresentationInput } from "./useSourceCollectionPresentationTypes";


export function useSourceCollectionPresentationMid(input: UseSourceCollectionPresentationInput) {

  const teamWorkflowKnowledgeIngestionStatus = input.teamWorkflowKnowledgeIngestionStatusQuery.data ?? null;
  // R2-o: summary / stage cards / records projection pure.
  const summaryProjection = deriveSourceCollectionSummaryProjection({
    teamWorkflowCandidateGraphQueryData: input.teamWorkflowCandidateGraphQuery.data,
    sourceCollectionSummaryQueryData: input.sourceCollectionSummaryQuery.data,
    sourceCollectionRecordsQueryData: input.sourceCollectionRecordsQuery.data,
    sourceCollectionAssignmentsQueryData: input.sourceCollectionAssignmentsQuery.data,
    sourceCollectionRunStatusQueryData: input.sourceCollectionRunStatusQuery.data,
    selectedSourceCollectionRun: input.selectedSourceCollectionRun,
    selectedSourceCollectionRunEffectiveId: input.selectedSourceCollectionRunEffectiveId,
    researchStagePhases: input.researchStagePhases,
    researchStageRoundStatus: input.researchStageRoundStatus,
    aiSearchRunsQueryData: input.aiSearchRunsQuery.data,
    researchLoopTemplatesQueryData: input.researchLoopTemplatesQuery.data,
    researchLoopStatusQueryData: input.researchLoopStatusQuery.data,
    experimentPlanningStatusQueryData: input.experimentPlanningStatusQuery.data,
  });
  const {
    teamWorkflowCandidateGraph,
    sourceCollectionSummary,
    sourceCollectionSummaryRun,
    sourceCollectionSummaryRunId,
    sourceCollectionActionRunId,
    sourceCollectionPhaseCloseGate,
    sourceCollectionSummaryStageRound,
    sourceCollectionStageRound,
    sourceCollectionStageCards,
    sourceCollectionStageCardById,
    experimentPlanningStatus,
    sourceCollectionRecords,
    sourceCollectionAssignments,
    sourceCollectionRunStatus,
    sourceCollectionSearchPlanRef,
    aiSearchRuns,
    researchLoopTemplatesPayload,
    researchLoopStatus,
  } = summaryProjection;
  // Phase 4: team-scoped pending/error/result flags collapsed into one surface bag.
  const routeMutationSurface = buildTeamsRouteMutationSurface({
    teamId: input.selectedTeam?.teamId,
    resetResearchProjectSourceCollection: input.resetResearchProjectSourceCollectionMutation,
    startResearchStageRound: input.startResearchStageRoundMutation,
    createExperimentPlan: input.createExperimentPlanMutation,
    materializeEngineeringProxyHypothesis: input.materializeEngineeringProxyHypothesisMutation,
    completeScientificHypothesisFromDesign: input.completeScientificHypothesisFromDesignMutation,
    reviewExperimentHypothesis: input.reviewExperimentHypothesisMutation,
    createExperimentHypothesisRevision: input.createExperimentHypothesisRevisionMutation,
    freezeExperimentDesign: input.freezeExperimentDesignMutation,
    registerExperimentBaselineArtifact: input.registerExperimentBaselineArtifactMutation,
    runExperimentSmoke: input.runExperimentSmokeMutation,
    registerExperimentSmokeResult: input.registerExperimentSmokeResultMutation,
    registerExperimentFullRunResult: input.registerExperimentFullRunResultMutation,
    requestExperimentKnowledgeIngestion: input.requestExperimentKnowledgeIngestionMutation,
    createResearchLoop: input.createResearchLoopMutation,
    recordResearchLoopEvidence: input.recordResearchLoopEvidenceMutation,
    recordResearchLoopDecision: input.recordResearchLoopDecisionMutation,
    startSourceCollectionRun: input.startSourceCollectionRunMutation,
    startSourceCollectionStageSessionTask: input.startSourceCollectionStageSessionTaskMutation,
    recordSourceCollectionOutput: input.recordSourceCollectionOutputMutation,
    executeSourceCollectionSearch: input.executeSourceCollectionSearchMutation,
    extractSourceCollectionCandidates: input.extractSourceCollectionCandidatesMutation,
    openSourceCollectionStorage: input.openSourceCollectionStorageMutation,
    startAiSearchRun: input.startAiSearchRunMutation,
    researchStageProjectAgentStarting: input.researchStageProjectAgentTasks.isStarting,
    researchStageProjectAgentError: input.researchStageProjectAgentTasks.error,
    selectedSourceCollectionRunEffectiveId: input.selectedSourceCollectionRunEffectiveId,
  });
  const {
    selectedResearchProjectSourceCollectionResetPending,
    selectedResearchProjectSourceCollectionResetError,
    selectedTeamStartResearchStagePending,
    selectedTeamStartResearchStageError,
    selectedTeamStartResearchStageResult,
    selectedTeamCreateExperimentPlanPending,
    selectedTeamCreateExperimentPlanError,
    selectedTeamCreateExperimentPlanResult,
    selectedTeamMaterializeEngineeringProxyPending,
    selectedTeamMaterializeEngineeringProxyError,
    selectedTeamCompleteScientificHypothesisCandidateId,
    selectedTeamCompleteScientificHypothesisError,
    selectedTeamReviewExperimentHypothesisCandidateId,
    selectedTeamReviewExperimentHypothesisError,
    selectedTeamCreateExperimentHypothesisRevisionCandidateId,
    selectedTeamCreateExperimentHypothesisRevisionError,
    selectedTeamFreezeExperimentDesignPending,
    selectedTeamFreezeExperimentDesignError,
    selectedTeamFreezeExperimentDesignResult,
    selectedTeamRegisterExperimentBaselineArtifactPending,
    selectedTeamRegisterExperimentBaselineArtifactError,
    selectedTeamRegisterExperimentBaselineArtifactResult,
    selectedTeamRunExperimentSmokePending,
    selectedTeamRunExperimentSmokeError,
    selectedTeamRunExperimentSmokeResult,
    selectedTeamRegisterExperimentSmokeResultPending,
    selectedTeamRegisterExperimentSmokeResultError,
    selectedTeamRegisterExperimentSmokeResultResult,
    selectedTeamRegisterExperimentFullRunResultPending,
    selectedTeamRegisterExperimentFullRunResultError,
    selectedTeamRegisterExperimentFullRunResultResult,
    selectedTeamRequestExperimentKnowledgeIngestionPending,
    selectedTeamRequestExperimentKnowledgeIngestionError,
    selectedTeamRequestExperimentKnowledgeIngestionResult,
    selectedTeamCreateResearchLoopPending,
    selectedTeamCreateResearchLoopError,
    selectedTeamCreateResearchLoopResult,
    selectedTeamRecordResearchLoopEvidencePending,
    selectedTeamRecordResearchLoopEvidenceError,
    selectedTeamRecordResearchLoopEvidenceResult,
    selectedTeamRecordResearchLoopDecisionPending,
    selectedTeamRecordResearchLoopDecisionError,
    selectedTeamRecordResearchLoopDecisionResult,
    selectedTeamStartSourceCollectionPending,
    selectedTeamStartSourceCollectionError,
    selectedTeamStartSourceCollectionResult,
    selectedTeamStartSourceCollectionStageTaskPending,
    selectedTeamStartSourceCollectionStageTaskError,
    sourceCollectionStageSessionTaskPendingStageId,
    selectedTeamRecordSourceCollectionOutputPending,
    selectedTeamRecordSourceCollectionOutputError,
    selectedTeamRecordSourceCollectionOutputResult,
    selectedTeamExecuteSourceCollectionSearchPending,
    selectedTeamExecuteSourceCollectionSearchError,
    selectedTeamExecuteSourceCollectionSearchResult,
    selectedTeamExtractSourceCollectionCandidatesPending,
    selectedTeamExtractSourceCollectionCandidatesError,
    selectedTeamExtractSourceCollectionCandidatesResult,
    selectedSourceCollectionStorageOpenPending,
    selectedSourceCollectionStorageOpenResult,
    selectedSourceCollectionStorageOpenError,
    selectedTeamStartAiSearchPending,
    selectedTeamStartAiSearchError,
    selectedTeamStartAiSearchResult,
  } = routeMutationSurface;
  const latestAiSearchRun = selectedTeamStartAiSearchResult ?? aiSearchRuns[0] ?? null;
  const aiSearchRunCanStart = Boolean(input.selectedTeam?.teamId && input.aiSearchRunTopic.trim() && !selectedTeamStartAiSearchPending);
  // R2-n: finding options / prompt-cache / search selection / candidate maps.
  const selectionPresentation = deriveSourceCollectionSelectionPresentation({
    lang: input.lang,
    teamId: input.selectedTeam?.teamId || "",
    effectiveTeamId: input.effectiveTeamId,
    sourceCollectionRuns: input.sourceCollectionRuns,
    sourceCollectionAssignments,
    sourceCollectionOutputDraft: input.sourceCollectionOutputDraft,
    sourceCollectionDraft: input.sourceCollectionDraft,
    activeSourceCollectionResearchProjectId: input.activeSourceCollectionResearchProjectId,
    selectedSourceCollectionRun: input.selectedSourceCollectionRun,
    sourceCollectionSearchPlanRef,
    selectedTeamStartSourceCollectionResult,
    selectedTeamStartResearchStageResult,
    selectedTeamExecuteSourceCollectionSearchResult,
    runtimeSummaryData: input.runtimeSummaryQuery.data,
    selectedSourceCollectionRunEffectiveId: input.selectedSourceCollectionRunEffectiveId,
    sourceCollectionSummary,
    teamWorkflowCandidates: input.teamWorkflowCandidates,
    selectedSourceCollectionCandidateId: input.selectedSourceCollectionCandidateId,
  });
  const {
    selectedSourceCollectionAssignment,
    selectedSourceCollectionQueries,
    sourceCollectionFindingRunOptions,
    sourceCollectionFindingAssignments,
    sourceCollectionFindingQueries,
    sourceCollectionCanStart,
    researchStageCanLaunch,
    sourceCollectionResetResearchProjectId,
    sourceCollectionResetAvailable,
    sourceCollectionPromptCachePolicy,
    sourceCollectionPromptCachePolicyRef,
    sourceCollectionPromptCacheStatus,
    sourceCollectionPromptCacheMode,
    sourceCollectionPromptCacheRequirement,
    sourceCollectionOutputHasRecord,
    selectedTeamInitialSourceCollectionSearchResult,
    selectedSourceCollectionSearchExecutionResult,
    selectedSourceCollectionSearchAccepted,
    runtimeSourceCollectionActiveWorkRun,
    summarySourceCollectionActiveWorkRun,
    selectedSourceCollectionActiveWorkRun,
    sourceCollectionSummaryStorageArtifacts,
    selectedSourceCollectionStorageArtifacts,
    sourceManifestCandidates,
    teamWorkflowCandidatesById,
    sourceCollectionRunCandidates,
    selectedSourceCollectionCandidate,
    selectedSourceCollectionCandidateTrace,
    selectedSourceCollectionCandidateRunId,
    selectedSourceCollectionCandidateStorageArtifacts,
  } = selectionPresentation;
  useSourceCollectionPresentationEffects({
    queryClient: input.queryClient,
    pageVisible: input.pageVisible,
    researchWorkflowTeamSelected: input.researchWorkflowTeamSelected,
    selectedTeamId: input.selectedTeam?.teamId || "",
    selectedSourceCollectionRunEffectiveId: input.selectedSourceCollectionRunEffectiveId,
    requestedSourceCollectionStage: input.requestedSourceCollectionStage,
    setSourceCollectionStageSyncUntilMs: input.setSourceCollectionStageSyncUntilMs,
    selectedSourceCollectionSearchAccepted,
    selectedSourceCollectionCandidateId: input.selectedSourceCollectionCandidateId,
    sourceManifestCandidates,
    setSelectedSourceCollectionCandidateId: input.setSelectedSourceCollectionCandidateId,
  });

  const sourceCollectionSummaryCounts = sourceCollectionSummary?.summary ?? {};
  const listMetrics = deriveSourceCollectionListMetrics({
    lang: input.lang,
    researchWorkflowTeamSelected: input.researchWorkflowTeamSelected,
    selectedSourceCollectionRunEffectiveId: input.selectedSourceCollectionRunEffectiveId,
    sourceCollectionSourceFilter: input.sourceCollectionSourceFilter,
    sourceCollectionRecords,
    sourceCollectionAssignments,
    sourceCollectionRunStatus,
    sourceCollectionSummaryCounts,
    sourceCollectionRecordsQuery: input.sourceCollectionRecordsQuery,
    sourceCollectionAssignmentsQuery: input.sourceCollectionAssignmentsQuery,
    sourceCollectionRunStatusQuery: input.sourceCollectionRunStatusQuery,
    sourceCollectionSummaryQuery: input.sourceCollectionSummaryQuery,
    sourceCollectionRunsQuery: input.sourceCollectionRunsQuery,
    teamWorkflowCandidatesQuery: input.teamWorkflowCandidatesQuery,
    teamWorkflowSourceQualityStatusQuery: input.teamWorkflowSourceQualityStatusQuery,
    teamWorkflowCandidateGraphQuery: input.teamWorkflowCandidateGraphQuery,
    teamWorkflowKnowledgeIngestionStatusQuery: input.teamWorkflowKnowledgeIngestionStatusQuery,
    teamWorkflowSourceQualityStatus: input.teamWorkflowSourceQualityStatus,
    teamWorkflowCandidateListEnabled: input.teamWorkflowCandidateListEnabled,
    sourceCollectionNeedsCandidateList: input.sourceCollectionNeedsCandidateList,
    sourceCollectionFindingDetailsVisible: input.sourceCollectionFindingDetailsVisible,
    sourceCollectionWorkspaceSelected: input.sourceCollectionWorkspaceSelected,
    teamWorkflowSourceQualityEnabled: input.teamWorkflowSourceQualityEnabled,
    teamWorkflowGraphEnabled: input.teamWorkflowGraphEnabled,
    teamWorkflowKnowledgeIngestionEnabled: input.teamWorkflowKnowledgeIngestionEnabled,
    sourceCollectionRunCandidates,
    sourceCollectionStageCardById,
    sourceCollectionStageRound,
    sourceCollectionSearchPlanRef,
    selectedTeamStartSourceCollectionResult,
  });
  const {
    sourceCollectionRunSummary,
    sourceCollectionOpenAssignments,
    sourceCollectionOpenAssignmentCount,
    sourceCollectionSearchOpenAssignmentCount,
    sourceCollectionDownstreamOpenAssignmentCount,
    sourceCollectionCandidatesByRecordId,
    sourceCollectionRecordProvenances,
    sourceCollectionRecordSourceCategories,
    sourceCollectionFilteredRecords,
    sourceCollectionRunCandidateSourceCategories,
    sourceCollectionFilteredRunCandidates,
    sourceCollectionRawRecordCount,
    sourceCollectionRecordClickableSourceCount,
    sourceCollectionRecordLocalFileCount,
    sourceCollectionRecordMissingSourceCount,
    sourceCollectionRunCandidateCount,
    sourceCollectionRecordFilterCounts,
    sourceCollectionCandidateFilterCounts,
    sourceCollectionReviewableRunCandidates,
    sourceCollectionRunReviewableCandidateCount,
    sourceCollectionRunAssessedCount,
    sourceCollectionRunApprovedCount,
    sourceCollectionRunNeedsRevisionCount,
    sourceCollectionEvidenceLedgerSummaries,
    sourceCollectionEvidenceReadyCandidateCount,
    sourceCollectionMissingEvidenceAnchorCount,
    sourceCollectionCollectedCount,
    sourceCollectionRunSummaryHasRecordCount,
    sourceCollectionSummaryHasRecordCount,
    sourceCollectionRunSummaryHasAssignmentCounts,
    sourceCollectionCandidateListDataLoading,
    sourceCollectionRecordsDataLoading,
    sourceCollectionAssignmentsDataLoading,
    sourceCollectionCollectionProjection,
    sourceCollectionExtractionProjection,
    sourceCollectionCandidateProjection,
    sourceCollectionScreeningProjection,
    sourceCollectionGraphProjection,
    sourceCollectionMemoryProjection,
    sourceCollectionExcludedSourceCount,
    sourceCollectionStageSummaryCandidateCount,
    sourceCollectionCandidateProjectionFallbackCount,
    sourceCollectionProjectedCollectedCount,
    sourceCollectionProjectedCandidateCount,
    sourceCollectionProjectedAssessedCount,
    sourceCollectionProjectedApprovedCount,
    sourceCollectionDisplayedCandidateCount,
    sourceCollectionQueryCount,
    sourceCollectionPrimaryDataLoading,
    sourceCollectionSourceQualityLoading,
    sourceCollectionGraphDataLoading,
    sourceCollectionKnowledgeIngestionDataLoading,
    sourceCollectionActionInitialDataPending,
    sourceCollectionActionDataError,
    sourceCollectionSourceQualityDataError,
    sourceCollectionGraphDataError,
    sourceCollectionKnowledgeIngestionDataError,
    sourceCollectionScreeningDataLoading,
  } = listMetrics;

  const {
    loadingText: sourceCollectionLoadingText,
    dataSyncText: sourceCollectionDataSyncText,
    loadingSummary: sourceCollectionLoadingSummary,
    actionLoadingReason: sourceCollectionActionLoadingReason,
    actionErrorReason: sourceCollectionActionErrorReason,
    actionNoRunReason: sourceCollectionActionNoRunReason,
    actionNoInputReason: sourceCollectionActionNoInputReason,
    actionBusyReason: sourceCollectionActionBusyReason,
  } = sourceCollectionLoadingChrome(input.lang);
  const sourceCollectionActionReadiness = sourceCollectionActionReadinessOf;
  const sourceCollectionActionDisabledTitle = sourceCollectionActionDisabledTitlePure;
  // R2-m: count/label texts live in deriveSourceCollectionDisplayLabels (pure).
  const displayLabels = deriveSourceCollectionDisplayLabels({
    lang: input.lang,
    loadingText: sourceCollectionLoadingText,
    dataSyncText: sourceCollectionDataSyncText,
    recordsDataLoading: sourceCollectionRecordsDataLoading,
    assignmentsDataLoading: sourceCollectionAssignmentsDataLoading,
    primaryDataLoading: sourceCollectionPrimaryDataLoading,
    screeningDataLoading: sourceCollectionScreeningDataLoading,
    collectedCount: sourceCollectionCollectedCount,
    projectedCollectedCount: sourceCollectionProjectedCollectedCount,
    searchOpenAssignmentCount: sourceCollectionSearchOpenAssignmentCount,
    downstreamOpenAssignmentCount: sourceCollectionDownstreamOpenAssignmentCount,
    queryCount: sourceCollectionQueryCount,
    assignmentsLength: sourceCollectionAssignments.length,
    searchPlanQueryCount: (sourceCollectionSearchPlanRef as { queryCount?: number } | null | undefined)?.queryCount,
    startResultSearchPlanQueryCount: selectedTeamStartSourceCollectionResult?.searchPlan?.queryCount,
    displayedCandidateCount: sourceCollectionDisplayedCandidateCount,
    projectedCandidateCount: sourceCollectionProjectedCandidateCount,
    projectedAssessedCount: sourceCollectionProjectedAssessedCount,
    projectedApprovedCount: sourceCollectionProjectedApprovedCount,
    runReviewableCandidateCount: sourceCollectionRunReviewableCandidateCount,
    runCandidateCount: sourceCollectionRunCandidateCount,
    runAssessedCount: sourceCollectionRunAssessedCount,
    candidateProjection: sourceCollectionCandidateProjection,
    candidateFilterCounts: sourceCollectionCandidateFilterCounts,
  });
  const {
    sourceCollectionCountText,
    sourceCollectionCountWithUnit,
    sourceCollectionCollectedCountText,
    sourceCollectionProjectedCollectedCountText,
    sourceCollectionSearchOpenAssignmentCountText,
    sourceCollectionDownstreamOpenAssignmentCountText,
    sourceCollectionQueryDataLoading,
    sourceCollectionQueryCountText,
    sourceCollectionCollectedCountLabel,
    sourceCollectionProjectedCollectedCountLabel,
    sourceCollectionSearchOpenAssignmentCountLabel,
    sourceCollectionDownstreamOpenAssignmentCountLabel,
    sourceCollectionQueryCountLabel,
    sourceCollectionCollectedRunSummaryText,
    sourceCollectionAssignmentRunSummaryText,
    sourceCollectionDisplayedCandidateCountText,
    sourceCollectionProjectedCandidateCountText,
    sourceCollectionCoverageBoundCandidateCount,
    sourceCollectionCurrentCandidateCount,
    sourceCollectionCurrentCandidateCountText,
    sourceCollectionProjectedCandidateCountLabel,
    sourceCollectionProjectedAssessedCountText,
    sourceCollectionProjectedApprovedCountText,
    sourceCollectionDisplayedCandidateFilterCounts,
    sourceCollectionRunPendingScreeningCount,
    sourceCollectionRunPendingScreeningCountText,
  } = displayLabels;
  // F3: extraction recovery + stage focus pure metrics (presentationExtractionMetrics).
  const {
    recoveryCoverage: sourceCollectionExtractionRecoveryCoverage,
    recoveryClosure: sourceCollectionExtractionRecoveryClosure,
    sourceVerificationCount: sourceCollectionExtractionSourceVerificationCount,
    unverifiableCandidateIds: sourceCollectionUnverifiableCandidateIds,
    missingEvidenceAnchorCount: sourceCollectionExtractionMissingEvidenceAnchorCount,
    agentMaterialCount: sourceCollectionExtractionAgentMaterialCount,
    needsAgentMaterial: sourceCollectionExtractionNeedsAgentMaterial,
    recoveryMissingCount: sourceCollectionExtractionRecoveryMissingCount,
    excludedRecoveryState: sourceCollectionExtractionExcludedRecoveryState,
    canProceedAfterExclusions: sourceCollectionExtractionCanProceedAfterExclusions,
    proceedableSummary: sourceCollectionExtractionProceedableSummary,
    pendingCandidateImportCount: sourceCollectionPendingCandidateImportCount,
  } = useMemo(
    () => deriveSourceCollectionExtractionRecoveryMetrics({
      lang: input.lang,
      candidateProjection: sourceCollectionCandidateProjection,
      reviewableRunCandidates: sourceCollectionReviewableRunCandidates,
      rawRecordCount: sourceCollectionRawRecordCount,
      displayedCandidateCount: sourceCollectionDisplayedCandidateCount,
      runNeedsRevisionCount: sourceCollectionRunNeedsRevisionCount,
      projectedApprovedCount: sourceCollectionProjectedApprovedCount,
      runPendingScreeningCount: sourceCollectionRunPendingScreeningCount,
      excludedSourceCount: sourceCollectionExcludedSourceCount,
      extractResult: selectedTeamExtractSourceCollectionCandidatesResult,
      hasCurrentCandidates: Boolean(input.teamWorkflowCandidatesQuery.data),
    }),
    [
      input.lang,
      sourceCollectionCandidateProjection,
      sourceCollectionReviewableRunCandidates,
      sourceCollectionRawRecordCount,
      sourceCollectionDisplayedCandidateCount,
      sourceCollectionRunNeedsRevisionCount,
      sourceCollectionProjectedApprovedCount,
      sourceCollectionRunPendingScreeningCount,
      sourceCollectionExcludedSourceCount,
      selectedTeamExtractSourceCollectionCandidatesResult,
      input.teamWorkflowCandidatesQuery.data,
    ],
  );

  const sourceCollectionStageFocusLabel = sourceCollectionStageFocusLabelPure({
    lang: input.lang,
    hasRun: Boolean(input.selectedSourceCollectionRun),
    searchOpenAssignmentCount: sourceCollectionSearchOpenAssignmentCount,
    downstreamOpenAssignmentCount: sourceCollectionDownstreamOpenAssignmentCount,
    runPendingScreeningCount: sourceCollectionRunPendingScreeningCount,
    displayedCandidateCount: sourceCollectionDisplayedCandidateCount,
  });
  const writeMutationSurface = buildSourceCollectionWriteMutationSurface({
    teamId: input.selectedTeam?.teamId,
    selectedSourceCollectionRunEffectiveId: input.selectedSourceCollectionRunEffectiveId,
    buildCandidateGraph: input.buildCandidateGraphMutation,
    runKnowledgeIngestionPrecheck: input.runKnowledgeIngestionPrecheckMutation,
    runKnowledgeCollectionCompletion: input.runKnowledgeCollectionCompletionMutation,
    planPaperNoteChunks: input.planPaperNoteChunksMutation,
    assessSourceQuality: input.assessSourceQualityMutation,
    assessSourceQualityBatch: input.assessSourceQualityBatchMutation,
    knowledgeIngestionActiveWorkRun: input.teamWorkflowKnowledgeIngestionStatusQuery.data?.activeWorkRun ?? null,
    knowledgeIngestionLatestWorkRun: input.teamWorkflowKnowledgeIngestionStatusQuery.data?.latestWorkRun ?? null,
    lang: input.lang,
  });
  const {
    selectedTeamBuildCandidateGraphPending,
    selectedTeamBuildCandidateGraphError,
    selectedTeamKnowledgePrecheckPending,
    selectedTeamKnowledgePrecheckError,
    selectedTeamKnowledgeIngestionActiveWorkRun,
    selectedTeamKnowledgeIngestionLatestWorkRun,
    selectedTeamKnowledgeCollectionWorkRun,
    selectedTeamKnowledgeCollectionSourceRunId,
    selectedTeamKnowledgeCollectionMatchesSelectedRun,
    selectedTeamKnowledgeCollectionWorkRunStatus,
    selectedTeamKnowledgeCollectionFlowStatus,
    selectedTeamKnowledgeCollectionCompleted,
    selectedTeamKnowledgeCollectionCompletedForSelectedRun,
    selectedTeamKnowledgeCollectionIngestPending,
    selectedTeamKnowledgeCollectionIngestError,
    selectedTeamKnowledgeCollectionIngestResult,
    selectedTeamPlanPaperNoteChunksPending,
    selectedTeamPlanPaperNoteChunksError,
    selectedTeamAssessSourceQualityPending,
    selectedTeamAssessSourceQualityError,
    selectedTeamAssessSourceQualityBatchPending,
    selectedTeamAssessSourceQualityBatchError,
    selectedTeamSourceQualityPending,
    selectedTeamSourceQualityError,
    selectedTeamSourceQualityBatchResult,
    sourceCollectionQualityBatchFeedback,
  } = writeMutationSurface;
  // R2-q: run/operation flags + display state pure.
  const {
    sourceCollectionRunStatusValue,
    sourceCollectionAcceptedBackgroundActive,
    canRecordSourceCollectionOutput,
    canExecuteSourceCollectionSearch,
    sourceCollectionAcceptedBackgroundFailed,
    sourceCollectionOperationFailed,
    sourceCollectionDisplayState,
  } = deriveSourceCollectionOperationFlags({
    lang: input.lang,
    runStatus: sourceCollectionRunStatus,
    selectedRunStatus: input.selectedSourceCollectionRun?.status,
    selectedSourceCollectionSearchAccepted,
    selectedSourceCollectionActiveWorkRun,
    teamId: input.selectedTeam?.teamId,
    selectedSourceCollectionRunEffectiveId: input.selectedSourceCollectionRunEffectiveId,
    outputAssignmentId: input.sourceCollectionOutputDraft.assignmentId,
    selectedAssignmentId: selectedSourceCollectionAssignment?.assignmentId,
    sourceCollectionOutputHasRecord,
    selectedTeamRecordSourceCollectionOutputPending,
    sourceCollectionAssignmentsDataLoading,
    sourceCollectionActionDataError,
    sourceCollectionSearchOpenAssignmentCount,
    selectedTeamExecuteSourceCollectionSearchPending,
    selectedTeamStartResearchStageError,
    selectedTeamStartSourceCollectionError,
    selectedTeamExecuteSourceCollectionSearchError,
    selectedTeamExtractSourceCollectionCandidatesError,
    selectedTeamRecordSourceCollectionOutputError,
    selectedTeamSourceQualityError,
    selectedTeamBuildCandidateGraphError,
    selectedTeamKnowledgePrecheckError,
    selectedTeamKnowledgeCollectionIngestError,
    selectedTeamStartSourceCollectionStageTaskError,
    selectedTeamStartResearchStagePending,
    selectedTeamStartSourceCollectionPending,
    selectedTeamStartSourceCollectionStageTaskPending,
    selectedTeamExtractSourceCollectionCandidatesPending,
    selectedTeamSourceQualityPending,
    selectedTeamBuildCandidateGraphPending,
    selectedTeamKnowledgePrecheckPending,
    selectedTeamKnowledgeCollectionIngestPending,
    hasRun: Boolean(input.selectedSourceCollectionRun),
    searchOpenAssignmentCount: sourceCollectionSearchOpenAssignmentCount,
    downstreamOpenAssignmentCount: sourceCollectionDownstreamOpenAssignmentCount,
    pendingScreeningCount: sourceCollectionRunPendingScreeningCount,
    rawRecordCount: sourceCollectionRawRecordCount,
    candidateCount: sourceCollectionDisplayedCandidateCount,
  });
  // R2-m: graph/memory/ingest pure metrics.
  const downstreamMetrics = deriveSourceCollectionDownstreamMetrics({
    teamWorkflowSourceQualityStatus: input.teamWorkflowSourceQualityStatus,
    sourceCollectionSummaryCounts,
    teamWorkflowCandidateGraph,
    teamWorkflowKnowledgeIngestionStatus,
    graphProjection: sourceCollectionGraphProjection,
    memoryProjection: sourceCollectionMemoryProjection,
    runApprovedCount: sourceCollectionRunApprovedCount,
    displayedCandidateCount: sourceCollectionDisplayedCandidateCount,
  });
  const {
    sourceCollectionApprovedCount,
    candidateGraphNodeCount,
    candidateGraphEdgeCount,
    knowledgeStewardPackCount,
    knowledgePendingReviewCount,
    formalKnowledgeItemCount,
    sourceCollectionProjectedGraphNodeCount,
    sourceCollectionProjectedGraphEdgeCount,
    sourceCollectionProjectedStewardPackCount,
    sourceCollectionProjectedFormalKnowledgeCount,
    sourceCollectionDefaultKnowledgeBaseId,
    sourceCollectionPrecheckCandidateCount,
    sourceCollectionIngestCandidateCount,
    sourceCollectionCanBuildGraph,
  } = downstreamMetrics;
  // F3: stage action readiness + button chrome in presentationActionReadiness.
  const {
    searchActionReadiness: sourceCollectionSearchActionReadiness,
    candidateExtractionActionReadiness: sourceCollectionCandidateExtractionActionReadiness,
    screeningActionReadiness: sourceCollectionScreeningActionReadiness,
    graphActionReadiness: sourceCollectionGraphActionReadiness,
    memoryActionReadiness: sourceCollectionMemoryActionReadiness,
    completionActionReadiness: sourceCollectionCompletionActionReadiness,
    loopStartReadiness: sourceCollectionLoopStartReadiness,
    loopActionReadiness: sourceCollectionLoopActionReadiness,
    loopStartsNewRun: sourceCollectionLoopStartsNewRun,
    memoryActionDisabled: sourceCollectionMemoryActionDisabled,
    memoryActionLabel: sourceCollectionMemoryActionLabel,
    completionActionDisabled: sourceCollectionCompletionActionDisabled,
    completionActionLabel: sourceCollectionCompletionActionLabel,
    loopActionDisabled: sourceCollectionLoopActionDisabled,
    loopActionLabel: sourceCollectionLoopActionLabel,
    graphActionDisabled: sourceCollectionGraphActionDisabled,
    graphActionLabel: sourceCollectionGraphActionLabel,
    screeningDisabled: sourceCollectionScreeningDisabled,
    screeningForceRescreen: sourceCollectionScreeningForceRescreen,
    screeningButtonText: sourceCollectionScreeningButtonText,
    screeningButtonTitle: sourceCollectionScreeningButtonTitle,
    screeningStatusText: sourceCollectionScreeningStatusText,
    candidateExtractionButtonText: sourceCollectionCandidateExtractionButtonText,
  } = buildSourceCollectionActionReadinessBag({
    lang: input.lang,
    reasons: {
      actionLoadingReason: sourceCollectionActionLoadingReason,
      actionErrorReason: sourceCollectionActionErrorReason,
      actionNoRunReason: sourceCollectionActionNoRunReason,
      actionNoInputReason: sourceCollectionActionNoInputReason,
      actionBusyReason: sourceCollectionActionBusyReason,
    },
    loadingText: sourceCollectionLoadingText,
    hasTeam: Boolean(input.selectedTeam?.teamId),
    hasRun: Boolean(input.selectedSourceCollectionRunEffectiveId),
    actionRunId: sourceCollectionActionRunId,
    canExecuteSearch: canExecuteSourceCollectionSearch,
    canStart: sourceCollectionCanStart,
    canBuildGraph: sourceCollectionCanBuildGraph,
    assignmentsDataLoading: sourceCollectionAssignmentsDataLoading,
    recordsDataLoading: sourceCollectionRecordsDataLoading,
    primaryDataLoading: sourceCollectionPrimaryDataLoading,
    sourceQualityLoading: sourceCollectionSourceQualityLoading,
    graphDataLoading: sourceCollectionGraphDataLoading,
    knowledgeIngestionDataLoading: sourceCollectionKnowledgeIngestionDataLoading,
    actionInitialDataPending: sourceCollectionActionInitialDataPending,
    actionDataError: sourceCollectionActionDataError,
    sourceQualityDataError: sourceCollectionSourceQualityDataError,
    graphDataError: sourceCollectionGraphDataError,
    knowledgeIngestionDataError: sourceCollectionKnowledgeIngestionDataError,
    rawRecordCount: sourceCollectionRawRecordCount,
    displayedCandidateCount: sourceCollectionDisplayedCandidateCount,
    runPendingScreeningCount: sourceCollectionRunPendingScreeningCount,
    runPendingScreeningCountText: sourceCollectionRunPendingScreeningCountText,
    pendingCandidateImportCount: sourceCollectionPendingCandidateImportCount,
    searchOpenAssignmentCount: sourceCollectionSearchOpenAssignmentCount,
    ingestCandidateCount: sourceCollectionIngestCandidateCount,
    precheckCandidateCount: sourceCollectionPrecheckCandidateCount,
    runApprovedCount: sourceCollectionRunApprovedCount,
    acceptedBackgroundActive: sourceCollectionAcceptedBackgroundActive,
    operationFailed: sourceCollectionOperationFailed,
    extractionNeedsAgentMaterial: sourceCollectionExtractionNeedsAgentMaterial,
    searchPending: selectedTeamExecuteSourceCollectionSearchPending,
    extractPending: selectedTeamExtractSourceCollectionCandidatesPending,
    sourceQualityPending: selectedTeamSourceQualityPending,
    graphPending: selectedTeamBuildCandidateGraphPending,
    knowledgeIngestPending: selectedTeamKnowledgeCollectionIngestPending,
    startRunPending: selectedTeamStartSourceCollectionPending,
    knowledgeCompletedForSelectedRun: selectedTeamKnowledgeCollectionCompletedForSelectedRun,
  });
  // F3: mutation action handlers + stage display helpers.
  return {
    teamWorkflowKnowledgeIngestionStatus,
    summaryProjection,
    routeMutationSurface,
    latestAiSearchRun,
    aiSearchRunCanStart,
    selectionPresentation,
    sourceCollectionSummaryCounts,
    listMetrics,
    sourceCollectionActionReadiness,
    sourceCollectionActionDisabledTitle,
    displayLabels,
    sourceCollectionStageFocusLabel,
    writeMutationSurface,
    downstreamMetrics,
    teamWorkflowCandidateGraph,
    sourceCollectionSummary,
    sourceCollectionSummaryRun,
    sourceCollectionSummaryRunId,
    sourceCollectionActionRunId,
    sourceCollectionPhaseCloseGate,
    sourceCollectionSummaryStageRound,
    sourceCollectionStageRound,
    sourceCollectionStageCards,
    sourceCollectionStageCardById,
    experimentPlanningStatus,
    sourceCollectionRecords,
    sourceCollectionAssignments,
    sourceCollectionRunStatus,
    sourceCollectionSearchPlanRef,
    aiSearchRuns,
    researchLoopTemplatesPayload,
    researchLoopStatus,
    selectedResearchProjectSourceCollectionResetPending,
    selectedResearchProjectSourceCollectionResetError,
    selectedTeamStartResearchStagePending,
    selectedTeamStartResearchStageError,
    selectedTeamStartResearchStageResult,
    selectedTeamCreateExperimentPlanPending,
    selectedTeamCreateExperimentPlanError,
    selectedTeamCreateExperimentPlanResult,
    selectedTeamMaterializeEngineeringProxyPending,
    selectedTeamMaterializeEngineeringProxyError,
    selectedTeamCompleteScientificHypothesisCandidateId,
    selectedTeamCompleteScientificHypothesisError,
    selectedTeamReviewExperimentHypothesisCandidateId,
    selectedTeamReviewExperimentHypothesisError,
    selectedTeamCreateExperimentHypothesisRevisionCandidateId,
    selectedTeamCreateExperimentHypothesisRevisionError,
    selectedTeamFreezeExperimentDesignPending,
    selectedTeamFreezeExperimentDesignError,
    selectedTeamFreezeExperimentDesignResult,
    selectedTeamRegisterExperimentBaselineArtifactPending,
    selectedTeamRegisterExperimentBaselineArtifactError,
    selectedTeamRegisterExperimentBaselineArtifactResult,
    selectedTeamRunExperimentSmokePending,
    selectedTeamRunExperimentSmokeError,
    selectedTeamRunExperimentSmokeResult,
    selectedTeamRegisterExperimentSmokeResultPending,
    selectedTeamRegisterExperimentSmokeResultError,
    selectedTeamRegisterExperimentSmokeResultResult,
    selectedTeamRegisterExperimentFullRunResultPending,
    selectedTeamRegisterExperimentFullRunResultError,
    selectedTeamRegisterExperimentFullRunResultResult,
    selectedTeamRequestExperimentKnowledgeIngestionPending,
    selectedTeamRequestExperimentKnowledgeIngestionError,
    selectedTeamRequestExperimentKnowledgeIngestionResult,
    selectedTeamCreateResearchLoopPending,
    selectedTeamCreateResearchLoopError,
    selectedTeamCreateResearchLoopResult,
    selectedTeamRecordResearchLoopEvidencePending,
    selectedTeamRecordResearchLoopEvidenceError,
    selectedTeamRecordResearchLoopEvidenceResult,
    selectedTeamRecordResearchLoopDecisionPending,
    selectedTeamRecordResearchLoopDecisionError,
    selectedTeamRecordResearchLoopDecisionResult,
    selectedTeamStartSourceCollectionPending,
    selectedTeamStartSourceCollectionError,
    selectedTeamStartSourceCollectionResult,
    selectedTeamStartSourceCollectionStageTaskPending,
    selectedTeamStartSourceCollectionStageTaskError,
    sourceCollectionStageSessionTaskPendingStageId,
    selectedTeamRecordSourceCollectionOutputPending,
    selectedTeamRecordSourceCollectionOutputError,
    selectedTeamRecordSourceCollectionOutputResult,
    selectedTeamExecuteSourceCollectionSearchPending,
    selectedTeamExecuteSourceCollectionSearchError,
    selectedTeamExecuteSourceCollectionSearchResult,
    selectedTeamExtractSourceCollectionCandidatesPending,
    selectedTeamExtractSourceCollectionCandidatesError,
    selectedTeamExtractSourceCollectionCandidatesResult,
    selectedSourceCollectionStorageOpenPending,
    selectedSourceCollectionStorageOpenResult,
    selectedSourceCollectionStorageOpenError,
    selectedTeamStartAiSearchPending,
    selectedTeamStartAiSearchError,
    selectedTeamStartAiSearchResult,
    selectedSourceCollectionAssignment,
    selectedSourceCollectionQueries,
    sourceCollectionFindingRunOptions,
    sourceCollectionFindingAssignments,
    sourceCollectionFindingQueries,
    sourceCollectionCanStart,
    researchStageCanLaunch,
    sourceCollectionResetResearchProjectId,
    sourceCollectionResetAvailable,
    sourceCollectionPromptCachePolicy,
    sourceCollectionPromptCachePolicyRef,
    sourceCollectionPromptCacheStatus,
    sourceCollectionPromptCacheMode,
    sourceCollectionPromptCacheRequirement,
    sourceCollectionOutputHasRecord,
    selectedTeamInitialSourceCollectionSearchResult,
    selectedSourceCollectionSearchExecutionResult,
    selectedSourceCollectionSearchAccepted,
    runtimeSourceCollectionActiveWorkRun,
    summarySourceCollectionActiveWorkRun,
    selectedSourceCollectionActiveWorkRun,
    sourceCollectionSummaryStorageArtifacts,
    selectedSourceCollectionStorageArtifacts,
    sourceManifestCandidates,
    teamWorkflowCandidatesById,
    sourceCollectionRunCandidates,
    selectedSourceCollectionCandidate,
    selectedSourceCollectionCandidateTrace,
    selectedSourceCollectionCandidateRunId,
    selectedSourceCollectionCandidateStorageArtifacts,
    sourceCollectionRunSummary,
    sourceCollectionOpenAssignments,
    sourceCollectionOpenAssignmentCount,
    sourceCollectionSearchOpenAssignmentCount,
    sourceCollectionDownstreamOpenAssignmentCount,
    sourceCollectionCandidatesByRecordId,
    sourceCollectionRecordProvenances,
    sourceCollectionRecordSourceCategories,
    sourceCollectionFilteredRecords,
    sourceCollectionRunCandidateSourceCategories,
    sourceCollectionFilteredRunCandidates,
    sourceCollectionRawRecordCount,
    sourceCollectionRecordClickableSourceCount,
    sourceCollectionRecordLocalFileCount,
    sourceCollectionRecordMissingSourceCount,
    sourceCollectionRunCandidateCount,
    sourceCollectionRecordFilterCounts,
    sourceCollectionCandidateFilterCounts,
    sourceCollectionReviewableRunCandidates,
    sourceCollectionRunReviewableCandidateCount,
    sourceCollectionRunAssessedCount,
    sourceCollectionRunApprovedCount,
    sourceCollectionRunNeedsRevisionCount,
    sourceCollectionEvidenceLedgerSummaries,
    sourceCollectionEvidenceReadyCandidateCount,
    sourceCollectionMissingEvidenceAnchorCount,
    sourceCollectionCollectedCount,
    sourceCollectionRunSummaryHasRecordCount,
    sourceCollectionSummaryHasRecordCount,
    sourceCollectionRunSummaryHasAssignmentCounts,
    sourceCollectionCandidateListDataLoading,
    sourceCollectionRecordsDataLoading,
    sourceCollectionAssignmentsDataLoading,
    sourceCollectionCollectionProjection,
    sourceCollectionExtractionProjection,
    sourceCollectionCandidateProjection,
    sourceCollectionScreeningProjection,
    sourceCollectionGraphProjection,
    sourceCollectionMemoryProjection,
    sourceCollectionExcludedSourceCount,
    sourceCollectionStageSummaryCandidateCount,
    sourceCollectionCandidateProjectionFallbackCount,
    sourceCollectionProjectedCollectedCount,
    sourceCollectionProjectedCandidateCount,
    sourceCollectionProjectedAssessedCount,
    sourceCollectionProjectedApprovedCount,
    sourceCollectionDisplayedCandidateCount,
    sourceCollectionQueryCount,
    sourceCollectionPrimaryDataLoading,
    sourceCollectionSourceQualityLoading,
    sourceCollectionGraphDataLoading,
    sourceCollectionKnowledgeIngestionDataLoading,
    sourceCollectionActionInitialDataPending,
    sourceCollectionActionDataError,
    sourceCollectionSourceQualityDataError,
    sourceCollectionGraphDataError,
    sourceCollectionKnowledgeIngestionDataError,
    sourceCollectionScreeningDataLoading,
    sourceCollectionLoadingText,
    sourceCollectionDataSyncText,
    sourceCollectionLoadingSummary,
    sourceCollectionActionLoadingReason,
    sourceCollectionActionErrorReason,
    sourceCollectionActionNoRunReason,
    sourceCollectionActionNoInputReason,
    sourceCollectionActionBusyReason,
    sourceCollectionCountText,
    sourceCollectionCountWithUnit,
    sourceCollectionCollectedCountText,
    sourceCollectionProjectedCollectedCountText,
    sourceCollectionSearchOpenAssignmentCountText,
    sourceCollectionDownstreamOpenAssignmentCountText,
    sourceCollectionQueryDataLoading,
    sourceCollectionQueryCountText,
    sourceCollectionCollectedCountLabel,
    sourceCollectionProjectedCollectedCountLabel,
    sourceCollectionSearchOpenAssignmentCountLabel,
    sourceCollectionDownstreamOpenAssignmentCountLabel,
    sourceCollectionQueryCountLabel,
    sourceCollectionCollectedRunSummaryText,
    sourceCollectionAssignmentRunSummaryText,
    sourceCollectionDisplayedCandidateCountText,
    sourceCollectionProjectedCandidateCountText,
    sourceCollectionCoverageBoundCandidateCount,
    sourceCollectionCurrentCandidateCount,
    sourceCollectionCurrentCandidateCountText,
    sourceCollectionProjectedCandidateCountLabel,
    sourceCollectionProjectedAssessedCountText,
    sourceCollectionProjectedApprovedCountText,
    sourceCollectionDisplayedCandidateFilterCounts,
    sourceCollectionRunPendingScreeningCount,
    sourceCollectionRunPendingScreeningCountText,
    sourceCollectionExtractionRecoveryCoverage,
    sourceCollectionExtractionRecoveryClosure,
    sourceCollectionExtractionSourceVerificationCount,
    sourceCollectionUnverifiableCandidateIds,
    sourceCollectionExtractionMissingEvidenceAnchorCount,
    sourceCollectionExtractionAgentMaterialCount,
    sourceCollectionExtractionNeedsAgentMaterial,
    sourceCollectionExtractionRecoveryMissingCount,
    sourceCollectionExtractionExcludedRecoveryState,
    sourceCollectionExtractionCanProceedAfterExclusions,
    sourceCollectionExtractionProceedableSummary,
    sourceCollectionPendingCandidateImportCount,
    selectedTeamBuildCandidateGraphPending,
    selectedTeamBuildCandidateGraphError,
    selectedTeamKnowledgePrecheckPending,
    selectedTeamKnowledgePrecheckError,
    selectedTeamKnowledgeIngestionActiveWorkRun,
    selectedTeamKnowledgeIngestionLatestWorkRun,
    selectedTeamKnowledgeCollectionWorkRun,
    selectedTeamKnowledgeCollectionSourceRunId,
    selectedTeamKnowledgeCollectionMatchesSelectedRun,
    selectedTeamKnowledgeCollectionWorkRunStatus,
    selectedTeamKnowledgeCollectionFlowStatus,
    selectedTeamKnowledgeCollectionCompleted,
    selectedTeamKnowledgeCollectionCompletedForSelectedRun,
    selectedTeamKnowledgeCollectionIngestPending,
    selectedTeamKnowledgeCollectionIngestError,
    selectedTeamKnowledgeCollectionIngestResult,
    selectedTeamPlanPaperNoteChunksPending,
    selectedTeamPlanPaperNoteChunksError,
    selectedTeamAssessSourceQualityPending,
    selectedTeamAssessSourceQualityError,
    selectedTeamAssessSourceQualityBatchPending,
    selectedTeamAssessSourceQualityBatchError,
    selectedTeamSourceQualityPending,
    selectedTeamSourceQualityError,
    selectedTeamSourceQualityBatchResult,
    sourceCollectionQualityBatchFeedback,
    sourceCollectionRunStatusValue,
    sourceCollectionAcceptedBackgroundActive,
    canRecordSourceCollectionOutput,
    canExecuteSourceCollectionSearch,
    sourceCollectionAcceptedBackgroundFailed,
    sourceCollectionOperationFailed,
    sourceCollectionDisplayState,
    sourceCollectionApprovedCount,
    candidateGraphNodeCount,
    candidateGraphEdgeCount,
    knowledgeStewardPackCount,
    knowledgePendingReviewCount,
    formalKnowledgeItemCount,
    sourceCollectionProjectedGraphNodeCount,
    sourceCollectionProjectedGraphEdgeCount,
    sourceCollectionProjectedStewardPackCount,
    sourceCollectionProjectedFormalKnowledgeCount,
    sourceCollectionDefaultKnowledgeBaseId,
    sourceCollectionPrecheckCandidateCount,
    sourceCollectionIngestCandidateCount,
    sourceCollectionCanBuildGraph,
    sourceCollectionSearchActionReadiness,
    sourceCollectionCandidateExtractionActionReadiness,
    sourceCollectionScreeningActionReadiness,
    sourceCollectionGraphActionReadiness,
    sourceCollectionMemoryActionReadiness,
    sourceCollectionCompletionActionReadiness,
    sourceCollectionLoopStartReadiness,
    sourceCollectionLoopActionReadiness,
    sourceCollectionLoopStartsNewRun,
    sourceCollectionMemoryActionDisabled,
    sourceCollectionMemoryActionLabel,
    sourceCollectionCompletionActionDisabled,
    sourceCollectionCompletionActionLabel,
    sourceCollectionLoopActionDisabled,
    sourceCollectionLoopActionLabel,
    sourceCollectionGraphActionDisabled,
    sourceCollectionGraphActionLabel,
    sourceCollectionScreeningDisabled,
    sourceCollectionScreeningForceRescreen,
    sourceCollectionScreeningButtonText,
    sourceCollectionScreeningButtonTitle,
    sourceCollectionScreeningStatusText,
    sourceCollectionCandidateExtractionButtonText,
  };
}
