/** SC presentation wire/return phase (R2-s close-out). Core re-exports thin entry. */
/**
 * Source-collection presentation + action adapters for Teams.
 * Extracted from TeamsRoute (behavior-conserving).
 *
 * R02/R2-q: typed without @ts-nocheck — input bag lives in useSourceCollectionPresentationTypes.
 */
import { useMemo } from "react";

import {
  buildSourceCollectionWriteMutationSurface,
  buildTeamsRouteMutationSurface,
} from "./teamMutationSurface";
import {
  sourceCollectionActionDisabledTitle as sourceCollectionActionDisabledTitlePure,
  sourceCollectionActionReadinessOf,
  sourceCollectionLoadingChrome,
} from "./source-collection/actionChrome";
import {
  EMPTY_SOURCE_COLLECTION_DISPLAY_STATE,
  type SourceCollectionStepState,
} from "./source-collection/runModel";
import {
  type SourceCollectionActionReadiness,
  type SourceCollectionStageModuleId,
} from "./source-collection/stageProjection";
import {
  deriveSourceCollectionExtractionRecoveryMetrics,
  sourceCollectionStageFocusLabel as sourceCollectionStageFocusLabelPure,
} from "./source-collection/presentationExtractionMetrics";
import { buildSourceCollectionActionReadinessBag } from "./source-collection/presentationActionReadiness";
import {
  buildSourceCollectionPipelineStepStates,
  sourceCollectionStepStatusText as sourceCollectionStepStatusTextPure,
} from "./source-collection/presentationStepStates";
import { createSourceCollectionActionHandlers } from "./source-collection/createSourceCollectionActionHandlers";
import { createSourceCollectionStageActionHelpers } from "./source-collection/createSourceCollectionStageActionHelpers";
import { useSourceCollectionPresentationEffects } from "./source-collection/useSourceCollectionPresentationEffects";
import { deriveSourceCollectionListMetrics } from "./source-collection/deriveSourceCollectionListMetrics";
import { deriveSourceCollectionDisplayLabels } from "./source-collection/deriveSourceCollectionDisplayLabels";
import { deriveSourceCollectionDownstreamMetrics } from "./source-collection/deriveSourceCollectionDownstreamMetrics";
import { deriveSourceCollectionStageDisplaySurfaces } from "./source-collection/deriveSourceCollectionStageDisplaySurfaces";
import { deriveSourceCollectionSelectionPresentation } from "./source-collection/deriveSourceCollectionSelectionPresentation";
import { deriveSourceCollectionSummaryProjection } from "./source-collection/deriveSourceCollectionSummaryProjection";
import { deriveSourceCollectionOperationFlags } from "./source-collection/deriveSourceCollectionOperationFlags";
import { researchWorkspaceStageRoute } from "./researchWorkspaceModel";
import { RESEARCH_TEAM_ID } from "../TeamsRoute.canvasData";
import type { UseSourceCollectionPresentationInput } from "./useSourceCollectionPresentationTypes";

export function useSourceCollectionPresentationTail(
  input: UseSourceCollectionPresentationInput,
  mid: ReturnType<typeof import("./useSourceCollectionPresentationMid").useSourceCollectionPresentationMid>,
) {
  const {
    teamWorkflowKnowledgeIngestionStatus,
    summaryProjection,
    routeMutationSurface,
    latestAiSearchRun,
    aiSearchRunCanStart,
    selectionPresentation,
    sourceCollectionSummaryCounts,
    listMetrics,
    sourceCollectionActionReadiness,
    sourceCollectionActionDisabledTitle,
    displayLabels,
    sourceCollectionStageFocusLabel,
    writeMutationSurface,
    downstreamMetrics,
    teamWorkflowCandidateGraph,
    sourceCollectionSummary,
    sourceCollectionSummaryRun,
    sourceCollectionSummaryRunId,
    sourceCollectionActionRunId,
    sourceCollectionPhaseCloseGate,
    sourceCollectionSummaryStageRound,
    sourceCollectionStageRound,
    sourceCollectionStageCards,
    sourceCollectionStageCardById,
    experimentPlanningStatus,
    sourceCollectionRecords,
    sourceCollectionAssignments,
    sourceCollectionRunStatus,
    sourceCollectionSearchPlanRef,
    aiSearchRuns,
    researchLoopTemplatesPayload,
    researchLoopStatus,
    selectedResearchProjectSourceCollectionResetPending,
    selectedResearchProjectSourceCollectionResetError,
    selectedTeamStartResearchStagePending,
    selectedTeamStartResearchStageError,
    selectedTeamStartResearchStageResult,
    selectedTeamCreateExperimentPlanPending,
    selectedTeamCreateExperimentPlanError,
    selectedTeamCreateExperimentPlanResult,
    selectedTeamMaterializeEngineeringProxyPending,
    selectedTeamMaterializeEngineeringProxyError,
    selectedTeamCompleteScientificHypothesisCandidateId,
    selectedTeamCompleteScientificHypothesisError,
    selectedTeamReviewExperimentHypothesisCandidateId,
    selectedTeamReviewExperimentHypothesisError,
    selectedTeamCreateExperimentHypothesisRevisionCandidateId,
    selectedTeamCreateExperimentHypothesisRevisionError,
    selectedTeamFreezeExperimentDesignPending,
    selectedTeamFreezeExperimentDesignError,
    selectedTeamFreezeExperimentDesignResult,
    selectedTeamRegisterExperimentBaselineArtifactPending,
    selectedTeamRegisterExperimentBaselineArtifactError,
    selectedTeamRegisterExperimentBaselineArtifactResult,
    selectedTeamRunExperimentSmokePending,
    selectedTeamRunExperimentSmokeError,
    selectedTeamRunExperimentSmokeResult,
    selectedTeamRegisterExperimentSmokeResultPending,
    selectedTeamRegisterExperimentSmokeResultError,
    selectedTeamRegisterExperimentSmokeResultResult,
    selectedTeamRegisterExperimentFullRunResultPending,
    selectedTeamRegisterExperimentFullRunResultError,
    selectedTeamRegisterExperimentFullRunResultResult,
    selectedTeamRequestExperimentKnowledgeIngestionPending,
    selectedTeamRequestExperimentKnowledgeIngestionError,
    selectedTeamRequestExperimentKnowledgeIngestionResult,
    selectedTeamCreateResearchLoopPending,
    selectedTeamCreateResearchLoopError,
    selectedTeamCreateResearchLoopResult,
    selectedTeamRecordResearchLoopEvidencePending,
    selectedTeamRecordResearchLoopEvidenceError,
    selectedTeamRecordResearchLoopEvidenceResult,
    selectedTeamRecordResearchLoopDecisionPending,
    selectedTeamRecordResearchLoopDecisionError,
    selectedTeamRecordResearchLoopDecisionResult,
    selectedTeamStartSourceCollectionPending,
    selectedTeamStartSourceCollectionError,
    selectedTeamStartSourceCollectionResult,
    selectedTeamStartSourceCollectionStageTaskPending,
    selectedTeamStartSourceCollectionStageTaskError,
    sourceCollectionStageSessionTaskPendingStageId,
    selectedTeamRecordSourceCollectionOutputPending,
    selectedTeamRecordSourceCollectionOutputError,
    selectedTeamRecordSourceCollectionOutputResult,
    selectedTeamExecuteSourceCollectionSearchPending,
    selectedTeamExecuteSourceCollectionSearchError,
    selectedTeamExecuteSourceCollectionSearchResult,
    selectedTeamExtractSourceCollectionCandidatesPending,
    selectedTeamExtractSourceCollectionCandidatesError,
    selectedTeamExtractSourceCollectionCandidatesResult,
    selectedSourceCollectionStorageOpenPending,
    selectedSourceCollectionStorageOpenResult,
    selectedSourceCollectionStorageOpenError,
    selectedTeamStartAiSearchPending,
    selectedTeamStartAiSearchError,
    selectedTeamStartAiSearchResult,
    selectedSourceCollectionAssignment,
    selectedSourceCollectionQueries,
    sourceCollectionFindingRunOptions,
    sourceCollectionFindingAssignments,
    sourceCollectionFindingQueries,
    sourceCollectionCanStart,
    researchStageCanLaunch,
    sourceCollectionResetResearchProjectId,
    sourceCollectionResetAvailable,
    sourceCollectionPromptCachePolicy,
    sourceCollectionPromptCachePolicyRef,
    sourceCollectionPromptCacheStatus,
    sourceCollectionPromptCacheMode,
    sourceCollectionPromptCacheRequirement,
    sourceCollectionOutputHasRecord,
    selectedTeamInitialSourceCollectionSearchResult,
    selectedSourceCollectionSearchExecutionResult,
    selectedSourceCollectionSearchAccepted,
    runtimeSourceCollectionActiveWorkRun,
    summarySourceCollectionActiveWorkRun,
    selectedSourceCollectionActiveWorkRun,
    sourceCollectionSummaryStorageArtifacts,
    selectedSourceCollectionStorageArtifacts,
    sourceManifestCandidates,
    teamWorkflowCandidatesById,
    sourceCollectionRunCandidates,
    selectedSourceCollectionCandidate,
    selectedSourceCollectionCandidateTrace,
    selectedSourceCollectionCandidateRunId,
    selectedSourceCollectionCandidateStorageArtifacts,
    sourceCollectionRunSummary,
    sourceCollectionOpenAssignments,
    sourceCollectionOpenAssignmentCount,
    sourceCollectionSearchOpenAssignmentCount,
    sourceCollectionDownstreamOpenAssignmentCount,
    sourceCollectionCandidatesByRecordId,
    sourceCollectionRecordProvenances,
    sourceCollectionRecordSourceCategories,
    sourceCollectionFilteredRecords,
    sourceCollectionRunCandidateSourceCategories,
    sourceCollectionFilteredRunCandidates,
    sourceCollectionRawRecordCount,
    sourceCollectionRecordClickableSourceCount,
    sourceCollectionRecordLocalFileCount,
    sourceCollectionRecordMissingSourceCount,
    sourceCollectionRunCandidateCount,
    sourceCollectionRecordFilterCounts,
    sourceCollectionCandidateFilterCounts,
    sourceCollectionReviewableRunCandidates,
    sourceCollectionRunReviewableCandidateCount,
    sourceCollectionRunAssessedCount,
    sourceCollectionRunApprovedCount,
    sourceCollectionRunNeedsRevisionCount,
    sourceCollectionEvidenceLedgerSummaries,
    sourceCollectionEvidenceReadyCandidateCount,
    sourceCollectionMissingEvidenceAnchorCount,
    sourceCollectionCollectedCount,
    sourceCollectionRunSummaryHasRecordCount,
    sourceCollectionSummaryHasRecordCount,
    sourceCollectionRunSummaryHasAssignmentCounts,
    sourceCollectionCandidateListDataLoading,
    sourceCollectionRecordsDataLoading,
    sourceCollectionAssignmentsDataLoading,
    sourceCollectionCollectionProjection,
    sourceCollectionExtractionProjection,
    sourceCollectionCandidateProjection,
    sourceCollectionScreeningProjection,
    sourceCollectionGraphProjection,
    sourceCollectionMemoryProjection,
    sourceCollectionExcludedSourceCount,
    sourceCollectionStageSummaryCandidateCount,
    sourceCollectionCandidateProjectionFallbackCount,
    sourceCollectionProjectedCollectedCount,
    sourceCollectionProjectedCandidateCount,
    sourceCollectionProjectedAssessedCount,
    sourceCollectionProjectedApprovedCount,
    sourceCollectionDisplayedCandidateCount,
    sourceCollectionQueryCount,
    sourceCollectionPrimaryDataLoading,
    sourceCollectionSourceQualityLoading,
    sourceCollectionGraphDataLoading,
    sourceCollectionKnowledgeIngestionDataLoading,
    sourceCollectionActionInitialDataPending,
    sourceCollectionActionDataError,
    sourceCollectionSourceQualityDataError,
    sourceCollectionGraphDataError,
    sourceCollectionKnowledgeIngestionDataError,
    sourceCollectionScreeningDataLoading,
    sourceCollectionLoadingText,
    sourceCollectionDataSyncText,
    sourceCollectionLoadingSummary,
    sourceCollectionActionLoadingReason,
    sourceCollectionActionErrorReason,
    sourceCollectionActionNoRunReason,
    sourceCollectionActionNoInputReason,
    sourceCollectionActionBusyReason,
    sourceCollectionCountText,
    sourceCollectionCountWithUnit,
    sourceCollectionCollectedCountText,
    sourceCollectionProjectedCollectedCountText,
    sourceCollectionSearchOpenAssignmentCountText,
    sourceCollectionDownstreamOpenAssignmentCountText,
    sourceCollectionQueryDataLoading,
    sourceCollectionQueryCountText,
    sourceCollectionCollectedCountLabel,
    sourceCollectionProjectedCollectedCountLabel,
    sourceCollectionSearchOpenAssignmentCountLabel,
    sourceCollectionDownstreamOpenAssignmentCountLabel,
    sourceCollectionQueryCountLabel,
    sourceCollectionCollectedRunSummaryText,
    sourceCollectionAssignmentRunSummaryText,
    sourceCollectionDisplayedCandidateCountText,
    sourceCollectionProjectedCandidateCountText,
    sourceCollectionCoverageBoundCandidateCount,
    sourceCollectionCurrentCandidateCount,
    sourceCollectionCurrentCandidateCountText,
    sourceCollectionProjectedCandidateCountLabel,
    sourceCollectionProjectedAssessedCountText,
    sourceCollectionProjectedApprovedCountText,
    sourceCollectionDisplayedCandidateFilterCounts,
    sourceCollectionRunPendingScreeningCount,
    sourceCollectionRunPendingScreeningCountText,
    sourceCollectionExtractionRecoveryCoverage,
    sourceCollectionExtractionRecoveryClosure,
    sourceCollectionExtractionSourceVerificationCount,
    sourceCollectionUnverifiableCandidateIds,
    sourceCollectionExtractionMissingEvidenceAnchorCount,
    sourceCollectionExtractionAgentMaterialCount,
    sourceCollectionExtractionNeedsAgentMaterial,
    sourceCollectionExtractionRecoveryMissingCount,
    sourceCollectionExtractionExcludedRecoveryState,
    sourceCollectionExtractionCanProceedAfterExclusions,
    sourceCollectionExtractionProceedableSummary,
    sourceCollectionPendingCandidateImportCount,
    selectedTeamBuildCandidateGraphPending,
    selectedTeamBuildCandidateGraphError,
    selectedTeamKnowledgePrecheckPending,
    selectedTeamKnowledgePrecheckError,
    selectedTeamKnowledgeIngestionActiveWorkRun,
    selectedTeamKnowledgeIngestionLatestWorkRun,
    selectedTeamKnowledgeCollectionWorkRun,
    selectedTeamKnowledgeCollectionSourceRunId,
    selectedTeamKnowledgeCollectionMatchesSelectedRun,
    selectedTeamKnowledgeCollectionWorkRunStatus,
    selectedTeamKnowledgeCollectionFlowStatus,
    selectedTeamKnowledgeCollectionCompleted,
    selectedTeamKnowledgeCollectionCompletedForSelectedRun,
    selectedTeamKnowledgeCollectionIngestPending,
    selectedTeamKnowledgeCollectionIngestError,
    selectedTeamKnowledgeCollectionIngestResult,
    selectedTeamPlanPaperNoteChunksPending,
    selectedTeamPlanPaperNoteChunksError,
    selectedTeamAssessSourceQualityPending,
    selectedTeamAssessSourceQualityError,
    selectedTeamAssessSourceQualityBatchPending,
    selectedTeamAssessSourceQualityBatchError,
    selectedTeamSourceQualityPending,
    selectedTeamSourceQualityError,
    selectedTeamSourceQualityBatchResult,
    sourceCollectionQualityBatchFeedback,
    sourceCollectionRunStatusValue,
    sourceCollectionAcceptedBackgroundActive,
    canRecordSourceCollectionOutput,
    canExecuteSourceCollectionSearch,
    sourceCollectionAcceptedBackgroundFailed,
    sourceCollectionOperationFailed,
    sourceCollectionDisplayState,
    sourceCollectionApprovedCount,
    candidateGraphNodeCount,
    candidateGraphEdgeCount,
    knowledgeStewardPackCount,
    knowledgePendingReviewCount,
    formalKnowledgeItemCount,
    sourceCollectionProjectedGraphNodeCount,
    sourceCollectionProjectedGraphEdgeCount,
    sourceCollectionProjectedStewardPackCount,
    sourceCollectionProjectedFormalKnowledgeCount,
    sourceCollectionDefaultKnowledgeBaseId,
    sourceCollectionPrecheckCandidateCount,
    sourceCollectionIngestCandidateCount,
    sourceCollectionCanBuildGraph,
    sourceCollectionSearchActionReadiness,
    sourceCollectionCandidateExtractionActionReadiness,
    sourceCollectionScreeningActionReadiness,
    sourceCollectionGraphActionReadiness,
    sourceCollectionMemoryActionReadiness,
    sourceCollectionCompletionActionReadiness,
    sourceCollectionLoopStartReadiness,
    sourceCollectionLoopActionReadiness,
    sourceCollectionLoopStartsNewRun,
    sourceCollectionMemoryActionDisabled,
    sourceCollectionMemoryActionLabel,
    sourceCollectionCompletionActionDisabled,
    sourceCollectionCompletionActionLabel,
    sourceCollectionLoopActionDisabled,
    sourceCollectionLoopActionLabel,
    sourceCollectionGraphActionDisabled,
    sourceCollectionGraphActionLabel,
    sourceCollectionScreeningDisabled,
    sourceCollectionScreeningForceRescreen,
    sourceCollectionScreeningButtonText,
    sourceCollectionScreeningButtonTitle,
    sourceCollectionScreeningStatusText,
    sourceCollectionCandidateExtractionButtonText
  } = mid;

  const actionHandlers = createSourceCollectionActionHandlers({
    lang: input.lang,
    selectedTeam: input.selectedTeam,
    selectedSourceCollectionRunEffectiveId: input.selectedSourceCollectionRunEffectiveId,
    openSourceCollectionStorageMutation: input.openSourceCollectionStorageMutation,
    setSelectedSourceCollectionCandidateId: input.setSelectedSourceCollectionCandidateId,
    setSelectedSourceCollectionStageId: input.setSelectedSourceCollectionStageId,
    sourceCollectionStandalone: input.sourceCollectionStandalone,
    searchParams: input.searchParams,
    setSearchParams: input.setSearchParams,
    setSourceCollectionFocusedPanelId: input.setSourceCollectionFocusedPanelId,
    setSourceCollectionExpandedPanelId: input.setSourceCollectionExpandedPanelId,
    sourceCollectionControlPanelRef: input.sourceCollectionControlPanelRef,
    scrollSourceCollectionPanelIntoViewRef: input.scrollSourceCollectionPanelIntoViewRef,
    sourceCollectionScreeningDisabled,
    sourceCollectionScreeningActionReadiness,
    sourceCollectionRunPendingScreeningCount,
    sourceCollectionDisplayedCandidateCount,
    assessSourceQualityBatchMutation: input.assessSourceQualityBatchMutation,
    sourceCollectionExtractorAgentId: input.sourceCollectionExtractorAgentId,
    selectedTeamSourceQualityPending,
    sourceCollectionUnverifiableCandidateIds,
    assessSourceQualityMutation: input.assessSourceQualityMutation,
    sourceCollectionCandidateExtractionActionReadiness,
    extractSourceCollectionCandidatesMutation: input.extractSourceCollectionCandidatesMutation,
    sourceCollectionPendingCandidateImportCount,
    sourceCollectionRawRecordCount,
    sourceCollectionGraphActionReadiness,
    buildCandidateGraphMutation: input.buildCandidateGraphMutation,
    sourceCollectionRelationMapperAgentId: input.sourceCollectionRelationMapperAgentId,
    sourceCollectionIngestCandidateCount,
    sourceCollectionRunApprovedCount,
    sourceCollectionIngestorAgentId: input.sourceCollectionIngestorAgentId,
    sourceCollectionDefaultKnowledgeBaseId,
    sourceCollectionDraft: input.sourceCollectionDraft,
    sourceCollectionSearchOpenAssignmentCount,
    sourceCollectionPrecheckCandidateCount,
    selectResearchWorkspaceView: input.selectResearchWorkspaceView,
    runKnowledgeCollectionCompletionMutation: input.runKnowledgeCollectionCompletionMutation,
    sourceCollectionCompletionActionReadiness,
    sourceCollectionActionRunId,
    sourceCollectionLoopActionReadiness,
    sourceCollectionLoopStartsNewRun,
    startSourceCollectionRunMutation: input.startSourceCollectionRunMutation,
    sourceCollectionSearchActionReadiness,
    selectedSourceCollectionAssignment,
    executeSourceCollectionSearchMutation: input.executeSourceCollectionSearchMutation,
    selectedSourceCollectionRun: input.selectedSourceCollectionRun,
    launchResearchStage: input.launchResearchStage,
    sourceCollectionStageWritebackSyncActive: input.sourceCollectionStageWritebackSyncActive,
    sourceCollectionStageCardById,
    sourceCollectionStageSessionTaskPendingStageId,
    sourceCollectionPendingStageTaskIds: input.sourceCollectionPendingStageTaskIds,
    selectedTeamStartResearchStagePending,
    selectedTeamStartSourceCollectionStageTaskPending,
    researchStageCanLaunch,
    sourceCollectionActionBusyReason,
    sourceCollectionActionNoInputReason,
    sourceCollectionAssignmentsDataLoading,
    sourceCollectionActionDataError,
    sourceCollectionActionLoadingReason,
    sourceCollectionActionErrorReason,
    selectedTeamExecuteSourceCollectionSearchPending,
    sourceCollectionAcceptedBackgroundActive,
    sourceCollectionActionReadiness,
    styles: input.styles,
  });
  const {
    openSourceCollectionStorageTarget,
    selectSourceCollectionCandidate,
    sourceCollectionCandidateCardKeyDown,
    sourceCollectionStageForPanel,
    selectSourceCollectionStage,
    openSourceCollectionStage,
    scrollSourceCollectionPanelIntoView,
    openSourceCollectionScreeningPanel,
    runSourceCollectionScreeningAction,
    excludeUnverifiableSourceCollectionCandidates,
    openSourceCollectionCandidatePanel,
    runSourceCollectionCandidateExtractionAction,
    runSourceCollectionGraphAction,
    startKnowledgeCollectionCompletionForRun,
    runKnowledgeCollectionCompletionAction,
    runKnowledgeCollectionLoopAction,
    runSourceCollectionSearchFromHeader,
    runSourceCollectionCollectionAction,
    sourceCollectionStageProjectionSyncing,
    sourceCollectionStageProjectionLabel,
    sourceCollectionStageLaunchActive,
    sourceCollectionStageFormalRetryRequired,
    sourceCollectionStageLaunchSummary,
    sourceCollectionStageDisplayState,
    sourceCollectionStageDisplayStatus,
    sourceCollectionStageDisplaySummary,
    sourceCollectionStepClassName,
    sourceCollectionCollectionActionLabel,
    sourceCollectionCollectionActionReadiness,
  } = actionHandlers;

  // Guard: incomplete SC bag / partial mid must never crash the workbench shell.
  const resolvedSourceCollectionDisplayState =
    sourceCollectionDisplayState ?? EMPTY_SOURCE_COLLECTION_DISPLAY_STATE;

  const sourceCollectionConsoleState: SourceCollectionStepState = resolvedSourceCollectionDisplayState.consoleState;
  const sourceCollectionConsoleStatusText = resolvedSourceCollectionDisplayState.statusText;
  const sourceCollectionDecisionText = resolvedSourceCollectionDisplayState.decisionText;
  const sourceCollectionStepStatusText = (state: SourceCollectionStepState) =>
    sourceCollectionStepStatusTextPure(input.lang, state);
  // F3: pipeline step states in presentationStepStates.
  const {
    searchStepState: sourceCollectionSearchStepState,
    screeningFallbackStepState: sourceCollectionScreeningFallbackStepState,
    screeningStepStateRaw: sourceCollectionScreeningStepStateRaw,
    screeningStepState: sourceCollectionScreeningStepState,
    candidateFallbackStepState: sourceCollectionCandidateFallbackStepState,
    candidateStepStateRaw: sourceCollectionCandidateStepStateRaw,
    candidateStepState: sourceCollectionCandidateStepState,
    extractionDefaultPanelId: sourceCollectionExtractionDefaultPanelId,
    graphFallbackStepState: sourceCollectionGraphFallbackStepState,
    graphStepState: sourceCollectionGraphStepState,
    memoryFallbackStepState: sourceCollectionMemoryFallbackStepState,
    memoryStepState: sourceCollectionMemoryStepState,
    extractionStepState: sourceCollectionExtractionStepState,
  } = buildSourceCollectionPipelineStepStates({
    searchFallback: resolvedSourceCollectionDisplayState.searchStepState,
    collectionProjection: sourceCollectionCollectionProjection,
    screeningProjection: sourceCollectionScreeningProjection,
    candidateProjection: sourceCollectionCandidateProjection,
    graphProjection: sourceCollectionGraphProjection,
    memoryProjection: sourceCollectionMemoryProjection,
    extractionCanProceedAfterExclusions: sourceCollectionExtractionCanProceedAfterExclusions,
    sourceQualityError: Boolean(selectedTeamSourceQualityError),
    sourceQualityPending: selectedTeamSourceQualityPending,
    runAssessedCount: sourceCollectionRunAssessedCount,
    displayedCandidateCount: sourceCollectionDisplayedCandidateCount,
    searchOpenAssignmentCount: sourceCollectionSearchOpenAssignmentCount,
    recordOutputError: Boolean(selectedTeamRecordSourceCollectionOutputError),
    extractError: Boolean(selectedTeamExtractSourceCollectionCandidatesError),
    recordOutputPending: selectedTeamRecordSourceCollectionOutputPending,
    extractPending: selectedTeamExtractSourceCollectionCandidatesPending,
    hasRun: Boolean(input.selectedSourceCollectionRun),
    graphError: Boolean(selectedTeamBuildCandidateGraphError),
    graphQueryError: Boolean(input.teamWorkflowCandidateGraphQuery.error),
    graphPending: selectedTeamBuildCandidateGraphPending,
    graphNodeCount: candidateGraphNodeCount,
    runApprovedCount: sourceCollectionRunApprovedCount,
    knowledgeQueryError: Boolean(input.teamWorkflowKnowledgeIngestionStatusQuery.error),
    knowledgePrecheckError: Boolean(selectedTeamKnowledgePrecheckError),
    knowledgeIngestError: Boolean(selectedTeamKnowledgeCollectionIngestError),
    knowledgePrecheckPending: selectedTeamKnowledgePrecheckPending,
    knowledgeIngestPending: selectedTeamKnowledgeCollectionIngestPending,
    formalKnowledgeItemCount,
    knowledgePendingReviewCount,
    knowledgeStewardPackCount,
    ingestCandidateCount: sourceCollectionIngestCandidateCount,
  });
  // R2-o: stage task label/readiness helpers.
  const stageActionHelpers = createSourceCollectionStageActionHelpers({
    lang: input.lang,
    sourceCollectionStageSessionTaskPendingStageId,
    sourceCollectionStageLaunchActive,
    sourceCollectionActionReadiness,
    selectedTeamStartSourceCollectionStageTaskPending,
    sourceCollectionActionBusyReason,
    sourceCollectionStageCardById,
    sourceCollectionCollectionActionReadiness,
    sourceCollectionActionNoInputReason,
    sourceCollectionCandidateExtractionActionReadiness,
    sourceCollectionScreeningActionReadiness,
    sourceCollectionGraphActionReadiness,
    sourceCollectionMemoryActionReadiness,
  });
  const {
    sourceCollectionStageTaskActionLabel,
    sourceCollectionStageTaskActionReadiness,
    sourceCollectionStageActionLabelFor,
    sourceCollectionStageActionReadinessFor,
  } = stageActionHelpers;
  // R2-m: stage display loading/state + extraction sync metric labels.
  const stageDisplaySurfaces = deriveSourceCollectionStageDisplaySurfaces({
    lang: input.lang,
    loadingText: sourceCollectionLoadingText,
    dataSyncText: sourceCollectionDataSyncText,
    recordsDataLoading: sourceCollectionRecordsDataLoading,
    assignmentsDataLoading: sourceCollectionAssignmentsDataLoading,
    primaryDataLoading: sourceCollectionPrimaryDataLoading,
    screeningDataLoading: sourceCollectionScreeningDataLoading,
    graphDataLoading: sourceCollectionGraphDataLoading,
    sourceQualityLoading: sourceCollectionSourceQualityLoading,
    knowledgeIngestionDataLoading: sourceCollectionKnowledgeIngestionDataLoading,
    searchStepState: sourceCollectionSearchStepState,
    extractionStepState: sourceCollectionExtractionStepState,
    graphStepState: sourceCollectionGraphStepState,
    memoryStepState: sourceCollectionMemoryStepState,
    projectedCollectedCount: sourceCollectionProjectedCollectedCount,
    displayedCandidateCount: sourceCollectionDisplayedCandidateCount,
    projectedCandidateCount: sourceCollectionProjectedCandidateCount,
    projectedAssessedCount: sourceCollectionProjectedAssessedCount,
    projectedApprovedCount: sourceCollectionProjectedApprovedCount,
    currentCandidateCount: sourceCollectionCurrentCandidateCount,
    extractionAgentMaterialCount: sourceCollectionExtractionAgentMaterialCount,
    runPendingScreeningCount: sourceCollectionRunPendingScreeningCount,
    projectedFormalKnowledgeCount: sourceCollectionProjectedFormalKnowledgeCount,
  });
  const {
    sourceCollectionFindingDisplayLoading,
    sourceCollectionFindingDisplayState,
    sourceCollectionExtractionDisplayLoading,
    sourceCollectionExtractionDisplayState,
    sourceCollectionRelationsDisplayLoading,
    sourceCollectionRelationsDisplayState,
    sourceCollectionIngestionDisplayLoading,
    sourceCollectionIngestionDisplayState,
    sourceCollectionSourceSyncStatusText,
    sourceCollectionCandidateSyncStatusText,
    sourceCollectionExtractionLoadingMetric,
    sourceCollectionExtractionMaterialMetric,
    sourceCollectionExtractionLoadingOutputLabel,
    sourceCollectionIngestionReadyForExperiment,
  } = stageDisplaySurfaces;
  const sourceCollectionExperimentPlanningRoute = researchWorkspaceStageRoute(
    input.selectedTeam?.teamId || RESEARCH_TEAM_ID,
    "experiment",
  );

  const {
    teamWorkflowCandidateGraphRecord: _omitGraphRecord,
    teamWorkflowCandidateGraph: _omitGraph,
    ...summaryProjectionReturn
  } = summaryProjection;
  void _omitGraphRecord;
  void _omitGraph;

  return {
    ...summaryProjectionReturn,
    ...routeMutationSurface,
    latestAiSearchRun,
    aiSearchRunCanStart,
    ...selectionPresentation,
    sourceCollectionSummaryCounts,
    ...listMetrics,
    sourceCollectionActionReadiness,
    sourceCollectionActionDisabledTitle,
    ...displayLabels,
    sourceCollectionPendingCandidateImportCount,
    sourceCollectionExtractionRecoveryCoverage,
    sourceCollectionExtractionRecoveryClosure,
    sourceCollectionExtractionSourceVerificationCount,
    sourceCollectionUnverifiableCandidateIds,
    sourceCollectionExtractionMissingEvidenceAnchorCount,
    sourceCollectionExtractionAgentMaterialCount,
    sourceCollectionExtractionNeedsAgentMaterial,
    sourceCollectionExtractionRecoveryMissingCount,
    sourceCollectionExtractionExcludedRecoveryState,
    sourceCollectionExtractionCanProceedAfterExclusions,
    sourceCollectionExtractionProceedableSummary,
    sourceCollectionStageFocusLabel,
    sourceCollectionRunStatusValue,
    sourceCollectionAcceptedBackgroundActive,
    canRecordSourceCollectionOutput,
    canExecuteSourceCollectionSearch,
    sourceCollectionAcceptedBackgroundFailed,
    sourceCollectionOperationFailed,
    sourceCollectionDisplayState: resolvedSourceCollectionDisplayState,
    ...downstreamMetrics,
    sourceCollectionSearchActionReadiness,
    sourceCollectionCandidateExtractionActionReadiness,
    sourceCollectionScreeningActionReadiness,
    sourceCollectionGraphActionReadiness,
    sourceCollectionMemoryActionReadiness,
    sourceCollectionCompletionActionReadiness,
    sourceCollectionLoopStartsNewRun,
    sourceCollectionLoopStartReadiness,
    sourceCollectionLoopActionReadiness,
    sourceCollectionMemoryActionDisabled,
    sourceCollectionMemoryActionLabel,
    sourceCollectionCompletionActionDisabled,
    sourceCollectionCompletionActionLabel,
    sourceCollectionLoopActionDisabled,
    sourceCollectionLoopActionLabel,
    sourceCollectionGraphActionDisabled,
    sourceCollectionGraphActionLabel,
    sourceCollectionScreeningDisabled,
    sourceCollectionScreeningForceRescreen,
    sourceCollectionScreeningButtonText,
    sourceCollectionScreeningButtonTitle,
    sourceCollectionScreeningStatusText,
    sourceCollectionCandidateExtractionButtonText,
    ...actionHandlers,
    sourceCollectionConsoleState,
    sourceCollectionConsoleStatusText,
    sourceCollectionDecisionText,
    sourceCollectionStepStatusText,
    sourceCollectionSearchStepState,
    sourceCollectionScreeningFallbackStepState,
    sourceCollectionScreeningStepStateRaw,
    sourceCollectionScreeningStepState,
    sourceCollectionCandidateFallbackStepState,
    sourceCollectionCandidateStepStateRaw,
    sourceCollectionCandidateStepState,
    sourceCollectionExtractionDefaultPanelId,
    sourceCollectionGraphFallbackStepState,
    sourceCollectionGraphStepState,
    sourceCollectionMemoryFallbackStepState,
    sourceCollectionMemoryStepState,
    sourceCollectionExtractionStepState,
    ...stageActionHelpers,
    ...stageDisplaySurfaces,
    sourceCollectionExperimentPlanningRoute,
    sourceCollectionLoadingText,
    sourceCollectionDataSyncText,
    sourceCollectionLoadingSummary,
    sourceCollectionActionLoadingReason,
    sourceCollectionActionErrorReason,
    sourceCollectionActionNoRunReason,
    sourceCollectionActionNoInputReason,
    sourceCollectionActionBusyReason,
    ...writeMutationSurface,
  };
}
