/**
 * Input contract for SC presentation core (R2-q typed bag).
 */
import type { MutableRefObject, Dispatch, SetStateAction } from "react";
import type { NavigateFunction, SetURLSearchParams } from "react-router-dom";
import type { QueryClient, UseMutationResult, UseQueryResult } from "@tanstack/react-query";
import type { Team, TeamWorkflowCandidate } from "../../api/types";
import type { SourceCollectionSourceFilter } from "./source-collection/evidenceModel";
import type { SourceCollectionStageModuleId } from "./source-collection/stageProjection";
import type { SourceCollectionDraft } from "./source-collection/presentationModel";
import type { SourceCollectionOutputDraft } from "./sourceCollectionMutationModel";

export type UseSourceCollectionPresentationInput = {
  lang: "zh" | "en";
  selectedTeam: Team | null;
  effectiveTeamId: string;
  researchWorkflowTeamSelected: boolean;
  pageVisible: boolean;
  researchStagePhases: any[];
  researchStageRoundStatus: any;
  researchStageProjectAgentTasks: { isStarting: boolean; error: unknown };
  teamWorkflowCandidates: TeamWorkflowCandidate[];
  teamWorkflowCandidatesQuery: UseQueryResult<any, Error>;
  teamWorkflowCandidateListEnabled: boolean;
  teamWorkflowSourceQualityStatus: any;
  teamWorkflowSourceQualityStatusQuery: UseQueryResult<any, Error>;
  teamWorkflowCandidateGraphQuery: UseQueryResult<any, Error>;
  teamWorkflowKnowledgeIngestionStatusQuery: UseQueryResult<any, Error>;
  teamWorkflowPaperNoteChunkStatus: any;
  teamWorkflow: any;
  runtimeSummaryQuery: { data?: any };
  sourceCollectionSummaryQuery: UseQueryResult<any, Error>;
  sourceCollectionRecordsQuery: UseQueryResult<any, Error>;
  sourceCollectionAssignmentsQuery: UseQueryResult<any, Error>;
  sourceCollectionRunStatusQuery: UseQueryResult<any, Error>;
  sourceCollectionFindingDetailsVisible: boolean;
  sourceCollectionRuns: any[];
  sourceCollectionRunsQuery: UseQueryResult<any, Error>;
  sourceCollectionWorkspaceSelected: boolean;
  teamWorkflowSourceQualityEnabled: boolean;
  teamWorkflowGraphEnabled: boolean;
  teamWorkflowKnowledgeIngestionEnabled: boolean;
  selectedSourceCollectionRun: any;
  selectedSourceCollectionRunEffectiveId: string;
  sourceCollectionDraft: SourceCollectionDraft;
  sourceCollectionOutputDraft: SourceCollectionOutputDraft;
  setSourceCollectionOutputDraft: Dispatch<SetStateAction<SourceCollectionOutputDraft>>;
  selectedSourceCollectionCandidateId: string;
  setSelectedSourceCollectionCandidateId: Dispatch<SetStateAction<string>>;
  sourceCollectionSourceFilter: SourceCollectionSourceFilter;
  setSourceCollectionSourceFilter: Dispatch<SetStateAction<SourceCollectionSourceFilter>>;
  sourceCollectionResultPageByStage: Record<SourceCollectionStageModuleId, number>;
  setSourceCollectionResultPageByStage: Dispatch<SetStateAction<Record<SourceCollectionStageModuleId, number>>>;
  selectedSourceCollectionStageId: SourceCollectionStageModuleId;
  setSelectedSourceCollectionStageId: Dispatch<SetStateAction<SourceCollectionStageModuleId>>;
  sourceCollectionExpandedPanelId: string;
  setSourceCollectionExpandedPanelId: Dispatch<SetStateAction<string>>;
  sourceCollectionFocusedPanelId: string;
  setSourceCollectionFocusedPanelId: Dispatch<SetStateAction<string>>;
  activeSourceCollectionResearchProjectId: string;
  sourceCollectionNeedsCandidateList: boolean;
  experimentPlanningStatusQuery: UseQueryResult<any, Error>;
  researchLoopTemplatesQuery: UseQueryResult<any, Error>;
  researchLoopStatusQuery: UseQueryResult<any, Error>;
  aiSearchRunsQuery: UseQueryResult<any, Error>;
  aiSearchRunTopic: string;
  resetResearchProjectSourceCollectionMutation: UseMutationResult<any, Error, any, unknown>;
  startResearchStageRoundMutation: UseMutationResult<any, Error, any, unknown>;
  createExperimentPlanMutation: UseMutationResult<any, Error, any, unknown>;
  materializeEngineeringProxyHypothesisMutation: UseMutationResult<any, Error, any, unknown>;
  completeScientificHypothesisFromDesignMutation: UseMutationResult<any, Error, any, unknown>;
  reviewExperimentHypothesisMutation: UseMutationResult<any, Error, any, unknown>;
  createExperimentHypothesisRevisionMutation: UseMutationResult<any, Error, any, unknown>;
  freezeExperimentDesignMutation: UseMutationResult<any, Error, any, unknown>;
  registerExperimentBaselineArtifactMutation: UseMutationResult<any, Error, any, unknown>;
  runExperimentSmokeMutation: UseMutationResult<any, Error, any, unknown>;
  registerExperimentSmokeResultMutation: UseMutationResult<any, Error, any, unknown>;
  registerExperimentFullRunResultMutation: UseMutationResult<any, Error, any, unknown>;
  requestExperimentKnowledgeIngestionMutation: UseMutationResult<any, Error, any, unknown>;
  createResearchLoopMutation: UseMutationResult<any, Error, any, unknown>;
  recordResearchLoopEvidenceMutation: UseMutationResult<any, Error, any, unknown>;
  recordResearchLoopDecisionMutation: UseMutationResult<any, Error, any, unknown>;
  startSourceCollectionRunMutation: UseMutationResult<any, Error, any, unknown>;
  startSourceCollectionStageSessionTaskMutation: UseMutationResult<any, Error, any, unknown>;
  recordSourceCollectionOutputMutation: UseMutationResult<any, Error, any, unknown>;
  executeSourceCollectionSearchMutation: UseMutationResult<any, Error, any, unknown>;
  extractSourceCollectionCandidatesMutation: UseMutationResult<any, Error, any, unknown>;
  openSourceCollectionStorageMutation: UseMutationResult<any, Error, any, unknown>;
  startAiSearchRunMutation: UseMutationResult<any, Error, any, unknown>;
  buildCandidateGraphMutation: UseMutationResult<any, Error, any, unknown>;
  runKnowledgeIngestionPrecheckMutation: UseMutationResult<any, Error, any, unknown>;
  runKnowledgeCollectionCompletionMutation: UseMutationResult<any, Error, any, unknown>;
  planPaperNoteChunksMutation: UseMutationResult<any, Error, any, unknown>;
  assessSourceQualityMutation: UseMutationResult<any, Error, any, unknown>;
  assessSourceQualityBatchMutation: UseMutationResult<any, Error, any, unknown>;
  queryClient: QueryClient;
  requestedSourceCollectionStage: SourceCollectionStageModuleId | null;
  setSourceCollectionStageSyncUntilMs: Dispatch<SetStateAction<number>>;
  setSourceCollectionPendingStageTaskIds: Dispatch<SetStateAction<any>>;
  searchParams: URLSearchParams;
  setSearchParams: SetURLSearchParams;
  navigate: NavigateFunction;
  scrollSourceCollectionPanelIntoViewRef: MutableRefObject<(panelId: string) => void>;
  sourceCollectionControlPanelRef: MutableRefObject<HTMLElement | null>;
  sourceCollectionRelationMapperAgentId: string;
  sourceCollectionExtractorAgentId: string;
  sourceCollectionOwnerAgentId: string;
  sourceCollectionIngestorAgentId: string;
  sourceCollectionStandalone: boolean;
  sourceCollectionStageWritebackSyncActive: boolean;
  sourceCollectionPendingStageTaskIds: Partial<Record<SourceCollectionStageModuleId, string[]>>;
  selectResearchWorkspaceView: (view: any) => void;
  launchResearchStage: (stageType: any, mode?: "continue_or_start" | "new_round") => void | Promise<void>;
  /** CSS module map for SC step badge classes (route styles). */
  styles: Record<string, string>;
};
