/**
 * R2-s close-out: SC composition layer for workbench foundation.
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
import { useTeamsScComposition } from "./useTeamsScComposition";

export function useTeamsWorkbenchScLayer(ctx: any) {
  const scComposition = useTeamsScComposition({
    ...ctx.sourceCollectionWorkspace,
    ...ctx.mutationBundle,
    lang: ctx.lang,
    selectedTeam: ctx.selectedTeam,
    effectiveTeamId: ctx.effectiveTeamId,
    researchWorkflowTeamSelected: ctx.researchWorkflowTeamSelected,
    pageVisible: ctx.pageVisible,
    researchStagePhases: ctx.researchStagePhases,
    researchStageRoundStatus: ctx.researchStageRoundStatus,
    researchStageProjectAgentTasks: ctx.researchStageProjectAgentTasks,
    teamWorkflowCandidates: ctx.teamWorkflowCandidates,
    teamWorkflowCandidatesQuery: ctx.teamWorkflowCandidatesQuery,
    teamWorkflowCandidateListEnabled: ctx.teamWorkflowCandidateListEnabled,
    teamWorkflowSourceQualityStatus: ctx.teamWorkflowSourceQualityStatus,
    teamWorkflowSourceQualityStatusQuery: ctx.teamWorkflowSourceQualityStatusQuery,
    teamWorkflowCandidateGraphQuery: ctx.teamWorkflowCandidateGraphQuery,
    teamWorkflowKnowledgeIngestionStatusQuery: ctx.teamWorkflowKnowledgeIngestionStatusQuery,
    teamWorkflowPaperNoteChunkStatus: ctx.teamWorkflowPaperNoteChunkStatus,
    teamWorkflow: ctx.teamWorkflow,
    sourceCollectionWorkspaceSelected: ctx.sourceCollectionWorkspaceSelected,
    teamWorkflowSourceQualityEnabled: ctx.teamWorkflowSourceQualityEnabled,
    teamWorkflowGraphEnabled: ctx.teamWorkflowGraphEnabled,
    teamWorkflowKnowledgeIngestionEnabled: ctx.teamWorkflowKnowledgeIngestionEnabled,
    sourceCollectionNeedsCandidateList: ctx.sourceCollectionNeedsCandidateList,
    experimentPlanningStatusQuery: ctx.experimentPlanningStatusQuery,
    researchLoopTemplatesQuery: ctx.researchLoopTemplatesQuery,
    researchLoopStatusQuery: ctx.researchLoopStatusQuery,
    aiSearchRunsQuery: ctx.aiSearchRunsQuery,
    aiSearchRunTopic: ctx.aiSearchRunTopic,
    queryClient: ctx.queryClient,
    requestedSourceCollectionStage: ctx.requestedSourceCollectionStage,
    searchParams: ctx.searchParams,
    setSearchParams: ctx.setSearchParams,
    navigate: ctx.navigate,
    scrollSourceCollectionPanelIntoViewRef: ctx.scrollSourceCollectionPanelIntoViewRef,
    sourceCollectionControlPanelRef: ctx.sourceCollectionControlPanelRef,
    sourceCollectionRelationMapperAgentId: ctx.sourceCollectionRelationMapperAgentId,
    sourceCollectionExtractorAgentId: ctx.sourceCollectionExtractorAgentId,
    sourceCollectionOwnerAgentId: ctx.sourceCollectionOwnerAgentId,
    sourceCollectionIngestorAgentId: ctx.sourceCollectionIngestorAgentId,
    sourceCollectionStandalone: ctx.sourceCollectionStandalone,
    selectResearchWorkspaceView: ctx.selectResearchWorkspaceView,
    launchResearchStage: ctx.launchResearchStage,
    styles: ctx.styles,
    setSourceCollectionStageAdvanceFailure: ctx.setSourceCollectionStageAdvanceFailure,
    teamWorkflowKnowledgeIngestionStatus: ctx.teamWorkflowKnowledgeIngestionStatus,
    teamWorkflowCandidateGraph: ctx.teamWorkflowCandidateGraph,
    repairSelectedWorkflowTeamAgentsIfNeeded: ctx.repairSelectedWorkflowTeamAgentsIfNeeded,
    knowledgeExpansionWorkflowTeamSelected: ctx.knowledgeExpansionWorkflowTeamSelected,
    sourceCollectionStageReturnRoute: ctx.sourceCollectionStageReturnRoute,
    sourceCollectionStageChatReturnLabel: ctx.sourceCollectionStageChatReturnLabel,
    sourceCollectionStageTaskClickKey: ctx.sourceCollectionStageTaskClickKey,
    sourceCollectionStageAgentChatState: ctx.sourceCollectionStageAgentChatState,
    sourceCollectionStagePrimaryAgentBinding: ctx.sourceCollectionStagePrimaryAgentBinding,
    openSourceCollectionStageAgentChat: ctx.openSourceCollectionStageAgentChat,
    agentSummaryQuery: ctx.agentSummaryQuery,
    selectedTeamReturnRoute: ctx.selectedTeamReturnRoute,
    workflowQualityToneBound: ctx.workflowQualityToneBound,
    workflowIngestionToneBound: ctx.workflowIngestionToneBound,
    sourceCollectionStageAgentBindings: ctx.sourceCollectionStageAgentBindings,
    sourceCollectionStageAdvanceFailure: ctx.sourceCollectionStageAdvanceFailure,
  });

  const {
    experimentPlanningStatus,
    researchStageCanLaunch: researchStageCanLaunchFromSc,
    renderSourceCollectionStandalonePage,
    selectSourceCollectionStage,
    selectedTeamAssessSourceQualityPending,
    selectedTeamPlanPaperNoteChunksPending,
    selectedTeamRecordSourceCollectionOutputError,
    selectedTeamRecordSourceCollectionOutputResult,
    selectedTeamSourceQualityPending,
    selectedTeamStartResearchStagePending: selectedTeamStartResearchStagePendingFromSc,
    selectedTeamStartSourceCollectionError,
    selectedTeamStartSourceCollectionResult,
    sourceCollectionAssignmentRunSummaryText,
    sourceCollectionBoardNextStepLabel,
    sourceCollectionCollectedCountLabel,
    sourceCollectionCollectedCountText,
    sourceCollectionCollectedRunSummaryText,
    sourceCollectionConsoleState,
    sourceCollectionConsoleStatusText,
    sourceCollectionDisplayState,
    sourceCollectionDownstreamOpenAssignmentCountText,
    sourceCollectionFindingStageCompact,
    sourceCollectionPhaseCloseGate,
    sourceCollectionPromptCacheMode,
    sourceCollectionPromptCacheStatus,
    sourceCollectionQueryCountText,
    sourceCollectionRunStatus,
    sourceCollectionSearchOpenAssignmentCountText,
    sourceCollectionStandaloneStageModules,
    sourceCollectionStepClassName,
  } = scComposition;

  return {
    scComposition,
    experimentPlanningStatus,
    researchStageCanLaunch: researchStageCanLaunchFromSc,
    researchStageCanLaunchFromSc,
    renderSourceCollectionStandalonePage,
    selectSourceCollectionStage,
    selectedTeamAssessSourceQualityPending,
    selectedTeamPlanPaperNoteChunksPending,
    selectedTeamRecordSourceCollectionOutputError,
    selectedTeamRecordSourceCollectionOutputResult,
    selectedTeamSourceQualityPending,
    selectedTeamStartResearchStagePending: selectedTeamStartResearchStagePendingFromSc,
    selectedTeamStartResearchStagePendingFromSc,
    selectedTeamStartSourceCollectionError,
    selectedTeamStartSourceCollectionResult,
    sourceCollectionAssignmentRunSummaryText,
    sourceCollectionBoardNextStepLabel,
    sourceCollectionCollectedCountLabel,
    sourceCollectionCollectedCountText,
    sourceCollectionCollectedRunSummaryText,
    sourceCollectionConsoleState,
    sourceCollectionConsoleStatusText,
    sourceCollectionDisplayState,
    sourceCollectionDownstreamOpenAssignmentCountText,
    sourceCollectionFindingStageCompact,
    sourceCollectionPhaseCloseGate,
    sourceCollectionPromptCacheMode,
    sourceCollectionPromptCacheStatus,
    sourceCollectionQueryCountText,
    sourceCollectionRunStatus,
    sourceCollectionSearchOpenAssignmentCountText,
    sourceCollectionStandaloneStageModules,
    sourceCollectionStepClassName,
  };
}
