export const queryKeys = {
  runtimeSummary: () => ["runtime", "summary"] as const,
  launcherStatus: () => ["launcher", "status"] as const,
  backendHealth: () => ["runtime", "backend-health"] as const,
  gitStatus: () => ["git", "status"] as const,
  tools: () => ["tools"] as const,
  toolWebSearchHealth: () => ["tools", "web-search", "health"] as const,
  skills: () => ["skills"] as const,
  skill: (command: string) => ["skills", command] as const,
  toolImage2Models: () => ["tools", "image2", "models"] as const,
  gitCommits: () => ["git", "commits"] as const,
  gitDiff: (path: string) => ["git", "diff", path] as const,
  agents: () => ["agents"] as const,
  agentConfigWorkspace: () => ["agents", "config-workspace"] as const,
  agent: (id: string) => ["agents", id] as const,
  agentRuns: (id: string) => ["agents", id, "runs"] as const,
  agentMessages: (id: string, status = "pending") => ["agents", id, "messages", status] as const,
  agentRuntimeEvidence: (id: string) => ["agents", id, "runtime-evidence"] as const,
  promptTemplates: () => ["prompt-templates"] as const,
  agentModeBindings: () => ["agent-mode-bindings"] as const,
  conversations: () => ["conversations"] as const,
  sessions: () => ["sessions"] as const,
  sessionQuery: (q = "", limit = 50, cursor = "") => ["sessions", "query", q, limit, cursor] as const,
  sessionAgentTemplates: () => ["sessions", "agent-templates"] as const,
  session: (id: string) => ["sessions", id] as const,
  chatRooms: () => ["chat-rooms"] as const,
  chatRoom: (id: string) => ["chat-rooms", id] as const,
  chatRoomModes: () => ["chat-rooms", "modes"] as const,
  chatRoomPurposes: () => ["chat-rooms", "purposes"] as const,
  projectAgentBus: () => ["project-agent-bus"] as const,
  teams: () => ["teams"] as const,
  teamTemplates: () => ["team-templates"] as const,
  team: (id: string) => ["teams", id] as const,
  teamCanvas: (id: string) => ["teams", id, "canvas"] as const,
  teamWorkflow: (id: string) => ["teams", id, "workflow-orchestration"] as const,
  teamWorkflowCandidates: (id: string, limit = 8) => ["teams", id, "workflow-orchestration", "candidates", limit] as const,
  teamWorkflowCandidateGraph: (id: string) => ["teams", id, "workflow-orchestration", "candidate-graph"] as const,
  teamWorkflowCoordinationStatus: (id: string) => ["teams", id, "workflow-orchestration", "coordination", "status"] as const,
  teamWorkflowKnowledgeIngestionStatus: (id: string) => ["teams", id, "workflow-orchestration", "knowledge-ingestion", "status"] as const,
  teamWorkflowSourceCollectionRuns: (id: string, limit = 6) =>
    ["teams", id, "workflow-orchestration", "source-collection-runs", limit] as const,
  dataProcessingRunStatus: (id: string) => ["data-processing", "runs", id, "status"] as const,
  dataProcessingCollectionAssignments: (id: string) => ["data-processing", "runs", id, "collection-assignments"] as const,
  fileTree: () => ["files", "tree"] as const,
  fileContent: (path: string) => ["files", "content", path] as const,
  memoryOverview: () => ["memory", "overview"] as const,
  memoryItemDetails: () => ["memory", "item-detail"] as const,
  memoryItemDetail: (sectionId: string, itemId: string) => ["memory", "item-detail", sectionId, itemId] as const,
  memoryUsageContract: () => ["memory", "usage-contract"] as const,
  memoryKnowledgeGraph: (agentId = "") => ["memory", "knowledge-graph", agentId] as const,
  memoryKnowledgeGraphNodeDetail: (nodeId: string, agentId = "") => ["memory", "knowledge-graph", "node-detail", nodeId, agentId] as const,
  knowledgeDashboardSnapshot: (agentId = "") => ["knowledge", "dashboard-snapshot", agentId] as const,
  knowledgeOverview: () => ["knowledge", "overview"] as const,
  knowledgeStewardOverview: () => ["knowledge", "steward", "overview"] as const,
  knowledgeStewardRecommendations: (agentId = "") => ["knowledge", "steward", "recommendations", agentId] as const,
  knowledgeStewardWorkbench: (agentId = "") => ["knowledge", "steward", "workbench", agentId] as const,
  knowledgeItems: (knowledgeBaseId: string, agentId = "") => ["knowledge", "items", knowledgeBaseId, agentId] as const,
  knowledgeSearch: (knowledgeBaseId: string, agentId: string, query: string, tags: string, mode = "") =>
    ["knowledge", "search", knowledgeBaseId, agentId, query, tags, mode] as const,
  knowledgeRagHealth: () => ["knowledge", "rag", "health"] as const,
  knowledgeRagRetrieve: (knowledgeBaseId: string, agentId: string, query: string, tags: string, mode: string, topK: number, maxContextChars: number) =>
    ["knowledge", "rag", "retrieve", knowledgeBaseId, agentId, query, tags, mode, topK, maxContextChars] as const,
  knowledgeRatingSuggestions: (knowledgeBaseId: string, agentId = "", status = "", priority = "") =>
    ["knowledge", "rating-suggestions", knowledgeBaseId, agentId, status, priority] as const,
  knowledgePermissionAudit: (agentId: string) => ["knowledge", "permissions", agentId] as const,
  knowledgeGovernanceTasks: (agentId: string, status = "open") => ["knowledge", "governance-tasks", agentId, status] as const,
  knowledgeOperationsHealth: (agentId = "") => ["knowledge", "operations-health", agentId] as const,
  knowledgeGovernancePlan: (agentId = "") => ["knowledge", "governance-plan", agentId] as const,
  knowledgeIngestionAdapters: () => ["knowledge", "ingestion-adapters"] as const,
  knowledgeTrace: (knowledgeBaseId: string, agentId: string, targetId: string) => ["knowledge", "trace", knowledgeBaseId, agentId, targetId] as const,
  researchThemeDiscoverySessions: () => ["research", "theme-discovery", "sessions"] as const,
  researchThemeDiscoverySession: (sessionId: string) => ["research", "theme-discovery", "sessions", sessionId] as const,
  researchThemeDiscoveryPrompts: () => ["research", "theme-discovery", "prompts"] as const,
  researchKnowledgeBase: (query = "", kind = "", category = "") =>
    ["research", "knowledge-base", query, kind, category] as const,
  researchFlowCanvas: () => ["research", "flow-canvas"] as const,
  researchOrganization: () => ["research", "organization"] as const,
  logRoots: () => ["logs", "roots"] as const,
  logTree: (root: string) => ["logs", "tree", root] as const,
  logContent: (root: string, path: string) => ["logs", "content", root, path] as const,
  runtimeScenes: () => ["logs", "runtime-scenes"] as const,
  runtimeScene: (sceneId: string) => ["logs", "runtime-scenes", sceneId] as const,
  runtimeSceneContent: (sceneId: string, path: string) =>
    ["logs", "runtime-scenes", sceneId, "content", path] as const,
  evolutionWorkspaceSnapshot: () => ["evolution", "workspace-snapshot"] as const,
  evolutionOverview: () => ["evolution", "overview"] as const,
  evolutionRuns: () => ["evolution", "runs"] as const,
  evolutionLibrary: () => ["evolution", "library"] as const,
  evolutionProposal: (sessionId: string) => ["evolution", "proposal", sessionId] as const,
  evolutionWorkbench: () => ["evolution", "workbench"] as const,
  evolutionWorktreeRuns: () => ["evolution", "worktree-runs"] as const,
  evolutionWorktreeActiveRun: () => ["evolution", "worktree-runs", "active"] as const,
  evolutionChatReview: () => ["evolution", "chat-review"] as const,
  evolutionChatReviewCandidate: (candidateId: string) => ["evolution", "chat-review", candidateId] as const,
  evolutionActiveRun: () => ["evolution", "active-run"] as const,
  evolutionLatestRun: () => ["evolution", "latest-run"] as const,
  evolutionRunCommand: (commandId: string) => ["evolution", "runs", "commands", commandId] as const,
  evolutionSelfOverview: () => ["evolution", "self", "overview"] as const,
  evolutionSelfActiveRun: () => ["evolution", "self", "active-run"] as const,
  evolutionSelfLatestRun: () => ["evolution", "self", "latest-run"] as const,
  evolutionSelfTransactions: () => ["evolution", "self", "transactions"] as const,
  evolutionSelfAudit: () => ["evolution", "self", "audit"] as const,
  petSummary: () => ["pet", "summary"] as const,
  resetSummary: () => ["reset", "summary"] as const,
  diagnosticsHealth: () => ["diagnostics", "health"] as const,
  configPublic: () => ["config", "public"] as const,
  configWorkspace: () => ["config", "workspace"] as const,
};
