"""Fail-closed contract tests for G12 judgement records and bundles.

The manifest used throughout is generated by the real audit sampling
service (G12 full-pilot manifest) so the sampling-scope binding under test
is the production binding, not a hand-built stand-in.
"""

from __future__ import annotations

import pytest

from core.research.competition.calibration_records import (
    BUNDLE_STATUS_COMPLETE,
    BUNDLE_STATUS_PENDING,
    CalibrationRecordError,
    G12CalibrationBundle,
    G12JudgementRecord,
    g12_calibration_bundle_hash,
)
from core.research.competition.calibration_stats import build_confusion_matrix
from core.research.workflow.contracts.audit_sampling import SampleKind
from core.web.services.team_workflow.research_runtime.audit_sampling_service import (
    generate_g12_calibration_manifest,
)

POLICY_SNAPSHOT = {
    "policyId": "cc-auto-advance-policy-002",
    "version": "2.0.0-candidate.1",
    "contentHash": "A" * 64,
}


def _pool(count: int = 12) -> list[dict[str, str]]:
    return [
        {
            "questionId": f"q{index:02d}",
            "riskClass": "low",
            "catalogDomain": "physics",
        }
        for index in range(1, count + 1)
    ]


def _manifest(count: int = 12):
    return generate_g12_calibration_manifest(
        pool=_pool(count),
        policy=POLICY_SNAPSHOT,
        seed="seed-g12-records",
        generated_at="2026-08-28T00:00:00+08:00",
    )


def _record(
    question_id: str,
    *,
    auto: str = "auto_approve",
    human: str = "approve",
    sample_kind: SampleKind = SampleKind.G12_CALIBRATION,
) -> G12JudgementRecord:
    return G12JudgementRecord(
        questionId=question_id,
        sampleKind=sample_kind,
        autoDecision=auto,
        humanDecision=human,
        riskClass="low",
        domain="physics",
        recordedAt="2026-08-28T01:00:00+08:00",
        evidenceRef=f"review:g12:{question_id}",
    )


def _full_records(count: int = 12) -> list[G12JudgementRecord]:
    return [_record(f"q{index:02d}") for index in range(1, count + 1)]


# ---------------------------------------------------------------------------
# Record contract
# ---------------------------------------------------------------------------


def test_record_round_trip_and_stats_projection() -> None:
    payload = {
        "questionId": "q01",
        "sampleKind": "g12_calibration",
        "autoDecision": "auto_escalate",
        "humanDecision": "escalate",
        "riskClass": "low",
        "domain": "physics",
        "recordedAt": "2026-08-28T01:00:00+08:00",
        "evidenceRef": "review:g12:q01",
    }
    record = G12JudgementRecord.from_dict(payload)
    assert record.sampleKind is SampleKind.G12_CALIBRATION
    assert record.to_dict() == payload
    # The stats projection is exactly the mapping calibration_stats consumes.
    matrix = build_confusion_matrix([record.stats_record()])
    assert matrix.true_positives == 1


def test_record_rejects_unknown_or_missing_fields() -> None:
    base = {
        "questionId": "q01",
        "sampleKind": "g12_calibration",
        "autoDecision": "auto_approve",
        "humanDecision": "approve",
        "riskClass": "low",
        "domain": "physics",
        "recordedAt": "2026-08-28T01:00:00+08:00",
        "evidenceRef": "review:g12:q01",
    }
    with pytest.raises(CalibrationRecordError, match="autoDecision"):
        G12JudgementRecord.from_dict({**base, "autoDecision": "maybe_auto"})
    with pytest.raises(CalibrationRecordError, match="humanDecision"):
        G12JudgementRecord.from_dict({**base, "humanDecision": "maybe_reject"})
    with pytest.raises(CalibrationRecordError, match="sampleKind"):
        G12JudgementRecord.from_dict({**base, "sampleKind": "mystery_kind"})
    for key in ("questionId", "riskClass", "domain", "recordedAt", "evidenceRef"):
        broken = {k: v for k, v in base.items() if k != key}
        with pytest.raises(CalibrationRecordError, match=key):
            G12JudgementRecord.from_dict(broken)


# ---------------------------------------------------------------------------
# Bundle construction and manifest binding
# ---------------------------------------------------------------------------


def test_bundle_complete_when_all_manifest_questions_judged() -> None:
    bundle = G12CalibrationBundle.build(manifest=_manifest(), records=_full_records())
    assert bundle.status == BUNDLE_STATUS_COMPLETE
    assert bundle.missing_question_ids() == ()
    assert bundle.manifestId == _manifest().manifestId
    assert bundle.policyId == POLICY_SNAPSHOT["policyId"]
    assert bundle.policyContentHash == POLICY_SNAPSHOT["contentHash"]


def test_bundle_pending_and_missing_projection_on_partial_collection() -> None:
    manifest = _manifest()
    bundle = G12CalibrationBundle.build(
        manifest=manifest, records=_full_records()[:11]
    )
    assert bundle.status == BUNDLE_STATUS_PENDING
    assert bundle.missing_question_ids() == ("q12",)


def test_bundle_rejects_record_outside_manifest_scope() -> None:
    with pytest.raises(CalibrationRecordError, match="sampling scope"):
        G12CalibrationBundle.build(
            manifest=_manifest(), records=[_record("q99")]
        )


def test_bundle_rejects_sample_kind_mismatch() -> None:
    with pytest.raises(CalibrationRecordError, match="sampleKind"):
        G12CalibrationBundle.build(
            manifest=_manifest(),
            records=[_record("q01", sample_kind=SampleKind.DRIFT_SENTINEL)],
        )


def test_bundle_rejects_duplicate_question_records() -> None:
    with pytest.raises(CalibrationRecordError, match="duplicate"):
        G12CalibrationBundle.build(
            manifest=_manifest(), records=[_record("q01"), _record("q01")]
        )


def test_bundle_requires_a_manifest() -> None:
    with pytest.raises(CalibrationRecordError, match="AuditSampleManifest"):
        G12CalibrationBundle.build(
            manifest="not-a-manifest",  # type: ignore[arg-type]
            records=_full_records(),
        )


def test_bundle_binds_records_to_their_own_manifest_only() -> None:
    manifest_a = _manifest()
    bundle_a = G12CalibrationBundle.build(manifest=manifest_a, records=_full_records())
    assert bundle_a.manifestId == manifest_a.manifestId
    # A different pool (chemistry instead of physics) yields a different
    # manifest hash -- the derived manifest id covers only
    # (gate, batchIndex, policy, seed, questionIds), the content hash also
    # covers strata -- and the bundle binds to that exact manifest object.
    pool_b = [
        {"questionId": entry["questionId"], "riskClass": "low", "catalogDomain": "chemistry"}
        for entry in _pool()
    ]
    manifest_c = generate_g12_calibration_manifest(
        pool=pool_b,
        policy=POLICY_SNAPSHOT,
        seed="seed-g12-records",
        generated_at="2026-08-28T00:00:00+08:00",
    )
    assert manifest_c.manifestId == manifest_a.manifestId
    assert manifest_c.manifestHash != manifest_a.manifestHash
    bound = G12CalibrationBundle.build(manifest=manifest_c, records=_full_records())
    assert bound.manifestId == manifest_c.manifestId
    assert bundle_a.records == bound.records  # same judgements, different scope


# ---------------------------------------------------------------------------
# Persistence round trip and hash verification
# ---------------------------------------------------------------------------


def test_bundle_round_trip_verifies_declared_hash_and_status() -> None:
    bundle = G12CalibrationBundle.build(
        manifest=_manifest(), records=_full_records(), bundle_id="bundle-fixed"
    )
    payload = bundle.to_dict()
    payload["bundleHash"] = g12_calibration_bundle_hash(bundle)
    restored = G12CalibrationBundle.from_dict(payload)
    assert restored.bundleId == "bundle-fixed"
    assert restored.status == BUNDLE_STATUS_COMPLETE
    assert restored.records == bundle.records
    assert restored.bundleHash == payload["bundleHash"]


def test_bundle_round_trip_rejects_tampered_hash() -> None:
    bundle = G12CalibrationBundle.build(manifest=_manifest(), records=_full_records())
    payload = bundle.to_dict()
    payload["bundleHash"] = "B" * 64
    with pytest.raises(CalibrationRecordError, match="bundleHash"):
        G12CalibrationBundle.from_dict(payload)


def test_bundle_round_trip_rejects_status_contradicting_records() -> None:
    bundle = G12CalibrationBundle.build(
        manifest=_manifest(), records=_full_records()[:6]
    )
    payload = bundle.to_dict()
    payload["status"] = BUNDLE_STATUS_COMPLETE
    with pytest.raises(CalibrationRecordError, match="status"):
        G12CalibrationBundle.from_dict(payload)


def test_bundle_round_trip_rejects_record_swapped_after_signing() -> None:
    bundle = G12CalibrationBundle.build(manifest=_manifest(), records=_full_records())
    payload = bundle.to_dict()
    payload["bundleHash"] = g12_calibration_bundle_hash(bundle)
    payload["records"][0]["humanDecision"] = "escalate"
    with pytest.raises(CalibrationRecordError, match="bundleHash"):
        G12CalibrationBundle.from_dict(payload)


# ---------------------------------------------------------------------------
# Package export wiring
# ---------------------------------------------------------------------------


def test_competition_package_exports_record_contracts() -> None:
    import core.research.competition as competition_pkg

    for name in (
        "AUTO_DECISIONS",
        "BUNDLE_STATUSES",
        "BUNDLE_STATUS_COMPLETE",
        "BUNDLE_STATUS_PENDING",
        "CalibrationRecordError",
        "G12CalibrationBundle",
        "G12JudgementRecord",
        "HUMAN_DECISIONS",
        "g12_calibration_bundle_hash",
    ):
        assert name in competition_pkg.__all__
        assert hasattr(competition_pkg, name)
