import { useState } from "react";
import { createRoot } from "react-dom/client";
import { BookOpen, Brain, ChevronRight, FileText, History, LockKeyhole, Search, ArrowLeft, CircleCheck, Link2 } from "lucide-react";
import { VButton, VNativeInput, VTabs, VSplitWorkspace, VuiProvider, VStringSelect } from "../../src/components/vui";
import "./preview.css";

const memories = [
  {id:1, type:"偏好与事实", title:"先给结论，再展开依据", summary:"技术讨论使用中文，优先说明结果与影响。", date:"今天 14:32", source:"对话 · 设置页改进", text:"交流时先说明结论，再提供支持结论的事实。默认使用中文，代码名称、路径和协议字段保留原文。", points:["短回复优先，避免重复背景与空泛总结。","需要解释技术取舍时，说明影响，而不是只罗列术语。","未完成的验证应明确标注，不把推测写成事实。"], quote:"先告诉我现在怎么样了，细节需要的时候再展开。", state:"有效", used:true},
  {id:2, type:"经验与约定", title:"启动成功，不等于更新已生效", summary:"区分代码合入、构建、桌面壳换版与运行验证。", date:"今天 11:08", source:"对话 · Launcher 更新", text:"进程启动和健康接口通过，只能证明相应阶段成功。确认更新生效，需要读取正在运行的桌面壳与前端产物身份。", points:["构建失败时保留当前版本和明确错误。","不能用本地文件时间代替运行版本证据。","用户的活动任务和数据必须得到保护。"], quote:"我点了确认更新，但界面还是旧的。", state:"有效", used:false},
  {id:3, type:"任务经历", title:"设置页采用一项一行的布局", summary:"统一控件高度，复杂配置进入详情。", date:"昨天 18:24", source:"对话 · 设置界面", text:"设置页以可扫描的功能行为单位排列。每行保留标题、必要说明与操作，减少重复标题和长期悬浮面板。", points:["复杂模型配置保留独立详情。","危险操作与普通偏好分组。"], quote:"其余功能都做成一行按钮的形式。", state:"有效", used:false},
  {id:4, type:"偏好与事实", title:"桌宠默认不自动启动", summary:"需要时从设置开启，不打断工作。", date:"09/28", source:"对话 · 桌面宠物", text:"桌面宠物默认关闭，由用户通过设置主动开启。启动、关闭和形象切换应当有明确反馈。", points:["不因部署成功而自动弹出宠物窗口。","关闭后保留清楚的重新打开入口。"], quote:"部署成功时默认不启动。", state:"有效", used:false},
  {id:5, type:"经验与约定", title:"旧设置入口约定", summary:"原右下角入口已被设置页入口替代。", date:"09/22", source:"对话 · 早期原型", text:"早期原型曾将桌宠入口放在右下角控制台。此记录已被后续设置页入口约定替代，不应继续作为当前偏好使用。", points:["历史保留用于追溯，不代表当前有效规则。"], quote:"后来决定将桌宠开关放入设置。", state:"已替代", used:false},
];
const agents=[{name:"OpenCode Flash",initial:"OP",count:5},{name:"Grok 4.5",initial:"GR",count:0},{name:"DeepSeek",initial:"DE",count:0}];
function App(){
 const [agent,setAgent]=useState(0),[selected,setSelected]=useState(1),[query,setQuery]=useState(""),[category,setCategory]=useState("全部"),[tab,setTab]=useState("read"),[raw,setRaw]=useState(false),[source,setSource]=useState(false),[mobile,setMobile]=useState(false);
 const items=agent===0?memories.filter(m=>(category==="全部"||m.type===category)&&[m.title,m.summary,m.text,...m.points].join(" ").includes(query)):[];
 const item=items.find(m=>m.id===selected)??items[0];
 const switchAgent=(value:number)=>{setAgent(value);setQuery("");setSelected(1);setSource(false);setRaw(false);setMobile(false);};
 const rail=<aside className="agents"><div className="rail-title">工作空间 <span>个人</span></div><h2>我的 Agent</h2>{agents.map((a,i)=><VButton contentLayout="plain" key={a.name} variant="ghost" className={`agent-row ${agent===i?"chosen":""}`} aria-pressed={agent===i} onPress={()=>switchAgent(i)}><span className={`avatar avatar-${i}`}>{a.initial}</span><span className="agent-name"><strong>{a.name}</strong><small>{a.count?`${a.count} 条示例记忆`:"尚无有效记忆"}</small></span></VButton>)}<div className="rail-note"><LockKeyhole size={14}/><span>独立记忆，清楚归属<br/>共享知识不会混入私有记忆</span></div></aside>;
 const library=<section className="library"><div className="library-controls"><label className="search"><Search size={16}/><VNativeInput aria-label="搜索记忆正文" placeholder="搜索记忆" value={query} onChange={e=>setQuery(e.target.value)}/></label><VStringSelect ariaLabel="记忆分类" value={category} onValueChange={setCategory} options={["全部","偏好与事实","经验与约定","任务经历"].map(value=>({value,label:value==="全部"?"全部":value}))}/></div><div className="memory-list">{items.map(m=><VButton contentLayout="plain" key={m.id} variant="ghost" aria-pressed={item?.id===m.id} className={`memory-row ${item?.id===m.id?"selected":""}`} onPress={()=>{setSelected(m.id);setSource(false);setRaw(false);setMobile(true);}}><span className="row-meta">{m.type}<time>{m.date}</time></span><strong>{m.title}</strong><span className="row-summary">{m.summary}</span>{m.state!=="有效"&&<span className="old">已替代 · 仅供追溯</span>}</VButton>)}{!items.length&&<div className="list-empty"><BookOpen size={26}/><strong>{query?"没有匹配的记忆":"尚未形成有效记忆"}</strong><p>{query?"试试搜索“中文”或清空筛选。":"初始化文件不计为有效记忆。"}</p>{query&&<VButton contentLayout="plain" variant="secondary" onPress={()=>setQuery("")}>清空搜索</VButton>}</div>}</div></section>;
 const reader=<section className="reader"><div className="reader-toolbar"><VButton contentLayout="plain" variant="ghost" className="back" onPress={()=>setMobile(false)}><ArrowLeft size={16}/>返回列表</VButton></div>{item?<><div className="reader-tabs"><VTabs aria-label="记忆查看方式" value={tab} onValueChange={setTab} items={[{id:"read",label:"正文"},{id:"sources",label:"来源与变化"},{id:"usage",label:"对话使用记录"}]}/></div><article className="article" key={`${agent}-${item.id}`}><div className="article-top"><span className="tag">{item.type}</span><span className={item.state==="有效"?"valid":"muted"}><CircleCheck size={13}/>{item.state}</span></div><h2>{item.title}</h2><p className="article-meta">更新于 {item.date} <span>·</span> {agents[agent].name}</p>{tab==="read"?<><p className="lead">{item.text}</p><h3>具体内容</h3><ul>{item.points.map(p=><li key={p}>{p}</li>)}</ul><div className="source-fold"><VButton contentLayout="plain" variant="ghost" aria-expanded={source} onPress={()=>setSource(!source)}><Link2 size={15}/>{item.source}<ChevronRight size={14} className={source?"rotated":""}/></VButton>{source&&<blockquote><span>来源片段 · 示例</span><p>“{item.quote}”</p></blockquote>}</div></>:tab==="sources"?<><h3>形成这条记忆的依据</h3><div className="evidence"><span className="evidence-icon"><Link2 size={18}/></span><div><strong>{item.source}</strong><p>对话来源 · 示例片段，不链接真实会话</p><blockquote>“{item.quote}”</blockquote></div></div><h3>变化记录</h3><div className="timeline"><History size={17}/><div><strong>{item.date} · 保存记忆</strong><p>这是模拟变化记录，正式版本需要后端历史证据。</p></div></div><VButton contentLayout="plain" variant="secondary" onPress={()=>setRaw(!raw)} aria-expanded={raw}>{raw?"收起原始记录":"查看原始记录"}</VButton>{raw&&<pre>{JSON.stringify({id:`demo-${item.id}`,body:item.text,status:item.state,source:"preview-fixture"},null,2)}</pre>}</>:<><h3>最近一次使用 · 示例</h3>{item.used?<><div className="usage-head"><span>设置页排版优化</span><span className="muted">第 8 轮</span></div><div className="timeline"><CircleCheck size={18}/><div><strong>检索召回</strong><p>检索结果包含这条记忆。</p></div></div><div className="timeline"><CircleCheck size={18}/><div><strong>已加入本轮上下文</strong><p>根据上下文组装记录标注，不能据此声称模型采纳。</p></div></div><div className="callout"><FileText size={18}/><p>以上为模拟证据。正式页面只显示实际记录到的阶段。</p></div></>:<div className="usage-empty"><History size={28}/><h3>暂未记录使用证据</h3><p>保存过不等于使用过。没有调用记录时，不显示虚构的使用次数或最近使用时间。</p></div>}</>}</article></>:<div className="empty-reader"><Brain size={34}/><h2>{query?"没有匹配的记忆":"从真实经历开始积累"}</h2><p>{query?"调整搜索条件后继续阅读。":"只有初始化模板时，不制造“已经记住”的假象。"}</p></div>}</section>;
 return <VuiProvider><div className={`preview ${mobile?"mobile-reading":""}`}><header className="app-header"><span className="brand"><Brain size={21}/>Vibelution</span><span className="header-divider"/><strong>记忆库</strong><span className="preview-label">交互预览 · 全部为示例数据</span></header><VSplitWorkspace className="workspace" columnsClassName="memory-columns" sidebar={rail} main={<VSplitWorkspace className="inner-workspace" columnsClassName="reader-columns" sidebar={library} main={reader}/>}/></div></VuiProvider>;
}
const root = createRoot(document.getElementById("root")!);
root.render(<App/>);
if (import.meta.hot) import.meta.hot.dispose(() => root.unmount());
