export default {
  page: "flex min-h-0 min-w-0 flex-1 flex-col gap-5 overflow-y-auto p-6",
  heading: "m-0 text-lg font-semibold",
  card: "grid min-w-0 gap-4 !border !border-[var(--vui-border-subtle)]",
  field: "grid min-w-0 gap-2 text-xs text-[var(--fg-secondary)]",
  actions: "flex min-w-0 flex-wrap items-end gap-3",
  examples: "grid min-w-0 gap-2",
  example: "!h-auto !justify-start !whitespace-normal !py-3 text-left",
  columns: "grid min-w-0 grid-cols-[minmax(160px,1fr)_minmax(0,2fr)] gap-4",
  list: "grid min-w-0 content-start gap-2",
  listItem: "!h-auto !min-w-0 !justify-start !whitespace-normal !py-3 text-left",
  title: "m-0 break-words text-sm font-semibold",
  small: "m-0 break-words text-xs leading-relaxed text-[var(--fg-tertiary)]",
  description: "m-0 line-clamp-2 break-words text-xs leading-relaxed text-[var(--fg-tertiary)]",
  text: "m-0 whitespace-pre-wrap break-words text-sm leading-7 text-[var(--fg-secondary)]",
  content: "m-0 max-h-[480px] overflow-auto whitespace-pre-wrap break-words text-xs leading-6 text-[var(--fg-secondary)]",
  selected: "!border-[var(--accent-cool)] !bg-[color-mix(in_srgb,var(--accent-cool)_8%,transparent)]",
  success: "text-sm text-[var(--state-success)]",
  warning: "text-sm text-[var(--state-warning)]",
  toolbar: "flex min-w-0 flex-wrap items-center justify-between gap-3",
  skill: "grid min-w-0 gap-2 text-left",
} as const;
