export default {
  panel: "grid min-w-0 grid-cols-[minmax(0,1fr)] gap-2 p-3",
  heading: "grid min-w-0 grid-cols-[minmax(0,1fr)] gap-0.5",
  headingLine: "flex min-w-0 items-center gap-2",
  caption: "text-[11px] text-[var(--fg-tertiary)]",
  title: "m-0 min-w-0 flex-1 truncate text-sm font-medium",
  status: "flex min-w-0 max-w-[65%] shrink-0 items-center gap-1.5 text-xs [&>svg]:shrink-0",
  statusLabel: "min-w-0 truncate font-medium",
  warning: "text-[var(--state-warning)]",
  running: "animate-spin motion-reduce:animate-none text-[var(--accent-cool)]",
  error: "text-[var(--state-error)]",
  success: "text-[var(--state-success)]",
  muted: "text-[var(--fg-tertiary)]",
  tools: "list-none grid min-w-0 grid-cols-[minmax(0,1fr)] gap-1 p-0 m-0",
  tool: "flex min-w-0 items-center gap-2 text-xs",
  runningTool: "shrink-0 animate-spin motion-reduce:animate-none text-[var(--accent-cool)]",
  pendingTool: "shrink-0 text-[var(--fg-tertiary)]",
  failedTool: "shrink-0 text-[var(--state-error)]",
  completedTool: "shrink-0 text-[var(--state-success)]",
  warningTool: "shrink-0 text-[var(--state-warning)]",
  warningStatus: "shrink-0 truncate text-[var(--state-warning)]",
  toolText: "flex min-w-0 flex-1 items-center gap-2",
  toolTitle: "min-w-0 flex-1 truncate font-medium",
  toolStatus: "shrink-0 truncate text-[var(--fg-tertiary)]",
  empty: "text-xs leading-5 text-[var(--fg-tertiary)] m-0",
  action: "!h-8 !min-h-8 !px-2.5 !py-1 text-xs",
  errorText: "block break-words",
} as const;
