export default {
  list: "grid min-w-0 grid-cols-[minmax(0,1fr)] gap-2",
  actionRow: "flex min-w-0 items-center gap-1 [&>button:first-child]:min-w-0 [&>button:first-child]:flex-1 [&>button:last-child]:shrink-0 [&>button:last-child]:!h-8 [&>button:last-child]:!w-8 [&>button:last-child]:!min-h-8 [&>button:last-child]:!min-w-8 [&>button:last-child]:!px-1 [&>button:last-child]:!py-1 [&>button:last-child]:!border-transparent [&>button:last-child]:!bg-transparent [&>button:last-child]:!shadow-none",
  filters: "flex min-w-0 flex-wrap gap-3 mb-3 [&>input]:min-w-0 [&>input]:flex-1",
  statusSelect: "max-w-[210px]",
  recordContent: "grid min-w-0 w-full grid-cols-[minmax(0,1fr)] gap-1",
  recordHeading: "flex min-w-0 w-full items-center gap-2",
  title: "min-w-0 flex-1 truncate text-xs font-medium",
  status: "inline-flex shrink-0 items-center justify-center",
  statusCompleted: "text-[var(--state-success)]",
  statusRunning: "animate-spin motion-reduce:animate-none text-[var(--accent-cool)]",
  statusStopped: "text-[var(--fg-tertiary)]",
  statusFailed: "text-[var(--state-error)]",
  statusWarning: "text-[var(--state-warning)]",
  statusIdle: "text-[var(--fg-tertiary)]",
  preview: "min-w-0 whitespace-pre-wrap break-words text-left text-xs leading-relaxed text-[var(--fg-tertiary)]",
  metadata: "shrink-0 whitespace-nowrap text-xs text-[var(--fg-tertiary)]",
  record: "!h-auto !w-full !max-w-full !justify-start text-left",
  compactRecord: "!min-h-8 !border-transparent !px-2 !py-1 !shadow-none hover:!bg-[var(--vui-control-muted)]",
  fullRecord: "!min-h-12 !px-2.5 !py-1.5",
  selectedRecord: "!bg-[color-mix(in_srgb,var(--accent-cool)_9%,transparent)]",
} as const;
