export default {
  page: "grid min-w-0 gap-5",
  header: "flex min-w-0 flex-wrap items-center justify-between gap-3",
  heading: "m-0 text-base font-semibold text-[var(--fg-primary)]",
  form: "grid min-w-0 gap-4",
  fields: "grid min-w-0 grid-cols-[repeat(auto-fit,minmax(min(100%,15rem),1fr))] gap-3",
  field: "grid min-w-0 content-start gap-2 text-xs text-[var(--fg-secondary)]",
  codes: "min-h-20 w-full resize-y",
  shortcuts: "flex min-w-0 flex-wrap items-center gap-2",
  hint: "m-0 text-xs text-[var(--fg-tertiary)]",
  error: "m-0 break-words text-xs text-[var(--state-error)]",
  success: "m-0 text-xs text-[var(--state-success)]",
  footer: "flex min-w-0 flex-wrap items-center justify-between gap-3",
  list: "grid min-w-0 gap-3",
  card: "grid min-w-0 gap-3 !border !border-[var(--vui-border-subtle)]",
  identity: "grid min-w-0 flex-1 gap-2",
  title: "break-words text-sm font-medium text-[var(--fg-primary)]",
  actions: "flex min-w-0 flex-wrap items-center gap-2",
  errorBox: "whitespace-pre-wrap break-words text-xs text-[var(--fg-secondary)]",
  tableWrap: "min-w-0 overflow-x-auto",
  table: "w-full border-collapse text-left text-xs [&_th]:pb-3 [&_th]:font-medium [&_th]:text-[var(--fg-tertiary)] [&_td]:border-t [&_td]:border-[var(--vui-border-subtle)] [&_td]:py-3 [&_td]:pr-3 [&_td]:align-top",
  stockCell: "whitespace-nowrap font-medium text-[var(--fg-primary)]",
  reason: "max-w-72 whitespace-pre-wrap break-words text-[var(--fg-tertiary)]",
} as const;
