const border = "border-[var(--vui-border-subtle)]";
const muted = "text-[var(--fg-tertiary)]";

export default {
  root: "grid min-w-0 gap-4",
  heading: "flex min-w-0 flex-wrap items-center justify-between gap-3",
  title: "m-0 text-base font-semibold text-[var(--fg-primary)]",
  meta: `text-xs ${muted}`,
  toolbar: `grid min-w-0 gap-3 rounded-[var(--vui-radius-soft)] border ${border} bg-[var(--vui-surface-row)] p-3`,
  filters: "grid min-w-0 grid-cols-2 gap-2 xl:grid-cols-5",
  field: "grid min-w-0 gap-1 text-xs text-[var(--fg-tertiary)]",
  input: "!h-9 !min-w-0 text-xs",
  actions: "flex min-w-0 flex-wrap items-center justify-between gap-2",
  actionGroup: "flex min-w-0 flex-wrap items-center gap-2",
  sort: "min-w-[10rem]",
  presetPanel: `flex min-w-0 flex-wrap items-end gap-2 rounded-[var(--vui-radius-soft)] border ${border} bg-[var(--vui-surface-row)] p-2.5`,
  presetName: "grid min-w-[12rem] flex-1 gap-1 text-xs text-[var(--fg-tertiary)]",
  presetSelect: "grid min-w-[12rem] flex-1 gap-1 text-xs text-[var(--fg-tertiary)]",
  presetCount: `ml-auto text-xs ${muted}`,
  presetMessage: "m-0 text-xs text-[var(--fg-secondary)]",
  warning: "m-0 text-xs text-[var(--state-warning)]",
  promptRow: "grid min-w-0 grid-cols-[minmax(0,1fr)_auto] items-end gap-2 border-t border-[var(--vui-border-subtle)] pt-3",
  promptField: "grid min-w-0 gap-1 text-xs text-[var(--fg-tertiary)]",
  coverage: "grid min-w-0 gap-2",
  coverageFacts: "flex min-w-0 flex-wrap gap-2 text-xs",
  coverageFact: `rounded border ${border} bg-[var(--vui-surface-row)] px-2 py-1 ${muted}`,
  tableWrap: "min-w-0 max-w-full overflow-x-auto",
  stockButton: "!h-auto !min-h-0 !max-w-full !justify-start !px-0.5 !py-0.5 text-left",
  stockCell: "grid min-w-0 gap-0.5",
  stockName: "truncate text-xs font-medium text-[var(--fg-primary)]",
  ticker: `font-mono text-[var(--vui-type-caption-size)] ${muted}`,
  positive: "font-mono text-[var(--state-error)]",
  negative: "font-mono text-[var(--state-success)]",
  number: "font-mono text-[var(--fg-primary)]",
  nullValue: `font-mono ${muted}`,
  source: `flex min-w-0 flex-wrap items-center justify-between gap-2 border-t ${border} pt-2 text-xs ${muted}`,
  paging: "flex min-w-0 items-center justify-between gap-2",
  prompt: `grid min-w-0 gap-3 rounded-[var(--vui-radius-soft)] border ${border} bg-[var(--vui-surface-panel)] p-3`,
  section: `grid min-w-0 gap-2 rounded-[var(--vui-radius-soft)] border ${border} bg-[var(--vui-surface-row)] p-3`,
  sectionHeader: "flex min-w-0 flex-wrap items-center justify-between gap-2",
  sectionTitle: "m-0 text-sm font-semibold text-[var(--fg-primary)]",
  list: "grid min-w-0 gap-1",
  listItem: `grid min-w-0 gap-1 border-t ${border} py-2 first:border-t-0`,
  itemTitle: "break-words text-sm font-medium text-[var(--fg-primary)]",
  itemTitleLink: "block break-words text-sm font-medium text-[var(--accent-cool)] underline-offset-2 hover:underline",
  itemMeta: `flex min-w-0 flex-wrap items-center gap-x-3 gap-y-1 text-xs ${muted}`,
  itemLink: "break-words text-[var(--accent-cool)] underline-offset-2 hover:underline",
  metrics: "grid min-w-0 grid-cols-1 gap-2 md:grid-cols-2 xl:grid-cols-3",
  metric: `grid min-w-0 gap-1 rounded border ${border} bg-[var(--vui-surface-row)] p-2`,
  metricLabel: `text-xs ${muted}`,
  metricValue: "break-words font-mono text-sm font-semibold text-[var(--fg-primary)]",
  metricMeta: `text-[var(--vui-type-caption-size)] ${muted}`,
} as const;
