const border = "border-[var(--vui-border-subtle)]";
const muted = "text-[var(--fg-tertiary)]";
export default {
  page: "grid min-h-0 min-w-0 content-start gap-4 overflow-y-auto overflow-x-hidden p-5 text-[var(--fg-primary)] 2xl:p-6",
  header: "flex min-w-0 flex-wrap items-center justify-between gap-3 border-b " + border + " pb-3",
  headingGroup: "grid min-w-0 gap-1 [&>h1]:m-0 [&>h1]:text-lg [&>h1]:font-semibold [&>p]:m-0 [&>p]:text-xs " + muted,
  eyebrow: "text-[10px] font-semibold uppercase tracking-[0.13em] text-[var(--fg-tertiary)]",
  headerActions: "flex shrink-0 items-center gap-2",
  setupPanel: "grid min-w-0 grid-cols-[minmax(0,1fr)_auto] items-start gap-3",
  setupCopy: "grid min-w-0 gap-1 [&>strong]:text-sm [&>span]:text-xs [&>span]:leading-relaxed " + muted,
  warning: "col-span-full m-0 break-words text-xs text-[var(--state-warning)]",
  roster: "col-span-full flex min-w-0 flex-wrap gap-x-4 gap-y-2 border-t border-[var(--vui-border-subtle)] pt-3",
  rosterItem: "flex items-center gap-1.5 text-xs text-[var(--fg-secondary)]",
  readyIcon: "shrink-0 text-[var(--state-success)]",
  pendingIcon: "shrink-0 text-[var(--fg-tertiary)]",
  controls: "flex min-w-0 flex-wrap items-end gap-3",
  stockIdentity: "mr-auto flex min-w-28 flex-col gap-1 pb-1 [&>strong]:truncate [&>strong]:text-sm [&>span]:font-mono [&>span]:text-xs " + muted,
  field: "grid min-w-32 gap-1 text-xs " + muted,
  history: "flex min-w-0 gap-2 overflow-x-auto pb-1",
  historyButton: "!h-auto !min-h-12 !min-w-48 !max-w-72 !justify-between !gap-3 !px-3 !py-2 text-left",
  historySelected: "!border-[var(--accent-cool)] !bg-[color-mix(in_srgb,var(--accent-cool)_8%,transparent)]",
  historyItem: "grid min-w-0 gap-1",
  runHeader: "flex min-w-0 flex-wrap items-end gap-3 border-b " + border + " pb-3 [&>div:first-child]:mr-auto [&>div:first-child]:grid [&>div:first-child]:gap-1 [&_h2]:m-0 [&_h2]:break-words [&_h2]:text-base [&_h2]:font-semibold",
  runMeta: "flex items-center gap-1.5",
  executionSummary: "max-w-full text-xs text-[var(--fg-tertiary)]",
  runActions: "flex flex-wrap items-center gap-2",
  progress: "flex min-w-0 flex-wrap items-center gap-2 text-xs " + muted + " [&>strong]:text-sm [&>strong]:text-[var(--fg-primary)]",
  analystGrid: "grid min-w-0 grid-cols-[repeat(auto-fit,minmax(min(100%,22rem),1fr))] gap-3",
  inspector: "grid min-w-0 content-start gap-4",
  inspectorMeta: "grid min-w-0 gap-1 text-xs text-[var(--fg-tertiary)] [&>strong]:break-words [&>strong]:text-sm [&>strong]:text-[var(--fg-primary)]",
  inspectorRow: "flex min-w-0 items-center justify-between gap-2 text-xs",
  analystCard: "flex min-h-44 min-w-0 flex-col gap-3 overflow-hidden",
  cardHeading: "flex min-w-0 items-center justify-between gap-2",
  roleTitle: "flex min-w-0 items-center gap-2 text-sm [&>h3]:m-0 [&>h3]:truncate [&>h3]:text-sm [&>h3]:font-semibold",
  activity: "m-0 max-h-12 overflow-hidden break-words rounded bg-[var(--vui-surface-inset)] px-2 py-1 text-xs leading-5 text-[var(--fg-secondary)]",
  answer: "min-h-0 max-h-[min(42vh,560px)] min-w-0 overflow-auto break-words rounded border border-[var(--vui-border-subtle)] bg-[var(--vui-surface-inset)] px-3 py-2 text-xs leading-6 text-[var(--fg-secondary)] [&_p:first-child]:mt-0 [&_p:last-child]:mb-0 [&_pre]:max-w-full [&_pre]:overflow-auto [&_table]:block [&_table]:max-w-full [&_table]:overflow-auto",
  placeholder: "m-0 min-h-12 flex-1 content-center text-xs leading-relaxed " + muted,
  cardActions: "mt-auto flex flex-wrap items-center gap-1 border-t border-[var(--vui-border-subtle)] pt-2 [&>button]:!min-h-8 [&>button]:!px-2 [&>button]:text-xs",
  synthesis: "grid min-w-0 gap-3",
  errorText: "block break-words",
} as const;
