export default {
  panel: "grid min-w-0 grid-cols-[minmax(0,1fr)] gap-5 p-4",
  caption: "text-xs text-[var(--fg-tertiary)]",
  title: "text-sm font-medium mt-2 mb-0 break-words",
  status: "flex items-center gap-2 text-sm",
  warning: "text-[var(--state-warning)]",
  running: "animate-spin motion-reduce:animate-none text-[var(--accent-cool)]",
  error: "text-[var(--state-error)]",
  success: "text-[var(--state-success)]",
  muted: "text-[var(--fg-tertiary)]",
  tools: "list-none grid min-w-0 grid-cols-[minmax(0,1fr)] gap-4 p-0 m-0",
  tool: "flex items-start gap-2.5 text-xs",
  runningTool: "shrink-0 animate-spin motion-reduce:animate-none text-[var(--accent-cool)]",
  pendingTool: "shrink-0 text-[var(--fg-tertiary)]",
  failedTool: "shrink-0 text-[var(--state-error)]",
  completedTool: "shrink-0 text-[var(--state-success)]",
  warningTool: "shrink-0 text-[var(--state-warning)]",
  warningStatus: "mt-1 mb-0 text-[var(--state-warning)]",
  toolText: "min-w-0 break-words [overflow-wrap:anywhere]",
  toolTitle: "font-medium",
  toolStatus: "mt-1 mb-0 text-[var(--fg-tertiary)]",
  empty: "text-xs leading-6 text-[var(--fg-tertiary)] m-0",
  errorText: "block break-words",
} as const;
