export default {
  root: "flex min-h-0 min-w-0 flex-1 flex-col overflow-hidden",
  controls: "shrink-0 px-3",
  newResearch: "!w-full !justify-start",
  search: "relative mt-3",
  searchIcon: "pointer-events-none absolute left-2.5 top-2 text-vui-fg-tertiary",
  searchInput: "!w-full !pl-8",
  collection: "flex shrink-0 items-center justify-between px-4 pb-1 pt-3",
  quiet: "!border-transparent !bg-transparent !shadow-none hover:!bg-[var(--vui-control-muted)]",
  collectionButton: "!h-6 !min-h-6 !px-0 !text-xs",
  count: "shrink-0 text-xs tabular-nums text-vui-fg-tertiary",
  list: "min-h-0 min-w-0 flex-1 overflow-y-auto px-2 pb-3",
  loading: "grid gap-2 py-2",
  skeleton: "h-8",
  section: "mb-3",
  sectionLabel: "px-2 pb-2 pt-2 text-xs text-vui-fg-tertiary",
  more: "!text-xs",
  footer: "shrink-0 border-t border-vui-border-subtle px-3 pb-3 pt-2",
  footerLabel: "px-1 pb-1.5 text-xs text-vui-fg-tertiary",
  groups: "grid grid-cols-2 gap-1",
  groupButton: "!w-full !justify-start !border-transparent !shadow-none",
  groupSelected: "!bg-[color-mix(in_srgb,var(--accent-cool)_9%,transparent)] !text-[var(--accent-cool)]",
  config: "mt-2 flex justify-end border-t border-vui-border-subtle pt-2",
  configLink: "!h-8 !min-h-8 !w-8 !px-0",
} as const;
