export default {
  root: "grid min-w-0 gap-3 p-3",
  heading: "flex min-w-0 items-center justify-between gap-3",
  titleGroup: "flex min-w-0 items-center gap-2",
  title: "m-0 truncate text-sm font-semibold text-vui-fg-primary",
  subtitle: "m-0 text-xs text-vui-fg-tertiary",
  headerActions: "flex shrink-0 items-center gap-1",
  section: "grid min-w-0 gap-2",
  sectionHeading: "m-0 flex items-center justify-between gap-2 text-xs font-semibold text-vui-fg-secondary",
  controls: "grid min-w-0 gap-2 rounded-[var(--radius-control)] border border-vui-border-hairline bg-vui-surface-panel p-2 xl:grid-cols-[minmax(0,1fr)_110px_130px_minmax(140px,1.4fr)_auto] xl:items-end",
  field: "grid min-w-0 gap-1 text-[11px] text-vui-fg-tertiary",
  input: "min-w-0",
  orderMeta: "flex flex-wrap items-center gap-x-3 gap-y-1 text-[11px] text-vui-fg-tertiary",
  orderError: "m-0 text-xs text-[var(--state-error)]",
  warning: "m-0 break-words text-xs text-[var(--state-warning)]",
  source: "flex flex-wrap items-center gap-x-3 gap-y-1 text-[11px] text-vui-fg-tertiary",
  positive: "font-medium text-[var(--state-success)]",
  negative: "font-medium text-[var(--state-error)]",
  neutral: "text-vui-fg-secondary",
  helper: "m-0 break-words text-[11px] leading-5 text-vui-fg-tertiary",
  calendar: "grid min-w-0 grid-cols-7 overflow-hidden rounded-[var(--radius-control)] border border-vui-border-hairline",
  weekday: "min-w-0 border-b border-r border-vui-border-hairline bg-vui-surface-toolbar px-2 py-1 text-center text-[11px] text-vui-fg-tertiary",
  calendarDay: "min-h-16 min-w-0 border-b border-r border-vui-border-hairline bg-vui-surface-panel p-1.5 text-left last:border-r-0",
  calendarDate: "block text-[11px] font-semibold text-vui-fg-secondary",
  calendarTrades: "mt-1 block text-[10px] text-vui-fg-tertiary",
  calendarResult: "mt-0.5 block truncate text-[11px] font-medium",
  blankDay: "min-h-16 border-b border-r border-vui-border-hairline bg-vui-surface-row last:border-r-0",
  dailyRow: "font-mono tabular-nums",
  recentOrders: "grid min-w-0 gap-1.5",
  recentOrder: "grid min-w-0 grid-cols-[minmax(0,1fr)_auto] gap-x-2 gap-y-1 border-b border-vui-border-hairline px-1 py-2 last:border-b-0",
  recentIdentity: "min-w-0 truncate text-xs font-medium text-vui-fg-primary",
  recentNumbers: "text-right text-xs font-mono tabular-nums text-vui-fg-secondary",
  recentReason: "col-span-full min-w-0 break-words text-[11px] text-vui-fg-tertiary",
  quotePrice: "font-mono tabular-nums text-vui-fg-primary",
  loading: "grid min-w-0 gap-2",
  loadingSurface: "h-24",
  loadingSkeleton: "h-20",
  openAction: "mt-2",
  warningIcon: "mr-1 inline",
  orderReason: "ml-2 text-vui-fg-tertiary",
  calendarToolbar: "flex min-w-0 items-center justify-between gap-2",
} as const;
