export default {
  header: "shrink-0 border-b border-[var(--vui-border-subtle)] px-6 pt-5 pb-4",
  compactHeader: "shrink-0 min-w-0 border-b border-[var(--vui-border-subtle)] px-6 py-3",
  compactName: "m-0 min-w-0 truncate text-sm font-semibold",
  compactPriceRow: "flex shrink-0 items-center gap-2 whitespace-nowrap tabular-nums",
  compactPrice: "text-lg font-semibold",
  compactChange: "inline-flex items-center gap-1 text-xs",
  compactProvider: "mt-1 min-w-0 truncate text-xs text-[var(--fg-tertiary)]",
  heading: "flex items-center justify-between gap-4",
  identity: "flex min-w-0 items-center gap-3",
  name: "m-0 text-xl font-semibold truncate",
  ticker: "text-sm font-mono text-[var(--fg-tertiary)]",
  actions: "flex shrink-0 items-center gap-2",
  priceHeading: "flex items-end justify-between gap-5 mt-3",
  refreshWarning: "mt-3",
  price: "text-3xl tracking-tight font-semibold",
  change: "flex items-center gap-1 pb-1 text-sm",
  changePercent: "ml-2",
  quoteState: "pb-1 text-xs",
  provider: "text-right text-xs leading-5 text-[var(--fg-tertiary)]",
  facts: "grid grid-cols-6 gap-4 mt-4 mb-0 text-xs tabular-nums",
  fact: "min-w-0",
  factLabel: "text-[var(--fg-tertiary)] mb-1.5",
  factValues: "m-0 flex flex-wrap gap-x-1 gap-y-1 font-medium text-[var(--fg-primary)]",
  number: "whitespace-nowrap",
  loadingPanel: "min-h-[370px] border border-[var(--vui-border-subtle)] rounded-lg",
  chartTitle: "text-sm",
  loadingSkeleton: "grid gap-6 pt-8",
  priceRow: "flex items-end gap-4 tabular-nums",
  rising: "text-[var(--state-error)]",
  falling: "text-[var(--state-success)]",
  unavailable: "text-[var(--fg-tertiary)]",
} as const;
