import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { parseDesktopCliArgs } from "../src/cli/desktopCli.js";
import {
  DESKTOP_LAUNCH_PROFILE_FILE,
  applyDesktopLaunchSettingsToEnvironment,
  resolveDesktopLaunchSettings
} from "../src/launch/desktopLaunchSettings.js";

function resolveWithFiles(input: {
  env?: NodeJS.ProcessEnv;
  argv?: string[];
  userDataRoot?: string;
  resourcesRoot?: string;
  files?: Record<string, string>;
}) {
  const userDataRoot = input.userDataRoot ?? "C:/Users/17533/AppData/Roaming/Vibelution";
  const resourcesRoot = input.resourcesRoot ?? "C:/Users/17533/Desktop/Vibelution/dist/desktop/win-unpacked/resources";
  const files = new Map(Object.entries(input.files ?? {}));
  return resolveDesktopLaunchSettings({
    env: input.env ?? {},
    cliArgs: parseDesktopCliArgs(input.argv ?? []),
    userDataRoot,
    resourcesRoot,
    readTextFile: (path) => files.get(path) ?? null
  });
}

describe("desktop launch settings", () => {
  it("loads a package launch profile as the default Electron entry context", () => {
    const resourcesRoot = "C:/Users/17533/Desktop/Vibelution/dist/desktop/win-unpacked/resources";
    const profilePath = join(resourcesRoot, DESKTOP_LAUNCH_PROFILE_FILE);

    const settings = resolveWithFiles({
      resourcesRoot,
      files: {
        [profilePath]: JSON.stringify({
          schemaVersion: 1,
          workspaceRoot: "C:/Users/17533/Desktop/Vibelution",
          operatorConfigPath: "C:/Users/17533/Documents/Vibelution/config/config.toml",
          pythonPath: "C:/Users/17533/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/python.exe"
        })
      }
    });

    expect(settings).toMatchObject({
      workspaceRoot: "C:/Users/17533/Desktop/Vibelution",
      configPath: "C:/Users/17533/Documents/Vibelution/config/config.toml",
      pythonPath: "C:/Users/17533/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/python.exe",
      profilePath,
      profileError: ""
    });
  });

  it("keeps CLI and environment values stronger than a package profile", () => {
    const resourcesRoot = "C:/package/resources";
    const profilePath = join(resourcesRoot, DESKTOP_LAUNCH_PROFILE_FILE);

    const settings = resolveWithFiles({
      argv: ["--workspace", "D:/FromCli/Vibelution", "--config", "D:/FromCli/config.toml"],
      env: { VIBELUTION_PYTHON_PATH: "D:/FromEnv/python.exe" },
      resourcesRoot,
      files: {
        [profilePath]: JSON.stringify({
          schemaVersion: 1,
          workspaceRoot: "D:/FromProfile/Vibelution",
          operatorConfigPath: "D:/FromProfile/config.toml",
          pythonPath: "D:/FromProfile/python.exe"
        })
      }
    });

    expect(settings.workspaceRoot).toBe("D:/FromCli/Vibelution");
    expect(settings.configPath).toBe("D:/FromCli/config.toml");
    expect(settings.pythonPath).toBe("D:/FromEnv/python.exe");

    expect(applyDesktopLaunchSettingsToEnvironment({ NODE_ENV: "production" }, settings)).toMatchObject({
      NODE_ENV: "production",
      VIBELUTION_WORKSPACE_ROOT: "D:/FromCli/Vibelution",
      VIBELUTION_CONFIG_PATH: "D:/FromCli/config.toml",
      VIBELUTION_PYTHON_PATH: "D:/FromEnv/python.exe"
    });
  });

  it("ignores malformed or non-string profile fields without leaking profile contents", () => {
    const userDataRoot = "C:/Users/17533/AppData/Roaming/Vibelution";
    const resourcesRoot = "C:/package/resources";
    const userProfilePath = join(userDataRoot, DESKTOP_LAUNCH_PROFILE_FILE);
    const resourceProfilePath = join(resourcesRoot, DESKTOP_LAUNCH_PROFILE_FILE);

    const settings = resolveWithFiles({
      userDataRoot,
      resourcesRoot,
      files: {
        [userProfilePath]: "{not-json",
        [resourceProfilePath]: JSON.stringify({
          schemaVersion: 1,
          workspaceRoot: 123,
          operatorConfigPath: ["secret-config-path"],
          pythonPath: null
        })
      }
    });

    expect(settings.workspaceRoot).toBe("");
    expect(settings.configPath).toBe("");
    expect(settings.pythonPath).toBe("");
    expect(settings.profilePath).toBe(resourceProfilePath);
    expect(settings.profileError).toBe("invalid_launch_profile_json");
    expect(settings.profileError).not.toContain("secret-config-path");
  });

  it("accepts UTF-8 BOM launch profiles generated by Windows packaging scripts", () => {
    const resourcesRoot = "C:/package/resources";
    const profilePath = join(resourcesRoot, DESKTOP_LAUNCH_PROFILE_FILE);

    const settings = resolveWithFiles({
      resourcesRoot,
      files: {
        [profilePath]: `\uFEFF${JSON.stringify({
          schemaVersion: 1,
          workspaceRoot: "C:/Users/17533/Desktop/Vibelution",
          operatorConfigPath: "C:/Users/17533/Documents/Vibelution/config/config.toml",
          pythonPath: "C:/Python/python.exe"
        })}`
      }
    });

    expect(settings.workspaceRoot).toBe("C:/Users/17533/Desktop/Vibelution");
    expect(settings.configPath).toBe("C:/Users/17533/Documents/Vibelution/config/config.toml");
    expect(settings.pythonPath).toBe("C:/Python/python.exe");
    expect(settings.profileError).toBe("");
  });
});
