/**
 * Settings-align wave 3 — bilingual settings copy table, extracted verbatim
 * from ConfigRoute.tsx (zero wording changes). Single import source for the
 * route shell, the section editor, and the extracted display panels.
 */

export type ConfigLanguage = "zh" | "en";

export const CONFIG_COPY = {
  zh: {
    pageTitle: "设置",
    subtitle: "结构化配置、模型资产与保存状态。启动设置在 Launcher 面板维护。",
    subtitleHint: "启动设置在 Launcher 面板维护；结构化编辑、完整配置检查和最终保存仍收口到外部 operator config.toml。",
    returnToAgents: "返回 Agent 配置",
    returnToSource: "返回来源页",
    loading: "正在加载统一配置工作区...",
    loadFailed: "配置工作区加载失败",
    migrationPreviewExpired: "预览已失效，请重新生成",
    sourceTitle: "保存与生效",
    sourceBody: "这里显示当前修改是否已经保存，以及哪些系统级设置需要重启后才会生效。",
    sourceBodyShort: "保存状态、配置路径和外部环境入口。",
    runtimeTitle: "进化审核方式",
    runtimeBody: "手工操作适合逐步确认；自动审查会让进化任务直接进入审核流程。",
    modelsTitle: "模型库",
    modelsBody: "这里只管理模型资产：服务商、模型名、密钥状态、能力检测和连通性测试。每个 Agent 的具体模型选择请到 Agent 管理中维护。",
    modelsBodyShort: "模型资产、密钥状态、能力检测和连通性。",
    draftTitle: "高级配置检查",
    draftBody: "检查整份当前配置；保存只写外部 operator config.toml。",
    diagnosticsTitle: "诊断与保存",
    diagnosticsBody: "同类问题按根因合并；先处理根因，再保存配置。",
    configPath: "配置路径",
    configStatus: "当前状态",
    rawToml: "当前外部 config.toml",
    rawTomlHint: "这里只读显示真实文件内容；修改并保存后会更新这里。",
    syncedDraft: "已和外部 config.toml 一致",
    unsavedDraft: "有未保存修改",
    refresh: "重新读取",
    validateDraft: "检查当前修改",
    resetDraft: "还原编辑文本",
    openEnvironment: "打开系统环境变量",
    openEnvironmentHint: "会打开 Windows 系统窗口，方便你自己查看当前使用了哪些 key。",
    openEnvironmentPending: "正在打开系统环境变量",
    openEnvironmentOpened: "已打开系统环境变量窗口。",
    saveConfig: "保存到外部配置",
    applying: "保存中",
    leaveGuardTitle: "还有未保存的设置",
    leaveGuardBody: "本次修改还没有保存到外部 operator config.toml。离开前要保存吗？",
    leaveGuardSave: "保存并离开",
    leaveGuardSaving: "保存后离开中",
    leaveGuardDiscard: "不保存离开",
    leaveGuardCancel: "取消",
    intakeMode: "默认审核方式",
    groupOverviewSaveTitle: "总览与保存",
    groupOverviewSaveSummary: "在一个页面查看保存状态、阻塞问题与建议动作，修复后直接保存。",
    groupWorkbenchTitle: "界面与工作台",
    groupWorkbenchSummary: "管理工作台行为、配色和背景；启动相关设置仍由 Launcher 维护。",
    groupAvatarPetTitle: "个人资料与桌宠",
    groupAvatarPetSummary: "统一设置显示名、终端形象与陪伴体；Web 用户头像在用户信息里维护，常用项直接展示，其余参数按需展开。",
    groupModelingTitle: "模型库",
    groupModelingSummary: "模型资产、服务商账号、密钥、能力检测和模型发现都在这里集中管理。",
    groupRuntimeContextTitle: "上下文与分析",
    groupRuntimeContextSummary: "全局上下文压缩放在主路径；分析数据目录仅在自定义存储时按需展开。",
    groupToolingTitle: "工具与诊断",
    groupToolingSummary: "日常联网与安全、健康诊断、日志追踪和高级维护分层管理。",
    healthTitle: "健康诊断中心",
    healthBody: "把会话入口、日志入口、最近信号、可清理建议和保护边界整理到同一个只读诊断面。",
    healthLoading: "正在整理日志 Helper...",
    healthEmpty: "当前没有可用日志 Helper。",
    healthRefresh: "重新诊断",
    healthPriority: "优先处理",
    healthQuickActions: "快速入口",
    healthEvidence: "证据",
    healthRecommended: "建议",
    healthRelatedFindings: "关联问题",
    healthNoFindings: "当前没有阻塞或注意项。",
    healthOpenLogs: "打开日志页",
    healthOpenChat: "打开会话页",
    healthOpenLauncher: "去 Launcher 维护",
    healthOpen: "打开",
    healthFiles: "文件",
    healthDirs: "目录",
    healthSessions: "会话",
    healthBusy: "运行中",
    healthFailed: "失败",
    healthStale: "缺时间",
    healthPhase: "阶段",
    healthLatest: "最近信号",
    healthUpdated: "更新时间",
    healthSize: "体量",
    healthProtected: "保护",
    healthMaintenanceAvailable: "可从 Launcher 维护",
    healthStatusOk: "正常",
    healthStatusWarning: "注意",
    healthStatusBlocked: "阻塞",
    healthMissing: "暂无日志文件",
    healthNotRecorded: "未记录",
    shortcutsTitle: "快捷键",
    shortcutsIntro: "点击「修改」后按下新组合键完成录制（Esc 取消 · Backspace 恢复默认）；「清除」写入显式空数组（未设置，不回退默认）。",
    shortcutsPersistence: "覆盖持久化到 localStorage 键 vibelution.shortcuts.overrides，与全局快捷键同一存储。",
    shortcutsEffectiveNow: "改键即时生效，无需重启；快捷键在应用全局生效，触发时走命令面板同一执行路径。",
    shortcutsResetAll: "恢复全部默认",
    shortcutsClose: "关闭",
    shortcutsStatusDefault: "默认",
    shortcutsStatusOverridden: "已覆盖",
    shortcutsStatusCleared: "已清除",
    shortcutsUnset: "未设置",
    shortcutsModify: "修改",
    shortcutsClear: "清除",
    shortcutsRestore: "恢复默认",
    shortcutsRecording: "录制中：请按下新组合键",
    shortcutsRecordingHint: "Esc 取消 · Backspace 恢复默认",
    shortcutsRecordingPending: "已收到修饰键，等待完整组合…",
    shortcutsRecordCancelled: "录制已取消，绑定未变更。",
    shortcutsRestoredByBackspace: "已恢复「{title}」的默认绑定（录制态 Backspace）。",
    shortcutsFilterPlaceholder: "过滤命令…",
    shortcutsFilterByKeystroke: "按键盘找",
    shortcutsFilterCapturing: "按下组合键…（Esc 退出）",
    shortcutsFilterClear: "清除按键过滤",
    shortcutsFilterUnknownKey: "无法识别的按键",
    shortcutsFilterNoTextMatch: "没有文本命中的命令",
    shortcutsFilterKeyUnbound: "该组合键未被任何命令占用",
    shortcutsInvalidNoModifier: "录制失败：普通字符键必须至少带一个修饰键（F 键、方向键等命名键允许裸键）。",
    shortcutsInvalidUnsupported: "录制失败：不支持的按键组合（主修饰键在归一中丢失），绑定未变更。",
    shortcutsBoundNotice: "已把 {binding} 绑定到「{title}」（覆盖为整组替换该命令的绑定）。",
    shortcutsReservedNotice: "拒绝：{binding} 是保留键（浏览器/编辑原生行为或组件固定交互），不能绑定为「{title}」的全局快捷键。",
    shortcutsOccupiedNotice: "拒绝：{binding} 已被「{owner}」占用。请换一个组合，或抢占该键。",
    shortcutsSteal: "抢占并绑定",
    shortcutsStealHint: "抢占会把「{owner}」变为未绑定，并把 {binding} 绑定到「{title}」。",
    shortcutsStealDone: "已把 {binding} 绑定到「{title}」，「{owner}」变为未绑定。",
    shortcutsClearedNotice: "已清除「{title}」的全部绑定（显式空数组 = 未设置，不回退默认）。",
    shortcutsRestoredNotice: "「{title}」已移除用户覆盖，恢复默认绑定。",
    shortcutsResetAllNotice: "已恢复全部默认绑定，并清除持久化覆盖。",
    settingsStatusTitle: "设置状态",
    settingsNextStep: "下一步",
    settingsCanSave: "可以保存",
    settingsNeedsCheck: "先检查高级配置",
    settingsSynced: "已同步",
    settingsSections: "分区",
    developerModeReadonly: "开发者模式",
    developerModeControlled: "Launcher 控制",
    developerModeEnabled: "已开启",
    developerModeDisabled: "已关闭",
    runtimeProfile: "运行档位",
    defaultMode: "默认模式",
    defaultRoute: "默认入口",
    modelEditorCreate: "新增模型",
    modelEditorEdit: "编辑模型",
    modelCenterAccounts: "服务商账号",
    modelCenterInventory: "模型库存",
    modelCenterHealth: "状态",
    modelCenterModels: "可选模型",
    modelCenterCapabilityIssues: "需关注",
    modelCenterActions: "操作",
    modelCenterProtocol: "协议链路",
    modelScenario: "新增方式",
    modelScenarioChat: "通用对话模型",
    modelScenarioRelay: "中转站模型",
    modelScenarioImage: "图片工具模型",
    modelScenarioLocal: "本地模型",
    modelScenarioManual: "高级手填",
    modelScenarioHint: "选择场景会自动套用最接近的模板；服务商、模型名和密钥仍可以在下方调整。",
    preset: "厂商",
    providerVendor: "厂商",
    providerTemplate: "模板",
    providerTemplatePlaceholder: "选择模板",
    presetGroupOfficial: "官方供应商",
    presetGroupRelay: "Relay Responses",
    presetGroupOpenAiCompatible: "OpenAI 兼容 API",
    presetGroupLocal: "本地模型",
    customEntry: "手填",
    autoValue: "自动生成",
    modelId: "模型 ID",
    label: "显示名",
    modelName: "模型名",
    discoverModels: "发现模型",
    discoveryPending: "发现模型中",
    discoveredModel: "发现结果",
    discoveryEmpty: "没有发现可用模型",
    discoveryFailed: "模型发现失败",
    discoveryUnavailable: "当前服务商不支持自动发现，请手动填写模型名。",
    providerKind: "服务商类型",
    providerKeyEnv: "服务商默认变量",
    modelKeyEnv: "模型唯一变量",
    modelKeyInput: "API Key",
    keyStorageHint: "填写后先进入本次修改；点击“保存到外部配置”时才会写入本机用户级环境变量。",
    keyEnvAdvancedHint: "模型密钥变量名由模型 ID 唯一生成并只读展示；真正填写的是 API Key，保存时写入这个用户级环境变量。服务商默认变量仅作兼容来源展示，不作为新增密钥入口。",
    deleteModelHint: "删除模型会同步清理该模型唯一绑定的环境密钥；Agent 与工具的模型选择请在各自管理页调整。",
    deleteModelConfirm: "确认删除这个模型？这会清理它绑定的环境密钥，并从模型库移除该资产。",
    baseUrl: "基础地址",
    compatMode: "兼容模式",
    providerApi: "Provider API",
    modelProtocol: "模型协议",
    modelCompat: "兼容策略对象",
    contextWindow: "上下文窗口（必填，禁止默认）",
    requiresApiKey: "需要 API Key",
    imageInputSupport: "图像输入",
    imageInputSupportUnknown: "未声明",
    imageInputSupportSupported: "支持",
    imageInputSupportUnsupported: "不支持",
    transport: "传输协议",
    contract: "交互契约",
    reasoningStateField: "推理状态字段",
    toolCallingMode: "工具调用",
    promptCacheMode: "Prompt cache",
    strictCompatibility: "严格兼容",
    streaming: "流式",
    discoveryEnabled: "发现能力",
    temperature: "温度",
    maxOutputTokens: "最大输出令牌数",
    timeout: "超时（秒）",
    connectTimeout: "连接超时（秒）",
    clearSecret: "保存时同时清除这个环境变量里的密钥",
    saveModel: "确认模型修改",
    modelRequiredFieldsMissing: "请先填写模型名和基础地址。",
    deleteModel: "删除模型",
    cancelEditing: "清空表单",
    modelTestSelect: "测试模型",
    modelTestPlaceholder: "选择一个模型",
    testSelectedLibraryModel: "测试选中模型",
    modelTestRequired: "请先选择要测试的模型。",
    checkSavedImageCapabilities: "检测已保存模型图像输入",
    imageCapabilityCheckPending: "检测模型能力中",
    imageCapabilityStatus: "图像能力",
    imageInputStatusUnknown: "图像未检测",
    imageInputStatusSupported: "支持图像输入",
    imageInputStatusUnsupported: "不支持图像输入",
    imageInputStatusFailed: "检测失败",
    expandSection: "展开内容",
    collapseSection: "收起内容",
    keyConfigured: "已配置",
    keyPending: "待写入",
    keyClearPending: "待清除",
    keyMissing: "缺失",
    noBlocking: "当前没有阻塞问题。",
    noWarnings: "当前没有警告。",
    noSuggestions: "当前没有额外建议动作。",
    blockingIssues: "阻塞问题",
    warningSignals: "警告信号",
    suggestedActions: "建议动作",
    rootCauseMetric: "根因",
    affectedReferenceMetric: "受影响引用",
    warningMetric: "警告",
    affectedReferences: "受影响的配置引用",
    showAffectedReferences: "查看受影响引用",
    repairProviderCredential: "设置 API Key",
    editorDirtyHint: "编辑文本有未检查改动。先检查当前修改，再继续结构化编辑或测试。",
    editorCleanHint: "当前结构化面板和编辑文本一致。",
    editorRestoreHint: "放弃编辑文本里的未检查内容，并回到当前结构化面板。",
    saveSourceHint: "当前修改还没写入外部 operator config.toml，保存成功后这里会刷新为最新文件状态。",
    modelSavePending: "保存模型修改中",
    modelSaveFailed: "模型修改未生效：",
    modelEditorAdvancedTitle: "高级参数",
    modelEditorAdvancedHint: "常用字段已经在上方，只有需要时再展开这里。",
    testPending: "测试连接中",
    testScopeDraft: "按当前修改测试",
    testScopeSaved: "按已保存配置测试",
    testRouteLabel: "测试路由",
    testRuntimeLabel: "运行路径",
    testKeyLabel: "API key",
    testKeyNotRequired: "当前路由不要求",
    testKeySourceLabel: "来源",
    testCapabilityLabel: "能力",
    validationPending: "检查修改中",
    refreshPending: "重新读取中",
    editSection: "编辑分区",
    saveSection: "确认分区修改",
    cancelSection: "取消编辑",
    sectionSavePending: "保存分区修改中",
    rowStatusApplied: "已生效",
    rowStatusPending: "待保存",
    rowStatusWaiting: "等待中",
    rowStatusFailed: "未生效",
    settingsPendingCountUnit: " 项待保存",
    saveBlockedInvalid: "有格式不正确的修改，修正后才能保存",
    jsonValidHint: "✓ 格式正确",
    jsonInvalidPrefix: "格式有误：",
    jsonErrorAt: "（第",
    jsonErrorLine: "行，第",
    jsonErrorCol: "列）",
    numberRequired: "请输入数值",
    numberInvalidPrefix: "不是合法数字：",
    numberBelowMinInclusive: "不能小于 ",
    numberBelowMinExclusive: "必须大于 ",
    numberAboveMaxInclusive: "不能大于 ",
    numberAboveMaxExclusive: "必须小于 ",
    numberRangeHint: "范围",
    numberStepHint: "步进",
    listLinePrefix: "第",
    listLineMid: "行：",
    listInvalidToolName: "不是合法工具注册名（小写字母开头，仅小写字母/数字/下划线）",
    listDuplicateItem: "重复项",
    listBlankLineWarning: "空行会在保存时自动忽略",
    listWhitespaceWarning: "首尾空格会在保存时自动清理",
    uploadAvatarImage: "上传本地图片",
    clearAvatarImage: "清除图片",
    avatarImageUploading: "上传头像图片中",
    avatarImageUploadFailed: "头像图片上传失败：",
    avatarImageCurrent: "当前头像",
    avatarImageEmpty: "未设置头像图片",
    avatarImageClickToUpload: "点击头像上传",
    userProfileAvatarGroupTitle: "头像设置",
    userProfileAvatarGroupHint: "头像预设和本地头像图片只影响前端展示，不会把图片内容传给模型。",
    uploadThemeBackgroundImage: "上传背景图片",
    clearThemeBackgroundImage: "清除背景图片",
    themeBackgroundPresetTitle: "内置背景",
    themeBackgroundImageUploading: "上传背景图片中",
    themeBackgroundImageUploadFailed: "背景图片上传失败：",
    avatarCropTitle: "裁剪头像",
    avatarCropHint: "拖动图片调整位置，使用滑杆缩放；确认后会保存 1:1 裁剪结果。",
    avatarCropZoom: "缩放",
    avatarCropConfirm: "确认裁剪",
    avatarCropCancel: "取消裁剪",
    avatarCropPreview: "头像预览",
    fieldCountLabel: "字段",
    emptyValue: "空",
    itemLabel: "条目",
    yes: "是",
    no: "否",
  },
  en: {
    pageTitle: "Settings",
    subtitle: "Structured config, model assets, and save state. Startup settings are maintained in Launcher.",
    subtitleHint: "Startup settings are maintained in Launcher; structured editing, full-config checks, and final writes still converge on the external operator config.toml.",
    returnToAgents: "Return to Agent config",
    returnToSource: "Return to source page",
    loading: "Loading unified config workspace...",
    loadFailed: "Failed to load config workspace",
    migrationPreviewExpired: "The migration preview expired. Generate a new preview.",
    sourceTitle: "Save and Apply",
    sourceBody: "Shows whether current changes are saved and which system-level settings take effect after restart.",
    sourceBodyShort: "Save state, config path, and environment entry.",
    runtimeTitle: "Evolution review mode",
    runtimeBody: "Manual operation keeps each step under review; automatic review sends evolution tasks directly into the review flow.",
    modelsTitle: "Model Library",
    modelsBody: "This section manages model assets only: provider routes, model names, key state, capability checks, and connection tests. Edit each Agent's model choices in Agent management.",
    modelsBodyShort: "Model assets, key state, capability checks, and connectivity.",
    draftTitle: "Advanced Config Check",
    draftBody: "Inspect the full current config. Saves write only external operator config.toml.",
    diagnosticsTitle: "Diagnostics and Save",
    diagnosticsBody: "Related issues are grouped by root cause. Fix the cause first, then save.",
    configPath: "Config path",
    configStatus: "Current status",
    rawToml: "Current external config.toml",
    rawTomlHint: "This is a read-only view of the real file. It refreshes after you save changes.",
    syncedDraft: "Matches external config.toml",
    unsavedDraft: "Unsaved changes",
    refresh: "Reload",
    validateDraft: "Check changes",
    resetDraft: "Restore editor text",
    openEnvironment: "Open system environment variables",
    openEnvironmentHint: "Opens the Windows system dialog so you can inspect which keys are in use.",
    openEnvironmentPending: "Opening system environment variables",
    openEnvironmentOpened: "System environment variables window opened.",
    saveConfig: "Save to external config",
    applying: "Saving",
    leaveGuardTitle: "Unsaved settings",
    leaveGuardBody: "These changes have not been saved to the external operator config.toml. Save before leaving?",
    leaveGuardSave: "Save and leave",
    leaveGuardSaving: "Saving before leaving",
    leaveGuardDiscard: "Leave without saving",
    leaveGuardCancel: "Cancel",
    intakeMode: "Default review mode",
    groupOverviewSaveTitle: "Overview and Save",
    groupOverviewSaveSummary: "Review save state, blockers, and suggested actions in one place, then save after fixes.",
    groupWorkbenchTitle: "Workbench & Interface",
    groupWorkbenchSummary: "Manage workbench behavior, colors, and background here. Startup settings remain in Launcher.",
    groupAvatarPetTitle: "Profile & desktop pet",
    groupAvatarPetSummary: "Set the display name, terminal avatar, and companion in one place. The Web user avatar lives under User Info, while advanced parameters remain on demand.",
    groupModelingTitle: "Model Library",
    groupModelingSummary: "Manage model assets, provider accounts, keys, capability checks, and discovery in one place.",
    groupRuntimeContextTitle: "Context & Analysis",
    groupRuntimeContextSummary: "Keep global context compression on the main path and expand analysis data directories only for custom storage layouts.",
    groupToolingTitle: "Tooling and Diagnostics",
    groupToolingSummary: "Layer everyday access, health diagnostics, logging, tracing, and advanced maintenance.",
    healthTitle: "Health Diagnostics Center",
    healthBody: "Organizes session entry points, log entry points, recent signals, cleanup hints, and protected boundaries in one read-only diagnostic surface.",
    healthLoading: "Organizing log helpers...",
    healthEmpty: "No log helpers are available right now.",
    healthRefresh: "Run again",
    healthPriority: "Top findings",
    healthQuickActions: "Quick actions",
    healthEvidence: "Evidence",
    healthRecommended: "Recommendation",
    healthRelatedFindings: "Related findings",
    healthNoFindings: "No blocked or warning findings.",
    healthOpenLogs: "Open logs",
    healthOpenChat: "Open chat",
    healthOpenLauncher: "Open Launcher",
    healthOpen: "Open",
    healthFiles: "files",
    healthDirs: "dirs",
    healthSessions: "sessions",
    healthBusy: "busy",
    healthFailed: "failed",
    healthStale: "stale",
    healthPhase: "phase",
    healthLatest: "Latest signal",
    healthUpdated: "Updated",
    healthSize: "Size",
    healthProtected: "Protected",
    healthMaintenanceAvailable: "Launcher maintenance available",
    healthStatusOk: "OK",
    healthStatusWarning: "Attention",
    healthStatusBlocked: "Blocked",
    healthMissing: "No log files yet",
    healthNotRecorded: "Not recorded",
    shortcutsTitle: "Keyboard shortcuts",
    shortcutsIntro: "Click Change and press the new key combination to record it (Esc to cancel · Backspace to restore default). Clear writes an explicit empty array (not set, no fallback to defaults).",
    shortcutsPersistence: "Overrides persist to the localStorage key vibelution.shortcuts.overrides, the same storage the global shortcuts read.",
    shortcutsEffectiveNow: "Rebinds apply immediately without a restart; shortcuts work across the app through the same execution path as the command palette.",
    shortcutsResetAll: "Restore all defaults",
    shortcutsClose: "Close",
    shortcutsStatusDefault: "Default",
    shortcutsStatusOverridden: "Customized",
    shortcutsStatusCleared: "Cleared",
    shortcutsUnset: "Not set",
    shortcutsModify: "Change",
    shortcutsClear: "Clear",
    shortcutsRestore: "Restore default",
    shortcutsRecording: "Recording: press the new key combination",
    shortcutsRecordingHint: "Esc to cancel · Backspace to restore default",
    shortcutsRecordingPending: "Modifier received, waiting for the full combination…",
    shortcutsRecordCancelled: "Recording cancelled. No binding changed.",
    shortcutsRestoredByBackspace: "\"{title}\" default bindings restored (Backspace while recording).",
    shortcutsFilterPlaceholder: "Filter commands…",
    shortcutsFilterByKeystroke: "Find by key",
    shortcutsFilterCapturing: "Press a key combination… (Esc to exit)",
    shortcutsFilterClear: "Clear key filter",
    shortcutsFilterUnknownKey: "Unrecognized key",
    shortcutsFilterNoTextMatch: "No commands match the text",
    shortcutsFilterKeyUnbound: "No command uses this key combination",
    shortcutsInvalidNoModifier: "Recording failed: plain character keys need at least one modifier (named keys such as F-keys and arrows may be bare).",
    shortcutsInvalidUnsupported: "Recording failed: unsupported key combination (primary modifier lost in normalization). No binding changed.",
    shortcutsBoundNotice: "Bound {binding} to \"{title}\" (the override replaces all bindings of that command).",
    shortcutsReservedNotice: "Rejected: {binding} is a reserved key (native browser/editor behavior or fixed component interaction) and cannot be bound to \"{title}\".",
    shortcutsOccupiedNotice: "Rejected: {binding} is already used by \"{owner}\". Choose another combination, or steal the key.",
    shortcutsSteal: "Steal and bind",
    shortcutsStealHint: "Stealing unbinds \"{owner}\" and binds {binding} to \"{title}\".",
    shortcutsStealDone: "Bound {binding} to \"{title}\"; \"{owner}\" is now unset.",
    shortcutsClearedNotice: "Cleared all bindings of \"{title}\" (explicit empty array = not set, no fallback to defaults).",
    shortcutsRestoredNotice: "\"{title}\" overrides removed; default bindings restored.",
    shortcutsResetAllNotice: "All default bindings restored and persisted overrides cleared.",
    settingsStatusTitle: "Settings status",
    settingsNextStep: "Next step",
    settingsCanSave: "Ready to save",
    settingsNeedsCheck: "Check advanced config first",
    settingsSynced: "Synced",
    settingsSections: "Sections",
    developerModeReadonly: "Developer mode",
    developerModeControlled: "Launcher controlled",
    developerModeEnabled: "Enabled",
    developerModeDisabled: "Disabled",
    runtimeProfile: "Runtime mode",
    defaultMode: "Default mode",
    defaultRoute: "Default route",
    modelEditorCreate: "Create model",
    modelEditorEdit: "Edit model",
    modelCenterAccounts: "Provider accounts",
    modelCenterInventory: "Model inventory",
    modelCenterHealth: "Health",
    modelCenterModels: "Selectable models",
    modelCenterCapabilityIssues: "Attention",
    modelCenterActions: "Actions",
    modelCenterProtocol: "Protocol route",
    modelScenario: "Add as",
    modelScenarioChat: "General chat model",
    modelScenarioRelay: "Relay model",
    modelScenarioImage: "Image tool model",
    modelScenarioLocal: "Local model",
    modelScenarioManual: "Advanced manual",
    modelScenarioHint: "The scenario picks the closest template. Provider, model name, and key can still be adjusted below.",
    preset: "Vendor",
    providerVendor: "Vendor",
    providerTemplate: "Template",
    providerTemplatePlaceholder: "Choose a template",
    presetGroupOfficial: "Official providers",
    presetGroupRelay: "Relay Responses",
    presetGroupOpenAiCompatible: "OpenAI-compatible APIs",
    presetGroupLocal: "Local models",
    customEntry: "Manual",
    autoValue: "Auto",
    modelId: "Model ID",
    label: "Label",
    modelName: "Model",
    discoverModels: "Discover models",
    discoveryPending: "Discovering models",
    discoveredModel: "Discovered model",
    discoveryEmpty: "No models discovered",
    discoveryFailed: "Model discovery failed",
    discoveryUnavailable: "This provider does not support automatic discovery. Enter the model name manually.",
    providerKind: "Provider kind",
    providerKeyEnv: "Provider default variable",
    modelKeyEnv: "Unique model variable",
    modelKeyInput: "API key",
    keyStorageHint: "This is staged first. It is written to the local user environment only when you save to the external config.",
    keyEnvAdvancedHint: "The model key variable is uniquely generated from the model ID and shown read-only. Enter the API key value; saving writes it to this user environment variable. The provider default variable is compatibility-only display, not a new key entry point.",
    deleteModelHint: "Deleting a model also clears the unique environment key bound to that model. Adjust Agent and tool model choices in their own management pages.",
    deleteModelConfirm: "Delete this model? This clears its bound environment key and removes the asset from the model library.",
    baseUrl: "Base URL",
    compatMode: "Compat mode",
    providerApi: "Provider API",
    modelProtocol: "Model protocol",
    modelCompat: "Compat policy object",
    contextWindow: "Context window (required, no default)",
    requiresApiKey: "Requires API key",
    imageInputSupport: "Image input",
    imageInputSupportUnknown: "Undeclared",
    imageInputSupportSupported: "Supported",
    imageInputSupportUnsupported: "Unsupported",
    transport: "Transport",
    contract: "Contract",
    reasoningStateField: "Reasoning state field",
    toolCallingMode: "Tool calling",
    promptCacheMode: "Prompt cache",
    strictCompatibility: "Strict compatibility",
    streaming: "Streaming",
    discoveryEnabled: "Discovery enabled",
    temperature: "Temperature",
    maxOutputTokens: "Max output tokens",
    timeout: "Timeout (s)",
    connectTimeout: "Connect timeout (s)",
    clearSecret: "Also clear this environment key on save",
    saveModel: "Confirm model changes",
    modelRequiredFieldsMissing: "Enter the model name and base URL first.",
    deleteModel: "Delete model",
    cancelEditing: "Clear form",
    modelTestSelect: "Test model",
    modelTestPlaceholder: "Choose a model",
    testSelectedLibraryModel: "Test selected model",
    modelTestRequired: "Choose a model to test first.",
    checkSavedImageCapabilities: "Check saved models image input",
    imageCapabilityCheckPending: "Checking model capabilities",
    imageCapabilityStatus: "Image capability",
    imageInputStatusUnknown: "Image not checked",
    imageInputStatusSupported: "Supports image input",
    imageInputStatusUnsupported: "No image input",
    imageInputStatusFailed: "Check failed",
    expandSection: "Expand",
    collapseSection: "Collapse",
    keyConfigured: "configured",
    keyPending: "pending",
    keyClearPending: "clear pending",
    keyMissing: "missing",
    noBlocking: "No blocking issues right now.",
    noWarnings: "No warnings right now.",
    noSuggestions: "No extra suggested actions right now.",
    blockingIssues: "Blocking issues",
    warningSignals: "Warnings",
    suggestedActions: "Suggested actions",
    rootCauseMetric: "Root causes",
    affectedReferenceMetric: "Affected references",
    warningMetric: "Warnings",
    affectedReferences: "Affected config references",
    showAffectedReferences: "Show affected references",
    repairProviderCredential: "Set API Key",
    editorDirtyHint: "The editor text has unchecked changes. Check them before more structured edits or tests.",
    editorCleanHint: "Structured controls and editor text are in sync.",
    editorRestoreHint: "Discard unchecked editor text and return to the current structured panel.",
    saveSourceHint: "Save to the external config to persist the current changes.",
    modelSavePending: "Saving model changes",
    modelSaveFailed: "Model changes were not applied:",
    modelEditorAdvancedTitle: "Advanced parameters",
    modelEditorAdvancedHint: "The common fields are above. Expand this only when needed.",
    testPending: "Testing connection",
    testScopeDraft: "Testing current changes",
    testScopeSaved: "Testing saved config",
    testRouteLabel: "Route",
    testRuntimeLabel: "Runtime path",
    testKeyLabel: "API key",
    testKeyNotRequired: "not required for this route",
    testKeySourceLabel: "source",
    testCapabilityLabel: "Capability",
    validationPending: "Checking changes",
    refreshPending: "Reloading",
    editSection: "Edit section",
    saveSection: "Confirm section changes",
    cancelSection: "Cancel editing",
    sectionSavePending: "Saving section changes",
    rowStatusApplied: "Applied",
    rowStatusPending: "Pending save",
    rowStatusWaiting: "Waiting",
    rowStatusFailed: "Not applied",
    settingsPendingCountUnit: " pending",
    saveBlockedInvalid: "Some changes are invalid; fix them before saving",
    jsonValidHint: "✓ Correct format",
    jsonInvalidPrefix: "Format error: ",
    jsonErrorAt: " (line ",
    jsonErrorLine: ", column ",
    jsonErrorCol: ")",
    numberRequired: "Enter a number",
    numberInvalidPrefix: "Not a valid number: ",
    numberBelowMinInclusive: "Cannot be below ",
    numberBelowMinExclusive: "Must be greater than ",
    numberAboveMaxInclusive: "Cannot exceed ",
    numberAboveMaxExclusive: "Must be below ",
    numberRangeHint: "range",
    numberStepHint: "step",
    listLinePrefix: "Line ",
    listLineMid: ": ",
    listInvalidToolName: "Not a valid tool name (start with a lowercase letter; letters, digits, underscore only)",
    listDuplicateItem: "duplicate item",
    listBlankLineWarning: "Blank lines are ignored on save",
    listWhitespaceWarning: "Leading/trailing spaces are trimmed on save",
    uploadAvatarImage: "Upload local image",
    clearAvatarImage: "Clear image",
    avatarImageUploading: "Uploading avatar image",
    avatarImageUploadFailed: "Avatar image upload failed: ",
    avatarImageCurrent: "Current avatar",
    avatarImageEmpty: "No avatar image set",
    avatarImageClickToUpload: "Click avatar to upload",
    userProfileAvatarGroupTitle: "Avatar settings",
    userProfileAvatarGroupHint: "The avatar preset and local avatar image affect frontend display only. Image content is not sent to the model.",
    uploadThemeBackgroundImage: "Upload background image",
    clearThemeBackgroundImage: "Clear background image",
    themeBackgroundPresetTitle: "Built-in backgrounds",
    themeBackgroundImageUploading: "Uploading background image",
    themeBackgroundImageUploadFailed: "Background image upload failed: ",
    avatarCropTitle: "Crop avatar",
    avatarCropHint: "Drag the image to reposition it and use the slider to zoom. Confirm saves a 1:1 crop.",
    avatarCropZoom: "Zoom",
    avatarCropConfirm: "Confirm crop",
    avatarCropCancel: "Cancel crop",
    avatarCropPreview: "Avatar preview",
    fieldCountLabel: "fields",
    emptyValue: "Empty",
    itemLabel: "Item",
    yes: "Yes",
    no: "No",
  },
} as const;

export type ConfigCopy = Record<keyof (typeof CONFIG_COPY)["zh"], string>;
