/**
 * Settings-align wave 3 — bilingual settings copy table, extracted verbatim
 * from ConfigRoute.tsx (zero wording changes). Single import source for the
 * route shell, the section editor, and the extracted display panels.
 */

export type ConfigLanguage = "zh" | "en";

export const CONFIG_COPY = {
  zh: {
    pageTitle: "设置",
    subtitle: "结构化配置、模型资产与保存状态。启动设置在 Launcher 面板维护。",
    subtitleHint: "启动设置在 Launcher 面板维护；结构化编辑、完整配置检查和最终保存仍收口到外部 operator config.toml。",
    returnToAgents: "返回 Agent 配置",
    returnToSource: "返回来源页",
    loading: "正在加载统一配置工作区...",
    loadFailed: "配置工作区加载失败",
    migrationPreviewExpired: "预览已失效，请重新生成",
    sourceTitle: "保存与生效",
    sourceBody: "这里显示当前修改是否已经保存，以及哪些系统级设置需要重启后才会生效。",
    sourceBodyShort: "保存状态、配置路径和外部环境入口。",
    runtimeTitle: "进化审核方式",
    runtimeBody: "手工操作适合逐步确认；自动审查会让进化任务直接进入审核流程。",
    modelsTitle: "模型库",
    modelsBody: "这里只管理模型资产：服务商、模型名、密钥状态、能力检测和连通性测试。每个 Agent 的具体模型选择请到 Agent 管理中维护。",
    modelsBodyShort: "模型资产、密钥状态、能力检测和连通性。",
    draftTitle: "高级配置检查",
    draftBody: "检查整份当前配置；保存只写外部 operator config.toml。",
    diagnosticsTitle: "诊断与保存",
    diagnosticsBody: "同类问题按根因合并；先处理根因，再保存配置。",
    configPath: "配置路径",
    configStatus: "当前状态",
    rawToml: "当前外部 config.toml",
    rawTomlHint: "这里只读显示真实文件内容；修改并保存后会更新这里。",
    syncedDraft: "已和外部 config.toml 一致",
    unsavedDraft: "有未保存修改",
    refresh: "重新读取",
    validateDraft: "检查当前修改",
    resetDraft: "还原编辑文本",
    openEnvironment: "打开系统环境变量",
    openEnvironmentHint: "会打开 Windows 系统窗口，方便你自己查看当前使用了哪些 key。",
    openEnvironmentPending: "正在打开系统环境变量",
    openEnvironmentOpened: "已打开系统环境变量窗口。",
    saveConfig: "保存到外部配置",
    applying: "保存中",
    leaveGuardTitle: "还有未保存的设置",
    leaveGuardBody: "本次修改还没有保存到外部 operator config.toml。离开前要保存吗？",
    leaveGuardSave: "保存并离开",
    leaveGuardSaving: "保存后离开中",
    leaveGuardDiscard: "不保存离开",
    leaveGuardCancel: "取消",
    intakeMode: "默认审核方式",
    groupOverviewSaveTitle: "总览与保存",
    groupOverviewSaveSummary: "在一个页面查看保存状态、阻塞问题与建议动作，修复后直接保存。",
    groupWorkbenchTitle: "界面与工作台",
    groupWorkbenchSummary: "管理工作台行为、配色和背景；启动相关设置仍由 Launcher 维护。",
    groupAvatarPetTitle: "个人资料与桌宠",
    groupAvatarPetSummary: "统一设置显示名、终端形象与陪伴体；Web 用户头像在用户信息里维护，常用项直接展示，其余参数按需展开。",
    groupModelingTitle: "模型库",
    groupModelingSummary: "模型资产、服务商账号、密钥、能力检测和模型发现都在这里集中管理。",
    groupRuntimeContextTitle: "上下文与分析",
    groupRuntimeContextSummary: "全局上下文压缩放在主路径；分析数据目录仅在自定义存储时按需展开。",
    groupToolingTitle: "工具与诊断",
    groupToolingSummary: "日常联网与安全、健康诊断、日志追踪和高级维护分层管理。",
    healthTitle: "健康诊断中心",
    healthBody: "把会话入口、日志入口、最近信号、可清理建议和保护边界整理到同一个只读诊断面。",
    healthLoading: "正在整理日志 Helper...",
    healthEmpty: "当前没有可用日志 Helper。",
    healthRefresh: "重新诊断",
    healthPriority: "优先处理",
    healthQuickActions: "快速入口",
    healthEvidence: "证据",
    healthRecommended: "建议",
    healthRelatedFindings: "关联问题",
    healthNoFindings: "当前没有阻塞或注意项。",
    healthOpenLogs: "打开日志页",
    healthOpenChat: "打开会话页",
    healthOpenLauncher: "去 Launcher 维护",
    healthOpen: "打开",
    healthFiles: "文件",
    healthDirs: "目录",
    healthSessions: "会话",
    healthBusy: "运行中",
    healthFailed: "失败",
    healthStale: "缺时间",
    healthPhase: "阶段",
    healthLatest: "最近信号",
    healthUpdated: "更新时间",
    healthSize: "体量",
    healthProtected: "保护",
    healthMaintenanceAvailable: "可从 Launcher 维护",
    healthStatusOk: "正常",
    healthStatusWarning: "注意",
    healthStatusBlocked: "阻塞",
    healthMissing: "暂无日志文件",
    healthNotRecorded: "未记录",
    shortcutsTitle: "快捷键",
    shortcutsIntro: "点击「修改」后按下新组合键完成录制（Esc 取消 · Backspace 恢复默认）；「清除」写入显式空数组（未设置，不回退默认）。",
    shortcutsPersistence: "覆盖持久化到 localStorage 键 vibelution.shortcuts.overrides，与全局快捷键同一存储。",
    shortcutsEffectiveNow: "改键即时生效，无需重启；快捷键在应用全局生效，触发时走命令面板同一执行路径。",
    uiFontLabel: "界面字号",
    uiFontDescription: "调整整个工作台的文字大小（14–18，默认 16）。即时生效，仅本机：保存在浏览器 localStorage，不写入 config.toml。",
    uiFontDecrease: "减小界面字号",
    uiFontIncrease: "增大界面字号",
    shortcutsResetAll: "恢复全部默认",
    shortcutsClose: "关闭",
    shortcutsStatusDefault: "默认",
    shortcutsStatusOverridden: "已覆盖",
    shortcutsStatusCleared: "已清除",
    shortcutsUnset: "未设置",
    shortcutsModify: "修改",
    shortcutsClear: "清除",
    shortcutsRestore: "恢复默认",
    shortcutsRecording: "录制中：请按下新组合键",
    shortcutsRecordingHint: "Esc 取消 · Backspace 恢复默认",
    shortcutsRecordingPending: "已收到修饰键，等待完整组合…",
    shortcutsRecordCancelled: "录制已取消，绑定未变更。",
    shortcutsRestoredByBackspace: "已恢复「{title}」的默认绑定（录制态 Backspace）。",
    shortcutsFilterPlaceholder: "过滤命令…",
    shortcutsFilterByKeystroke: "按键盘找",
    shortcutsFilterCapturing: "按下组合键…（Esc 退出）",
    shortcutsFilterClear: "清除按键过滤",
    shortcutsFilterUnknownKey: "无法识别的按键",
    shortcutsFilterNoTextMatch: "没有文本命中的命令",
    shortcutsFilterKeyUnbound: "该组合键未被任何命令占用",
    shortcutsInvalidNoModifier: "录制失败：普通字符键必须至少带一个修饰键（F 键、方向键等命名键允许裸键）。",
    shortcutsInvalidUnsupported: "录制失败：不支持的按键组合（主修饰键在归一中丢失），绑定未变更。",
    shortcutsBoundNotice: "已把 {binding} 绑定到「{title}」（覆盖为整组替换该命令的绑定）。",
    shortcutsReservedNotice: "拒绝：{binding} 是保留键（浏览器/编辑原生行为或组件固定交互），不能绑定为「{title}」的全局快捷键。",
    shortcutsOccupiedNotice: "拒绝：{binding} 已被「{owner}」占用。请换一个组合，或抢占该键。",
    shortcutsSteal: "抢占并绑定",
    shortcutsStealHint: "抢占会把「{owner}」变为未绑定，并把 {binding} 绑定到「{title}」。",
    shortcutsStealDone: "已把 {binding} 绑定到「{title}」，「{owner}」变为未绑定。",
    shortcutsClearedNotice: "已清除「{title}」的全部绑定（显式空数组 = 未设置，不回退默认）。",
    shortcutsRestoredNotice: "「{title}」已移除用户覆盖，恢复默认绑定。",
    shortcutsResetAllNotice: "已恢复全部默认绑定，并清除持久化覆盖。",
    settingsStatusTitle: "设置状态",
    settingsNextStep: "下一步",
    settingsCanSave: "可以保存",
    settingsNeedsCheck: "先检查高级配置",
    settingsSynced: "已同步",
    settingsSections: "分区",
    developerModeReadonly: "开发者模式",
    developerModeControlled: "Launcher 控制",
    developerModeEnabled: "已开启",
    developerModeDisabled: "已关闭",
    runtimeProfile: "运行档位",
    defaultMode: "默认模式",
    defaultRoute: "默认入口",
    modelEditorCreate: "新增模型",
    modelEditorEdit: "编辑模型",
    modelCenterAccounts: "服务商账号",
    modelCenterInventory: "模型库存",
    modelCenterHealth: "状态",
    modelCenterModels: "可选模型",
    modelCenterCapabilityIssues: "需关注",
    modelCenterActions: "操作",
    modelCenterProtocol: "协议链路",
    modelScenario: "新增方式",
    modelScenarioChat: "通用对话模型",
    modelScenarioRelay: "中转站模型",
    modelScenarioImage: "图片工具模型",
    modelScenarioLocal: "本地模型",
    modelScenarioManual: "高级手填",
    modelScenarioHint: "选择场景会自动套用最接近的模板；服务商、模型名和密钥仍可以在下方调整。",
    preset: "厂商",
    providerVendor: "厂商",
    providerTemplate: "模板",
    providerTemplatePlaceholder: "选择模板",
    presetGroupOfficial: "官方供应商",
    presetGroupRelay: "Relay Responses",
    presetGroupOpenAiCompatible: "OpenAI 兼容 API",
    presetGroupLocal: "本地模型",
    customEntry: "手填",
    autoValue: "自动生成",
    modelId: "模型 ID",
    label: "显示名",
    modelName: "模型名",
    discoverModels: "发现模型",
    discoveryPending: "发现模型中",
    discoveredModel: "发现结果",
    discoveryEmpty: "没有发现可用模型",
    discoveryFailed: "模型发现失败",
    discoveryUnavailable: "当前服务商不支持自动发现，请手动填写模型名。",
    providerKind: "服务商类型",
    providerKeyEnv: "服务商默认变量",
    modelKeyEnv: "模型唯一变量",
    modelKeyInput: "API Key",
    keyStorageHint: "填写后先进入本次修改；点击“保存到外部配置”时才会写入本机用户级环境变量。",
    keyEnvAdvancedHint: "模型密钥变量名由模型 ID 唯一生成并只读展示；真正填写的是 API Key，保存时写入这个用户级环境变量。服务商默认变量仅作兼容来源展示，不作为新增密钥入口。",
    deleteModelHint: "删除模型会同步清理该模型唯一绑定的环境密钥；Agent 与工具的模型选择请在各自管理页调整。",
    deleteModelConfirm: "确认删除这个模型？这会清理它绑定的环境密钥，并从模型库移除该资产。",
    baseUrl: "基础地址",
    compatMode: "兼容模式",
    providerApi: "Provider API",
    modelProtocol: "模型协议",
    modelCompat: "兼容策略对象",
    contextWindow: "上下文窗口（必填，禁止默认）",
    requiresApiKey: "需要 API Key",
    imageInputSupport: "图像输入",
    imageInputSupportUnknown: "未声明",
    imageInputSupportSupported: "支持",
    imageInputSupportUnsupported: "不支持",
    transport: "传输协议",
    contract: "交互契约",
    reasoningStateField: "推理状态字段",
    toolCallingMode: "工具调用",
    promptCacheMode: "Prompt cache",
    strictCompatibility: "严格兼容",
    streaming: "流式",
    discoveryEnabled: "发现能力",
    temperature: "温度",
    maxOutputTokens: "最大输出令牌数",
    timeout: "超时（秒）",
    connectTimeout: "连接超时（秒）",
    clearSecret: "保存时同时清除这个环境变量里的密钥",
    saveModel: "确认模型修改",
    modelRequiredFieldsMissing: "请先填写模型名和基础地址。",
    deleteModel: "删除模型",
    cancelEditing: "清空表单",
    modelTestSelect: "测试模型",
    modelTestPlaceholder: "选择一个模型",
    testSelectedLibraryModel: "测试选中模型",
    modelTestRequired: "请先选择要测试的模型。",
    checkSavedImageCapabilities: "检测已保存模型图像输入",
    imageCapabilityCheckPending: "检测模型能力中",
    imageCapabilityStatus: "图像能力",
    imageInputStatusUnknown: "图像未检测",
    imageInputStatusSupported: "支持图像输入",
    imageInputStatusUnsupported: "不支持图像输入",
    imageInputStatusFailed: "检测失败",
    expandSection: "展开内容",
    collapseSection: "收起内容",
    keyConfigured: "已配置",
    keyPending: "待写入",
    keyClearPending: "待清除",
    keyMissing: "缺失",
    noBlocking: "当前没有阻塞问题。",
    noWarnings: "当前没有警告。",
    noSuggestions: "当前没有额外建议动作。",
    blockingIssues: "阻塞问题",
    warningSignals: "警告信号",
    suggestedActions: "建议动作",
    rootCauseMetric: "根因",
    affectedReferenceMetric: "受影响引用",
    warningMetric: "警告",
    affectedReferences: "受影响的配置引用",
    showAffectedReferences: "查看受影响引用",
    repairProviderCredential: "设置 API Key",
    editorDirtyHint: "编辑文本有未检查改动。先检查当前修改，再继续结构化编辑或测试。",
    editorCleanHint: "当前结构化面板和编辑文本一致。",
    editorRestoreHint: "放弃编辑文本里的未检查内容，并回到当前结构化面板。",
    saveSourceHint: "当前修改还没写入外部 operator config.toml，保存成功后这里会刷新为最新文件状态。",
    modelSavePending: "保存模型修改中",
    modelSaveFailed: "模型修改未生效：",
    modelEditorAdvancedTitle: "高级参数",
    modelEditorAdvancedHint: "常用字段已经在上方，只有需要时再展开这里。",
    testPending: "测试连接中",
    testScopeDraft: "按当前修改测试",
    testScopeSaved: "按已保存配置测试",
    testRouteLabel: "测试路由",
    testRuntimeLabel: "运行路径",
    testKeyLabel: "API key",
    testKeyNotRequired: "当前路由不要求",
    testKeySourceLabel: "来源",
    testCapabilityLabel: "能力",
    validationPending: "检查修改中",
    refreshPending: "重新读取中",
    editSection: "编辑分区",
    saveSection: "确认分区修改",
    cancelSection: "取消编辑",
    sectionSavePending: "保存分区修改中",
    rowStatusApplied: "已生效",
    rowStatusPending: "待保存",
    rowStatusWaiting: "等待中",
    rowStatusFailed: "未生效",
    settingsPendingCountUnit: " 项待保存",
    saveBlockedInvalid: "有格式不正确的修改，修正后才能保存",
    jsonValidHint: "✓ 格式正确",
    jsonInvalidPrefix: "格式有误：",
    jsonErrorAt: "（第",
    jsonErrorLine: "行，第",
    jsonErrorCol: "列）",
    numberRequired: "请输入数值",
    numberInvalidPrefix: "不是合法数字：",
    numberBelowMinInclusive: "不能小于 ",
    numberBelowMinExclusive: "必须大于 ",
    numberAboveMaxInclusive: "不能大于 ",
    numberAboveMaxExclusive: "必须小于 ",
    numberRangeHint: "范围",
    numberStepHint: "步进",
    listLinePrefix: "第",
    listLineMid: "行：",
    listInvalidToolName: "不是合法工具注册名（小写字母开头，仅小写字母/数字/下划线）",
    listDuplicateItem: "重复项",
    listBlankLineWarning: "空行会在保存时自动忽略",
    listWhitespaceWarning: "首尾空格会在保存时自动清理",
    uploadAvatarImage: "上传本地图片",
    clearAvatarImage: "清除图片",
    avatarImageUploading: "上传头像图片中",
    avatarImageUploadFailed: "头像图片上传失败：",
    avatarImageCurrent: "当前头像",
    avatarImageEmpty: "未设置头像图片",
    avatarImageClickToUpload: "点击头像上传",
    userProfileAvatarGroupTitle: "头像设置",
    userProfileAvatarGroupHint: "头像预设和本地头像图片只影响前端展示，不会把图片内容传给模型。",
    uploadThemeBackgroundImage: "上传背景图片",
    clearThemeBackgroundImage: "清除背景图片",
    themeBackgroundPresetTitle: "内置背景",
    themeBackgroundImageUploading: "上传背景图片中",
    themeBackgroundImageUploadFailed: "背景图片上传失败：",
    avatarCropTitle: "裁剪头像",
    avatarCropHint: "拖动图片调整位置，使用滑杆缩放；确认后会保存 1:1 裁剪结果。",
    avatarCropZoom: "缩放",
    avatarCropConfirm: "确认裁剪",
    avatarCropCancel: "取消裁剪",
    avatarCropPreview: "头像预览",
    fieldCountLabel: "字段",
    emptyValue: "空",
    itemLabel: "条目",
    yes: "是",
    no: "否",
    cancel: "取消",
    navResizeSeparator: "设置导航宽度",
    navCollapse: "收起设置导航",
    navExpand: "展开设置导航",
    statusUnsaved: "有未保存修改",
    statusSaved: "配置已保存",
    searchPetTitle: "桌面宠物",
    searchPetDetail: "开启或关闭桌面宠物",
    searchPetHaystack: "桌宠 桌面宠物 开启 关闭 desktop pet",
    searchPetTitleHaystack: "桌面宠物 桌宠",
    intakeAuto: "自动审查",
    intakeManual: "手工操作",
    modelsActionsAria: "模型连接操作",
    advancedSettings: "高级设置",
    collapseAdvancedSettings: "收起高级设置",
    advancedSettingsHint: "模板向导、迁移与底层参数。",
    backToConfiguredProviders: "返回已配置服务",
    routeEditSectionTitle: "服务地址与协议",
    routeEditActionsAria: "Provider 路由编辑操作",
    routePreviewPending: "生成预览中…",
    routePreviewAction: "预览替换影响",
    routeFieldBaseUrl: "服务地址",
    routeFieldDriver: "接口类型",
    routeFieldProtocol: "请求协议",
    routeEditWarning: "保存前会检查哪些模型和 Agent 受到影响，请确认后再应用。",
    routeConfirmChangedTitle: "确认连接修改",
    routeConfirmUnchangedTitle: "连接没有变化",
    routeReferenceCountUnit: " 处引用",
    routeConfirmActionsAria: "Provider 路由替换确认",
    routeApplyPending: "更新中…",
    routeConfirmAction: "确认并更新连接",
    routeConfirmBody: "以上模型和引用会使用新的连接设置。确认前请核对服务地址与协议。",
    registryTabConnection: "连接",
    registryTabModels: "模型库 · 固定",
    registryTabProtocols: "协议与能力",
    registryTabDiagnostics: "诊断",
    registryFilterAll: "全部",
    registryFilterPinned: "已添加",
    registryFilterDiscovered: "添加模型",
    testRecoveryAuth: "请在连接设置中检查 API Key。",
    testRecoveryRateLimited: "请求受到限流，请稍后重试；若持续出现，请检查服务额度。",
    testRecoveryNetwork: "无法连接服务，请检查网络和服务是否启动。",
    testRecoveryTimeout: "服务响应超时，请稍后重试并检查服务负载。",
    testRecoveryUnavailable: "上游服务暂不可用，请稍后重试或切换服务。",
    testRecoveryNotFound: "请核对模型名称与服务地址，必要时刷新模型目录。",
    testRecoveryDefault: "请查看错误详情，核对请求参数后重试。",
    providerStatusReachable: "目录已更新",
    providerStatusStale: "目录待更新",
    providerStatusNotDiscovered: "尚未发现模型",
    providerStatusConfigured: "已配置",
    providerStatusAuthFailed: "认证失败",
    providerStatusDiscoveryFailed: "模型发现失败",
    providerStatusProtocolMismatch: "协议不匹配",
    providerStatusBlocked: "已阻塞",
    providerStatusObserved: "已发现",
    providerStatusPinned: "已添加",
    providerStatusMissingRemote: "已添加 · 最新目录未收录",
    providerStatusDisabled: "已禁用",
    discoveryErrTimeout: "请求超时",
    discoveryErrNetwork: "网络不可达",
    discoveryErrCredentialMissing: "未配置凭据",
    discoveryErrAuthFailed: "认证失败",
    discoveryErrEndpointInvalid: "服务地址无效",
    discoveryErrProtocolMismatch: "协议不兼容",
    discoveryErrInvalidResponse: "返回格式不兼容",
    discoveryErrRateLimited: "上游限流",
    discoveryErrUpstreamRejected: "上游拒绝请求",
    discoveryErrUnavailable: "上游暂不可用",
    discoveryErrBlocked: "访问被阻止",
    discoveryErrOther: "发现失败",
    discoveryErrNone: "无",
    reasoningDepthPrefix: "思考深度: ",
    reasoningMissingLabel: "思考深度: 未配置",
    reasoningDeclaredDetail: "协议已声明 · 默认 {default} · adapter {adapter}",
    reasoningVerifiedDetail: "已验证 · adapter {adapter}",
    reasoningMissingDetail: "固定后可写 pin defaults.reasoning_effort_values，或对 Responses 模型点「验证推理 low/high」",
    capabilityUnobserved: "能力未观测",
    capabilityCheckedAtMissing: "未记录时间",
    capabilityValueUnknown: "unknown（未知）",
    capabilityValueUnsupported: "unsupported（不支持）",
    checklistAria: "配置进度",
    checklistDone: "完成",
    checklistOptional: "可选",
    checklistTodo: "待办",
    checklistNextPrefix: "下一步：",
    checklistNextPinHint: "（在下方「已固定 / 已发现」中固定对话模型）",
    checklistNextCredentialHint: "（点「设置 API Key」）",
    checklistNextConnectionHint: "（点「发现」或检查路由）",
    checklistAllDone: "本 Provider 基础配置已完成。固定的模型可在 Agent 中选用。",
    actionPinDisabledReason: "当前配置操作不可用",
    actionPinHint: "固定后写入模型库，保存配置即可在 Agent 中选用",
    actionPinLabel: "固定到配置",
    actionUnpinLabel: "取消固定",
    actionInUseLabel: "使用中",
    actionUnavailableLabel: "不可用",
    actionUnpinnableLabel: "不可固定",
    checklistCredentialLabel: "API Key / 凭据已就绪",
    checklistConnectionLabel: "连接可达或已配置",
    checklistPinLabel: "至少固定 1 个对话模型",
    checklistReasoningLabel: "（可选）为已固定模型声明思考深度",
    apiKeyRowLabel: "API 密钥",
    apiKeySharedHint: "此供应商下的模型共用一把密钥；已保存的密钥不会回显。",
    apiKeyNotRequiredHint: "此服务无需 API Key。",
    updateApiKey: "更新 API Key",
    enterApiKey: "填写 API Key",
    noKeyNeeded: "无需 Key",
    newApiKeyPlaceholder: "输入新的 API Key",
    apiKeyActionsAria: "API Key 操作",
    saveKey: "保存 Key",
    contextLimitRowLabel: "默认上下文上限",
    contextLimitRowHint: "供应商级兜底值，仅在模型没有独立上限时使用。",
    useModelDeclared: "使用模型声明",
    adjustContextDetails: "调整上限与部署详情",
    contextWindowFieldLabel: "上下文窗口",
    contextWindowExample: "例如 128000",
    saveContextWindow: "保存上下文窗口",
    driverPrefix: "驱动：",
    notConfigured: "未配置",
    runtimeFrameworkPrefix: "运行框架：",
    unknownValue: "未知",
    artifactFilePrefix: "模型文件：",
    modelsEmptyCatalog: "还没有模型目录，请点击「发现模型」获取。",
    modelsEmptyPinned: "还没有添加模型。切换到「添加模型」，选择需要使用的模型。",
    modelsEmptyDiscovered: "没有待添加模型。可刷新模型目录，或查看「已添加」。",
    modelsEmptyNoMatch: "没有匹配的模型。请调整搜索或筛选条件。",
    verificationHeader: "最近测试",
    verifyErrTimeout: "超时",
    verifyErrBadRequest: "上游 400 拒绝",
    verifyErrAuthFailed: "鉴权失败",
    verifyErrRateLimited: "限流",
    verifyErrNotFound: "模型不存在",
    verifyErrNetwork: "网络错误",
    verifyErrMissingCredential: "缺 Key",
    verifyErrUnavailable: "上游不可用",
    verifyUntested: "未测试",
    verifyPassed: "测试通过",
    verifyFailed: "测试失败",
    verifyRequestFailed: "请求未成功",
    verifyErrorDetails: "错误详情",
    columnModelRef: "模型引用",
    columnUpstreamId: "上游 ID",
    columnAvailability: "可用性",
    columnCapabilities: "能力来源",
    columnActions: "操作",
    modelActionsAriaSuffix: " 模型操作",
    imageProbeHint: "发送一张最小有效图片，验证当前模型路由是否支持图像输入，并保存运行时能力证据。",
    imageProbeBusy: "验证图片中…",
    imageProbeRetry: "重新验证图片",
    imageProbeAction: "验证图片输入",
    reasoningDeclaredTooltip: "运营协议合同已声明；Composer 可显示档位。可选再验证 low/high 取证。",
    reasoningVerifiedTooltip: "运行时验证已保存能力证据。完整档位仍以运营协议合同为准。",
    reasoningDeclaredPrefix: "协议已声明 ",
    reasoningVerifiedTemplate: "推理 {values} 已验证",
    reasoningProbeHint: "一期探测仅验证 low/high + reasoning_object（Responses）。成功后保存能力证据；完整档位（medium/xhigh 等）请在 pin defaults 写协议合同。",
    reasoningProbeBusy: "验证推理中…",
    reasoningProbeAction: "验证推理 low / high",
    pinToAdd: "添加到模型库",
    pinAdding: "正在添加…",
    testCallHint: "发送最小真实模型请求并保存脱敏结果。",
    testCall: "测试调用",
    unpinAction: "从模型库移除",
    referenceCountUnit: " 个引用",
    pinCompact: "添加",
    detailsAction: "详情",
    detailAriaSuffix: " 详情",
    searchModelsAria: "搜索模型",
    searchModelsPlaceholder: "搜索模型名称或 ID",
    modelFiltersAria: "模型状态筛选",
    pinBannerAria: "批量添加模型",
    pinBannerActionsAria: "批量添加操作",
    pinAllBusy: "正在添加模型…",
    pinAllHint: "添加当前搜索结果中的模型，添加成功后可在 Agent 中选用。",
    pinAllStaleHint: "目录可能已过期，仍可添加当前列表中的 {count} 个已发现模型；建议稍后点「发现模型」刷新。",
    pinAllTemplate: "添加当前结果（{count}）",
    catalogTableAriaSuffix: " 模型目录",
    columnModel: "模型",
    modelDetailTitle: "模型详情",
    modelDetailDescription: "完整标识、能力与验证记录",
    wireProtocolLabel: "默认 wire protocol",
    noCapabilityTitle: "暂无能力观测",
    noCapabilityBody: "运行发现后，unknown 与 unsupported 会分别显示。",
    providerCriticalPrefix: "当前 Provider 状态为 ",
    providerCriticalSuffix: "。请修复认证或协议后再用于运行路由。",
    refreshDueTitle: "目录已过期，需要刷新",
    registryDiagnosticsTitle: "Provider 诊断",
    factLastAttempt: "最近尝试",
    factLastSuccess: "最近成功",
    factLastFailure: "最近失败原因",
    factAuth: "认证",
    factProtocol: "协议",
    valueNever: "从未",
    valueFailed: "失败",
    valueMismatch: "不匹配",
    rediscover: "重新发现",
    registryDiagnosticsBody: "诊断只展示有界状态，不展示原始响应或凭据内容。",
    unsavedModelsTitle: "有未保存的模型配置",
    savePromptTooltip: "路由替换等高级改动仍未保存。必须点「保存到外部配置」或完成 preview 确认后才会写入 operator config.toml。",
    saveBusy: "保存中…",
    addProvider: "添加供应商",
    addProviderHint: "接入新的模型服务，添加后先检测再使用",
    configuredProvidersHeading: "已配置服务",
    configuredListAria: "已配置服务列表",
    emptyConfiguredTitle: "暂无已配置服务",
    emptyConfiguredNormal: "点下方「添加供应商」接入中转站并保存 Key。",
    inUseBadge: "使用中",
    providerDotOk: "可用",
    providerDotWarn: "异常或未检测",
    providerDotOff: "已停用",
    providerSwitchAriaSuffix: "启用开关",
    providerSwitchHint: "停用后模型选择器不再列出该供应商的模型；点「保存到外部配置」后生效，不影响已保存的调用配置。",
    detectAction: "检测",
    detectBusy: "检测中…",
    detectHint: "验证连通与认证，并刷新模型目录",
    catalogFreshLine: "模型目录已同步",
    catalogStaleLine: "模型目录已过期，可点「检测」刷新",
    providerHeaderActionsAria: "供应商操作",
    advancedManage: "高级管理",
    baseUrlRowLabel: "服务地址",
    editRouteAction: "修改地址与协议",
    protocolRowLabel: "接口协议",
    protocolRowHint: "此供应商下模型使用的默认协议",
    pinnedModelsTemplate: "已添加 {count} 个模型",
    pickProviderTitle: "选择左侧已配置服务",
    pickProviderBody: "点选服务查看已添加模型；点「连接设置」修改地址与密钥。",
    inspectorTitlePrefix: "高级管理 · ",
    inspectorTitle: "高级管理",
    inspectorDescription: "查看服务诊断、合并重复供应商或移除服务。",
    advancedOpsAria: "进阶连接操作",
    collapseDiagnostics: "收起诊断",
    diagnosticsMergeAdvanced: "诊断 / 合并（高级）",
    mergeSectionTitle: "合并重复 Provider（高级）",
    mergeSectionMeta: "仅当存在端点完全相同的重复项时使用；日常中转站不需要",
    mergeKeepTemplate: "保留 {canonical}，候选重复项：{duplicates}。",
    mergeModelsToAddTemplate: "新增模型 {count}",
    mergeActionsAria: "重复 Provider 合并操作",
    mergePreviewBusy: "验证中…",
    mergePreviewAction: "生成合并预览",
    applyMerge: "应用合并",
    mergeConfirmLabel: "确认使用主 Provider 凭据并迁移引用",
    deleteProviderBlockedHint: "请先移除此服务下的模型，并解除 Agent 等引用。",
    deleteProviderDraftHint: "删除此未保存服务",
    deleteProviderAction: "删除服务",
    reasoningProbePending: "正在验证 low/high…",
    reasoningProbeFailed: "推理能力验证失败",
    reasoningProbeSuccess: "已验证并保存 {values}（一期仅 low/high；完整档位请写 pin defaults 协议合同）",
    wizardStepTemplate: "1 模板",
    wizardStepConnection: "2 连接",
    wizardStepDiscovery: "3 发现",
    wizardStepPin: "4 固定",
    wizardGroupOfficial: "官方 API",
    wizardGroupAggregator: "聚合平台",
    wizardGroupRelay: "中继",
    wizardGroupSelfHosted: "远程自托管",
    wizardGroupLocalRuntime: "本地框架",
    wizardGroupCustom: "自定义",
    wizardModelFamilyUnlabeled: "模型族未标注",
    wizardTitle: "模型服务高级配置",
    wizardStepsAria: "Provider 向导进度",
    wizardStepProgressTemplate: "步骤 {current}/{total}",
    wizardSuggestFailed: "Provider ID 建议失败",
    wizardDiscoverPreserved: "发现失败；已保留上一次目录。 ",
    wizardPinFailed: "固定模型失败",
    wizardCustomService: "自定义服务",
    wizardLockedTitle: "Provider 已创建，连接字段已锁定",
    wizardLockedBody: "返回 Provider 详情使用“修改路由”并完成 backend preview token 确认；向导不会静默忽略字段修改。",
    wizardDisplayName: "显示名称",
    wizardSecretOnce: "Secret（仅本次请求）",
    wizardDefaultWireProtocol: "默认 wire protocol",
    wizardDiscoverFailedTitle: "发现失败，已保留上次目录",
    wizardDiscoveredTemplate: "发现 {count} 个模型",
    wizardDiscoverIdleTitle: "创建连接并测试发现",
    wizardCreateTestDiscover: "创建 / 测试 / 发现",
    wizardDiscoveryBody: "仅展示归一化目录与有界错误，不展示原始 Provider 响应。Secret 完成请求后立即清空。",
    wizardPrevious: "上一步",
    wizardNextActionsAria: "向导下一步",
    wizardPinSelected: "固定所选模型",
    wizardNext: "下一步",
    quickSetupCheckingTitle: "正在检测连接",
    quickSetupReviewTitle: "确认生成的配置",
    quickSetupSavingTitle: "正在保存配置",
    quickSetupSuccessTitle: "配置已保存",
    quickSetupErrorTitle: "需要处理后重试",
    quickSetupIdleTitle: "等待检测",
    quickSetupPhaseChecking: "检测中",
    quickSetupPhaseReview: "待确认",
    quickSetupPhaseSaving: "保存中",
    quickSetupPhaseSuccess: "已完成",
    quickSetupPhaseError: "需处理",
    quickSetupPhaseIdle: "待输入",
    quickSetupDetecting: "检测中…",
    quickSetupRedetect: "重新检测",
    quickSetupDetect: "检测连接",
    quickSetupFactEndpoint: "端点",
    quickSetupFactProtocol: "协议",
    quickSetupFactModels: "发现模型",
    quickSetupErrorFallback: "检测或保存未完成，请检查输入后重试。",
    quickSetupRecommendationPrefix: "推荐理由：",
    quickSetupWaitingChoice: "等待选择",
    quickSetupSavedBody: "模型已保存，可在 Agent 配置中选择使用。",
    quickSetupIdleBody: "保持当前页面，完成后会在这里显示结果。",
    quickSetupCredentialHint: "凭据只用于本次本地检测；确认前不会写入正式配置。",
    quickSetupDisabledReason: "当前配置暂不可编辑。",
    quickSetupPickProviderFirst: "先选择服务商。",
    quickSetupFillBaseUrlFirst: "先填写服务地址。",
    quickSetupFillKeyFirst: "先填写 API Key。",
    quickSetupBusyReason: "当前检测或保存仍在进行。",
    quickSetupTitle: "连接一个模型服务",
    quickSetupTooltip: "选择服务商并填写凭据，系统会自动发现模型并给出默认推荐。",
    quickSetupTooltipLabel: "快速模型连接说明",
    quickSetupProviderLabel: "选择服务商",
    quickSetupProviderPlaceholder: "选择服务商或自定义服务",
    quickSetupBaseUrlPlaceholder: "https://你的服务地址/v1",
    quickSetupCredentialLabel: "凭据",
    quickSetupNoCredential: "无需凭据",
    quickSetupKeyPlaceholder: "仅用于本次本地配置请求",
    quickSetupDetectHint: "自动检测服务端点、协议和模型目录，不会直接写入正式配置。",
    quickSetupAdvanced: "高级参数",
    quickSetupProtocolLabel: "协议",
    quickSetupChatCompletionsLabel: "OpenAI Chat Completions（兼容接口）",
    quickSetupAuthMethodLabel: "认证方式",
    quickSetupNoAuthLabel: "无需认证（仅限服务明确支持）",
    quickSetupModelToAdd: "要添加的模型",
    quickSetupGoAgents: "去配置 Agent",
    quickSetupSaving: "保存中…",
    quickSetupRetrySave: "重试保存",
    quickSetupSaveFinish: "保存并完成",
    migrationAliasTitle: "兼容别名退出条件",
    migrationLiveReferenceUnit: " 个 live 引用",
    migrationAliasInUseTitle: "别名仍被使用",
    migrationAliasClearTitle: "别名已满足退出条件",
    migrationAliasInUseBody: "只有 live 引用归零后才可进入别名清理；本工作台不会提前提供删除动作。",
    migrationAliasClearBody: "live 引用已经归零。别名删除仍属于后续受控清理，不在本次迁移中自动执行。",
    migrationV2Title: "迁移到 Provider-first schema v2",
    migrationNotPreviewed: "尚未预览",
    migrationCritical: "迁移会修改外部 operator config。Schema v1 库存保持只读，不能在此新增、更新或删除。",
    migrationWhyTitle: "为什么需要迁移",
    migrationFactProviders: "Provider 分组",
    migrationFactLive: "Live 引用",
    migrationFactHistory: "历史引用",
    migrationWhyBody: "v1 把连接、凭据与模型混在单条记录中；v2 使用 canonical providerId/modelRef。应用前会创建备份，失败时可按 migration ID 回滚。",
    migrationMapAria: "v1 到 v2 modelRef 映射",
    migrationMapEmpty: "预览未返回模型映射。",
    migrationResolutionAria: "模型部署标识冲突裁决",
    migrationResolutionHeading: "模型部署标识需要显式裁决",
    migrationResolutionHint: "裁决只重新生成服务端预览，不会应用迁移。",
    migrationOfflineChip: "离线未核验",
    migrationOfflineWarning: "verificationState: unverified_offline。请仅从服务端允许的裁决中选择。",
    migrationDecisionAriaSuffix: " 裁决方式",
    migrationDecisionPlaceholder: "选择裁决方式",
    migrationPreserveLabel: "保留现有 upstream ID",
    migrationSplitLabel: "拆分部署记录并指定 upstream ID",
    migrationPreserveConfirm: "我确认保留此模型的现有 upstream ID",
    migrationNewUpstreamAriaSuffix: " 新 upstream ID",
    migrationUpstreamInvalid: "请输入非空且非路径型的 upstream ID。",
    migrationRegenerateResolutions: "重新生成裁决预览",
    migrationCredentialBlockedTitle: "Credential 冲突阻止应用",
    migrationCredentialBlockedTemplate: "{count} 个凭据映射冲突必须先处理；界面不会显示 credential reference 目标或 secret。",
    migrationUnresolvedHeading: "未解决冲突",
    migrationGlobalFallback: "全局",
    migrationNoConflictsTitle: "预览无阻塞冲突",
    migrationNoConflictsBody: "Apply 仍需最终 destructive impact 确认，不会在预览后自动执行。",
    migrationPreviewFirstTitle: "先生成只读迁移预览",
    migrationPreviewFirstBody: "预览会列出 Provider 分组、old-to-new modelRef、live 引用与冲突。",
    migrationActionsAria: "迁移操作",
    migrationPreviewAction: "生成迁移预览",
    migrationApplyTooltip: "应用迁移会修改外部 operator config。",
    migrationNeedPreviewFirst: "先生成预览",
    migrationConflictsRemain: "仍有未解决冲突",
    migrationInProgress: "迁移操作正在进行",
    migrationApplyAction: "应用迁移",
    actionDiscoverProviderBusy: "正在发现 Provider 模型…",
    actionDiscoverBusy: "正在发现模型…",
    actionDiscoverFoundTemplate: "发现 {count} 个模型",
    actionCatalogRefreshed: "目录已刷新",
    actionCreateProviderBusy: "正在创建 Provider 连接…",
    actionPinNoneMessage: "没有可固定的模型。请先点「发现模型」，确认列表里有「已发现」状态的行。",
    actionAllPinnedMessage: "所选模型均已固定。已切换到「已固定」列表。",
    actionUnpinBusy: "正在取消固定模型…",
    actionDeleteProviderConfirm: "删除 Provider {id}？此操作只允许在没有固定模型时继续。",
    actionDeleteProviderBusy: "正在删除 Provider…",
    actionCredentialBusy: "正在更新 Provider API Key…",
    actionSavingKey: "正在保存 API Key…",
    actionKeySaved: "API Key 已写入 operator config",
    actionContextWindowBusy: "正在更新上下文窗口…",
    actionSavingContextWindow: "正在保存上下文窗口…",
    actionContextWindowSetTemplate: "上下文窗口已设为 {value}",
    actionContextWindowCleared: "已清除 Provider 上下文窗口",
    actionToggleEnabledBusy: "正在切换供应商启停状态…",
    actionRoutePreviewBusy: "正在预览路由影响…",
    actionGeneratingRoutePreview: "正在生成路由预览…",
    actionRoutePreviewReady: "路由预览已生成",
    actionRouteUnchanged: "当前路由没有变化",
    actionRouteApplyBusy: "正在更新 Provider 路由…",
    actionUpdatingRoute: "正在更新 Provider 路由…",
    actionRouteApplied: "Provider 路由已更新（未保存）",
    pinBusyProgressTemplate: "正在固定模型…（{completed}/{total}）",
    pinBusyOneTemplate: "正在固定 {ref}…",
    pinBusyManyTemplate: "正在固定 {count} 个模型…",
    pinSuccessNewTemplate: "新固定 {count} 个",
    pinSuccessSkippedTemplate: "跳过已存在 {count} 个",
    pinSuccessFallback: "固定完成",
    pinSuccessListJoiner: "，",
    pinSuccessSuffix: "。已切换到「已固定」列表；请点右上角「保存到外部配置」。",
    pinErrorPartialTemplate: "已固定 {count} 个后失败：{message}",
    pinErrorTemplate: "固定失败：{message}",
    migrationPreviewPending: "正在生成迁移预览…",
    migrationApplyConfirm: "将修改外部 operator config。\nLive references: {liveCount}\nCanonical model refs:\n{refs}\n\n确认应用已预览的迁移？",
    migrationApplyPending: "正在应用迁移…",
    quickSetupPinFailedMessage: "模型未添加成功，请重试保存。已检测结果和选择已保留。",
    quickSetupApplyBusy: "正在应用快速配置…",
    quickSetupPartialSaveMessage: "配置尚未保存，已检测结果和模型选择已保留。请点击「重试保存」。",
    testModelBusyTemplate: "正在测试 {ref}…",
    testRealCallTemplate: "正在真实调用测试 {ref}…",
    testCallOkTemplate: "{ref} 可调用",
    testCallPersistedSuffix: "（已写入真实调用状态）",
    testCallFailedTemplate: "{ref} 调用失败：{reason}",
    testRequestFailedTemplate: "{ref} 测试请求失败：{message}",
    discoveryFailureCredentialMissing: "未配置 API Key；请先保存该 Provider 的凭据。",
    discoveryFailureCredentialRejected: "API Key 被上游拒绝；请检查凭据后重试。",
    discoveryFailureEndpointInvalid: "服务地址无效或不允许访问；请检查端点配置。",
    discoveryFailureNetwork: "无法连接到服务地址；请检查网络、局域网服务或端口。",
    discoveryFailureTimeout: "服务响应超时；可稍后重试。",
    discoveryFailureProtocolMismatch: "该端点不支持当前模型发现协议；请改用兼容接口或手动填写模型。",
    discoveryFailureInvalidResponse: "服务返回的模型目录格式不兼容；请检查 Provider 协议。",
    discoveryFailureRateLimited: "上游暂时限流；请稍后重试。",
    discoveryFailureUpstreamRejected: "上游服务拒绝了模型目录请求；请检查服务状态或协议。",
    discoveryFailureDefault: "该 Provider 的模型发现暂不可用；请检查连接后重试。",
    avatarTypeError: "头像只支持 PNG、JPG 或 WebP 图片。",
    avatarReadError: "无法读取这张图片。",
    avatarCropReadError: "无法读取裁剪后的图片。",
    avatarCropUnsupported: "当前浏览器无法裁剪图片。",
    avatarCropFailed: "头像裁剪失败。",
    currentBadge: "当前",
    placeholderNavOverview: "总览与保存",
    placeholderNavInterface: "界面与高级配置",
    placeholderNavProfile: "用户与形象",
    placeholderNavModels: "模型库",
    placeholderNavRuntime: "运行时与上下文",
    placeholderNavTooling: "工具与诊断",
    sectionErrorPrefix: "分区保存失败：",
    sectionErrorInline: "本次修改未生效，请修正后重试；其他分区不受影响。",
    confirmTitle: "操作确认",
    confirmAction: "确认",
  },
  en: {
    pageTitle: "Settings",
    subtitle: "Structured config, model assets, and save state. Startup settings are maintained in Launcher.",
    subtitleHint: "Startup settings are maintained in Launcher; structured editing, full-config checks, and final writes still converge on the external operator config.toml.",
    returnToAgents: "Return to Agent config",
    returnToSource: "Return to source page",
    loading: "Loading unified config workspace...",
    loadFailed: "Failed to load config workspace",
    migrationPreviewExpired: "The migration preview expired. Generate a new preview.",
    sourceTitle: "Save and Apply",
    sourceBody: "Shows whether current changes are saved and which system-level settings take effect after restart.",
    sourceBodyShort: "Save state, config path, and environment entry.",
    runtimeTitle: "Evolution review mode",
    runtimeBody: "Manual operation keeps each step under review; automatic review sends evolution tasks directly into the review flow.",
    modelsTitle: "Model Library",
    modelsBody: "This section manages model assets only: provider routes, model names, key state, capability checks, and connection tests. Edit each Agent's model choices in Agent management.",
    modelsBodyShort: "Model assets, key state, capability checks, and connectivity.",
    draftTitle: "Advanced Config Check",
    draftBody: "Inspect the full current config. Saves write only external operator config.toml.",
    diagnosticsTitle: "Diagnostics and Save",
    diagnosticsBody: "Related issues are grouped by root cause. Fix the cause first, then save.",
    configPath: "Config path",
    configStatus: "Current status",
    rawToml: "Current external config.toml",
    rawTomlHint: "This is a read-only view of the real file. It refreshes after you save changes.",
    syncedDraft: "Matches external config.toml",
    unsavedDraft: "Unsaved changes",
    refresh: "Reload",
    validateDraft: "Check changes",
    resetDraft: "Restore editor text",
    openEnvironment: "Open system environment variables",
    openEnvironmentHint: "Opens the Windows system dialog so you can inspect which keys are in use.",
    openEnvironmentPending: "Opening system environment variables",
    openEnvironmentOpened: "System environment variables window opened.",
    saveConfig: "Save to external config",
    applying: "Saving",
    leaveGuardTitle: "Unsaved settings",
    leaveGuardBody: "These changes have not been saved to the external operator config.toml. Save before leaving?",
    leaveGuardSave: "Save and leave",
    leaveGuardSaving: "Saving before leaving",
    leaveGuardDiscard: "Leave without saving",
    leaveGuardCancel: "Cancel",
    intakeMode: "Default review mode",
    groupOverviewSaveTitle: "Overview and Save",
    groupOverviewSaveSummary: "Review save state, blockers, and suggested actions in one place, then save after fixes.",
    groupWorkbenchTitle: "Workbench & Interface",
    groupWorkbenchSummary: "Manage workbench behavior, colors, and background here. Startup settings remain in Launcher.",
    groupAvatarPetTitle: "Profile & desktop pet",
    groupAvatarPetSummary: "Set the display name, terminal avatar, and companion in one place. The Web user avatar lives under User Info, while advanced parameters remain on demand.",
    groupModelingTitle: "Model Library",
    groupModelingSummary: "Manage model assets, provider accounts, keys, capability checks, and discovery in one place.",
    groupRuntimeContextTitle: "Context & Analysis",
    groupRuntimeContextSummary: "Keep global context compression on the main path and expand analysis data directories only for custom storage layouts.",
    groupToolingTitle: "Tooling and Diagnostics",
    groupToolingSummary: "Layer everyday access, health diagnostics, logging, tracing, and advanced maintenance.",
    healthTitle: "Health Diagnostics Center",
    healthBody: "Organizes session entry points, log entry points, recent signals, cleanup hints, and protected boundaries in one read-only diagnostic surface.",
    healthLoading: "Organizing log helpers...",
    healthEmpty: "No log helpers are available right now.",
    healthRefresh: "Run again",
    healthPriority: "Top findings",
    healthQuickActions: "Quick actions",
    healthEvidence: "Evidence",
    healthRecommended: "Recommendation",
    healthRelatedFindings: "Related findings",
    healthNoFindings: "No blocked or warning findings.",
    healthOpenLogs: "Open logs",
    healthOpenChat: "Open chat",
    healthOpenLauncher: "Open Launcher",
    healthOpen: "Open",
    healthFiles: "files",
    healthDirs: "dirs",
    healthSessions: "sessions",
    healthBusy: "busy",
    healthFailed: "failed",
    healthStale: "stale",
    healthPhase: "phase",
    healthLatest: "Latest signal",
    healthUpdated: "Updated",
    healthSize: "Size",
    healthProtected: "Protected",
    healthMaintenanceAvailable: "Launcher maintenance available",
    healthStatusOk: "OK",
    healthStatusWarning: "Attention",
    healthStatusBlocked: "Blocked",
    healthMissing: "No log files yet",
    healthNotRecorded: "Not recorded",
    shortcutsTitle: "Keyboard shortcuts",
    shortcutsIntro: "Click Change and press the new key combination to record it (Esc to cancel · Backspace to restore default). Clear writes an explicit empty array (not set, no fallback to defaults).",
    shortcutsPersistence: "Overrides persist to the localStorage key vibelution.shortcuts.overrides, the same storage the global shortcuts read.",
    shortcutsEffectiveNow: "Rebinds apply immediately without a restart; shortcuts work across the app through the same execution path as the command palette.",
    uiFontLabel: "Interface font size",
    uiFontDescription: "Adjust the overall workbench text size (14–18, default 16). Applies immediately, on this machine only: stored in the browser's localStorage, never written to config.toml.",
    uiFontDecrease: "Decrease interface font size",
    uiFontIncrease: "Increase interface font size",
    shortcutsResetAll: "Restore all defaults",
    shortcutsClose: "Close",
    shortcutsStatusDefault: "Default",
    shortcutsStatusOverridden: "Customized",
    shortcutsStatusCleared: "Cleared",
    shortcutsUnset: "Not set",
    shortcutsModify: "Change",
    shortcutsClear: "Clear",
    shortcutsRestore: "Restore default",
    shortcutsRecording: "Recording: press the new key combination",
    shortcutsRecordingHint: "Esc to cancel · Backspace to restore default",
    shortcutsRecordingPending: "Modifier received, waiting for the full combination…",
    shortcutsRecordCancelled: "Recording cancelled. No binding changed.",
    shortcutsRestoredByBackspace: "\"{title}\" default bindings restored (Backspace while recording).",
    shortcutsFilterPlaceholder: "Filter commands…",
    shortcutsFilterByKeystroke: "Find by key",
    shortcutsFilterCapturing: "Press a key combination… (Esc to exit)",
    shortcutsFilterClear: "Clear key filter",
    shortcutsFilterUnknownKey: "Unrecognized key",
    shortcutsFilterNoTextMatch: "No commands match the text",
    shortcutsFilterKeyUnbound: "No command uses this key combination",
    shortcutsInvalidNoModifier: "Recording failed: plain character keys need at least one modifier (named keys such as F-keys and arrows may be bare).",
    shortcutsInvalidUnsupported: "Recording failed: unsupported key combination (primary modifier lost in normalization). No binding changed.",
    shortcutsBoundNotice: "Bound {binding} to \"{title}\" (the override replaces all bindings of that command).",
    shortcutsReservedNotice: "Rejected: {binding} is a reserved key (native browser/editor behavior or fixed component interaction) and cannot be bound to \"{title}\".",
    shortcutsOccupiedNotice: "Rejected: {binding} is already used by \"{owner}\". Choose another combination, or steal the key.",
    shortcutsSteal: "Steal and bind",
    shortcutsStealHint: "Stealing unbinds \"{owner}\" and binds {binding} to \"{title}\".",
    shortcutsStealDone: "Bound {binding} to \"{title}\"; \"{owner}\" is now unset.",
    shortcutsClearedNotice: "Cleared all bindings of \"{title}\" (explicit empty array = not set, no fallback to defaults).",
    shortcutsRestoredNotice: "\"{title}\" overrides removed; default bindings restored.",
    shortcutsResetAllNotice: "All default bindings restored and persisted overrides cleared.",
    settingsStatusTitle: "Settings status",
    settingsNextStep: "Next step",
    settingsCanSave: "Ready to save",
    settingsNeedsCheck: "Check advanced config first",
    settingsSynced: "Synced",
    settingsSections: "Sections",
    developerModeReadonly: "Developer mode",
    developerModeControlled: "Launcher controlled",
    developerModeEnabled: "Enabled",
    developerModeDisabled: "Disabled",
    runtimeProfile: "Runtime mode",
    defaultMode: "Default mode",
    defaultRoute: "Default route",
    modelEditorCreate: "Create model",
    modelEditorEdit: "Edit model",
    modelCenterAccounts: "Provider accounts",
    modelCenterInventory: "Model inventory",
    modelCenterHealth: "Health",
    modelCenterModels: "Selectable models",
    modelCenterCapabilityIssues: "Attention",
    modelCenterActions: "Actions",
    modelCenterProtocol: "Protocol route",
    modelScenario: "Add as",
    modelScenarioChat: "General chat model",
    modelScenarioRelay: "Relay model",
    modelScenarioImage: "Image tool model",
    modelScenarioLocal: "Local model",
    modelScenarioManual: "Advanced manual",
    modelScenarioHint: "The scenario picks the closest template. Provider, model name, and key can still be adjusted below.",
    preset: "Vendor",
    providerVendor: "Vendor",
    providerTemplate: "Template",
    providerTemplatePlaceholder: "Choose a template",
    presetGroupOfficial: "Official providers",
    presetGroupRelay: "Relay Responses",
    presetGroupOpenAiCompatible: "OpenAI-compatible APIs",
    presetGroupLocal: "Local models",
    customEntry: "Manual",
    autoValue: "Auto",
    modelId: "Model ID",
    label: "Label",
    modelName: "Model",
    discoverModels: "Discover models",
    discoveryPending: "Discovering models",
    discoveredModel: "Discovered model",
    discoveryEmpty: "No models discovered",
    discoveryFailed: "Model discovery failed",
    discoveryUnavailable: "This provider does not support automatic discovery. Enter the model name manually.",
    providerKind: "Provider kind",
    providerKeyEnv: "Provider default variable",
    modelKeyEnv: "Unique model variable",
    modelKeyInput: "API key",
    keyStorageHint: "This is staged first. It is written to the local user environment only when you save to the external config.",
    keyEnvAdvancedHint: "The model key variable is uniquely generated from the model ID and shown read-only. Enter the API key value; saving writes it to this user environment variable. The provider default variable is compatibility-only display, not a new key entry point.",
    deleteModelHint: "Deleting a model also clears the unique environment key bound to that model. Adjust Agent and tool model choices in their own management pages.",
    deleteModelConfirm: "Delete this model? This clears its bound environment key and removes the asset from the model library.",
    baseUrl: "Base URL",
    compatMode: "Compat mode",
    providerApi: "Provider API",
    modelProtocol: "Model protocol",
    modelCompat: "Compat policy object",
    contextWindow: "Context window (required, no default)",
    requiresApiKey: "Requires API key",
    imageInputSupport: "Image input",
    imageInputSupportUnknown: "Undeclared",
    imageInputSupportSupported: "Supported",
    imageInputSupportUnsupported: "Unsupported",
    transport: "Transport",
    contract: "Contract",
    reasoningStateField: "Reasoning state field",
    toolCallingMode: "Tool calling",
    promptCacheMode: "Prompt cache",
    strictCompatibility: "Strict compatibility",
    streaming: "Streaming",
    discoveryEnabled: "Discovery enabled",
    temperature: "Temperature",
    maxOutputTokens: "Max output tokens",
    timeout: "Timeout (s)",
    connectTimeout: "Connect timeout (s)",
    clearSecret: "Also clear this environment key on save",
    saveModel: "Confirm model changes",
    modelRequiredFieldsMissing: "Enter the model name and base URL first.",
    deleteModel: "Delete model",
    cancelEditing: "Clear form",
    modelTestSelect: "Test model",
    modelTestPlaceholder: "Choose a model",
    testSelectedLibraryModel: "Test selected model",
    modelTestRequired: "Choose a model to test first.",
    checkSavedImageCapabilities: "Check saved models image input",
    imageCapabilityCheckPending: "Checking model capabilities",
    imageCapabilityStatus: "Image capability",
    imageInputStatusUnknown: "Image not checked",
    imageInputStatusSupported: "Supports image input",
    imageInputStatusUnsupported: "No image input",
    imageInputStatusFailed: "Check failed",
    expandSection: "Expand",
    collapseSection: "Collapse",
    keyConfigured: "configured",
    keyPending: "pending",
    keyClearPending: "clear pending",
    keyMissing: "missing",
    noBlocking: "No blocking issues right now.",
    noWarnings: "No warnings right now.",
    noSuggestions: "No extra suggested actions right now.",
    blockingIssues: "Blocking issues",
    warningSignals: "Warnings",
    suggestedActions: "Suggested actions",
    rootCauseMetric: "Root causes",
    affectedReferenceMetric: "Affected references",
    warningMetric: "Warnings",
    affectedReferences: "Affected config references",
    showAffectedReferences: "Show affected references",
    repairProviderCredential: "Set API Key",
    editorDirtyHint: "The editor text has unchecked changes. Check them before more structured edits or tests.",
    editorCleanHint: "Structured controls and editor text are in sync.",
    editorRestoreHint: "Discard unchecked editor text and return to the current structured panel.",
    saveSourceHint: "Save to the external config to persist the current changes.",
    modelSavePending: "Saving model changes",
    modelSaveFailed: "Model changes were not applied:",
    modelEditorAdvancedTitle: "Advanced parameters",
    modelEditorAdvancedHint: "The common fields are above. Expand this only when needed.",
    testPending: "Testing connection",
    testScopeDraft: "Testing current changes",
    testScopeSaved: "Testing saved config",
    testRouteLabel: "Route",
    testRuntimeLabel: "Runtime path",
    testKeyLabel: "API key",
    testKeyNotRequired: "not required for this route",
    testKeySourceLabel: "source",
    testCapabilityLabel: "Capability",
    validationPending: "Checking changes",
    refreshPending: "Reloading",
    editSection: "Edit section",
    saveSection: "Confirm section changes",
    cancelSection: "Cancel editing",
    sectionSavePending: "Saving section changes",
    rowStatusApplied: "Applied",
    rowStatusPending: "Pending save",
    rowStatusWaiting: "Waiting",
    rowStatusFailed: "Not applied",
    settingsPendingCountUnit: " pending",
    saveBlockedInvalid: "Some changes are invalid; fix them before saving",
    jsonValidHint: "✓ Correct format",
    jsonInvalidPrefix: "Format error: ",
    jsonErrorAt: " (line ",
    jsonErrorLine: ", column ",
    jsonErrorCol: ")",
    numberRequired: "Enter a number",
    numberInvalidPrefix: "Not a valid number: ",
    numberBelowMinInclusive: "Cannot be below ",
    numberBelowMinExclusive: "Must be greater than ",
    numberAboveMaxInclusive: "Cannot exceed ",
    numberAboveMaxExclusive: "Must be below ",
    numberRangeHint: "range",
    numberStepHint: "step",
    listLinePrefix: "Line ",
    listLineMid: ": ",
    listInvalidToolName: "Not a valid tool name (start with a lowercase letter; letters, digits, underscore only)",
    listDuplicateItem: "duplicate item",
    listBlankLineWarning: "Blank lines are ignored on save",
    listWhitespaceWarning: "Leading/trailing spaces are trimmed on save",
    uploadAvatarImage: "Upload local image",
    clearAvatarImage: "Clear image",
    avatarImageUploading: "Uploading avatar image",
    avatarImageUploadFailed: "Avatar image upload failed: ",
    avatarImageCurrent: "Current avatar",
    avatarImageEmpty: "No avatar image set",
    avatarImageClickToUpload: "Click avatar to upload",
    userProfileAvatarGroupTitle: "Avatar settings",
    userProfileAvatarGroupHint: "The avatar preset and local avatar image affect frontend display only. Image content is not sent to the model.",
    uploadThemeBackgroundImage: "Upload background image",
    clearThemeBackgroundImage: "Clear background image",
    themeBackgroundPresetTitle: "Built-in backgrounds",
    themeBackgroundImageUploading: "Uploading background image",
    themeBackgroundImageUploadFailed: "Background image upload failed: ",
    avatarCropTitle: "Crop avatar",
    avatarCropHint: "Drag the image to reposition it and use the slider to zoom. Confirm saves a 1:1 crop.",
    avatarCropZoom: "Zoom",
    avatarCropConfirm: "Confirm crop",
    avatarCropCancel: "Cancel crop",
    avatarCropPreview: "Avatar preview",
    fieldCountLabel: "fields",
    emptyValue: "Empty",
    itemLabel: "Item",
    yes: "Yes",
    no: "No",
    cancel: "Cancel",
    navResizeSeparator: "Settings navigation width",
    navCollapse: "Collapse settings navigation",
    navExpand: "Expand settings navigation",
    statusUnsaved: "Unsaved changes",
    statusSaved: "Config saved",
    searchPetTitle: "Desktop pet",
    searchPetDetail: "Open or close desktop pet",
    searchPetHaystack: "桌宠 桌面宠物 开启 关闭 desktop pet",
    searchPetTitleHaystack: "Desktop pet",
    intakeAuto: "automatic review",
    intakeManual: "manual operation",
    modelsActionsAria: "Model connection actions",
    advancedSettings: "Advanced settings",
    collapseAdvancedSettings: "Hide advanced settings",
    advancedSettingsHint: "Template wizard, migration, and low-level parameters.",
    backToConfiguredProviders: "Back to configured providers",
    routeEditSectionTitle: "Service URL and protocol",
    routeEditActionsAria: "Provider route edit actions",
    routePreviewPending: "Generating preview…",
    routePreviewAction: "Preview replacement impact",
    routeFieldBaseUrl: "Service URL",
    routeFieldDriver: "Interface type",
    routeFieldProtocol: "Wire protocol",
    routeEditWarning: "Before saving, the models and Agents affected are checked. Review them before applying.",
    routeConfirmChangedTitle: "Confirm connection changes",
    routeConfirmUnchangedTitle: "No connection changes",
    routeReferenceCountUnit: " references",
    routeConfirmActionsAria: "Provider route replacement confirmation",
    routeApplyPending: "Updating…",
    routeConfirmAction: "Confirm and update connection",
    routeConfirmBody: "These models and references will use the new connection settings. Verify the service URL and protocol before confirming.",
    registryTabConnection: "Connection",
    registryTabModels: "Model library · pinned",
    registryTabProtocols: "Protocols & capabilities",
    registryTabDiagnostics: "Diagnostics",
    registryFilterAll: "All",
    registryFilterPinned: "Added",
    registryFilterDiscovered: "Add models",
    testRecoveryAuth: "Check the API Key in connection settings.",
    testRecoveryRateLimited: "Requests are rate limited. Retry later; if it persists, check your service quota.",
    testRecoveryNetwork: "Cannot reach the service. Check the network and whether the service is running.",
    testRecoveryTimeout: "The service response timed out. Retry later and check service load.",
    testRecoveryUnavailable: "The upstream service is temporarily unavailable. Retry later or switch services.",
    testRecoveryNotFound: "Verify the model name and service URL, and refresh the model catalog if needed.",
    testRecoveryDefault: "Check the error details and verify the request parameters, then retry.",
    providerStatusReachable: "Catalog updated",
    providerStatusStale: "Catalog outdated",
    providerStatusNotDiscovered: "Not discovered yet",
    providerStatusConfigured: "Configured",
    providerStatusAuthFailed: "Auth failed",
    providerStatusDiscoveryFailed: "Model discovery failed",
    providerStatusProtocolMismatch: "Protocol mismatch",
    providerStatusBlocked: "Blocked",
    providerStatusObserved: "Discovered",
    providerStatusPinned: "Added",
    providerStatusMissingRemote: "Added · missing from latest catalog",
    providerStatusDisabled: "Disabled",
    discoveryErrTimeout: "Request timeout",
    discoveryErrNetwork: "Network unreachable",
    discoveryErrCredentialMissing: "No credential configured",
    discoveryErrAuthFailed: "Auth failed",
    discoveryErrEndpointInvalid: "Invalid service URL",
    discoveryErrProtocolMismatch: "Protocol incompatible",
    discoveryErrInvalidResponse: "Incompatible response format",
    discoveryErrRateLimited: "Upstream rate limited",
    discoveryErrUpstreamRejected: "Upstream rejected the request",
    discoveryErrUnavailable: "Upstream unavailable",
    discoveryErrBlocked: "Access blocked",
    discoveryErrOther: "Discovery failed",
    discoveryErrNone: "none",
    reasoningDepthPrefix: "Reasoning depth: ",
    reasoningMissingLabel: "Reasoning depth: not configured",
    reasoningDeclaredDetail: "Declared by contract · default {default} · adapter {adapter}",
    reasoningVerifiedDetail: "Verified · adapter {adapter}",
    reasoningMissingDetail: "After pinning, write pin defaults.reasoning_effort_values, or click \"Verify reasoning low/high\" on Responses models",
    capabilityUnobserved: "Capability not observed",
    capabilityCheckedAtMissing: "not recorded",
    capabilityValueUnknown: "unknown",
    capabilityValueUnsupported: "unsupported",
    checklistAria: "Setup progress",
    checklistDone: "Done",
    checklistOptional: "Optional",
    checklistTodo: "To do",
    checklistNextPrefix: "Next: ",
    checklistNextPinHint: " (pin a chat model under \"Added / Discovered\" below)",
    checklistNextCredentialHint: " (click \"Set API Key\")",
    checklistNextConnectionHint: " (click \"Discover\" or check the route)",
    checklistAllDone: "This provider's basic setup is complete. Pinned models can be used in Agents.",
    actionPinDisabledReason: "Config actions unavailable right now",
    actionPinHint: "Pinning writes to the model library; save the config to use it in Agents",
    actionPinLabel: "Pin to config",
    actionUnpinLabel: "Unpin",
    actionInUseLabel: "In use",
    actionUnavailableLabel: "Unavailable",
    actionUnpinnableLabel: "Cannot pin",
    checklistCredentialLabel: "API key / credential ready",
    checklistConnectionLabel: "Connection reachable or configured",
    checklistPinLabel: "At least 1 chat model pinned",
    checklistReasoningLabel: "(Optional) declare reasoning depth for pinned models",
    apiKeyRowLabel: "API key",
    apiKeySharedHint: "Models under this provider share one key; saved keys are never echoed back.",
    apiKeyNotRequiredHint: "This service does not need an API key.",
    updateApiKey: "Update API key",
    enterApiKey: "Enter API key",
    noKeyNeeded: "No key needed",
    newApiKeyPlaceholder: "Enter a new API key",
    apiKeyActionsAria: "API key actions",
    saveKey: "Save key",
    contextLimitRowLabel: "Default context limit",
    contextLimitRowHint: "Provider-level fallback used only when a model has no limit of its own.",
    useModelDeclared: "Uses model declaration",
    adjustContextDetails: "Adjust limit and deployment details",
    contextWindowFieldLabel: "Context window",
    contextWindowExample: "e.g. 128000",
    saveContextWindow: "Save context window",
    driverPrefix: "Driver: ",
    notConfigured: "Not configured",
    runtimeFrameworkPrefix: "Runtime framework: ",
    unknownValue: "unknown",
    artifactFilePrefix: "Model file: ",
    modelsEmptyCatalog: "No model catalog yet. Click \"Discover models\" to fetch one.",
    modelsEmptyPinned: "No models added yet. Switch to \"Add models\" and pick the ones you need.",
    modelsEmptyDiscovered: "Nothing pending. Refresh the catalog or check \"Added\".",
    modelsEmptyNoMatch: "No matching models. Adjust the search or filter.",
    verificationHeader: "Latest test",
    verifyErrTimeout: "Timeout",
    verifyErrBadRequest: "Upstream 400 rejected",
    verifyErrAuthFailed: "Auth failed",
    verifyErrRateLimited: "Rate limited",
    verifyErrNotFound: "Model not found",
    verifyErrNetwork: "Network error",
    verifyErrMissingCredential: "Missing key",
    verifyErrUnavailable: "Upstream unavailable",
    verifyUntested: "Not tested",
    verifyPassed: "Test passed",
    verifyFailed: "Test failed",
    verifyRequestFailed: "request did not succeed",
    verifyErrorDetails: "Error details",
    columnModelRef: "Model ref",
    columnUpstreamId: "Upstream ID",
    columnAvailability: "Availability",
    columnCapabilities: "Capability source",
    columnActions: "Actions",
    modelActionsAriaSuffix: " model actions",
    imageProbeHint: "Send a minimal valid image to verify whether this model route supports image input, saving runtime capability evidence.",
    imageProbeBusy: "Verifying image…",
    imageProbeRetry: "Re-verify image",
    imageProbeAction: "Verify image input",
    reasoningDeclaredTooltip: "Declared by the operations contract; Composer can show the levels. Optionally verify low/high for evidence.",
    reasoningVerifiedTooltip: "Runtime verification saved capability evidence. The full ladder still follows the operations contract.",
    reasoningDeclaredPrefix: "Contract declared ",
    reasoningVerifiedTemplate: "Reasoning {values} verified",
    reasoningProbeHint: "Phase-1 probing verifies low/high + reasoning_object (Responses) only. Evidence is saved on success; write the full ladder (medium/xhigh etc.) into pin defaults.",
    reasoningProbeBusy: "Verifying reasoning…",
    reasoningProbeAction: "Verify reasoning low / high",
    pinToAdd: "Add to model library",
    pinAdding: "Adding…",
    testCallHint: "Send a minimal real model request and save a redacted result.",
    testCall: "Test call",
    unpinAction: "Remove from library",
    referenceCountUnit: " references",
    pinCompact: "Add",
    detailsAction: "Details",
    detailAriaSuffix: " details",
    searchModelsAria: "Search models",
    searchModelsPlaceholder: "Search model names or IDs",
    modelFiltersAria: "Model status filters",
    pinBannerAria: "Batch add models",
    pinBannerActionsAria: "Batch add actions",
    pinAllBusy: "Adding models…",
    pinAllHint: "Adds the models in the current search results so they can be used in Agents.",
    pinAllStaleHint: "The catalog may be outdated. You can still add the {count} discovered models listed; refresh via \"Discover models\" later.",
    pinAllTemplate: "Add current results ({count})",
    catalogTableAriaSuffix: " model catalog",
    columnModel: "Model",
    modelDetailTitle: "Model details",
    modelDetailDescription: "Full identity, capabilities, and verification records",
    wireProtocolLabel: "Default wire protocol",
    noCapabilityTitle: "No capability observations yet",
    noCapabilityBody: "Run discovery and unknown / unsupported will show up separately.",
    providerCriticalPrefix: "This provider's status is ",
    providerCriticalSuffix: ". Fix auth or protocol before using it for runtime routes.",
    refreshDueTitle: "Catalog outdated, refresh needed",
    registryDiagnosticsTitle: "Provider diagnostics",
    factLastAttempt: "Last attempt",
    factLastSuccess: "Last success",
    factLastFailure: "Last failure reason",
    factAuth: "Auth",
    factProtocol: "Protocol",
    valueNever: "never",
    valueFailed: "failed",
    valueMismatch: "mismatch",
    rediscover: "Rediscover",
    registryDiagnosticsBody: "Diagnostics show bounded status only, never raw responses or credential content.",
    unsavedModelsTitle: "Unsaved model changes",
    savePromptTooltip: "Advanced changes such as route replacement are still unsaved. Click \"Save to external config\" or finish the preview confirmation to write operator config.toml.",
    saveBusy: "Saving…",
    addProvider: "Add provider",
    addProviderHint: "Onboard a new model service; run Check before using it",
    configuredProvidersHeading: "Configured providers",
    configuredListAria: "Configured providers list",
    emptyConfiguredTitle: "No configured providers yet",
    emptyConfiguredNormal: "Click \"Add provider\" below to onboard a relay and save its key.",
    inUseBadge: "In use",
    providerDotOk: "Available",
    providerDotWarn: "Unverified or failing",
    providerDotOff: "Disabled",
    providerSwitchAriaSuffix: "enable toggle",
    providerSwitchHint: "Disabled providers are hidden from the model picker; takes effect after \"Save to external config\" and does not affect already-saved call configs.",
    detectAction: "Check",
    detectBusy: "Checking…",
    detectHint: "Verify connectivity and auth, then refresh the model catalog",
    catalogFreshLine: "Model catalog up to date",
    catalogStaleLine: "Model catalog is stale; click Check to refresh",
    providerHeaderActionsAria: "Provider actions",
    advancedManage: "Advanced manage",
    baseUrlRowLabel: "Service URL",
    editRouteAction: "Edit URL and protocol",
    protocolRowLabel: "Interface protocol",
    protocolRowHint: "The default protocol models under this provider use",
    pinnedModelsTemplate: "{count} models added",
    pickProviderTitle: "Pick a configured provider",
    pickProviderBody: "Select a provider to view its added models; use \"Connection settings\" to edit URL and key.",
    inspectorTitlePrefix: "Advanced manage · ",
    inspectorTitle: "Advanced manage",
    inspectorDescription: "View provider diagnostics, merge duplicates, or remove the provider.",
    advancedOpsAria: "Advanced connection actions",
    collapseDiagnostics: "Hide diagnostics",
    diagnosticsMergeAdvanced: "Diagnostics / merge (advanced)",
    mergeSectionTitle: "Merge duplicate providers (advanced)",
    mergeSectionMeta: "Only for providers with identical endpoints; everyday relays do not need this",
    mergeKeepTemplate: "Keep {canonical}; duplicate candidates: {duplicates}.",
    mergeModelsToAddTemplate: "{count} models to add",
    mergeActionsAria: "Duplicate provider merge actions",
    mergePreviewBusy: "Validating…",
    mergePreviewAction: "Generate merge preview",
    applyMerge: "Apply merge",
    mergeConfirmLabel: "Confirm using the canonical provider credential and migrating references",
    deleteProviderBlockedHint: "Remove this provider's models and release Agent references first.",
    deleteProviderDraftHint: "Delete unsaved provider",
    deleteProviderAction: "Delete provider",
    reasoningProbePending: "Verifying low/high…",
    reasoningProbeFailed: "Reasoning capability verification failed",
    reasoningProbeSuccess: "Verified and saved {values} (phase 1 covers low/high only; write the full ladder into pin defaults)",
    wizardStepTemplate: "1 Template",
    wizardStepConnection: "2 Connection",
    wizardStepDiscovery: "3 Discovery",
    wizardStepPin: "4 Pin",
    wizardGroupOfficial: "Official APIs",
    wizardGroupAggregator: "Aggregators",
    wizardGroupRelay: "Relay",
    wizardGroupSelfHosted: "Remote self-hosted",
    wizardGroupLocalRuntime: "Local runtimes",
    wizardGroupCustom: "Custom",
    wizardModelFamilyUnlabeled: "model family unlabeled",
    wizardTitle: "Advanced model service setup",
    wizardStepsAria: "Provider wizard progress",
    wizardStepProgressTemplate: "Step {current}/{total}",
    wizardSuggestFailed: "Provider ID suggestion failed",
    wizardDiscoverPreserved: "Discovery failed; the previous catalog was kept. ",
    wizardPinFailed: "Failed to pin models",
    wizardCustomService: "Custom service",
    wizardLockedTitle: "Provider created; connection fields locked",
    wizardLockedBody: "Go back to the provider detail and use \"Edit route\" with the backend preview token confirmation. The wizard never silently ignores field changes.",
    wizardDisplayName: "Display name",
    wizardSecretOnce: "Secret (this request only)",
    wizardDefaultWireProtocol: "Default wire protocol",
    wizardDiscoverFailedTitle: "Discovery failed; previous catalog kept",
    wizardDiscoveredTemplate: "{count} models discovered",
    wizardDiscoverIdleTitle: "Create the connection and test discovery",
    wizardCreateTestDiscover: "Create / test / discover",
    wizardDiscoveryBody: "Shows the normalized catalog and bounded errors only, never the raw provider response. Secrets are cleared as soon as the request finishes.",
    wizardPrevious: "Back",
    wizardNextActionsAria: "Wizard next step",
    wizardPinSelected: "Pin selected models",
    wizardNext: "Next",
    quickSetupCheckingTitle: "Checking connection",
    quickSetupReviewTitle: "Confirm the generated config",
    quickSetupSavingTitle: "Saving config",
    quickSetupSuccessTitle: "Config saved",
    quickSetupErrorTitle: "Fix issues and retry",
    quickSetupIdleTitle: "Waiting for detection",
    quickSetupPhaseChecking: "Checking",
    quickSetupPhaseReview: "To confirm",
    quickSetupPhaseSaving: "Saving",
    quickSetupPhaseSuccess: "Done",
    quickSetupPhaseError: "Attention",
    quickSetupPhaseIdle: "Input",
    quickSetupDetecting: "Checking…",
    quickSetupRedetect: "Check again",
    quickSetupDetect: "Check connection",
    quickSetupFactEndpoint: "Endpoint",
    quickSetupFactProtocol: "Protocol",
    quickSetupFactModels: "Discovered models",
    quickSetupErrorFallback: "Detection or save did not finish. Check the inputs and retry.",
    quickSetupRecommendationPrefix: "Why recommended: ",
    quickSetupWaitingChoice: "waiting for selection",
    quickSetupSavedBody: "The model is saved and can be selected in Agent config.",
    quickSetupIdleBody: "Stay on this page; the result will appear here when done.",
    quickSetupCredentialHint: "The credential is used for this local detection only. Nothing is written to the real config before you confirm.",
    quickSetupDisabledReason: "The current config cannot be edited right now.",
    quickSetupPickProviderFirst: "Pick a provider first.",
    quickSetupFillBaseUrlFirst: "Enter the service URL first.",
    quickSetupFillKeyFirst: "Enter the API key first.",
    quickSetupBusyReason: "Detection or save is still running.",
    quickSetupTitle: "Connect a model service",
    quickSetupTooltip: "Pick a provider and fill in the credential. The system discovers models automatically and suggests a default.",
    quickSetupTooltipLabel: "Quick model connection details",
    quickSetupProviderLabel: "Provider",
    quickSetupProviderPlaceholder: "Pick a provider or a custom service",
    quickSetupBaseUrlPlaceholder: "https://your-service.example/v1",
    quickSetupCredentialLabel: "Credential",
    quickSetupNoCredential: "No credential needed",
    quickSetupKeyPlaceholder: "Only used for this local config request",
    quickSetupDetectHint: "Detects the service endpoint, protocol, and model catalog. Nothing is written to the real config directly.",
    quickSetupAdvanced: "Advanced parameters",
    quickSetupProtocolLabel: "Protocol",
    quickSetupChatCompletionsLabel: "OpenAI Chat Completions (compatible)",
    quickSetupAuthMethodLabel: "Auth method",
    quickSetupNoAuthLabel: "No auth (only if the service explicitly supports it)",
    quickSetupModelToAdd: "Model to add",
    quickSetupGoAgents: "Configure Agents",
    quickSetupSaving: "Saving…",
    quickSetupRetrySave: "Retry save",
    quickSetupSaveFinish: "Save and finish",
    migrationAliasTitle: "Legacy alias exit criteria",
    migrationLiveReferenceUnit: " live references",
    migrationAliasInUseTitle: "Aliases still in use",
    migrationAliasClearTitle: "Aliases meet the exit criteria",
    migrationAliasInUseBody: "Alias cleanup starts only after live references reach zero. This workbench does not offer deletion actions early.",
    migrationAliasClearBody: "Live references are already at zero. Alias deletion remains a controlled cleanup step later and is not executed automatically in this migration.",
    migrationV2Title: "Migrate to Provider-first schema v2",
    migrationNotPreviewed: "Not previewed",
    migrationCritical: "Migration modifies the external operator config. The schema v1 inventory stays read-only; you cannot add, update, or delete here.",
    migrationWhyTitle: "Why migration is needed",
    migrationFactProviders: "Provider groups",
    migrationFactLive: "Live references",
    migrationFactHistory: "Historical references",
    migrationWhyBody: "v1 mixes connections, credentials, and models in single records; v2 uses canonical providerId/modelRef. A backup is created before applying, and rollback is possible by migration ID on failure.",
    migrationMapAria: "v1 to v2 modelRef mapping",
    migrationMapEmpty: "The preview returned no model mappings.",
    migrationResolutionAria: "Model deployment identity conflict resolutions",
    migrationResolutionHeading: "Model deployment identities need explicit resolution",
    migrationResolutionHint: "Resolving only regenerates the server preview; it does not apply the migration.",
    migrationOfflineChip: "Offline unverified",
    migrationOfflineWarning: "verificationState: unverified_offline. Choose only from the server-allowed resolutions.",
    migrationDecisionAriaSuffix: " resolution",
    migrationDecisionPlaceholder: "Choose a resolution",
    migrationPreserveLabel: "Keep the existing upstream ID",
    migrationSplitLabel: "Split the deployment record and assign an upstream ID",
    migrationPreserveConfirm: "I confirm keeping this model's existing upstream ID",
    migrationNewUpstreamAriaSuffix: " new upstream ID",
    migrationUpstreamInvalid: "Enter a non-empty upstream ID that is not a path.",
    migrationRegenerateResolutions: "Regenerate resolution preview",
    migrationCredentialBlockedTitle: "Credential conflicts block apply",
    migrationCredentialBlockedTemplate: "{count} credential mapping conflicts must be resolved first. The UI never shows credential reference targets or secrets.",
    migrationUnresolvedHeading: "Unresolved conflicts",
    migrationGlobalFallback: "global",
    migrationNoConflictsTitle: "Preview has no blocking conflicts",
    migrationNoConflictsBody: "Apply still requires the final destructive impact confirmation; nothing runs automatically after preview.",
    migrationPreviewFirstTitle: "Generate the read-only migration preview first",
    migrationPreviewFirstBody: "The preview lists provider groups, old-to-new modelRefs, live references, and conflicts.",
    migrationActionsAria: "Migration actions",
    migrationPreviewAction: "Generate migration preview",
    migrationApplyTooltip: "Applying the migration modifies the external operator config.",
    migrationNeedPreviewFirst: "Generate a preview first",
    migrationConflictsRemain: "Unresolved conflicts remain",
    migrationInProgress: "A migration action is running",
    migrationApplyAction: "Apply migration",
    actionDiscoverProviderBusy: "Discovering provider models…",
    actionDiscoverBusy: "Discovering models…",
    actionDiscoverFoundTemplate: "Found {count} models",
    actionCatalogRefreshed: "Catalog refreshed",
    actionCreateProviderBusy: "Creating provider connection…",
    actionPinNoneMessage: "No models to pin. Click \"Discover models\" first and make sure the list has rows in \"Discovered\" state.",
    actionAllPinnedMessage: "All selected models were already pinned. Switched to the \"Added\" list.",
    actionUnpinBusy: "Unpinning model…",
    actionDeleteProviderConfirm: "Delete provider {id}? This only proceeds when no models are pinned.",
    actionDeleteProviderBusy: "Deleting provider…",
    actionCredentialBusy: "Updating provider API key…",
    actionSavingKey: "Saving API key…",
    actionKeySaved: "API key written to operator config",
    actionContextWindowBusy: "Updating context window…",
    actionSavingContextWindow: "Saving context window…",
    actionContextWindowSetTemplate: "Context window set to {value}",
    actionContextWindowCleared: "Provider context window cleared",
    actionToggleEnabledBusy: "Toggling provider…",
    actionRoutePreviewBusy: "Previewing route impact…",
    actionGeneratingRoutePreview: "Generating route preview…",
    actionRoutePreviewReady: "Route preview generated",
    actionRouteUnchanged: "The current route has no changes",
    actionRouteApplyBusy: "Updating provider route…",
    actionUpdatingRoute: "Updating provider route…",
    actionRouteApplied: "Provider route updated (unsaved)",
    pinBusyProgressTemplate: "Pinning models… ({completed}/{total})",
    pinBusyOneTemplate: "Pinning {ref}…",
    pinBusyManyTemplate: "Pinning {count} models…",
    pinSuccessNewTemplate: "{count} newly pinned",
    pinSuccessSkippedTemplate: "{count} already existed, skipped",
    pinSuccessFallback: "Pinning finished",
    pinSuccessListJoiner: ", ",
    pinSuccessSuffix: ". Switched to the \"Added\" list. Click \"Save to external config\" in the top right.",
    pinErrorPartialTemplate: "Failed after pinning {count}: {message}",
    pinErrorTemplate: "Pinning failed: {message}",
    migrationPreviewPending: "Generating migration preview…",
    migrationApplyConfirm: "This will modify the external operator config.\nLive references: {liveCount}\nCanonical model refs:\n{refs}\n\nApply the previewed migration?",
    migrationApplyPending: "Applying migration…",
    quickSetupPinFailedMessage: "The model was not added. Retry saving. Detection results and your selection are preserved.",
    quickSetupApplyBusy: "Applying quick setup…",
    quickSetupPartialSaveMessage: "The config was not saved yet. Detection results and the model selection are preserved. Click \"Retry save\".",
    testModelBusyTemplate: "Testing {ref}…",
    testRealCallTemplate: "Running a real test call against {ref}…",
    testCallOkTemplate: "{ref} is callable",
    testCallPersistedSuffix: " (real-call state persisted)",
    testCallFailedTemplate: "{ref} call failed: {reason}",
    testRequestFailedTemplate: "{ref} test request failed: {message}",
    discoveryFailureCredentialMissing: "No API key configured. Save this provider's credential first.",
    discoveryFailureCredentialRejected: "The API key was rejected upstream. Check the credential and retry.",
    discoveryFailureEndpointInvalid: "The service URL is invalid or not allowed. Check the endpoint config.",
    discoveryFailureNetwork: "Cannot reach the service URL. Check the network, LAN service, or port.",
    discoveryFailureTimeout: "The service response timed out. Retry later.",
    discoveryFailureProtocolMismatch: "This endpoint does not support the current discovery protocol. Use a compatible endpoint or enter models manually.",
    discoveryFailureInvalidResponse: "The service returned an incompatible model catalog format. Check the provider protocol.",
    discoveryFailureRateLimited: "The upstream is rate limiting temporarily. Retry later.",
    discoveryFailureUpstreamRejected: "The upstream service rejected the model catalog request. Check service status or protocol.",
    discoveryFailureDefault: "Model discovery is unavailable for this provider. Check the connection and retry.",
    avatarTypeError: "Avatars support PNG, JPG, or WebP images only.",
    avatarReadError: "This image could not be read.",
    avatarCropReadError: "The cropped image could not be read.",
    avatarCropUnsupported: "This browser cannot crop images.",
    avatarCropFailed: "Avatar cropping failed.",
    currentBadge: "Current",
    placeholderNavOverview: "Overview and save",
    placeholderNavInterface: "Interface and advanced",
    placeholderNavProfile: "User and avatar",
    placeholderNavModels: "Model library",
    placeholderNavRuntime: "Runtime and context",
    placeholderNavTooling: "Tools and diagnostics",
    sectionErrorPrefix: "Section save failed: ",
    sectionErrorInline: "These changes were not applied. Fix and retry; other sections are unaffected.",
    confirmTitle: "Confirm action",
    confirmAction: "Confirm",
  },
} as const;

export type ConfigCopy = Record<keyof (typeof CONFIG_COPY)["zh"], string>;

/** Substitute `{name}` placeholders in a copy template. Missing keys stay literal. */
export function formatConfigCopy(template: string, vars: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (match, key: string) =>
    Object.prototype.hasOwnProperty.call(vars, key) ? String(vars[key]) : match,
  );
}
