"""Public v2.1 workflow contract surface.

Each independently changing contract stays in its owning module; callers import
from this package boundary instead of growing ``models.py``.
"""

from ._canonical import canonical_json, sha256_hex
from ._validation import ContractValidationError
from .artifact_manifest import ArtifactManifest
from .artifact_receipt import ArtifactReceipt, BudgetReceipt
from .automation_policy import (
    AUTO_ADVANCE_CAPABILITIES,
    AUTO_ADVANCE_DRAIN_MODES,
    AUTO_ADVANCE_EXECUTION_MODES,
    AUTO_ADVANCE_POLICY_STATUSES,
    AUTO_ADVANCE_UI_PRESET_IDS,
    MAX_AUTO_REVISION_ROUNDS_ADJUSTABLE_TO,
    MAX_AUTO_REVISION_ROUNDS_DEFAULT,
    AutoAdvancePolicyV2,
    AutomationPolicyValidationError,
    HumanReviewPolicyV2,
    POLICY_CONTENT_HASH_RULE,
    compute_policy_content_hash,
)
from .budget import ResearchBudgetLedger
from .catalog_hypothesis_flow_readiness import (
    CATALOG_HYPOTHESIS_FLOW_EVIDENCE_IDS,
    CATALOG_HYPOTHESIS_FLOW_EVIDENCE_STATUSES,
    CATALOG_HYPOTHESIS_FLOW_NOT_READY_STATUS,
    CATALOG_HYPOTHESIS_FLOW_READY_STATUS,
    CATALOG_HYPOTHESIS_FLOW_REPAIR_ACTION,
    CATALOG_HYPOTHESIS_FLOW_REPORT_KIND,
    CATALOG_HYPOTHESIS_FLOW_SCHEMA_VERSION,
    RESEARCH_AUTHORIZATION_REQUIRED_ACTION,
    CatalogHypothesisFlowReadinessAuthority,
    CatalogHypothesisFlowReadinessReport,
    catalog_hypothesis_flow_report_hash,
)
from .claim_ledger import (
    ACCEPTED_REVIEW_STATUS,
    CLAIM_SOURCES,
    CLAIM_STATUSES,
    SUPPORT_LEVELS,
    ClaimEvidenceRef,
    ClaimLedgerEntry,
)
from .competition_evaluation import CompetitionEvaluationSnapshot
from .decision_record import (
    DECISION_KINDS,
    DECISION_STATUSES,
    DecisionRecord,
)
from .discussion_scope import (
    CANDIDATE_REVIEW_SCOPE_KIND,
    DISCUSSION_SCOPE_KINDS,
    DISCUSSION_SCOPE_VERSION,
    PREFORMAL_CANDIDATE_REVIEW_SCOPE_KIND,
    PREFORMAL_DISCUSSION_SCOPE_KINDS,
    PREFORMAL_DISCUSSION_SCOPE_VERSION,
    QUESTION_GENERATION_SCOPE_KIND,
    DiscussionScopeEnvelope,
    DiscussionScopeV1,
    PreformalCandidateReviewScopeV1,
    WorkflowDiscussionScopeV1,
    canonical_discussion_scope,
    canonical_discussion_scope_json,
    discussion_scope_hash,
    discussion_scope_hash_for,
    discussion_scope_key,
    discussion_scope_key_for,
    parse_discussion_scope,
    parse_discussion_scope_envelope,
    session_scope_key,
)
from .execution import NodeExecutionEnvelope, TaskLease, TaskLeaseStatus
from .execution_anchor import ExecutionAnchor
from .experiment_campaign import ExperimentCampaign, ExperimentCampaignStage
from .hypothesis import HypothesisCandidate, HypothesisPortfolio
from .hypothesis_fragment import (
    HYPOTHESIS_FRAGMENT_KIND,
    HYPOTHESIS_FRAGMENT_SCHEMA_VERSION,
    HypothesisFragment,
    canonical_fragment_payload,
)
from .hypothesis_quality import (
    AUXILIARY_HYPOTHESIS_DIAGNOSTIC_DIMENSIONS,
    HYPOTHESIS_SCORE_DIMENSIONS,
    HYPOTHESIS_SCORE_RUBRIC_SHA256,
    HYPOTHESIS_SCORE_RUBRIC_VERSION,
    canonical_hypothesis_score_rubric,
    hypothesis_score_rubric_sha256,
)
from .hypothesis_round import (
    COMPARISON_OUTCOMES,
    LINEAGE_KINDS,
    MEETING_REF_KINDS,
    MIN_CANDIDATES,
    ROUND_STATUSES,
    SCORE_DIMENSIONS,
    HypothesisLineageRef,
    HypothesisMeetingRef,
    HypothesisMetaReview,
    HypothesisPairwiseComparison,
    HypothesisParetoAnalysis,
    HypothesisRound,
    HypothesisRoundCandidate,
)
from .hypothesis_selection import MAX_SELECTED_CANDIDATES, HypothesisSelectionRecord
from .meeting_digest import MeetingDigest
from .meeting_round import MEETING_STATUSES, MEETING_TYPES, MeetingRound
from .node_readiness import (
    ActorReadiness,
    BudgetReadiness,
    NodeReadiness,
    ReadinessBlocker,
)
from .pending_action import ExecutionReceipt, PendingAction
from .personal_memory_candidate import (
    EVIDENCE_STATUSES,
    MEMORY_CLASSES,
    REUSE_POLICIES,
    PersonalMemoryCandidate,
)
from .platform_readiness import (
    BLOCKER_CAMPAIGN_THEME_MISMATCH,
    BLOCKER_DEV_THEME_ONLY,
    BLOCKER_THEME_NOT_ACTIVATED,
    PlatformFlowReadinessReport,
)
from .question_stage_binding import (
    QUESTION_PACKAGE_STAGES,
    QUESTION_STAGE_BINDING_POLICY_ID,
    QUESTION_STAGE_BINDING_SCHEMA_VERSION,
    QuestionStageBinding,
)
from .research_scope import (
    REQUIRED_SCOPE_FIELDS,
    ResearchScopeEnvelope,
    ScopeMode,
    parse_scope_mode,
    scope_hash_for,
    scope_identity_seed,
)
from .research_task_outputs import (
    RESEARCH_TASK_OUTPUT_SCHEMA_SHA256,
    RESEARCH_TASK_OUTPUT_SCHEMA_VERSION,
    HypothesisDesignOutput,
    ProtocolReviewOutput,
    ResultEvaluationOutput,
    canonical_research_task_output_schema_bundle,
    parse_research_task_output,
    research_task_output_schema_sha256,
)
from .research_team_role_contract import (
    CANDIDATE_GENERATION_MEETING_TYPE,
    CURRENT_RESEARCH_TEAM_ROLE_CONTRACT,
    HYPOTHESIS_REVIEW_MEETING_TYPE,
    LEGACY_READ_MODE,
    RESEARCH_PARTICIPANT_POLICY_VERSION,
    RESEARCH_TEAM_ROLE_CONTRACT_ID,
    RESEARCH_TEAM_ROLE_CONTRACT_VERSION,
    RESEARCH_TEAM_ROLE_SEMANTIC_VERSION,
    ProductAgentRole,
    ResearchParticipantPolicy,
    ResearchTeamRoleContract,
    SystemCapability,
    current_research_team_role_contract_snapshot,
)
from .research_template import (
    ADDENDUM_STATUSES,
    BASELINE_STATUSES,
    TemplateAddendum,
    TemplateBaseline,
)
from .review_independence import (
    ESCALATION_STATUS_FLAGGED_ONLY,
    REVIEW_ASSIGNMENT_SOURCES,
    REVIEW_DISAGREEMENT_DECISION_AXES,
    REVIEW_DISAGREEMENT_SCHEMA_VERSION,
    REVIEW_EXECUTION_MODES,
    REVIEW_INDEPENDENCE_SCHEMA_VERSION,
    REVIEW_STEP_NAMES,
    ReviewDisagreementArtifact,
    ReviewEscalation,
    ReviewPairDisagreement,
    ReviewScoreRef,
    ReviewerIndependenceRecord,
    inconsistent_axes_for_pair,
    review_step_identity,
    reviewer_independence_summary,
    validate_step_independence,
)
from .run_input import WorkflowRunInputSnapshot
from .session_scope import (
    SESSION_SCOPE_KINDS,
    SESSION_SCOPE_VERSION,
    WORKFLOW_CANDIDATE_SCOPE_KIND,
    WORKFLOW_NODE_ROOT_SCOPE_KIND,
    WorkflowSessionScopeV3,
)
from .task_bundle import ResearchSubtask, ResearchTaskBundle
from .theme_campaign import (
    DEFAULT_PROGRAM_ID,
    DEV_PROGRAM_ID,
    DEV_THEME_PREFIX,
    CampaignActivationStatus,
    ResearchCampaignActivation,
    ThemeContract,
    ThemeContractStatus,
    activation_scope_hash,
    build_campaign_activation_payload,
)
from .workflow_command import (
    ActorRef,
    CommandOffer,
    CommandReceipt,
    CommandRequest,
    ConfirmationContract,
    WorkflowCommandKind,
)
from .workflow_event import WorkflowEventEnvelope, WorkflowEventType
from .workflow_problem import (
    Remediation,
    RemediationKind,
    WorkflowProblem,
    WorkflowProblemCategory,
)
from .workflow_snapshot import (
    AgentBindingSummary,
    BudgetSummary,
    HandoffSummary,
    HumanTaskSummary,
    NodeAttemptSummary,
    ResearchWorkflowNodeDetail,
    ResearchWorkflowSnapshot,
    WorkflowRunSummary,
)

__all__ = [
    "ACCEPTED_REVIEW_STATUS",
    "ADDENDUM_STATUSES",
    "AUTO_ADVANCE_CAPABILITIES",
    "AUTO_ADVANCE_DRAIN_MODES",
    "AUTO_ADVANCE_EXECUTION_MODES",
    "AUTO_ADVANCE_POLICY_STATUSES",
    "AUTO_ADVANCE_UI_PRESET_IDS",
    "AUXILIARY_HYPOTHESIS_DIAGNOSTIC_DIMENSIONS",
    "BASELINE_STATUSES",
    "BLOCKER_CAMPAIGN_THEME_MISMATCH",
    "BLOCKER_DEV_THEME_ONLY",
    "BLOCKER_THEME_NOT_ACTIVATED",
    "CANDIDATE_GENERATION_MEETING_TYPE",
    "CANDIDATE_REVIEW_SCOPE_KIND",
    "CATALOG_HYPOTHESIS_FLOW_EVIDENCE_IDS",
    "CATALOG_HYPOTHESIS_FLOW_EVIDENCE_STATUSES",
    "CATALOG_HYPOTHESIS_FLOW_NOT_READY_STATUS",
    "CATALOG_HYPOTHESIS_FLOW_READY_STATUS",
    "CATALOG_HYPOTHESIS_FLOW_REPAIR_ACTION",
    "CATALOG_HYPOTHESIS_FLOW_REPORT_KIND",
    "CATALOG_HYPOTHESIS_FLOW_SCHEMA_VERSION",
    "CLAIM_SOURCES",
    "CLAIM_STATUSES",
    "COMPARISON_OUTCOMES",
    "CURRENT_RESEARCH_TEAM_ROLE_CONTRACT",
    "DECISION_KINDS",
    "DECISION_STATUSES",
    "DEFAULT_PROGRAM_ID",
    "DEV_PROGRAM_ID",
    "DEV_THEME_PREFIX",
    "DISCUSSION_SCOPE_KINDS",
    "DISCUSSION_SCOPE_VERSION",
    "EVIDENCE_STATUSES",
    "ESCALATION_STATUS_FLAGGED_ONLY",
    "HYPOTHESIS_FRAGMENT_KIND",
    "HYPOTHESIS_FRAGMENT_SCHEMA_VERSION",
    "HYPOTHESIS_REVIEW_MEETING_TYPE",
    "HYPOTHESIS_SCORE_DIMENSIONS",
    "HYPOTHESIS_SCORE_RUBRIC_SHA256",
    "HYPOTHESIS_SCORE_RUBRIC_VERSION",
    "LEGACY_READ_MODE",
    "LINEAGE_KINDS",
    "MAX_AUTO_REVISION_ROUNDS_ADJUSTABLE_TO",
    "MAX_AUTO_REVISION_ROUNDS_DEFAULT",
    "MAX_SELECTED_CANDIDATES",
    "MEETING_REF_KINDS",
    "MEETING_STATUSES",
    "MEETING_TYPES",
    "MEMORY_CLASSES",
    "MIN_CANDIDATES",
    "POLICY_CONTENT_HASH_RULE",
    "PREFORMAL_CANDIDATE_REVIEW_SCOPE_KIND",
    "PREFORMAL_DISCUSSION_SCOPE_KINDS",
    "PREFORMAL_DISCUSSION_SCOPE_VERSION",
    "QUESTION_GENERATION_SCOPE_KIND",
    "QUESTION_PACKAGE_STAGES",
    "QUESTION_STAGE_BINDING_POLICY_ID",
    "QUESTION_STAGE_BINDING_SCHEMA_VERSION",
    "REQUIRED_SCOPE_FIELDS",
    "RESEARCH_AUTHORIZATION_REQUIRED_ACTION",
    "RESEARCH_PARTICIPANT_POLICY_VERSION",
    "RESEARCH_TASK_OUTPUT_SCHEMA_SHA256",
    "RESEARCH_TASK_OUTPUT_SCHEMA_VERSION",
    "RESEARCH_TEAM_ROLE_CONTRACT_ID",
    "RESEARCH_TEAM_ROLE_CONTRACT_VERSION",
    "RESEARCH_TEAM_ROLE_SEMANTIC_VERSION",
    "REUSE_POLICIES",
    "REVIEW_ASSIGNMENT_SOURCES",
    "REVIEW_DISAGREEMENT_DECISION_AXES",
    "REVIEW_DISAGREEMENT_SCHEMA_VERSION",
    "REVIEW_EXECUTION_MODES",
    "REVIEW_INDEPENDENCE_SCHEMA_VERSION",
    "REVIEW_STEP_NAMES",
    "ROUND_STATUSES",
    "SCORE_DIMENSIONS",
    "SESSION_SCOPE_KINDS",
    "SESSION_SCOPE_VERSION",
    "SUPPORT_LEVELS",
    "WORKFLOW_CANDIDATE_SCOPE_KIND",
    "WORKFLOW_NODE_ROOT_SCOPE_KIND",
    "ActorReadiness",
    "ActorRef",
    "AgentBindingSummary",
    "ArtifactManifest",
    "ArtifactReceipt",
    "AutoAdvancePolicyV2",
    "AutomationPolicyValidationError",
    "BudgetReadiness",
    "BudgetReceipt",
    "BudgetSummary",
    "CampaignActivationStatus",
    "CatalogHypothesisFlowReadinessAuthority",
    "CatalogHypothesisFlowReadinessReport",
    "ClaimEvidenceRef",
    "ClaimLedgerEntry",
    "CommandOffer",
    "CommandReceipt",
    "CommandRequest",
    "CompetitionEvaluationSnapshot",
    "ConfirmationContract",
    "ContractValidationError",
    "DecisionRecord",
    "DiscussionScopeEnvelope",
    "DiscussionScopeV1",
    "ExecutionAnchor",
    "ExecutionReceipt",
    "ExperimentCampaign",
    "ExperimentCampaignStage",
    "HandoffSummary",
    "HumanReviewPolicyV2",
    "HumanTaskSummary",
    "HypothesisCandidate",
    "HypothesisDesignOutput",
    "HypothesisFragment",
    "HypothesisLineageRef",
    "HypothesisMeetingRef",
    "HypothesisMetaReview",
    "HypothesisPairwiseComparison",
    "HypothesisParetoAnalysis",
    "HypothesisPortfolio",
    "HypothesisRound",
    "HypothesisRoundCandidate",
    "HypothesisSelectionRecord",
    "MeetingDigest",
    "MeetingRound",
    "NodeAttemptSummary",
    "NodeExecutionEnvelope",
    "NodeReadiness",
    "PendingAction",
    "PersonalMemoryCandidate",
    "PlatformFlowReadinessReport",
    "PreformalCandidateReviewScopeV1",
    "ProductAgentRole",
    "ProtocolReviewOutput",
    "QuestionStageBinding",
    "ReadinessBlocker",
    "Remediation",
    "RemediationKind",
    "ResearchBudgetLedger",
    "ResearchCampaignActivation",
    "ResearchParticipantPolicy",
    "ResearchScopeEnvelope",
    "ResearchSubtask",
    "ResearchTaskBundle",
    "ResearchTeamRoleContract",
    "ResearchWorkflowNodeDetail",
    "ResearchWorkflowSnapshot",
    "ResultEvaluationOutput",
    "ReviewDisagreementArtifact",
    "ReviewEscalation",
    "ReviewPairDisagreement",
    "ReviewScoreRef",
    "ReviewerIndependenceRecord",
    "ScopeMode",
    "SystemCapability",
    "TaskLease",
    "TaskLeaseStatus",
    "TemplateAddendum",
    "TemplateBaseline",
    "ThemeContract",
    "ThemeContractStatus",
    "WorkflowCommandKind",
    "WorkflowDiscussionScopeV1",
    "WorkflowEventEnvelope",
    "WorkflowEventType",
    "WorkflowProblem",
    "WorkflowProblemCategory",
    "WorkflowRunInputSnapshot",
    "WorkflowRunSummary",
    "WorkflowSessionScopeV3",
    "activation_scope_hash",
    "build_campaign_activation_payload",
    "canonical_discussion_scope",
    "canonical_discussion_scope_json",
    "canonical_fragment_payload",
    "canonical_hypothesis_score_rubric",
    "canonical_json",
    "canonical_research_task_output_schema_bundle",
    "catalog_hypothesis_flow_report_hash",
    "compute_policy_content_hash",
    "current_research_team_role_contract_snapshot",
    "discussion_scope_hash",
    "discussion_scope_hash_for",
    "discussion_scope_key",
    "discussion_scope_key_for",
    "hypothesis_score_rubric_sha256",
    "inconsistent_axes_for_pair",
    "parse_discussion_scope",
    "parse_discussion_scope_envelope",
    "parse_research_task_output",
    "parse_scope_mode",
    "research_task_output_schema_sha256",
    "review_step_identity",
    "reviewer_independence_summary",
    "scope_hash_for",
    "scope_identity_seed",
    "session_scope_key",
    "sha256_hex",
    "validate_step_independence",
]
