export const companionVisualChatPreviewStyles = {
  page: "cvp-page",
  previewHeader: "cvp-preview-header",
  previewTitle: "cvp-preview-title",
  previewKicker: "cvp-preview-kicker",
  previewSubtitle: "cvp-preview-subtitle",
  previewControls: "cvp-preview-controls",
  frame: "cvp-frame",
  frameCompact: "cvp-frame cvp-frame--compact",
  portraitRail: "cvp-portrait-rail",
  portraitBackdrop: "cvp-portrait-backdrop",
  portraitTopbar: "cvp-portrait-topbar",
  portraitImage: "cvp-portrait-image",
  portraitGlow: "cvp-portrait-glow",
  portraitSummary: "cvp-portrait-summary",
  presenceLine: "cvp-presence-line",
  personName: "cvp-person-name",
  personStatus: "cvp-person-status",
  miniFacts: "cvp-mini-facts",
  miniFact: "cvp-mini-fact",
  chat: "cvp-chat",
  chatHeader: "cvp-chat-header",
  chatIdentity: "cvp-chat-identity",
  smallAvatar: "cvp-small-avatar",
  headerCopy: "cvp-header-copy",
  headerActions: "cvp-header-actions",
  timeline: "cvp-timeline",
  dayDivider: "cvp-day-divider",
  messageRow: "cvp-message-row",
  messageRowMine: "cvp-message-row cvp-message-row--mine",
  messageAvatar: "cvp-message-avatar",
  messageStack: "cvp-message-stack",
  messageBubble: "cvp-message-bubble",
  messageBubbleMine: "cvp-message-bubble cvp-message-bubble--mine",
  messageMeta: "cvp-message-meta",
  scenePostcard: "cvp-scene-postcard",
  sceneArt: "cvp-scene-art",
  sceneCopy: "cvp-scene-copy",
  typingBubble: "cvp-typing-bubble",
  typingDots: "cvp-typing-dots",
  composer: "cvp-composer",
  composerInput: "cvp-composer-input",
  composerActions: "cvp-composer-actions",
  lifeRail: "cvp-life-rail",
  lifeRailCollapsed: "cvp-life-rail cvp-life-rail--collapsed",
  lifeHeader: "cvp-life-header",
  lifeTitle: "cvp-life-title",
  lifeTabs: "cvp-life-tabs",
  lifeTabList: "cvp-life-tab-list",
  lifeTabTrigger: "cvp-life-tab-trigger",
  lifeTabContent: "cvp-life-tab-content",
  sceneCard: "cvp-scene-card",
  sceneCardArt: "cvp-scene-card-art",
  sceneCardCopy: "cvp-scene-card-copy",
  vitalGrid: "cvp-vital-grid",
  moodVisual: "cvp-mood-visual",
  energyVisual: "cvp-energy-visual",
  meter: "cvp-meter",
  meterFillEnergy: "cvp-meter-fill cvp-meter-fill--energy",
  meterFillSocial: "cvp-meter-fill cvp-meter-fill--social",
  nextCard: "cvp-next-card",
  nextTime: "cvp-next-time",
  nextCopy: "cvp-next-copy",
  timelineList: "cvp-life-timeline",
  timelineItem: "cvp-life-timeline-item",
  memoryGrid: "cvp-memory-grid",
  memoryCard: "cvp-memory-card",
  memoryArt: "cvp-memory-art",
  memoryCopy: "cvp-memory-copy",
  collapsedRail: "cvp-collapsed-rail",
  collapsedAvatar: "cvp-collapsed-avatar",
  note: "cvp-note",
} as const;
