"""Technical reading notes for the reviewed domain architecture flows.

This file is deliberately data-only. Flow topology and source anchors remain in
``flows.py``; these notes explain the current implementation at each node.
"""

DETAILS = {'teams': {'question': '团队成员发出的一条消息，怎样到达对应 Agent？',
           'entry': '从 Team 通信面板发起发送，进入团队消息 API。',
           'outcome': 'Agent Kernel 收到 message event；送达不表示 Agent 已处理完成。',
           'category': 'capability',
           'readingOrder': ['panel', 'api', 'route', 'team', 'bus', 'kernel', 'store'],
           'relatedViews': ['session', 'research', 'storage'],
           'nodes': {'panel': {'label': '发送团队消息',
                               'subtitle': 'TeamCommunicationPanel',
                               'summary': '收集消息并触发发送 mutation',
                               'role': 'entry',
                               'ownerPath': 'web/src/routes/teams/TeamCommunicationPanel.tsx',
                               'inputs': ['当前 teamId', '用户撰写的消息内容'],
                               'outputs': ['调用团队消息 mutation'],
                               'mechanism': ['TeamCommunicationPanel 收集团队消息输入。',
                                             'useTeamShellMutations 将发送动作接到领域 API。'],
                               'boundaries': ['这里只发起操作；Agent 是否醒来及其后续执行由内核策略决定。'],
                               'relatedViews': ['research', 'session']},
                     'api': {'label': '提交团队消息',
                             'subtitle': 'sendTeamProjectBusMessage',
                             'summary': 'POST 团队消息，不承担 Agent 执行',
                             'role': 'entry',
                             'ownerPath': 'web/src/api/projectAgentBus.ts',
                             'inputs': ['teamId', '消息请求体'],
                             'outputs': ['POST /api/teams/{teamId}/messages 的响应'],
                             'mechanism': ['sendTeamProjectBusMessage 通过公共 HTTP 客户端发起请求。',
                                           '请求地址按 teamId 指向团队消息 route。'],
                             'boundaries': ['API 成功只说明服务端接受/处理了请求，不能作为 Agent 完成工作的证据。'],
                             'relatedViews': ['session', 'research']},
                     'route': {'label': '接收团队请求',
                               'subtitle': 'team_message_create',
                               'summary': '校验请求并委托团队服务',
                               'role': 'entry',
                               'ownerPath': 'core/web/routes/teams.py',
                               'inputs': ['teamId 路径参数', '消息请求 DTO'],
                               'outputs': ['团队服务返回的发送结果'],
                               'mechanism': ['team_message_create 读取 teamId 与消息 DTO。',
                                             'route 将领域操作委托给 send_team_message。'],
                               'boundaries': ['route 是接入层；收件人选择与 Bus 投递由服务负责。'],
                               'relatedViews': ['session', 'research']},
                     'team': {'label': '解析团队收件人',
                              'subtitle': 'send_team_message',
                              'summary': '按活动成员列表确定本次收件人',
                              'role': 'process',
                              'ownerPath': 'core/web/services/team/team_crud.py',
                              'inputs': ['teamId', '消息文本', '团队当前 active member IDs'],
                              'outputs': ['带 teamId、teamName、source=team 的 Bus 请求'],
                              'mechanism': ['send_team_message 按当前 active member IDs 固定收件人范围。',
                                            '发送上下文附带 teamId、teamName 和 source=team。'],
                              'boundaries': ['收件人来自当前团队成员状态；Bus 送达事件不是 Agent 执行回执。'],
                              'relatedViews': ['research', 'session']},
                     'bus': {'label': '投递 Agent 消息',
                             'subtitle': 'send_project_agent_bus_message',
                             'summary': '构造 message event 并追加投递记录',
                             'role': 'process',
                             'ownerPath': 'core/web/services/project_agent_bus_service.py',
                             'inputs': ['目标 Agent', '消息正文', '团队来源上下文'],
                             'outputs': ['Agent message event', '事件 JSONL 追加记录'],
                             'mechanism': ['send_project_agent_bus_message 为收件人构造 Agent message event。',
                                           '投递事件追加到 Bus JSONL 记录。'],
                             'boundaries': ['事件记录描述传输路径；它不是会话 transcript，也不证明后续回合已经结束。'],
                             'relatedViews': ['session', 'storage']},
                     'kernel': {'label': '提交内核事件',
                                'subtitle': 'submit_agent_message_event',
                                'summary': '进入内核接收边界，后续由策略调度',
                                'role': 'external',
                                'ownerPath': 'core/web/services/project_agent_bus_service.py',
                                'inputs': ['submit_agent_message_event 接收的 Agent message event'],
                                'outputs': ['内核接受或拒绝的投递结果'],
                                'mechanism': ['Bus 服务将消息交给 submit_agent_message_event。',
                                              '后续是否唤醒 Agent 由 Agent Kernel 策略处理。'],
                                'boundaries': ['不把投递成功等同于已创建回合、已生成回复或已完成任务。'],
                                'relatedViews': ['session', 'stream']},
                     'store': {'label': '保存团队与画布',
                               'subtitle': 'create_team · teams.json · canvas.json',
                               'summary': 'teams.json 与各团队 canvas.json 各司其职',
                               'role': 'store',
                               'ownerPath': 'core/web/services/team/team_crud.py',
                               'inputs': ['团队创建/更新字段', '画布节点与连线内容'],
                               'outputs': ['团队记录',
                                           '每队独立的 canvas.json',
                                           '相关 direct session / linked chat room 标识'],
                               'mechanism': ['create_team 创建团队配置并管理 teams.json。',
                                             '画布按 team 写入独立 canvas.json，并维护关联聊天资源。'],
                               'boundaries': ['团队文件与画布不是研究 Workflow Ledger；不合并为一个运行账本。'],
                               'relatedViews': ['research', 'storage']}}},
 'research': {'question': '研究运行如何固定定义、可靠调度，并恢复已提交事件？',
              'entry': '创建 Question Run 时固定输入、定义和 binding 快照。',
              'outcome': '运行状态与事件可从 Ledger 回放；图执行位置由独立 checkpoint 恢复。',
              'category': 'capability',
              'readingOrder': ['create',
                               'definition',
                               'command',
                               'ledger',
                               'graph',
                               'checkpoint',
                               'adapter',
                               'ports',
                               'replay'],
              'relatedViews': ['teams', 'knowledge', 'session', 'storage'],
              'nodes': {'create': {'label': '创建研究运行',
                                   'subtitle': 'create_question_run',
                                   'summary': '固定定义、binding 与初始图状态',
                                   'role': 'process',
                                   'ownerPath': 'core/web/services/team_workflow/research_runtime/run_creation.py',
                                   'inputs': ['团队研究请求', '当前 Stage-One 定义及运行 binding'],
                                   'outputs': ['question run', 'definition/binding 快照', '初始 checkpoint'],
                                   'mechanism': ['create_question_run 生成本次运行的服务端输入。',
                                                 '同次创建固定 definition、binding 快照和起始 checkpoint。'],
                                   'boundaries': ['运行使用创建时固定的定义，不随团队后续配置漂移。',
                                                  'Knowledge sideflow 是独立 child run，不是 Stage-One 主图节点。'],
                                   'relatedViews': ['teams', 'knowledge', 'storage']},
                        'definition': {'label': '定义研究主图',
                                       'subtitle': 'Stage-One: problem_understanding → hypothesis_design '
                                                   '→ result_package',
                                       'summary': '主图顺序为理解、假设设计、结果包',
                                       'role': 'control',
                                       'ownerPath': 'core/research/workflow/stage_one_definition.py',
                                       'inputs': ['问题理解阶段输出', '假设设计阶段输入与结果'],
                                       'outputs': ['problem_understanding → hypothesis_design → '
                                                   'result_package 图结构'],
                                       'mechanism': ['Stage-One 定义主图的三个有序节点及依赖。',
                                                     '其他 workflow definition 独立维护，不混入当前主图。'],
                                       'boundaries': ['只代表当前 Stage-One 主图，不把其他工作流或历史版本塞入该图。'],
                                       'relatedViews': ['teams', 'knowledge']},
                        'command': {'label': '校验工作流命令',
                                    'subtitle': 'WorkflowCommandService',
                                    'summary': '核验权限、幂等键、版本与 readiness',
                                    'role': 'control',
                                    'ownerPath': 'core/web/services/team_workflow/research_runtime/command_service.py',
                                    'inputs': ['runId',
                                               'team 上下文',
                                               '幂等键',
                                               '预期 runVersion',
                                               'command payload'],
                                    'outputs': ['已提交的 command / attempt / event 与待调度项'],
                                    'mechanism': ['WorkflowCommandService 校验 team、幂等键与预期 runVersion。',
                                                  '处理 start_node 等命令前还检查 readiness。'],
                                    'boundaries': ['命令验证成功不代表工作已完成；执行发生在已提交 outbox 被 worker 消费之后。'],
                                    'relatedViews': ['teams', 'storage']},
                        'ledger': {'label': '提交运行事务',
                                   'subtitle': 'WorkflowLedgerStore',
                                   'summary': '一次 UoW 原子提交命令、事件与 outbox',
                                   'role': 'store',
                                   'ownerPath': 'core/research/workflow/ledger/store.py',
                                   'inputs': ['command 与 attempt',
                                              'run 状态变化',
                                              'graph_dispatch 任务',
                                              'workflow event'],
                                   'outputs': ['workflow-ledger.sqlite 中已提交的业务事实和待消费 outbox'],
                                   'mechanism': ['WorkflowLedgerStore 通过单写入器处理状态变更。',
                                                 'command、attempt、outbox、event 与 run 更新在一个 UoW 提交。'],
                                   'boundaries': ['Ledger 保存业务运行权威；图执行位置另存 checkpoint，不替代 Session '
                                                  'transcript。'],
                                   'relatedViews': ['storage', 'session']},
                        'graph': {'label': '调度研究节点',
                                  'subtitle': 'GraphDispatchWorker',
                                  'summary': '读取 outbox、恢复 checkpoint 并决定后继',
                                  'role': 'process',
                                  'ownerPath': 'core/web/services/team_workflow/research_runtime/graph_dispatch_worker.py',
                                  'inputs': ['已提交 graph_dispatch outbox',
                                             'LangGraph checkpoint',
                                             '上游节点结果'],
                                  'outputs': ['后继图节点或领域 adapter 调度'],
                                  'mechanism': ['GraphDispatchWorker 消费已提交的 graph_dispatch outbox。',
                                                '借助 LangGraph checkpoint 恢复位置，并按上游成功与 handoff 决定后继。'],
                                  'boundaries': ['Worker 只处理 Ledger 已提交的调度项；不得从前端状态推断尚未提交的工作。'],
                                  'relatedViews': ['storage', 'knowledge']},
                        'checkpoint': {'label': '恢复图执行状态',
                                       'subtitle': 'runtime_factory · checkpoints.sqlite',
                                       'summary': '图 checkpoint 与业务账本分开保存',
                                       'role': 'store',
                                       'ownerPath': 'core/web/services/team_workflow/research_runtime/runtime_factory.py',
                                       'inputs': ['图节点执行状态与恢复元数据'],
                                       'outputs': ['checkpoints.sqlite 中可恢复的图位置'],
                                       'mechanism': ['runtime_factory 为图状态配置 checkpoints.sqlite。',
                                                     '业务运行与命令仍由 workflow-ledger.sqlite 管理，职责分开。'],
                                       'boundaries': ['checkpoints.sqlite 不取代 workflow-ledger.sqlite 中的 '
                                                      'command、run 和 event 业务权威。'],
                                       'relatedViews': ['storage']},
                        'adapter': {'label': '执行领域动作',
                                    'subtitle': 'AdapterDispatchWorker',
                                    'summary': '预检、预算检查后调用 adapter 并核对版本',
                                    'role': 'process',
                                    'ownerPath': 'core/web/services/team_workflow/research_runtime/adapter_dispatch_worker.py',
                                    'inputs': ['图产生的领域动作', '固定的 task / artifact 目标', '执行预算'],
                                    'outputs': ['领域执行结果', '产物 hash / revision 验收记录'],
                                    'mechanism': ['AdapterDispatchWorker 先校验输入、预检条件和执行预算。',
                                                  '完成领域调用后回读产物 hash/revision 进行验收。'],
                                    'boundaries': ['adapter 结果必须对应预期产物版本；仅有工具/任务启动结果不等于交付产物验收。'],
                                    'relatedViews': ['session', 'knowledge']},
                        'ports': {'label': '连接真实执行端口',
                                  'subtitle': 'RealDomainPorts.create_agent_task',
                                  'summary': '具体 Agent task 和原生 Session 的执行边界',
                                  'role': 'external',
                                  'ownerPath': 'core/web/services/team_workflow/research_runtime/real_domain_ports.py',
                                  'inputs': ['研究动作参数', '目标 Agent 与上下文'],
                                  'outputs': ['Agent task / 原生 Session 执行结果和产物信息'],
                                  'mechanism': ['RealDomainPorts 将研究动作映射到具体 Agent task 或原生 Session。',
                                                '执行回执和产物信息再转成 workflow 可消费的结果。'],
                                  'boundaries': ['端口连接既有真实执行能力，不另建第二套 Agent 回合或 transcript。'],
                                  'relatedViews': ['session', 'stream', 'teams']},
                        'replay': {'label': '回放持久事件',
                                   'subtitle': 'event_replay_service',
                                   'summary': '回放已提交 workflow_events 而非 SSE 缓存',
                                   'role': 'process',
                                   'ownerPath': 'core/web/services/team_workflow/research_runtime/event_replay_service.py',
                                   'inputs': ['runId', '已提交 workflow_events', '前端 snapshot 与事件游标'],
                                   'outputs': ['有序事件回放', '由前端 reducer 更新的运行投影'],
                                   'mechanism': ['event_replay_service 从 Ledger 读取已提交 workflow_events。',
                                                 '前端 hydrate snapshot 后用 reducer 应用事件；SSE 只是实时投影通道。'],
                                   'boundaries': ['SSE 是实时传输/投影通道；事件权威来自持久 Ledger，不能将丢失的 SSE 当作丢失业务事件。'],
                                   'relatedViews': ['storage', 'stream']}}},
 'knowledge': {'question': 'Agent 的知识查询如何先守住范围权限，再返回可引用结果？',
               'entry': '带 Agent identity 与查询范围的统一搜索工具调用。',
               'outcome': '返回受权限过滤的结果；RAG 输出有界 contexts 与 citations。',
               'category': 'capability',
               'readingOrder': ['tool', 'unified', 'canonical', 'acl', 'rank', 'index', 'rag'],
               'relatedViews': ['knowledge-write', 'tools', 'storage', 'research'],
               'nodes': {'tool': {'label': '发起受限搜索',
                                  'subtitle': 'unified_memory_search_tool',
                                  'summary': '要求 Agent identity 并限制查询范围',
                                  'role': 'entry',
                                  'ownerPath': 'tools/team_knowledge_tools.py',
                                  'inputs': ['Agent identity',
                                             'query / query_mode',
                                             'knowledge base 或用户 Space 范围'],
                                  'outputs': ['统一搜索结果及必要的来源元数据'],
                                  'mechanism': ['unified_memory_search_tool 要求 Agent identity 并校验查询主体。',
                                                '读取知识库 read policy 与用户 Space allowlist 后才调用搜索服务。',
                                                '@audit_memory_tool 记录 blocked/failed 终态和有限标识，不记录完整参数正文。'],
                                  'boundaries': ['受 knowledge read policy 与 Space allowlist '
                                                 '约束；不是任意文件读取器。',
                                                 '返回搜索证据，不负责把结果直接注入 Agent prompt。'],
                                  'relatedViews': ['knowledge-write', 'tools']},
                         'unified': {'label': '分派统一检索',
                                     'subtitle': 'search_unified_memory',
                                     'summary': '统一入口按模式查询正式知识及其他来源',
                                     'role': 'process',
                                     'ownerPath': 'core/web/services/unified_knowledge_search_service.py',
                                     'inputs': ['身份和可见范围', '查询文本及 query_mode', '可选知识库/研究来源过滤条件'],
                                     'outputs': ['带查询模式与来源信息的搜索结果'],
                                     'mechanism': ['search_unified_memory 按 query_mode '
                                                   '分派正式知识、个人记忆和用户显式内容。',
                                                   'literal、semantic、hybrid、metadata、regex 与 RAG '
                                                   '分支各有检索路径。'],
                                     'boundaries': ['统一接口不表示各来源共享一套正文存储或 ACL；每个来源仍执行自己的范围规则。'],
                                     'relatedViews': ['knowledge-write', 'storage', 'research']},
                         'canonical': {'label': '筛选正式知识',
                                       'subtitle': 'search_knowledge_items',
                                       'summary': '按 owner、来源、状态与资格条件检索',
                                       'role': 'process',
                                       'ownerPath': 'core/web/services/team_knowledge/retrieval.py',
                                       'inputs': ['query', 'owner / team / knowledgeBase 范围', '研究来源过滤条件'],
                                       'outputs': ['满足生命周期、来源和授权条件的条目候选'],
                                       'mechanism': ['search_knowledge_items 从 canonical items 构造正式知识候选。',
                                                     '再按 owner、来源、eligibility 与权限条件过滤。'],
                                       'boundaries': ['只读正式知识；提案不自动成为可检索条目，索引也不是正文权威。'],
                                       'relatedViews': ['knowledge-write', 'storage']},
                         'acl': {'label': '检查知识权限',
                                 'subtitle': '_require_permission',
                                 'summary': '对 owner 与 knowledge base 执行读取权限检查',
                                 'role': 'control',
                                 'ownerPath': 'core/web/services/team_knowledge/permissions.py',
                                 'inputs': ['Agent ID', '知识库 owner / base', 'read 操作'],
                                 'outputs': ['允许继续或抛出 permission error'],
                                 'mechanism': ['_require_permission 将 Agent 与 owner/base 交给访问策略。',
                                               '策略按 read、propose、review 等动作分别检查权限。'],
                                 'boundaries': ['必须在条目内容对调用方可见之前检查；owner 与基础范围不是绕过授权的凭据。'],
                                 'relatedViews': ['knowledge-write', 'tools']},
                         'rank': {'label': '排序检索结果',
                                  'subtitle': 'rank_candidates',
                                  'summary': '支持 BM25、semantic 与 hybrid 路径',
                                  'role': 'process',
                                  'ownerPath': 'core/web/services/team_knowledge/semantic.py',
                                  'inputs': ['已过滤候选', 'query', '请求的检索模式', '向量模型 readiness'],
                                  'outputs': ['按相关度排序的候选及实际检索状态'],
                                  'mechanism': ['rank_candidates 在 ACL 与生命周期过滤后排序候选。',
                                                '依模式使用 BM25、semantic 或 hybrid，并回报降级状态。'],
                                  'boundaries': ['hybrid 的向量不可用时可如实降为 BM25；状态应说明语义匹配不可用，不伪装成功。'],
                                  'relatedViews': ['knowledge-write']},
                         'index': {'label': '可重建向量索引',
                                   'subtitle': 'rank_candidates → _read_json',
                                   'summary': '排序只读匹配候选的向量记录',
                                   'role': 'store',
                                   'ownerPath': 'core/web/services/rag_vector_index_service.py',
                                   'inputs': ['通过 ACL 与生命周期筛选的候选条目',
                                              '候选 ID、内容 hash 与模型 readiness'],
                                   'outputs': ['索引记录字段：status、embeddingModel、contentHash、chunks',
                                               '缺失记录为空对象，由排序器处理缺失或陈旧状态'],
                                   'mechanism': ['rank_candidates 按候选 ID 调用 _item_record_path，再由 _read_json 读取记录。',
                                                 '只采用 status、模型名、contentHash 和向量维度均匹配的 chunks。',
                                                 '写入仍由 write_index_record 承担，经 knowledge-write 的 sync_reviewed_item 触发；查询只读。'],
                                   'boundaries': ['索引是派生数据；索引失败或过期不改写 canonical knowledge item。'],
                                   'relatedViews': ['knowledge-write', 'storage']},
                         'rag': {'label': '组装检索上下文',
                                 'subtitle': 'retrieve_rag_contexts',
                                 'summary': '输出有界 contexts 与 citations',
                                 'role': 'process',
                                 'ownerPath': 'core/web/services/rag_retrieval_service.py',
                                 'inputs': ['Agent ID', 'query', 'owner/team/knowledge base 和研究范围'],
                                 'outputs': ['有界 contexts', '对应 citations', 'retrieval policy 与状态'],
                                 'mechanism': ['retrieve_rag_contexts 只在 rag 查询模式下执行。',
                                               '返回有长度上限的 contexts/citations，不拥有 prompt 装配权。'],
                                 'boundaries': ['RAG service 返回证据包，不取代工具授权，也不单独拥有 Agent prompt 装配权。'],
                                 'relatedViews': ['knowledge-write', 'tools', 'research']}}},
 'knowledge-write': {'question': '什么内容经过审核才成为正式知识，哪些记忆走独立持久化？',
                     'entry': '正式知识可经 refinement proposal 审核，也可走明确的来源接收流程。',
                     'outcome': '正式条目成为 canonical data；语义索引、个人事件与文件记忆保持独立。',
                     'category': 'data',
                     'readingOrder': ['proposal',
                                      'review',
                                      'items',
                                      'sync',
                                      'index',
                                      'ingest',
                                      'episodic',
                                      'filememory'],
                     'relatedViews': ['knowledge', 'storage', 'tools'],
                     'nodes': {'proposal': {'label': '创建知识提案',
                                            'subtitle': 'create_refinement_proposal',
                                            'summary': '绑定来源并创建待审 refinement proposal',
                                            'role': 'process',
                                            'ownerPath': 'core/web/services/team_knowledge/governance.py',
                                            'inputs': ['knowledgeBaseId',
                                                       '提案 Agent',
                                                       '标题/摘要/内容',
                                                       'source artifact IDs',
                                                       '可选审核人'],
                                            'outputs': ['带来源引用和审核状态的 proposal'],
                                            'mechanism': ['create_refinement_proposal 校验知识库范围、来源和提案权限。',
                                                          '它记录待审核内容，不直接发布为正式知识条目。'],
                                            'boundaries': ['创建提案不代表其内容已被接受或可供正式知识检索。'],
                                            'relatedViews': ['knowledge', 'tools']},
                               'review': {'label': '审核并应用提案',
                                          'subtitle': 'review_refinement_proposal',
                                          'summary': '接受并应用后才写正式批次与条目',
                                          'role': 'control',
                                          'ownerPath': 'core/web/services/team_knowledge/governance.py',
                                          'inputs': ['knowledgeBaseId',
                                                     'proposalId',
                                                     '审核结论',
                                                     'reviewer Agent'],
                                          'outputs': ['审核状态', '接受时产生的正式条目批次与审计记录'],
                                          'mechanism': ['review_refinement_proposal 检查 reviewer 的 review '
                                                        '权限。',
                                                        '接受并应用的分支创建正式 item、batch 和审计记录。'],
                                          'boundaries': ['仅有 proposal 或审核意见不等于已发布内容；失败/拒绝路径不能当作正式条目。'],
                                          'relatedViews': ['knowledge', 'tools', 'storage']},
                               'items': {'label': '保存正式知识',
                                         'subtitle': '_knowledge_root_for_owner',
                                         'summary': '条目、来源、提案、批次与审计按 owner 落盘',
                                         'role': 'store',
                                         'ownerPath': 'core/web/services/team_knowledge/store.py',
                                         'inputs': ['ownerType/ownerId', '知识库、来源和条目变更'],
                                         'outputs': ['owner-scoped knowledge files 与 canonical item 记录'],
                                         'mechanism': ['_knowledge_root_for_owner 按 ownerType 与 ownerId '
                                                       '定位知识根目录。',
                                                       'store 在该 owner 范围持久化知识库、来源、提案、items、批次和审计。'],
                                         'boundaries': ['team 与 Agent 的知识空间隔离；正式正文权威不依赖可重建的向量索引。'],
                                         'relatedViews': ['knowledge', 'storage']},
                               'sync': {'label': '同步语义索引',
                                        'subtitle': 'sync_reviewed_item',
                                        'summary': 'reviewed item 以内容 hash 同步到检索索引',
                                        'role': 'process',
                                        'ownerPath': 'core/web/services/team_knowledge/semantic.py',
                                        'inputs': ['已应用 item', 'Agent review 权限', 'embedding readiness'],
                                        'outputs': ['indexed / stale / unavailable / failed 状态'],
                                        'mechanism': ['sync_reviewed_item 处理已应用条目，并检查 embedding '
                                                      'readiness 与 review 权限。',
                                                      '同步失败只回报索引状态，不撤销 canonical item。'],
                                        'boundaries': ['索引未就绪或同步失败不撤销已经审核生效的 canonical 条目。'],
                                        'relatedViews': ['knowledge', 'storage']},
                               'index': {'label': '保存向量记录',
                                         'subtitle': 'write_index_record',
                                         'summary': '存储向量记录，不作为正式知识正文',
                                         'role': 'store',
                                         'ownerPath': 'core/web/services/rag_vector_index_service.py',
                                         'inputs': ['正式 item 元数据', '内容 hash', 'embedding model 与 chunks'],
                                         'outputs': ['向量记录与索引健康状态'],
                                         'mechanism': ['write_index_record 按正式 item 内容生成向量元数据和 chunks。',
                                                       '检索索引可重建，不作为正式知识正文权威。'],
                                         'boundaries': ['可从正式条目重建；不可用索引不等于知识内容丢失。'],
                                         'relatedViews': ['knowledge', 'storage']},
                               'ingest': {'label': '审核来源导入',
                                          'subtitle': 'knowledge_ingestion_tool',
                                          'summary': 'inbox_source_id 路径须 accept 后才导入',
                                          'role': 'entry',
                                          'ownerPath': 'tools/team_knowledge_tools.py',
                                          'inputs': ['knowledgeBaseId',
                                                     '来源类型与引用',
                                                     'excerpt/提案内容',
                                                     '可选 inbox source ID'],
                                          'outputs': ['接收结果及 accept 后的正式 ingest 结果'],
                                          'mechanism': ['knowledge_ingestion_tool 接收来源引用和可选 '
                                                        'inbox_source_id。',
                                                        'inbox 来源经 accept 后才调用 ingest_on_accept。',
                                                        '@audit_memory_tool 记录 blocked/failed 终态和有限标识，不记录完整参数正文。'],
                                          'boundaries': ['不是每次工具调用都会直接写正式 items；来源接收与提案审核是不同治理路径。'],
                                          'relatedViews': ['knowledge', 'tools']},
                               'episodic': {'label': '追加个人记忆',
                                            'subtitle': 'append_episodic_event',
                                            'summary': '个人事件写 JSONL 且受 memoryPolicy 控制',
                                            'role': 'store',
                                            'ownerPath': 'core/web/services/agent_directory/episodic_memory.py',
                                            'inputs': ['Agent ID', '事件文本/类型', '时间与引用'],
                                            'outputs': ['workspace/agents/{id}/events/episodic_events.jsonl '
                                                        '事件'],
                                            'mechanism': ['append_episodic_event 先检查 Agent 的 '
                                                          'memoryPolicy.enabled。',
                                                          '启用后以 JSONL 追加一条私有事件，不调用 LLM。'],
                                            'boundaries': ['这是 Agent 私有事件记忆，不是正式团队知识，也不是 Session '
                                                           'transcript。'],
                                            'relatedViews': ['storage', 'session', 'knowledge']},
                               'filememory': {'label': '保存文件记忆',
                                              'subtitle': '_save_memory',
                                              'summary': '工具写入自己的 memory 文件，不并入 Journal',
                                              'role': 'store',
                                              'ownerPath': 'tools/memory_tools.py',
                                              'inputs': ['memory tool 接收的结构化记忆对象'],
                                              'outputs': ['memory index 路径下的 JSON 文件'],
                                              'mechanism': ['_save_memory 将 memory 对象写到工具解析出的记忆文件。',
                                                            '文件记忆路径与 Turn Journal 和正式知识 items 分开。'],
                                              'boundaries': ['与 episodic JSONL、正式知识 items 和 Session Turn '
                                                             'Journal 分属不同存储与语义。'],
                                              'relatedViews': ['storage', 'session', 'knowledge']}}},
 'self-evolution': {'question': '自主进化如何形成候选，并在哪个边界等待明确批准？',
                    'entry': '启动 autonomous self-evolution run，由默认 orchestrator 建立 WorkRun。',
                    'outcome': '候选及验证结果停在批准边界；批准后才进入集成与清理。',
                    'category': 'capability',
                    'readingOrder': ['start',
                                     'workrun',
                                     'observe',
                                     'plan',
                                     'evolve',
                                     'review',
                                     'approve',
                                     'integrate'],
                    'relatedViews': ['supervised', 'gym', 'storage'],
                    'nodes': {'start': {'label': '启动自主运行',
                                        'subtitle': 'start_autonomous_self_evolution',
                                        'summary': '创建 WorkRun 并启动 observe-plan-evolve',
                                        'role': 'entry',
                                        'ownerPath': 'core/web/services/self_evolution_autonomous_loop_orchestrator.py',
                                        'inputs': ['目标和约束', '请求者/项目上下文'],
                                        'outputs': ['WorkRun ID 与初始化运行状态'],
                                        'mechanism': ['start_autonomous_self_evolution 使用默认 orchestrator '
                                                      '创建 WorkRun。',
                                                      '服务按 observe、plan、evolve 顺序推进至待审边界。'],
                                        'boundaries': ['自主运行不能绕过后续显式审批；它不等同于监督 Worktree 的双次评测流程。'],
                                        'relatedViews': ['supervised', 'storage']},
                              'observe': {'label': '收集目标证据',
                                          'subtitle': 'observe',
                                          'summary': '观察阶段为后续计划提供当前证据',
                                          'role': 'process',
                                          'ownerPath': 'core/web/services/self_evolution_autonomous_loop_runtime.py',
                                          'inputs': ['目标', '当前工作区和可读取的项目证据'],
                                          'outputs': ['结构化观察结果'],
                                          'mechanism': ['observe 阶段读取与当前目标相关的状态和证据。',
                                                        '结构化观察结果成为后续 plan 的输入。'],
                                          'boundaries': ['观察结果是本次运行的输入证据，不自动赋予修改权限或批准候选。'],
                                          'relatedViews': ['knowledge', 'storage']},
                              'plan': {'label': '制定修改计划',
                                       'subtitle': 'plan',
                                       'summary': '形成目标文件边界内的候选执行计划',
                                       'role': 'process',
                                       'ownerPath': 'core/web/services/self_evolution_autonomous_loop_runtime.py',
                                       'inputs': ['Observe 结果', '目标与允许修改范围'],
                                       'outputs': ['候选修改计划及待验证内容'],
                                       'mechanism': ['plan 阶段结合观察结果和允许范围生成候选计划。', '计划指导候选构建，不会自行触发集成。'],
                                       'boundaries': ['计划本身不产生集成效果；是否执行仍受运行约束与最终审批门控制。'],
                                       'relatedViews': ['supervised']},
                              'evolve': {'label': '生成候选改动',
                                         'subtitle': '_evolve_candidate',
                                         'summary': '按目标文件边界操作隔离候选',
                                         'role': 'process',
                                         'ownerPath': 'core/web/services/self_evolution_autonomous_loop_runtime.py',
                                         'inputs': ['计划', '隔离工作区', '允许修改文件边界'],
                                         'outputs': ['候选改动与验证结果'],
                                         'mechanism': ['_evolve_candidate 在隔离候选工作区执行计划。',
                                                       '候选修改受目标文件边界约束并运行指定验证。'],
                                         'boundaries': ['候选只保存在运行候选中；通过验证也不自动合并或激活。'],
                                         'relatedViews': ['supervised', 'storage']},
                              'review': {'label': '等待明确批准',
                                         'subtitle': 'run_until_review',
                                         'summary': '候选生成后等待用户明确批准',
                                         'role': 'control',
                                         'ownerPath': 'core/web/services/self_evolution_autonomous_loop_service.py',
                                         'inputs': ['候选 diff/验证结果', '当前 WorkRun 状态'],
                                         'outputs': ['awaiting_user_approval 状态'],
                                         'mechanism': ['run_until_review 依次调用 observe、plan、evolve hooks。',
                                                       '随后持久化 awaiting_user_approval 并返回，不执行集成。'],
                                         'boundaries': ['候选生成、验证通过都不能代替批准；拒绝分支不集成。'],
                                         'relatedViews': ['supervised', 'gym']},
                              'approve': {'label': '批准候选改动',
                                          'subtitle': 'approve',
                                          'summary': '只有 approve 进入集成，拒绝不集成',
                                          'role': 'control',
                                          'ownerPath': 'core/web/services/self_evolution_autonomous_loop_service.py',
                                          'inputs': ['WorkRun ID', '显式批准或拒绝决定'],
                                          'outputs': ['批准后进入 integrate，或保留非集成的拒绝结果'],
                                          'mechanism': ['approve 校验运行是否处于待审状态并读取决定。',
                                                        '显式批准才调度 integrate；拒绝分支不集成。'],
                                          'boundaries': ['此 view 是自主进化的用户批准链；不表示监督流程中审批一定由用户执行。'],
                                          'relatedViews': ['supervised']},
                              'integrate': {'label': '集成并清理',
                                            'subtitle': 'integrate',
                                            'summary': '集成与 cleanup 发生在明确批准之后',
                                            'role': 'process',
                                            'ownerPath': 'core/web/services/self_evolution_autonomous_loop_orchestrator.py',
                                            'inputs': ['已批准的 WorkRun',
                                                       '候选产物',
                                                       'orchestrator runtime hooks'],
                                            'outputs': ['集成结果', '已清理的本次任务资源'],
                                            'mechanism': ['orchestrator 的 integrate hook 处理已批准候选。',
                                                          '收尾 hook 清理本次 WorkRun 的任务资源。'],
                                            'boundaries': ['集成只针对已批准候选；本 view 不表示远端发布或用户环境已运行验证。'],
                                            'relatedViews': ['storage', 'supervised']},
                              'workrun': {'label': '保存自主运行状态',
                                          'subtitle': 'build_default_orchestrator',
                                          'summary': '自主 WorkRun 与监督 worktree run 分开保存',
                                          'role': 'store',
                                          'ownerPath': 'core/web/services/self_evolution_autonomous_loop_orchestrator.py',
                                          'inputs': ['WorkRun 创建/阶段状态/候选结果'],
                                          'outputs': ['formal workspace 下 '
                                                      'self_evolution/autonomous_loops/work_runs 运行记录'],
                                          'mechanism': ['build_default_orchestrator 为 autonomous loop 绑定 '
                                                        'WorkRunStore。',
                                                        'WorkRun 落在正式 workspace 的自主运行目录，与监督 run 分开。'],
                                          'boundaries': ['这份状态不与 supervised worktree run 的记录或普通研究 '
                                                         'Workflow Ledger 混为一个权威。'],
                                          'relatedViews': ['supervised', 'storage']}}},
 'supervised': {'question': '监督进化怎样用同一 Judge 和冻结 rubric 比较候选，并等待最终审批？',
                'entry': '创建并启动监督 WorkRun；先有 baseline，不立即创建候选 worktree。',
                'outcome': '候选经 clean-room 复测、同 Judge 复评和配置审批后才合入。',
                'category': 'capability',
                'readingOrder': ['start', 'baseline', 'judge', 'candidate', 'rerun', 'decision', 'merge'],
                'relatedViews': ['self-evolution', 'gym', 'storage'],
                'nodes': {'start': {'label': '启动监督运行',
                                    'subtitle': 'start_supervised_worktree_run',
                                    'summary': '启动时先创建 run，不先创建候选 worktree',
                                    'role': 'entry',
                                    'ownerPath': 'core/web/services/supervised_worktree_evolution_service.py',
                                    'inputs': ['目标任务', '监督运行配置', '候选允许范围'],
                                    'outputs': ['监督 WorkRun 和初始阶段状态'],
                                    'mechanism': ['start_supervised_worktree_run 建立运行记录并进入 '
                                                  '_execute_flow。',
                                                  '候选 worktree 延后到基线、Judge 首评和 reflection 之后创建。'],
                                    'boundaries': ['开始时没有候选工作树；本流程不是普通 benchmark evaluator 的同义词。'],
                                    'relatedViews': ['self-evolution', 'gym', 'storage']},
                          'baseline': {'label': '评测原始基线',
                                       'subtitle': 'supervised_worktree_evolution_service._execute_flow '
                                                   '· baseline',
                                       'summary': '基线输出供 Judge 冻结 rubric 并首评',
                                       'role': 'process',
                                       'ownerPath': 'core/web/services/supervised_worktree_evolution_service.py',
                                       'inputs': ['监督任务定义', '原始工作区/基线代码', 'baseline cases'],
                                       'outputs': ['基线运行证据', '提交 Judge 的评分输入'],
                                       'mechanism': ['_execute_flow 先运行修改前 baseline。',
                                                     'Judge 随后冻结 rubric，并基于基线证据完成首评。'],
                                       'boundaries': ['baseline 是修改前参照；不能用候选结果替代，也不代表最终审批已通过。'],
                                       'relatedViews': ['gym', 'self-evolution']},
                          'candidate': {'label': '创建候选改动',
                                        'subtitle': '_execute_flow · reflection → worktree',
                                        'summary': '评测与反思之后才创建候选 worktree',
                                        'role': 'process',
                                        'ownerPath': 'core/web/services/supervised_worktree_evolution_service.py',
                                        'inputs': ['baseline 证据', '首轮 Judge 评分', 'reflection', '白名单文件范围'],
                                        'outputs': ['新建候选 worktree', '限定范围的候选改动'],
                                        'mechanism': ['reflection 使用基线证据和 Judge 首评分数形成改进方向。',
                                                      '之后才创建候选 worktree，并限制到允许修改的文件范围。'],
                                        'boundaries': ['候选必须随后做隔离复测；生成修改本身不表示质量通过或已集成。'],
                                        'relatedViews': ['self-evolution', 'storage']},
                          'rerun': {'label': '隔离复测候选',
                                    'subtitle': '_execute_flow · clean-room rerun',
                                    'summary': '使用隔离复测和 workspace audit 产生候选证据',
                                    'role': 'process',
                                    'ownerPath': 'core/web/services/supervised_worktree_evolution_service.py',
                                    'inputs': ['候选 worktree', '原定评测 cases', 'clean-room 环境'],
                                    'outputs': ['复测证据', 'workspace audit 结果'],
                                    'mechanism': ['候选在 clean-room 环境重新执行评测。',
                                                  'workspace audit 检查候选状态后才提交复评。'],
                                    'boundaries': ['不得以修改前基线结果或非隔离结果冒充候选复测。'],
                                    'relatedViews': ['gym', 'storage']},
                          'judge': {'label': '冻结标准复评',
                                    'subtitle': '_execute_flow · frozen rubric',
                                    'summary': '同一 Judge 与冻结标准降低评分漂移',
                                    'role': 'control',
                                    'ownerPath': 'core/web/services/supervised_worktree_evolution_service.py',
                                    'inputs': ['冻结 rubric', 'baseline 评分', '候选 clean-room 复测结果'],
                                    'outputs': ['候选复评分数和理由'],
                                    'mechanism': ['候选复评复用基线阶段的同一 Judge 与冻结 rubric。',
                                                  '分数供审批判断使用，不直接授权合入。'],
                                    'boundaries': ['评分是审批决策输入；达到阈值不自动代表批准或合入。'],
                                    'relatedViews': ['gym', 'self-evolution']},
                          'decision': {'label': '审批集成决策',
                                       'subtitle': '_execute_flow · approvalMode',
                                       'summary': '可由用户或独立审批 Agent 最终裁决',
                                       'role': 'control',
                                       'ownerPath': 'core/web/services/supervised_worktree_evolution_service.py',
                                       'inputs': ['基线与候选评分', '评测/审计证据', 'approvalMode'],
                                       'outputs': ['批准或拒绝集成的最终决定'],
                                       'mechanism': ['approvalMode 选择用户或独立审批 Agent 执行最终审批。',
                                                     '审批发生在候选复测和同标准复评之后。'],
                                       'boundaries': ['不能将批准主体固定假设为 human-only；分数和 reflection 都不能绕过此门。'],
                                       'relatedViews': ['self-evolution', 'gym']},
                          'merge': {'label': '合入候选改动',
                                    'subtitle': '_merge_candidate',
                                    'summary': '集成检查后合入并排队 runtime 激活',
                                    'role': 'process',
                                    'ownerPath': 'core/web/services/supervised_worktree_evolution_service.py',
                                    'inputs': ['已批准候选', '集成检查结果', '候选 worktree'],
                                    'outputs': ['集成提交', '排队的 runtime 激活请求'],
                                    'mechanism': ['_merge_candidate 只在审批通过和集成检查后执行。',
                                                  '合入完成后排队 runtime 激活；排队不证明已激活。'],
                                    'boundaries': ['候选评分通过不自动合入；排队激活不等同于已经完成运行时重启或验收。'],
                                    'relatedViews': ['self-evolution', 'storage']}}},
 'gym': {'question': '普通监督评测在什么条件下调用 Gym，评测通过后何时生效？',
         'entry': '普通 supervised_evolution evaluator 汇总 baseline/candidate case。',
         'outcome': '只有 PROMOTE 进入 Gym gate；proposal 后续应用与激活是独立步骤。',
         'category': 'capability',
         'readingOrder': ['eval', 'gate', 'episode', 'promotion'],
         'relatedViews': ['supervised', 'self-evolution', 'storage'],
         'nodes': {'eval': {'label': '汇总评测结果',
                            'subtitle': 'run_supervised_evolution_session',
                            'summary': '聚合 baseline/candidate cases 形成评估决定',
                            'role': 'process',
                            'ownerPath': 'core/evaluation/supervised_evolution.py',
                            'inputs': ['baseline cases', 'candidate cases', 'evaluator 配置'],
                            'outputs': ['改善/持平/退化等评估结论与指标'],
                            'mechanism': ['run_supervised_evolution_session 汇总 baseline 与 candidate '
                                          'cases。',
                                          '评估器产生结论和指标供后续分支判断。'],
                            'boundaries': ['普通评估器与监督 Worktree 的 clean-room/Judge 复评分链是不同执行器。'],
                            'relatedViews': ['supervised']},
                   'gate': {'label': '判定晋升入口',
                            'subtitle': '_apply_promotion_gate',
                            'summary': '仅 PROMOTE 结论进入 promotion gate',
                            'role': 'control',
                            'ownerPath': 'core/evaluation/supervised_evolution.py',
                            'inputs': ['监督评估结论', '候选与运行上下文'],
                            'outputs': ['需要 promotion gate 时的 Gym episode 请求'],
                            'mechanism': ['_apply_promotion_gate 只对 PROMOTE 结论进入 Gym。',
                                          '非 PROMOTE 结果不触发 promotion gate episode。'],
                            'boundaries': ['非 PROMOTE 结果不触发晋升评测；通过 gate 也不是显式 apply 或 activate。'],
                            'relatedViews': ['supervised']},
                   'episode': {'label': '执行 Gym 评测回合',
                               'subtitle': 'run_promotion_gate_episode',
                               'summary': 'promotion gate 调用 runner 执行 episode',
                               'role': 'process',
                               'ownerPath': 'core/gym/runner.py',
                               'inputs': ['promotion proposal / candidate', '评测环境与 gate 配置'],
                               'outputs': ['episode 结果和 proposal 评估状态'],
                               'mechanism': ['run_promotion_gate_episode 在 Gym runner 中执行一次 gate 评测。',
                                             'episode 返回评测证据，不直接修改 active runtime。'],
                               'boundaries': ['episode 的评测结果不会直接修改 active runtime。'],
                               'relatedViews': ['supervised', 'storage']},
                   'promotion': {'label': '应用并激活候选',
                                 'subtitle': 'apply_gym_promotion_proposal',
                                 'summary': 'apply 与 activate 是评测之外的独立操作',
                                 'role': 'control',
                                 'ownerPath': 'core/gym/promotion.py',
                                 'inputs': ['已评测的 Gym proposal', '显式 apply / activate 请求'],
                                 'outputs': ['应用或激活结果'],
                                 'mechanism': ['apply_gym_promotion_proposal 执行 proposal 的显式应用操作。',
                                               '运行时激活是独立步骤，评测通过不会自动应用或激活。'],
                                 'boundaries': ['PROMOTE 或 episode 通过不等于自动应用，更不等于运行时已激活。'],
                                 'relatedViews': ['supervised', 'self-evolution']}}},
 'companion': {'question': 'Companion 消息如何保持到达顺序，同时复用普通 Session transcript？',
               'entry': '人物专属 route 接收消息，经受信插件 admission 写入 Agent-scoped mailbox。',
               'outcome': 'Mailbox 按序领取并提交原生 Session；Journal/worker/SSE 仍是会话权威。',
               'category': 'capability',
               'readingOrder': ['route',
                                'facade',
                                'plugin',
                                'mailbox',
                                'dispatch',
                                'submitter',
                                'native'],
               'relatedViews': ['session', 'stream', 'storage'],
               'nodes': {'route': {'label': '接收人物消息',
                                   'subtitle': 'life_conversation_message',
                                   'summary': '接收 life_conversation_message 请求',
                                   'role': 'entry',
                                   'ownerPath': 'core/web/routes/virtual_human_life.py',
                                   'inputs': ['人物/Agent 标识', '对话 Session 与消息请求'],
                                   'outputs': ['交给人物 Web facade 的入队结果'],
                                   'mechanism': ['life_conversation_message 接收人物专属对话请求。',
                                                 'route 将消息转交 queue_virtual_human_conversation_message '
                                                 'facade。'],
                                   'boundaries': ['此入口只服务 Companion 身份；不改变普通 Agent Session 的 admission '
                                                  '语义。'],
                                   'relatedViews': ['session']},
                         'facade': {'label': '转交插件消息',
                                    'subtitle': 'queue_virtual_human_conversation_message',
                                    'summary': '委托 Agent-scoped 插件消息队列',
                                    'role': 'process',
                                    'ownerPath': 'core/web/services/virtual_human_life_service.py',
                                    'inputs': ['route 验证后的人物消息', '人物 Agent 上下文'],
                                    'outputs': ['插件 queue_conversation_message 调用结果'],
                                    'mechanism': ['queue_virtual_human_conversation_message 定位受信任的虚拟人插件。',
                                                  '请求保持在对应 Agent 的 Companion mailbox 范围内。'],
                                    'boundaries': ['人物 mailbox 隔离在插件适配面，不成为 Session transcript '
                                                   '或第二套普通消息实现。'],
                                    'relatedViews': ['session', 'tools']},
                         'plugin': {'label': '接纳待处理消息',
                                    'subtitle': 'queue_conversation_message',
                                    'summary': '人物 Agent 插件接收待处理对话命令',
                                    'role': 'entry',
                                    'ownerPath': 'core/agent_plugins/virtual_human_life/service.py',
                                    'inputs': ['人物 Agent ID', 'Session ID', '消息命令与来源'],
                                    'outputs': ['入队的 mailbox entry'],
                                    'mechanism': ['queue_conversation_message 在原生 Session 接收前接纳人物命令。',
                                                  '命令进入该 Agent 专属 mailbox 等待有序派发。'],
                                    'boundaries': ['只扩展 Companion 的入口顺序；不修改普通 Session '
                                                   'admission、Journal、worker 或投影。'],
                                    'relatedViews': ['session', 'tools']},
                         'mailbox': {'label': '保存消息租约',
                                     'subtitle': 'enqueue_mailbox_entry',
                                     'summary': 'Agent mailbox 管顺序与租约，不存 transcript',
                                     'role': 'store',
                                     'ownerPath': 'core/agent_plugins/virtual_human_life/mailbox.py',
                                     'inputs': ['人物消息命令', 'Agent-scoped queue state'],
                                     'outputs': ['conversation/mailbox.json 中的顺序和租约记录'],
                                     'mechanism': ['enqueue_mailbox_entry 将命令顺序和租约写入 '
                                                   'conversation/mailbox.json。',
                                                   '文件不保存第二份 transcript。'],
                                     'boundaries': ['mailbox 保存到达顺序和投递状态，不保存第二套 transcript 或取代原生 Session '
                                                    'Journal。'],
                                     'relatedViews': ['session', 'storage']},
                         'dispatch': {'label': '按序派发消息',
                                      'subtitle': 'dispatch_conversation_mailbox_once',
                                      'summary': 'FIFO 领取 lease 后提交原生消息',
                                      'role': 'process',
                                      'ownerPath': 'core/agent_plugins/virtual_human_life/service.py',
                                      'inputs': ['Agent mailbox', '待处理 entry', '当前 lease 状态'],
                                      'outputs': ['交给 submitter 的一条原生提交请求'],
                                      'mechanism': ['dispatch_conversation_mailbox_once 按 FIFO 领取待处理 '
                                                    'entry 的 lease。',
                                                    '成功领取后调用 conversation submitter 并推进投递状态。'],
                                      'boundaries': ['顺序与重试职责止于 mailbox/dispatcher；回合生命周期仍由 Session 处理。'],
                                      'relatedViews': ['session', 'stream', 'storage']},
                         'submitter': {'label': '提交原生会话',
                                       'subtitle': '_default_conversation_submitter',
                                       'summary': '默认适配器调用轻量 Session submit 接口',
                                       'role': 'external',
                                       'ownerPath': 'core/web/services/virtual_human_life_service.py',
                                       'inputs': ['已领取的 mailbox 消息', '目标 Agent 与 Session 上下文'],
                                       'outputs': ['submit_session_message_lightweight 的提交结果'],
                                       'mechanism': ['_default_conversation_submitter 将人物命令映射到原生 Session '
                                                     '请求。',
                                                     '适配器调用 submit_session_message_lightweight '
                                                     '跨入原生接收边界。'],
                                       'boundaries': ['在原生接收边界前做适配；不新建人物专属 worker 或 transcript。'],
                                       'relatedViews': ['session', 'stream']},
                         'native': {'label': '执行原生会话',
                                    'subtitle': 'submit_session_message_lightweight',
                                    'summary': '复用 Session worker、Journal 与 SSE 执行链',
                                    'role': 'external',
                                    'ownerPath': 'core/web/services/session/submit.py',
                                    'inputs': ['Session ID', 'Agent ID', '提交的用户消息'],
                                    'outputs': ['原生 turn、Journal 事件、worker 执行与 SSE 输出'],
                                    'mechanism': ['submit_session_message_lightweight 进入普通 Session '
                                                  'submit/scheduler 链。',
                                                  '后续 worker、Journal 与 SSE 拥有 turn、transcript 和实时输出。'],
                                    'boundaries': ['原生 Session Journal、worker 和 SSE 是 Turn、transcript '
                                                   '与实时输出权威。'],
                                    'relatedViews': ['session', 'stream', 'storage']}}},
 'finance': {'question': '金融助手首次打开时怎样建立能力范围，哪些金融能力当前实际可用？',
             'entry': '列表为空且 entry plan=create 时，FinanceRoute 自动调用 create API。',
             'outcome': '助手复用 Agent、scoped knowledge 和普通 Session；能力状态明确标记未接通项。',
             'category': 'capability',
             'readingOrder': ['ui', 'route', 'setup', 'agent', 'kb', 'session', 'projection'],
             'relatedViews': ['session', 'knowledge', 'tools', 'storage'],
             'nodes': {'ui': {'label': '初始化金融助手',
                              'subtitle': 'FinanceRoute',
                              'summary': '空列表且计划为 create 时自动触发创建',
                              'role': 'entry',
                              'ownerPath': 'web/src/routes/FinanceRoute.tsx',
                              'inputs': ['助手列表投影', '页面 entry plan'],
                              'outputs': ['读取列表，或调用 createFinancialAssistant'],
                              'mechanism': ['FinanceRoute 读取助手列表投影和 entry plan。',
                                            '空列表且 plan=create 时自动调用 createFinancialAssistant。'],
                              'boundaries': ['这是初始化流程，不代表行情、交易或私有账本等产品能力已接通。'],
                              'relatedViews': ['session', 'knowledge']},
                       'route': {'label': '处理助手请求',
                                 'subtitle': 'financial_assistant_create',
                                 'summary': 'list 是纯读投影，create 是显式 POST setup',
                                 'role': 'entry',
                                 'ownerPath': 'core/web/routes/financial_assistant.py',
                                 'inputs': ['GET 列表查询', 'POST create 请求'],
                                 'outputs': ['当前助手列表投影', '创建/setup 服务结果'],
                                 'mechanism': ['GET list 只返回状态投影。',
                                               'POST create 委托 setup service；list 不暗中修复资源。'],
                                 'boundaries': ['GET 不暗中补建或修复资源；自动创建由前端显式发出的 POST 请求触发。'],
                                 'relatedViews': ['session', 'knowledge']},
                       'setup': {'label': '建立助手资源',
                                 'subtitle': 'create_financial_assistant',
                                 'summary': 'pending setup 只由 create service 续作',
                                 'role': 'process',
                                 'ownerPath': 'core/web/services/financial_assistant_service.py',
                                 'inputs': ['create request', '已有 Agent / KB / Session setup 状态'],
                                 'outputs': ['完成或续作后的助手资源及状态投影'],
                                 'mechanism': ['create_financial_assistant 协调 Agent、知识库和 Session 初始化。',
                                               '只续作该 service 自己记录的 pending setup。'],
                                 'boundaries': ['不通过 list 读取路径触发隐式修复；幂等不等于任意既有资源自动接管。'],
                                 'relatedViews': ['session', 'knowledge', 'storage']},
                       'agent': {'label': '配置金融 Agent',
                                 'subtitle': 'create_financial_assistant · Agent Directory',
                                 'summary': '创建 general Agent 并设置金融角色与工具 profile',
                                 'role': 'external',
                                 'ownerPath': 'core/web/services/financial_assistant_service.py',
                                 'inputs': ['金融助手标识与初始化配置'],
                                 'outputs': ['general Agent 档案',
                                             'financial_advisor 角色',
                                             'financial_assistant_v1 tool profile'],
                                 'mechanism': ['setup 调用 Agent Directory 建立 general Agent 档案。',
                                               '档案设置 financial_advisor 角色和 financial_assistant_v1 工具 '
                                               'profile。'],
                                 'boundaries': ['Agent profile 描述可用工具边界；不等于工具背后的行情或交易服务真实已连接。'],
                                 'relatedViews': ['tools', 'session']},
                       'kb': {'label': '配置专属知识库',
                              'subtitle': 'create_financial_assistant · scoped knowledge',
                              'summary': '创建 per-Agent 知识库并设置读取策略',
                              'role': 'external',
                              'ownerPath': 'core/web/services/financial_assistant_service.py',
                              'inputs': ['Agent ID', '金融助手知识库初始化配置'],
                              'outputs': ['Agent scoped knowledge base 与 read policy'],
                              'mechanism': ['setup 创建 per-Agent knowledge base 并设置读取策略。',
                                            '工具面覆盖研究入口，新闻委派当前仍为 disabled。'],
                              'boundaries': ['知识库范围隔离不等于外部新闻委派已启用；来源访问仍受现有能力状态限制。'],
                              'relatedViews': ['knowledge', 'knowledge-write', 'tools']},
                       'session': {'label': '创建金融会话',
                                   'subtitle': 'ensure_agent_direct_session',
                                   'summary': '建立 direct Session 后走普通 Agent chat',
                                   'role': 'external',
                                   'ownerPath': 'core/web/services/financial_assistant_service.py',
                                   'inputs': ['金融 Agent ID', '工作区与 direct session 配置'],
                                   'outputs': ['原生 Agent direct Session 标识'],
                                   'mechanism': ['ensure_agent_direct_session 为金融 Agent 创建原生 direct '
                                                 'Session。',
                                                 '页面之后复用普通 Agent chat，不另建 transcript。'],
                                   'boundaries': ['不创建金融专属 transcript、worker 或消息生命周期。'],
                                   'relatedViews': ['session', 'stream', 'storage']},
                       'projection': {'label': '投影能力状态',
                                      'subtitle': '_project',
                                      'summary': '明确无交易、行情未连接、新闻关闭、私有账本未实现',
                                      'role': 'control',
                                      'ownerPath': 'core/web/services/financial_assistant_service.py',
                                      'inputs': ['金融助手配置和资源状态'],
                                      'outputs': ['tradingEnabled=false',
                                                  'market data not_connected',
                                                  'news delegation disabled',
                                                  'private ledger not_implemented'],
                                      'mechanism': ['_project 从后端 setup 与能力状态构造 UI 投影。',
                                                    '明确标记 trading=false、market data 未连接、news delegation '
                                                    '关闭、private ledger 未实现。'],
                                      'boundaries': ['不能从页面存在或工具 profile 名称推断交易、实时行情、新闻委派或私有账本已可用。'],
                                      'relatedViews': ['session', 'knowledge', 'tools']}}},
 'storage': {'question': '项目路径、Session transcript、会话目录和研究账本分别由谁负责？',
             'entry': '先按 project/instance 解析存储根，再由各业务模块拥有自己的数据权威。',
             'outcome': '目录投影、Operator 配置、Session Journal 与研究 Ledger 分离，不能互相代替。',
             'category': 'data',
             'readingOrder': ['paths', 'workspace', 'journal', 'directory', 'bridge', 'config', 'ledger'],
             'relatedViews': ['session', 'research', 'knowledge-write', 'teams'],
             'nodes': {'paths': {'label': '解析项目路径',
                                 'subtitle': 'resolve_project_storage_paths',
                                 'summary': '分清 project、instance 与运行数据路径',
                                 'role': 'process',
                                 'ownerPath': 'vibelution_storage.py',
                                 'inputs': ['project_root',
                                            'project identity',
                                            'instance identity',
                                            '存储根环境配置'],
                                 'outputs': ['ProjectStoragePaths 中的 '
                                             'projects/project/instance/data/runtime/logs/memory/cache '
                                             '路径'],
                                 'mechanism': ['resolve_project_storage_paths 结合 project 和 instance '
                                               'identity 计算目录。',
                                               '返回 data、runtime、logs、memory、cache 等独立路径。'],
                                 'boundaries': ['这是路径解析模型，不是统一业务数据库，也不表示所有内容都写进同一目录。'],
                                 'relatedViews': ['session', 'research', 'knowledge-write', 'teams']},
                       'workspace': {'label': '定位实例工作区',
                                     'subtitle': 'formal_workspace_path',
                                     'summary': '正式 workspace 从实例 data 派生，沙箱路径单独解析',
                                     'role': 'process',
                                     'ownerPath': 'core/infrastructure/developer_sandbox.py',
                                     'inputs': ['project root', '实例 identity', '可选 sandbox 上下文'],
                                     'outputs': ['formal workspace path 或受限 sandbox path'],
                                     'mechanism': ['formal_workspace_path 从项目身份与正式 workspace 根定位路径。',
                                                   '存在明确 sandbox 上下文时单独解析隔离路径。'],
                                     'boundaries': ['调用必须依据实际 project/instance 路径；不把 workspace 与 '
                                                    'Journal、知识库、Operator config 混为一处。'],
                                     'relatedViews': ['session', 'research', 'knowledge-write']},
                       'journal': {'label': '追加 Turn 事件',
                                   'subtitle': 'append_turn_event',
                                   'summary': 'Turn 事件追加到 session token 专属 Journal',
                                   'role': 'store',
                                   'ownerPath': 'core/chat/turn_journal.py',
                                   'inputs': ['project root',
                                              'session ID',
                                              'turn ID',
                                              'event type/status/payload'],
                                   'outputs': ['sessions/<token>/turn_journal.jsonl 的追加事件'],
                                   'mechanism': ['append_turn_event 追加到 '
                                                 'sessions/<token>/turn_journal.jsonl。',
                                                 '终态事件保护避免已结束 turn 被非法覆盖。'],
                                   'boundaries': ['这是 Session transcript 事件权威；会话目录 SQLite '
                                                  '是查询/控制投影，不能代替它。'],
                                   'relatedViews': ['session', 'stream', 'companion']},
                       'directory': {'label': '存取会话目录',
                                     'subtitle': 'ConversationStore',
                                     'summary': 'ConversationStore 是目录与控制面存取层',
                                     'role': 'store',
                                     'ownerPath': 'core/chat/conversation_store/store.py',
                                     'inputs': ['会话目录项', '状态/预览/更新时间等索引字段'],
                                     'outputs': ['可查询的 ConversationStore SQLite 记录'],
                                     'mechanism': ['ConversationStore 组合数据库、repository 与 writer。',
                                                   '它保存目录和控制元数据，不负责完整 transcript。'],
                                     'boundaries': ['不保存或取代完整的 Session transcript；消息正文权威仍是 Turn '
                                                    'Journal。'],
                                     'relatedViews': ['session', 'stream']},
                       'bridge': {'label': '同步目录投影',
                                  'subtitle': 'sync_conversation_record',
                                  'summary': '同步目录字段，不把目录写入当作 transcript',
                                  'role': 'process',
                                  'ownerPath': 'core/web/services/session/directory_bridge.py',
                                  'inputs': ['conversation record',
                                             'last preview/status',
                                             'recency 与等待选项'],
                                  'outputs': ['ConversationStore 会话目录 upsert'],
                                  'mechanism': ['sync_conversation_record 将 conversation record 转成目录 '
                                                'upsert。',
                                                '列表预览、状态和 recency 字段进入 ConversationStore。'],
                                  'boundaries': ['目录同步失败不意味着 Journal transcript 被改写；目录不得成为第二个 transcript '
                                                 '写入者。'],
                                  'relatedViews': ['session', 'stream']},
                       'config': {'label': '解析配置路径',
                                  'subtitle': 'resolve_config_path',
                                  'summary': '配置路径按显式值、环境变量与默认目录解析',
                                  'role': 'control',
                                  'ownerPath': 'config/paths.py',
                                  'inputs': ['显式 config_path',
                                             'VIBELUTION_CONFIG_PATH / CONFIG_HOME 环境覆盖',
                                             '默认配置目录'],
                                  'outputs': ['解析后的 Operator config.toml 路径'],
                                  'mechanism': ['resolve_config_path 首先采用调用方提供的 config_path。',
                                                '否则检查环境覆盖，再落到解析后的默认 config home。'],
                                  'boundaries': ['仓库中的 config/ 是配置代码库；不可把仓库根 config.toml 或 config/ '
                                                 '误当成活跃用户配置值。'],
                                  'relatedViews': ['session', 'research']},
                       'ledger': {'label': '保存研究运行账本',
                                  'subtitle': 'WorkflowLedgerStore',
                                  'summary': '研究业务使用专门单写账本与只读查询池',
                                  'role': 'store',
                                  'ownerPath': 'core/research/workflow/ledger/store.py',
                                  'inputs': ['run/command/attempt/outbox/event 变更'],
                                  'outputs': ['workflow-ledger.sqlite 中提交的研究业务状态'],
                                  'mechanism': ['WorkflowLedgerStore 通过单写入器提交研究业务变更。',
                                                '池化只读查询读取已提交状态，不承担 Session transcript。'],
                                  'boundaries': ['只拥有研究 workflow 业务记录；不是普通 Session transcript、会话目录或 '
                                                 'Operator 配置数据库。'],
                                  'relatedViews': ['research', 'session']}}}}
