"""Interactive reading details for the reviewed runtime architecture views.

This module is intentionally data-only. Source references and node identifiers are
owned by curated.py and flows.py; these details explain how to read those nodes.
"""

DETAILS = {
    'startup': {
        'question': '桌面控制指令怎样经 IPC 启动后端，并从健康响应走到业务路由就绪？',
        'entry': '从 Launcher renderer 的桥接检测开始，沿 preload、Electron main、控制队列、后端进程和 FastAPI 启动阶段阅读。',
        'outcome': '区分桌面控制、子进程启动、health 可用和完整业务路由就绪。',
        'category': 'runtime',
        'readingOrder': ['ui', 'ipc', 'main', 'queue', 'process', 'health', 'routes'],
        'relatedViews': ['http', 'session'],
        'nodes': {
            'ui': {
                'label': '识别桌面 IPC 能力',
                'subtitle': 'hasLauncherIpcBridge',
                'summary': '确认当前窗口可否调用受限桌面桥',
                'role': 'entry',
                'ownerPath': 'web/src/api/launcher.ts',
                'inputs': ['Launcher 窗口中的生命周期操作', 'preload 暴露的 launcherInvoke 函数'],
                'outputs': ['带 schemaVersion 和控制路径的 IPC 请求'],
                'mechanism': ['hasLauncherIpcBridge 检查 window 桥接对象和函数。', '可用桥接时调用 launcherInvoke；部分只读 API 仍可走 HTTP。'],
                'boundaries': ['Renderer 只发出受限命令，不创建或管理 Python 进程。', 'Launcher IPC 和普通领域 fetchJson 属于不同传输路径。'],
                'relatedViews': ['http'],
            },
            'ipc': {
                'label': '转发 Launcher 操作',
                'subtitle': 'launcherInvoke',
                'summary': '用 context-isolated preload 代理命令',
                'role': 'process',
                'ownerPath': 'desktop/electron/src/preload.ts',
                'inputs': ['renderer 的 launcherInvoke 参数'],
                'outputs': ['IPC_CHANNELS.launcherInvoke 的 invoke 请求'],
                'mechanism': ['preload 通过 contextBridge 暴露受限 API。', 'launcherInvoke 使用 ipcRenderer.invoke 等待主进程结果。'],
                'boundaries': ['只向获准的 Launcher control window 暴露完整 launcherInvoke。', 'Preload 不解析 lifecycle 命令的业务语义。'],
                'relatedViews': ['http'],
            },
            'main': {
                'label': '校验并派发桌面命令',
                'subtitle': 'ipcMain.handle(IPC_CHANNELS.launcherInvoke)',
                'summary': '验证 IPC 来源后交给 Launcher host',
                'role': 'control',
                'ownerPath': 'desktop/electron/src/main.ts',
                'inputs': ['IPC sender 与 launcherInvoke payload'],
                'outputs': ['Launcher host 的操作结果'],
                'mechanism': ['ipcMain.handle 注册 launcherInvoke handler。', 'assertTrustedIpcSender 校验调用方，再调用 resolveLauncherIpcHost().invoke。'],
                'boundaries': ['IPC 信任校验在进入 lifecycle 命令处理前执行。', '主进程 handler 负责边界与派发，队列负责生命周期串行控制。'],
                'relatedViews': [],
            },
            'queue': {
                'label': '串行化生命周期操作',
                'subtitle': 'createMainLineCommandQueue',
                'summary': '合并兼容命令并控制并发与关闭退避',
                'role': 'control',
                'ownerPath': 'desktop/electron/src/lifecycle/mainLine/commandQueue.ts',
                'inputs': ['start、stop、restart 等 lifecycle intent', '调用者提供的执行与持久化回调'],
                'outputs': ['排队或合并后的命令执行次序', '可观察的 intent 状态更新'],
                'mechanism': ['createMainLineCommandQueue 管理主生命周期命令的队列状态。', 'workbenchLifecycle 将命令 submit 到共享队列后执行对应操作。'],
                'boundaries': ['队列约束的是 Electron 主进程的生命周期控制命令。', '队列完成不代表 FastAPI routesReady 或前端业务可用。'],
                'relatedViews': ['http'],
            },
            'process': {
                'label': '启动工作台后端',
                'subtitle': 'spawnWorkbenchBackend',
                'summary': '按项目实例配置启动 Python Web 进程',
                'role': 'related',
                'ownerPath': 'desktop/electron/src/process/workbenchBackend.ts',
                'inputs': ['workspaceRoot 与脚本根目录', 'Python 可执行文件、端口及实例 dataHome'],
                'outputs': ['受 Electron 跟踪的后端子进程', 'health 探测所需的实例身份信息'],
                'mechanism': ['spawnWorkbenchBackend 组装进程参数和实例环境。', '生命周期管理器追踪子进程并用 health 响应确认后端启动阶段。'],
                'boundaries': ['进程是独立 Python runtime，不是 Electron 内嵌服务。', 'health 成功只说明早期服务可响应，不说明业务路由已挂载。'],
                'relatedViews': ['http'],
            },
            'health': {
                'label': '开放早期健康入口',
                'subtitle': 'create_app',
                'summary': '先建立中间件和 health 控制端点',
                'role': 'process',
                'ownerPath': 'core/web/app.py',
                'inputs': ['进程内的 workspace 与 serving metadata'],
                'outputs': ['/api/health', '/api/control-token', '分阶段 route readiness 状态'],
                'mechanism': ['create_app 构造 FastAPI 和 control、CORS、runtime-scene 等 middleware。', '阶段一先保留 health 与 control-token；路由 bootstrap 由 lifespan/请求阶段完成。'],
                'boundaries': ['routesReady=false 时 health 仍可返回 status=ok。', '运行服务固定其启动时读取的 frontend/backend serving identity。'],
                'relatedViews': ['http'],
            },
            'routes': {
                'label': '挂载业务 API 与 SPA',
                'subtitle': 'ensure_web_routes_registered',
                'summary': '装载业务路由并固定发布的前端目录',
                'role': 'process',
                'ownerPath': 'core/web/route_bootstrap.py',
                'inputs': ['FastAPI app', '已解析的 API route modules 与前端发布目录'],
                'outputs': ['带 /api 前缀的业务路由', 'SPA index 与 fallback route', 'routesReady 状态'],
                'mechanism': ['ensure_web_routes_registered 幂等导入并挂载业务 routers。', 'register_spa_routes 在 API routers 后挂载 index/fallback，再由 _mark_routes_ready 发布就绪状态。'],
                'boundaries': ['只在 API routers 和 SPA route 注册后标记 routesReady。', '已 pin 的 release 不会静默切换到新的 mutable frontend dist。'],
                'relatedViews': ['http'],
            },
        },
    },
    'http': {
        'question': '页面的领域请求如何经公共 HTTP helper、控制校验和 FastAPI 路由注册到达业务入口？',
        'entry': '沿页面路由、fetchJson/fetchWithControl、中间件和 route registry 阅读；Launcher lifecycle IPC 是单独控制路径。',
        'outcome': '理解浏览器页面、HTTP transport、安全校验、API mount 和 lifespan 的职责分界。',
        'category': 'runtime',
        'readingOrder': ['router', 'transport', 'guard', 'bootstrap', 'routes', 'lifecycle'],
        'relatedViews': ['startup', 'session', 'stream'],
        'nodes': {
            'router': {
                'label': '解析前端页面',
                'subtitle': 'createBrowserRouter',
                'summary': '把浏览器 URL 映射到工作台页面',
                'role': 'entry',
                'ownerPath': 'web/src/app/router.tsx',
                'inputs': ['浏览器 pathname 与 query', '工作台 route definitions'],
                'outputs': ['匹配的页面组件及其 route 参数'],
                'mechanism': ['createBrowserRouter 集中声明前端路由。', '页面可 lazy 加载，领域组件通过对应 API 模块发起后端请求。'],
                'boundaries': ['前端 route 匹配不是 FastAPI route 注册。', 'Launcher IPC 命令不经过通用页面 HTTP transport。'],
                'relatedViews': ['startup', 'session'],
            },
            'transport': {
                'label': '发送受控 HTTP 请求',
                'subtitle': 'fetchJson / fetchWithControl',
                'summary': '统一附加控制凭据并处理响应错误',
                'role': 'process',
                'ownerPath': 'web/src/api/client.ts',
                'inputs': ['领域 API path 与 RequestInit', '同源 API 所需的 control token'],
                'outputs': ['HTTP Response 或抛出的规范化请求错误'],
                'mechanism': ['fetchJson 通过 fetchWithControl 发请求并解析 JSON。', 'fetchWithControl 按请求来源获取控制 token、设置凭据，并对失效 token 做一次有限重试。'],
                'boundaries': ['SSE 等流式接口不会由 fetchJson 当作 JSON 消费。', '控制 token 的来源与信任范围由服务端 guard 决定。'],
                'relatedViews': ['startup', 'session', 'stream'],
            },
            'guard': {
                'label': '校验控制来源与令牌',
                'subtitle': 'WebControlGuardMiddleware',
                'summary': '拦截不可信的 API 控制请求',
                'role': 'control',
                'ownerPath': 'core/web/control.py',
                'inputs': ['HTTP method、path、origin/host 与 control-token header'],
                'outputs': ['校验拒绝响应或交给下游的 Request'],
                'mechanism': ['dispatch 只对受保护的 /api 路径执行控制校验。', '变更请求校验完整控制请求；source-only GET 和预检请求使用较窄路径。'],
                'boundaries': ['只校验控制访问边界，不执行业务授权和领域逻辑。', 'OPTIONS 预检请求不走同一 token 拒绝分支。'],
                'relatedViews': ['startup'],
            },
            'bootstrap': {
                'label': '装载 Web 路由模块',
                'subtitle': 'import_web_route_modules',
                'summary': '在早期 health 之后导入并准备路由',
                'role': 'control',
                'ownerPath': 'core/web/router_registry.py',
                'inputs': ['稳定顺序的 route module registry', '当前 FastAPI app'],
                'outputs': ['已导入的 router modules', '供挂载阶段消费的列表'],
                'mechanism': ['import_web_route_modules 按 registry 导入模块并记录加载时序。', 'route_bootstrap 将路由装载与早期 health readiness 分阶段处理。'],
                'boundaries': ['这是服务启动/路由准备工作，不是每个 HTTP 请求的业务处理。', '模块目录或文件存在不代表模块已经注册到运行 app。'],
                'relatedViews': ['startup'],
            },
            'routes': {
                'label': '分发领域 API',
                'subtitle': 'register_web_routers_from_modules',
                'summary': '统一挂载业务 router 并添加 API 前缀',
                'role': 'process',
                'ownerPath': 'core/web/router_registry.py',
                'inputs': ['已导入且提供 router 的模块'],
                'outputs': ['挂载到 app 的 /api 路由表'],
                'mechanism': ['register_web_routers_from_modules 逐个 include_router。', '注册时添加 /api 前缀；模块内装饰器定义相对 path。'],
                'boundaries': ['具体 route 只负责 HTTP 适配，业务 owner 仍由领域服务决定。', 'API routers 完整挂载后才继续 SPA fallback 注册。'],
                'relatedViews': ['session', 'stream'],
            },
            'lifecycle': {
                'label': '管理服务启动与退出',
                'subtitle': 'web_workbench_lifespan',
                'summary': '协调启动恢复任务和有界关闭',
                'role': 'control',
                'ownerPath': 'core/web/lifecycle.py',
                'inputs': ['FastAPI startup/shutdown 生命周期事件', '后台 startup jobs 与恢复任务'],
                'outputs': ['后台 startup 任务状态', '进入服务或关闭阶段的协调结果'],
                'mechanism': ['web_workbench_lifespan 启动有界后台初始化与恢复工作。', '退出时按超时预算等待或收束后台任务，并执行关闭标记。'],
                'boundaries': ['lifespan 是进程级协调，不是页面到业务 route 的同步调用。', '早期 health 可在部分路由 warmup 继续进行时先响应。'],
                'relatedViews': ['startup', 'session'],
            },
        },
    },
    'session': {
        'question': '一条 Session 消息怎样被接收、调度、组装上下文、执行并写入回合记录？',
        'entry': '从 session_submit_message 沿 submit、Scheduler callback、worker、build_agent_context、turn runner 读到最终 Journal 事件。',
        'outcome': '分清 202 受理、实际执行、最终持久化，以及上下文工具检索之间的边界。',
        'category': 'runtime',
        'readingOrder': ['http', 'submit', 'schedule', 'scheduler', 'worker', 'context', 'turn', 'persist', 'journal'],
        'relatedViews': ['stream', 'llm', 'tools', 'knowledge'],
        'nodes': {
            'http': {
                'label': '接收会话消息',
                'subtitle': 'session_submit_message',
                'summary': '受理消息并选择轻量或普通响应',
                'role': 'entry',
                'ownerPath': 'core/web/routes/sessions.py',
                'inputs': ['session_id 与消息 payload', 'Prefer: respond-async 等请求头'],
                'outputs': ['202 accepted 回合响应', '交给 Session submit 的消息字段'],
                'mechanism': ['session_submit_message 按 Prefer 头选择轻量 submit wrapper 或完整响应分支。', '路由生成/保留 client submission ID 并传入附件、references 与 turn options。'],
                'boundaries': ['HTTP 受理成功不代表 Agent 回合已完成。', '路由不运行模型或工具。'],
                'relatedViews': ['http', 'stream'],
            },
            'submit': {
                'label': '登记回合输入',
                'subtitle': 'submit_session_message',
                'summary': '验证输入并写入回合启动事件',
                'role': 'process',
                'ownerPath': 'core/web/services/session/submit.py',
                'inputs': ['session 与 user content', 'attachment/reference 和执行选项'],
                'outputs': ['turn context 与 turn ID', '初始 Journal markers/user_message'],
                'mechanism': ['按 session admission 与幂等信息验证此次提交。', '建立执行 context，追加初始事件后调用 schedule adapter。'],
                'boundaries': ['此阶段登记回合并安排执行，不同步等待完整模型输出。', 'Session directory 控制状态和 Journal transcript 各有职责。'],
                'relatedViews': ['stream', 'storage'],
            },
            'schedule': {
                'label': '提交执行调度',
                'subtitle': '_schedule_session_turn',
                'summary': '把回合 context 交给会话调度器',
                'role': 'process',
                'ownerPath': 'core/web/services/session/schedule.py',
                'inputs': ['已受理的 turn context', 'submit/release callbacks'],
                'outputs': ['运行中或排队的调度任务'],
                'mechanism': ['_schedule_session_turn 调全局 SessionTurnScheduler.schedule。', '调度器回调最终经 Session executor 包装函数进入 worker。'],
                'boundaries': ['调度器负责并发槽与排队，不作为会话历史权威。', '后台 executor 接收任务不等于任务已经开始执行。'],
                'relatedViews': ['storage'],
            },
            'scheduler': {
                'label': '管理会话执行槽',
                'subtitle': 'SessionTurnScheduler',
                'summary': '保持会话串行并限制同一 Agent 并发',
                'role': 'control',
                'ownerPath': 'core/web/services/session_turn_scheduler.py',
                'inputs': ['session_id/agent_id 与 turn context', '调度 submit 和 release callbacks'],
                'outputs': ['按序执行的 callback', 'queued/dequeued 状态与 queue position'],
                'mechanism': ['schedule 将任务按 session key 纳入队列。', '激活时保持同一 session 排序，并受 per-Agent active session 上限约束。'],
                'boundaries': ['scheduler 队列是运行期调度状态，不是持久 transcript。', '外部保留、取消和释放可改变下一项获准执行时机。'],
                'relatedViews': ['startup', 'storage'],
            },
            'worker': {
                'label': '运行 Agent 回合',
                'subtitle': '_run_session_turn_impl',
                'summary': '读取 Agent 快照并驱动单轮执行',
                'role': 'process',
                'ownerPath': 'core/web/services/session/worker.py',
                'inputs': ['已获执行槽的 turn context', 'Agent identity、Session history 与控制状态'],
                'outputs': ['本轮 Agent 结果或失败状态', '终态持久化与槽释放'],
                'mechanism': ['_run_session_turn_impl 读取 Agent 配置并生成运行绑定，再通过 _acquire_chat_agent_for_session 获取本回合 Agent runtime lease。', 'worker 组装上下文并调用 turn runner；结束时持久化，在 finally 释放 runtime lease 并收束调度槽。'],
                'boundaries': ['异常路径记录失败；runtime lease 清理异常也不会跳过 worker 收束。', 'worker 是 Session 调度任务的执行器，不是模型协议实现。'],
                'relatedViews': ['llm', 'stream', 'tools'],
            },
            'turn': {
                'label': '编排单轮交互',
                'subtitle': 'run_existing_agent_single_turn',
                'summary': '把会话消息交给现有 Agent runtime 执行',
                'role': 'process',
                'ownerPath': 'core/orchestration/turn_runner.py',
                'inputs': ['AgentRuntime 实例与单轮消息', '回合历史、stop/control 与 output options'],
                'outputs': ['Agent turn result', '含规范化模型/工具事件的回合结果'],
                'mechanism': ['prepare_agent_turn 整理输入、history 与本轮运行 metadata。', 'run_existing_agent_single_turn 驱动既有 Agent 的 ReAct 多轮循环。'],
                'boundaries': ['turn runner 是回合适配与驱动层，不直接选择具体 Provider wire。', '工具循环在 AgentRuntime/ToolLifecycleBridge 中完成。'],
                'relatedViews': ['llm', 'tools'],
            },
            'persist': {
                'label': '保存最终回合结果',
                'subtitle': '_persist_session_turn_result',
                'summary': '写入最终 assistant 内容和终态信息',
                'role': 'store',
                'ownerPath': 'core/web/services/session/persist.py',
                'inputs': ['worker 的成功/失败结果', 'turn/session identity 与终态 metadata'],
                'outputs': ['最终 assistant message 与 terminal Journal event', '更新后的 Session 状态投影'],
                'mechanism': ['_persist_session_turn_result 收束本轮 assistant/result metadata。', '成功和异常路径分别写相应终态事实，再由 worker 发布最新 Session detail。'],
                'boundaries': ['最终结果持久化与 SSE delta 是不同动作。', '持久化失败不能解释为模型请求已经成功结束。'],
                'relatedViews': ['stream', 'storage'],
            },
            'journal': {
                'label': '维护回合事件账本',
                'subtitle': 'append_turn_event',
                'summary': '追加 transcript、工具与生命周期事件',
                'role': 'store',
                'ownerPath': 'core/chat/turn_journal.py',
                'inputs': ['session_id、turn_id 与 event payload', '事件类型、source 与关联 call IDs'],
                'outputs': ['带 sequence 的追加事件记录', '可重放的回合 transcript/tool facts'],
                'mechanism': ['append_turn_event 执行事件转换校验并追加 JSONL。', '为事件分配 sequence，并维护终态 watermark/缓存和并发写锁。'],
                'boundaries': ['Journal 是 transcript 与工具事件来源；SQLite 会话目录不代替它。', '终态后的写入按 transition guard 拒绝或隔离。'],
                'relatedViews': ['stream', 'storage'],
            },
            'context': {
                'label': '组装当前回合上下文',
                'subtitle': 'build_agent_context',
                'summary': '把身份、策略、记忆候选和历史装入回合',
                'role': 'process',
                'ownerPath': 'core/orchestration/context_engine.py',
                'inputs': ['AgentDirectory snapshot 与 memoryPolicy', 'Session history、会话上下文和执行 options'],
                'outputs': ['Agent context packet 与 context blocks', '供 worker 组装单轮调用的记忆/身份材料'],
                'mechanism': ['build_agent_context 读取 AgentDirectory、策略允许的记忆、episodic events、group context 与 inbox。', 'Session worker 将 packet 的 context segments 与另行装配的 history 合并，再传入 Agent 单轮调用。'],
                'boundaries': ['build_agent_context 产出上下文数据，不直接调用 turn runner。', 'Team Knowledge unified search 是独立工具路径，不应误画成每回合自动 RAG 注入。'],
                'relatedViews': ['llm', 'tools', 'knowledge'],
            },
        },
    },
    'stream': {
        'question': 'assistant/tool 增量怎样进入 Journal 和 SSE，最终结果又怎样与直播流分开保存？',
        'entry': '沿 Session UI stream capture、delta publisher、异步 subscriber 和 /events SSE endpoint 阅读，再对照结果持久化。',
        'outcome': '把实时投影、恢复游标和持久 transcript 区分开。',
        'category': 'runtime',
        'readingOrder': ['capture', 'journal', 'publish', 'subscribe', 'sse', 'persist'],
        'relatedViews': ['session', 'storage'],
        'nodes': {
            'capture': {
                'label': '捕获回合增量',
                'subtitle': '_capture_session_ui_stream',
                'summary': '接收 assistant/tool 事件并记录实时输出',
                'role': 'process',
                'ownerPath': 'core/web/services/session/stream_capture.py',
                'inputs': ['Agent/UI stream callbacks', 'canonical assistant 与 tool lifecycle 事件'],
                'outputs': ['Journal capture events', '当前 Session 的 live output/delta'],
                'mechanism': ['_capture_session_ui_stream 安装 response/thought stream proxy。', '捕获 assistant segment、reasoning 和工具调用事实，并通过 Session publish API 发出实时更新。'],
                'boundaries': ['capture 产生直播投影，不能替代最终 transcript 重放。', 'late write 或 turn restart boundary 会阻止过期片段继续落入当前回合。'],
                'relatedViews': ['session', 'llm', 'tools'],
            },
            'publish': {
                'label': '发布 assistant Delta',
                'subtitle': '_publish_session_assistant_delta',
                'summary': '把新片段送入当前订阅者队列',
                'role': 'process',
                'ownerPath': 'core/web/services/session/publish.py',
                'inputs': ['session_id、turn_id 与新增 assistant delta'],
                'outputs': ['有 sequence 的 assistant_delta event', '各订阅者的 bounded queue 更新'],
                'mechanism': ['_publish_session_assistant_delta 构造事件属性与恢复序号。', '发布器向当前 Session subscribers 广播，并可合并/丢弃过量的可恢复 delta。'],
                'boundaries': ['队列是实时投影，不是持久消息存储。', '客户端需要依据 event sequence 和恢复协议处理断线。'],
                'relatedViews': ['session', 'storage'],
            },
            'subscribe': {
                'label': '订阅并恢复事件流',
                'subtitle': 'stream_session_events_async',
                'summary': '读取初始状态并持续消费 Session 事件',
                'role': 'process',
                'ownerPath': 'core/web/services/session/publish.py',
                'inputs': ['session_id 与 last-event-id sequence', '初始 detail/state 和订阅队列'],
                'outputs': ['带事件 ID 的 SSE frames', '断线后的可恢复事件序列'],
                'mechanism': ['stream_session_events_async 注册 Session subscriber 并提供初始状态。', '按 resume cursor 补齐 Journal 序列后继续消费 live queue。'],
                'boundaries': ['恢复游标重放的是 Journal 投影事件，不是读取发布队列历史。', 'subscriber 生命周期结束时必须解除注册。'],
                'relatedViews': ['session', 'storage'],
            },
            'sse': {
                'label': '开放 Session SSE',
                'subtitle': 'session_events',
                'summary': '通过 text/event-stream 暴露实时会话事件',
                'role': 'entry',
                'ownerPath': 'core/web/routes/sessions.py',
                'inputs': ['session_id、initial mode 与 Last-Event-ID header'],
                'outputs': ['StreamingResponse 与 text/event-stream frames'],
                'mechanism': ['session_events 校验恢复游标并解析初始状态。', '路由以 stream_session_events_async 作为响应内容持续发送事件。'],
                'boundaries': ['HTTP stream 是客户端传输，不是 Journal 写入端。', '事件流断开不代表 turn 已完成或已取消。'],
                'relatedViews': ['http', 'session'],
            },
            'persist': {
                'label': '保存最终回合结果',
                'subtitle': '_persist_session_turn_result',
                'summary': '在回合收束时落下最终内容与状态',
                'role': 'store',
                'ownerPath': 'core/web/services/session/persist.py',
                'inputs': ['最终 Agent turn result', 'terminal status、metadata 与 Session identity'],
                'outputs': ['最终 assistant 内容与 terminal event'],
                'mechanism': ['_persist_session_turn_result 将最终回合结果与状态写入持久面。', 'worker 的收束流程再发布 Session detail snapshot。'],
                'boundaries': ['最终持久化独立于增量 SSE 发送。', '结果落账失败需要以持久化错误报告，不能由最后一个 delta 推断成功。'],
                'relatedViews': ['session', 'storage'],
            },
            'journal': {
                'label': '保存 transcript 与事件事实',
                'subtitle': 'append_turn_event',
                'summary': '以追加事件作为回放和工具事实来源',
                'role': 'store',
                'ownerPath': 'core/chat/turn_journal.py',
                'inputs': ['turn lifecycle、assistant 与 tool event'],
                'outputs': ['有序 append-only event sequence', '供历史/恢复与投影消费的事件事实'],
                'mechanism': ['append_turn_event 校验每种事件在 turn 状态中的合法转换。', '读取方可从 JSONL 重建可见对话、工具结果和恢复事件。'],
                'boundaries': ['Journal 才是 transcript/tool-event 权威；SSE 是它的投影/传输之一。', 'ConversationStore SQLite 只拥有目录和控制信息。'],
                'relatedViews': ['session', 'storage'],
            },
        },
    },
    'llm': {
        'question': '已组装的 Agent 回合如何调用统一 LLM invocation，并把获准工具 schema 一起交给模型？',
        'entry': '沿 ContextEngine、turn runner、AgentRuntime、回合适配器到 LLMClient 阅读；Provider 可用性另需现场验证。',
        'outcome': '理解消息准备、模型调用和 protocol/wire 选择发生在哪一层。',
        'category': 'runtime',
        'readingOrder': ['context', 'turn', 'agent', 'tools', 'adapter', 'invoke'],
        'relatedViews': ['session', 'tools'],
        'nodes': {
            'context': {
                'label': '提供 Agent 回合上下文',
                'subtitle': 'build_agent_context',
                'summary': '为当前执行准备身份、记忆策略和历史材料',
                'role': 'process',
                'ownerPath': 'core/orchestration/context_engine.py',
                'inputs': ['Agent runtime binding 与 memoryPolicy', 'Session history 和 episodic/group context 候选'],
                'outputs': ['Agent context blocks', '可供回合消息装配使用的历史和约束'],
                'mechanism': ['build_agent_context 聚合 AgentDirectory 与策略允许的上下文来源。', 'worker 将 context packet 的结果传入 turn 准备流程。'],
                'boundaries': ['上下文组装不等于 Team Knowledge RAG 查询。', '知识库搜索通常通过获准工具由 Agent 按需调用。'],
                'relatedViews': ['session', 'tools', 'knowledge'],
            },
            'turn': {
                'label': '准备并驱动 Agent 单轮',
                'subtitle': 'run_existing_agent_single_turn',
                'summary': '统一准备输入后进入 Agent ReAct loop',
                'role': 'process',
                'ownerPath': 'core/orchestration/turn_runner.py',
                'inputs': ['现有 Agent runtime 与 Session turn input', 'history、output contract 和 stop/control metadata'],
                'outputs': ['规范化单轮结果', 'Agent ReAct loop 内部的模型/工具交互'],
                'mechanism': ['prepare_agent_turn 根据 Session history 和 runtime binding 准备输入。', 'run_existing_agent_single_turn 调用已有 Agent 实例完成该 turn。'],
                'boundaries': ['Runner 负责单轮适配，不决定 provider wire protocol。', '一轮可包含多次模型 attempt 与多次工具调用。'],
                'relatedViews': ['session', 'tools'],
            },
            'agent': {
                'label': '发起当前模型调用',
                'subtitle': 'AgentRuntime._invoke_llm',
                'summary': '把当前消息和回放状态交给回合适配层',
                'role': 'process',
                'ownerPath': 'agent.py',
                'inputs': ['当前 Agent messages', '本轮 tools、replay state 与 invocation metadata'],
                'outputs': ['LLM attempt result 或规范化 TurnOutcome'],
                'mechanism': ['AgentRuntime 驱动模型 response preview 和 TurnOutcome 决策。', '_invoke_llm 将调用委托给 invoke_agent_llm_turn；AgentRuntime 按 role/profile/config identity 有界复用可关闭的 raw LLM client，并由 close() 释放所属客户端。'],
                'boundaries': ['模型响应会先规范化为控制面结果，再决定 finish 或 execute tools。', '这个调用点本身不代表 Provider 已连通。'],
                'relatedViews': ['session', 'tools'],
            },
            'adapter': {
                'label': '处理 LLM 回合尝试',
                'subtitle': 'invoke_agent_llm_turn',
                'summary': '在流式、降级、fallback 间协调一次回合调用',
                'role': 'process',
                'ownerPath': 'core/orchestration/turn_llm_adapter.py',
                'inputs': ['Agent messages 与 replay state', 'AgentLlmTurnHooks 注入的 invocation helpers'],
                'outputs': ['AgentLlmAttemptResult', '经处理的流式事件或失败/fallback 结果'],
                'mechanism': ['适配器通过注入 hooks 调统一 invocation helper。', '先尝试同 profile 的退化动作，再按允许策略切换一次 fallback，最后形成终态。'],
                'boundaries': ['fallback 次数与可恢复错误由协议/韧性策略约束。', '具体 Provider/wire 实现位于 core/llm。'],
                'relatedViews': ['session'],
            },
            'invoke': {
                'label': '调用统一 LLM 客户端',
                'subtitle': 'invoke_llm → LLMClient.invoke',
                'summary': '合并调用元数据并进入协议感知的客户端',
                'role': 'process',
                'ownerPath': 'core/llm/invocation.py',
                'inputs': ['messages 与 LLMClient', 'tools schema、metadata、context 与可选输出 schema'],
                'outputs': ['client response 或 canonical TurnOutcome'],
                'mechanism': ['invoke_llm 规范化 metadata/cache partition 后调用 client.invoke。', 'LLMClient 根据 model profile/provider 解析 protocol，选择 wire adapter 并编码、发送、解码响应。'],
                'boundaries': ['Provider 配置和可用性必须以当前实例为准。', '协议兼容性/网络成功不能从静态源码结构推断。'],
                'relatedViews': ['startup', 'tools'],
            },
            'tools': {
                'label': '随请求附带获准工具',
                'subtitle': 'AgentRuntime._materialize_authorized_tools',
                'summary': '只把本回合允许的工具定义绑定到模型请求',
                'role': 'control',
                'ownerPath': 'agent.py',
                'inputs': ['Key_Tools 候选定义', 'Agent ToolPolicy 与 turn authorization decision'],
                'outputs': ['物化后的可见工具列表', 'LLMClient 可编码的 tools schema'],
                'mechanism': ['Agent 初始化时调用 materialize_authorized_tools 过滤到 decision.visible_tools。', 'Agent 将获准工具 bind 到 LLM client；client 再把工具对象转换成 provider schema。'],
                'boundaries': ['模型可见性不是执行权限的最终证明。', 'ToolExecutor 每次实际调用仍做 canonical authorization。'],
                'relatedViews': ['tools'],
            },
        },
    },
    'tools': {
        'question': '模型提出工具调用后，如何通过回合可见性、执行前授权和必要的用户审批？',
        'entry': '先读 Key_Tools 候选集合和 Agent turn policy，再跟踪模型 tool_calls 到 ToolLifecycleBridge 与 ToolExecutor。',
        'outcome': '区分模型工具 schema、隐藏调用拦截、最终执行授权与人工审批。',
        'category': 'runtime',
        'readingOrder': ['defs', 'policy', 'materialize', 'visible', 'lifecycle', 'executor', 'auth', 'approval', 'decision'],
        'relatedViews': ['llm', 'session', 'knowledge', 'knowledge-write'],
        'nodes': {
            'defs': {
                'label': '构造模型候选工具',
                'subtitle': 'create_llm_facing_tools',
                'summary': '从已注册工具筛出可暴露给模型的候选集',
                'role': 'entry',
                'ownerPath': 'tools/Key_Tools.py',
                'inputs': ['内建工具定义与封装实现', '当前 LLM-facing 工具选择配置'],
                'outputs': ['候选 BaseTool 列表', '工具名称、签名与描述'],
                'mechanism': ['create_key_tools 汇集注册工具函数。', 'create_llm_facing_tools 对完整注册集应用默认暴露筛选。'],
                'boundaries': ['注册或出现在候选集合中不等于当前 Agent 获准使用。', '模型可见集合由授权阶段进一步缩小。'],
                'relatedViews': ['llm'],
            },
            'policy': {
                'label': '计算本回合工具授权',
                'subtitle': 'resolve_turn_authorization',
                'summary': '基于主体策略和 registry 决定可见与可执行范围',
                'role': 'control',
                'ownerPath': 'core/orchestration/tool_authorization_binding.py',
                'inputs': ['Agent identity/ToolPolicy', 'Tool registry descriptors 与 turn grants'],
                'outputs': ['AuthorizationReport 与 visible/executable tool sets', '拒绝原因和审批需求摘要'],
                'mechanism': ['绑定 Agent、Session 和 turn runtime identity。', '调用 canonical authorization service 对 registry snapshot、policy、grant 与预算做判定。'],
                'boundaries': ['缺失或无效的 Agent policy 会收窄/拒绝可见工具。', '此结果不会免除执行时的再次授权检查。'],
                'relatedViews': ['llm', 'session'],
            },
            'materialize': {
                'label': '物化获准工具集合',
                'subtitle': 'materialize_authorized_tools',
                'summary': '只保留授权决策中的模型可见工具',
                'role': 'process',
                'ownerPath': 'core/orchestration/tool_authorization_binding.py',
                'inputs': ['原始 LLM-facing tools', 'AuthorizationReport.decision.visible_tools'],
                'outputs': ['Agent.key_tools 中的获准工具', '提供给 LLM bind_tools 的工具集合'],
                'mechanism': ['从 decision.visible_tools 提取 canonical names。', '过滤注册工具，仅保留名字命中的对象供 Agent 使用。'],
                'boundaries': ['空可见集合会物化为空工具列表。', '物化本身不运行工具函数。'],
                'relatedViews': ['llm'],
            },
            'visible': {
                'label': '拦截隐藏工具调用',
                'subtitle': '_is_tool_visible_to_current_agent',
                'summary': '执行工具前阻断模型猜出的未授权名称',
                'role': 'control',
                'ownerPath': 'agent.py',
                'inputs': ['模型返回的 canonical tool_calls', '当前 Agent 已物化的可见工具名'],
                'outputs': ['交给 lifecycle 的可见调用', '隐藏调用的拒绝占位和 Journal 事实'],
                'mechanism': ['Agent loop 对每个工具名调用 _is_tool_visible_to_current_agent。', '不可见调用在进入 ToolExecutor 前拒绝，并写入失败占位和 hidden-call ledger event。'],
                'boundaries': ['模型自行编造工具名不会注册工具或获得执行权。', '隐藏工具分支不进入 ToolExecutor。'],
                'relatedViews': ['llm', 'session'],
            },
            'lifecycle': {
                'label': '编排工具调用生命周期',
                'subtitle': 'ToolLifecycleBridge',
                'summary': '按只读并发与写入串行规则执行并绑定结果',
                'role': 'process',
                'ownerPath': 'core/orchestration/tool_lifecycle.py',
                'inputs': ['Agent 过滤后的可执行 tool_calls', '当前对话消息与工具回调'],
                'outputs': ['调用结果写回消息链', '工具 lifecycle action 或 turn-stop signal'],
                'mechanism': ['execute_tools 将连续 read-only calls 分批并发，mutating calls 保留串行边界。', 'execute_tool 调执行器、记录结果事实，并把结果绑定回 Agent 消息。'],
                'boundaries': ['未知工具不因 lifecycle 接受参数而绕过 ToolExecutor mapping。', '取消、预算耗尽和失败结果会改变本轮继续策略。'],
                'relatedViews': ['session', 'stream', 'llm'],
            },
            'executor': {
                'label': '验证并分派工具函数',
                'subtitle': 'ToolExecutor.execute',
                'summary': '解析参数、最终授权并调用注册函数',
                'role': 'process',
                'ownerPath': 'core/infrastructure/tool_executor.py',
                'inputs': ['canonical tool name、arguments 与 tool_call_id', '执行期 Agent/Session identity'],
                'outputs': ['工具结果与特殊 action', '工具事件及业务结果分类'],
                'mechanism': ['execute 解析参数并在分派前调用 _check_canonical_execution_authorization。', '授权通过后按 tool map 查找注册函数并做参数校验、执行和结果分类。', '异步工具线程通过 copy_context 保留 memory_tool_call_scope 注入的 tool_call_id，供关联 memory event 使用。'],
                'boundaries': ['Agent 可见性检查和 executor 最终授权是两个闸门。', 'canonical 授权验证异常时按 fail-closed 拒绝。'],
                'relatedViews': ['session', 'stream'],
            },
            'auth': {
                'label': '执行前复核授权',
                'subtitle': 'authorize_tool_execution',
                'summary': '用当前执行上下文和策略决定是否放行',
                'role': 'control',
                'ownerPath': 'core/authorization/tool_authorization_service.py',
                'inputs': ['工具名、调用参数和 call ID', 'Agent execution context 与当前 authorization report'],
                'outputs': ['allowed/denied 结果', '审批要求或 grant 结果'],
                'mechanism': ['复核 Agent identity、registry descriptor、ToolPolicy、turn grant 和运行约束。', '遇到 on_request 决策时委托 Session approval service 等待决策。'],
                'boundaries': ['Agent identity 存在但执行 ContextVar 缺失时拒绝。', '无 Agent identity 的 internal context 按各自 enforcement contract 处理。'],
                'relatedViews': ['session'],
            },
            'approval': {
                'label': '等待用户工具审批',
                'subtitle': 'authorize_or_wait',
                'summary': '挂起当前执行并等待一次会话决策',
                'role': 'control',
                'ownerPath': 'core/web/services/session/tool_approvals.py',
                'inputs': ['Session/turn/Agent/call/tool identity', '审批模式、风险和 wait timeout'],
                'outputs': ['允许、拒绝、取消或超时结果', '必要时的 session 或 durable grant'],
                'mechanism': ['authorize_or_wait 登记审批 request 并挂起当前执行线程。', 'Session approval API 更新等待对象；拒绝、取消和 timeout 会终止放行。'],
                'boundaries': ['待处理 request 和 session grant 是进程内状态。', '持久授权 grant 写入 Agent ToolPolicy；always-approval 工具不能获 session/durable grant。'],
                'relatedViews': ['session'],
            },
            'decision': {
                'label': '提交审批决策',
                'subtitle': 'session_resolve_tool_approval',
                'summary': '用 request ID 唤醒对应工具调用等待者',
                'role': 'entry',
                'ownerPath': 'core/web/routes/sessions.py',
                'inputs': ['session_id 与 approval request_id', 'accept、acceptForSession、acceptAlways、decline 或 cancel'],
                'outputs': ['审批请求的公开状态投影', '唤醒 authorize_or_wait 的结果'],
                'mechanism': ['session_resolve_tool_approval 调 resolve_tool_approval_request。', '服务校验 request 与 Session 归属及决策状态，再通知 waiter 继续或拒绝。'],
                'boundaries': ['审批 endpoint 本身不直接调用工具函数。', 'always-approval 工具不能用 acceptForSession 或 acceptAlways 获得长期 grant。'],
                'relatedViews': ['session'],
            },
        },
    },
}
