"""Shared option lists and field labels for Vibelution config editors.

Single source for the workbench editor schema
(``core/web/services/config_editor_schema.py``) and the local config panel
(``scripts/config_panel.py``).
"""

from __future__ import annotations

from .models import VALID_AGENT_MODES

AGENT_MODE_OPTIONS = list(VALID_AGENT_MODES)

RUNTIME_PROFILE_OPTIONS = ["safe_local", "safe_remote", "debug", "ci"]
SEGMENTATION_STRATEGY_OPTIONS = ["task_contiguous"]
AVATAR_PRESET_OPTIONS = ["lobster", "shrimp", "crab", "cat", "chick", "bunny", "slime", "penguin", "moose"]
USER_AVATAR_PRESET_OPTIONS = ["default", "circle", "spark", "codex", "minimal", "initial"]
WORKBENCH_WINDOW_MODE_OPTIONS = ["windowed", "fullscreen"]
WORKBENCH_BACKGROUND_READABILITY_OPTIONS = ["soft", "standard", "strong"]
LOG_LEVEL_OPTIONS = ["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"]

SECTION_LABELS = {
    "zh": {
        "runtime": "运行时",
        "workbench": "工作台启动",
        "avatar": "终端形象",
        "user_profile": "用户信息",
        "context_compression": "上下文压缩",
        "security": "安全",
        "log": "日志",
        "network": "网络",
        "evolution": "进化",
        "analysis": "分析",
        "git.commit_message_model_ref": "Git 提交模型",
        "git.commit_message_prompt": "Git 提交提示词",
        "ui": "界面",
        "parser": "解析器",
        "debug": "调试",
        "pet": "宠物",
    },
    "en": {
        "runtime": "Runtime",
        "workbench": "Workbench Startup",
        "avatar": "Terminal Avatar",
        "user_profile": "User Info",
        "context_compression": "Context Compression",
        "security": "Security",
        "log": "Logging",
        "network": "Network",
        "evolution": "Evolution",
        "analysis": "Analysis",
        "git.commit_message_model_ref": "Git Commit Model",
        "git.commit_message_prompt": "Git Commit Prompt",
        "ui": "UI",
        "parser": "Parser",
        "debug": "Debug",
        "pet": "Pet",
    },
}

FIELD_LABELS = {
    "zh": {
        "runtime.profile": "运行档位",
        "runtime.preflight_doctor": "启动前自检",
        "runtime.require_venv": "要求使用 .venv",
        "workbench.backend_port": "后端服务端口",
        "workbench.frontend_port": "前端页面端口",
        "workbench.window_mode": "窗口模式",
        "avatar.preset": "终端形象预设",
        "user_profile.display_name": "用户显示名",
        "user_profile.bio": "用户背景",
        "user_profile.preferences": "用户偏好",
        "user_profile.avatar_preset": "用户头像",
        "user_profile.avatar_image_path": "本地头像图片",
        "context_compression.keep_recent_steps": "保留最近步骤数",
        "context_compression.max_compressions_per_session": "每会话最大压缩次数",
        "context_compression.effectiveness_threshold": "压缩有效性阈值",
        "context_compression.preservation.keep_ai_messages": "保留 AI 消息数",
        "context_compression.preservation.preserve_errors": "保留错误",
        "context_compression.preservation.extract_key_decisions": "提取关键决策",
        "ui.language": "界面语言",
        "ui.max_log_entries": "最大日志条目数",
        "ui.refresh_rate": "刷新频率",
        "ui.show_ascii_art": "显示 ASCII Art",
        "ui.show_welcome": "显示欢迎面板",
        "ui.workbench_theme": "工作台主题",
        "ui.workbench_theme.background_image_path": "工作台背景图片",
        "ui.workbench_theme.background_readability": "背景可读性",
        "network.proxy_enabled": "启用代理",
        "network.proxy_url": "代理地址",
        "evolution.chat_dataset.enabled": "启用 chat 数据采样",
        "evolution.chat_dataset.source_modes": "采样来源模式",
        "evolution.chat_dataset.auto_capture": "自动采样",
        "evolution.chat_dataset.segmentation_strategy": "分段策略",
        "evolution.chat_dataset.min_turns": "最少轮数",
        "evolution.chat_dataset.max_turns": "最多轮数",
        "evolution.chat_dataset.require_tool_call_or_analysis_or_conclusion": "要求工具/分析/结论信号",
        "evolution.chat_dataset.exclude_pure_chitchat": "排除纯闲聊",
        "evolution.chat_dataset.candidate_dir": "候选目录",
        "evolution.chat_dataset.review_queue_path": "审核队列路径",
        "evolution.chat_dataset.approved_raw_dir": "已批准原始目录",
        "evolution.chat_dataset.approved_jsonl_path": "已批准数据集路径",
        "evolution.chat_dataset.rejected_log_path": "拒绝审计路径",
        "git.commit_message_model_ref": "Git 提交使用的模型",
        "git.commit_message_prompt": "Git 提交提示词",
    },
    "en": {
        "runtime.profile": "Runtime Mode",
        "runtime.preflight_doctor": "Preflight Doctor",
        "runtime.require_venv": "Require .venv",
        "workbench.backend_port": "Backend Service Port",
        "workbench.frontend_port": "Frontend Page Port",
        "workbench.window_mode": "Workbench Window Mode",
        "avatar.preset": "Terminal Avatar Preset",
        "user_profile.display_name": "User Display Name",
        "user_profile.bio": "User Background",
        "user_profile.preferences": "User Preferences",
        "user_profile.avatar_preset": "User Avatar",
        "user_profile.avatar_image_path": "Local Avatar Image",
        "context_compression.keep_recent_steps": "Recent Steps to Keep",
        "context_compression.max_compressions_per_session": "Max Compressions Per Session",
        "context_compression.effectiveness_threshold": "Compression Effectiveness Threshold",
        "context_compression.preservation.keep_ai_messages": "AI Messages to Keep",
        "context_compression.preservation.preserve_errors": "Preserve Errors",
        "context_compression.preservation.extract_key_decisions": "Extract Key Decisions",
        "ui.language": "Interface Language",
        "ui.max_log_entries": "Max Log Entries",
        "ui.refresh_rate": "Refresh Rate",
        "ui.show_ascii_art": "Show ASCII Art",
        "ui.show_welcome": "Show Welcome Panel",
        "ui.workbench_theme": "Workbench Theme",
        "ui.workbench_theme.background_image_path": "Workbench Background Image",
        "ui.workbench_theme.background_readability": "Background Readability",
        "network.proxy_enabled": "Enable Proxy",
        "network.proxy_url": "Proxy URL",
        "evolution.chat_dataset.enabled": "Enable Chat Dataset Capture",
        "evolution.chat_dataset.source_modes": "Capture Source Modes",
        "evolution.chat_dataset.auto_capture": "Auto Capture",
        "evolution.chat_dataset.segmentation_strategy": "Segmentation Strategy",
        "evolution.chat_dataset.min_turns": "Minimum Turns",
        "evolution.chat_dataset.max_turns": "Maximum Turns",
        "evolution.chat_dataset.require_tool_call_or_analysis_or_conclusion": "Require Tool/Analysis/Conclusion Signal",
        "evolution.chat_dataset.exclude_pure_chitchat": "Exclude Pure Chitchat",
        "evolution.chat_dataset.candidate_dir": "Candidate Directory",
        "evolution.chat_dataset.review_queue_path": "Review Queue Path",
        "evolution.chat_dataset.approved_raw_dir": "Approved Raw Directory",
        "evolution.chat_dataset.approved_jsonl_path": "Approved Dataset Path",
        "evolution.chat_dataset.rejected_log_path": "Rejected Audit Path",
        "git.commit_message_model_ref": "Git Commit Model",
        "git.commit_message_prompt": "Git Commit Prompt",
    },
}

FIELD_SUFFIX_LABELS = {
    "zh": {
        "provider": "服务提供方",
        "kind": "类型",
        "provider.kind": "服务商类型",
        "api_key_env": "密钥环境变量",
        "provider.api_key_env": "服务商密钥环境变量",
        "base_url": "基础地址",
        "provider.base_url": "服务商基础地址",
        "compat_mode": "兼容模式",
        "provider.compat_mode": "服务商兼容模式",
        "context_window": "上下文窗口",
        "provider.context_window": "服务商上下文窗口",
        "requires_api_key": "需要 API Key",
        "provider.requires_api_key": "服务商需要 API Key",
        "transport": "传输协议",
        "contract": "交互契约",
        "reasoning_state_field": "推理状态字段",
        "tool_calling_mode": "工具调用模式",
        "strict_compatibility": "严格兼容",
        "temperature": "温度",
        "max_output_tokens": "最大输出令牌数",
        "timeout": "超时（秒）",
        "connect_timeout": "连接超时（秒）",
        "streaming": "启用流式响应",
        "discovery_enabled": "启用模型发现",
        "label": "显示名",
        "model": "模型名称",
        "model_id": "模型 ID",
        "model_ref": "绑定模型",
    },
    "en": {
        "provider": "Provider",
        "kind": "Kind",
        "provider.kind": "Provider Kind",
        "api_key_env": "API Key Env",
        "provider.api_key_env": "Provider API Key Env",
        "base_url": "Base URL",
        "provider.base_url": "Provider Base URL",
        "compat_mode": "Compat Mode",
        "provider.compat_mode": "Provider Compat Mode",
        "context_window": "Context Window",
        "provider.context_window": "Provider Context Window",
        "requires_api_key": "Requires API Key",
        "provider.requires_api_key": "Provider Requires API Key",
        "transport": "Transport",
        "contract": "Contract",
        "reasoning_state_field": "Reasoning State Field",
        "tool_calling_mode": "Tool Calling Mode",
        "strict_compatibility": "Strict Compatibility",
        "temperature": "Temperature",
        "max_output_tokens": "Max Output Tokens",
        "timeout": "Timeout (s)",
        "connect_timeout": "Connect Timeout (s)",
        "streaming": "Streaming",
        "discovery_enabled": "Discovery Enabled",
        "label": "Label",
        "model": "Model Name",
        "model_id": "Model ID",
        "model_ref": "Model binding",
    },
}

BADGE_LABELS = {
    "zh": {
        "Group": "分组",
        "List": "列表",
        "Toggle": "开关",
        "Option": "选项",
        "Seconds": "秒",
        "Token": "令牌",
        "Number": "数字",
        "JSON": "JSON",
        "Secret": "密钥",
        "URL": "地址",
        "Path": "路径",
        "Text": "文本",
        "Multiline": "多行文本",
        "Image": "图片",
    },
    "en": {
        "Group": "Group",
        "List": "List",
        "Toggle": "Toggle",
        "Option": "Option",
        "Seconds": "Seconds",
        "Token": "Token",
        "Number": "Number",
        "JSON": "JSON",
        "Secret": "Secret",
        "URL": "URL",
        "Path": "Path",
        "Text": "Text",
        "Multiline": "Multiline",
        "Image": "Image",
    },
}

FIELD_HINTS = {
    "zh": {
        "runtime.profile": "决定默认运行策略，通常先从 safe_local 或 debug 开始。",
        "runtime.preflight_doctor": "启动前先做自检，适合排查环境漂移。",
        "workbench.backend_port": "后端服务监听的本地端口，修改后下次启动或重启生效。",
        "workbench.frontend_port": "前端页面使用的本地端口，修改后下次启动或重启生效。",
        "workbench.window_mode": "窗口化保留系统标题栏；沉浸全屏会隐藏原生标题栏，修改后重启工作台生效。",
        "avatar.preset": "用于终端/CLI 工作台和宠物陪伴体的内置形象；Web 用户头像在“用户信息”里维护。",
        "context_compression.keep_recent_steps": "压缩后仍然保留的最近步骤数。",
        "context_compression.max_compressions_per_session": "单会话允许的最大压缩次数。",
        "evolution.chat_dataset.source_modes": "哪些 agent mode 产生的对话可以被静默采样进入审核队列。",
        "evolution.chat_dataset.segmentation_strategy": "chat 采样如何切分连续多轮上下文。",
        "ui.refresh_rate": "终端工作台刷新频率。",
        "ui.max_log_entries": "UI 内部保留的日志条目数。",
        "network.proxy_enabled": "启用后，科研调研等真实公网请求会通过下方代理地址访问。",
        "network.proxy_url": "填写 HTTP/HTTPS 代理地址，例如 http://127.0.0.1:7890。",
        "git.commit_message_model_ref": "选择用于生成 Git 提交说明的模型库条目。",
        "git.commit_message_prompt": "Git 提交说明生成的系统提示词模板，需要保留 {diff} 占位符。",
        "user_profile.display_name": "用于工作台和对话消息的用户名称；为空时回退到系统用户名。",
        "user_profile.bio": "简短用户背景，会作为 agent 的参考依据进入系统提示词。",
        "user_profile.preferences": "用户偏好列表，会作为 agent 的参考依据进入系统提示词。",
        "user_profile.avatar_preset": "用户头像预设，仅用于前端显示，不把图片内容传给模型。",
        "user_profile.avatar_image_path": "上传本地图片后会复制到主配置文件旁的 avatars 目录，仅用于前端显示，不把图片内容传给模型。",
        "ui.workbench_theme.background_image_path": "上传本地图片后会复制到项目外配置资源目录，并作为工作台背景显示。",
        "ui.workbench_theme.background_readability": "控制背景图片上方的遮罩和面板透明度，保障内容可读性；图片较花时使用增强。",
    },
    "en": {
        "runtime.profile": "Sets the default runtime posture. Start with safe_local or debug in most cases.",
        "runtime.preflight_doctor": "Runs startup checks before execution to catch environment drift.",
        "workbench.backend_port": "Local port listened on by the backend service. Restart the workbench after changing it.",
        "workbench.frontend_port": "Local port used by the frontend page. Restart the workbench after changing it.",
        "workbench.window_mode": "Windowed mode keeps the native title bar; immersive fullscreen hides it. Restart the workbench after changing it.",
        "avatar.preset": "Built-in avatar used by the terminal/CLI workbench and companion pet. Manage the Web user avatar under User Info.",
        "context_compression.keep_recent_steps": "How many recent steps survive compression.",
        "context_compression.max_compressions_per_session": "Compression cap per session.",
        "evolution.chat_dataset.source_modes": "Which agent modes may silently contribute conversation samples to the review queue.",
        "evolution.chat_dataset.segmentation_strategy": "How chat capture segments contiguous multi-turn context.",
        "ui.refresh_rate": "Refresh cadence for the terminal workbench.",
        "ui.max_log_entries": "How many UI log entries are retained.",
        "network.proxy_enabled": "When enabled, real public research requests use the proxy URL below.",
        "network.proxy_url": "HTTP/HTTPS proxy URL, for example http://127.0.0.1:7890.",
        "git.commit_message_model_ref": "Model-library entry used to generate Git commit messages.",
        "git.commit_message_prompt": "System prompt template for Git commit message generation. Keep the {diff} placeholder.",
        "user_profile.display_name": "User name used by the workbench and chat messages. Falls back to the OS user name when empty.",
        "user_profile.bio": "Short user background included as agent reference context.",
        "user_profile.preferences": "User preference list included as agent reference context.",
        "user_profile.avatar_preset": "User avatar preset for frontend display only. Image content is not sent to the model.",
        "user_profile.avatar_image_path": "Local image uploads are copied into the avatars directory beside the main config file for frontend display only. Image content is not sent to the model.",
        "ui.workbench_theme.background_image_path": "Local image uploads are copied into the external config resource directory and shown as the workbench background.",
        "ui.workbench_theme.background_readability": "Controls the overlay and panel opacity above the background image. Use Strong for busy images.",
    },
}
