const styles = {
  detailSection: "min-w-0 [border:1px_solid_color-mix(in_srgb,_var(--border-soft)_76%,_transparent)] [border-radius:8px] [background:color-mix(in_srgb,_var(--surface-panel)_58%,_transparent)] [&_svg]:[grid-area:icon] [&_svg]:[color:var(--accent-cool)] grid [gap:8px] [padding:10px]",
  panelHeader: "flex [align-items:flex-start] [justify-content:space-between] [gap:8px] min-w-0 [&_div]:min-w-0",
  panelHeaderActions: "inline-flex [align-items:center] [justify-content:flex-end] [gap:8px] min-w-0",
  panelEyebrow: "[margin:0_0_1px] [color:var(--fg-tertiary)] [font-size:var(--vui-font-xs)] [letter-spacing:0.07em] [text-transform:uppercase]",
  pathList: "[&_code]:min-w-0 [&_code]:[overflow:hidden] [&_code]:[color:var(--fg-secondary)] [&_code]:[font-size:var(--vui-font-xs)] [&_code]:[text-overflow:ellipsis] [&_code]:[white-space:nowrap] grid [align-content:start] [gap:5px] min-w-0 [&_span]:[margin:0] [&_span]:[color:var(--fg-secondary)] [&_span]:[font-size:var(--vui-font-xs)] [&_span]:[line-height:1.4]",
  emptyText: "[margin:0] [color:var(--fg-secondary)] [font-size:var(--vui-font-xs)] [line-height:1.4]",
  activityTimelineList: "grid [align-content:start] [gap:5px] min-w-0 [max-height:280px] [overflow:auto] [padding-right:3px]",
  activityTimelineItem: "grid [gap:4px] min-w-0 [padding:7px_8px] [border:1px_solid_var(--border-soft)] [border-radius:var(--radius-control)] [background:var(--surface-panel)] [&_strong]:min-w-0 [&_strong]:[overflow:hidden] [&_strong]:[text-overflow:ellipsis] [&_p]:min-w-0 [&_p]:[overflow:hidden] [&_p]:[text-overflow:ellipsis] [&_small]:min-w-0 [&_small]:[overflow:hidden] [&_small]:[text-overflow:ellipsis] [&_strong]:[white-space:nowrap] [&_small]:[white-space:nowrap] [&_strong]:[color:var(--fg-primary)] [&_strong]:[font-size:var(--vui-font-xs)] [&_p]:[display:-webkit-box] [&_p]:[margin:0] [&_p]:[color:var(--fg-secondary)] [&_p]:[font-size:var(--vui-font-xs)] [&_p]:[line-height:1.35] [&_p]:[-webkit-box-orient:vertical] [&_p]:[-webkit-line-clamp:2] [&_small]:[color:var(--fg-tertiary)] [&_small]:[font-size:var(--vui-font-xs)]",
  activityTimelineItem_context: "[border-color:color-mix(in_srgb,_var(--fg-tertiary)_22%,_var(--border-soft))]",
  activityTimelineItem_inbox: "[border-color:color-mix(in_srgb,_var(--state-success)_28%,_var(--border-soft))] [background:color-mix(in_srgb,_var(--state-success)_5%,_var(--surface-panel))]",
  activityTimelineItem_run: "[border-color:color-mix(in_srgb,_var(--accent-cool)_28%,_var(--border-soft))] [background:color-mix(in_srgb,_var(--accent-cool)_5%,_var(--surface-panel))]",
  activityTimelineItem_sub_run: "[border-color:color-mix(in_srgb,_var(--accent-warm)_28%,_var(--border-soft))] [background:color-mix(in_srgb,_var(--accent-warm)_5%,_var(--surface-panel))]",
  timelineActions: "flex [flex-wrap:wrap] [gap:5px] min-w-0 [&_[data-vui=\\\"button\\\"]]:[max-width:100%] [&_[data-vui=\\\"button\\\"]]:[white-space:nowrap]",
  runHistoryList: "grid [align-content:start] [gap:5px] min-w-0 [max-height:260px] [overflow:auto] [padding-right:3px]",
  runHistoryItem: "grid [gap:3px] min-w-0 [padding:7px_8px] [border:1px_solid_var(--border-soft)] [border-radius:var(--radius-control)] [background:var(--surface-panel)] [&_strong]:min-w-0 [&_strong]:[overflow:hidden] [&_strong]:[text-overflow:ellipsis] [&_strong]:[white-space:nowrap] [&_span]:min-w-0 [&_span]:[overflow:hidden] [&_span]:[text-overflow:ellipsis] [&_span]:[white-space:nowrap] [&_small]:min-w-0 [&_small]:[overflow:hidden] [&_small]:[text-overflow:ellipsis] [&_small]:[white-space:nowrap] [&_strong]:[color:var(--fg-primary)] [&_strong]:[font-size:var(--vui-font-xs)] [&_span]:[color:var(--fg-secondary)] [&_span]:[font-size:var(--vui-font-xs)] [&_small]:[color:var(--fg-tertiary)] [&_small]:[font-size:var(--vui-font-xs)]",
  inboxMessageList: "grid [align-content:start] [gap:5px] min-w-0 [max-height:280px] [overflow:auto] [padding-right:3px]",
  inboxMessageItem: "grid [gap:5px] min-w-0 [padding:7px_8px] [border:1px_solid_var(--border-soft)] [border-radius:var(--radius-control)] [background:var(--surface-panel)] [&_strong]:min-w-0 [&_strong]:[overflow:hidden] [&_strong]:[text-overflow:ellipsis] [&_p]:min-w-0 [&_p]:[overflow:hidden] [&_p]:[text-overflow:ellipsis] [&_small]:min-w-0 [&_small]:[overflow:hidden] [&_small]:[text-overflow:ellipsis] [&_strong]:[white-space:nowrap] [&_small]:[white-space:nowrap] [&_strong]:[color:var(--fg-primary)] [&_strong]:[font-size:var(--vui-font-xs)] [&_p]:[display:-webkit-box] [&_p]:[margin:0] [&_p]:[color:var(--fg-secondary)] [&_p]:[font-size:var(--vui-font-xs)] [&_p]:[line-height:1.35] [&_p]:[-webkit-box-orient:vertical] [&_p]:[-webkit-line-clamp:2] [&_small]:[color:var(--fg-tertiary)] [&_small]:[font-size:var(--vui-font-xs)]",
  inboxMessageItemFocused: "[border-color:color-mix(in_srgb,_var(--accent-cool)_44%,_transparent)] [box-shadow:none] [background:color-mix(in_srgb,_var(--accent-cool)_10%,_transparent)]",
  inboxMessageTop: "grid [grid-template-columns:minmax(0,_1fr)_auto] [align-items:center] [gap:8px] min-w-0 [&_span]:grid [&_span]:[gap:2px] [&_span]:min-w-0",
} as const;

export default styles;
