import { createVuiStyleMap } from "../components/vui/styles/createVuiStyleMap";

const styleKeys = [
  "activityTimelineItem",
  "activityTimelineItem_context",
  "activityTimelineItem_inbox",
  "activityTimelineItem_run",
  "activityTimelineItem_sub_run",
  "activityTimelineList",
  "advancedFilterBody",
  "advancedFilterSection",
  "advancedFilterSummary",
  "agentAvatar",
  "agentAvatarImage",
  "agentColumn",
  "agentColumnGrid",
  "agentColumnHeader",
  "agentIdentity",
  "agentIdentityCopy",
  "agentPanel",
  "agentPanelCreating",
  "agentRoleTag",
  "agentRoleTag_chat",
  "agentRoleTag_general",
  "agentRoleTag_memory",
  "agentRoleTag_research",
  "agentRoleTag_self",
  "agentRoleTag_supervised",
  "agentRoleTag_tool",
  "agentRow",
  "agentRowActive",
  "agentRowBulkSelected",
  "agentRowShell",
  "agentTable",
  "agentTableHead",
  "avatarEditorActions",
  "avatarEditorAnchor",
  "avatarEditorHeader",
  "avatarEditorPanel",
  "avatarLibraryHeader",
  "avatarOption",
  "avatarOptionGrid",
  "avatarOptionSelected",
  "boundarySummaryGrid",
  "bulkFieldHeader",
  "bulkPromptPicker",
  "bulkPromptSelect",
  "bulkSelectionList",
  "capabilityPreviewPanel",
  "checkField",
  "cleanPill",
  "compressionInlineCheck",
  "compressionPolicyFooter",
  "compressionPolicyGrid",
  "compressionPolicySubgrid",
  "compressionToggleField",
  "configDeepLinkRow",
  "configEditor",
  "contextModeGrid",
  "controlStrip",
  "countPill",
  "createAgentGrid",
  "createAgentPanel",
  "createToolBundleGrid",
  "createToolBundleOption",
  "createToolBundlePreview",
  "createToolBundleSelected",
  "dangerButton",
  "dangerZone",
  "detailAvatar",
  "detailAvatarButton",
  "detailHeader",
  "detailHeaderActions",
  "detailHealthStatus",
  "detailPanel",
  "detailSection",
  "detailTab",
  "detailTabActive",
  "detailTabs",
  "dirtyPill",
  "editorActions",
  "editorGrid",
  "emptyState",
  "emptyText",
  "errorText",
  "eyebrow",
  "factGrid",
  "field",
  "fieldWide",
  "filterPanel",
  "governanceActions",
  "governanceEditorGrid",
  "groupButton",
  "groupButtonActive",
  "groupList",
  "groupSection",
  "groupSectionItems",
  "groupSectionTitle",
  "health_blocked",
  "health_ok",
  "health_warning",
  "healthCell",
  "healthGuide_blocking",
  "healthGuide_info",
  "healthGuide_ok",
  "healthGuide_warning",
  "healthGuidePanel",
  "healthPill",
  "iconButton",
  "inboxMessageItem",
  "inboxMessageItemFocused",
  "inboxMessageList",
  "inboxMessageTop",
  "inlineAdd",
  "issue_blocking",
  "issue_info",
  "issue_ok",
  "issue_warning",
  "issueItem",
  "issueItem_blocking",
  "issueItem_warning",
  "issueList",
  "issuePill",
  "llmSlotField",
  "llmSlotGrid",
  "maintenanceIntro",
  "managementBriefHeader",
  "managementBriefPanel",
  "managementChecklist",
  "managementChecklistDone",
  "managementChecklistMissing",
  "managementNav",
  "memoryPolicyGrid",
  "modeList",
  "nextActionList",
  "panelEyebrow",
  "panelHeader",
  "panelHeaderActions",
  "pathList",
  "pillList",
  "policyGrid",
  "policyHint",
  "policySummaryGrid",
  "primaryButton",
  "promptConfigField",
  "promptConfigRow",
  "protectedZone",
  "referenceHeader",
  "referenceItem",
  "referenceList",
  "referenceMetaRow",
  "referenceStatusActive",
  "referenceStatusStale",
  "resetOptionField",
  "resetOptionGrid",
  "resetZone",
  "returnBanner",
  "returnBannerButton",
  "returnBannerCopy",
  "roomCheckField",
  "roomMembershipList",
  "route",
  "rowSelect",
  "runHistoryItem",
  "runHistoryList",
  "runtime_archived",
  "runtime_blocked",
  "runtime_failed",
  "runtime_idle",
  "runtime_running",
  "runtime_stopped",
  "runtime_unknown",
  "runtimeEvidenceHint",
  "runtimeFocusHeader",
  "runtimeFocusMeta",
  "runtimeFocusPanel",
  "runtimeNextStep",
  "runtimePill",
  "runtimePolicyGrid",
  "searchBox",
  "secondaryButton",
  "segmentActive",
  "segmentActiveDanger",
  "segmentButton",
  "segmentedControl",
  "storagePanel",
  "successText",
  "tagList",
  "timelineActions",
  "title",
  "toggleGrid",
  "toolBundleActions",
  "toolBundleItem",
  "toolBundleList",
  "toolBundlePanel",
  "toolBundlePanelHeader",
  "toolGovernanceItem",
  "toolGovernanceList",
  "toolPermissionGroup",
  "toolPermissionGroupHeader",
  "toolPermissionGroupList",
  "toolPermissionList",
  "toolPermissionMeta",
  "toolPermissionRow",
  "workspace",
  "workspaceCreating",
  "workspaceScopePanel",
] as const;

const styles = createVuiStyleMap(styleKeys, {
  extensions: {
    agentColumn: "content-start gap-1.5",
    agentColumnGrid: "min-h-0 content-start gap-2 overflow-auto pr-1 [scrollbar-width:thin]",
    agentColumnHeader:
      "!grid grid-cols-[minmax(0,1fr)_auto] items-center gap-1.5 px-1 text-[var(--vui-font-xs)] [&_em]:not-italic",
    agentIdentity: "grid-cols-[30px_minmax(0,1fr)] items-center gap-1.5",
    agentIdentityCopy: "content-center gap-0.5 [&_span]:truncate [&_strong]:truncate",
    agentPanel: "min-h-0 grid-rows-[auto_auto_minmax(0,1fr)] overflow-hidden",
    agentPanelCreating: "grid-rows-[auto_minmax(360px,1.4fr)_minmax(120px,0.6fr)]",
    agentRow:
      "!grid min-h-[44px] w-full grid-cols-[minmax(180px,1.3fr)_minmax(120px,0.86fr)_minmax(110px,0.82fr)_minmax(88px,0.48fr)_minmax(104px,0.72fr)_minmax(128px,0.68fr)] items-center gap-1.5 rounded-[var(--radius-control)] border border-[var(--vui-border-subtle)] bg-[var(--vui-surface-row)] px-2 py-1 text-left text-[var(--vui-font-xs)]",
    agentRowShell: "grid-cols-[28px_minmax(0,1fr)] items-start gap-1",
    agentTable: "grid min-w-0 content-start gap-1 overflow-x-auto [scrollbar-width:thin]",
    agentTableHead:
      "sticky top-0 z-10 grid-cols-[minmax(180px,1.3fr)_minmax(120px,0.86fr)_minmax(110px,0.82fr)_minmax(88px,0.48fr)_minmax(104px,0.72fr)_minmax(128px,0.68fr)] bg-[var(--vui-surface-glass)] text-[var(--vui-font-xs)]",
    controlStrip:
      "!grid grid-cols-[auto_minmax(0,1fr)] items-start gap-1.5 px-3 pt-1 max-[1120px]:grid-cols-[1fr]",
    detailPanel: "min-h-0 overflow-auto",
    emptyState: "place-items-start min-h-[72px] text-left",
    filterPanel: "min-h-0 grid-rows-[auto_minmax(0,1fr)_auto] overflow-hidden",
    groupButton:
      "!grid w-full grid-cols-[minmax(0,1fr)_auto_auto] items-center gap-1.5 rounded-[var(--radius-control)] px-2 py-1 text-left [&_em]:not-italic [&_span]:min-w-0 [&_span]:truncate",
    groupList: "content-start gap-1.5 overflow-auto pr-1 [scrollbar-width:thin]",
    groupSection: "content-start gap-1.5",
    groupSectionItems: "content-start gap-1",
    managementNav: "m-0 self-start justify-self-start",
    panelHeader:
      "!flex flex-nowrap items-start justify-between gap-2 [&_h2]:m-0 [&_h3]:m-0",
    panelHeaderActions: "!flex flex-nowrap items-center justify-end gap-1.5",
    route: "grid-rows-[auto_auto_minmax(0,1fr)] gap-1.5 overflow-hidden bg-transparent",
    searchBox:
      "!flex h-[var(--vui-control-height-md)] items-center gap-1.5 rounded-[var(--radius-control)] border border-[var(--vui-border-subtle)] bg-[var(--vui-surface-row)] px-2",
    storagePanel: "content-start gap-1.5 overflow-hidden [&_code]:truncate",
    workspace:
      "!grid min-h-0 grid-cols-[minmax(214px,268px)_minmax(430px,1.08fr)_minmax(330px,0.86fr)] grid-rows-[minmax(0,1fr)] gap-[var(--agent-density-gap)] overflow-hidden px-2.5 pb-2 pt-1 max-[1040px]:grid-cols-[minmax(220px,270px)_minmax(0,1fr)] max-[1040px]:auto-rows-[minmax(180px,auto)] max-[1040px]:content-start max-[860px]:grid-cols-[1fr] max-[860px]:auto-rows-auto",
    workspaceCreating: "grid-rows-[minmax(0,1fr)]",
  },
});

export default styles;
