const styles = {
  configEditor: "grid [gap:8px] min-w-0 [padding:10px] [border:1px_solid_color-mix(in_srgb,_var(--border-soft)_78%,_transparent)] [border-radius:8px] [background:color-mix(in_srgb,_var(--surface-panel)_54%,_transparent)]",
  panelHeader: "flex [align-items:flex-start] [justify-content:space-between] [gap:8px] min-w-0 [&_div]:min-w-0",
  panelEyebrow: "[margin:0_0_1px] [color:var(--fg-tertiary)] [font-size:var(--vui-font-xs)] [letter-spacing:0.07em] [text-transform:uppercase]",
  dirtyPill: "inline-flex [align-items:center] [min-height:24px] [padding:0_8px] [border-radius:999px] [font-size:var(--vui-font-xs)] [font-weight:700] [border:1px_solid_color-mix(in_srgb,_var(--accent-warm)_30%,_transparent)] [background:color-mix(in_srgb,_var(--accent-warm)_10%,_transparent)] [color:var(--accent-warm-2)]",
  cleanPill: "inline-flex [align-items:center] [min-height:24px] [padding:0_8px] [border-radius:999px] [font-size:var(--vui-font-xs)] [font-weight:700] [border:1px_solid_color-mix(in_srgb,_var(--state-success)_26%,_transparent)] [background:color-mix(in_srgb,_var(--state-success)_8%,_transparent)] [color:var(--state-success)]",
  healthGuidePanel: "grid [gap:7px] min-w-0 [padding:8px] [border:1px_solid_color-mix(in_srgb,_var(--border-soft)_78%,_transparent)] [border-radius:var(--radius-control)] [background:color-mix(in_srgb,_var(--surface-panel)_54%,_transparent)] [&_div]:grid [&_div]:[gap:2px] [&_div]:min-w-0 [&_span]:[color:var(--fg-tertiary)] [&_span]:[font-size:var(--vui-font-xs)] [&_span]:[font-weight:760] [&_strong]:min-w-0 [&_strong]:[overflow-wrap:anywhere] [&_p]:[margin:0] [&_p]:[color:var(--fg-secondary)] [&_p]:[font-size:var(--vui-font-xs)] [&_p]:[line-height:1.38] [&_p]:[overflow-wrap:anywhere] [&_strong]:[margin-right:6px] [&_strong]:[color:var(--fg-tertiary)] [&_strong]:[font-size:var(--vui-font-xs)]",
  healthGuide_blocking: "[border-color:color-mix(in_srgb,_var(--state-error)_28%,_transparent)] [background:color-mix(in_srgb,_var(--state-error)_7%,_var(--surface-panel))]",
  healthGuide_info: "[border-color:color-mix(in_srgb,_var(--accent-warm)_28%,_transparent)] [background:color-mix(in_srgb,_var(--accent-warm)_7%,_var(--surface-panel))]",
  healthGuide_ok: "[border-color:color-mix(in_srgb,_var(--state-success)_24%,_transparent)] [background:color-mix(in_srgb,_var(--state-success)_7%,_var(--surface-panel))]",
  healthGuide_warning: "[border-color:color-mix(in_srgb,_var(--accent-warm)_28%,_transparent)] [background:color-mix(in_srgb,_var(--accent-warm)_7%,_var(--surface-panel))]",
  editorGrid: "grid [grid-template-columns:repeat(2,_minmax(0,_1fr))] [gap:7px] min-w-0 max-[860px]:[grid-template-columns:1fr]",
  fieldWide: "grid [grid-column:1_/_-1] [gap:4px] min-w-0 [&_span]:[color:var(--fg-tertiary)] [&_span]:[font-size:var(--vui-font-xs)] [&_small]:[color:var(--fg-tertiary)] [&_small]:[font-size:var(--vui-font-xs)] [&_small]:[line-height:1.32] [&_textarea]:[width:100%] [&_textarea]:min-w-0 [&_textarea]:[border:1px_solid_var(--border-soft)] [&_textarea]:[border-radius:var(--radius-control)] [&_textarea]:[background:var(--surface-panel)] [&_textarea]:[color:var(--fg-primary)] [&_textarea]:[font:inherit] [&_textarea]:[font-size:var(--vui-font-xs)] [&_textarea]:[min-height:62px] [&_textarea]:[resize:vertical] [&_textarea]:[padding:7px_9px] [&_textarea]:[line-height:1.35] [&_textarea]:focus:[outline:2px_solid_color-mix(in_srgb,_var(--accent-cool)_24%,_transparent)] [&_textarea]:focus:[border-color:color-mix(in_srgb,_var(--accent-cool)_48%,_transparent)]",
  llmSlotGrid: "grid [grid-template-columns:repeat(2,_minmax(0,_1fr))] [gap:8px] min-w-0 max-[860px]:[grid-template-columns:1fr]",
  llmSlotField: "grid [gap:5px] min-w-0 [padding:7px] [border:1px_solid_color-mix(in_srgb,_var(--border-soft)_88%,_transparent)] [border-radius:var(--radius-control)] [background:color-mix(in_srgb,_var(--surface-panel)_58%,_transparent)] [&_span]:grid [&_span]:[grid-template-columns:minmax(0,_1fr)_auto] [&_span]:[align-items:center] [&_span]:[gap:8px] [&_span]:min-w-0 [&_strong]:min-w-0 [&_strong]:[overflow-wrap:anywhere] [&_strong]:[color:var(--fg-secondary)] [&_strong]:[font-size:var(--vui-font-xs)] [&_small]:[display:-webkit-box] [&_small]:[min-height:32px] [&_small]:[overflow:hidden] [&_small]:[color:var(--fg-tertiary)] [&_small]:[font-size:var(--vui-font-xs)] [&_small]:[line-height:1.32] [&_small]:[-webkit-box-orient:vertical] [&_small]:[-webkit-line-clamp:2] [&_select]:[width:100%] [&_select]:min-w-0 [&_select]:[min-height:30px] [&_select]:[border:1px_solid_var(--border-soft)] [&_select]:[border-radius:var(--radius-control)] [&_select]:[background:var(--surface-panel)] [&_select]:[color:var(--fg-primary)] [&_select]:[font:inherit] [&_select]:[font-size:var(--vui-font-xs)] [&_select]:[padding:0_8px] [&_select]:focus:[outline:2px_solid_color-mix(in_srgb,_var(--accent-cool)_24%,_transparent)] [&_select]:focus:[border-color:color-mix(in_srgb,_var(--accent-cool)_48%,_transparent)]",
  configDeepLinkRow: "flex [justify-content:flex-end] [gap:6px] min-w-0 [flex-wrap:wrap] [&_[data-vui=\"button\"]]:[max-width:100%] [&_[data-vui=\"button\"]]:w-fit [&_[data-vui=\"button\"]]:[white-space:nowrap]",
  promptConfigField: "[gap:6px]",
  promptConfigRow: "grid [grid-template-columns:minmax(0,_1fr)_max-content] [align-items:center] [gap:6px] min-w-0 [&_select]:min-w-0 [&_[data-vui=\"button\"]]:[max-width:100%] [&_[data-vui=\"button\"]]:w-fit [&_[data-vui=\"button\"]]:[white-space:nowrap] [&_select]:focus:[outline:2px_solid_color-mix(in_srgb,_var(--accent-cool)_24%,_transparent)] [&_select]:focus:[border-color:color-mix(in_srgb,_var(--accent-cool)_48%,_transparent)] max-[860px]:[grid-template-columns:1fr]",
  errorText: "[margin:0] [font-size:var(--vui-font-xs)] [line-height:1.4] [overflow-wrap:anywhere] [color:var(--state-error)]",
  successText: "[margin:0] [font-size:var(--vui-font-xs)] [line-height:1.4] [overflow-wrap:anywhere] [color:var(--state-success)]",
  editorActions: "flex [justify-content:flex-end] [gap:6px] min-w-0 [flex-wrap:wrap] [&_[data-vui=\"button\"]]:[max-width:100%] [&_[data-vui=\"button\"]]:w-fit",
} as const;

export default styles;
