const styles = {
  runtimeFocusPanel: "grid [gap:8px] min-w-0 [padding:10px] [border:1px_solid_color-mix(in_srgb,_var(--accent-cool)_28%,_var(--border-soft))] [border-radius:8px] [background:color-mix(in_srgb,_var(--accent-cool)_6%,_var(--surface-panel))] [box-shadow:none] [&_p]:min-w-0 [&_p]:[overflow:hidden] [&_p]:[text-overflow:ellipsis] [&_p]:[white-space:nowrap] [&_p]:[margin:0] [&_p]:[color:var(--fg-secondary)] [&_p]:[font-size:var(--vui-font-xs)]",
  runtimeFocusHeader: "grid [grid-template-columns:minmax(0,_1fr)_auto] [gap:10px] [align-items:center] min-w-0",
  panelEyebrow: "[margin:0_0_1px] [color:var(--fg-tertiary)] [font-size:var(--vui-font-xs)] [letter-spacing:0.07em] [text-transform:uppercase]",
  runtimePill: "inline-flex [align-items:center] [justify-content:center] [min-height:26px] [padding:0_7px] [border:1px_solid_var(--border-soft)] [border-radius:999px] [font-size:var(--vui-font-xs)] [font-weight:700] [white-space:nowrap]",
  runtime_archived: "[border-color:color-mix(in_srgb,_var(--fg-tertiary)_24%,_transparent)] [background:color-mix(in_srgb,_var(--fg-tertiary)_8%,_transparent)] [color:var(--fg-secondary)]",
  runtime_blocked: "[border-color:color-mix(in_srgb,_var(--state-error)_34%,_transparent)] [background:color-mix(in_srgb,_var(--state-error)_10%,_transparent)] [color:var(--state-error)]",
  runtime_failed: "[border-color:color-mix(in_srgb,_var(--state-error)_34%,_transparent)] [background:color-mix(in_srgb,_var(--state-error)_10%,_transparent)] [color:var(--state-error)]",
  runtime_idle: "[border-color:color-mix(in_srgb,_var(--fg-tertiary)_24%,_transparent)] [background:color-mix(in_srgb,_var(--fg-tertiary)_8%,_transparent)] [color:var(--fg-secondary)]",
  runtime_running: "[border-color:color-mix(in_srgb,_var(--accent-cool)_34%,_transparent)] [background:color-mix(in_srgb,_var(--accent-cool)_10%,_transparent)] [color:var(--accent-cool)]",
  runtime_stopped: "[border-color:color-mix(in_srgb,_var(--fg-tertiary)_24%,_transparent)] [background:color-mix(in_srgb,_var(--fg-tertiary)_8%,_transparent)] [color:var(--fg-secondary)]",
  runtime_unknown: "[border-color:color-mix(in_srgb,_var(--fg-tertiary)_24%,_transparent)] [background:color-mix(in_srgb,_var(--fg-tertiary)_8%,_transparent)] [color:var(--fg-secondary)]",
  runtimeFocusMeta: "[&_code]:min-w-0 [&_code]:[overflow:hidden] [&_code]:[text-overflow:ellipsis] [&_code]:[white-space:nowrap] grid [grid-template-columns:repeat(3,_minmax(0,_1fr))] [gap:6px] min-w-0 [&_span]:grid [&_span]:[gap:3px] [&_span]:min-w-0 [&_span]:[padding:6px_7px] [&_span]:[border:1px_solid_var(--border-soft)] [&_span]:[border-radius:var(--radius-control)] [&_span]:[background:var(--surface-card)] [&_strong]:[color:var(--fg-tertiary)] [&_strong]:[font-size:var(--vui-font-xs)] [&_strong]:[font-weight:700] [&_strong]:[text-transform:uppercase] [&_code]:[color:var(--fg-secondary)] [&_code]:[font-family:var(--font-mono,_ui-monospace,_SFMono-Regular,_Consolas,_monospace)] [&_code]:[font-size:var(--vui-font-xs)]",
  runtimeNextStep: "grid [gap:4px] min-w-0 [padding:9px_10px] [border:1px_solid_color-mix(in_srgb,_var(--accent-warm)_20%,_transparent)] [border-radius:var(--radius-control)] [background:color-mix(in_srgb,_var(--accent-warm)_7%,_transparent)] [&_strong]:[color:var(--fg-tertiary)] [&_strong]:[font-size:var(--vui-font-xs)] [&_strong]:[font-weight:700] [&_strong]:[text-transform:uppercase] [&_span]:[color:var(--fg-secondary)] [&_span]:[font-size:var(--vui-font-xs)] [&_span]:[line-height:1.4]",
  runtimeEvidenceHint: "grid [grid-template-columns:auto_auto_minmax(0,_1fr)] [gap:8px] [align-items:center] min-w-0 [padding:8px_10px] [border:1px_solid_var(--border-soft)] [border-radius:var(--radius-control)] [background:var(--surface-card)] [&_strong]:min-w-0 [&_strong]:[overflow:hidden] [&_strong]:[text-overflow:ellipsis] [&_strong]:[white-space:nowrap] [&_span]:min-w-0 [&_span]:[overflow:hidden] [&_span]:[text-overflow:ellipsis] [&_span]:[white-space:nowrap] [&_code]:min-w-0 [&_code]:[overflow:hidden] [&_code]:[text-overflow:ellipsis] [&_code]:[white-space:nowrap] [&_strong]:[color:var(--fg-tertiary)] [&_strong]:[font-size:var(--vui-font-xs)] [&_strong]:[font-weight:700] [&_strong]:[text-transform:uppercase] [&_span]:[color:var(--fg-secondary)] [&_span]:[font-size:var(--vui-font-xs)] [&_span]:[font-weight:700] [&_code]:[color:var(--fg-primary)] [&_code]:[font-family:var(--font-mono,_ui-monospace,_SFMono-Regular,_Consolas,_monospace)] [&_code]:[font-size:var(--vui-font-xs)]",
  timelineActions: "flex [flex-wrap:wrap] [gap:5px] min-w-0 [&_[data-vui=\\\"button\\\"]]:[max-width:100%] [&_[data-vui=\\\"button\\\"]]:[white-space:nowrap]",
} as const;

export default styles;
