const styles = {
  cleanPill: "inline-flex [align-items:center] [min-height:24px] [padding:0_8px] [border-radius:999px] [font-size:var(--vui-font-xs)] [font-weight:700] [border:1px_solid_color-mix(in_srgb,_var(--state-success)_26%,_transparent)] [background:color-mix(in_srgb,_var(--state-success)_8%,_transparent)] [color:var(--state-success)]",
  configEditor: "grid [gap:8px] min-w-0 [padding:10px] [border:1px_solid_color-mix(in_srgb,_var(--vui-border-subtle)_78%,_transparent)] [border-radius:var(--radius-panel)] [background:color-mix(in_srgb,_var(--vui-surface-panel)_54%,_transparent)]",
  detailSection: "min-w-0 [border:1px_solid_color-mix(in_srgb,_var(--vui-border-subtle)_76%,_transparent)] [border-radius:var(--radius-panel)] [background:color-mix(in_srgb,_var(--vui-surface-panel)_58%,_transparent)] [&_svg]:[grid-area:icon] [&_svg]:[color:var(--accent-cool)] grid [gap:8px] [padding:10px]",
  emptyText: "[margin:0] [color:var(--fg-secondary)] [font-size:var(--vui-font-xs)] [line-height:1.4]",
  panelEyebrow: "[margin:0_0_1px] [color:var(--fg-tertiary)] [font-size:var(--vui-font-xs)] [letter-spacing:0.07em] [text-transform:uppercase]",
  panelHeader: "flex [align-items:flex-start] [justify-content:space-between] [gap:8px] min-w-0 [&_div]:min-w-0",
  referenceHeader: "grid [grid-template-columns:minmax(0,_1fr)_auto] [align-items:center] [gap:6px] min-w-0 max-[860px]:[grid-template-columns:1fr]",
  referenceItem: "[&_small]:[grid-area:meta] [&_small]:min-w-0 [&_small]:[overflow-wrap:anywhere] [&_small]:[color:var(--fg-tertiary)] [&_small]:[font-size:var(--vui-font-xs)] grid [gap:4px] min-w-0 [padding:7px_8px] [border:1px_solid_color-mix(in_srgb,_var(--vui-border-subtle)_86%,_transparent)] [border-radius:var(--radius-control)] [background:color-mix(in_srgb,_var(--vui-surface-row)_58%,_transparent)] [&_strong]:min-w-0 [&_strong]:[overflow-wrap:anywhere] [&_strong]:[color:var(--fg-primary)] [&_strong]:[font-size:var(--vui-font-xs)] [&_span]:[margin:0] [&_span]:min-w-0 [&_span]:[overflow-wrap:anywhere] [&_span]:[color:var(--fg-secondary)] [&_span]:[font-size:var(--vui-font-xs)] [&_span]:[line-height:1.4]",
  referenceList: "grid [align-content:start] [gap:5px] min-w-0",
  referenceMetaRow: "grid [grid-template-columns:minmax(0,_1fr)_auto] [align-items:center] [gap:6px] min-w-0 [&_[data-vui=\"button\"]]:[max-width:100%] [&_[data-vui=\"button\"]]:w-fit [&_[data-vui=\"button\"]]:[white-space:nowrap] max-[860px]:[grid-template-columns:1fr]",
  referenceStatusActive: "inline-flex [align-items:center] [min-height:19px] [padding:0_6px] [border:1px_solid_var(--vui-border-subtle)] [border-radius:999px] [font-size:var(--vui-font-xs)] [font-weight:760] [text-transform:uppercase] [white-space:nowrap] [border-color:color-mix(in_srgb,_var(--state-success)_28%,_transparent)] [background:color-mix(in_srgb,_var(--state-success)_8%,_transparent)] [color:var(--state-success)]",
  referenceStatusStale: "inline-flex [align-items:center] [min-height:19px] [padding:0_6px] [border:1px_solid_var(--vui-border-subtle)] [border-radius:999px] [font-size:var(--vui-font-xs)] [font-weight:760] [text-transform:uppercase] [white-space:nowrap] [border-color:color-mix(in_srgb,_var(--accent-warm)_32%,_transparent)] [background:color-mix(in_srgb,_var(--accent-warm)_10%,_transparent)] [color:var(--accent-warm-2)]",
  roomCheckField: "grid [grid-template-columns:auto_minmax(0,_1fr)_max-content] [align-items:center] [gap:8px] min-w-0 [min-height:36px] [padding:6px_8px] [border:1px_solid_color-mix(in_srgb,_var(--vui-border-subtle)_86%,_transparent)] [border-radius:var(--radius-control)] [background:color-mix(in_srgb,_var(--vui-surface-row)_58%,_transparent)] [color:var(--fg-secondary)] [&_input]:[margin:0] [&_span]:grid [&_span]:[gap:2px] [&_span]:min-w-0 [&_strong]:min-w-0 [&_strong]:[overflow-wrap:anywhere] [&_small]:min-w-0 [&_small]:[overflow-wrap:anywhere] [&_strong]:[color:var(--fg-primary)] [&_strong]:[font-size:var(--vui-font-xs)] [&_small]:[color:var(--fg-tertiary)] [&_small]:[font-size:var(--vui-font-xs)] [&_[data-vui=\"button\"]]:[max-width:100%] [&_[data-vui=\"button\"]]:w-fit [&_[data-vui=\"button\"]]:[white-space:nowrap] max-[860px]:[grid-template-columns:auto_minmax(0,_1fr)] max-[860px]:[align-items:start]",
  roomMembershipList: "grid [align-content:start] [gap:7px] min-w-0 [max-height:220px] [overflow:auto] [padding-right:3px]",
} as const;

export default styles;
