const styles = {
  factGrid: "grid [grid-template-columns:repeat(auto-fit,_minmax(190px,_1fr))] [gap:6px] [&_section]:min-w-0 [&_section]:[border:1px_solid_color-mix(in_srgb,_var(--border-soft)_76%,_transparent)] [&_section]:[border-radius:8px] [&_section]:[background:color-mix(in_srgb,_var(--surface-card)_72%,_transparent)] [&_section]:grid [&_section]:[grid-template-columns:18px_minmax(0,_1fr)] [&_section]:[grid-template-rows:auto_auto] [&_section]:[align-items:center] [&_section]:[column-gap:8px] [&_section]:[row-gap:2px] [&_section]:[padding:7px_8px_8px] [&_svg]:[grid-column:1] [&_svg]:[grid-row:1_/_span_2] [&_svg]:[width:16px] [&_svg]:[height:16px] [&_svg]:[align-self:center] [&_svg]:[color:var(--accent-cool)] [&_span]:[grid-column:2] [&_span]:[grid-row:1] [&_span]:block [&_span]:min-w-0 [&_span]:[overflow:hidden] [&_span]:[color:var(--fg-tertiary)] [&_span]:[font-size:var(--vui-font-xs)] [&_span]:[text-overflow:ellipsis] [&_span]:[white-space:nowrap] [&_strong]:[grid-column:2] [&_strong]:[grid-row:2] [&_strong]:block [&_strong]:min-w-0 [&_strong]:[overflow:hidden] [&_strong]:[color:var(--fg-primary)] [&_strong]:[font-size:var(--vui-font-xs)] [&_strong]:[text-overflow:ellipsis] [&_strong]:[white-space:nowrap] max-[860px]:[grid-template-columns:1fr]",
  detailSection: "min-w-0 [border:1px_solid_color-mix(in_srgb,_var(--border-soft)_76%,_transparent)] [border-radius:8px] [background:color-mix(in_srgb,_var(--surface-card)_72%,_transparent)] [&_svg]:[grid-area:icon] [&_svg]:[color:var(--accent-cool)] grid [gap:8px] [padding:10px]",
  panelHeader: "flex [align-items:flex-start] [justify-content:space-between] [gap:8px] min-w-0 [&_div]:min-w-0",
  panelEyebrow: "[margin:0_0_1px] [color:var(--fg-tertiary)] [font-size:var(--vui-font-xs)] [letter-spacing:0.07em] [text-transform:uppercase]",
  boundarySummaryGrid: "grid [align-content:start] [gap:5px] min-w-0 [grid-template-columns:repeat(3,_minmax(0,_1fr))] [&_span]:grid [&_span]:[gap:2px] [&_span]:min-w-0 [&_span]:[padding:7px_8px] [&_span]:[border:1px_solid_var(--border-soft)] [&_span]:[border-radius:var(--radius-control)] [&_span]:[background:var(--surface-panel)] [&_strong]:min-w-0 [&_strong]:[overflow:hidden] [&_strong]:[text-overflow:ellipsis] [&_strong]:[white-space:nowrap] [&_small]:min-w-0 [&_small]:[overflow:hidden] [&_small]:[text-overflow:ellipsis] [&_small]:[white-space:nowrap] [&_strong]:[color:var(--fg-primary)] [&_strong]:[font-size:var(--vui-font-xs)] [&_small]:[color:var(--fg-tertiary)] [&_small]:[font-size:var(--vui-font-xs)]",
  pillList: "[&_span]:inline-flex [&_span]:[align-items:center] [&_span]:[min-height:22px] [&_span]:[padding:0_6px] [&_span]:[border:1px_solid_color-mix(in_srgb,_var(--accent-cool)_22%,_transparent)] [&_span]:[border-radius:999px] [&_span]:[background:color-mix(in_srgb,_var(--accent-cool)_8%,_transparent)] [&_span]:[color:var(--accent-cool)] [&_span]:[font-style:normal] [&_span]:[font-size:var(--vui-font-xs)] [&_span]:[white-space:nowrap] [align-content:start] [gap:5px] min-w-0 flex [flex-wrap:wrap]",
  policyGrid: "grid [grid-template-columns:repeat(3,_minmax(0,_1fr))] [gap:6px] [&_div]:min-w-0 [&_div]:[border:1px_solid_color-mix(in_srgb,_var(--border-soft)_76%,_transparent)] [&_div]:[border-radius:8px] [&_div]:[background:color-mix(in_srgb,_var(--surface-card)_72%,_transparent)] [&_div]:grid [&_div]:[grid-template-columns:auto_minmax(0,_1fr)] [&_div]:[grid-template-rows:auto_auto] [&_div]:[column-gap:8px] [&_div]:[row-gap:2px] [&_div]:[padding:7px_8px_8px] [&_svg]:[grid-column:1] [&_svg]:[grid-row:1_/_3] [&_svg]:[color:var(--accent-cool)] [&_span]:[grid-column:2] [&_span]:[grid-row:1] [&_span]:[color:var(--fg-tertiary)] [&_span]:[font-size:var(--vui-font-xs)] [&_strong]:[grid-column:2] [&_strong]:[grid-row:2] [&_strong]:min-w-0 [&_strong]:[overflow:hidden] [&_strong]:[color:var(--fg-primary)] [&_strong]:[font-size:var(--vui-font-xs)] [&_strong]:[text-overflow:ellipsis] [&_strong]:[white-space:nowrap] max-[860px]:[grid-template-columns:1fr]",
} as const;

export default styles;
