const styles = {
  configEditor: "grid [gap:8px] min-w-0 [padding:10px] [border:1px_solid_color-mix(in_srgb,_var(--vui-border-subtle)_78%,_transparent)] [border-radius:var(--radius-panel)] [background:color-mix(in_srgb,_var(--vui-surface-panel)_54%,_transparent)]",
  panelHeader: "flex [align-items:flex-start] [justify-content:space-between] [gap:8px] min-w-0 [&_div]:min-w-0",
  panelEyebrow: "[margin:0_0_1px] [color:var(--fg-tertiary)] [font-size:var(--vui-font-xs)] [letter-spacing:0.07em] [text-transform:uppercase]",
  bulkSelectionList: "flex [flex-wrap:wrap] [gap:6px] min-w-0 [padding:6px] [border:1px_solid_color-mix(in_srgb,_var(--vui-border-subtle)_72%,_transparent)] [border-radius:var(--radius-control)] [background:color-mix(in_srgb,_var(--vui-surface-row)_44%,_transparent)] [overflow-wrap:anywhere] [&_span]:min-w-0 [&_span]:[max-width:100%] [&_span]:[padding:3px_7px] [&_span]:[border:1px_solid_color-mix(in_srgb,_var(--vui-border-subtle)_86%,_transparent)] [&_span]:[border-radius:var(--radius-control)] [&_span]:[background:color-mix(in_srgb,_var(--vui-surface-row)_52%,_transparent)] [&_span]:[color:var(--fg-secondary)] [&_span]:[font-size:var(--vui-font-xs)]",
  editorGrid: "grid [grid-template-columns:repeat(2,_minmax(0,_1fr))] [gap:7px] min-w-0 max-[860px]:[grid-template-columns:1fr]",
  field: "last-child:[grid-column:1_/_-1] grid [gap:4px] min-w-0 [&_span]:[color:var(--fg-tertiary)] [&_span]:[font-size:var(--vui-font-xs)] [&_small]:[color:var(--fg-tertiary)] [&_small]:[font-size:var(--vui-font-xs)] [&_small]:[line-height:1.32] [&_input]:min-w-0 [&_input]:[border:1px_solid_var(--vui-border-subtle)] [&_input]:[border-radius:var(--radius-control)] [&_input]:[background:var(--vui-surface-row)] [&_input]:[color:var(--fg-primary)] [&_input]:[font:inherit] [&_input]:[font-size:var(--vui-font-xs)] [&_select]:[width:100%] [&_select]:min-w-0 [&_select]:[min-height:30px] [&_select]:[border:1px_solid_var(--vui-border-subtle)] [&_select]:[border-radius:var(--radius-control)] [&_select]:[background:var(--vui-surface-row)] [&_select]:[color:var(--fg-primary)] [&_select]:[font:inherit] [&_select]:[font-size:var(--vui-font-xs)] [&_input]:[flex:0_0_auto] [&_input]:[width:14px] [&_input]:[height:14px] [&_input]:[min-height:14px] [&_input]:[padding:0] [&_select]:[padding:0_8px] [&_input]:focus:[outline:2px_solid_color-mix(in_srgb,_var(--accent-cool)_24%,_transparent)] [&_input]:focus:[border-color:color-mix(in_srgb,_var(--accent-cool)_48%,_transparent)] [&_select]:focus:[outline:2px_solid_color-mix(in_srgb,_var(--accent-cool)_24%,_transparent)] [&_select]:focus:[border-color:color-mix(in_srgb,_var(--accent-cool)_48%,_transparent)]",
  bulkFieldHeader: "inline-flex [align-items:center] [gap:6px] [color:var(--fg-tertiary)] [font-size:var(--vui-font-xs)] [font-weight:800] [&_input]:[width:14px] [&_input]:[height:14px] [&_input]:[margin:0] [&_input]:[accent-color:var(--accent-cool)]",
  errorText: "[margin:0] [font-size:var(--vui-font-xs)] [line-height:1.4] [overflow-wrap:anywhere] [color:var(--state-error)]",
  successText: "[margin:0] [font-size:var(--vui-font-xs)] [line-height:1.4] [overflow-wrap:anywhere] [color:var(--state-success)]",
  editorActions: "flex [justify-content:flex-end] [gap:6px] min-w-0 [flex-wrap:wrap] [&_[data-vui=\"button\"]]:[max-width:100%] [&_[data-vui=\"button\"]]:w-fit",
} as const;

export default styles;
