const styles = {
  createAgentPanel: "grid [align-content:start] [gap:8px] min-w-0 min-h-0 [padding:10px] [border:1px_solid_color-mix(in_srgb,_var(--accent-cool)_26%,_var(--border-soft))] [border-radius:8px] [background:color-mix(in_srgb,_var(--accent-cool)_6%,_var(--surface-card))] [overflow:auto] [&_p]:[margin:0] [&_p]:[color:var(--fg-secondary)] [&_p]:[font-size:var(--vui-font-xs)] [&_p]:[line-height:1.42] [&_p]:[overflow-wrap:anywhere]",
  panelHeader: "flex [align-items:flex-start] [justify-content:space-between] [gap:8px] min-w-0 [&_div]:min-w-0",
  panelEyebrow: "[margin:0_0_1px] [color:var(--fg-tertiary)] [font-size:var(--vui-font-xs)] [letter-spacing:0.07em] [text-transform:uppercase]",
  createAgentGrid: "grid [grid-template-columns:repeat(2,_minmax(0,_1fr))] [gap:7px] min-w-0 max-[860px]:[grid-template-columns:1fr]",
  fieldWide: "grid [grid-column:1_/_-1] [gap:4px] min-w-0 [&_span]:[color:var(--fg-tertiary)] [&_span]:[font-size:var(--vui-font-xs)] [&_small]:[color:var(--fg-tertiary)] [&_small]:[font-size:var(--vui-font-xs)] [&_small]:[line-height:1.32] [&_textarea]:[width:100%] [&_textarea]:min-w-0 [&_textarea]:[border:1px_solid_var(--border-soft)] [&_textarea]:[border-radius:var(--radius-control)] [&_textarea]:[background:var(--surface-panel)] [&_textarea]:[color:var(--fg-primary)] [&_textarea]:[font:inherit] [&_textarea]:[font-size:var(--vui-font-xs)] [&_textarea]:[min-height:62px] [&_textarea]:[resize:vertical] [&_textarea]:[padding:7px_9px] [&_textarea]:[line-height:1.35] [&_textarea]:focus:[outline:2px_solid_color-mix(in_srgb,_var(--accent-cool)_24%,_transparent)] [&_textarea]:focus:[border-color:color-mix(in_srgb,_var(--accent-cool)_48%,_transparent)]",
  createToolBundleGrid: "grid [grid-template-columns:repeat(2,_minmax(0,_1fr))] [gap:6px] min-w-0 [max-height:184px] [overflow:auto] [padding-right:3px] max-[860px]:[grid-template-columns:1fr]",
  createToolBundleOption: "grid [grid-template-columns:auto_minmax(0,_1fr)] [align-items:flex-start] [gap:7px] min-w-0 [padding:8px] [border:1px_solid_var(--border-soft)] [border-radius:8px] [background:color-mix(in_srgb,_var(--surface-panel)_78%,_transparent)] [&_input]:[margin-top:2px] [&_span]:grid [&_span]:[gap:2px] [&_span]:min-w-0 [&_strong]:min-w-0 [&_strong]:[overflow:hidden] [&_strong]:[text-overflow:ellipsis] [&_strong]:[color:var(--fg-primary)] [&_strong]:[font-size:var(--vui-font-xs)] [&_strong]:[white-space:nowrap]",
  createToolBundleSelected: "grid [grid-template-columns:auto_minmax(0,_1fr)] [align-items:flex-start] [gap:7px] min-w-0 [padding:8px] [border:1px_solid_var(--border-soft)] [border-radius:8px] [border-color:color-mix(in_srgb,_var(--accent-cool)_44%,_var(--border-soft))] [background:color-mix(in_srgb,_var(--accent-cool)_10%,_var(--surface-panel))] [&_input]:[margin-top:2px] [&_span]:grid [&_span]:[gap:2px] [&_span]:min-w-0 [&_strong]:min-w-0 [&_strong]:[overflow:hidden] [&_strong]:[text-overflow:ellipsis] [&_strong]:[color:var(--fg-primary)] [&_strong]:[font-size:var(--vui-font-xs)] [&_strong]:[white-space:nowrap]",
  createToolBundlePreview: "[padding:7px_8px] [border:1px_solid_var(--border-soft)] [border-radius:8px] [background:color-mix(in_srgb,_var(--surface-panel)_72%,_transparent)] [&_strong]:min-w-0 [&_strong]:[overflow:hidden] [&_strong]:[color:var(--fg-primary)] [&_strong]:[font-size:var(--vui-font-xs)] [&_strong]:[text-overflow:ellipsis] [&_strong]:[white-space:nowrap]",
  errorText: "[margin:0] [font-size:var(--vui-font-xs)] [line-height:1.4] [overflow-wrap:anywhere] [color:var(--state-error)]",
  successText: "[margin:0] [font-size:var(--vui-font-xs)] [line-height:1.4] [overflow-wrap:anywhere] [color:var(--state-success)]",
  editorActions: "flex [justify-content:flex-end] [gap:6px] min-w-0",
} as const;

export default styles;
