const styles = {
  detailHeader: "flex [align-items:flex-start] [justify-content:space-between] [gap:8px] min-w-0 [&_div]:min-w-0 [&_h2]:min-w-0 [&_h2]:[overflow:hidden] [&_h2]:[text-overflow:ellipsis] [&_h2]:[white-space:nowrap] [&_p]:[margin:4px_0_0] [&_p]:[color:var(--fg-secondary)] [&_p]:[font-size:var(--vui-font-xs)] [&_p]:[line-height:1.42] max-[860px]:[flex-wrap:wrap]",
  panelEyebrow: "[margin:0_0_1px] [color:var(--fg-tertiary)] [font-size:var(--vui-font-xs)] [letter-spacing:0.07em] [text-transform:uppercase]",
  agentRoleTag: "inline-flex [align-items:center] [justify-content:center] [border:1px_solid_var(--vui-border-subtle)] [border-radius:999px] [font-weight:700] [white-space:nowrap] [justify-self:start] [min-height:22px] [max-width:100%] [padding:0_7px] [font-size:var(--vui-font-xs)] [line-height:1] [overflow:hidden] [text-overflow:ellipsis]",
  agentRoleTag_chat: "[border-color:color-mix(in_srgb,_var(--accent-warm)_34%,_var(--vui-border-subtle))] [background:color-mix(in_srgb,_var(--accent-warm)_12%,_transparent)] [color:var(--accent-warm-2)]",
  agentRoleTag_general: "[border-color:color-mix(in_srgb,_var(--fg-tertiary)_24%,_var(--vui-border-subtle))] [background:color-mix(in_srgb,_var(--fg-tertiary)_8%,_transparent)] [color:var(--fg-secondary)]",
  agentRoleTag_memory: "[border-color:color-mix(in_srgb,_var(--fg-tertiary)_30%,_var(--vui-border-subtle))] [background:color-mix(in_srgb,_var(--fg-tertiary)_10%,_transparent)] [color:var(--fg-secondary)]",
  agentRoleTag_research: "[border-color:color-mix(in_srgb,_var(--accent-cool)_36%,_var(--vui-border-subtle))] [background:color-mix(in_srgb,_var(--accent-cool)_13%,_transparent)] [color:var(--accent-cool-2)]",
  agentRoleTag_self: "[border-color:color-mix(in_srgb,_var(--state-success)_34%,_var(--vui-border-subtle))] [background:color-mix(in_srgb,_var(--state-success)_12%,_transparent)] [color:var(--state-success)]",
  agentRoleTag_supervised: "[border-color:color-mix(in_srgb,_var(--state-warning)_36%,_var(--vui-border-subtle))] [background:color-mix(in_srgb,_var(--state-warning)_12%,_transparent)] [color:var(--state-warning)]",
  agentRoleTag_tool: "[border-color:color-mix(in_srgb,_var(--fg-tertiary)_30%,_var(--vui-border-subtle))] [background:color-mix(in_srgb,_var(--fg-tertiary)_10%,_transparent)] [color:var(--fg-secondary)]",
  detailHeaderActions: "flex [flex-direction:column] [align-items:flex-end] [gap:6px] min-w-0 [max-width:100%]",
  detailHealthStatus: "flex [align-items:center] [justify-items:start] min-w-0 [max-width:100%] [flex:0_1_auto] [justify-content:flex-end]",
  issuePill: "inline-flex [align-items:center] [justify-content:center] [min-height:26px] [max-width:100%] [padding:0_7px] [border:1px_solid_var(--vui-border-subtle)] [border-radius:999px] [font-size:var(--vui-font-xs)] [font-weight:700] [overflow:hidden] [text-overflow:ellipsis] [white-space:nowrap]",
  issue_blocking: "[border-color:color-mix(in_srgb,_var(--state-error)_34%,_transparent)] [background:color-mix(in_srgb,_var(--state-error)_10%,_transparent)] [color:var(--state-error)]",
  issue_info: "[border-color:color-mix(in_srgb,_var(--accent-cool)_28%,_transparent)] [background:color-mix(in_srgb,_var(--accent-cool)_8%,_transparent)] [color:var(--accent-cool)]",
  issue_ok: "[border-color:color-mix(in_srgb,_var(--state-success)_28%,_transparent)] [background:color-mix(in_srgb,_var(--state-success)_9%,_transparent)] [color:var(--state-success)]",
  issue_warning: "[border-color:color-mix(in_srgb,_var(--accent-warm)_30%,_transparent)] [background:color-mix(in_srgb,_var(--accent-warm)_10%,_transparent)] [color:var(--accent-warm-2)]",
  detailTabs: "grid [grid-template-columns:repeat(3,_minmax(0,_1fr))] [gap:4px] min-w-0 [padding:4px] [border:1px_solid_var(--vui-border-subtle)] [border-radius:var(--radius-control)] [background:color-mix(in_srgb,_var(--vui-surface-row)_58%,_transparent)] max-[860px]:[grid-template-columns:1fr]",
  detailTab: "grid w-full [justify-items:center] [gap:2px] min-w-0 [min-height:30px] [padding:5px_4px] [border:1px_solid_transparent] [border-radius:var(--radius-control)] [background:transparent] [color:var(--fg-tertiary)] [&_span]:[max-width:100%] [&_span]:[overflow:hidden] [&_span]:[font-size:var(--vui-font-xs)] [&_span]:[font-weight:700] [&_span]:[text-overflow:ellipsis] [&_span]:[white-space:nowrap] [&_strong]:[color:var(--fg-secondary)] [&_strong]:[font-size:var(--vui-font-xs)] hover:[background:var(--vui-surface-row-hover)] hover:[color:var(--fg-secondary)]",
  detailTabActive: "grid w-full [justify-items:center] [gap:2px] min-w-0 [min-height:30px] [padding:5px_4px] [border:1px_solid_transparent] [border-radius:var(--radius-control)] [&_span]:[max-width:100%] [&_span]:[overflow:hidden] [&_span]:[font-size:var(--vui-font-xs)] [&_span]:[font-weight:700] [&_span]:[text-overflow:ellipsis] [&_span]:[white-space:nowrap] [&_strong]:[font-size:var(--vui-font-xs)] [border-color:color-mix(in_srgb,_var(--accent-cool)_30%,_transparent)] [background:color-mix(in_srgb,_var(--accent-cool)_10%,_transparent)] [color:var(--accent-cool)] [&_strong]:[color:var(--accent-cool)]",
} as const;

export default styles;
