const styles = {
  factGrid: "grid [grid-template-columns:repeat(2,_minmax(0,_1fr))] min-[1540px]:[grid-template-columns:repeat(3,_minmax(0,_1fr))] [gap:6px] [&_section]:min-w-0 [&_section]:[border:1px_solid_color-mix(in_srgb,_var(--vui-border-subtle)_76%,_transparent)] [&_section]:[border-radius:var(--radius-control)] [&_section]:[background:color-mix(in_srgb,_var(--vui-surface-row)_58%,_transparent)] [&_section]:grid [&_section]:[grid-template-columns:18px_minmax(0,_1fr)] [&_section]:[grid-template-rows:auto_auto] [&_section]:[align-items:center] [&_section]:[column-gap:8px] [&_section]:[row-gap:2px] [&_section]:[padding:8px_9px_9px] [&_svg]:[grid-column:1] [&_svg]:[grid-row:1_/_span_2] [&_svg]:[width:16px] [&_svg]:[height:16px] [&_svg]:[align-self:center] [&_svg]:[color:var(--accent-cool)] [&_span]:[grid-column:2] [&_span]:[grid-row:1] [&_span]:block [&_span]:min-w-0 [&_span]:[overflow-wrap:anywhere] [&_span]:[text-overflow:ellipsis] [&_span]:[color:var(--fg-tertiary)] [&_span]:[font-size:var(--vui-font-xs)] [&_strong]:[grid-column:2] [&_strong]:[grid-row:2] [&_strong]:block [&_strong]:min-w-0 [&_strong]:[overflow-wrap:anywhere] [&_strong]:[text-overflow:ellipsis] [&_strong]:[color:var(--fg-primary)] [&_strong]:[font-size:var(--vui-font-xs)] max-[860px]:[grid-template-columns:1fr]",
  detailSection: "min-w-0 [border:1px_solid_color-mix(in_srgb,_var(--vui-border-subtle)_76%,_transparent)] [border-radius:var(--radius-panel)] [background:color-mix(in_srgb,_var(--vui-surface-panel)_58%,_transparent)] [&_svg]:[grid-area:icon] [&_svg]:[color:var(--accent-cool)] grid [gap:8px] [padding:10px]",
  panelHeader: "flex [align-items:flex-start] [justify-content:space-between] [gap:8px] min-w-0 [&_div]:min-w-0",
  panelEyebrow: "[margin:0_0_1px] [color:var(--fg-tertiary)] [font-size:var(--vui-font-xs)] [letter-spacing:0.07em] [text-transform:uppercase]",
  boundarySummaryGrid: "grid [align-content:start] [gap:5px] min-w-0 [grid-template-columns:repeat(3,_minmax(0,_1fr))] [&_span]:grid [&_span]:[gap:2px] [&_span]:min-w-0 [&_span]:[padding:7px_8px] [&_span]:[border:1px_solid_color-mix(in_srgb,_var(--vui-border-subtle)_76%,_transparent)] [&_span]:[border-radius:var(--radius-control)] [&_span]:[background:color-mix(in_srgb,_var(--vui-surface-row)_58%,_transparent)] [&_strong]:min-w-0 [&_strong]:[overflow-wrap:anywhere] [&_small]:min-w-0 [&_small]:[overflow-wrap:anywhere] [&_strong]:[color:var(--fg-primary)] [&_strong]:[font-size:var(--vui-font-xs)] [&_small]:[color:var(--fg-tertiary)] [&_small]:[font-size:var(--vui-font-xs)] max-[860px]:[grid-template-columns:1fr]",
  pillList: "[&_span]:inline-flex [&_span]:[align-items:center] [&_span]:[min-height:22px] [&_span]:[padding:0_6px] [&_span]:[border:1px_solid_color-mix(in_srgb,_var(--accent-cool)_22%,_transparent)] [&_span]:[border-radius:999px] [&_span]:[background:color-mix(in_srgb,_var(--accent-cool)_8%,_transparent)] [&_span]:[color:var(--accent-cool)] [&_span]:[font-style:normal] [&_span]:[font-size:var(--vui-font-xs)] [&_span]:[white-space:nowrap] [align-content:start] [gap:5px] min-w-0 flex [flex-wrap:wrap]",
  policyGrid: "grid [grid-template-columns:repeat(2,_minmax(0,_1fr))] min-[1540px]:[grid-template-columns:repeat(4,_minmax(0,_1fr))] [gap:6px] [&_div]:min-w-0 [&_div]:[border:1px_solid_color-mix(in_srgb,_var(--vui-border-subtle)_76%,_transparent)] [&_div]:[border-radius:var(--radius-control)] [&_div]:[background:color-mix(in_srgb,_var(--vui-surface-row)_58%,_transparent)] [&_div]:grid [&_div]:[grid-template-columns:auto_minmax(0,_1fr)] [&_div]:[grid-template-rows:auto_auto] [&_div]:[column-gap:8px] [&_div]:[row-gap:2px] [&_div]:[padding:8px_9px_9px] [&_svg]:[grid-column:1] [&_svg]:[grid-row:1_/_3] [&_svg]:[color:var(--accent-cool)] [&_span]:[grid-column:2] [&_span]:[grid-row:1] [&_span]:min-w-0 [&_span]:[overflow-wrap:anywhere] [&_span]:[color:var(--fg-tertiary)] [&_span]:[font-size:var(--vui-font-xs)] [&_strong]:[grid-column:2] [&_strong]:[grid-row:2] [&_strong]:min-w-0 [&_strong]:[overflow-wrap:anywhere] [&_strong]:[color:var(--fg-primary)] [&_strong]:[font-size:var(--vui-font-xs)] max-[860px]:[grid-template-columns:1fr]",
  technicalDetails: "min-w-0 border border-[color-mix(in_srgb,var(--vui-border-subtle)_76%,transparent)] rounded-[var(--radius-control)] bg-[color-mix(in_srgb,var(--vui-surface-row)_42%,transparent)] [&_summary]:grid [&_summary]:grid-cols-[auto_auto_minmax(0,1fr)_auto] [&_summary]:items-center [&_summary]:gap-2 [&_summary]:min-h-[36px] [&_summary]:px-2.5 [&_summary]:cursor-pointer [&_summary]:list-none [&_summary::-webkit-details-marker]:hidden [&_summary_svg]:text-[var(--accent-cool)] [&_summary_span]:font-bold [&_summary_span]:text-[var(--fg-primary)] [&_summary_[data-vui=contextual-hint]]:justify-self-end [&[open]_summary]:border-b [&[open]_summary]:border-[var(--vui-border-hairline)]",
  technicalContent: "grid gap-2 p-2.5",
} as const;

export default styles;
