const styles = {
  root: "relative grid min-w-0 gap-1.5",
  trigger: "!flex !min-h-9 !w-full !justify-between !rounded-[10px] !border !border-[var(--vui-border-subtle)] !bg-[var(--vui-surface-panel)] !px-2.5 !text-left !shadow-none hover:!bg-[var(--vui-control-muted)] [&_[data-slot=vui-button-content]]:!w-full [&_[data-slot=vui-button-content]]:!justify-between",
  triggerCopy: "flex min-w-0 flex-1 items-center gap-2",
  triggerLabel: "min-w-0 flex-1 truncate text-[var(--vui-font-sm)] text-[var(--fg-primary)]",
  triggerMeta: "shrink-0 text-[var(--vui-font-xs)] font-normal text-[var(--fg-tertiary)]",
  panel: "absolute left-0 top-[calc(100%+6px)] z-[80] grid w-[min(620px,calc(100vw-40px))] max-w-[calc(100vw-40px)] gap-2 rounded-[14px] border border-[var(--vui-border-subtle)] bg-[var(--vui-surface-panel)] p-2 shadow-[var(--vui-shadow-soft)]",
  panelHeader: "flex items-start justify-between gap-3 px-1 pt-0.5",
  panelTitle: "grid min-w-0 gap-0.5",
  panelTitleText: "text-[var(--vui-font-sm)] font-semibold text-[var(--fg-primary)]",
  panelHint: "text-[var(--vui-font-xs)] leading-5 text-[var(--fg-tertiary)]",
  search: "w-full",
  list: "grid max-h-[min(460px,58vh)] min-w-0 gap-2 overflow-y-auto overflow-x-hidden pr-0.5",
  group: "grid min-w-0 gap-1",
  groupHeader: "sticky top-0 z-[1] flex min-w-0 items-center justify-between gap-2 bg-[var(--vui-surface-panel)] px-1 py-1 text-[var(--vui-font-xs)] font-semibold text-[var(--fg-secondary)]",
  groupCount: "font-normal text-[var(--fg-tertiary)]",
  option: "!grid !min-h-[58px] !w-full !min-w-0 !grid-cols-[minmax(0,1fr)_auto] !items-center !gap-3 !rounded-[10px] !border !border-transparent !bg-transparent !px-2.5 !py-2 !text-left !shadow-none hover:!border-[var(--vui-border-subtle)] hover:!bg-[var(--vui-control-muted)] focus-visible:!border-[var(--accent-cool)] [&_[data-slot=vui-button-content]]:contents",
  optionSelected: "!border-[color-mix(in_srgb,var(--accent-cool)_42%,transparent)] !bg-[color-mix(in_srgb,var(--accent-cool)_8%,transparent)]",
  optionDisabled: "opacity-60",
  optionCopy: "grid min-w-0 gap-1",
  optionTitle: "flex min-w-0 flex-wrap items-center gap-1.5 text-[var(--vui-font-sm)] font-semibold text-[var(--fg-primary)]",
  optionIdentity: "min-w-0 break-all text-[var(--vui-font-xs)] leading-5 text-[var(--fg-tertiary)]",
  optionMeta: "flex min-w-0 flex-wrap items-center gap-x-2 gap-y-1 text-[var(--vui-font-xs)] text-[var(--fg-secondary)]",
  action: "shrink-0 text-right text-[var(--vui-font-xs)] font-semibold text-[var(--fg-secondary)]",
  badge: "rounded-full border border-[var(--vui-border-subtle)] px-1.5 py-0.5 text-[10px] font-medium text-[var(--fg-secondary)]",
  reason: "col-span-2 min-w-0 break-words text-[var(--vui-font-xs)] leading-5 text-[var(--status-warning-fg)]",
  check: "shrink-0 text-[var(--accent-cool)]",
  empty: "px-3 py-8 text-center text-[var(--vui-font-xs)] text-[var(--fg-tertiary)]",
};

export default styles;
