const styles = {
  contextualHintRow: "inline-flex [align-items:center] [gap:6px]",
  managementBriefHeader: "grid [grid-template-columns:minmax(0,_1fr)_auto] [align-items:center] [gap:10px] min-w-0 [&_div]:grid [&_div]:[gap:2px] [&_div]:min-w-0 [&_span]:min-w-0 [&_span]:[overflow:hidden] [&_span]:[text-overflow:ellipsis] [&_span]:[white-space:nowrap] [&_span]:[color:var(--fg-tertiary)] [&_span]:[font-size:var(--vui-font-xs)] [&_strong]:inline-flex [&_strong]:[align-items:center] [&_strong]:[justify-content:center] [&_strong]:[width:42px] [&_strong]:[min-height:28px] [&_strong]:[border:1px_solid_color-mix(in_srgb,_var(--accent-cool)_30%,_transparent)] [&_strong]:[border-radius:var(--radius-control)] [&_strong]:[background:color-mix(in_srgb,_var(--accent-cool)_10%,_transparent)] [&_strong]:[color:var(--accent-cool)] [&_strong]:[font-size:0.9rem]",
  managementBriefPanel: "grid [gap:7px] min-w-0 [padding:9px] [border:1px_solid_color-mix(in_srgb,_var(--accent-cool)_24%,_var(--vui-border-subtle))] [border-radius:var(--radius-panel)] [background:color-mix(in_srgb,_var(--accent-cool)_5%,_transparent)]",
  managementChecklist: "flex [flex-wrap:wrap] [align-items:center] [gap:5px] min-w-0 [&_button]:inline-flex [&_button]:[align-items:center] [&_button]:[justify-content:center] [&_button]:[gap:5px] [&_button]:min-w-[104px] [&_button]:[min-height:30px] [&_button]:[padding:4px_9px] [&_button]:[border:1px_solid_var(--vui-border-subtle)] [&_button]:[border-radius:var(--radius-control)] [&_button]:[background:var(--vui-surface-row)] [&_button]:[color:var(--fg-secondary)] [&_svg]:[flex:0_0_auto] [&_span]:min-w-0 [&_span]:[overflow:hidden] [&_span]:[font-size:var(--vui-font-xs)] [&_span]:[font-weight:720] [&_span]:[text-overflow:ellipsis] [&_span]:[white-space:nowrap] [&_button]:hover:[background:var(--vui-surface-row-hover)]",
  managementChecklistDone: "[&_svg]:[color:var(--state-success)]",
  managementChecklistMissing: "[&_svg]:[color:var(--accent-warm)]",
  nextActionList: "grid [justify-items:start] [align-items:start] [gap:5px] min-w-0 [&_span]:inline-flex [&_span]:[align-items:center] [&_span]:[color:var(--fg-tertiary)] [&_span]:[font-size:var(--vui-font-xs)] [&_span]:[font-weight:760] [&_span]:[white-space:nowrap] [&_button]:grid [&_button]:[gap:2px] [&_button]:min-w-[140px] [&_button]:[max-width:100%] [&_button]:[margin:0] [&_button]:[padding:7px_10px] [&_button]:[border:1px_solid_var(--vui-border-subtle)] [&_button]:[border-radius:var(--radius-control)] [&_button]:[background:color-mix(in_srgb,_var(--vui-surface-row)_78%,_transparent)] [&_button]:[color:var(--fg-secondary)] [&_button]:[text-align:left] [&_p]:grid [&_p]:[gap:2px] [&_p]:[margin:0] [&_p]:[padding:6px_7px] [&_p]:[border:1px_solid_var(--vui-border-subtle)] [&_p]:[border-radius:var(--radius-control)] [&_p]:[background:color-mix(in_srgb,_var(--vui-surface-row)_78%,_transparent)] [&_p]:[text-align:left] [&_strong]:min-w-0 [&_strong]:[overflow:hidden] [&_strong]:[text-overflow:ellipsis] [&_strong]:[white-space:nowrap] [&_small]:min-w-0 [&_small]:[overflow:hidden] [&_small]:[text-overflow:ellipsis] [&_small]:[white-space:nowrap] [&_p]:min-w-0 [&_p]:[overflow:hidden] [&_p]:[text-overflow:ellipsis] [&_p]:[white-space:nowrap] [&_strong]:[color:var(--fg-primary)] [&_strong]:[font-size:var(--vui-font-xs)] [&_small]:[color:var(--fg-tertiary)] [&_small]:[font-size:var(--vui-font-xs)] [&_p]:[color:var(--fg-tertiary)] [&_p]:[font-size:var(--vui-font-xs)]",
  panelEyebrow: "[margin:0_0_1px] [color:var(--fg-tertiary)] [font-size:var(--vui-font-xs)] [letter-spacing:0.07em] [text-transform:uppercase]",
  nextActionButton: "w-fit max-w-full",
} as const;

export default styles;
