import { createVuiStyleMap } from "../components/vui/styles/createVuiStyleMap";

const styleKeys = [
  "activeSkillEyebrow",
  "activeSkillIdentity",
  "activeSkillMeta",
  "activeSkillState",
  "activeSkillStatus",
  "activeSkillStatus_active",
  "activeSkillStatus_missing",
  "activeSkillStatus_stale",
  "agentAvatarImage",
  "agentIndexAvatar",
  "agentIndexCard",
  "agentIndexCopy",
  "agentIndexDetails",
  "agentIndexEmptyState",
  "agentIndexExpandButton",
  "agentIndexHeader",
  "agentIndexList",
  "agentIndexMentalBlock",
  "agentIndexNameLine",
  "agentIndexOpenButton",
  "agentIndexRoster",
  "agentIndexStatus",
  "agentIndexWarning",
  "agentMention",
  "agentMissingInline",
  "agentMissingLine",
  "agentMissingNotice",
  "agentModelLine",
  "agentModelTag",
  "agentModelTitleTag",
  "agentOptionAvatar",
  "agentOptionMeta",
  "agentRoleTag",
  "agentRoleTag_chat",
  "agentRoleTag_general",
  "agentRoleTag_memory",
  "agentRoleTag_research",
  "agentRoleTag_self",
  "agentRoleTag_supervised",
  "agentRoleTag_tool",
  "agentSessionTab",
  "agentSessionTabActive",
  "agentSessionTabChild",
  "agentSessionTabCli",
  "agentSessionTabClosable",
  "agentSessionTabCloseButton",
  "agentSessionTabCopy",
  "agentSessionTabCopyCompact",
  "agentSessionTabEditActions",
  "agentSessionTabEditButton",
  "agentSessionTabEditing",
  "agentSessionTabGroup",
  "agentSessionTabIcon",
  "agentSessionTabKicker",
  "agentSessionTabMainAction",
  "agentSessionTabMeta",
  "agentSessionTabRoot",
  "agentSessionTabTitle",
  "agentSessionTabTitleInput",
  "backendHealthRow",
  "backendLabel",
  "backendNote",
  "backendPill",
  "backendPill_checking",
  "backendPill_healthy",
  "backendPill_offline",
  "backendPill_unhealthy",
  "backendPillDot",
  "blockEyebrow",
  "cacheDetailBody",
  "cacheDetailBoundary",
  "cacheDetailBoundaryHit",
  "cacheDetailBoundaryLabels",
  "cacheDetailBoundaryMiss",
  "cacheDetailBoundaryTrack",
  "cacheDetailBoundaryUnknown",
  "cacheDetailCalibrationNote",
  "cacheDetailCloseButton",
  "cacheDetailDialog",
  "cacheDetailDonutCenter",
  "cacheDetailDonutLegend",
  "cacheDetailDonutPanel",
  "cacheDetailDonutShell",
  "cacheDetailDonutSvg",
  "cacheDetailEmpty",
  "cacheDetailHeader",
  "cacheDetailOverlay",
  "cacheDetailSegmentGroup",
  "cacheDetailSegmentHeader",
  "cacheDetailSegmentList",
  "cacheDetailSegmentMeta",
  "cacheDetailSegmentRow",
  "cacheDetailSegmentSource",
  "cacheDetailSegmentText",
  "cacheDetailSummaryGrid",
  "cacheDetailSwatch",
  "cacheDonutCenter",
  "cacheDonutInnerSegment",
  "cacheDonutInnerTrack",
  "cacheDonutOuterSegment",
  "cacheDonutOuterTrack",
  "cacheDonutPanel",
  "cacheDonutSegment",
  "cacheDonutSegmentAgent",
  "cacheDonutSegmentAttachments",
  "cacheDonutSegmentCached",
  "cacheDonutSegmentCacheWrite",
  "cacheDonutSegmentGuidance",
  "cacheDonutSegmentHistory",
  "cacheDonutSegmentMissing",
  "cacheDonutSegmentOther",
  "cacheDonutSegmentProjectRules",
  "cacheDonutSegmentProviderUnmapped",
  "cacheDonutSegmentSkill",
  "cacheDonutSegmentSystem",
  "cacheDonutSegmentTask",
  "cacheDonutSegmentToolDescriptions",
  "cacheDonutSegmentToolSchema",
  "cacheDonutSegmentUncached",
  "cacheDonutSegmentUser",
  "cacheDonutShell",
  "cacheDonutStats",
  "cacheDonutSvg",
  "cacheDonutTrack",
  "cacheDonutTrigger",
  "cacheStatusCard",
  "centerPane",
  "centerSurface",
  "chatReturnLink",
  "childTopLevelSessionItem",
  "cliAgentRunPanel",
  "cliAgentRunPanelHidden",
  "cliAgentTerminalAction",
  "cliAgentTerminalCommand",
  "cliAgentTerminalFrame",
  "cliAgentTerminalOutput",
  "cliAgentTerminalOutputShell",
  "cliAgentTerminalOverlay",
  "cliAgentTerminalStatus",
  "compactDetails",
  "compactDetailsClosedLabel",
  "compactDetailsOpenLabel",
  "companionBlock",
  "companionCompact",
  "companionCopy",
  "companionTopLine",
  "compressionFact",
  "compressionFactGrid",
  "compressionFactWide",
  "compressionStatusCard",
  "compressionStrategyCard",
  "compressionStrategyList",
  "compressionStrategyRow",
  "contextCompositionBar",
  "contextCompositionHeader",
  "contextCompositionItem",
  "contextCompositionLegend",
  "contextCompositionPanel",
  "contextCompositionSegment",
  "contextCompositionSegmentAgent",
  "contextCompositionSegmentAttachments",
  "contextCompositionSegmentCached",
  "contextCompositionSegmentCacheWrite",
  "contextCompositionSegmentExact",
  "contextCompositionSegmentGuidance",
  "contextCompositionSegmentHistory",
  "contextCompositionSegmentMissing",
  "contextCompositionSegmentOther",
  "contextCompositionSegmentProjectRules",
  "contextCompositionSegmentProviderUnmapped",
  "contextCompositionSegmentSkill",
  "contextCompositionSegmentSystem",
  "contextCompositionSegmentTask",
  "contextCompositionSegmentToolDescriptions",
  "contextCompositionSegmentToolSchema",
  "contextCompositionSegmentUncached",
  "contextCompositionSegmentUnused",
  "contextCompositionSegmentUser",
  "contextLineCompact",
  "contextStatusCard",
  "contextUsageValue",
  "conversationAvatar",
  "conversationAvatarDirect",
  "conversationAvatarGroup",
  "conversationCopy",
  "conversationFrame",
  "conversationFrameFocus",
  "conversationGroup",
  "conversationGroupHeader",
  "conversationGroupList",
  "conversationKindBadge",
  "conversationKindBadgeChild",
  "conversationKindBadgeDirect",
  "conversationKindBadgeGroup",
  "conversationMetaMain",
  "conversationMetaRow",
  "conversationMetaTime",
  "conversationTitleMain",
  "conversationTitleRow",
  "conversationTreeRootHeader",
  "createGroupButton",
  "currentSessionBlock",
  "currentSessionLine",
  "currentSessionMetaList",
  "detailNote",
  "directSessionItem",
  "emptyConversationSurface",
  "emptySurface",
  "featureChip",
  "featureChipActive",
  "featureChipPrimary",
  "featureChipRow",
  "featurePresetBlock",
  "featurePresetNote",
  "featurePresetScope",
  "featurePrimarySlot",
  "featureToggle",
  "featureToggleActive",
  "featureTogglePrimary",
  "featureToggleState",
  "featureToggleText",
  "fileTab",
  "fileTabActive",
  "fileTabButton",
  "fileTabClose",
  "groupAgentOption",
  "groupAgentOptionSelected",
  "groupAgentPicker",
  "groupApplyButton",
  "groupBubble",
  "groupBubbleAvatar",
  "groupBubbleBody",
  "groupBubbleBodyCollapsed",
  "groupBubbleHeader",
  "groupBubbleMeta",
  "groupBubbleRow",
  "groupBubbleRowFailed",
  "groupBubbleRowPending",
  "groupBubbleToggle",
  "groupComposerBar",
  "groupComposerEmpty",
  "groupComposerField",
  "groupComposerInput",
  "groupComposerPanel",
  "groupConversationFrame",
  "groupConversationHeader",
  "groupDeleteButton",
  "groupEmptyState",
  "groupManagementActions",
  "groupManagementControls",
  "groupManagementCount",
  "groupManagementHeader",
  "groupManagementHint",
  "groupManagementPanel",
  "groupMemberChip",
  "groupMemberChipSelected",
  "groupMemberCopy",
  "groupMemberPicker",
  "groupMessageCard",
  "groupMessageCardFailed",
  "groupMessageList",
  "groupMessageTimeline",
  "groupModeSelect",
  "groupProfileBlock",
  "groupRefreshButton",
  "groupRoundBlock",
  "groupRoundDivider",
  "groupRoundSummary",
  "groupSessionItem",
  "groupStopButton",
  "groupTitleField",
  "groupTopicBubble",
  "groupTopicMessage",
  "groupTypingDots",
  "inlineMetaList",
  "inlineMetaPill",
  "inlineNotice",
  "inlineStat",
  "inlineStatGrid",
  "kernelTraceLink",
  "layout",
  "layoutCenterFirst",
  "leftBlock",
  "leftRail",
  "memberIndexSummary",
  "mentalStateBadge",
  "mentalStateBadge_disoriented",
  "mentalStateBadge_looping",
  "mentalStateBadge_normal",
  "mentalStateBadge_productive",
  "mentalStateBadge_thrashing",
  "mentalStateBadge_tunnel_vision",
  "mentalStateBadge_unknown",
  "metricValue",
  "newGroupButton",
  "newSessionButton",
  "oneLineValue",
  "paneCollapsed",
  "panelBody",
  "panelNotice",
  "panelSearch",
  "panelSearchInput",
  "panelState",
  "petMiniAvatar",
  "petShowcase",
  "petShowcaseAction",
  "petShowcaseActionHint",
  "petShowcaseActions",
  "petShowcaseAura",
  "petShowcaseAvatar",
  "petShowcaseAvatar_bunny",
  "petShowcaseAvatar_cat",
  "petShowcaseAvatar_chick",
  "petShowcaseAvatar_crab",
  "petShowcaseAvatar_default",
  "petShowcaseAvatar_lobster",
  "petShowcaseAvatar_moose",
  "petShowcaseAvatar_penguin",
  "petShowcaseAvatar_shrimp",
  "petShowcaseAvatar_slime",
  "petShowcaseEarLeft",
  "petShowcaseEarRight",
  "petShowcaseEye",
  "petShowcaseFace",
  "petShowcaseFeedback",
  "petShowcaseFootLeft",
  "petShowcaseFootRight",
  "petShowcaseInfo",
  "petShowcaseLine",
  "petShowcaseMuzzle",
  "petShowcaseName",
  "petShowcaseStage",
  "petShowcaseSymbol",
  "petShowcaseTop",
  "progressFillCool",
  "progressFillWarm",
  "progressTrack",
  "projectBusEvent",
  "projectBusEventActions",
  "projectBusEventBody",
  "projectBusEventHeader",
  "projectBusEventMeta",
  "projectBusEventRevoked",
  "projectBusInterruptToggle",
  "resizeHandle",
  "resizeHandleActive",
  "resourceBlock",
  "resourceMetric",
  "resourceSplit",
  "rightIndexTab",
  "rightIndexTabActive",
  "rightIndexTabs",
  "rightPane",
  "runModeBlock",
  "runtimeNotice",
  "runtimeNotice_error",
  "runtimeNotice_success",
  "runtimeNotice_warning",
  "runtimeNoticeBody",
  "runtimeNoticeLabel",
  "runtimeNoticeMessage",
  "runtimeNoticeStack",
  "sectionHeader",
  "sectionIdentity",
  "sectionMetaLine",
  "sectionTitle",
  "sessionActionRow",
  "sessionActionStack",
  "sessionAgentLine",
  "sessionBindingNotice",
  "sessionContextMenu",
  "sessionContextMenuDanger",
  "sessionContextMenuItem",
  "sessionCurrentBadge",
  "sessionCurrentIndicator",
  "sessionDeleteButton",
  "sessionDiagnosticsBody",
  "sessionDiagnosticsDetails",
  "sessionDiagnosticsSnapshot",
  "sessionDiagnosticsSummary",
  "sessionDiagnosticsSummaryText",
  "sessionIconButton",
  "sessionItem",
  "sessionItemActive",
  "sessionItemError",
  "sessionItemIdentity",
  "sessionItemMain",
  "sessionItemMeta",
  "sessionItemNotice",
  "sessionItemSummary",
  "sessionItemTitle",
  "sessionItemTop",
  "sessionLoadMoreButton",
  "sessionLoadMoreStatus",
  "sessionResourceDiagnostics",
  "sessionRunningBadge",
  "sessionState",
  "sessionStatePill",
  "sessionStatePill_answering",
  "sessionStatePill_blocked",
  "sessionStatePill_editing",
  "sessionStatePill_failed",
  "sessionStatePill_idle",
  "sessionStatePill_needs_input",
  "sessionStatePill_planning",
  "sessionStatePill_reading",
  "sessionStatePill_ready",
  "sessionStatePill_running",
  "sessionStatePill_success",
  "sessionStatePill_thinking",
  "sessionStatePill_tooling",
  "sessionStatePill_verifying",
  "sessionStatePill_waiting",
  "sessionStatusCluster",
  "sessionTitleInput",
  "sessionUnreadBadge",
  "systemEntryButton",
  "systemEntryButtonActive",
  "systemEntryCopy",
  "systemEntryGroup",
  "systemEntryIcon",
  "systemEntryMeta",
  "systemEntryTitle",
  "systemEntryTitleRow",
  "tab",
  "tabActive",
  "tabStrip",
  "teamTreeChild",
  "teamTreeChildren",
  "teamTreeGroup",
  "teamTreeItem",
  "teamTreeLabelRow",
  "tokenCompressionCard",
  "tokenStatusBar",
  "tokenStatusCopy",
  "tokenStatusLabel",
  "tokenStatusMeta",
  "tokenStatusMetric",
  "tokenStatusMetric_cache",
  "tokenStatusMetric_compression",
  "tokenStatusMetric_modelInput",
  "tokenStatusMetricButton",
  "tokenStatusRing",
  "tokenStatusRingCore",
  "tokenStatusVisualGrid",
  "toolApprovalActions",
  "toolApprovalAllow",
  "toolApprovalBody",
  "toolApprovalDialog",
  "toolApprovalHeader",
  "toolApprovalIcon",
  "toolApprovalOverlay",
  "toolApprovalToolList",
  "vitalItemCompact",
  "vitalLabelRow",
  "vitalStackCompact",
] as const;

const styles = createVuiStyleMap(styleKeys, {
  baseClassName: "vui-routes-chatcodingroute",
  extensions: {
    activeSkillStatus: "!grid grid-cols-[minmax(0,1fr)_auto] items-center gap-2",
    agentIndexHeader: "!grid grid-cols-[18px_minmax(0,1fr)_auto] items-center gap-[7px]",
    agentIndexOpenButton: "!grid grid-cols-[30px_minmax(0,1fr)] items-center gap-[7px]",
    centerPane:
      "grid h-full min-h-0 grid-rows-[auto_minmax(0,1fr)] overflow-hidden bg-[color-mix(in_srgb,var(--surface-page)_10%,transparent)]",
    centerSurface:
      "grid h-full min-h-0 overflow-hidden bg-[color-mix(in_srgb,var(--surface-panel-strong)_6%,transparent)]",
    cacheDetailBody: "max-h-[min(620px,calc(100dvh_-_238px))] overflow-auto [scrollbar-gutter:stable]",
    cacheDetailBoundaryTrack: "[&_span+span]:border-l [&_span+span]:border-[var(--vui-border-subtle)]",
    cacheDetailCalibrationNote: "!grid grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-[7px]",
    cacheDetailDialog: "w-[min(1120px,calc(100vw_-_44px))] max-h-[min(860px,calc(100dvh_-_52px))]",
    cacheDonutSegmentToolDescriptions: "stroke-[var(--accent-warm)]",
    cacheDonutSegmentToolSchema: "stroke-[var(--accent-warm)]",
    chatReturnLink: "[&_span]:truncate",
    cliAgentRunPanelHidden: "hidden",
    cliAgentTerminalCommand: "!grid grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-2",
    cliAgentTerminalOutputShell: "bg-[var(--bg-canvas)]",
    conversationFrameFocus: "justify-self-center w-[min(calc(100%_-_48px),1480px)] max-w-full max-[980px]:w-full",
    conversationMetaRow: "grid grid-cols-[minmax(0,1fr)_max-content] [&_time]:flex-none [&_time]:overflow-visible [&_time]:text-clip",
    conversationMetaTime: "max-w-[min(164px,68%)] [&_time]:flex-none [&_time]:overflow-visible [&_time]:text-clip",
    conversationTitleRow: "grid grid-cols-[minmax(0,1fr)_fit-content(92px)] max-w-full",
    conversationTreeRootHeader: "!grid grid-cols-[minmax(0,1fr)_auto] items-center gap-[7px]",
    emptyConversationSurface:
      "grid min-h-[74px] w-[min(360px,calc(100%_-_32px))] place-self-center place-items-center rounded-[var(--radius-panel)] border border-dashed border-[var(--vui-border-subtle)] bg-[color-mix(in_srgb,var(--vui-surface-row)_58%,transparent)] px-4 py-3 text-center text-[var(--vui-font-sm)] font-semibold leading-tight text-[var(--fg-secondary)] shadow-[var(--vui-shadow-hairline)]",
    emptySurface:
      "grid h-full min-h-[min(420px,calc(100dvh_-_190px))] place-items-center px-4 py-8 text-center text-[var(--fg-secondary)]",
    featureChip:
      "relative !grid !w-full grid-cols-[auto_minmax(0,1fr)] justify-start gap-1.5 px-1.5 [&_[data-slot=vui-button-content]]:min-w-0 [&_[data-slot=vui-button-content]]:max-w-full [&_[data-slot=vui-button-content]]:!w-full [&_[data-slot=vui-button-label]]:grid [&_[data-slot=vui-button-label]]:min-w-0 [&_[data-slot=vui-button-label]]:w-full [&_[data-slot=vui-button-label]]:grid-cols-[minmax(0,1fr)_auto] [&_[data-slot=vui-button-label]]:items-center [&_[data-slot=vui-button-label]]:gap-1 before:content-[''] before:h-1.5 before:w-1.5 before:shrink-0 before:rounded-full before:bg-[var(--fg-tertiary)] [&_em]:shrink-0 [&_em]:not-italic [&_strong]:min-w-0 [&_strong]:truncate [&_strong]:whitespace-nowrap",
    featureChipActive:
      "border-[color-mix(in_srgb,var(--accent-cool)_38%,var(--vui-border-subtle))] text-[var(--fg-primary)] before:bg-[var(--accent-cool)]",
    featureChipPrimary:
      "border-[color-mix(in_srgb,var(--accent-warm)_32%,var(--vui-border-subtle))] before:bg-[var(--accent-warm-2)]",
    featureChipRow: "!grid grid-cols-2 gap-1.5 overflow-visible rounded-none border-0 bg-transparent p-0",
    groupAgentOption: "!grid grid-cols-[auto_28px_minmax(0,1fr)] items-center gap-1.5",
    groupBubbleRow: "!grid grid-cols-[30px_minmax(0,1fr)] items-start gap-[7px]",
    groupComposerBar: "!grid grid-cols-[minmax(0,1fr)_auto_auto] gap-2.5",
    groupManagementActions: "!grid grid-cols-[repeat(2,minmax(0,1fr))] gap-[7px]",
    groupManagementControls: "!grid grid-cols-[minmax(0,1fr)_auto] items-start gap-[9px]",
    groupMemberChip: "!grid grid-cols-[auto_26px_minmax(0,1fr)_auto] items-center gap-1.5",
    inlineMetaList: "!grid grid-cols-[minmax(0,1fr)] gap-[3px]",
    inlineMetaPill:
      "!grid grid-cols-[minmax(58px,0.42fr)_minmax(0,1fr)] items-baseline gap-1.5 [&_strong]:truncate [&_strong]:whitespace-nowrap",
    inlineStat: "!grid grid-cols-[minmax(0,0.8fr)_minmax(0,1.2fr)] items-baseline gap-0.5",
    inlineStatGrid: "!grid grid-cols-[1fr] gap-[5px]",
    layout:
      "h-[calc(100dvh_-_var(--shell-topbar-height))] max-h-[calc(100dvh_-_var(--shell-topbar-height))] overflow-hidden grid-cols-[var(--chat-left-pane-width,220px)_8px_minmax(0,1fr)_8px_var(--chat-right-pane-width,284px)] max-[1100px]:grid-cols-[var(--chat-left-pane-width,220px)_8px_minmax(0,1fr)_8px_var(--chat-right-pane-width,284px)]",
    layoutCenterFirst:
      "!grid-cols-[minmax(0,var(--chat-left-pane-width,0px))_8px_minmax(520px,1fr)_8px_minmax(0,var(--chat-right-pane-width,0px))] max-[980px]:!grid-cols-[minmax(0,var(--chat-left-pane-width,0px))_8px_minmax(420px,1fr)_8px_minmax(0,var(--chat-right-pane-width,0px))] max-[640px]:!grid-cols-[minmax(0,var(--chat-left-pane-width,0px))_6px_minmax(280px,1fr)_6px_minmax(0,var(--chat-right-pane-width,0px))]",
    leftBlock:
      "grid gap-1.5 rounded-[var(--radius-panel)] border border-[var(--vui-border-subtle)] bg-[color-mix(in_srgb,var(--vui-surface-glass)_82%,transparent)] p-1.5 shadow-[var(--vui-shadow-hairline)]",
    leftRail: "!flex h-full min-h-0 !flex-col gap-[5px] overflow-auto p-1.5 [scrollbar-gutter:stable]",
    memberIndexSummary: "!grid grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-1.5",
    panelBody: "min-h-0 overflow-auto [scrollbar-gutter:stable]",
    paneCollapsed: "invisible pointer-events-none !overflow-hidden opacity-0",
    petShowcaseActions: "!grid grid-cols-[repeat(3,minmax(0,1fr))] gap-[5px]",
    resourceSplit: "!grid grid-cols-[repeat(auto-fit,minmax(118px,1fr))] gap-[5px]",
    rightIndexTabs: "!grid grid-cols-[repeat(2,minmax(0,1fr))] gap-1",
    rightPane: "grid h-full min-h-0 grid-rows-[auto_auto_minmax(0,1fr)] overflow-hidden p-1.5",
    runtimeNotice: "!grid grid-cols-[16px_minmax(0,1fr)] items-start gap-[7px]",
    sectionHeader: "flex items-center justify-between gap-1.5",
    sectionIdentity: "grid min-w-0 gap-0.5",
    sectionTitle: "m-0 text-[var(--vui-font-title)] font-semibold leading-tight text-[var(--fg-primary)]",
    sessionBindingNotice: "!grid grid-cols-[minmax(0,1fr)_auto] items-center gap-1.5",
    sessionContextMenuItem:
      "[&_[data-slot=vui-button-content]]:contents [&_[data-slot=vui-button-label]]:contents [&_[data-slot=vui-button-label]]:col-span-full",
    sessionItemActive: "shadow-[var(--vui-shadow-inset-accent)]",
    tokenStatusCopy: "min-w-0 overflow-visible [overflow-wrap:anywhere]",
    tokenStatusLabel: "block max-w-full whitespace-normal text-[11px] leading-[1.12]",
    tokenStatusMeta: "block max-w-full line-clamp-2 whitespace-normal leading-[1.14]",
    tokenStatusMetric:
      "!grid min-h-[62px] !w-full grid-cols-[38px_minmax(0,1fr)] items-center justify-stretch gap-1.5 overflow-visible rounded-[var(--radius-control)] px-1.5 py-1",
    tokenStatusMetricButton:
      "!grid !w-full [&_[data-slot=vui-button-content]]:contents [&_[data-slot=vui-button-label]]:contents",
    tokenStatusRing: "relative size-[38px] shrink-0 bg-[conic-gradient(var(--accent-cool)_calc(var(--token-status-value)*1%),var(--vui-border-subtle)_0)]",
    tokenStatusRingCore: "max-w-[32px] truncate text-[10px] leading-none",
    tokenStatusVisualGrid: "!grid !w-full grid-cols-1 justify-stretch gap-1.5 rounded-[var(--radius-control)]",
    tokenStatusBar: "[&>span]:w-[calc(var(--token-status-value)*1%)]",
    toolApprovalDialog: "!grid grid-cols-[34px_minmax(0,1fr)_auto] gap-2.5",
  },
  overrides: {
    centerSurface:
      "grid h-full min-h-0 overflow-hidden bg-[color-mix(in_srgb,var(--surface-panel-strong)_6%,transparent)]",
    conversationFrame:
      "relative flex h-full min-h-0 min-w-0 flex-col overflow-hidden",
    conversationGroup:
      "grid min-w-0 gap-0.5",
    conversationGroupHeader:
      "!grid !w-full min-h-[28px] grid-cols-[14px_minmax(0,1fr)_auto] items-center gap-1 rounded-none border-0 bg-transparent px-1.5 py-0 text-left text-[var(--vui-font-sm)] font-semibold leading-tight text-[var(--fg-secondary)] shadow-none hover:border-transparent hover:bg-[color-mix(in_srgb,var(--surface-card)_36%,transparent)] [&_[data-slot=vui-button-content]]:contents [&_[data-slot=vui-button-label]]:contents [&_span]:min-w-0 [&_span]:truncate [&_strong]:text-[var(--vui-font-xs)] [&_strong]:font-semibold",
    conversationGroupList:
      "grid min-w-0 gap-1",
    agentModelTag:
      "inline-flex min-h-[18px] min-w-0 max-w-[96px] shrink items-center gap-0.5 overflow-hidden rounded-full border border-[color-mix(in_srgb,var(--accent-cool)_24%,var(--vui-border-subtle))] bg-[color-mix(in_srgb,var(--accent-cool)_7%,transparent)] px-1.5 py-0 text-[var(--vui-font-xs)] font-semibold leading-none text-[var(--accent-cool)] [&_span]:min-w-0 [&_span]:truncate [&_svg]:shrink-0",
    agentModelTitleTag:
      "max-w-[96px]",
    compactDetails:
      "grid min-w-0 gap-1 rounded-[var(--radius-control)] border border-[var(--vui-border-subtle)] bg-[color-mix(in_srgb,var(--vui-surface-row)_54%,transparent)] px-2 py-1.5 text-[var(--vui-font-xs)] text-[var(--fg-secondary)] [&>summary]:grid [&>summary]:cursor-pointer [&>summary]:list-none [&>summary]:grid-cols-[14px_minmax(0,1fr)] [&>summary]:items-center [&>summary]:gap-1 [&>summary]:font-semibold [&>summary::-webkit-details-marker]:hidden [&>summary_svg]:transition-transform [&[open]>summary_svg]:rotate-90 [&_.compactDetailsOpenLabel]:hidden [&[open]_.compactDetailsOpenLabel]:inline [&[open]_.compactDetailsClosedLabel]:hidden",
    conversationCopy:
      "grid min-w-0 gap-0.5 overflow-hidden text-left",
    conversationMetaMain:
      "inline-flex min-w-0 items-center gap-1 overflow-hidden text-[var(--vui-font-xs)] font-medium leading-tight text-[var(--fg-tertiary)] [&>span]:min-w-0 [&>span]:truncate",
    conversationMetaRow:
      "grid min-w-0 grid-cols-[minmax(0,1fr)_max-content] items-center gap-x-1.5 text-[var(--vui-font-xs)] leading-tight text-[var(--fg-tertiary)] [&_time]:flex-none [&_time]:overflow-visible [&_time]:text-clip",
    conversationMetaTime:
      "inline-flex max-w-[112px] shrink-0 items-center justify-end gap-0.5 overflow-visible whitespace-nowrap text-[var(--vui-font-xs)] leading-tight text-[var(--fg-tertiary)] [&_time]:flex-none [&_time]:overflow-visible [&_time]:text-clip",
    conversationTitleMain:
      "inline-flex min-w-0 max-w-full items-center gap-1.5 overflow-hidden",
    conversationTitleRow:
      "grid min-w-0 max-w-full grid-cols-[minmax(0,1fr)_auto] items-center gap-1",
    directSessionItem:
      "pr-1 shadow-none",
    featureChip:
      "relative !grid min-h-[28px] min-w-0 !w-full max-w-full grid-cols-[auto_minmax(0,1fr)] items-center justify-start gap-1.5 rounded-[var(--radius-control)] border border-[var(--vui-border-subtle)] bg-[var(--vui-control-muted)] px-1.5 py-1 text-[var(--vui-font-xs)] font-semibold leading-tight text-[var(--fg-secondary)] transition-colors hover:border-[var(--border-strong)] hover:bg-[var(--vui-control-muted-hover)] hover:text-[var(--fg-primary)] disabled:cursor-default disabled:opacity-55 [&_[data-slot=vui-button-content]]:min-w-0 [&_[data-slot=vui-button-content]]:max-w-full [&_[data-slot=vui-button-content]]:w-full [&_[data-slot=vui-button-label]]:grid [&_[data-slot=vui-button-label]]:min-w-0 [&_[data-slot=vui-button-label]]:w-full [&_[data-slot=vui-button-label]]:grid-cols-[minmax(0,1fr)_auto] [&_[data-slot=vui-button-label]]:items-center [&_[data-slot=vui-button-label]]:gap-1 before:content-[''] before:h-1.5 before:w-1.5 before:shrink-0 before:rounded-full before:bg-[var(--fg-tertiary)] [&_em]:shrink-0 [&_em]:not-italic [&_strong]:min-w-0 [&_strong]:truncate [&_strong]:whitespace-nowrap",
    featureChipActive:
      "border-[color-mix(in_srgb,var(--accent-cool)_38%,var(--vui-border-subtle))] text-[var(--fg-primary)] before:bg-[var(--accent-cool)]",
    featureChipPrimary:
      "border-[color-mix(in_srgb,var(--accent-warm)_32%,var(--vui-border-subtle))] before:bg-[var(--accent-warm-2)]",
    featureChipRow: "grid min-w-0 grid-cols-2 gap-1.5 overflow-visible rounded-none border-0 bg-transparent p-0",
    panelNotice:
      "grid min-w-0 rounded-[var(--radius-control)] border border-[color-mix(in_srgb,var(--accent-warm)_22%,var(--vui-border-subtle))] bg-[color-mix(in_srgb,var(--accent-warm)_5%,var(--vui-surface-row))] px-2 py-1.5 text-[var(--vui-font-xs)] font-semibold leading-tight text-[var(--fg-secondary)]",
    panelState:
      "grid min-h-[42px] min-w-0 place-items-center rounded-[var(--radius-control)] border border-dashed border-[var(--vui-border-subtle)] bg-[color-mix(in_srgb,var(--vui-surface-row)_66%,transparent)] px-2 py-2 text-center text-[var(--vui-font-xs)] font-semibold leading-tight text-[var(--fg-tertiary)]",
    groupSessionItem:
      "pr-1 border-transparent bg-transparent shadow-none",
    newGroupButton:
      "!inline-flex !h-[32px] !min-h-[32px] !w-auto items-center gap-1 rounded-[var(--radius-control)] border border-[var(--vui-border-subtle)] bg-[var(--vui-control-muted)] px-2 py-0 !text-[var(--vui-font-xs)] font-semibold !leading-none text-[var(--fg-secondary)] shadow-none hover:bg-[var(--vui-control-muted-hover)] [&_[data-slot=vui-button-content]]:!leading-none [&_[data-slot=vui-button-label]]:!leading-none",
    newSessionButton:
      "!inline-flex !h-[32px] !min-h-[32px] !w-auto items-center gap-1 rounded-[var(--radius-control)] border border-[var(--vui-border-subtle)] bg-[var(--vui-control-muted)] px-2 py-0 !text-[var(--vui-font-xs)] font-semibold !leading-none text-[var(--fg-secondary)] shadow-none hover:bg-[var(--vui-control-muted-hover)] [&_[data-slot=vui-button-content]]:!leading-none [&_[data-slot=vui-button-label]]:!leading-none",
    sessionActionRow:
      "grid min-w-0 grid-cols-[auto_auto] justify-start gap-1 rounded-none border-0 bg-transparent p-0",
    sessionItem:
      "relative grid min-w-0 grid-cols-[minmax(0,1fr)] gap-0 rounded-[var(--radius-control)] border border-transparent bg-transparent !px-1 !py-0.5 text-left transition-colors hover:bg-[color-mix(in_srgb,var(--surface-card)_58%,transparent)] hover:shadow-[var(--vui-shadow-inset-accent)] focus-within:bg-[color-mix(in_srgb,var(--surface-card)_58%,transparent)] focus-within:shadow-[var(--vui-shadow-inset-accent)]",
    sessionItemActive:
      "border-[color-mix(in_srgb,var(--accent-cool)_20%,transparent)] bg-[color-mix(in_srgb,var(--surface-card)_68%,transparent)] shadow-[var(--vui-shadow-inset-accent)]",
    sessionItemMain:
      "!grid !w-full min-w-0 grid-cols-[27px_minmax(0,1fr)] items-center justify-stretch gap-1.5 rounded-none border-0 bg-transparent !p-0 text-left text-[var(--fg-primary)] shadow-none hover:border-transparent hover:bg-transparent hover:shadow-none [&_[data-slot=vui-button-content]]:contents [&_[data-slot=vui-button-label]]:contents",
    sessionItemSummary:
      "block min-w-0 truncate text-[var(--vui-font-xs)] leading-tight text-[var(--fg-secondary)]",
    sessionItemTitle:
      "min-w-0 truncate text-[var(--vui-font-md)] font-semibold leading-tight text-[var(--fg-primary)]",
    sessionStatusCluster:
      "inline-flex min-w-0 items-center justify-end gap-1",
    systemEntryButton:
      "!grid min-h-[48px] !w-full grid-cols-[26px_minmax(0,1fr)] items-center justify-start gap-2 overflow-hidden rounded-[var(--radius-control)] border border-[var(--vui-border-subtle)] bg-[color-mix(in_srgb,var(--vui-surface-row)_72%,transparent)] px-2 py-1.5 text-left text-[var(--fg-secondary)] shadow-none transition-colors hover:border-[color-mix(in_srgb,var(--accent-cool)_26%,var(--vui-border-subtle))] hover:bg-[color-mix(in_srgb,var(--accent-cool)_6%,var(--vui-surface-row))] [&_[data-slot=vui-button-content]]:contents [&_[data-slot=vui-button-label]]:contents",
    systemEntryButtonActive:
      "border-[color-mix(in_srgb,var(--accent-cool)_36%,var(--vui-border-subtle))] bg-[color-mix(in_srgb,var(--accent-cool)_9%,var(--vui-surface-row))] text-[var(--fg-primary)]",
    systemEntryCopy:
      "grid min-w-0 gap-0.5 overflow-hidden text-left",
    systemEntryGroup:
      "grid min-w-0 gap-1.5 rounded-[var(--radius-panel)] border border-[var(--vui-border-subtle)] bg-[var(--vui-surface-glass)] p-2 shadow-[var(--vui-shadow-hairline)]",
    systemEntryIcon:
      "grid size-[26px] shrink-0 place-items-center rounded-[var(--radius-control)] border border-[var(--vui-border-subtle)] bg-[var(--vui-control-muted)] text-[var(--fg-secondary)]",
    systemEntryMeta:
      "block min-w-0 truncate text-[10px] font-medium leading-tight text-[var(--fg-tertiary)]",
    systemEntryTitle:
      "block min-w-0 truncate text-[var(--vui-font-xs)] font-semibold leading-tight text-[var(--fg-primary)]",
    systemEntryTitleRow:
      "!flex min-w-0 items-center gap-1.5",
    tokenStatusBar:
      "relative mt-1 block h-1 overflow-hidden rounded-full bg-[var(--vui-border-subtle)] [&>span]:block [&>span]:h-full [&>span]:rounded-full [&>span]:bg-[var(--accent-cool)] [&>span]:w-[calc(var(--token-status-value)*1%)]",
    tokenStatusCopy: "grid min-w-0 gap-0.5 overflow-visible [overflow-wrap:anywhere]",
    tokenStatusLabel:
      "block min-w-0 max-w-full whitespace-normal text-[11px] font-semibold leading-[1.12] text-vui-fg-secondary",
    tokenStatusMeta:
      "block min-w-0 max-w-full line-clamp-2 whitespace-normal text-[10px] leading-[1.14] text-vui-fg-tertiary",
    tokenStatusMetric:
      "!grid min-h-[62px] !w-full grid-cols-[38px_minmax(0,1fr)] items-center justify-stretch gap-1.5 overflow-visible rounded-[var(--radius-control)] border border-[var(--vui-border-subtle)] bg-[var(--vui-control-muted)] px-1.5 py-1 text-left",
    tokenStatusMetric_cache:
      "border-[color-mix(in_srgb,var(--accent-cool)_24%,var(--vui-border-subtle))] bg-[color-mix(in_srgb,var(--accent-cool)_7%,var(--vui-control-muted))]",
    tokenStatusMetric_compression:
      "border-[color-mix(in_srgb,var(--accent-warm)_24%,var(--vui-border-subtle))] bg-[color-mix(in_srgb,var(--accent-warm)_7%,var(--vui-control-muted))]",
    tokenStatusMetric_modelInput:
      "border-[color-mix(in_srgb,var(--state-success)_22%,var(--vui-border-subtle))] bg-[color-mix(in_srgb,var(--state-success)_7%,var(--vui-control-muted))]",
    tokenStatusMetricButton:
      "!grid !w-full [&_[data-slot=vui-button-content]]:contents [&_[data-slot=vui-button-label]]:contents",
    tokenStatusRing:
      "relative size-[38px] shrink-0 rounded-full bg-[conic-gradient(var(--accent-cool)_calc(var(--token-status-value)*1%),var(--vui-border-subtle)_0)]",
    tokenStatusRingCore:
      "absolute inset-[5px] grid place-items-center rounded-full bg-[var(--surface-card)] text-[10px] font-bold leading-none text-vui-fg-primary",
    tokenStatusVisualGrid: "!grid w-full grid-cols-1 justify-stretch gap-1.5 rounded-[var(--radius-control)]",
  },
});

export default styles;
