import { createVuiStyleMap } from "../components/vui/styles/createVuiStyleMap";

const styleKeys = [
  "actionButton",
  "actionGrid",
  "actionGridCompact",
  "actionRow",
  "approvalEvidenceActions",
  "approvalEvidenceItem",
  "approvalEvidencePanel",
  "batchToggle",
  "bulkToolbar",
  "bulkToolbarHint",
  "bulkToolbarText",
  "cardFooter",
  "cardHeadline",
  "caseConversationFallback",
  "caseConversationShell",
  "caseConversationTranscript",
  "casePreflightIssue",
  "caseRawEvidence",
  "caseTraceBody",
  "caseTraceChevron",
  "caseTraceIcon",
  "caseTraceMessage",
  "caseTraceMeta",
  "caseTracePreview",
  "caseTraceSection",
  "caseTraceSectionJson",
  "caseTraceStack",
  "caseTraceStateGrid",
  "caseTraceStateRow",
  "caseTraceStatus",
  "caseTraceSummary",
  "caseTraceTime",
  "caseTraceTimeline",
  "caseTraceTitle",
  "caseTraceTurn",
  "caseTraceTurn_assistant",
  "caseTraceTurn_error",
  "caseTraceTurn_input",
  "caseTraceTurn_thought",
  "caseTraceTurn_tool",
  "chatReviewSurface",
  "checkboxLabel",
  "checkboxRow",
  "closedLoopLaunchBlock",
  "closedLoopLedger",
  "closedLoopLedgerEvidenceGrid",
  "closedLoopLedgerHeader",
  "closedLoopModeBadge",
  "closedLoopStatus",
  "closedLoopTitleRow",
  "collapsibleEvidence",
  "compactActionGroup",
  "compactFact",
  "compactFieldGrid",
  "compactIconAction",
  "compactRunList",
  "compactRunMain",
  "compactRunMeta",
  "compactRunRow",
  "compactTextAction",
  "controlActions",
  "controlColumn",
  "controlFooter",
  "controlLabel",
  "controlSurface",
  "dangerDetailSection",
  "dangerIconAction",
  "dangerInlineAction",
  "dashboardIo",
  "dashboardLaunch",
  "dashboardRun",
  "datasetCatalogEmpty",
  "datasetCatalogFilterButton",
  "datasetCatalogFilterButtonActive",
  "datasetCatalogFilterRow",
  "datasetCatalogHeader",
  "datasetCatalogItem",
  "datasetCatalogItemMain",
  "datasetCatalogList",
  "datasetCatalogPanel",
  "datasetCatalogStatus",
  "datasetMeta",
  "datasetMetaCompact",
  "deltaBadge",
  "deltaNegative",
  "deltaNeutral",
  "deltaPositive",
  "detailFactGrid",
  "detailHeader",
  "detailHeaderActions",
  "detailLead",
  "detailList",
  "detailPanel",
  "detailSection",
  "detailSectionCompact",
  "detailSubtleId",
  "detailTitle",
  "emptyState",
  "errorText",
  "errorTextCompact",
  "eventHeader",
  "eventList",
  "eventListScrollable",
  "eventRow",
  "eventSummary",
  "eyebrow",
  "feedbackText",
  "feedbackTextCompact",
  "filterButton",
  "filterButtonActive",
  "filterField",
  "filterMeta",
  "filterRow",
  "filterSegmented",
  "formField",
  "formGrid",
  "formHint",
  "headerIcon",
  "heroHeading",
  "heroHeadingRow",
  "heroSummary",
  "heroSurface",
  "heroTitleRow",
  "heroTop",
  "idleMonitor",
  "inlineAction",
  "inlineNoticeRow",
  "intakeButton",
  "intakeButtonActive",
  "intakeControl",
  "intakeSegmented",
  "ioContent",
  "ioEntry",
  "ioMetaRow",
  "ioStack",
  "ioSurface",
  "ioTranscript",
  "ioWaitingState",
  "launchSurface",
  "libraryFilters",
  "librarySummaryBar",
  "libraryViewStack",
  "listEmptyState",
  "listPanel",
  "listRow",
  "listRowTop",
  "listStack",
  "liveIoPane",
  "liveIoResizeHandle",
  "liveLaunchStack",
  "liveResizeHandle",
  "liveResizeHandleLaunch",
  "liveResizeHandleRun",
  "liveRunToolbar",
  "liveStatusRow",
  "liveSummaryRow",
  "liveSurface",
  "masterDetail",
  "metaRow",
  "metricGrid",
  "metricStrip",
  "metricTile",
  "modeTeamCanvasMap",
  "modeTeamEdges",
  "modeTeamEmpty",
  "modeTeamHeader",
  "modeTeamNode",
  "modeTeamNodeBound",
  "modeTeamNodeStale",
  "modeTeamPanel",
  "modeTeamStats",
  "monitorMetrics",
  "monitorMetricsDense",
  "monitorSummary",
  "mutedCounter",
  "noticeText",
  "noticeTextCompact",
  "overviewGrid",
  "overviewSecondaryGrid",
  "overviewWorkspace",
  "page",
  "paneCollapsed",
  "panelHeader",
  "pathText",
  "primaryEvidenceBlock",
  "proposalCard",
  "proposalCardButton",
  "proposalEditGrid",
  "rawBlock",
  "rawBlockStack",
  "rawJson",
  "relatedList",
  "relatedRow",
  "resizeHandle",
  "reviewLead",
  "runCardButton",
  "runControlReason",
  "runControlSummaryBody",
  "runDetailOverview",
  "runDetailPanel",
  "runItem",
  "runItemActive",
  "runListScrollable",
  "runMonitor",
  "runMonitorDense",
  "runNextActionStrip",
  "runQueuePanel",
  "runRecordCard",
  "runRecordIdentity",
  "runRecordTitleRow",
  "runRuntimeNote",
  "runsCommandHeader",
  "runsCommandMetrics",
  "runsCommandStrip",
  "runScoreDiagnosis",
  "runScoreFacts",
  "runScorePanel",
  "runsGuideCard",
  "runsHeaderBody",
  "runsHeaderSurface",
  "runSignalGrid",
  "runSignalStack",
  "runsSurface",
  "runSummaryTone_danger",
  "runSummaryTone_idle",
  "runSummaryTone_running",
  "runSummaryTone_success",
  "runSummaryTone_warning",
  "runsWorkspace",
  "scoreRow",
  "secondaryPill",
  "sectionHeadingRow",
  "sectionTitle",
  "segmentButton",
  "segmentButtonActive",
  "segmented",
  "selectInput",
  "selectionBar",
  "selectionSummary",
  "selfModeStack",
  "sourceHero",
  "sourceInventoryBar",
  "sourceMetaCompact",
  "sourceMetaMain",
  "sourceMetaSide",
  "sourceMetricGrid",
  "sourceNextAction",
  "sourceSummary",
  "sourceWarningStrip",
  "statusIcon",
  "statusLead",
  "statusMetricGrid",
  "statusPill",
  "statusSurface",
  "stripItem",
  "structuredEmptyState",
  "subtitle",
  "summaryMetricStrip",
  "summarySurface",
  "supervisedMemberIdentity",
  "supervisedMemberLink",
  "supervisedMemberRole",
  "supervisedMemberRow",
  "supervisedMemberRowActive",
  "supervisedMemberRowMissing",
  "supervisedMembersHeader",
  "supervisedMembersHeaderActions",
  "supervisedMembersList",
  "supervisedMembersPanel",
  "supervisedRunConsole",
  "supervisedRunConsoleGrid",
  "supervisedRunConsoleHeader",
  "supervisedRunConsoleStatus",
  "supervisedRunOptions",
  "supervisedRunSetup",
  "supervisedStepFollowButton",
  "supervisedStepMemberCard",
  "supervisedStepMemberCardActive",
  "supervisedStepMemberCardCurrent",
  "supervisedStepMemberLabel",
  "supervisedStepMemberRail",
  "supervisedWorkflowCard",
  "supervisedWorkflowCardActive",
  "supervisedWorkflowCardButton",
  "supervisedWorkflowCardCurrent",
  "supervisedWorkflowCardFooter",
  "supervisedWorkflowCardGrid",
  "supervisedWorkflowCardTopline",
  "supervisedWorkflowFollowButton",
  "supervisedWorkflowLivePreview",
  "supervisedWorkflowPanel",
  "supervisedWorkflowSessionLink",
  "surface",
  "surfaceHeader",
  "surfaceHeaderCompact",
  "textArea",
  "textInput",
  "title",
  "toolbar",
  "toolbarControls",
  "toolbarIntro",
  "transcriptSection",
  "trendBarFill",
  "trendBarTrack",
  "trendMeta",
  "trendRow",
  "trendStack",
  "trendValue",
  "truncateText",
  "viewStack",
] as const;

const styles = createVuiStyleMap(styleKeys, {
  extensions: {
    caseConversationShell: "min-h-0",
    caseConversationTranscript: "min-h-0",
    caseRawEvidence: "max-h-[30%]",
    caseTraceMessage: "line-clamp-2",
    caseTraceMeta: "justify-end",
    caseTraceStack: "justify-end",
    caseTraceTimeline: "relative before:content-['']",
    launchSurface: "max-h-none",
    librarySummaryBar: "grid-cols-[minmax(300px,1fr)_minmax(260px,0.8fr)_minmax(300px,0.9fr)]",
    liveLaunchStack:
      "grid-rows-[minmax(0,1fr)] overflow-hidden max-h-none max-[1360px]:grid max-[900px]:h-auto max-[900px]:overflow-auto max-[900px]:content-start max-[900px]:grid-rows-[max-content_max-content_max-content]",
    noticeText: "max-[1200px]:hidden",
    sourceInventoryBar: "max-[1200px]:hidden",
    sourceMetaCompact: "max-[1200px]:hidden",
    structuredEmptyState: "min-h-[86px] px-3 py-2.5",
    supervisedMemberRow: "min-h-[34px] font-mono",
    supervisedMembersList: "max-h-[min(238px,34vh)]",
    supervisedRunConsole: "[container-type:inline-size]",
    supervisedRunConsoleGrid:
      "grid-cols-[minmax(300px,var(--evolution-live-launch-width,348px))_minmax(0,1fr)_minmax(300px,var(--evolution-live-run-width,360px))] grid-rows-[minmax(0,1fr)] max-[900px]:grid-cols-1 max-[900px]:auto-rows-max",
    supervisedRunSetup: "max-h-[min(118px,22vh)]",
    supervisedWorkflowCard: "min-h-[112px] overflow-visible p-2",
    supervisedWorkflowCardButton:
      "!grid !h-full !min-h-[86px] !w-full !max-w-none grid-rows-[auto_auto_minmax(0,1fr)] items-start justify-stretch gap-1.5 p-2 text-left [&_[data-slot=vui-button-content]]:contents [&_[data-slot=vui-button-label]]:contents",
    supervisedWorkflowCardFooter: "mt-1 grid w-full grid-cols-2 gap-1",
    supervisedWorkflowCardGrid:
      "grid-cols-[repeat(4,minmax(168px,1fr))] gap-1.5 overflow-visible max-[1280px]:grid-cols-2 max-[760px]:grid-cols-1",
    supervisedWorkflowCardTopline:
      "flex min-h-0 w-full items-center justify-between gap-1 rounded-none border-0 bg-transparent p-0 text-[var(--vui-font-xs)] leading-tight",
    supervisedWorkflowFollowButton: "min-h-[26px] px-2 text-[var(--vui-font-xs)]",
    supervisedWorkflowLivePreview: "line-clamp-2 min-h-[30px] text-[var(--vui-font-xs)] leading-[1.28]",
    supervisedWorkflowPanel: "overflow-visible",
    supervisedWorkflowSessionLink:
      "min-h-[24px] w-full justify-center px-1.5 text-[var(--vui-font-xs)] leading-none",
    transcriptSection: "flex-1 basis-0 bg-transparent",
  },
});

export default styles;
