const styles = {
  root: "@container grid h-full min-h-0 [grid-template-rows:auto_minmax(0,_1fr)_auto] overflow-hidden bg-[var(--vui-surface-base)] text-[var(--fg-primary)]",
  header: "flex min-w-0 items-start justify-between gap-3 border-b border-[var(--vui-border-subtle)] px-4 py-3 max-[520px]:px-3",
  headingCopy: "grid min-w-0 gap-1",
  eyebrow: "[color:var(--accent-cool-2)] [font-size:var(--vui-font-2xs)] [font-weight:750] [letter-spacing:0.08em] [line-height:1.2]",
  title: "m-0 [font-size:1.02rem] [font-weight:750] [line-height:1.3]",
  subtitle: "m-0 max-w-[680px] [color:var(--fg-secondary)] [font-size:var(--vui-font-xs)] [line-height:1.4]",
  sourceCount: "mt-1 shrink-0 rounded-full border border-[var(--vui-border-subtle)] bg-[var(--vui-surface-row)] px-2 py-1 [color:var(--fg-secondary)] [font-size:var(--vui-font-2xs)] [line-height:1.2]",
  content: "grid min-h-0 [grid-template-columns:minmax(0,_1fr)] [align-content:start] gap-3 overflow-y-auto px-4 py-3 max-[520px]:px-3 [@container(min-width:720px)]:[grid-template-columns:minmax(0,_1.12fr)_minmax(240px,_0.88fr)] [@container(min-width:720px)]:[align-content:stretch] [@container(min-width:720px)]:overflow-hidden",
  sourcePicker: "grid min-h-0 [grid-template-rows:auto_auto_minmax(0,_1fr)] gap-2",
  sectionHeader: "flex min-w-0 items-start justify-between gap-3",
  sectionTitle: "m-0 [font-size:var(--vui-font-sm)] [font-weight:720] [line-height:1.3]",
  sectionHint: "m-0 mt-0.5 [color:var(--fg-tertiary)] [font-size:var(--vui-font-2xs)] [line-height:1.35]",
  searchField: "flex min-w-0 items-center gap-2 rounded-md border border-[var(--vui-border-subtle)] bg-[var(--vui-surface-row)] px-2.5 [color:var(--fg-tertiary)] focus-within:border-[color-mix(in_srgb,_var(--accent-cool)_50%,_var(--vui-border-subtle))] focus-within:[box-shadow:var(--vui-shadow-focus)] [&_svg]:shrink-0",
  searchInput: "!min-h-10 !border-0 !bg-transparent !px-0 !shadow-none focus:!outline-none focus:!ring-0",
  sourceGroups: "grid min-h-0 [align-content:start] gap-3 overflow-y-auto [max-height:min(44vh,_420px)] pr-1 [@container(min-width:720px)]:[max-height:none]",
  sourceGroup: "grid min-w-0 [align-content:start] gap-1.5",
  sourceGroupHeading: "m-0 flex min-w-0 items-center gap-1.5 px-1 [color:var(--fg-secondary)] [font-size:var(--vui-font-xs)] [font-weight:700] [&_svg]:shrink-0",
  sourceGroupCount: "ml-auto rounded-full bg-[var(--vui-surface-row)] px-1.5 py-0.5 [color:var(--fg-tertiary)] [font-size:var(--vui-font-2xs)] [font-weight:600]",
  sourceList: "m-0 grid list-none [align-content:start] gap-1.5 p-0",
  sourceOption: "!grid !justify-items-stretch !justify-start !h-auto !min-h-11 w-full [grid-template-columns:minmax(0,_1fr)] [align-content:start] gap-1 rounded-md border border-[var(--vui-border-subtle)] bg-[var(--vui-surface-row)] px-3 py-2.5 text-left text-[var(--fg-primary)] [white-space:normal] transition-colors hover:bg-[var(--vui-surface-row-hover)] aria-pressed:border-[color-mix(in_srgb,_var(--accent-cool)_55%,_var(--vui-border-subtle))] aria-pressed:bg-[color-mix(in_srgb,_var(--accent-cool)_var(--vui-alpha-wash),_var(--vui-surface-panel))] disabled:cursor-not-allowed disabled:opacity-55",
  sourceOptionSelected: "[box-shadow:inset_2px_0_0_var(--accent-cool)]",
  sourceOptionTopline: "flex min-w-0 items-center justify-between gap-2",
  sourceOptionName: "min-w-0 overflow-hidden text-ellipsis [font-size:var(--vui-font-xs)] [font-weight:720] [line-height:1.35] [overflow-wrap:anywhere]",
  sourceSelectedIcon: "shrink-0 [color:var(--accent-cool-2)]",
  sourceOptionMeta: "flex min-w-0 flex-wrap items-center gap-x-2 gap-y-1 [color:var(--fg-tertiary)] [font-size:var(--vui-font-2xs)] [line-height:1.35]",
  sourceKindBadge: "rounded-full border border-[var(--vui-border-subtle)] px-1.5 py-0.5 [color:var(--fg-secondary)]",
  sourceOptionStatus: "rounded-full bg-[var(--vui-surface-panel)] px-1.5 py-0.5 [color:var(--fg-secondary)]",
  sourceOptionDetail: "[color:var(--fg-tertiary)] [font-size:var(--vui-font-2xs)] [line-height:1.4] [overflow-wrap:anywhere]",
  sourceOptionDisabledReason: "[color:var(--accent-warm-2)] [font-size:var(--vui-font-2xs)] [line-height:1.4] [overflow-wrap:anywhere]",
  emptySources: "m-0 rounded-md border border-dashed border-[var(--vui-border-subtle)] px-3 py-6 text-center [color:var(--fg-tertiary)] [font-size:var(--vui-font-xs)] [line-height:1.45]",
  detailsPane: "grid min-h-0 [align-content:start] gap-2 overflow-y-auto",
  selectedSourceCard: "grid min-w-0 [align-content:start] gap-2 rounded-lg border border-[var(--vui-border-subtle)] bg-[var(--vui-surface-panel)] p-3",
  detailsHeader: "flex min-w-0 items-center justify-between gap-2",
  detailsEyebrow: "[color:var(--fg-tertiary)] [font-size:var(--vui-font-2xs)] [font-weight:700] [letter-spacing:0.05em]",
  selectedKindBadge: "inline-flex max-w-full items-center gap-1 rounded-full bg-[var(--vui-surface-row)] px-2 py-1 [color:var(--fg-secondary)] [font-size:var(--vui-font-2xs)] [&_svg]:shrink-0",
  selectedSourceName: "m-0 min-w-0 [font-size:var(--vui-font-sm)] [font-weight:760] [line-height:1.4] [overflow-wrap:anywhere]",
  sourceFacts: "m-0 grid grid-cols-2 gap-2 [&_div]:grid [&_div]:gap-0.5 [&_dt]:[color:var(--fg-tertiary)] [&_dt]:[font-size:var(--vui-font-2xs)] [&_dd]:m-0 [&_dd]:[color:var(--fg-primary)] [&_dd]:[font-size:var(--vui-font-xs)] [&_dd]:[font-weight:680] [&_dd]:[overflow-wrap:anywhere]",
  selectedSourceDetail: "m-0 rounded-md bg-[var(--vui-surface-row)] px-2.5 py-2 [color:var(--fg-secondary)] [font-size:var(--vui-font-xs)] [line-height:1.45] [overflow-wrap:anywhere]",
  evaluationMode: "grid gap-1 rounded-md border border-[var(--vui-border-subtle)] px-2.5 py-2 [&_strong]:[font-size:var(--vui-font-2xs)] [&_strong]:[color:var(--fg-secondary)] [&_span]:[font-size:var(--vui-font-xs)] [&_span]:[color:var(--fg-primary)] [&_span]:[line-height:1.45] [&_span]:[overflow-wrap:anywhere]",
  officialWarning: "m-0 flex min-w-0 items-start gap-1.5 rounded-md border border-[color-mix(in_srgb,_var(--accent-warm)_var(--vui-alpha-line),_var(--vui-border-subtle))] bg-[color-mix(in_srgb,_var(--accent-warm)_var(--vui-alpha-wash),_var(--vui-surface-panel))] px-2.5 py-2 [color:var(--accent-warm-2)] [font-size:var(--vui-font-2xs)] [line-height:1.45] [&_svg]:mt-0.5 [&_svg]:shrink-0",
  selectPrompt: "m-0 rounded-md border border-dashed border-[var(--vui-border-subtle)] px-2.5 py-3 [color:var(--fg-tertiary)] [font-size:var(--vui-font-xs)] [line-height:1.45]",
  caseLimitCard: "grid gap-1.5 rounded-lg border border-[var(--vui-border-subtle)] bg-[var(--vui-surface-panel)] p-3",
  formField: "grid min-w-0 [align-content:start] gap-1.5",
  formLabelWithHint: "flex min-w-0 items-center gap-1.5 [color:var(--fg-secondary)] [font-size:var(--vui-font-xs)] [font-weight:650] [&_label]:min-w-0",
  limitInput: "!min-h-11 !bg-[var(--vui-surface-row)]",
  inlineError: "m-0 rounded-md border border-[color-mix(in_srgb,_var(--accent-danger)_var(--vui-alpha-line),_var(--vui-border-subtle))] bg-[color-mix(in_srgb,_var(--accent-danger)_var(--vui-alpha-wash),_var(--vui-surface-panel))] px-2.5 py-2 [color:var(--accent-danger-2)] [font-size:var(--vui-font-xs)] [line-height:1.4] [overflow-wrap:anywhere]",
  advancedSection: "grid min-w-0 gap-1 rounded-lg border border-[var(--vui-border-subtle)] bg-[var(--vui-surface-panel)] p-2",
  advancedToggle: "!flex !h-9 !min-h-9 !w-full !justify-between !px-2 [font-size:var(--vui-font-xs)]",
  advancedFields: "grid min-w-0 gap-2 px-1 pb-1 [@container(min-width:720px)]:[grid-template-columns:minmax(0,_1fr)]",
  selectInput: "w-full",
  footer: "sticky bottom-0 z-10 grid min-w-0 [grid-template-columns:minmax(0,_1fr)_auto] items-center gap-3 border-t border-[var(--vui-border-subtle)] bg-[var(--vui-surface-panel)] px-4 py-2.5 shadow-[0_-8px_20px_color-mix(in_srgb,_var(--vui-surface-base)_76%,transparent)] max-[520px]:grid-cols-1 max-[520px]:gap-2 max-[520px]:px-3",
  footerMessage: "min-w-0 [&_p]:max-w-[760px]",
  lockHint: "m-0 [color:var(--fg-tertiary)] [font-size:var(--vui-font-2xs)] [line-height:1.4] [overflow-wrap:anywhere]",
  footerActions: "flex min-w-0 items-center justify-end gap-2 max-[520px]:grid max-[520px]:grid-cols-2 max-[520px]:data-[single=true]:grid-cols-1",
  footerButton: "!h-11 !min-h-11 max-[520px]:!w-full",
  startButton: "!h-11 !min-h-11 !min-w-[180px] max-[520px]:!w-full",
} as const;

export default styles;
