const border = "border-[var(--vui-border-subtle)]";
const muted = "text-[var(--fg-tertiary)]";
export default {
  frame: "finance-research-workspace flex h-[calc(100dvh_-_var(--shell-topbar-height))] w-full max-w-full min-h-0 min-w-0 flex-col overflow-hidden bg-[var(--vui-surface-panel)] text-[var(--fg-primary)]",
  actions: "flex shrink-0 items-center gap-1",
  split: "h-full w-full max-w-full flex-1 !gap-0 overflow-hidden",
  workspacePane: "flex h-full min-h-0 min-w-0 flex-col overflow-hidden bg-[var(--vui-surface-row)]",
  workspacePaneHeader: "shrink-0 !justify-between px-4 pb-2 pt-4",
  workspaceAsideHeader: "shrink-0 !justify-between px-3 pb-3 pt-4",
  workspacePaneAction: "!border-transparent !bg-transparent !shadow-none hover:!bg-[var(--vui-control-muted)]",
  workspacePaneTitle: "min-w-0 flex-1 truncate text-sm font-semibold",
  workspaceAsideTabs: "min-w-0 flex-1",
  workspaceAsideTitle: "whitespace-nowrap text-sm font-medium",
  workspaceHeaderContent: "flex min-w-0 flex-1 items-center gap-3",
  workspaceHeaderTitle: "m-0 min-w-0 truncate text-sm font-semibold",
  workspaceHeaderMeta: "shrink-0 whitespace-nowrap text-xs tabular-nums text-vui-fg-tertiary",
  workspaceHeaderActions: "flex shrink-0 items-center gap-2",
  workspacePlaceholder: "min-h-0 min-w-0 flex-1 px-3",
  workspaceToolbar: `shrink-0 !justify-between border-b ${border} px-5 py-3`,
  workspaceGroupTabs: "min-w-0 shrink-0 px-5 py-3",
  workspaceMarketSearch: "min-w-0 shrink-0 px-5 pb-3",
  workspaceMarketToolbar: "gap-3",
  workspaceMarketIcon: "shrink-0 text-vui-fg-tertiary",
  workspaceMarketSelect: "!w-24 shrink-0",
  workspaceMarketInput: "!w-auto min-w-0 flex-1",
  workspaceMarketLoading: "mt-2 h-8",
  workspaceMarketResults: "mt-2 grid max-h-48 gap-1 overflow-y-auto",
  workspaceGroupTabList: "!justify-start",
  rail: `flex h-full min-h-0 min-w-0 w-full flex-col gap-5 overflow-y-auto bg-[var(--vui-surface-row)] p-3`,
  aside: `flex h-full min-h-0 min-w-0 w-full flex-col gap-4 overflow-y-auto bg-[var(--vui-surface-row)] p-4`,
  sectionHeading: `flex items-center justify-between gap-2 text-xs font-medium ${muted}`,
  libraryHeading: "flex items-center gap-2",
  fields: "grid min-w-0 gap-3",
  field: `grid min-w-0 gap-1.5 text-xs ${muted}`,
  input: "!h-10 !w-full min-w-0 text-sm",
  newButton: "!min-h-9 !w-full !justify-start gap-2",
  records: "grid min-w-0 gap-1",
  record: "!h-auto !min-h-14 !w-full !max-w-full !justify-start !rounded-md !px-2.5 !py-2 text-left",
  selected: "!bg-[color-mix(in_srgb,var(--state-success)_10%,transparent)] !text-[var(--state-success)]",
  rowText: "grid min-w-0 w-full gap-1 text-left [&>strong]:truncate [&>strong]:text-xs [&>strong]:font-medium",
  small: `text-xs leading-relaxed ${muted}`,
  link: "!min-h-10 !justify-start text-xs",
  context: `flex shrink-0 flex-wrap items-center justify-between gap-2 border-b ${border} px-5 py-3`,
  contextTitle: "flex min-w-0 items-center gap-2 text-sm font-medium [&>span]:truncate",
  contextMeta: `text-xs ${muted}`,
  tasks: "flex items-center gap-1 [&>button]:!min-h-10 [&>button]:!px-3 [&>button]:text-xs",
  native: "flex min-h-0 min-w-0 flex-1 flex-col overflow-hidden [&_.tabStrip]:hidden [&_[data-vui-region=chat-conversation-center]]:!grid-rows-[minmax(0,1fr)] [&_.emptyState]:!border-0 [&_.emptyState]:!bg-transparent [&_.emptyState]:!shadow-none [&_[data-vui=conversation-starter-cards]]:hidden [&_[data-vui=chat-session-workbench-shell]]:!h-full [&_[data-vui=chat-session-workbench-shell]]:!max-h-full [&_[data-vui=chat-session-workbench-shell]]:!min-h-0",
  state: "flex min-h-0 flex-1 items-center justify-center overflow-auto px-5 py-8",
  stateSurface: "!max-w-md !border-0 !bg-transparent !shadow-none",
  sourceList: "grid min-w-0 gap-1",
  sourceButton: "!h-auto !min-h-8 !w-full !max-w-full !justify-start !px-2 !py-1.5 text-left",
  sourceArtifactButton: "!h-8 !min-h-8 !w-full !max-w-full !justify-start !px-2 !py-1 text-left",
  sourceArtifactRow: "flex min-w-0 w-full items-center gap-2 [&>strong]:min-w-0 [&>strong]:flex-1 [&>strong]:truncate [&>span]:shrink-0 [&>span]:truncate",
  detail: `grid min-w-0 gap-3 border-t ${border} pt-4`,
  facts: "grid grid-cols-[auto_minmax(0,1fr)] gap-x-3 gap-y-2 text-xs [&>dt]:text-[var(--fg-tertiary)] [&>dd]:m-0 [&>dd]:break-words",
  excerpt: `m-0 whitespace-pre-wrap break-words border-l-2 border-[var(--state-success)] pl-3 text-xs leading-7 text-[var(--fg-secondary)]`,
  skeleton: "grid gap-4 py-4",
  frameLoading: "flex min-h-0 flex-1 flex-col gap-5 p-6 overflow-hidden",
  frameLoadingBar: "h-8 shrink-0",
  frameLoadingQuestion: "ml-auto mt-3 w-3/4",
  frameLoadingQuestionBar: "h-12",
  frameLoadingReply: "grid max-w-3xl gap-5",
  frameLoadingReplyLabel: "h-5 w-28",
  frameLoadingReplyTitle: "h-6 w-2/3",
  frameLoadingReplyText: "h-4",
  frameLoadingReplyBody: "h-24",
  frameLoadingComposer: "mt-auto h-24 shrink-0",
  libraryCitation: "flex min-w-0 flex-wrap items-center gap-2 border-b border-[var(--vui-border-subtle)] pb-3",
  libraryCitationRow: "flex min-w-0 w-full items-center gap-2 whitespace-nowrap",
  libraryCitationTitle: "inline-flex min-w-0 flex-1 items-center gap-1 truncate text-xs",
  libraryCitationAction: "!h-8 !min-h-8 !px-2 !py-1 text-xs",
  workspaceSearchButton: "!justify-start !h-auto !py-2 !w-full",
  workspaceSearchText: "flex w-full min-w-0 items-center gap-2 whitespace-nowrap text-left [&>span]:shrink-0",
  workspaceStockName: "min-w-0 flex-1 truncate text-xs",
  workspaceAside: "flex min-h-0 min-w-0 h-full w-full max-w-full flex-col overflow-hidden bg-[var(--vui-surface-row)]",
  workspaceAsideBody: "flex-1 min-h-0 min-w-0 overflow-y-auto",
  workspaceErrorText: "block break-words",
  workspaceViewTabs: "shrink-0 px-6 py-3 border-b border-[var(--vui-border-subtle)]",
  workspaceOverview: "min-h-0 flex-1 overflow-y-auto p-6 grid content-start gap-5",
  workspaceChatHeading: "px-5 pt-3 shrink-0 flex items-center justify-between gap-3 text-xs text-[var(--fg-tertiary)]",
  workspaceTopicHeader: "flex min-w-0 shrink-0 items-center justify-between gap-3 border-b border-[var(--vui-border-subtle)] px-6 py-4 text-sm [&>strong]:min-w-0 [&>strong]:truncate",
  workspaceCollection: "min-h-0 min-w-0 w-full flex-1 overflow-auto p-6",
  workspaceCollectionTitle: "text-lg font-semibold mt-0 mb-5",
} as const;
