const border = "border-[var(--vui-border-subtle)]";
const muted = "text-[var(--fg-tertiary)]";
export default {
  frame: "finance-research-workspace flex h-[calc(100dvh_-_var(--shell-topbar-height))] min-h-0 min-w-0 flex-col overflow-hidden bg-[var(--vui-surface-panel)] text-[var(--fg-primary)]",
  heading: `flex min-h-12 shrink-0 items-center justify-between gap-2 border-b ${border} px-5`,
  brand: "flex min-w-0 items-center gap-2.5 text-sm font-semibold",
  brandIcon: "grid h-8 w-8 shrink-0 place-items-center rounded-md bg-[color-mix(in_srgb,var(--state-success)_10%,transparent)] text-[var(--state-success)]",
  actions: "flex shrink-0 items-center gap-1",
  market: `finance-market-state text-xs ${muted}`,
  split: "h-full flex-1 !gap-0 overflow-hidden",
  rail: `flex h-full min-h-0 flex-col gap-5 overflow-y-auto bg-[var(--vui-surface-row)] p-3`,
  aside: `flex h-full min-h-0 flex-col gap-4 overflow-y-auto bg-[var(--vui-surface-row)] p-4`,
  sectionHeading: `flex items-center justify-between gap-2 text-xs font-medium ${muted}`,
  libraryHeading: "flex items-center gap-2",
  fields: "grid min-w-0 gap-3",
  field: `grid min-w-0 gap-1.5 text-xs ${muted}`,
  input: "!h-10 !w-full min-w-0 text-sm",
  newButton: "!min-h-9 !w-full !justify-start gap-2",
  records: "grid min-w-0 gap-1",
  record: "!h-auto !min-h-14 !w-full !max-w-full !justify-start !rounded-md !px-2.5 !py-2 text-left",
  selected: "!bg-[color-mix(in_srgb,var(--state-success)_10%,transparent)] !text-[var(--state-success)]",
  rowText: "grid min-w-0 w-full gap-1 text-left [&>strong]:truncate [&>strong]:text-xs [&>strong]:font-medium",
  small: `text-xs leading-relaxed ${muted}`,
  link: "!min-h-10 !justify-start text-xs",
  context: `flex shrink-0 flex-wrap items-center justify-between gap-2 border-b ${border} px-5 py-3`,
  contextTitle: "flex min-w-0 items-center gap-2 text-sm font-medium [&>span]:truncate",
  contextMeta: `text-xs ${muted}`,
  tasks: "flex items-center gap-1 [&>button]:!min-h-10 [&>button]:!px-3 [&>button]:text-xs",
  native: "flex min-h-0 min-w-0 flex-1 flex-col overflow-hidden [&_.tabStrip]:hidden [&_[data-vui-region=chat-conversation-center]]:!grid-rows-[minmax(0,1fr)] [&_.emptyState]:!border-0 [&_.emptyState]:!bg-transparent [&_.emptyState]:!shadow-none [&_[data-vui=conversation-starter-cards]]:hidden [&_[data-vui=chat-session-workbench-shell]]:!h-full [&_[data-vui=chat-session-workbench-shell]]:!max-h-full [&_[data-vui=chat-session-workbench-shell]]:!min-h-0",
  state: "flex min-h-0 flex-1 items-center justify-center overflow-auto px-5 py-8",
  stateSurface: "!max-w-md !border-0 !bg-transparent !shadow-none",
  sourceList: "grid min-w-0 gap-1",
  sourceButton: "!h-auto !min-h-14 !w-full !max-w-full !justify-start !px-2 !py-2 text-left",
  detail: `grid min-w-0 gap-3 border-t ${border} pt-4`,
  facts: "grid grid-cols-[auto_minmax(0,1fr)] gap-x-3 gap-y-2 text-xs [&>dt]:text-[var(--fg-tertiary)] [&>dd]:m-0 [&>dd]:break-words",
  excerpt: `m-0 whitespace-pre-wrap break-words border-l-2 border-[var(--state-success)] pl-3 text-xs leading-7 text-[var(--fg-secondary)]`,
  skeleton: "grid gap-4 py-4",
  frameLoading: "flex min-h-0 flex-1 flex-col gap-5 p-6 overflow-hidden",
  frameLoadingHeading: "grid grid-cols-[2fr_1fr] gap-6",
  frameLoadingTitle: "h-12",
  frameLoadingFacts: "grid grid-cols-6 gap-5",
  frameLoadingChart: "min-h-[290px] flex-1",
  frameLoadingConfig: "h-24",
  libraryCitation: "grid gap-2 border-b border-[var(--vui-border-subtle)] pb-3",
  libraryCitationTitle: "text-xs",
  workspaceHistoryLoading: "grid gap-4",
  workspaceNav: "grid gap-1",
  workspaceSection: "grid gap-2",
  workspaceSearchButton: "!justify-start !h-auto !py-2 !w-full",
  workspaceSearchText: "grid gap-1 text-left",
  workspaceStockName: "text-xs",
  workspaceWatchlistButton: "!justify-start !w-full !h-auto !py-2",
  workspaceWatchlistRow: "flex w-full justify-between gap-2 text-xs",
  workspaceTruncate: "truncate",
  workspaceTicker: "font-mono text-[var(--fg-tertiary)]",
  workspaceStorageWarning: "text-xs text-[var(--state-warning)]",
  workspaceRecent: "grid gap-2 border-t border-[var(--vui-border-subtle)] pt-4",
  workspaceAside: "flex min-h-0 h-full flex-col overflow-hidden bg-[var(--vui-surface-row)]",
  workspaceAsideTabs: "shrink-0 px-3 pt-3",
  workspaceAsideBody: "flex-1 min-h-0 overflow-y-auto",
  workspaceErrorText: "block break-words",
  workspaceViewTabs: "shrink-0 px-6 py-3 border-b border-[var(--vui-border-subtle)]",
  workspaceOverview: "min-h-0 flex-1 overflow-y-auto p-6 grid content-start gap-5",
  workspaceChatHeading: "px-5 pt-3 shrink-0 flex items-center justify-between gap-3 text-xs text-[var(--fg-tertiary)]",
  workspaceCollection: "min-h-0 flex-1 overflow-auto p-6",
  workspaceCollectionTitle: "text-lg font-semibold mt-0 mb-5",
  workspaceWatchlistCard: "flex items-center justify-between gap-4 border border-[var(--vui-border-subtle)]",
  workspaceWatchlistIdentity: "flex items-center gap-4",
  workspaceWatchlistName: "text-sm",
  workspaceWatchlistActions: "flex gap-2",
  workspaceNavButton: "!justify-start !w-full",
  workspaceNavSelected: "!bg-[color-mix(in_srgb,var(--accent-cool)_9%,transparent)] !text-[var(--accent-cool)]",
} as const;
