const styles = {
  currentMarker: "ml-2 font-normal text-vui-xs text-vui-fg-tertiary",
  runtimeStack: "flex min-w-0 items-center gap-2",
  windowState: "text-vui-xs text-vui-fg-tertiary",
  heading: "m-0 text-xl font-semibold",
  description: "mb-0 mt-1 text-vui-xs text-vui-fg-secondary",
  connectionStatus: "text-vui-xs text-vui-fg-secondary",
  searchField: "relative min-w-40 flex-1",
  searchIcon: "pointer-events-none absolute left-3 top-1/2 z-10 -translate-y-1/2 text-vui-fg-tertiary",
  filterSelect: "!w-36 !shrink-0",
  listError: "mx-7 mb-3 shrink-0 max-[640px]:mx-4",
  desktopList: "max-[700px]:hidden",
  mobileList: "hidden max-[700px]:block",
  mobileRow: "border-b border-vui-border-subtle px-3 py-3",
  mobileBranchButton: "!min-h-11 !max-w-full !justify-start !px-0",
  mobileBranchName: "truncate",
  mobileActions: "flex flex-wrap items-center justify-between gap-2",
  listFooter: "flex shrink-0 justify-between border-t border-vui-border-subtle px-7 py-3 text-vui-xs text-vui-fg-tertiary",
  runtimeRunning: "text-[var(--state-success)]",
  runtimeFailed: "text-[var(--state-error)]",
  runtimeOther: "text-vui-fg-secondary",
  panel: "flex h-full min-h-0 min-w-0 flex-1 flex-col overflow-hidden bg-vui-surface-panel",
  panelBody: "flex min-h-0 min-w-0 flex-1 flex-col",
  panelHeader:
    "flex min-w-0 shrink-0 items-start justify-between gap-3 px-7 pb-3 pt-4 max-[640px]:px-4",
  panelEyebrow: "m-0 [font-size:var(--vui-font-xs)] uppercase tracking-[0.08em] text-vui-fg-tertiary",
  panelHeaderActions: "ml-auto flex shrink-0 flex-wrap items-center justify-end gap-1.5",
  controlWindow: "m-0 flex min-w-0 items-center gap-1.5 [font-size:var(--vui-font-xs)] text-vui-fg-secondary",
  filterRow: "flex min-w-0 shrink-0 flex-wrap items-center gap-3 px-7 pb-4 max-[640px]:px-4",
  filterBar: "flex min-w-0 flex-[1_1_34rem] flex-wrap items-center gap-1.5",
  searchInput: "!min-h-9 w-full !pl-9 max-[640px]:!min-h-11",
  errorReason: "mt-0.5 block max-w-[18rem] truncate [font-size:var(--vui-font-2xs)] text-vui-fg-tertiary",
  tabBar: "min-w-0 flex-none",
  tabLabel: "inline-flex min-w-0 items-center gap-1.5",
  tabCount:
    "inline-flex min-w-5 items-center justify-center rounded-full border border-vui-border-subtle bg-vui-control-muted px-1.5 py-0.5 [font-size:var(--vui-font-2xs)] text-vui-fg-secondary",
  tabBody: "min-h-0 min-w-0 flex-1 overflow-auto border-t border-vui-border-subtle px-5 max-[640px]:px-2",
  tabHeader: "flex min-w-0 shrink-0 flex-wrap items-end justify-between gap-2",
  tabHint: "m-0 min-w-0 [font-size:var(--vui-font-xs)] text-vui-fg-tertiary",
  tabHeaderActions: "ml-auto flex min-w-0 flex-wrap items-center gap-1.5",
  globalEmpty: "mx-7 my-5",
  pager: "inline-flex min-w-0 items-center gap-1.5",
  rangeLabel: "min-w-0 truncate text-[var(--fg-muted)]",
  notice: "min-w-0 flex-auto truncate text-[var(--fg-secondary)]",
  noticeError: "min-w-0 flex-auto truncate text-[var(--state-error)]",
  statusTable: "min-h-0 min-w-0 w-full !rounded-none !border-0 !bg-transparent [&_[role=columnheader]]:!py-2 [&_[role=columnheader]]:!font-medium [&_[role=cell]]:!py-2",
  selectCell: "w-9 !px-1",
  branchName: "font-medium text-[var(--fg-primary)]",
  actionCell: "z-[1] min-w-0",
  actionButtons: "flex !flex-nowrap items-center justify-end gap-1",
  actionStack: "grid min-w-0 justify-items-end gap-0.5",
  rowFeedback: "mt-0.5 block max-w-[18rem] truncate text-left [font-size:var(--vui-font-2xs)] text-vui-fg-tertiary",
  rowFeedbackError: "mt-0.5 block max-w-[18rem] truncate text-left [font-size:var(--vui-font-2xs)] text-[var(--state-error)]",
  confirmList: "m-0 flex list-none flex-col gap-2 p-0 text-left",
  confirmItem: "min-w-0 rounded-md border border-[var(--border-soft)] bg-[var(--vui-surface-row)] px-2 py-1.5",
  confirmName: "m-0 text-[var(--fg-primary)]",
  confirmPath: "m-0 truncate text-[var(--fg-tertiary)]",
  confirmRisks: "m-0 mt-1 list-disc pl-4 text-[var(--state-warning)]",
} as const;

export default styles;
