const panelSurface = "rounded-lg border border-vui-border-subtle bg-vui-surface-panel/72";
const primaryControl =
  "inline-flex min-h-7 w-fit max-w-full flex-none items-center justify-center gap-1.5 rounded-[var(--radius-control)] border border-[color-mix(in_srgb,var(--accent-primary)_34%,transparent)] bg-[color-mix(in_srgb,var(--accent-primary)_12%,var(--vui-control-muted))] px-2 text-[var(--vui-font-xs)] leading-none text-vui-fg-primary no-underline hover:border-[color-mix(in_srgb,var(--accent-primary)_44%,transparent)] hover:bg-[color-mix(in_srgb,var(--accent-primary)_18%,var(--vui-control-muted))] disabled:cursor-default disabled:opacity-55 [&[data-vui]]:min-w-0";

const styles = {
  segmentedControl: "inline-flex min-w-0 items-center gap-0.5 rounded-[var(--radius-control)] border border-vui-border-subtle bg-vui-surface-toolbar p-0.5 max-[860px]:justify-self-start [&_button]:min-h-[25px] [&_button]:rounded-[calc(var(--radius-control)-2px)] [&_button]:border-0 [&_button]:bg-transparent [&_button]:px-[7px] [&_button]:py-[3px] [&_button]:text-[var(--vui-font-xs)] [&_button]:leading-none [&_button]:text-vui-fg-secondary [&_button[data-active=true]]:bg-[color-mix(in_srgb,var(--accent-primary)_12%,var(--vui-control-muted))] [&_button[data-active=true]]:text-vui-fg-primary [&_button:disabled]:cursor-default [&_button:disabled]:opacity-60 [&_button[data-vui]]:min-w-0 [&_button[data-vui]_[data-slot=vui-button-content]]:inline-flex [&_button[data-vui]_[data-slot=vui-button-content]]:items-center [&_button[data-vui]_[data-slot=vui-button-content]]:gap-[5px] [&_button[data-vui]_[data-slot=vui-button-label]]:inline-flex [&_button[data-vui]_[data-slot=vui-button-label]]:items-center [&_button[data-vui]_[data-slot=vui-button-label]]:gap-[5px]",
  settingError: "col-span-full text-[var(--vui-font-xs)] text-[var(--state-error)]",
  settingField: "grid min-w-0 gap-[3px] [&>span]:text-[var(--vui-font-xs)] [&>span]:uppercase [&>span]:tracking-[0.06em] [&>span]:text-[var(--fg-tertiary)] [&>small]:min-w-0 [&>small]:truncate [&>small]:text-[var(--vui-font-xs)] [&>small]:text-[var(--fg-secondary)] [&_input]:min-h-7 [&_input]:w-full [&_input]:min-w-0 [&_input]:rounded-[var(--radius-control)] [&_input]:border [&_input]:border-[var(--border-soft)] [&_input]:bg-[var(--surface-card)] [&_input]:px-[7px] [&_input]:py-[3px] [&_input]:text-[var(--vui-font-xs)] [&_input]:text-[var(--fg-primary)] [&_select]:min-h-7 [&_select]:w-full [&_select]:min-w-0 [&_select]:rounded-[var(--radius-control)] [&_select]:border [&_select]:border-[var(--border-soft)] [&_select]:bg-[var(--surface-card)] [&_select]:px-[7px] [&_select]:py-[3px] [&_select]:text-[var(--vui-font-xs)] [&_select]:text-[var(--fg-primary)]",
  settingToggle: "inline-flex min-h-7 min-w-0 items-center gap-1.5 whitespace-nowrap pb-px [&>span]:text-[var(--vui-font-xs)] [&>span]:uppercase [&>span]:tracking-[0.06em] [&>span]:text-[var(--fg-tertiary)] [&_input]:m-0 [&_input]:h-3.5 [&_input]:w-3.5",
  settingsHeader: "grid self-center gap-0.5 [&>span]:text-[var(--vui-font-xs)] [&>span]:uppercase [&>span]:tracking-[0.06em] [&>span]:text-[var(--fg-tertiary)] [&>strong]:min-w-0 [&>strong]:truncate [&>strong]:text-[var(--vui-font-xs)] [&>strong]:text-[var(--fg-primary)] [&>small]:min-w-0 [&>small]:truncate [&>small]:text-[var(--vui-font-xs)] [&>small]:text-[var(--fg-secondary)]",
  settingsSaveButton: `${primaryControl} py-[3px]`,
  settingsStrip: `mx-3 mt-1.5 grid min-w-0 grid-cols-[minmax(110px,0.78fr)_minmax(92px,0.6fr)_repeat(3,minmax(82px,0.52fr))_max-content_minmax(96px,0.62fr)_minmax(104px,0.68fr)_max-content_max-content_max-content] items-end gap-1.5 self-start ${panelSurface} px-2 py-[7px] max-[1200px]:grid-cols-[max-content_max-content_minmax(0,1fr)] max-[860px]:grid-cols-[minmax(0,1fr)] [&>small]:col-span-full`,
  spin: "animate-spin",
} as const;

export default styles;
