export const launcherRouteStyles: Record<string, string> = {
  route:
    "grid h-full min-h-full content-start overflow-y-auto overflow-x-hidden overscroll-contain bg-[var(--surface-page)] pb-[max(12px,env(safe-area-inset-bottom))] text-[var(--fg-primary)] [scrollbar-gutter:stable] [--accent-primary:var(--accent-warm)] [--danger:var(--state-error)]",
  header:
    "mx-2.5 mt-2 min-w-0 border-[var(--vui-border-subtle)] bg-[color-mix(in_srgb,var(--surface-panel)_86%,transparent)] shadow-[var(--vui-shadow-hairline)]",
  panelEyebrow: "m-0 text-[0.68rem] uppercase tracking-[0.08em] text-[var(--fg-tertiary)]",
  statusBar:
    "grid w-[min(760px,58vw)] min-w-0 grid-cols-[minmax(220px,1fr)_max-content] items-center gap-2 max-[1200px]:w-full max-[1200px]:max-w-none max-[1200px]:grid-cols-[minmax(0,1fr)] max-[1200px]:justify-items-stretch",
  statusBarReason:
    "grid min-h-7 min-w-0 grid-cols-[minmax(76px,max-content)_minmax(94px,max-content)_minmax(0,1fr)] items-center gap-1.5 rounded-[var(--radius-control)] border border-[var(--border-soft)] bg-[color-mix(in_srgb,var(--surface-card)_90%,var(--surface-page))] px-2 data-[tone=success]:border-[color-mix(in_srgb,var(--state-success)_34%,var(--border-soft))] data-[tone=warning]:border-[color-mix(in_srgb,var(--state-warning)_38%,var(--border-soft))] data-[tone=error]:border-[color-mix(in_srgb,var(--state-error)_38%,var(--border-soft))] max-[860px]:grid-cols-[minmax(0,1fr)] [&_span]:whitespace-nowrap [&_span]:text-[0.66rem] [&_span]:uppercase [&_span]:tracking-[0.06em] [&_span]:text-[var(--fg-tertiary)] [&_strong]:min-w-0 [&_strong]:truncate [&_strong]:text-[0.82rem] [&_strong]:text-[var(--fg-primary)] [&_small]:min-w-0 [&_small]:truncate [&_small]:text-[0.74rem] [&_small]:text-[var(--fg-secondary)] max-[860px]:[&_span]:whitespace-normal max-[860px]:[&_span]:overflow-visible max-[860px]:[&_span]:overflow-wrap-anywhere max-[860px]:[&_strong]:whitespace-normal max-[860px]:[&_strong]:overflow-visible max-[860px]:[&_strong]:overflow-wrap-anywhere max-[860px]:[&_small]:whitespace-normal max-[860px]:[&_small]:overflow-visible max-[860px]:[&_small]:overflow-wrap-anywhere",
  statusBarActions:
    "flex min-w-0 flex-wrap items-center justify-end gap-1.5 max-[1200px]:justify-start",
  primaryButton:
    "inline-flex min-h-7 w-fit max-w-full flex-none items-center justify-center gap-1.5 rounded-[var(--radius-control)] border border-[color-mix(in_srgb,var(--accent-primary)_36%,var(--border-soft))] bg-[color-mix(in_srgb,var(--accent-primary)_10%,var(--surface-card))] px-2 text-[0.8rem] leading-none text-[var(--fg-primary)] no-underline hover:border-[var(--border-strong)] hover:bg-[var(--surface-panel-hover)] disabled:cursor-default disabled:opacity-55 [&[data-vui]]:min-w-0",
  iconButton:
    "inline-flex min-h-7 w-fit max-w-full flex-none items-center justify-center gap-1.5 rounded-[var(--radius-control)] border border-[var(--border-soft)] bg-[color-mix(in_srgb,var(--surface-card)_86%,var(--surface-page))] px-2 text-[0.8rem] leading-none text-[var(--fg-secondary)] no-underline hover:border-[var(--border-strong)] hover:bg-[var(--surface-panel-hover)] hover:text-[var(--fg-primary)] disabled:cursor-default disabled:opacity-55 [&[data-vui]]:min-w-0",
  statusBarButton:
    "inline-flex min-h-7 w-fit max-w-full flex-none items-center justify-center gap-1.5 rounded-[var(--radius-control)] border border-[var(--border-soft)] bg-[color-mix(in_srgb,var(--surface-card)_86%,var(--surface-page))] px-2 text-[0.8rem] leading-none text-[var(--fg-secondary)] no-underline hover:border-[var(--border-strong)] hover:bg-[var(--surface-panel-hover)] hover:text-[var(--fg-primary)] disabled:cursor-default disabled:opacity-55 [&[data-vui]]:min-w-0",
  dangerButton:
    "border-[color-mix(in_srgb,var(--danger)_34%,var(--border-soft))] bg-[color-mix(in_srgb,var(--danger)_7%,var(--surface-card))] text-[color-mix(in_srgb,var(--danger)_74%,var(--fg-primary))] hover:border-[color-mix(in_srgb,var(--danger)_52%,var(--border-strong))] hover:bg-[color-mix(in_srgb,var(--danger)_12%,var(--surface-card))] hover:text-[var(--fg-primary)]",
  summaryStrip: "grid grid-cols-4 gap-1.5 px-3 pt-2 max-[1200px]:grid-cols-2 max-[620px]:grid-cols-1",
  userGuide:
    "mx-3 mt-1.5 grid min-w-0 grid-cols-[max-content_minmax(132px,max-content)_max-content] items-center gap-2 rounded-[7px] border border-[var(--border-soft)] bg-[color-mix(in_srgb,var(--surface-panel)_88%,transparent)] px-[9px] py-1.5 data-[tone=success]:border-[color-mix(in_srgb,var(--state-success)_38%,var(--border-soft))] data-[tone=warning]:border-[color-mix(in_srgb,var(--state-warning)_42%,var(--border-soft))] data-[tone=error]:border-[color-mix(in_srgb,var(--state-error)_42%,var(--border-soft))] max-[1200px]:grid-cols-[max-content_minmax(132px,max-content)_minmax(0,1fr)] max-[860px]:grid-cols-[minmax(0,1fr)] [&_span]:text-[0.66rem] [&_span]:uppercase [&_span]:tracking-[0.06em] [&_span]:text-[var(--fg-tertiary)] [&_strong]:min-w-0 [&_strong]:truncate [&_strong]:text-[0.86rem] [&_strong]:text-[var(--fg-primary)] [&_em]:min-w-0 [&_em]:truncate [&_em]:text-[0.74rem] [&_em]:not-italic [&_em]:text-[var(--fg-secondary)] max-[1200px]:[&_em]:col-[2/-1] max-[860px]:[&_em]:col-auto max-[860px]:[&_em]:whitespace-normal max-[860px]:[&_em]:overflow-visible max-[860px]:[&_em]:overflow-wrap-anywhere",
  dangerZone:
    "mx-3 mt-1.5 grid min-w-0 grid-cols-[max-content_minmax(0,1fr)_max-content] items-center gap-2 rounded-[7px] border border-[color-mix(in_srgb,var(--danger)_30%,var(--border-soft))] bg-[color-mix(in_srgb,var(--danger)_4%,var(--surface-panel))] px-[9px] py-1.5 max-[860px]:grid-cols-[minmax(0,1fr)] [&_span]:whitespace-nowrap [&_span]:text-[0.72rem] [&_span]:font-bold [&_span]:text-[color-mix(in_srgb,var(--danger)_72%,var(--fg-primary))] [&_small]:min-w-0 [&_small]:truncate [&_small]:text-[0.74rem] [&_small]:text-[var(--fg-secondary)] max-[860px]:[&_small]:whitespace-normal max-[860px]:[&_small]:overflow-visible max-[860px]:[&_small]:overflow-wrap-anywhere",
  dangerActions: "flex min-w-0 justify-end max-[860px]:justify-start",
  settingsStrip:
    "mx-3 mt-1.5 grid min-w-0 grid-cols-[minmax(110px,0.78fr)_minmax(92px,0.6fr)_repeat(3,minmax(82px,0.52fr))_max-content_minmax(96px,0.62fr)_minmax(104px,0.68fr)_max-content_max-content_max-content] items-end gap-1.5 self-start rounded-[7px] border border-[var(--border-soft)] bg-[color-mix(in_srgb,var(--surface-panel)_90%,transparent)] px-2 py-[7px] max-[1200px]:grid-cols-[max-content_max-content_minmax(0,1fr)] max-[860px]:grid-cols-[minmax(0,1fr)] [&>small]:col-span-full",
  settingsHeader:
    "grid self-center gap-0.5 [&>span]:text-[0.66rem] [&>span]:uppercase [&>span]:tracking-[0.06em] [&>span]:text-[var(--fg-tertiary)] [&>strong]:min-w-0 [&>strong]:truncate [&>strong]:text-[0.8rem] [&>strong]:text-[var(--fg-primary)] [&>small]:min-w-0 [&>small]:truncate [&>small]:text-[0.74rem] [&>small]:text-[var(--fg-secondary)]",
  settingField:
    "grid min-w-0 gap-[3px] [&>span]:text-[0.66rem] [&>span]:uppercase [&>span]:tracking-[0.06em] [&>span]:text-[var(--fg-tertiary)] [&>small]:min-w-0 [&>small]:truncate [&>small]:text-[0.74rem] [&>small]:text-[var(--fg-secondary)] [&_input]:min-h-7 [&_input]:w-full [&_input]:min-w-0 [&_input]:rounded-[var(--radius-control)] [&_input]:border [&_input]:border-[var(--border-soft)] [&_input]:bg-[var(--surface-card)] [&_input]:px-[7px] [&_input]:py-[3px] [&_input]:text-[0.78rem] [&_input]:text-[var(--fg-primary)] [&_select]:min-h-7 [&_select]:w-full [&_select]:min-w-0 [&_select]:rounded-[var(--radius-control)] [&_select]:border [&_select]:border-[var(--border-soft)] [&_select]:bg-[var(--surface-card)] [&_select]:px-[7px] [&_select]:py-[3px] [&_select]:text-[0.78rem] [&_select]:text-[var(--fg-primary)]",
  settingToggle:
    "inline-flex min-h-7 min-w-0 items-center gap-1.5 whitespace-nowrap pb-px [&>span]:text-[0.66rem] [&>span]:uppercase [&>span]:tracking-[0.06em] [&>span]:text-[var(--fg-tertiary)] [&_input]:m-0 [&_input]:h-3.5 [&_input]:w-3.5",
  settingsSaveButton:
    "inline-flex min-h-7 items-center justify-center gap-[5px] rounded-[var(--radius-control)] border border-[color-mix(in_srgb,var(--accent-primary)_34%,var(--border-soft))] bg-[color-mix(in_srgb,var(--accent-primary)_9%,var(--surface-card))] px-2 py-[3px] text-[0.76rem] text-[var(--fg-primary)] disabled:cursor-default disabled:opacity-60 [&[data-vui]]:min-w-0",
  settingError: "col-span-full text-[0.74rem] text-[var(--state-error)]",
  segmentedControl:
    "inline-flex min-w-0 items-center gap-0.5 rounded-[var(--radius-control)] border border-[var(--border-soft)] bg-[var(--surface-card)] p-0.5 max-[860px]:justify-self-start [&_button]:min-h-[25px] [&_button]:rounded-[calc(var(--radius-control)-2px)] [&_button]:border-0 [&_button]:bg-transparent [&_button]:px-[7px] [&_button]:py-[3px] [&_button]:text-[0.76rem] [&_button]:leading-none [&_button]:text-[var(--fg-secondary)] [&_button[data-active=true]]:bg-[color-mix(in_srgb,var(--accent-primary)_11%,var(--surface-panel))] [&_button[data-active=true]]:text-[var(--fg-primary)] [&_button:disabled]:cursor-default [&_button:disabled]:opacity-60 [&_button[data-vui]]:min-w-0 [&_button[data-vui]_[data-slot=vui-button-content]]:inline-flex [&_button[data-vui]_[data-slot=vui-button-content]]:items-center [&_button[data-vui]_[data-slot=vui-button-content]]:gap-[5px] [&_button[data-vui]_[data-slot=vui-button-label]]:inline-flex [&_button[data-vui]_[data-slot=vui-button-label]]:items-center [&_button[data-vui]_[data-slot=vui-button-label]]:gap-[5px]",
  developerPanel:
    "mx-3 mt-1.5 grid min-w-0 gap-1.5 rounded-[7px] border border-[var(--border-soft)] bg-[color-mix(in_srgb,var(--surface-panel)_90%,transparent)] px-2 py-[7px] data-[enabled=true]:border-[color-mix(in_srgb,var(--state-warning)_42%,var(--border-soft))]",
  developerPanelHeader:
    "flex min-w-0 items-center justify-between gap-2 max-[860px]:flex-col max-[860px]:items-start [&>div]:grid [&>div]:min-w-0 [&>div]:gap-0.5 [&_strong]:text-[0.8rem] [&_strong]:text-[var(--fg-primary)]",
  developerGrid: "grid min-w-0 grid-cols-[minmax(138px,0.42fr)_minmax(300px,1fr)_minmax(260px,0.82fr)] gap-1.5 max-[1200px]:grid-cols-[minmax(0,1fr)]",
  developerStatus:
    "grid min-w-0 content-start gap-1 rounded-[7px] border border-[var(--border-soft)] bg-[color-mix(in_srgb,var(--surface-card)_88%,transparent)] p-[7px] data-[tone=warning]:border-[color-mix(in_srgb,var(--state-warning)_42%,var(--border-soft))] [&_span]:text-[0.66rem] [&_span]:uppercase [&_span]:tracking-[0.06em] [&_span]:text-[var(--fg-tertiary)] [&_strong]:min-w-0 [&_strong]:truncate [&_strong]:text-[0.82rem] [&_strong]:text-[var(--fg-primary)] [&_small]:min-w-0 [&_small]:truncate [&_small]:text-[0.74rem] [&_small]:text-[var(--fg-secondary)]",
  developerNoise: "grid min-w-0 gap-1.5 rounded-[7px] border border-[var(--border-soft)] bg-[color-mix(in_srgb,var(--surface-card)_88%,transparent)] p-[7px]",
  developerNoiseHeader: "flex min-w-0 items-center justify-between gap-2 [&_span]:text-[0.66rem] [&_span]:uppercase [&_span]:tracking-[0.06em] [&_span]:text-[var(--fg-tertiary)]",
  compactButton:
    "inline-flex min-h-6 items-center justify-center gap-[5px] rounded-[var(--radius-control)] border border-[var(--border-soft)] bg-[color-mix(in_srgb,var(--surface-card)_90%,var(--surface-page))] px-1.5 py-[3px] text-[0.74rem] text-[var(--fg-secondary)] disabled:cursor-default disabled:opacity-60 [&[data-vui]]:min-w-0",
  noiseItemGrid: "grid min-w-0 grid-cols-4 gap-[5px] max-[860px]:grid-cols-[minmax(0,1fr)]",
  noiseItem:
    "grid min-w-0 gap-0.5 rounded-md border border-[color-mix(in_srgb,var(--border-soft)_72%,transparent)] px-1.5 py-[5px] data-[protected=true]:opacity-80 [&_span]:min-w-0 [&_span]:truncate [&_span]:text-[0.72rem] [&_span]:text-[var(--fg-secondary)] [&_strong]:min-w-0 [&_strong]:truncate [&_strong]:text-[0.8rem] [&_strong]:text-[var(--fg-primary)] [&_small]:min-w-0 [&_small]:truncate [&_small]:text-[0.72rem] [&_small]:text-[var(--fg-secondary)]",
  cleanupConsole: "grid min-w-0 gap-1.5 rounded-[7px] border border-[var(--border-soft)] bg-[color-mix(in_srgb,var(--surface-card)_88%,transparent)] p-[7px]",
  cleanupMetrics:
    "flex min-w-0 flex-wrap items-center gap-1.5 [&_span]:text-[0.66rem] [&_span]:uppercase [&_span]:tracking-[0.06em] [&_span]:text-[var(--fg-tertiary)] [&_strong]:text-[var(--fg-primary)] max-[620px]:grid max-[620px]:grid-cols-[minmax(0,1fr)]",
  cleanupActions: "flex min-w-0 flex-wrap items-center gap-1.5 max-[620px]:grid max-[620px]:grid-cols-[minmax(0,1fr)]",
  cleanupPlan:
    "grid min-w-0 gap-[3px] rounded-md border border-[color-mix(in_srgb,var(--state-warning)_34%,var(--border-soft))] bg-[color-mix(in_srgb,var(--state-warning)_6%,var(--surface-card))] p-1.5 [&_strong]:min-w-0 [&_strong]:truncate [&_strong]:text-[0.78rem] [&_strong]:text-[var(--fg-primary)] [&_small]:min-w-0 [&_small]:truncate [&_small]:text-[0.72rem] [&_small]:text-[var(--fg-secondary)] [&_li]:min-w-0 [&_li]:truncate [&_li]:text-[0.72rem] [&_li]:text-[var(--fg-secondary)] [&_ul]:m-0 [&_ul]:grid [&_ul]:min-w-0 [&_ul]:gap-0.5 [&_ul]:pl-4",
  metric:
    "grid min-w-0 grid-cols-[minmax(72px,max-content)_minmax(0,1fr)] items-baseline gap-x-[7px] gap-y-0.5 rounded-[7px] border border-[color-mix(in_srgb,var(--border-soft)_90%,var(--surface-page))] bg-[var(--surface-panel)] px-[9px] py-[7px] data-[tone=success]:border-[color-mix(in_srgb,var(--state-success)_38%,var(--border-soft))] data-[tone=warning]:border-[color-mix(in_srgb,var(--state-warning)_42%,var(--border-soft))] data-[tone=error]:border-[color-mix(in_srgb,var(--state-error)_42%,var(--border-soft))] max-[620px]:grid-cols-[82px_minmax(0,1fr)] [&_span]:text-[0.66rem] [&_span]:uppercase [&_span]:tracking-[0.06em] [&_span]:text-[var(--fg-tertiary)] [&_strong]:min-w-0 [&_strong]:truncate [&_strong]:text-[var(--fg-primary)] [&_small]:col-span-full [&_small]:min-w-0 [&_small]:truncate [&_small]:text-[0.72rem] [&_small]:leading-tight [&_small]:text-[var(--fg-secondary)]",
  notice:
    "mx-3 mt-1.5 grid gap-0.5 rounded-[7px] border border-[var(--border-soft)] bg-[color-mix(in_srgb,var(--surface-panel)_92%,transparent)] px-2 py-1.5 text-[0.82rem] text-[var(--fg-secondary)] data-[tone=success]:border-[color-mix(in_srgb,var(--state-success)_34%,transparent)] data-[tone=success]:text-[var(--state-success)] data-[tone=warning]:border-[color-mix(in_srgb,var(--state-warning)_34%,transparent)] data-[tone=warning]:text-[var(--state-warning)] data-[tone=error]:border-[color-mix(in_srgb,var(--state-error)_34%,transparent)] data-[tone=error]:text-[var(--state-error)] [&_span]:min-w-0 [&_span]:truncate [&_span]:text-[0.72rem] [&_span]:text-[var(--fg-tertiary)]",
  workspace:
    "grid min-h-0 grid-cols-[minmax(0,1fr)] auto-rows-auto gap-1.5 overflow-visible px-3 pb-[max(14px,env(safe-area-inset-bottom))] pt-1.5 max-[1200px]:flex max-[1200px]:flex-col",
  panel: "block min-h-0 min-w-0 rounded-[7px] border border-[var(--border-soft)] bg-[var(--surface-panel)] px-[9px] py-[7px] max-[1200px]:flex-none",
  matrixPanel: "col-auto",
  panelHeader:
    "flex min-w-0 items-baseline justify-between gap-2.5 border-b border-[var(--border-soft)] pb-1.5 [&>*]:min-w-0 [&_strong]:flex-auto [&_strong]:truncate [&_strong]:text-right [&_strong]:text-[var(--fg-primary)]",
  guardStrip:
    "my-1.5 grid min-w-0 grid-cols-[minmax(82px,max-content)_minmax(128px,max-content)_minmax(0,1fr)] items-center gap-[7px] rounded-[7px] border border-[var(--border-soft)] bg-[color-mix(in_srgb,var(--surface-card)_88%,transparent)] px-2 py-1.5 data-[tone=success]:border-[color-mix(in_srgb,var(--state-success)_34%,var(--border-soft))] data-[tone=warning]:border-[color-mix(in_srgb,var(--state-warning)_40%,var(--border-soft))] max-[620px]:grid-cols-[minmax(0,1fr)] [&_span]:text-[0.66rem] [&_span]:uppercase [&_span]:tracking-[0.06em] [&_span]:text-[var(--fg-tertiary)] [&_strong]:min-w-0 [&_strong]:truncate [&_strong]:text-[0.82rem] [&_strong]:text-[var(--fg-primary)] [&_small]:min-w-0 [&_small]:truncate [&_small]:text-[0.76rem] [&_small]:text-[var(--fg-secondary)]",
  specGrid:
    "mt-2 grid min-w-0 grid-cols-[minmax(72px,max-content)_minmax(0,1fr)] gap-x-2.5 gap-y-1.5 [&_dt]:m-0 [&_dt]:min-w-0 [&_dt]:text-[0.66rem] [&_dt]:uppercase [&_dt]:tracking-[0.06em] [&_dt]:text-[var(--fg-tertiary)] [&_dd]:m-0 [&_dd]:min-w-0 [&_dd]:truncate [&_dd]:text-[0.78rem] [&_dd]:leading-tight [&_dd]:text-[var(--fg-primary)]",
  diagnosticsGrid:
    "grid min-w-0 grid-cols-[minmax(72px,max-content)_minmax(0,1fr)] gap-x-2.5 gap-y-1.5 px-2.5 pb-2.5 [&_dt]:m-0 [&_dt]:min-w-0 [&_dt]:text-[0.66rem] [&_dt]:uppercase [&_dt]:tracking-[0.06em] [&_dt]:text-[var(--fg-tertiary)] [&_dd]:m-0 [&_dd]:min-w-0 [&_dd]:truncate [&_dd]:text-[0.78rem] [&_dd]:leading-tight [&_dd]:text-[var(--fg-primary)]",
  statusTable: "mt-1.5 grid min-w-0 overflow-hidden rounded-[7px] border border-[var(--border-soft)]",
  guardianTable: "mt-1.5 grid min-w-0 overflow-hidden rounded-[7px] border border-[var(--border-soft)]",
  statusHead:
    "grid min-w-0 grid-cols-[minmax(140px,0.9fr)_minmax(92px,0.62fr)_minmax(160px,0.95fr)_minmax(0,1.7fr)] items-center gap-[7px] border-b border-[var(--border-soft)] bg-[color-mix(in_srgb,var(--surface-card)_94%,var(--surface-page))] px-2 py-1.5 text-[0.66rem] uppercase tracking-[0.06em] text-[var(--fg-tertiary)] max-[860px]:grid-cols-[minmax(118px,0.9fr)_minmax(82px,0.7fr)_minmax(0,1.4fr)] max-[860px]:[&>span:nth-child(3)]:hidden max-[620px]:grid-cols-[minmax(0,1fr)] max-[620px]:[&>span:nth-child(n+3)]:hidden",
  statusRow:
    "grid min-w-0 grid-cols-[minmax(140px,0.9fr)_minmax(92px,0.62fr)_minmax(160px,0.95fr)_minmax(0,1.7fr)] items-center gap-[7px] border-t border-[color-mix(in_srgb,var(--border-soft)_72%,transparent)] bg-[color-mix(in_srgb,var(--surface-page)_74%,var(--surface-card))] px-2 py-1.5 text-[0.78rem] text-[var(--fg-secondary)] first:border-t-0 data-[tone=success]:border-l-2 data-[tone=success]:border-l-[var(--state-success)] data-[tone=warning]:border-l-2 data-[tone=warning]:border-l-[var(--state-warning)] data-[tone=error]:border-l-2 data-[tone=error]:border-l-[var(--state-error)] max-[860px]:grid-cols-[minmax(118px,0.9fr)_minmax(82px,0.7fr)_minmax(0,1.4fr)] max-[860px]:[&>span:nth-child(3)]:hidden max-[620px]:grid-cols-[minmax(0,1fr)] max-[620px]:[&>span:nth-child(n+3)]:hidden [&_span]:min-w-0 [&_span]:truncate [&_strong]:text-[var(--fg-primary)]",
  guardianHead:
    "grid min-w-0 grid-cols-[minmax(178px,1fr)_minmax(120px,0.7fr)_minmax(84px,0.52fr)_minmax(0,1.7fr)] items-center gap-[7px] border-b border-[var(--border-soft)] bg-[color-mix(in_srgb,var(--surface-card)_94%,var(--surface-page))] px-2 py-1.5 text-[0.66rem] uppercase tracking-[0.06em] text-[var(--fg-tertiary)] max-[860px]:grid-cols-[minmax(140px,1fr)_minmax(96px,0.65fr)_minmax(82px,0.5fr)_minmax(0,1.4fr)] max-[620px]:grid-cols-[minmax(0,1fr)] max-[620px]:[&>span:nth-child(n+3)]:hidden",
  guardianRow:
    "grid min-w-0 grid-cols-[minmax(178px,1fr)_minmax(120px,0.7fr)_minmax(84px,0.52fr)_minmax(0,1.7fr)] items-center gap-[7px] border-t border-[color-mix(in_srgb,var(--border-soft)_72%,transparent)] bg-[color-mix(in_srgb,var(--surface-page)_74%,var(--surface-card))] px-2 py-1.5 text-[0.78rem] text-[var(--fg-secondary)] first:border-t-0 data-[tone=success]:border-l-2 data-[tone=success]:border-l-[var(--state-success)] data-[tone=warning]:border-l-2 data-[tone=warning]:border-l-[var(--state-warning)] data-[tone=error]:border-l-2 data-[tone=error]:border-l-[var(--state-error)] max-[860px]:grid-cols-[minmax(140px,1fr)_minmax(96px,0.65fr)_minmax(82px,0.5fr)_minmax(0,1.4fr)] max-[620px]:grid-cols-[minmax(0,1fr)] max-[620px]:[&>span:nth-child(n+3)]:hidden [&_span]:min-w-0 [&_span]:truncate [&_strong]:text-[var(--fg-primary)]",
  commandLine:
    "mt-2 grid min-w-0 grid-cols-[88px_minmax(0,1fr)] gap-x-2 gap-y-[5px] rounded-lg border border-[var(--border-soft)] bg-[color-mix(in_srgb,var(--surface-card)_72%,transparent)] px-[9px] py-[7px] max-[620px]:grid-cols-[minmax(0,1fr)] [&_span]:text-[0.66rem] [&_span]:uppercase [&_span]:tracking-[0.06em] [&_span]:text-[var(--fg-tertiary)] [&_strong]:min-w-0 [&_strong]:truncate [&_strong]:text-[0.78rem] [&_strong]:text-[var(--fg-primary)] [&_small]:col-start-2 [&_small]:min-w-0 [&_small]:truncate [&_small]:text-[0.74rem] [&_small]:text-[var(--fg-secondary)] max-[620px]:[&_small]:col-start-1",
  recoveryLine:
    "mt-2 grid min-w-0 grid-cols-[88px_minmax(0,1fr)] gap-x-2 gap-y-[5px] rounded-lg border border-[var(--border-soft)] bg-[color-mix(in_srgb,var(--surface-card)_72%,transparent)] px-[9px] py-[7px] data-[tone=success]:border-[color-mix(in_srgb,var(--state-success)_36%,var(--border-soft))] data-[tone=warning]:border-[color-mix(in_srgb,var(--state-warning)_42%,var(--border-soft))] max-[620px]:grid-cols-[minmax(0,1fr)] [&_span]:text-[0.66rem] [&_span]:uppercase [&_span]:tracking-[0.06em] [&_span]:text-[var(--fg-tertiary)] [&_strong]:min-w-0 [&_strong]:truncate [&_strong]:text-[0.78rem] [&_strong]:text-[var(--fg-primary)] [&_small]:col-start-2 [&_small]:min-w-0 [&_small]:truncate [&_small]:text-[0.74rem] [&_small]:text-[var(--fg-secondary)] max-[620px]:[&_small]:col-start-1",
  compactList: "mt-2 grid min-w-0 gap-[5px] [&>small]:text-[var(--fg-secondary)]",
  compactItem:
    "grid min-w-0 grid-cols-[minmax(150px,0.74fr)_minmax(0,1fr)] gap-2 border-b border-[color-mix(in_srgb,var(--border-soft)_68%,transparent)] py-[5px] data-[tone=success]:[&_strong]:text-[var(--state-success)] data-[tone=error]:[&_strong]:text-[var(--state-error)] max-[620px]:grid-cols-[minmax(0,1fr)] [&_strong]:min-w-0 [&_strong]:truncate [&_strong]:text-[0.78rem] [&_strong]:text-[var(--fg-primary)] [&_small]:min-w-0 [&_small]:truncate [&_small]:text-[0.74rem] [&_small]:text-[var(--fg-secondary)]",
  guardianSummary:
    "mt-2 grid min-w-0 grid-cols-[minmax(0,1fr)_repeat(3,max-content)_auto] items-center gap-2 text-[0.8rem] text-[var(--fg-secondary)] max-[860px]:grid-cols-2 max-[860px]:[&_span]:col-span-full max-[620px]:grid-cols-[minmax(0,1fr)] [&_span]:min-w-0 [&_span]:truncate [&_strong]:min-w-0 [&_strong]:truncate [&_strong]:font-semibold [&_strong]:text-[var(--fg-primary)]",
  diagnosticsPanel:
    "col-auto block min-h-0 p-0 [&_summary]:flex [&_summary]:min-w-0 [&_summary]:cursor-pointer [&_summary]:items-baseline [&_summary]:justify-between [&_summary]:gap-2.5 [&_summary]:px-2.5 [&_summary]:py-2 [&_summary]:text-[var(--fg-secondary)] [&_summary_span]:text-[0.68rem] [&_summary_span]:uppercase [&_summary_span]:tracking-[0.08em] [&_summary_span]:text-[var(--fg-tertiary)] [&_summary_strong]:text-[var(--fg-primary)]",
  diagnosticsBody: "grid min-w-0 grid-cols-2 gap-2 px-2.5 pb-2.5 max-[620px]:grid-cols-[minmax(0,1fr)]",
  diagnosticSection:
    "min-w-0 rounded-lg border border-[var(--border-soft)] bg-[color-mix(in_srgb,var(--surface-card)_65%,transparent)] p-2",
  spin: "animate-spin",
};
