const styles = {
  cleanupConsole: "grid min-w-0 gap-1.5 rounded-[7px] border border-[var(--border-soft)] bg-[color-mix(in_srgb,var(--surface-card)_88%,transparent)] p-[7px]",
  cleanupMetrics: "flex min-w-0 flex-wrap items-center gap-1.5 [&_span]:text-[var(--vui-font-xs)] [&_span]:uppercase [&_span]:tracking-[0.06em] [&_span]:text-[var(--fg-tertiary)] [&_strong]:text-[var(--fg-primary)] max-[620px]:grid max-[620px]:grid-cols-[minmax(0,1fr)]",
  cleanupPlan: "grid min-w-0 gap-[3px] rounded-md border border-[color-mix(in_srgb,var(--state-warning)_34%,var(--border-soft))] bg-[color-mix(in_srgb,var(--state-warning)_6%,var(--surface-card))] p-1.5 [&_strong]:min-w-0 [&_strong]:truncate [&_strong]:text-[var(--vui-font-xs)] [&_strong]:text-[var(--fg-primary)] [&_small]:min-w-0 [&_small]:truncate [&_small]:text-[var(--vui-font-xs)] [&_small]:text-[var(--fg-secondary)] [&_li]:min-w-0 [&_li]:truncate [&_li]:text-[var(--vui-font-xs)] [&_li]:text-[var(--fg-secondary)] [&_ul]:m-0 [&_ul]:grid [&_ul]:min-w-0 [&_ul]:gap-0.5 [&_ul]:pl-4",
  developerGrid: "grid min-w-0 grid-cols-[minmax(138px,0.42fr)_minmax(300px,1fr)_minmax(260px,0.82fr)] gap-1.5 max-[1200px]:grid-cols-[minmax(0,1fr)]",
  developerNoise: "grid min-w-0 gap-1.5 rounded-[7px] border border-[var(--border-soft)] bg-[color-mix(in_srgb,var(--surface-card)_88%,transparent)] p-[7px]",
  developerNoiseHeader: "flex min-w-0 items-center justify-between gap-2 [&_span]:text-[var(--vui-font-xs)] [&_span]:uppercase [&_span]:tracking-[0.06em] [&_span]:text-[var(--fg-tertiary)]",
  developerPanel: "mx-3 mt-1.5 grid min-w-0 gap-1.5 rounded-[7px] border border-[var(--border-soft)] bg-[color-mix(in_srgb,var(--surface-panel)_90%,transparent)] px-2 py-[7px] data-[enabled=true]:border-[color-mix(in_srgb,var(--state-warning)_42%,var(--border-soft))]",
  developerPanelHeader: "flex min-w-0 items-center justify-between gap-2 max-[860px]:flex-col max-[860px]:items-start [&>div]:grid [&>div]:min-w-0 [&>div]:gap-0.5 [&_strong]:text-[var(--vui-font-xs)] [&_strong]:text-[var(--fg-primary)]",
  developerStatus: "grid min-w-0 content-start gap-1 rounded-[7px] border border-[var(--border-soft)] bg-[color-mix(in_srgb,var(--surface-card)_88%,transparent)] p-[7px] data-[tone=warning]:border-[color-mix(in_srgb,var(--state-warning)_42%,var(--border-soft))] [&_span]:text-[var(--vui-font-xs)] [&_span]:uppercase [&_span]:tracking-[0.06em] [&_span]:text-[var(--fg-tertiary)] [&_strong]:min-w-0 [&_strong]:truncate [&_strong]:text-[var(--vui-font-xs)] [&_strong]:text-[var(--fg-primary)] [&_small]:min-w-0 [&_small]:truncate [&_small]:text-[var(--vui-font-xs)] [&_small]:text-[var(--fg-secondary)]",
  iconButton: "inline-flex min-h-7 w-fit max-w-full flex-none items-center justify-center gap-1.5 rounded-[var(--radius-control)] border border-[var(--border-soft)] bg-[color-mix(in_srgb,var(--surface-card)_86%,var(--surface-page))] px-2 text-[var(--vui-font-xs)] leading-none text-[var(--fg-secondary)] no-underline hover:border-[var(--border-strong)] hover:bg-[var(--surface-panel-hover)] hover:text-[var(--fg-primary)] disabled:cursor-default disabled:opacity-55 [&[data-vui]]:min-w-0",
  noiseItem: "grid min-w-0 gap-0.5 rounded-md border border-[color-mix(in_srgb,var(--border-soft)_72%,transparent)] px-1.5 py-[5px] data-[protected=true]:opacity-80 [&_span]:min-w-0 [&_span]:truncate [&_span]:text-[var(--vui-font-xs)] [&_span]:text-[var(--fg-secondary)] [&_strong]:min-w-0 [&_strong]:truncate [&_strong]:text-[var(--vui-font-xs)] [&_strong]:text-[var(--fg-primary)] [&_small]:min-w-0 [&_small]:truncate [&_small]:text-[var(--vui-font-xs)] [&_small]:text-[var(--fg-secondary)]",
  noiseItemGrid: "grid min-w-0 grid-cols-4 gap-[5px] max-[860px]:grid-cols-[minmax(0,1fr)]",
  panelEyebrow: "m-0 text-[var(--vui-font-xs)] uppercase tracking-[0.08em] text-[var(--fg-tertiary)]",
  primaryButton: "inline-flex min-h-7 w-fit max-w-full flex-none items-center justify-center gap-1.5 rounded-[var(--radius-control)] border border-[color-mix(in_srgb,var(--accent-primary)_36%,var(--border-soft))] bg-[color-mix(in_srgb,var(--accent-primary)_10%,var(--surface-card))] px-2 text-[var(--vui-font-xs)] leading-none text-[var(--fg-primary)] no-underline hover:border-[var(--border-strong)] hover:bg-[var(--surface-panel-hover)] disabled:cursor-default disabled:opacity-55 [&[data-vui]]:min-w-0",
  segmentedControl: "inline-flex min-w-0 items-center gap-0.5 rounded-[var(--radius-control)] border border-[var(--border-soft)] bg-[var(--surface-card)] p-0.5 max-[860px]:justify-self-start [&_button]:min-h-[25px] [&_button]:rounded-[calc(var(--radius-control)-2px)] [&_button]:border-0 [&_button]:bg-transparent [&_button]:px-[7px] [&_button]:py-[3px] [&_button]:text-[var(--vui-font-xs)] [&_button]:leading-none [&_button]:text-[var(--fg-secondary)] [&_button[data-active=true]]:bg-[color-mix(in_srgb,var(--accent-primary)_11%,var(--surface-panel))] [&_button[data-active=true]]:text-[var(--fg-primary)] [&_button:disabled]:cursor-default [&_button:disabled]:opacity-60 [&_button[data-vui]]:min-w-0 [&_button[data-vui]_[data-slot=vui-button-content]]:inline-flex [&_button[data-vui]_[data-slot=vui-button-content]]:items-center [&_button[data-vui]_[data-slot=vui-button-content]]:gap-[5px] [&_button[data-vui]_[data-slot=vui-button-label]]:inline-flex [&_button[data-vui]_[data-slot=vui-button-label]]:items-center [&_button[data-vui]_[data-slot=vui-button-label]]:gap-[5px]",
  spin: "animate-spin",
} as const;

export default styles;
