import { vuiRailFillClass, vuiWorkspaceFillClass } from "../design/vuiSurfaceRecipes";

const muted = "text-[var(--fg-tertiary)]";
const search = "focus-within:ring-2 focus-within:ring-[var(--accent-cool)] flex min-w-0 items-center gap-2 rounded-lg border border-vui-border-subtle bg-vui-surface-panel px-2 text-[var(--fg-tertiary)] [&_input]:min-w-0 [&_input]:w-full [&_input]:!border-0 [&_input]:!bg-transparent [&_input]:!shadow-none [&_input]:!outline-none [&_input]:text-sm";
const styles = {
  agentMemoryWorkspace: "agentMemoryWorkspace flex h-full min-h-0 min-w-0 flex-1 overflow-hidden",
  workspace: `workspace h-full min-h-0 w-full overflow-hidden !gap-0 ${vuiWorkspaceFillClass} max-lg:[&>[data-vui=split-sidebar]]:!hidden max-lg:[&>[role=separator]]:!hidden`,
  agentRail: `flex h-full min-h-0 flex-col p-3 ${vuiRailFillClass}`,
  railHeading: `mb-3 px-2 text-xs font-semibold ${muted}`,
  searchBox: `${search} mb-4`,
  railScroll: "min-h-0 flex-1 overflow-y-auto",
  groupHeading: `mb-2 flex items-center gap-2 px-2 text-xs ${muted}`,
  agentList: "grid gap-1",
  agentRow: "!h-auto !min-h-14 !w-full !justify-start !gap-2 !rounded-lg !border-0 !px-2 !py-2 text-left",
  agentRowActive: "!bg-[color-mix(in_srgb,var(--accent-cool)_10%,var(--vui-surface-row))]",
  avatar: "flex size-8 shrink-0 items-center justify-center rounded-lg bg-vui-surface-inset text-xs font-semibold text-[var(--accent-cool)]",
  agentIdentity: "flex min-w-0 flex-1 flex-col gap-1 [&_strong]:truncate [&_strong]:text-sm [&_strong]:font-semibold [&_small]:text-xs [&_small]:font-normal [&_small]:text-[var(--fg-tertiary)]",
  selectedDot: "size-1.5 shrink-0 rounded-full bg-[var(--accent-cool)]",
  groupToggle: `!mt-3 !h-auto !w-full !justify-start !gap-2 !border-0 !bg-transparent !px-2 !py-2 !shadow-none text-xs ${muted} [&>span:last-child]:ml-auto`,
  emptyState: `emptyState p-3 text-sm leading-relaxed ${muted}`,
  reader: "flex h-full min-h-0 min-w-0 flex-1 flex-col bg-vui-surface-panel",
  mobileSwitch: "!h-10 !shrink-0 !justify-start !gap-2 !rounded-none !border-0 !border-b !border-vui-border-subtle !px-3 lg:!hidden",
  mobileDialog: "!transform-none !h-[min(80dvh,640px)] !p-0 overflow-hidden",
  libraryWorkspace: "h-full min-h-0 flex-1 !gap-0 max-md:[&>[role=separator]]:!hidden",
  mobileReading: "max-md:[&>[data-vui=split-sidebar]]:!hidden",
  mobileListing: "max-md:[&>[data-vui=split-main]]:!hidden max-md:[&>[data-vui=split-sidebar]]:!w-full max-md:[&>[data-vui=split-sidebar]]:!max-w-none max-md:[&>[data-vui=split-sidebar]]:!basis-full max-md:[&>[data-vui=split-sidebar]]:!min-w-0",
  library: "flex h-full min-h-0 min-w-0 flex-col border-r border-vui-border-subtle bg-vui-surface-panel",
  libraryControls: "flex min-h-14 shrink-0 items-center gap-2 border-b border-vui-border-subtle px-3 py-2",
  memorySearch: `${search} flex-1`,
  category: "!w-24 !shrink-0",
  listScroll: "min-h-0 flex-1 overflow-y-auto p-2",
  memoryRow: "!mb-1 !h-auto !w-full !flex-col !items-stretch !justify-start !gap-2 !rounded-lg !border-0 !px-3 !py-3 text-left !whitespace-normal",
  memoryRowActive: "!bg-[color-mix(in_srgb,var(--accent-cool)_9%,var(--vui-surface-panel))]",
  rowMeta: `flex min-w-0 items-center justify-between gap-2 text-xs font-normal ${muted} [&_time]:truncate`,
  rowTitle: "line-clamp-2 text-sm font-semibold leading-6 [overflow-wrap:anywhere]",
  rowExcerpt: `line-clamp-2 text-xs font-normal leading-5 [overflow-wrap:anywhere] ${muted}`,
  loading: "grid gap-5 p-4",
  mobileBack: "!h-10 !shrink-0 !justify-start !gap-2 !px-4 md:!hidden",
  tabs: "!flex min-h-0 flex-1 flex-col !gap-0",
  tabList: "!min-h-14 !shrink-0 !justify-start !gap-3 !rounded-none !border-0 !border-b !border-vui-border-subtle !bg-transparent !px-4",
  tabTrigger: "!rounded-none !border-0 !bg-transparent !px-0 !py-3 !font-medium !shadow-none data-[state=active]:!border-b-2 data-[state=active]:!border-[var(--accent-cool)] data-[state=active]:!text-[var(--accent-cool)]",
  tabContent: "min-h-0 flex-1 overflow-y-auto",
  readingContent: "mx-auto w-full max-w-[900px] px-5 py-6 lg:px-8",
  documentHeader: "mb-6",
  documentTitle: "break-words text-xl font-semibold leading-relaxed",
  documentMeta: `mt-2 text-xs ${muted}`,
  documentBody: "min-w-0 space-y-5 [overflow-wrap:anywhere] [&_p]:!leading-8 [&_p]:!text-[var(--fg-secondary)] [&_dl]:!gap-5 [&_dt]:!text-sm [&_dt]:!text-[var(--fg-primary)] [&_dd]:!mt-2 [&_dd]:!leading-8 [&_dd]:!text-[var(--fg-secondary)] [&_ul]:list-disc [&_li]:leading-8",
  notice: `my-4 text-sm leading-6 ${muted}`,
  sourceFields: "grid gap-2 text-sm [&_dt]:text-[var(--fg-tertiary)] [&_dd]:mb-3 [&_dd]:break-all [&_dd]:leading-6",
  raw: "mt-4 overflow-x-auto whitespace-pre-wrap rounded-lg bg-vui-surface-inset p-4 text-xs leading-6 [overflow-wrap:anywhere]",
  emptyReader: "p-6",
} as const;
export default styles;
