import { createVuiStyleMap } from "../components/vui/styles/createVuiStyleMap";

const styleKeys = [
  "activeChannelPill",
  "agentMemoryViewStack",
  "agentMemoryWorkspace",
  "bulkActionBar",
  "buttonRow",
  "channelPill",
  "cleanupConfirmField",
  "cleanupExecuteButton",
  "cleanupExecutePanel",
  "cleanupExecutionSummary",
  "cleanupFeedback",
  "cleanupInlineWarning",
  "cleanupPathList",
  "cleanupPreviewCounts",
  "cleanupPreviewItem",
  "cleanupPreviewList",
  "cleanupPreviewPanel",
  "cleanupStats",
  "cleanupTargetList",
  "cleanupTargetPanel",
  "cleanupTargetRow",
  "cleanupWarning",
  "cleanupWorkspace",
  "collapsedFormButton",
  "compactItemMeta",
  "compactItemPrimary",
  "compactItemSummary",
  "compactMemoryList",
  "contractDomainGrid",
  "contractDomainRow",
  "contractForbiddenList",
  "contractPrinciples",
  "contractStateGrid",
  "controlStrip",
  "copyNotice",
  "countPill",
  "detailActionButton",
  "detailActions",
  "detailHeader",
  "detailMeta",
  "detailPanel",
  "editPreviewGrid",
  "editPreviewPanel",
  "effectiveGrid",
  "emptyDetail",
  "emptyState",
  "factGrid",
  "fieldStack",
  "filterButton",
  "filterButtonActive",
  "filterGroup",
  "formActionRow",
  "generatedAt",
  "governanceMiniPanel",
  "graphCanvasFallback",
  "graphCanvasLabels",
  "graphCanvasMount",
  "graphCanvasPanel",
  "graphCanvasShell",
  "graphCanvasToolbar",
  "graphClearFocusButton",
  "graphInteractionHint",
  "graphKnowledgeContent",
  "graphKnowledgeItem",
  "graphKnowledgeList",
  "graphKnowledgePanel",
  "graphNodeBadge",
  "graphNodeBadgeQuestion",
  "graphNodeBadgeType",
  "graphNodeList",
  "graphNodeTypeMark",
  "graphRelationEmpty",
  "graphRelationGroup",
  "graphRelationHeader",
  "graphRelationPanel",
  "graphResponsibilityPanel",
  "graphTypeList",
  "graphViewStack",
  "graphWorkspace",
  "header",
  "headerActions",
  "healthStrip",
  "iconButton",
  "impactPanel",
  "inlineActionButton",
  "inlineCheck",
  "itemBadges",
  "itemButton",
  "itemButtonActive",
  "itemButtonCompact",
  "itemButtonDense",
  "itemContentButton",
  "itemContentButtonDense",
  "itemHeader",
  "itemList",
  "itemOrigin",
  "itemPanel",
  "itemPath",
  "itemSelectionRow",
  "itemSelectionRowDense",
  "itemSummary",
  "knowledgeFormGrid",
  "knowledgeGovernanceDeck",
  "knowledgeItemCard",
  "knowledgeItems",
  "knowledgeMain",
  "knowledgeModeTab",
  "knowledgeModeTabActive",
  "knowledgeModeTabs",
  "knowledgeProposalList",
  "knowledgeRow",
  "knowledgeStewardPanel",
  "knowledgeViewStack",
  "knowledgeWorkspace",
  "manageDetailPanel",
  "manageFilterHeader",
  "manageFilterPanel",
  "manageFormPanel",
  "manageItemBadges",
  "manageItemFooter",
  "manageItemMeta",
  "manageItemPrimary",
  "manageItemSummary",
  "manageListPanel",
  "managementActions",
  "managementHeader",
  "managementPanel",
  "manageSourceFilters",
  "manageWorkspace",
  "matrixCard",
  "matrixCardActive",
  "matrixCardButton",
  "matrixGrid",
  "matrixHeader",
  "matrixHeaderMeta",
  "matrixPanel",
  "overviewGrid",
  "overviewPanel",
  "panelError",
  "panelEyebrow",
  "panelHeader",
  "panelLead",
  "panelNotice",
  "permissionMatrix",
  "permissionRow",
  "pipelineBoundary",
  "pipelineHeader",
  "pipelineIndex",
  "pipelinePanel",
  "pipelineStep",
  "pipelineSteps",
  "primaryActionButton",
  "projectMemoryProposalActions",
  "projectMemoryProposalFiles",
  "projectMemoryProposalList",
  "projectMemoryProposalMain",
  "projectMemoryProposalMeta",
  "projectMemoryProposalNote",
  "projectMemoryProposalResolved",
  "projectMemoryProposalRow",
  "projectMemoryProposalTitleLine",
  "projectMemoryQueueControls",
  "projectMemoryQueuePanel",
  "projectMemoryQueueStats",
  "queueToolbar",
  "ragContextCard",
  "ragContextList",
  "ragContextMeta",
  "ragHealthStrip",
  "ragPolicyStrip",
  "ragPreviewHeader",
  "ragPreviewPanel",
  "ratingControls",
  "rawPanel",
  "refreshButton",
  "returnButton",
  "reviewQueueActions",
  "reviewQueueBody",
  "reviewQueueItem",
  "reviewQueueList",
  "reviewQueuePanel",
  "reviewQueueSummary",
  "reviewQueueTime",
  "reviewQueueTitleLine",
  "reviewRank",
  "reviewReasonList",
  "reviewReasonPill",
  "route",
  "searchBox",
  "sectionPanel",
  "selectedConfigSummary",
  "sourceButton",
  "sourceButtonActive",
  "sourceChip",
  "sourceChipActive",
  "sourceCopy",
  "sourceGovernanceColumn",
  "sourceGovernanceControls",
  "sourceGovernanceGrid",
  "sourceIcon",
  "sourceList",
  "sourcePanel",
  "sourceRecord",
  "sourceRecordActions",
  "sourceRecordHeader",
  "sourceRecordList",
  "sourceRecordMeta",
  "sourceStats",
  "statusPill",
  "statusPillMuted",
  "statusPillPrompt",
  "statusPillVisible",
  "stewardActionGrid",
  "stewardActionRow",
  "stewardChecklist",
  "stewardGrid",
  "stewardMetric",
  "stewardMission",
  "stewardRecommendationHeader",
  "stewardRecommendationRow",
  "stewardRecommendations",
  "stewardStageCard",
  "stewardStageGrid",
  "stewardToolRows",
  "stewardWorkbench",
  "subnav",
  "subnavLink",
  "subnavLinkActive",
  "summaryCard",
  "summaryGrid",
  "usageContractPanel",
  "usageList",
  "viewStack",
  "visibilityHeader",
  "visibilityPanel",
  "warningStrip",
  "wideField",
  "workspace",
] as const;

const styles = createVuiStyleMap(styleKeys, {
  overrides: {
    compactItemMeta:
      "flex min-w-0 flex-wrap items-center gap-x-2 gap-y-0.5 text-[var(--vui-font-xs)] leading-tight text-[var(--fg-tertiary)] [&>span]:min-w-0 [&>span]:truncate",
    compactItemPrimary:
      "flex min-w-0 flex-wrap items-baseline justify-between gap-x-2 gap-y-0.5 text-[var(--vui-font-xs)] leading-tight [&>strong]:min-w-0 [&>strong]:font-semibold [&>strong]:text-[var(--fg-primary)] [&>span]:shrink-0 [&>span]:text-[var(--fg-tertiary)]",
    compactItemSummary:
      "line-clamp-2 min-w-0 text-[var(--vui-font-xs)] leading-[1.35] text-[var(--fg-secondary)]",
  },
  extensions: {
    cleanupPathList: "[&_span]:truncate",
    collapsedFormButton: "max-h-[92px]",
    compactMemoryList: "max-h-[148px]",
    contractForbiddenList: "hidden",
    contractStateGrid: "hidden",
    effectiveGrid: "[&_.overviewPanel]:max-h-[min(260px,36vh)] [&_.overviewPanel]:overflow-auto [&_.panelLead]:line-clamp-2",
    graphCanvasShell: "min-h-[360px] bg-[var(--vui-gradient-route-soft)] after:content-[''] after:[background-size:91px_91px]",
    graphKnowledgeItem: "line-clamp-3",
    graphRelationGroup: "[&_button]:w-full",
    graphWorkspace: "grid-cols-[minmax(210px,250px)_minmax(760px,1fr)_minmax(260px,0.34fr)]",
    headerActions: "justify-end",
    itemButtonDense: "min-h-[62px]",
    itemContentButtonDense: "grid-rows-[16px_14px_18px]",
    knowledgeGovernanceDeck: "hidden max-[900px]:grid-cols-[minmax(0,1fr)]",
    knowledgeMain: "[&_.managementPanel]:content-start",
    knowledgeModeTabs: "grid-cols-[repeat(5,minmax(0,1fr))]",
    knowledgeViewStack: "flex [&>.summaryGrid]:grid-cols-[repeat(4,minmax(0,1fr))] [&>.knowledgeWorkspace]:flex-1 [&>.knowledgeGovernanceDeck]:hidden",
    knowledgeWorkspace:
      "grid-cols-[minmax(170px,205px)_minmax(0,1.24fr)_minmax(260px,0.62fr)]",
    manageFormPanel: "[&>p]:hidden",
    manageItemBadges: "grid-cols-[repeat(auto-fit,minmax(82px,1fr))] max-h-[74px] [&>span]:truncate",
    graphNodeBadge:
      "data-[detail=true]:z-10 data-[agent-category=session_agent]:border-[color-mix(in_srgb,var(--accent-cool)_34%,transparent)] data-[agent-category=team_member_agent]:border-[color-mix(in_srgb,var(--accent-warm)_34%,transparent)] data-[node-type=knowledge_base]:border-[color-mix(in_srgb,var(--state-success)_32%,transparent)]",
    graphTypeList: "[&_button]:w-full [&_[data-active=true]]:border-[var(--accent-cool)]",
    manageWorkspace:
      "grid-cols-[minmax(300px,0.76fr)_minmax(0,1fr)] grid-rows-[minmax(210px,0.58fr)_minmax(260px,1fr)] [&_.manageListPanel]:row-span-2 [&_.detailPanel]:col-start-2 [&_.detailPanel]:row-start-2 [&_.detailPanel]:max-h-none",
    overviewGrid: "grid-cols-[repeat(2,minmax(0,1fr))] gap-2 max-[900px]:grid-cols-1",
    overviewPanel: "grid-rows-[auto_minmax(0,1fr)] overflow-auto",
    panelLead: "hidden",
    reviewQueueList: "overflow-auto",
    reviewQueuePanel: "max-h-[min(280px,34vh)] overflow-auto",
    reviewReasonList: "hidden",
    sourceGovernanceColumn: "[&_.sourceGovernanceControls]:grid-cols-[minmax(240px,0.92fr)_minmax(250px,1.08fr)]",
    stewardMission: "[&_small]:hidden",
    stewardMetric: "[&_small]:hidden",
    stewardRecommendations: "hidden",
    stewardWorkbench: "hidden",
    summaryCard:
      "grid min-h-[54px] grid-cols-[minmax(0,1fr)_auto] items-center gap-2 px-2 py-1.5 [&>span]:text-[var(--vui-font-xs)] [&>strong]:text-[var(--vui-font-title)]",
    summaryGrid:
      "grid-cols-[repeat(6,minmax(118px,1fr))] gap-1.5 max-[1180px]:grid-cols-3 max-[720px]:grid-cols-2",
    workspace: "grid-rows-[minmax(0,1fr)] overflow-auto",
  },
});

export default styles;
