import { createVuiStyleMap } from "../components/vui/styles/createVuiStyleMap";

const styleKeys = [
  "agentModeCard",
  "agentModeCard_live",
  "agentPanel",
  "agentReport",
  "agentReview",
  "agentTrace_agent",
  "agentTrace_context",
  "agentTrace_error",
  "agentTrace_observation",
  "agentTrace_tool",
  "agentTraceAvatar",
  "agentTraceBubble",
  "agentTraceContent",
  "agentTraceControls",
  "agentTraceDetailGroup",
  "agentTraceDetailIcon",
  "agentTraceDetailItem",
  "agentTraceDetailList",
  "agentTraceDetailSummary",
  "agentTraceHeader",
  "agentTraceLivePill",
  "agentTraceMeta",
  "agentTracePanel",
  "agentTracePanel_collapsed",
  "agentTraceTimeline",
  "agentTraceTurn",
  "cardActions",
  "cardPreviewIntro",
  "compactList",
  "compactList_warning",
  "countPill",
  "emptyText",
  "errorText",
  "evidenceCard",
  "evidenceHeader",
  "evidenceList",
  "evidencePanel",
  "evidenceRequestPanel",
  "guardrailPanel",
  "header",
  "headerActions",
  "historyPanel",
  "intakeField",
  "intakeField_medium",
  "intakeField_primary",
  "intakeField_tall",
  "intakeFields",
  "intakePanel",
  "okText",
  "outputPanel",
  "panelEyebrow",
  "panelHeader",
  "panelLead",
  "pipelinePanel",
  "primaryButton",
  "processPanel",
  "questionText",
  "riskText",
  "route",
  "scoreStrip",
  "secondaryButton",
  "sessionButton",
  "sessionDeleteButton",
  "sessionList",
  "sessionRail",
  "sessionRow",
  "sessionRow_active",
  "sideColumn",
  "sourceBar",
  "sourceBars",
  "sourceToggleButton",
  "stageBody",
  "stageCard",
  "stageCard_active",
  "stageCard_compact",
  "stageDescription",
  "stageHeader",
  "stageIndex",
  "stageList",
  "stageOutput",
  "stageOutputHeader",
  "stageRail",
  "stageResult",
  "stageResultItem",
  "stageResultItems",
  "stageResultSummary",
  "stageSelectButton",
  "state_blocked",
  "state_draft",
  "state_ready",
  "statePill",
  "statusSpinner",
  "subnav",
  "subnavLink",
  "subnavLinkActive",
  "summaryCard",
  "summaryGrid",
  "tagRow",
  "themeBody",
  "themeCard",
  "themeCard_selected",
  "themeCompareActions",
  "themeCompareHeader",
  "themeCompareMain",
  "themeCompareMetrics",
  "themeCompareQuestion",
  "themeCompareRank",
  "themeCompareReview",
  "themeCompareRow",
  "themeCompareRow_selected",
  "themeCompareTags",
  "themeGrid",
  "themeHeader",
  "themePlan",
  "themeRank",
  "traceBackToBottomButton",
  "traceGhostButton",
  "workflowModeButton",
  "workflowModeButton_active",
  "workflowModeControl",
  "workspace",
] as const;

const styles = createVuiStyleMap(styleKeys, {
  extensions: {
    summaryCard: "!grid grid-cols-[auto_minmax(0,1fr)] items-baseline gap-2 p-[var(--route-summary-padding)]",
    sessionRow:
      "!grid grid-cols-[minmax(0,1fr)_42px] items-stretch gap-0 rounded-lg border border-[var(--border-soft)] bg-[var(--surface-card)]",
    stageRail: "!grid grid-cols-[1fr] gap-1.5 min-w-0 overflow-visible pb-0",
    stageOutputHeader:
      "!grid grid-cols-[24px_minmax(0,1fr)] items-start gap-1.5 min-w-0 px-[7px] py-[5px] rounded-[7px] border border-[var(--border-soft)] bg-[color:color-mix(in_srgb,var(--surface-panel)_58%,transparent)]",
    agentTraceTurn: "!grid grid-cols-[30px_minmax(0,1fr)] gap-2.5 min-w-0",
    agentTraceDetailItem:
      "!grid grid-cols-[26px_minmax(0,1fr)] items-start gap-2 min-w-0 p-2 rounded-lg border border-[var(--border-soft)] bg-[color:color-mix(in_srgb,var(--surface-card)_72%,transparent)]",
    themeCompareHeader: "!grid grid-cols-[minmax(0,1fr)_auto] items-start gap-2 min-w-0",
    themeHeader: "!grid grid-cols-[minmax(0,1fr)_auto] items-start gap-2.5 min-w-0",
  },
});

export default styles;
