// Explicit style baseline (Phase 0, 2026-07-02 spec) — generated by
// web/scripts/bake-style-maps.ts from the previous createVuiStyleMap output;
// classes are byte-identical to what the inference produced. Every key is an
// explicit Tailwind class string; there are no name-based defaults. Edit
// values directly. This file is transitional: it is deleted in the wave that
// componentizes ResearchFlowCanvasRoute.
// Includes phantom keys (accessed by consumers but never declared in the old
// styleKeys — the Proxy synthesized them on demand) and prefix×tone-vocabulary
// coverage for dynamic `styles[`prefix_${tone}`]` lookups. Typed loosely as
// Record<string, string> because those dynamic template indexes cannot index a
// literal-keyed map; tightening is a follow-up, not Phase 0.
const styles: Record<string, string> = {
  agentRoleTag:
    "agentRoleTag min-w-0 inline-flex min-h-6 w-fit max-w-full items-center justify-center gap-1.5 rounded-full border border-[var(--vui-border-subtle)] bg-[var(--vui-control-muted)] px-2 text-[var(--vui-font-xs)] font-semibold leading-none text-[var(--fg-secondary)] border-[color-mix(in_srgb,var(--accent-cool)_28%,transparent)] bg-[color-mix(in_srgb,var(--accent-cool)_8%,transparent)] text-[var(--accent-cool)]",
  agentRoleTag_chat:
    "agentRoleTag_chat min-w-0 border-[color-mix(in_srgb,var(--accent-cool)_28%,transparent)] bg-[color-mix(in_srgb,var(--accent-cool)_8%,transparent)] text-[var(--accent-cool)]",
  agentRoleTag_general:
    "agentRoleTag_general min-w-0 border-[color-mix(in_srgb,var(--accent-cool)_28%,transparent)] bg-[color-mix(in_srgb,var(--accent-cool)_8%,transparent)] text-[var(--accent-cool)]",
  agentRoleTag_memory:
    "agentRoleTag_memory min-w-0 border-[color-mix(in_srgb,var(--accent-cool)_28%,transparent)] bg-[color-mix(in_srgb,var(--accent-cool)_8%,transparent)] text-[var(--accent-cool)]",
  agentRoleTag_research:
    "agentRoleTag_research min-w-0 border-[color-mix(in_srgb,var(--accent-cool)_28%,transparent)] bg-[color-mix(in_srgb,var(--accent-cool)_8%,transparent)] text-[var(--accent-cool)]",
  agentRoleTag_self:
    "agentRoleTag_self min-w-0 border-[color-mix(in_srgb,var(--accent-cool)_28%,transparent)] bg-[color-mix(in_srgb,var(--accent-cool)_8%,transparent)] text-[var(--accent-cool)]",
  agentRoleTag_supervised:
    "agentRoleTag_supervised min-w-0 border-[color-mix(in_srgb,var(--accent-cool)_28%,transparent)] bg-[color-mix(in_srgb,var(--accent-cool)_8%,transparent)] text-[var(--accent-cool)]",
  agentRoleTag_tool:
    "agentRoleTag_tool min-w-0 border-[color-mix(in_srgb,var(--accent-cool)_28%,transparent)] bg-[color-mix(in_srgb,var(--accent-cool)_8%,transparent)] text-[var(--accent-cool)]",
  body:
    "body min-w-0 text-[var(--vui-font-sm)] leading-[var(--vui-line-readable)] text-[var(--fg-secondary)]",
  canvas:
    "canvas min-w-0 grid min-h-0 gap-2 p-2",
  canvasLocked:
    "canvasLocked min-w-0 grid min-h-0 gap-2 p-2",
  canvasPanning:
    "canvasPanning min-w-0 grid min-h-0 gap-2 p-2",
  canvasScroller:
    "canvasScroller min-w-0 grid min-h-0 gap-2 p-2",
  canvasShell:
    "canvasShell min-w-0 grid h-full min-h-0 content-start overflow-hidden bg-[var(--surface-page)] text-[var(--fg-primary)] gap-2 p-2",
  canvasViewport:
    "canvasViewport min-w-0 grid min-h-0 gap-2 p-2",
  edge:
    "edge min-w-0",
  edgeActive:
    "edgeActive min-w-0 border-[color-mix(in_srgb,var(--accent-cool)_38%,transparent)] bg-[color-mix(in_srgb,var(--accent-cool)_11%,transparent)] text-[var(--accent-cool)] border-[color-mix(in_srgb,var(--accent-cool)_34%,transparent)] bg-[color-mix(in_srgb,var(--accent-cool)_10%,var(--vui-surface-row))]",
  edgeArrowHead:
    "edgeArrowHead min-w-0",
  edgeEndpointHandle:
    "edgeEndpointHandle min-w-0",
  edgeEndpointHandleActive:
    "edgeEndpointHandleActive min-w-0 border-[color-mix(in_srgb,var(--accent-cool)_38%,transparent)] bg-[color-mix(in_srgb,var(--accent-cool)_11%,transparent)] text-[var(--accent-cool)] border-[color-mix(in_srgb,var(--accent-cool)_34%,transparent)] bg-[color-mix(in_srgb,var(--accent-cool)_10%,var(--vui-surface-row))]",
  edgeEndpoints:
    "edgeEndpoints min-w-0",
  edgeHotspot:
    "edgeHotspot min-w-0",
  edgeHotspotActive:
    "edgeHotspotActive min-w-0 border-[color-mix(in_srgb,var(--accent-cool)_38%,transparent)] bg-[color-mix(in_srgb,var(--accent-cool)_11%,transparent)] text-[var(--accent-cool)] border-[color-mix(in_srgb,var(--accent-cool)_34%,transparent)] bg-[color-mix(in_srgb,var(--accent-cool)_10%,var(--vui-surface-row))]",
  edgeHotspotOffset:
    "edgeHotspotOffset min-w-0",
  edgeIssueList:
    "edgeIssueList min-w-0 grid min-h-0 content-start gap-1.5 overflow-auto",
  edgePair:
    "edgePair min-w-0 !grid grid-cols-[minmax(0,1fr)_auto_minmax(0,1fr)] items-center gap-2 p-2.5 rounded-lg border border-[var(--border-soft)] bg-[var(--surface-page)]",
  edgePath:
    "edgePath min-w-0 font-mono text-[var(--vui-font-xs)]",
  edgeTrack:
    "edgeTrack min-w-0",
  edgeTypeHint:
    "edgeTypeHint min-w-0 text-[var(--vui-font-xs)] leading-tight text-[var(--fg-tertiary)]",
  edgeType_active:
    "edgeType_active min-w-0 border-[color-mix(in_srgb,var(--accent-cool)_38%,transparent)] bg-[color-mix(in_srgb,var(--accent-cool)_11%,transparent)] text-[var(--accent-cool)] border-[color-mix(in_srgb,var(--accent-cool)_34%,transparent)] bg-[color-mix(in_srgb,var(--accent-cool)_10%,var(--vui-surface-row))]",
  edgeType_approval_gate:
    "edgeType_approval_gate min-w-0",
  edgeType_blocked:
    "edgeType_blocked min-w-0 border-[color-mix(in_srgb,var(--state-warning)_36%,transparent)] bg-[color-mix(in_srgb,var(--state-warning)_10%,transparent)] text-[var(--state-warning)]",
  edgeType_chat:
    "edgeType_chat min-w-0",
  edgeType_danger:
    "edgeType_danger min-w-0 border-[color-mix(in_srgb,var(--state-error)_36%,transparent)] bg-[color-mix(in_srgb,var(--state-error)_9%,transparent)] text-[var(--state-error)]",
  edgeType_done:
    "edgeType_done min-w-0",
  edgeType_error:
    "edgeType_error min-w-0 border-[color-mix(in_srgb,var(--state-error)_36%,transparent)] bg-[color-mix(in_srgb,var(--state-error)_9%,transparent)] text-[var(--state-error)]",
  edgeType_evidence_loop:
    "edgeType_evidence_loop min-w-0",
  edgeType_failed:
    "edgeType_failed min-w-0 border-[color-mix(in_srgb,var(--state-error)_36%,transparent)] bg-[color-mix(in_srgb,var(--state-error)_9%,transparent)] text-[var(--state-error)]",
  edgeType_failure:
    "edgeType_failure min-w-0",
  edgeType_general:
    "edgeType_general min-w-0",
  edgeType_human_handoff:
    "edgeType_human_handoff min-w-0",
  edgeType_idle:
    "edgeType_idle min-w-0 border-[var(--vui-border-subtle)] bg-[var(--vui-surface-row)] text-[var(--fg-tertiary)]",
  edgeType_info:
    "edgeType_info min-w-0 border-[color-mix(in_srgb,var(--accent-cool)_28%,transparent)] bg-[color-mix(in_srgb,var(--accent-cool)_8%,transparent)] text-[var(--accent-cool)]",
  edgeType_memory:
    "edgeType_memory min-w-0",
  edgeType_mental:
    "edgeType_mental min-w-0",
  edgeType_missing:
    "edgeType_missing min-w-0",
  edgeType_muted:
    "edgeType_muted min-w-0 text-[var(--vui-font-xs)] leading-tight text-[var(--fg-tertiary)]",
  edgeType_needs_evidence:
    "edgeType_needs_evidence min-w-0",
  edgeType_needs_input:
    "edgeType_needs_input min-w-0 grid gap-1 text-[var(--vui-font-xs)] text-[var(--fg-secondary)] [&_input]:min-h-[var(--vui-control-height-sm)] [&_select]:min-h-[var(--vui-control-height-sm)] [&_textarea]:min-h-20 [&_input]:w-full [&_select]:w-full [&_textarea]:w-full",
  edgeType_needs_review:
    "edgeType_needs_review min-w-0",
  edgeType_neutral:
    "edgeType_neutral min-w-0",
  edgeType_ok:
    "edgeType_ok min-w-0 border-[color-mix(in_srgb,var(--state-success)_32%,transparent)] bg-[color-mix(in_srgb,var(--state-success)_9%,transparent)] text-[var(--state-success)]",
  edgeType_pending:
    "edgeType_pending min-w-0",
  edgeType_ready:
    "edgeType_ready min-w-0 border-[color-mix(in_srgb,var(--state-success)_32%,transparent)] bg-[color-mix(in_srgb,var(--state-success)_9%,transparent)] text-[var(--state-success)]",
  edgeType_research:
    "edgeType_research min-w-0",
  edgeType_running:
    "edgeType_running min-w-0 border-[color-mix(in_srgb,var(--state-success)_32%,transparent)] bg-[color-mix(in_srgb,var(--state-success)_9%,transparent)] text-[var(--state-success)]",
  edgeType_selection:
    "edgeType_selection min-w-0",
  edgeType_self:
    "edgeType_self min-w-0",
  edgeType_skipped:
    "edgeType_skipped min-w-0",
  edgeType_stale:
    "edgeType_stale min-w-0",
  edgeType_status:
    "edgeType_status min-w-0",
  edgeType_success:
    "edgeType_success min-w-0 border-[color-mix(in_srgb,var(--state-success)_32%,transparent)] bg-[color-mix(in_srgb,var(--state-success)_9%,transparent)] text-[var(--state-success)]",
  edgeType_supervised:
    "edgeType_supervised min-w-0",
  edgeType_thought:
    "edgeType_thought min-w-0",
  edgeType_tool:
    "edgeType_tool min-w-0 border-[color-mix(in_srgb,var(--accent-warm)_24%,transparent)] bg-[color-mix(in_srgb,var(--accent-warm)_8%,transparent)] text-[var(--accent-warm)]",
  edgeType_warn:
    "edgeType_warn min-w-0",
  edgeType_warning:
    "edgeType_warning min-w-0 border-[color-mix(in_srgb,var(--state-warning)_36%,transparent)] bg-[color-mix(in_srgb,var(--state-warning)_10%,transparent)] text-[var(--state-warning)]",
  edges:
    "edges min-w-0",
  editorStack:
    "editorStack min-w-0 rounded-[var(--radius-panel)] border border-[var(--vui-border-subtle)] bg-[var(--vui-surface-glass)] shadow-[var(--vui-shadow-hairline)] p-2",
  emptyInspector:
    "emptyInspector min-w-0 text-[var(--vui-font-xs)] leading-tight text-[var(--fg-tertiary)]",
  emptyState:
    "emptyState min-w-0 text-[var(--vui-font-xs)] leading-tight text-[var(--fg-tertiary)]",
  executionBar:
    "executionBar min-w-0 flex flex-wrap items-center gap-1.5",
  executionGroup:
    "executionGroup min-w-0",
  executionHint:
    "executionHint min-w-0 text-[var(--vui-font-xs)] leading-tight text-[var(--fg-tertiary)]",
  fieldHint:
    "fieldHint min-w-0 grid gap-1 text-[var(--vui-font-xs)] text-[var(--fg-secondary)] [&_input]:min-h-[var(--vui-control-height-sm)] [&_select]:min-h-[var(--vui-control-height-sm)] [&_textarea]:min-h-20 [&_input]:w-full [&_select]:w-full [&_textarea]:w-full leading-tight text-[var(--fg-tertiary)]",
  header:
    "header min-w-0 flex flex-wrap items-center gap-1.5",
  headerActions:
    "headerActions min-w-0 flex flex-wrap items-center gap-1.5",
  iconButton:
    "iconButton min-w-0 inline-grid h-[var(--vui-control-height-sm)] min-h-[var(--vui-control-height-sm)] w-[var(--vui-control-height-sm)] min-w-[var(--vui-control-height-sm)] place-items-center rounded-[var(--radius-control)] border border-[var(--vui-border-subtle)] bg-[var(--vui-control-muted)] p-0 text-[var(--fg-secondary)] hover:border-[var(--border-strong)] hover:bg-[var(--vui-control-muted-hover)] hover:text-[var(--fg-primary)] shrink-0 text-[var(--fg-tertiary)]",
  inlineToggle:
    "inlineToggle min-w-0",
  inspector:
    "inspector min-w-0",
  inspectorBody:
    "inspectorBody min-w-0 text-[var(--vui-font-sm)] leading-[var(--vui-line-readable)] text-[var(--fg-secondary)] !grid grid-cols-[76px_minmax(0,1fr)] min-h-0 overflow-hidden",
  inspectorContent:
    "inspectorContent min-w-0 text-[var(--vui-font-sm)] leading-[var(--vui-line-readable)] text-[var(--fg-secondary)]",
  inspectorHeader:
    "inspectorHeader min-w-0 flex flex-wrap items-center gap-1.5",
  inspectorTab:
    "inspectorTab min-w-0 inline-flex min-h-[var(--vui-control-height-sm)] w-fit max-w-full items-center justify-center gap-1.5 rounded-[var(--radius-control)] border border-[var(--vui-border-subtle)] bg-[var(--vui-control-muted)] px-2 py-1 text-[var(--vui-font-xs)] font-semibold leading-tight text-[var(--fg-secondary)] hover:border-[var(--border-strong)] hover:bg-[var(--vui-control-muted-hover)] hover:text-[var(--fg-primary)] disabled:cursor-default disabled:opacity-55",
  inspectorTabActive:
    "inspectorTabActive min-w-0 border-[color-mix(in_srgb,var(--accent-cool)_38%,transparent)] bg-[color-mix(in_srgb,var(--accent-cool)_11%,transparent)] text-[var(--accent-cool)] border-[color-mix(in_srgb,var(--accent-cool)_34%,transparent)] bg-[color-mix(in_srgb,var(--accent-cool)_10%,var(--vui-surface-row))]",
  inspectorTabBadge:
    "inspectorTabBadge min-w-0 inline-flex min-h-6 w-fit max-w-full items-center justify-center gap-1.5 rounded-full border border-[var(--vui-border-subtle)] bg-[var(--vui-control-muted)] px-2 text-[var(--vui-font-xs)] font-semibold leading-none text-[var(--fg-secondary)]",
  inspectorTabs:
    "inspectorTabs min-w-0",
  issueCard:
    "issueCard min-w-0 rounded-[var(--radius-panel)] border border-[var(--vui-border-subtle)] bg-[var(--vui-surface-glass)] shadow-[var(--vui-shadow-hairline)] p-2",
  issueCardBody:
    "issueCardBody min-w-0 rounded-[var(--radius-panel)] border border-[var(--vui-border-subtle)] bg-[var(--vui-surface-glass)] shadow-[var(--vui-shadow-hairline)] p-2 text-[var(--vui-font-sm)] leading-[var(--vui-line-readable)] text-[var(--fg-secondary)]",
  issueCardError:
    "issueCardError min-w-0 rounded-[var(--radius-panel)] border border-[var(--vui-border-subtle)] bg-[var(--vui-surface-glass)] shadow-[var(--vui-shadow-hairline)] p-2 border-[color-mix(in_srgb,var(--state-error)_36%,transparent)] bg-[color-mix(in_srgb,var(--state-error)_9%,transparent)] text-[var(--state-error)]",
  issueCardHeader:
    "issueCardHeader min-w-0 rounded-[var(--radius-panel)] border border-[var(--vui-border-subtle)] bg-[var(--vui-surface-glass)] shadow-[var(--vui-shadow-hairline)] p-2 flex flex-wrap items-center gap-1.5",
  issueCardWarning:
    "issueCardWarning min-w-0 rounded-[var(--radius-panel)] border border-[var(--vui-border-subtle)] bg-[var(--vui-surface-glass)] shadow-[var(--vui-shadow-hairline)] p-2 border-[color-mix(in_srgb,var(--state-warning)_36%,transparent)] bg-[color-mix(in_srgb,var(--state-warning)_10%,transparent)] text-[var(--state-warning)]",
  issueEmpty:
    "issueEmpty min-w-0 text-[var(--vui-font-xs)] leading-tight text-[var(--fg-tertiary)]",
  issueFocusButton:
    "issueFocusButton min-w-0 inline-flex min-h-[var(--vui-control-height-sm)] w-fit max-w-full items-center justify-center gap-1.5 rounded-[var(--radius-control)] border border-[var(--vui-border-subtle)] bg-[var(--vui-control-muted)] px-2 py-1 text-[var(--vui-font-xs)] font-semibold leading-tight text-[var(--fg-secondary)] hover:border-[var(--border-strong)] hover:bg-[var(--vui-control-muted-hover)] hover:text-[var(--fg-primary)] disabled:cursor-default disabled:opacity-55",
  issueList:
    "issueList min-w-0 grid min-h-0 content-start gap-1.5 overflow-auto",
  issueMeta:
    "issueMeta min-w-0 flex flex-wrap items-center gap-1.5",
  issuePanel:
    "issuePanel min-w-0 rounded-[var(--radius-panel)] border border-[var(--vui-border-subtle)] bg-[var(--vui-surface-glass)] shadow-[var(--vui-shadow-hairline)] p-2",
  issueSummary:
    "issueSummary min-w-0 rounded-[var(--radius-panel)] border border-[var(--vui-border-subtle)] bg-[var(--vui-surface-glass)] shadow-[var(--vui-shadow-hairline)] p-2 !grid grid-cols-[repeat(2,minmax(0,1fr))] gap-2.5",
  issueSummaryError:
    "issueSummaryError min-w-0 rounded-[var(--radius-panel)] border border-[var(--vui-border-subtle)] bg-[var(--vui-surface-glass)] shadow-[var(--vui-shadow-hairline)] p-2 border-[color-mix(in_srgb,var(--state-error)_36%,transparent)] bg-[color-mix(in_srgb,var(--state-error)_9%,transparent)] text-[var(--state-error)]",
  issueSummaryOk:
    "issueSummaryOk min-w-0 rounded-[var(--radius-panel)] border border-[var(--vui-border-subtle)] bg-[var(--vui-surface-glass)] shadow-[var(--vui-shadow-hairline)] p-2 border-[color-mix(in_srgb,var(--state-success)_32%,transparent)] bg-[color-mix(in_srgb,var(--state-success)_9%,transparent)] text-[var(--state-success)]",
  issueSummaryWarning:
    "issueSummaryWarning min-w-0 rounded-[var(--radius-panel)] border border-[var(--vui-border-subtle)] bg-[var(--vui-surface-glass)] shadow-[var(--vui-shadow-hairline)] p-2 border-[color-mix(in_srgb,var(--state-warning)_36%,transparent)] bg-[color-mix(in_srgb,var(--state-warning)_10%,transparent)] text-[var(--state-warning)]",
  lockButtonActive:
    "lockButtonActive min-w-0 border-[color-mix(in_srgb,var(--accent-cool)_38%,transparent)] bg-[color-mix(in_srgb,var(--accent-cool)_11%,transparent)] text-[var(--accent-cool)] border-[color-mix(in_srgb,var(--accent-cool)_34%,transparent)] bg-[color-mix(in_srgb,var(--accent-cool)_10%,var(--vui-surface-row))]",
  node:
    "node min-w-0",
  nodeActive:
    "nodeActive min-w-0 border-[color-mix(in_srgb,var(--accent-cool)_38%,transparent)] bg-[color-mix(in_srgb,var(--accent-cool)_11%,transparent)] text-[var(--accent-cool)] border-[color-mix(in_srgb,var(--accent-cool)_34%,transparent)] bg-[color-mix(in_srgb,var(--accent-cool)_10%,var(--vui-surface-row))]",
  nodeConnectSource:
    "nodeConnectSource min-w-0",
  nodeIssueBadgeError:
    "nodeIssueBadgeError min-w-0 border-[color-mix(in_srgb,var(--state-error)_36%,transparent)] bg-[color-mix(in_srgb,var(--state-error)_9%,transparent)] text-[var(--state-error)]",
  nodeIssueBadgeWarning:
    "nodeIssueBadgeWarning min-w-0 border-[color-mix(in_srgb,var(--state-warning)_36%,transparent)] bg-[color-mix(in_srgb,var(--state-warning)_10%,transparent)] text-[var(--state-warning)]",
  nodeMeta:
    "nodeMeta min-w-0 flex flex-wrap items-center gap-1.5",
  nodeReconnectTarget:
    "nodeReconnectTarget min-w-0",
  nodeStatusCluster:
    "nodeStatusCluster min-w-0",
  nodeStatusDot:
    "nodeStatusDot min-w-0 inline-block h-2 w-2 rounded-full bg-current",
  nodeStatus_active:
    "nodeStatus_active min-w-0 border-[color-mix(in_srgb,var(--accent-cool)_38%,transparent)] bg-[color-mix(in_srgb,var(--accent-cool)_11%,transparent)] text-[var(--accent-cool)] border-[color-mix(in_srgb,var(--accent-cool)_34%,transparent)] bg-[color-mix(in_srgb,var(--accent-cool)_10%,var(--vui-surface-row))]",
  nodeStatus_approval_gate:
    "nodeStatus_approval_gate min-w-0",
  nodeStatus_blocked:
    "nodeStatus_blocked min-w-0 border-[color-mix(in_srgb,var(--state-warning)_36%,transparent)] bg-[color-mix(in_srgb,var(--state-warning)_10%,transparent)] text-[var(--state-warning)]",
  nodeStatus_chat:
    "nodeStatus_chat min-w-0",
  nodeStatus_danger:
    "nodeStatus_danger min-w-0 border-[color-mix(in_srgb,var(--state-error)_36%,transparent)] bg-[color-mix(in_srgb,var(--state-error)_9%,transparent)] text-[var(--state-error)]",
  nodeStatus_done:
    "nodeStatus_done min-w-0",
  nodeStatus_error:
    "nodeStatus_error min-w-0 border-[color-mix(in_srgb,var(--state-error)_36%,transparent)] bg-[color-mix(in_srgb,var(--state-error)_9%,transparent)] text-[var(--state-error)]",
  nodeStatus_evidence_loop:
    "nodeStatus_evidence_loop min-w-0",
  nodeStatus_failed:
    "nodeStatus_failed min-w-0 border-[color-mix(in_srgb,var(--state-error)_36%,transparent)] bg-[color-mix(in_srgb,var(--state-error)_9%,transparent)] text-[var(--state-error)]",
  nodeStatus_failure:
    "nodeStatus_failure min-w-0",
  nodeStatus_general:
    "nodeStatus_general min-w-0",
  nodeStatus_human_handoff:
    "nodeStatus_human_handoff min-w-0",
  nodeStatus_idle:
    "nodeStatus_idle min-w-0 border-[var(--vui-border-subtle)] bg-[var(--vui-surface-row)] text-[var(--fg-tertiary)]",
  nodeStatus_info:
    "nodeStatus_info min-w-0 border-[color-mix(in_srgb,var(--accent-cool)_28%,transparent)] bg-[color-mix(in_srgb,var(--accent-cool)_8%,transparent)] text-[var(--accent-cool)]",
  nodeStatus_memory:
    "nodeStatus_memory min-w-0",
  nodeStatus_mental:
    "nodeStatus_mental min-w-0",
  nodeStatus_missing:
    "nodeStatus_missing min-w-0",
  nodeStatus_muted:
    "nodeStatus_muted min-w-0 text-[var(--vui-font-xs)] leading-tight text-[var(--fg-tertiary)]",
  nodeStatus_needs_evidence:
    "nodeStatus_needs_evidence min-w-0",
  nodeStatus_needs_input:
    "nodeStatus_needs_input min-w-0 grid gap-1 text-[var(--vui-font-xs)] text-[var(--fg-secondary)] [&_input]:min-h-[var(--vui-control-height-sm)] [&_select]:min-h-[var(--vui-control-height-sm)] [&_textarea]:min-h-20 [&_input]:w-full [&_select]:w-full [&_textarea]:w-full",
  nodeStatus_needs_review:
    "nodeStatus_needs_review min-w-0",
  nodeStatus_neutral:
    "nodeStatus_neutral min-w-0",
  nodeStatus_ok:
    "nodeStatus_ok min-w-0 border-[color-mix(in_srgb,var(--state-success)_32%,transparent)] bg-[color-mix(in_srgb,var(--state-success)_9%,transparent)] text-[var(--state-success)]",
  nodeStatus_pending:
    "nodeStatus_pending min-w-0",
  nodeStatus_ready:
    "nodeStatus_ready min-w-0 border-[color-mix(in_srgb,var(--state-success)_32%,transparent)] bg-[color-mix(in_srgb,var(--state-success)_9%,transparent)] text-[var(--state-success)]",
  nodeStatus_research:
    "nodeStatus_research min-w-0",
  nodeStatus_running:
    "nodeStatus_running min-w-0 border-[color-mix(in_srgb,var(--state-success)_32%,transparent)] bg-[color-mix(in_srgb,var(--state-success)_9%,transparent)] text-[var(--state-success)]",
  nodeStatus_selection:
    "nodeStatus_selection min-w-0",
  nodeStatus_self:
    "nodeStatus_self min-w-0",
  nodeStatus_skipped:
    "nodeStatus_skipped min-w-0",
  nodeStatus_stale:
    "nodeStatus_stale min-w-0",
  nodeStatus_status:
    "nodeStatus_status min-w-0",
  nodeStatus_success:
    "nodeStatus_success min-w-0 border-[color-mix(in_srgb,var(--state-success)_32%,transparent)] bg-[color-mix(in_srgb,var(--state-success)_9%,transparent)] text-[var(--state-success)]",
  nodeStatus_supervised:
    "nodeStatus_supervised min-w-0",
  nodeStatus_thought:
    "nodeStatus_thought min-w-0",
  nodeStatus_tool:
    "nodeStatus_tool min-w-0 border-[color-mix(in_srgb,var(--accent-warm)_24%,transparent)] bg-[color-mix(in_srgb,var(--accent-warm)_8%,transparent)] text-[var(--accent-warm)]",
  nodeStatus_warn:
    "nodeStatus_warn min-w-0",
  nodeStatus_warning:
    "nodeStatus_warning min-w-0 border-[color-mix(in_srgb,var(--state-warning)_36%,transparent)] bg-[color-mix(in_srgb,var(--state-warning)_10%,transparent)] text-[var(--state-warning)]",
  nodeTitleInput:
    "nodeTitleInput min-w-0 grid gap-1 text-[var(--vui-font-xs)] text-[var(--fg-secondary)] [&_input]:min-h-[var(--vui-control-height-sm)] [&_select]:min-h-[var(--vui-control-height-sm)] [&_textarea]:min-h-20 [&_input]:w-full [&_select]:w-full [&_textarea]:w-full text-[var(--vui-font-title)] font-semibold leading-tight text-[var(--fg-primary)]",
  nodeTopline:
    "nodeTopline min-w-0",
  nodeWithError:
    "nodeWithError min-w-0 border-[color-mix(in_srgb,var(--state-error)_36%,transparent)] bg-[color-mix(in_srgb,var(--state-error)_9%,transparent)] text-[var(--state-error)]",
  nodeWithIssue:
    "nodeWithIssue min-w-0",
  observerStatus:
    "observerStatus min-w-0",
  observerStatusActive:
    "observerStatusActive min-w-0 border-[color-mix(in_srgb,var(--accent-cool)_38%,transparent)] bg-[color-mix(in_srgb,var(--accent-cool)_11%,transparent)] text-[var(--accent-cool)] border-[color-mix(in_srgb,var(--accent-cool)_34%,transparent)] bg-[color-mix(in_srgb,var(--accent-cool)_10%,var(--vui-surface-row))]",
  organizationActionRow:
    "organizationActionRow min-w-0 flex flex-wrap items-center gap-1.5 rounded-[var(--radius-control)] border border-[var(--vui-border-subtle)] bg-[var(--vui-surface-row)] p-2",
  organizationAgentCard:
    "organizationAgentCard min-w-0 rounded-[var(--radius-panel)] border border-[var(--vui-border-subtle)] bg-[var(--vui-surface-glass)] shadow-[var(--vui-shadow-hairline)] p-2 border-[color-mix(in_srgb,var(--accent-cool)_28%,transparent)] bg-[color-mix(in_srgb,var(--accent-cool)_8%,transparent)] text-[var(--accent-cool)]",
  organizationAgentList:
    "organizationAgentList min-w-0 grid min-h-0 content-start gap-1.5 overflow-auto border-[color-mix(in_srgb,var(--accent-cool)_28%,transparent)] bg-[color-mix(in_srgb,var(--accent-cool)_8%,transparent)] text-[var(--accent-cool)]",
  organizationAgentMeta:
    "organizationAgentMeta min-w-0 flex flex-wrap items-center gap-1.5 border-[color-mix(in_srgb,var(--accent-cool)_28%,transparent)] bg-[color-mix(in_srgb,var(--accent-cool)_8%,transparent)] text-[var(--accent-cool)]",
  organizationAuditAllowed:
    "organizationAuditAllowed min-w-0",
  organizationAuditBlocked:
    "organizationAuditBlocked min-w-0 border-[color-mix(in_srgb,var(--state-warning)_36%,transparent)] bg-[color-mix(in_srgb,var(--state-warning)_10%,transparent)] text-[var(--state-warning)]",
  organizationAuditCard:
    "organizationAuditCard min-w-0 rounded-[var(--radius-panel)] border border-[var(--vui-border-subtle)] bg-[var(--vui-surface-glass)] shadow-[var(--vui-shadow-hairline)] p-2",
  organizationAuditHeader:
    "organizationAuditHeader min-w-0 flex flex-wrap items-center gap-1.5",
  organizationAuditList:
    "organizationAuditList min-w-0 grid min-h-0 content-start gap-1.5 overflow-auto",
  organizationBadge:
    "organizationBadge min-w-0 inline-flex min-h-6 w-fit max-w-full items-center justify-center gap-1.5 rounded-full border border-[var(--vui-border-subtle)] bg-[var(--vui-control-muted)] px-2 text-[var(--vui-font-xs)] font-semibold leading-none text-[var(--fg-secondary)]",
  organizationBadgeBlocked:
    "organizationBadgeBlocked min-w-0 border-[color-mix(in_srgb,var(--state-warning)_36%,transparent)] bg-[color-mix(in_srgb,var(--state-warning)_10%,transparent)] text-[var(--state-warning)]",
  organizationBadgeProtected:
    "organizationBadgeProtected min-w-0",
  organizationBadgeRow:
    "organizationBadgeRow min-w-0 rounded-[var(--radius-control)] border border-[var(--vui-border-subtle)] bg-[var(--vui-surface-row)] p-2",
  organizationForm:
    "organizationForm min-w-0 grid gap-1 text-[var(--vui-font-xs)] text-[var(--fg-secondary)] [&_input]:min-h-[var(--vui-control-height-sm)] [&_select]:min-h-[var(--vui-control-height-sm)] [&_textarea]:min-h-20 [&_input]:w-full [&_select]:w-full [&_textarea]:w-full",
  organizationMessageList:
    "organizationMessageList min-w-0 grid min-h-0 content-start gap-1.5 overflow-auto text-[var(--vui-font-sm)] leading-[var(--vui-line-readable)] text-[var(--fg-secondary)]",
  organizationMetric:
    "organizationMetric min-w-0 !grid grid-cols-[auto_minmax(0,1fr)] items-center gap-x-2 gap-y-1 p-2.5 rounded-lg border border-[var(--border-soft)] bg-[var(--surface-page)]",
  organizationPanel:
    "organizationPanel min-w-0 rounded-[var(--radius-panel)] border border-[var(--vui-border-subtle)] bg-[var(--vui-surface-glass)] shadow-[var(--vui-shadow-hairline)] p-2",
  organizationProposalCard:
    "organizationProposalCard min-w-0 rounded-[var(--radius-panel)] border border-[var(--vui-border-subtle)] bg-[var(--vui-surface-glass)] shadow-[var(--vui-shadow-hairline)] p-2",
  organizationProposalList:
    "organizationProposalList min-w-0 grid min-h-0 content-start gap-1.5 overflow-auto",
  organizationSectionHeader:
    "organizationSectionHeader min-w-0 flex flex-wrap items-center gap-1.5",
  organizationSummaryGrid:
    "organizationSummaryGrid min-w-0 rounded-[var(--radius-panel)] border border-[var(--vui-border-subtle)] bg-[var(--vui-surface-glass)] shadow-[var(--vui-shadow-hairline)] p-2 grid gap-2 !grid grid-cols-[repeat(3,minmax(0,1fr))] gap-2",
  primaryButton:
    "primaryButton min-w-0 inline-flex min-h-[var(--vui-control-height-sm)] w-fit max-w-full items-center justify-center gap-1.5 rounded-[var(--radius-control)] border border-[var(--vui-border-subtle)] bg-[var(--vui-control-muted)] px-2 py-1 text-[var(--vui-font-xs)] font-semibold leading-tight text-[var(--fg-secondary)] hover:border-[var(--border-strong)] hover:bg-[var(--vui-control-muted-hover)] hover:text-[var(--fg-primary)] disabled:cursor-default disabled:opacity-55 border-[color-mix(in_srgb,var(--accent-cool)_34%,transparent)] bg-[color-mix(in_srgb,var(--accent-cool)_10%,var(--vui-surface-row))] text-[var(--accent-cool)]",
  readonlyDescription:
    "readonlyDescription min-w-0 text-[var(--vui-font-sm)] leading-[var(--vui-line-readable)] text-[var(--fg-secondary)]",
  readonlyDetailHeader:
    "readonlyDetailHeader min-w-0 rounded-[var(--radius-panel)] border border-[var(--vui-border-subtle)] bg-[var(--vui-surface-glass)] shadow-[var(--vui-shadow-hairline)] p-2 flex flex-wrap items-center gap-1.5",
  readonlySpecGrid:
    "readonlySpecGrid min-w-0 grid gap-2 !grid grid-cols-[auto_minmax(0,1fr)] gap-x-2.5 gap-y-[7px] p-2.5 rounded-lg border border-[var(--border-soft)] bg-[var(--surface-page)]",
  reconnectHint:
    "reconnectHint min-w-0 text-[var(--vui-font-xs)] leading-tight text-[var(--fg-tertiary)]",
  route:
    "route min-w-0 grid h-full min-h-0 content-start overflow-hidden bg-[var(--surface-page)] text-[var(--fg-primary)]",
  saveStatusError:
    "saveStatusError min-w-0 border-[color-mix(in_srgb,var(--state-error)_36%,transparent)] bg-[color-mix(in_srgb,var(--state-error)_9%,transparent)] text-[var(--state-error)]",
  saveStatusIdle:
    "saveStatusIdle min-w-0 border-[var(--vui-border-subtle)] bg-[var(--vui-surface-row)] text-[var(--fg-tertiary)]",
  saveStatusSuccess:
    "saveStatusSuccess min-w-0 border-[color-mix(in_srgb,var(--state-success)_32%,transparent)] bg-[color-mix(in_srgb,var(--state-success)_9%,transparent)] text-[var(--state-success)]",
  saveStatusWarning:
    "saveStatusWarning min-w-0 border-[color-mix(in_srgb,var(--state-warning)_36%,transparent)] bg-[color-mix(in_srgb,var(--state-warning)_10%,transparent)] text-[var(--state-warning)]",
  secondaryButton:
    "secondaryButton min-w-0 inline-flex min-h-[var(--vui-control-height-sm)] w-fit max-w-full items-center justify-center gap-1.5 rounded-[var(--radius-control)] border border-[var(--vui-border-subtle)] bg-[var(--vui-control-muted)] px-2 py-1 text-[var(--vui-font-xs)] font-semibold leading-tight text-[var(--fg-secondary)] hover:border-[var(--border-strong)] hover:bg-[var(--vui-control-muted-hover)] hover:text-[var(--fg-primary)] disabled:cursor-default disabled:opacity-55",
  selectionSummary:
    "selectionSummary min-w-0 rounded-[var(--radius-panel)] border border-[var(--vui-border-subtle)] bg-[var(--vui-surface-glass)] shadow-[var(--vui-shadow-hairline)] p-2",
  statusPill:
    "statusPill min-w-0 inline-flex min-h-6 w-fit max-w-full items-center justify-center gap-1.5 rounded-full border border-[var(--vui-border-subtle)] bg-[var(--vui-control-muted)] px-2 text-[var(--vui-font-xs)] font-semibold leading-none text-[var(--fg-secondary)]",
  status_active:
    "status_active min-w-0 border-[color-mix(in_srgb,var(--accent-cool)_38%,transparent)] bg-[color-mix(in_srgb,var(--accent-cool)_11%,transparent)] text-[var(--accent-cool)] border-[color-mix(in_srgb,var(--accent-cool)_34%,transparent)] bg-[color-mix(in_srgb,var(--accent-cool)_10%,var(--vui-surface-row))]",
  status_approval_gate:
    "status_approval_gate min-w-0",
  status_blocked:
    "status_blocked min-w-0 border-[color-mix(in_srgb,var(--state-warning)_36%,transparent)] bg-[color-mix(in_srgb,var(--state-warning)_10%,transparent)] text-[var(--state-warning)]",
  status_chat:
    "status_chat min-w-0",
  status_danger:
    "status_danger min-w-0 border-[color-mix(in_srgb,var(--state-error)_36%,transparent)] bg-[color-mix(in_srgb,var(--state-error)_9%,transparent)] text-[var(--state-error)]",
  status_done:
    "status_done min-w-0",
  status_error:
    "status_error min-w-0 border-[color-mix(in_srgb,var(--state-error)_36%,transparent)] bg-[color-mix(in_srgb,var(--state-error)_9%,transparent)] text-[var(--state-error)]",
  status_evidence_loop:
    "status_evidence_loop min-w-0",
  status_failed:
    "status_failed min-w-0 border-[color-mix(in_srgb,var(--state-error)_36%,transparent)] bg-[color-mix(in_srgb,var(--state-error)_9%,transparent)] text-[var(--state-error)]",
  status_failure:
    "status_failure min-w-0",
  status_general:
    "status_general min-w-0",
  status_human_handoff:
    "status_human_handoff min-w-0",
  status_idle:
    "status_idle min-w-0 border-[var(--vui-border-subtle)] bg-[var(--vui-surface-row)] text-[var(--fg-tertiary)]",
  status_info:
    "status_info min-w-0 border-[color-mix(in_srgb,var(--accent-cool)_28%,transparent)] bg-[color-mix(in_srgb,var(--accent-cool)_8%,transparent)] text-[var(--accent-cool)]",
  status_memory:
    "status_memory min-w-0",
  status_mental:
    "status_mental min-w-0",
  status_missing:
    "status_missing min-w-0",
  status_muted:
    "status_muted min-w-0 text-[var(--vui-font-xs)] leading-tight text-[var(--fg-tertiary)]",
  status_needs_evidence:
    "status_needs_evidence min-w-0",
  status_needs_input:
    "status_needs_input min-w-0 grid gap-1 text-[var(--vui-font-xs)] text-[var(--fg-secondary)] [&_input]:min-h-[var(--vui-control-height-sm)] [&_select]:min-h-[var(--vui-control-height-sm)] [&_textarea]:min-h-20 [&_input]:w-full [&_select]:w-full [&_textarea]:w-full",
  status_needs_review:
    "status_needs_review min-w-0",
  status_neutral:
    "status_neutral min-w-0",
  status_ok:
    "status_ok min-w-0 border-[color-mix(in_srgb,var(--state-success)_32%,transparent)] bg-[color-mix(in_srgb,var(--state-success)_9%,transparent)] text-[var(--state-success)]",
  status_pending:
    "status_pending min-w-0",
  status_ready:
    "status_ready min-w-0 border-[color-mix(in_srgb,var(--state-success)_32%,transparent)] bg-[color-mix(in_srgb,var(--state-success)_9%,transparent)] text-[var(--state-success)]",
  status_research:
    "status_research min-w-0",
  status_running:
    "status_running min-w-0 border-[color-mix(in_srgb,var(--state-success)_32%,transparent)] bg-[color-mix(in_srgb,var(--state-success)_9%,transparent)] text-[var(--state-success)]",
  status_selection:
    "status_selection min-w-0",
  status_self:
    "status_self min-w-0",
  status_skipped:
    "status_skipped min-w-0",
  status_stale:
    "status_stale min-w-0",
  status_status:
    "status_status min-w-0",
  status_success:
    "status_success min-w-0 border-[color-mix(in_srgb,var(--state-success)_32%,transparent)] bg-[color-mix(in_srgb,var(--state-success)_9%,transparent)] text-[var(--state-success)]",
  status_supervised:
    "status_supervised min-w-0",
  status_thought:
    "status_thought min-w-0",
  status_tool:
    "status_tool min-w-0 border-[color-mix(in_srgb,var(--accent-warm)_24%,transparent)] bg-[color-mix(in_srgb,var(--accent-warm)_8%,transparent)] text-[var(--accent-warm)]",
  status_warn:
    "status_warn min-w-0",
  status_warning:
    "status_warning min-w-0 border-[color-mix(in_srgb,var(--state-warning)_36%,transparent)] bg-[color-mix(in_srgb,var(--state-warning)_10%,transparent)] text-[var(--state-warning)]",
  twoColumns:
    "twoColumns min-w-0 grid gap-2 !grid grid-cols-[repeat(2,minmax(0,1fr))] gap-2.5",
  validationConnectionNotice:
    "validationConnectionNotice min-w-0 rounded-[var(--radius-panel)] border border-[var(--vui-border-subtle)] bg-[var(--vui-surface-glass)] shadow-[var(--vui-shadow-hairline)] p-2",
  validationIssue:
    "validationIssue min-w-0",
  validationIssueError:
    "validationIssueError min-w-0 border-[color-mix(in_srgb,var(--state-error)_36%,transparent)] bg-[color-mix(in_srgb,var(--state-error)_9%,transparent)] text-[var(--state-error)]",
  validationIssueWarning:
    "validationIssueWarning min-w-0 border-[color-mix(in_srgb,var(--state-warning)_36%,transparent)] bg-[color-mix(in_srgb,var(--state-warning)_10%,transparent)] text-[var(--state-warning)]",
  zoomControl:
    "zoomControl min-w-0 flex flex-wrap items-center gap-1.5",
};

export default styles;
