import { describe, expect, it } from "vitest";

import styles from "./ResearchRoute.module.css";
import routeSource from "./ResearchRoute.tsx?raw";

describe("ResearchRoute layout contract", () => {
  it("renders the API-backed theme discovery MVP", () => {
    expect(routeSource).toContain("ResearchRoute");
    expect(routeSource).toContain("/api/research/theme-discovery/sessions");
    expect(routeSource).toContain("/api/research/flow-canvas");
    expect(routeSource).toContain("/api/research/flow-canvas/execute");
    expect(routeSource).toContain("ResearchFlowCanvas");
    expect(routeSource).toContain("ResearchFlowExecutionResponse");
    expect(routeSource).toContain("AUTO_DRAFT_STEPS");
    expect(routeSource).toContain("runWorkflow");
    expect(routeSource).toContain("pauseAutoDraft");
    expect(routeSource).toContain("autoDraftPauseRequested");
    expect(routeSource).toContain("workflowMode");
    expect(routeSource).toContain("showFallbackWorkflowModeControl");
    expect(routeSource).toContain("workflowControlsDisabled");
    expect(routeSource).not.toContain("enabled: activeView === \"discovery\"");
    expect(routeSource).toContain("activeView === \"discovery\"");
    expect(routeSource).toContain("initialPayload");
    expect(routeSource).toContain("autoDraftStepIndex");
    expect(routeSource).toContain("PREVIOUS_DEFAULT_INPUT");
    expect(routeSource).toContain("Qwen/千问");
    expect(routeSource).toContain("阿里云百炼平台");
    expect(routeSource).toContain("Problem Statement");
    expect(routeSource).toContain("科学价值 40 分、技术深度 30 分、应用潜力 30 分");
    expect(routeSource).toContain("nextManualWorkflowStep");
    expect(routeSource).toContain("flowStageItems");
    expect(routeSource).toContain("flowNodeStage");
    expect(routeSource).toContain("nextRunnableFlowNode");
    expect(routeSource).toContain("flowNodeCanExecute");
    expect(routeSource).toContain("runFlowNode");
    expect(routeSource).toContain("missingEvidenceRequests");
    expect(routeSource).toContain("confirmEvidenceSearch");
    expect(routeSource).toContain("candidateCardPreview");
    expect(routeSource).toContain("defaultCollapsed");
    expect(routeSource).toContain("CodeMirror");
    expect(routeSource).toContain("promptWorkbench");
    expect(routeSource).toContain("/research/flow-canvas");
    expect(routeSource).toContain("promptAgentRail");
    expect(routeSource).toContain("promptEditorPanel");
    expect(routeSource).toContain("promptInspectorPanel");
    expect(routeSource).toContain("run-broad-search");
    expect(routeSource).toContain("run-deep-search");
    expect(routeSource).toContain("extract-evidence");
    expect(routeSource).toContain("generate-themes");
    expect(routeSource).toContain("theme-card");
    expect(routeSource).toContain("method: \"DELETE\"");
    expect(routeSource).toContain("deleteSession");
    expect(routeSource).toContain("Candidate themes");
    expect(routeSource).not.toContain("Frontend preview");
  });

  it("keeps the page in the existing dense workbench layout family", () => {
    expect(styles.route).toBeTypeOf("string");
    expect(styles.summaryGrid).toBeTypeOf("string");
    expect(styles.workspace).toBeTypeOf("string");
    expect(styles.sessionRail).toBeTypeOf("string");
    expect(styles.intakeFields).toBeTypeOf("string");
    expect(styles.intakeField).toBeTypeOf("string");
    expect(styles.intakeField_primary).toBeTypeOf("string");
    expect(styles.intakeField_tall).toBeTypeOf("string");
    expect(styles.intakeField_medium).toBeTypeOf("string");
    expect(styles.sessionDeleteButton).toBeTypeOf("string");
    expect(styles.pipelinePanel).toBeTypeOf("string");
    expect(styles.evidencePanel).toBeTypeOf("string");
    expect(styles.outputPanel).toBeTypeOf("string");
    expect(styles.themeGrid).toBeTypeOf("string");
    expect(styles.promptWorkbench).toBeTypeOf("string");
    expect(styles.promptAgentRail).toBeTypeOf("string");
    expect(styles.promptEditorPanel).toBeTypeOf("string");
    expect(styles.promptInspectorPanel).toBeTypeOf("string");
    expect(styles.promptCodeEditor).toBeTypeOf("string");
  });

  it("stacks workflow stages as full-width vertical rows", () => {
    expect(routeSource).toContain("styles.stageRail");
    expect(styles.stageRail).toBeTypeOf("string");
    expect(styles.stageCard).toBeTypeOf("string");
    expect(styles.stageCard_active).toBeTypeOf("string");
    expect(styles.stageCard_compact).toBeTypeOf("string");
    expect(styles.stageSelectButton).toBeTypeOf("string");
    expect(styles.stageBody).toBeTypeOf("string");
    expect(styles.workflowModeControl).toBeTypeOf("string");
    expect(styles.workflowModeButton_active).toBeTypeOf("string");
    expect(styles.evidenceRequestPanel).toBeTypeOf("string");
    expect(styles.agentTracePanel_collapsed).toBeTypeOf("string");
    expect(styles.cardPreviewIntro).toBeTypeOf("string");
    expect(styles.themeCard_selected).toBeTypeOf("string");
    expect(styles.themeCompareRow).toBeTypeOf("string");
    expect(styles.themeCompareMetrics).toBeTypeOf("string");
    expect(styles.themeCompareActions).toBeTypeOf("string");
    expect(routeSource).toContain("activeStage");
    expect(routeSource).toContain("ResearchStageOutput");
    expect(routeSource).toContain("AgentTracePanel");
    expect(routeSource).toContain("defaultCollapsed");
    expect(routeSource).toContain("stageDescription(stage, lang)");
    expect(routeSource).toContain("等待开始广撒网调研");
    expect(routeSource).toContain("等待抽取证据");
    expect(routeSource).toContain("等待生成候选主题");
    expect(routeSource).toContain("buildResearchTraceScrollSignal");
    expect(routeSource).toContain("ResearchTraceDetail");
    expect(routeSource).toContain("回到最新");
    expect(routeSource).toContain("工具调用与上下文过程");
    expect(routeSource).toContain("showAllSources");
    expect(routeSource).toContain("sourceToggleButton");
    expect(routeSource).toContain("formatTraceTimestamp");
    expect(routeSource).toContain("runFailure");
    expect(routeSource).toContain("failed");
    expect(styles.agentTracePanel).toBeTypeOf("string");
    expect(styles.agentTraceTimeline).toBeTypeOf("string");
    expect(styles.agentTraceTurn).toBeTypeOf("string");
    expect(styles.agentTraceDetailGroup).toBeTypeOf("string");
    expect(styles.traceBackToBottomButton).toBeTypeOf("string");
    expect(styles.agentTrace_error).toBeTypeOf("string");
  });

  it("lets users restore each research agent prompt from its default prompt", () => {
    expect(routeSource).toContain("defaultContent");
    expect(routeSource).toContain("恢复默认提示词");
    expect(routeSource).toContain("Restore default prompt");
    expect(routeSource).not.toContain("恢复当前内容");
    expect(routeSource).not.toContain("Reset current content");
  });
});
