import { describe, expect, it } from "vitest";

import styles from "./ResearchFlowCanvasRoute.module.css";
import routeSource from "./ResearchFlowCanvasRoute.tsx?raw";
import routerSource from "../app/router.tsx?raw";

describe("ResearchFlowCanvasRoute layout contract", () => {
  it("exposes a dedicated API-backed research flow canvas page with an organization side panel", () => {
    expect(routerSource).toContain("ResearchFlowCanvasRoute");
    expect(routerSource).toContain("research/flow-canvas");
    expect(routeSource).toContain("/api/research/flow-canvas");
    expect(routeSource).not.toContain("/api/research/flow-canvas/execute");
    expect(routeSource).toContain("/api/research/organization");
    expect(routeSource).toContain("/api/research/organization/messages");
    expect(routeSource).toContain("workspace/prompts/research/flow_canvas.json");
    expect(routeSource).toContain("workspace/research/organization_graph.json");
    expect(routeSource).toContain("Research Flow Canvas");
    expect(routeSource).toContain("科研流程画布");
    expect(routeSource).toContain("research_flow_canvas");
    expect(routeSource).not.toContain("research_agent_organization");
    expect(routeSource).toContain("模块模板库");
    expect(routeSource).toContain("添加模块");
    expect(routeSource).toContain("路由");
    expect(routeSource).toContain("结构校验");
    expect(routeSource).toContain("组织通信");
    expect(routeSource).toContain("科研组织通信");
    expect(routeSource).toContain("提案面板");
    expect(routeSource).toContain("审计流");
    expect(routeSource).toContain("human_override");
    expect(routeSource).toContain("inspectorView");
    expect(routeSource).toContain("错误警告");
    expect(routeSource).toContain("错误与警告");
    expect(routeSource).toContain("focusValidationIssue");
    expect(routeSource).toContain("先修复结构");
    expect(routeSource).toContain("无法连接");
    expect(routeSource).not.toContain("activeExecutionSessionId");
    expect(routeSource).toContain("researchFlowExecutionBlockReason");
    expect(routeSource).toContain("researchFlowLockBlockReason");
    expect(routeSource).toContain("锁定观察");
    expect(routeSource).toContain("取消锁定");
    expect(routeSource).toContain("useState(true)");
    expect(routeSource).toContain("实时观察");
    expect(routeSource).toContain("先锁定画布进入观察模式");
    expect(routeSource).not.toContain("执行下一节点");
    expect(routeSource).not.toContain("执行选中节点");
    expect(routeSource).not.toContain("执行前检查");
    expect(routeSource).toContain("readableResearchFlowIssueMessage");
    expect(routeSource).toContain("researchFlowIssueAdvice");
    expect(routeSource).toContain("refetchInterval: canvasLocked ? 2000 : false");
  });

  it("keeps the canvas editable as a flow contract board instead of an organization graph", () => {
    expect(routeSource).toContain("addNode");
    expect(routeSource).toContain("deleteSelected");
    expect(routeSource).toContain("handleNodePointerDown");
    expect(routeSource).toContain("connect.sourceId");
    expect(routeSource).toContain("nextEdgeId");
    expect(routeSource).toContain("RESEARCH_MODULE_TEMPLATES");
    expect(routeSource).toContain("createResearchNodeFromTemplate");
    expect(routeSource).toContain("nextTemplateNodeId");
    expect(routeSource).toContain("当前模块模板");
    expect(routeSource).toContain("线模板");
    expect(routeSource).toContain("保存为模块模板");
    expect(routeSource).toContain("保存为线模板");
    expect(routeSource).toContain("readCustomResearchTemplates");
    expect(routeSource).toContain("writeCustomResearchTemplates");
    expect(routeSource).toContain("createCustomResearchModuleTemplate");
    expect(routeSource).toContain("createCustomResearchEdgeTemplate");
    expect(routeSource).toContain("research_ceo_entry");
    expect(routeSource).toContain("organization_advisor_entry");
    expect(routeSource).toContain("broad_search");
    expect(routeSource).toContain("deep_search");
    expect(routeSource).toContain("evidence_review");
    expect(routeSource).toContain("theme_generation");
    expect(routeSource).toContain("theme_card");
    expect(routeSource).not.toContain("knowledge_lookup");
    expect(routeSource).not.toContain("literature_project_parse");
    expect(routeSource).not.toContain("semantic_cluster");
    expect(routeSource).not.toContain("novelty_reverse_check");
    expect(routeSource).not.toContain("human_choice");
    expect(routeSource).not.toContain("collaboration_chat");
    expect(routeSource).toContain("edgeGeometry");
    expect(routeSource).toContain("EDGE_TYPE_OPTIONS");
    expect(routeSource).toContain("EDGE_CONDITION_OPTIONS");
    expect(routeSource).toContain("normalizeEdgeCondition");
    expect(routeSource).toContain("edgeConditionLabel");
    expect(routeSource).toContain("edgeConditionDescription");
    expect(routeSource).toContain("resolveEdgeLanes");
    expect(routeSource).toContain("detectEdgeOverlap");
    expect(routeSource).toContain("arrowHeadPoints");
    expect(routeSource).toContain("edgeArrowHead");
    expect(routeSource).toContain("edgeTypeDescription");
    expect(routeSource).toContain("boundaryAnchor");
    expect(routeSource).toContain("EDGE_NODE_GAP");
    expect(routeSource).toContain("canvasZoom");
    expect(routeSource).toContain("PanState");
    expect(routeSource).toContain("canvasOffset");
    expect(routeSource).toContain("draftSignatureRef");
    expect(routeSource).toContain("远端画布已刷新");
    expect(routeSource).toContain("canvasViewportFromView");
    expect(routeSource).toContain("handleCanvasPointerDown");
    expect(routeSource).toContain("suppressCanvasClickRef");
    expect(routeSource).toContain("edgeVisualStyle");
    expect(routeSource).toContain("startEdgeReconnect");
    expect(routeSource).toContain("isValidEdgeReconnectTarget");
    expect(routeSource).toContain("正在重连");
    expect(routeSource).toContain("pushCanvasHistory");
    expect(routeSource).toContain("stepCanvasHistory");
    expect(routeSource).toContain("summarizeDeleteImpact");
    expect(routeSource).toContain("deleteCanvasSelection");
    expect(routeSource).toContain("已删除 ${removedSubject}");
    expect(routeSource).toContain("撤销编辑");
    expect(routeSource).toContain("重做编辑");
    expect(routeSource).toContain("保存失败:");
    expect(routeSource).toContain("useBlocker");
    expect(routeSource).toContain("shouldBlockCanvasLeave");
    expect(routeSource).toContain("beforeunload");
    expect(routeSource).toContain("保存后离开");
    expect(routeSource).toContain("不保存离开");
    expect(routeSource).toContain("离开前要保存科研流程画布吗");
    expect(routeSource).toContain("WORKBENCH_EXIT_GUARD_EVENT");
    expect(routeSource).toContain("关闭工作台");
    expect(routeSource).toContain("保存后${workbenchExitLabel}");
    expect(routeSource).toContain("起点模块");
    expect(routeSource).toContain("终点模块");
    expect(routeSource).toContain("模板说明");
    expect(routeSource).toContain("headers: { \"Content-Type\": \"application/json\" }");
    expect(routeSource).toContain("canvasKind: payload.canvasKind || FLOW_CANVAS_KIND");
    expect(routeSource).toContain("saveMessage");
    expect(routeSource).toContain("handleCanvasWheel");
    expect(routeSource).toContain("preventDefault");
    expect(routeSource).toContain("画布缩放区域，滚轮可缩放画布");
    expect(routeSource).not.toContain("!event.ctrlKey && !event.metaKey");
    expect(routeSource).toContain("translate(${canvasOffset.x}px, ${canvasOffset.y}px) scale(${canvasZoom})");
    expect(routeSource).toContain("STATUS_OPTIONS");
    expect(routeSource).toContain("blocked");
    expect(routeSource).toContain("agentId");
    expect(routeSource).toContain("agentKey");
    expect(routeSource).toContain("llmConfigId");
    expect(routeSource).toContain("绑定 Agent");
    expect(routeSource).toContain("模型配置来自 Agent");
    expect(routeSource).toContain("normalizeResearchFlowNodesForSave");
    expect(routeSource).toContain("styles.nodeTitleInput");
    expect(routeSource).toContain("模块模板");
    expect(routeSource).not.toContain("旧节点级 LLM");
    expect(routeSource).toContain("routeCondition");
    expect(routeSource).toContain("触发条件");
    expect(routeSource).toContain("condition: \"completed\"");
    expect(routeSource).not.toContain("executeMutation");
    expect(routeSource).not.toContain("researchThemeDiscoverySessions");
  });

  it("uses a full canvas plus inspector layout", () => {
    expect(styles.route).toBeTypeOf("string");
    expect(styles.canvasShell).toBeTypeOf("string");
    expect(styles.canvasScroller).toBeTypeOf("string");
    expect(styles.canvasViewport).toBeTypeOf("string");
    expect(styles.canvasPanning).toBeTypeOf("string");
    expect(styles.reconnectHint).toBeTypeOf("string");
    expect(styles.zoomControl).toBeTypeOf("string");
    expect(styles.iconButton).toBeTypeOf("string");
    expect(styles.node).toBeTypeOf("string");
    expect(styles.nodeTitleInput).toBeTypeOf("string");
    expect(styles.nodeStatusCluster).toBeTypeOf("string");
    expect(styles.nodeWithIssue).toBeTypeOf("string");
    expect(styles.nodeIssueBadgeWarning).toBeTypeOf("string");
    expect(styles.edgeHotspot).toBeTypeOf("string");
    expect(styles.edgeHotspotOffset).toBeTypeOf("string");
    expect(styles.edgeEndpointHandle).toBeTypeOf("string");
    expect(styles.edgeEndpointHandleActive).toBeTypeOf("string");
    expect(styles.edgeTrack).toBeTypeOf("string");
    expect(styles.edgePath).toBeTypeOf("string");
    expect(styles.edgeArrowHead).toBeTypeOf("string");
    expect(styles.edgeTypeHint).toBeTypeOf("string");
    expect(styles.saveStatusSuccess).toBeTypeOf("string");
    expect(styles.saveStatusWarning).toBeTypeOf("string");
    expect(styles.saveStatusError).toBeTypeOf("string");
    expect(styles.leaveGuardOverlay).toBeTypeOf("string");
    expect(styles.leaveGuardPanel).toBeTypeOf("string");
    expect(styles.leaveGuardActions).toBeTypeOf("string");
    expect(styles.inspector).toBeTypeOf("string");
    expect(styles.inspectorBody).toBeTypeOf("string");
    expect(styles.inspectorTabs).toBeTypeOf("string");
    expect(styles.inspectorTab).toBeTypeOf("string");
    expect(styles.inspectorTabActive).toBeTypeOf("string");
    expect(styles.inspectorTabBadge).toBeTypeOf("string");
    expect(styles.inspectorContent).toBeTypeOf("string");
    expect(styles.issuePanel).toBeTypeOf("string");
    expect(styles.issueSummary).toBeTypeOf("string");
    expect(styles.issueCard).toBeTypeOf("string");
    expect(styles.issueCardBody).toBeTypeOf("string");
    expect(styles.organizationPanel).toBeTypeOf("string");
    expect(styles.organizationSummaryGrid).toBeTypeOf("string");
    expect(styles.organizationAgentCard).toBeTypeOf("string");
    expect(styles.organizationForm).toBeTypeOf("string");
    expect(styles.organizationProposalCard).toBeTypeOf("string");
    expect(styles.organizationAuditCard).toBeTypeOf("string");
    expect(styles.selectionSummary).toBeTypeOf("string");
    expect(styles.issueFocusButton).toBeTypeOf("string");
    expect(styles.issueEmpty).toBeTypeOf("string");
    expect(styles.executionBar).toBeTypeOf("string");
    expect(styles.observerStatus).toBeTypeOf("string");
    expect(styles.observerStatusActive).toBeTypeOf("string");
    expect(styles.lockButtonActive).toBeTypeOf("string");
    expect(styles.canvasLocked).toBeTypeOf("string");
    expect(styles.moduleTemplateSelect).toBeTypeOf("string");
    expect(styles.templateActions).toBeTypeOf("string");
    expect(styles.executionHint).toBeTypeOf("string");
    expect(styles.editorStack).toBeTypeOf("string");
    expect(styles.status_blocked).toBeTypeOf("string");
  });
});
