import { describe, expect, it } from "vitest";

import styles from "./ResearchFlowCanvasRoute.module.css";
import routeSource from "./ResearchFlowCanvasRoute.tsx?raw";
import routerSource from "../app/router.tsx?raw";

describe("ResearchFlowCanvasRoute layout contract", () => {
  it("exposes a locked project organization canvas backed by the research organization graph", () => {
    expect(routerSource).toContain("ResearchFlowCanvasRoute");
    expect(routerSource).toContain("research/flow-canvas");
    expect(routeSource).toContain("/api/research/flow-canvas");
    expect(routeSource).not.toContain("/api/research/flow-canvas/execute");
    expect(routeSource).toContain("/api/research/organization");
    expect(routeSource).toContain("/api/research/organization/messages");
    expect(routeSource).toContain("workspace/research/organization_graph.json");
    expect(routeSource).toContain("Project Organization Canvas");
    expect(routeSource).toContain("科研组织画布");
    expect(routeSource).toContain("持续锁定到项目组织架构");
    expect(routeSource).toContain("画布持续只读同步");
    expect(routeSource).toContain("流程线与组织通信线使用同一份项目组织数据");
    expect(routeSource).toContain("canvasEditable = false");
    expect(routeSource).toContain("research_flow_canvas");
    expect(routeSource).not.toContain("research_agent_organization");
    expect(routeSource).toContain("组织通信");
    expect(routeSource).toContain("科研组织通信");
    expect(routeSource).toContain("提案面板");
    expect(routeSource).toContain("审计流");
    expect(routeSource).toContain("human_override");
    expect(routeSource).toContain("inspectorView");
    expect(routeSource).toContain("同步检查");
    expect(routeSource).toContain("错误与警告");
    expect(routeSource).toContain("focusValidationIssue");
    expect(routeSource).not.toContain("activeExecutionSessionId");
    expect(routeSource).toContain("持续锁定");
    expect(routeSource).toContain("useState(true)");
    expect(routeSource).toContain("绑定团队");
    expect(routeSource).toContain("科研团队");
    expect(routeSource).toContain("刷新组织图");
    expect(routeSource).not.toContain("执行下一节点");
    expect(routeSource).not.toContain("执行选中节点");
    expect(routeSource).not.toContain("执行前检查");
    expect(routeSource).not.toContain("添加模块");
    expect(routeSource).not.toContain("保存画布");
    expect(routeSource).toContain("readableResearchFlowIssueMessage");
    expect(routeSource).toContain("researchFlowIssueAdvice");
    expect(routeSource).toContain("refetchInterval: canvasLocked ? 2000 : false");
  });

  it("renders only organization Agent nodes and communication edges in the main canvas", () => {
    expect(routeSource).toContain("agentDisplayInfo");
    expect(routeSource).toContain("agentDisplayForFlowNode");
    expect(routeSource).toContain("styles[agentRoleClass(display.tone)]");
    expect(routeSource).toContain("Agent ID");
    expect(routeSource).toContain("组织角色");
    expect(routeSource).toContain("职级");
    expect(routeSource).toContain("通信线 / 流程线");
    expect(routeSource).toContain("流程线与通讯线相同");
    expect(routeSource).not.toContain("addNode");
    expect(routeSource).not.toContain("deleteSelected");
    expect(routeSource).not.toContain("保存为模块模板");
    expect(routeSource).not.toContain("保存为线模板");
    expect(routeSource).not.toContain("useBlocker");
    expect(routeSource).not.toContain("WORKBENCH_EXIT_GUARD_EVENT");
    expect(routeSource).not.toContain("beforeunload");
    expect(routeSource).not.toContain("离开前要保存科研流程画布吗");
    expect(routeSource).toContain("handleNodePointerDown");
    expect(routeSource).toContain("connect.sourceId");
    expect(routeSource).toContain("nextEdgeId");
    expect(routeSource).toContain("RESEARCH_MODULE_TEMPLATES");
    expect(routeSource).toContain("createResearchNodeFromTemplate");
    expect(routeSource).toContain("nextTemplateNodeId");
    expect(routeSource).toContain("readCustomResearchTemplates");
    expect(routeSource).toContain("writeCustomResearchTemplates");
    expect(routeSource).toContain("createCustomResearchModuleTemplate");
    expect(routeSource).toContain("createCustomResearchEdgeTemplate");
    expect(routeSource).toContain("research_ceo_entry");
    expect(routeSource).toContain("organization_advisor_entry");
    expect(routeSource).toContain("broad_search");
    expect(routeSource).toContain("deep_search");
    expect(routeSource).toContain("evidence_review");
    expect(routeSource).toContain("theme_generation");
    expect(routeSource).toContain("theme_card");
    expect(routeSource).not.toContain("knowledge_lookup");
    expect(routeSource).not.toContain("literature_project_parse");
    expect(routeSource).not.toContain("semantic_cluster");
    expect(routeSource).not.toContain("novelty_reverse_check");
    expect(routeSource).not.toContain("human_choice");
    expect(routeSource).not.toContain("collaboration_chat");
    expect(routeSource).toContain("edgeGeometry");
    expect(routeSource).toContain("EDGE_TYPE_OPTIONS");
    expect(routeSource).toContain("EDGE_CONDITION_OPTIONS");
    expect(routeSource).toContain("normalizeEdgeCondition");
    expect(routeSource).toContain("edgeConditionLabel");
    expect(routeSource).toContain("edgeConditionDescription");
    expect(routeSource).toContain("resolveEdgeLanes");
    expect(routeSource).toContain("detectEdgeOverlap");
    expect(routeSource).toContain("arrowHeadPoints");
    expect(routeSource).toContain("edgeArrowHead");
    expect(routeSource).toContain("edgeTypeDescription");
    expect(routeSource).toContain("boundaryAnchor");
    expect(routeSource).toContain("EDGE_NODE_GAP");
    expect(routeSource).toContain("canvasZoom");
    expect(routeSource).toContain("PanState");
    expect(routeSource).toContain("canvasOffset");
    expect(routeSource).toContain("draftSignatureRef");
    expect(routeSource).toContain("远端画布已刷新");
    expect(routeSource).toContain("canvasViewportFromView");
    expect(routeSource).toContain("handleCanvasPointerDown");
    expect(routeSource).toContain("suppressCanvasClickRef");
    expect(routeSource).toContain("edgeVisualStyle");
    expect(routeSource).toContain("startEdgeReconnect");
    expect(routeSource).toContain("isValidEdgeReconnectTarget");
    expect(routeSource).toContain("正在重连");
    expect(routeSource).toContain("pushCanvasHistory");
    expect(routeSource).toContain("stepCanvasHistory");
    expect(routeSource).toContain("summarizeDeleteImpact");
    expect(routeSource).toContain("deleteCanvasSelection");
    expect(routeSource).toContain("shouldBlockCanvasLeave");
    expect(routeSource).toContain("saveMessage");
    expect(routeSource).toContain("handleCanvasWheel");
    expect(routeSource).toContain("preventDefault");
    expect(routeSource).toContain("画布缩放区域，滚轮可缩放画布");
    expect(routeSource).not.toContain("!event.ctrlKey && !event.metaKey");
    expect(routeSource).toContain("translate(${canvasOffset.x}px, ${canvasOffset.y}px) scale(${canvasZoom})");
    expect(routeSource).toContain("STATUS_OPTIONS");
    expect(routeSource).toContain("blocked");
    expect(routeSource).toContain("agentId");
    expect(routeSource).toContain("agentKey");
    expect(routeSource).toContain("llmConfigId");
    expect(routeSource).toContain("normalizeResearchFlowNodesForSave");
    expect(routeSource).toContain("styles.nodeTitleInput");
    expect(routeSource).not.toContain("旧节点级 LLM");
    expect(routeSource).toContain("routeCondition");
    expect(routeSource).toContain("condition: \"completed\"");
    expect(routeSource).not.toContain("executeMutation");
    expect(routeSource).not.toContain("researchThemeDiscoverySessions");
  });

  it("uses a full canvas plus inspector layout", () => {
    expect(styles.route).toBeTypeOf("string");
    expect(styles.canvasShell).toBeTypeOf("string");
    expect(styles.canvasScroller).toBeTypeOf("string");
    expect(styles.canvasViewport).toBeTypeOf("string");
    expect(styles.canvasPanning).toBeTypeOf("string");
    expect(styles.reconnectHint).toBeTypeOf("string");
    expect(styles.zoomControl).toBeTypeOf("string");
    expect(styles.iconButton).toBeTypeOf("string");
    expect(styles.node).toBeTypeOf("string");
    expect(styles.nodeTitleInput).toBeTypeOf("string");
    expect(styles.nodeStatusCluster).toBeTypeOf("string");
    expect(styles.nodeWithIssue).toBeTypeOf("string");
    expect(styles.nodeIssueBadgeWarning).toBeTypeOf("string");
    expect(styles.edgeHotspot).toBeTypeOf("string");
    expect(styles.edgeHotspotOffset).toBeTypeOf("string");
    expect(styles.edgeEndpointHandle).toBeTypeOf("string");
    expect(styles.edgeEndpointHandleActive).toBeTypeOf("string");
    expect(styles.edgeTrack).toBeTypeOf("string");
    expect(styles.edgePath).toBeTypeOf("string");
    expect(styles.edgeArrowHead).toBeTypeOf("string");
    expect(styles.edgeTypeHint).toBeTypeOf("string");
    expect(styles.saveStatusSuccess).toBeTypeOf("string");
    expect(styles.saveStatusWarning).toBeTypeOf("string");
    expect(styles.saveStatusError).toBeTypeOf("string");
    expect(styles.inspector).toBeTypeOf("string");
    expect(styles.inspectorBody).toBeTypeOf("string");
    expect(styles.inspectorTabs).toBeTypeOf("string");
    expect(styles.inspectorTab).toBeTypeOf("string");
    expect(styles.inspectorTabActive).toBeTypeOf("string");
    expect(styles.inspectorTabBadge).toBeTypeOf("string");
    expect(styles.inspectorContent).toBeTypeOf("string");
    expect(styles.issuePanel).toBeTypeOf("string");
    expect(styles.issueSummary).toBeTypeOf("string");
    expect(styles.issueCard).toBeTypeOf("string");
    expect(styles.issueCardBody).toBeTypeOf("string");
    expect(styles.organizationPanel).toBeTypeOf("string");
    expect(styles.organizationSummaryGrid).toBeTypeOf("string");
    expect(styles.organizationAgentCard).toBeTypeOf("string");
    expect(styles.organizationForm).toBeTypeOf("string");
    expect(styles.organizationProposalCard).toBeTypeOf("string");
    expect(styles.organizationAuditCard).toBeTypeOf("string");
    expect(styles.selectionSummary).toBeTypeOf("string");
    expect(styles.issueFocusButton).toBeTypeOf("string");
    expect(styles.issueEmpty).toBeTypeOf("string");
    expect(styles.executionBar).toBeTypeOf("string");
    expect(styles.observerStatus).toBeTypeOf("string");
    expect(styles.observerStatusActive).toBeTypeOf("string");
    expect(styles.lockButtonActive).toBeTypeOf("string");
    expect(styles.canvasLocked).toBeTypeOf("string");
    expect(styles.agentRoleTag).toBeTypeOf("string");
    expect(styles.agentRoleTag_research).toBeTypeOf("string");
    expect(styles.readonlyDetailHeader).toBeTypeOf("string");
    expect(styles.readonlySpecGrid).toBeTypeOf("string");
    expect(styles.readonlyDescription).toBeTypeOf("string");
    expect(styles.executionHint).toBeTypeOf("string");
    expect(styles.editorStack).toBeTypeOf("string");
    expect(styles.status_blocked).toBeTypeOf("string");
  });
});
