const styles = {
  sourceSummary: "grid min-w-0 gap-1 rounded-[var(--vui-radius-soft)] bg-vui-surface-row px-2.5 py-2 text-vui-xs [&_span]:text-vui-fg-tertiary [&_strong]:break-words [&_strong]:font-medium [&_strong]:text-vui-fg-primary",
  conversationArea: "grid h-full min-h-0 min-w-0 grid-rows-[minmax(0,1fr)] overflow-hidden",
  conversationAreaWithNotice: "grid h-full min-h-0 min-w-0 grid-rows-[auto_minmax(0,1fr)] overflow-hidden",
  conversationBody: "grid h-full min-h-0 min-w-0 grid-rows-[minmax(0,1fr)_auto] overflow-hidden",
  conversationWithNotice: "grid h-full min-h-0 min-w-0 grid-rows-[auto_minmax(0,1fr)] overflow-hidden",
  retryRow: "flex min-w-0 flex-wrap items-center justify-between gap-2 border-t border-vui-border-subtle px-3 py-2 text-vui-xs text-[var(--state-error)]",
  setupPane: "mx-auto grid h-full min-h-0 w-full max-w-3xl content-start gap-5 overflow-auto p-5 max-[720px]:p-3",
  setupIntro: "flex min-w-0 flex-wrap items-start justify-between gap-4 border-b border-vui-border-subtle pb-4",
  eyebrow: "m-0 text-vui-xs font-semibold uppercase tracking-[0.08em] text-vui-fg-tertiary",
  setupHeading: "mb-1 mt-1 text-vui-lg font-semibold text-vui-fg-primary",
  subtleText: "m-0 text-vui-sm leading-relaxed text-vui-fg-secondary",
  modePicker: "flex flex-wrap gap-2",
  formStack: "grid max-w-2xl gap-4",
  formField: "grid min-w-0 gap-1.5 text-vui-sm font-medium text-vui-fg-secondary [&_textarea]:min-h-28 [&_textarea]:resize-y",
  budgetRow: "grid grid-cols-[auto_auto_1fr] items-center gap-3 rounded-[var(--vui-radius-soft)] bg-vui-surface-row px-3 py-2 text-vui-sm [&>span:first-child]:text-vui-fg-secondary [&>strong]:font-semibold [&>strong]:text-vui-fg-primary [&>span:last-child]:text-vui-xs [&>span:last-child]:text-vui-fg-tertiary",
  evidenceList: "grid gap-2",
  evidenceRow: "grid min-w-0 gap-1 rounded-[var(--vui-radius-soft)] bg-vui-surface-row px-3 py-2",
  evidenceLabel: "text-vui-xs font-semibold text-vui-fg-tertiary",
  evidenceValue: "m-0 whitespace-pre-wrap break-words font-mono text-vui-xs leading-relaxed text-vui-fg-primary",
  emptyEvidence: "m-0 rounded-[var(--vui-radius-soft)] border border-dashed border-vui-border-subtle p-3 text-vui-sm text-vui-fg-tertiary",
  footerContent: "grid min-w-0 gap-2 border-t border-vui-border-subtle bg-vui-surface-panel px-3 py-2",
  footerStatus: "flex min-w-0 items-center gap-2",
  footerGoal: "min-w-0 truncate text-vui-xs text-vui-fg-secondary",
  footerActions: "flex min-w-0 flex-wrap items-center gap-2",
  footerHint: "text-vui-xs text-vui-fg-tertiary",
  feedbackText: "m-0 text-vui-xs text-vui-fg-secondary",
  errorText: "m-0 whitespace-pre-wrap text-vui-xs text-[var(--state-error)]",
  dialogBody: "grid gap-4 p-1 text-vui-sm text-vui-fg-secondary",
  dialogFact: "m-0 break-words rounded-[var(--vui-radius-soft)] bg-vui-surface-row p-3 font-medium text-vui-fg-primary",
  dialogActions: "flex flex-wrap justify-end gap-2",
  contextFacts: "m-0 grid gap-2 [&>div]:grid [&>div]:grid-cols-[minmax(7rem,auto)_minmax(0,1fr)] [&>div]:gap-3 [&_dt]:text-vui-xs [&_dt]:text-vui-fg-tertiary [&_dd]:m-0 [&_dd]:break-words [&_dd]:text-vui-xs [&_dd]:text-vui-fg-primary",
};

export default styles;
