import { createVuiStyleMap } from "../components/vui/styles/createVuiStyleMap";

const canvasMeshBackgroundClass =
  "bg-[color-mix(in_srgb,var(--vui-surface-glass)_94%,white_6%)] [background-image:linear-gradient(to_right,color-mix(in_srgb,var(--vui-border-subtle)_45%,transparent)_1px,transparent_1px),linear-gradient(to_bottom,color-mix(in_srgb,var(--vui-border-subtle)_32%,transparent)_1px,transparent_1px)] [background-size:32px_32px]";

const styleKeys = [
  "actionRow",
  "aiSearchRunCard",
  "aiSearchRunCardDegraded",
  "aiSearchRunCardDetails",
  "aiSearchRunCardFailed",
  "aiSearchRunCardHeader",
  "aiSearchRunCardReview",
  "aiSearchRunCards",
  "aiSearchRunFallbackReason",
  "aiSearchRunHeader",
  "aiSearchRunInsight",
  "aiSearchRunLatest",
  "aiSearchRunPanel",
  "aiSearchRunQuery",
  "aiSearchRunRefs",
  "aiSearchRunResultHeader",
  "aiSearchRunStats",
  "aiSearchRunStatus",
  "aiSearchRunStatusCompleted",
  "aiSearchRunStatusFailed",
  "aiSearchRunStatusPartial",
  "aiSearchRunStatusRunning",
  "aiSearchRunStorage",
  "aiSearchRunSummary",
  "aiSearchRunTopic",
  "aiSearchScopeBadge",
  "aiSearchScopeDescription",
  "aiSearchScopeDetails",
  "aiSearchScopeEnabled",
  "aiSearchScopeHeader",
  "aiSearchScopePanel",
  "aiSearchScopePolicy",
  "aiSearchScopeSignal",
  "aiSearchScopeStats",
  "aiSearchSourceGroup",
  "aiSearchSourceGroupHeader",
  "aiSearchSourceGroups",
  "aiSearchSourceItem",
  "aiSearchSourceList",
  "aiSearchWorkflowSummary",
  "canvas",
  "canvasLayoutModeSwitch",
  "canvasPanel",
  "canvasReadOnlyBadge",
  "canvasReadOnlyNode",
  "canvasReadOnlyNodeWide",
  "canvasReadOnlyNotice",
  "canvasReadOnlyPanel",
  "canvasToolbar",
  "canvasViewport",
  "dangerButton",
  "deliveryList",
  "edgeCommunication",
  "edgeLayerLine",
  "edgeOrganization",
  "edges",
  "empty",
  "emptyCanvasContent",
  "emptyCanvasKicker",
  "emptyCanvasPanel",
  "emptyCanvasSteps",
  "experimentBaselineArtifact",
  "experimentBaselineForm",
  "experimentChecklist",
  "experimentChecklistPass",
  "experimentChecklistWarn",
  "experimentEvidenceGrid",
  "experimentGapList",
  "experimentHypothesisList",
  "experimentKnowledgeForm",
  "experimentKnowledgePanel",
  "experimentKnowledgeToggle",
  "experimentKnowledgeWide",
  "experimentLedgerEmpty",
  "experimentLedgerHeader",
  "experimentLedgerPanel",
  "experimentLedgerStats",
  "experimentPlanFields",
  "experimentPlanGrid",
  "experimentPlanSummary",
  "experimentSmokeForm",
  "experimentSmokeMeta",
  "experimentSmokeResult",
  "experimentSmokeResultPass",
  "experimentSmokeResultWarn",
  "experimentSmokeWide",
  "header",
  "iconButton",
  "inlineToggle",
  "inspector",
  "inspectorBody",
  "inspectorHeader",
  "issue",
  "issueList",
  "kernelTraceLink",
  "knowledgeCompletionFlowActions",
  "knowledgeCompletionFlowError",
  "knowledgeCompletionFlowHeader",
  "knowledgeCompletionFlowNode",
  "knowledgeCompletionFlowNodeBody",
  "knowledgeCompletionFlowNodeCurrent",
  "knowledgeCompletionFlowNodeHeader",
  "knowledgeCompletionFlowNodes",
  "knowledgeCompletionFlowPanel",
  "layerButtonActive",
  "linkedRoomLine",
  "managementNav",
  "messageError",
  "messageResult",
  "node",
  "nodeActive",
  "nodeBindingPlaceholder",
  "nodeBindingSection",
  "nodeBound",
  "nodeIcon",
  "nodeOpen",
  "nodeReadOnly",
  "nodeRoleBadge",
  "nodeRoleBadgeAdvisor",
  "nodeRoleBadgeGeneral",
  "nodeRoleBadgeLead",
  "nodeRoleBadgeOpen",
  "nodeRoleBadgeResearch",
  "nodeRoleBadgeSelf",
  "nodeRoleBadgeStale",
  "nodeRoleBadgeSteward",
  "nodeSourceAuthority",
  "nodeStale",
  "researchCanvasIndex",
  "researchCanvasPanelHidden",
  "researchDiscussionPanel",
  "researchInspector",
  "researchLoopActive",
  "researchLoopDecisionForm",
  "researchLoopEvidenceForm",
  "researchLoopHeader",
  "researchLoopOutcomeGrid",
  "researchLoopPanel",
  "researchLoopStats",
  "researchLoopStatusPills",
  "researchLoopTemplateBar",
  "researchLoopTemplateSummary",
  "researchLoopWide",
  "researchStageActionPanel",
  "researchStageActions",
  "researchStageAgentActions",
  "researchStageAgentCard",
  "researchStageAgentCard_blocked",
  "researchStageAgentCard_missing",
  "researchStageAgentCard_ready",
  "researchStageAgentCard_warning",
  "researchStageAgentGrid",
  "researchStageAgentMeta",
  "researchStageAgentPanel",
  "researchStageAgentPanelCompact",
  "researchStageAgentPanelHeader",
  "researchStageAgentRole",
  "researchStageAgentSummary",
  "researchStageAgentSummaryBlocked",
  "researchStageAgentSummaryMissing",
  "researchStageAgentSummaryReady",
  "researchStageBoundaryPanel",
  "researchStageCard",
  "researchStageCardActive",
  "researchStageCardHead",
  "researchStageCardMetrics",
  "researchStageGrid",
  "researchStageHeroPanel",
  "researchStageHeroStats",
  "researchStageLauncher",
  "researchStageLauncherHeader",
  "researchStageModuleCard",
  "researchStageModuleGrid",
  "researchStagePage",
  "researchStagePageActions",
  "researchStagePageBody",
  "researchStagePageHeader",
  "researchStageTopicInput",
  "revokeButton",
  "route",
  "saveState",
  "sectionTitle",
  "sourceCollectionCandidateListShell",
  "sourceCollectionCommandBar",
  "sourceCollectionCommandStats",
  "sourceCollectionCommandTitle",
  "sourceCollectionControlPanel",
  "sourceCollectionConversationHeader",
  "sourceCollectionConversationPanel",
  "sourceCollectionFilterActive",
  "sourceCollectionFilterBar",
  "sourceCollectionFocusedPanel",
  "sourceCollectionPage",
  "sourceCollectionPageActions",
  "sourceCollectionPageBody",
  "sourceCollectionPageGrid",
  "sourceCollectionPageHeader",
  "sourceCollectionPageTitleBlock",
  "sourceCollectionPageTitleLine",
  "sourceCollectionPagination",
  "sourceCollectionPanelActions",
  "sourceCollectionResultContent",
  "sourceCollectionResultItem",
  "sourceCollectionResultItemSelected",
  "sourceCollectionResultList",
  "sourceCollectionResultMeta",
  "sourceCollectionResultsHeader",
  "sourceCollectionResultSource",
  "sourceCollectionResultSourceMissing",
  "sourceCollectionResultsPanel",
  "sourceCollectionResultStats",
  "sourceCollectionResultStatus",
  "sourceCollectionResultWarning",
  "sourceCollectionRunBadge",
  "sourceCollectionScreeningList",
  "sourceCollectionScreeningListShell",
  "sourceCollectionScreeningScrollHint",
  "sourceCollectionSearchEvidence",
  "sourceCollectionSearchEvidenceBody",
  "sourceCollectionSourceDetailActions",
  "sourceCollectionSourceDetailFacts",
  "sourceCollectionSourceDetailHeader",
  "sourceCollectionSourceDetailNotice",
  "sourceCollectionSourceDetailPanel",
  "sourceCollectionStageAgentCard",
  "sourceCollectionStageAgentCardActions",
  "sourceCollectionStageAgentCardBody",
  "sourceCollectionStageAgentHeader",
  "sourceCollectionStageAgentList",
  "sourceCollectionStageAgentPanel",
  "sourceCollectionStageBlockers",
  "sourceCollectionStageCard",
  "sourceCollectionStageCardHead",
  "sourceCollectionStageCardSelected",
  "sourceCollectionStageChatActions",
  "sourceCollectionStageHandoff",
  "sourceCollectionStageHandoffNext",
  "sourceCollectionStageMiniFlow",
  "sourceCollectionStageModules",
  "sourceCollectionStageModuleText",
  "sourceCollectionStagePrimaryAction",
  "sourceCollectionStageProjection",
  "sourceCollectionStageSecondaryAction",
  "sourceCollectionStageTaskSummary",
  "sourceCollectionStageTechnicalDetails",
  "sourceCollectionStageWorkspace",
  "sourceCollectionStageWorkspaceHeader",
  "sourceCollectionStepActive",
  "sourceCollectionStepDone",
  "sourceCollectionStepFailed",
  "sourceCollectionStepIdle",
  "sourceCollectionStepPending",
  "sourceCollectionTrace_acquire",
  "sourceCollectionTrace_blocked",
  "sourceCollectionTrace_cache",
  "sourceCollectionTrace_extract",
  "sourceCollectionTrace_plan",
  "sourceCollectionTrace_quality",
  "sourceCollectionTrace_search",
  "sourceCollectionTrace_storage",
  "sourceCollectionTraceAvatar",
  "sourceCollectionTraceBody",
  "sourceCollectionTraceDetails",
  "sourceCollectionTraceHandoff",
  "sourceCollectionTraceList",
  "sourceCollectionTraceMessage",
  "sourceCollectionTraceMeta",
  "sourceCollectionTraceOwner",
  "sourceCollectionTraceRefs",
  "sourceCollectionTraceStorage",
  "sourceCollectionUnavailable",
  "teamContextActions",
  "teamContextBar",
  "teamContextChips",
  "teamHistoryHeader",
  "teamHistoryItem",
  "teamHistoryItemRevoked",
  "teamHistoryList",
  "teamHistoryMeta",
  "teamHistoryPanel",
  "teamMemoryActionRail",
  "teamMemoryIndex",
  "teamMemoryIndexHeader",
  "teamMemoryMemberActions",
  "teamMemoryMemberCard",
  "teamMemoryMemberHeading",
  "teamMemoryMemberIdentity",
  "teamMemoryMemberTable",
  "teamMemoryRole",
  "teamMemoryStatusBadge",
  "teamMessageForm",
  "teamRoundCard",
  "teamRoundHeader",
  "teamRoundMeta",
  "teamRoundPanel",
  "teamSelectField",
  "teamTaskForm",
  "teamTitleBlock",
  "toolbarActions",
  "toolbarLink",
  "workflowCandidateActions",
  "workflowCandidateHeader",
  "workflowCandidateItem",
  "workflowCandidateItemSelected",
  "workflowCandidateList",
  "workflowCandidateListHeader",
  "workflowCandidateListPanel",
  "workflowCandidateListScroll",
  "workflowCandidateListScrollHint",
  "workflowCandidateMeta",
  "workflowCoordinationBriefSummary",
  "workflowCoordinationPanel",
  "workflowCoordinationQueue",
  "workflowCoordinationQueues",
  "workflowCoordinationStats",
  "workflowError",
  "workflowGraphBoundary",
  "workflowGraphCanvas",
  "workflowGraphEdge",
  "workflowGraphFrame",
  "workflowGraphHeader",
  "workflowGraphIssues",
  "workflowGraphNode",
  "workflowGraphNodeDanger",
  "workflowGraphNodeNeutral",
  "workflowGraphNodeReady",
  "workflowGraphNodeWarning",
  "workflowGraphPanel",
  "workflowGraphStats",
  "workflowGraphSvg",
  "workflowIngestionActions",
  "workflowIngestionBoundary",
  "workflowIngestionHeader",
  "workflowIngestionPanel",
  "workflowIngestionStage",
  "workflowIngestionStages",
  "workflowIngestionStats",
  "workflowMeta",
  "workflowModelEvidenceCoverage",
  "workflowModelEvidencePanel",
  "workflowModelEvidenceStats",
  "workflowPanel",
  "workflowPaperNoteChunkPanel",
  "workflowPaperNoteChunkPlans",
  "workflowPaperNoteChunkStats",
  "workflowSourceCollectionAssignmentActive",
  "workflowSourceCollectionAssignments",
  "workflowSourceCollectionDetails",
  "workflowSourceCollectionForm",
  "workflowSourceCollectionOutputForm",
  "workflowSourceCollectionOutputHeader",
  "workflowSourceCollectionPanel",
  "workflowSourceCollectionPlan",
  "workflowSourceCollectionQueries",
  "workflowSourceCollectionRuns",
  "workflowSourceCollectionSearchAction",
  "workflowSourceCollectionStats",
  "workflowSourceCollectionStorageActions",
  "workflowSourceCollectionStorageButtons",
  "workflowSourceCollectionStorageDetails",
  "workflowSourceCollectionStorageError",
  "workflowSourceCollectionWide",
  "workflowSourceQualityPanel",
  "workflowSourceQualityQueue",
  "workflowSourceQualityStats",
  "workflowStageActive",
  "workflowStageList",
  "workflowStats",
  "workflowSuccess",
  "workflowTag",
  "workflowTagDanger",
  "workflowTagNeutral",
  "workflowTagReady",
  "workflowTagWarning",
  "workflowValidation",
  "workspace",
  "workspaceEmpty",
  "workspaceResearch",
  "workspaceResearchCanvas",
] as const;

const styles = createVuiStyleMap(styleKeys, {
  extensions: {
    canvas:
      `relative flex-1 overflow-auto ${canvasMeshBackgroundClass}`,
    canvasLayoutModeSwitch: "grid-cols-[repeat(auto-fit,minmax(86px,max-content))]",
    canvasPanel: "!flex min-h-0 flex-col overflow-hidden p-0",
    canvasReadOnlyBadge:
      "min-h-[26px] border-[color-mix(in_srgb,var(--accent-cool)_36%,var(--vui-border-subtle))] bg-[color-mix(in_srgb,var(--accent-cool)_10%,var(--vui-surface-row))] px-2 text-[var(--accent-cool)]",
    canvasReadOnlyNode: "grid-cols-[repeat(2,minmax(0,1fr))]",
    canvasReadOnlyNodeWide: "col-span-full",
    canvasReadOnlyNotice: "grid-cols-[auto_minmax(0,1fr)] items-start",
    canvasReadOnlyPanel: "content-start",
    canvasToolbar:
      "!flex min-h-[38px] flex-wrap items-start justify-between gap-2 border-b border-[var(--vui-border-subtle)] px-2 py-1 [&>div:first-child]:grid [&>div:first-child]:min-w-[220px] [&>div:first-child]:flex-1 [&_small]:truncate [&_strong]:text-[var(--vui-font-xs)] [&_span]:truncate [&_span]:text-[var(--vui-font-xs)]",
    canvasViewport:
      "relative box-content h-[760px] w-[1180px] origin-top-left pl-[var(--canvas-offset-x,0px)] pt-[var(--canvas-offset-y,0px)] [transform:scale(var(--canvas-scale,1))]",
    edgeCommunication: "text-[var(--fg-tertiary)] [stroke-dasharray:4_8] [stroke-width:1px] opacity-60",
    edgeLayerLine: "block truncate text-[var(--vui-font-xs)] font-semibold text-[var(--fg-tertiary)]",
    edgeOrganization: "text-[var(--accent-cool)] [stroke-width:1.75px] opacity-90",
    edges:
      "absolute inset-0 z-0 h-[760px] w-[1180px] overflow-visible text-[var(--accent-cool)] pointer-events-none [transform:translate(var(--canvas-offset-x,0px),var(--canvas-offset-y,0px))] [&>path]:fill-none [&>path]:stroke-current [&>path]:[stroke-linecap:butt] [&>path]:[stroke-linejoin:round] [&>path]:[stroke-width:1.5px] [&>path]:opacity-80",
    emptyCanvasContent: "max-w-[520px] content-start gap-1.5 p-2 text-left",
    emptyCanvasPanel: `flex-1 content-start overflow-auto p-2 ${canvasMeshBackgroundClass}`,
    emptyCanvasSteps: "!flex flex-wrap gap-1.5",
    inspector: "!flex min-h-0 flex-col overflow-hidden p-0",
    inspectorBody: "grid min-h-0 content-start gap-2 overflow-auto p-2",
    inspectorHeader:
      "!flex min-h-[36px] items-center justify-between border-b border-[var(--vui-border-subtle)] px-2 py-1",
    linkedRoomLine: "block truncate text-[var(--vui-font-xs)] font-semibold text-[var(--accent-cool)]",
    node:
      "!absolute left-[calc(var(--canvas-offset-x,0px)+var(--node-x,0px))] top-[calc(var(--canvas-offset-y,0px)+var(--node-y,0px))] z-[1] !grid h-[92px] w-[172px] cursor-grab select-none grid-cols-[20px_1fr] grid-rows-[auto_auto_auto] items-center gap-x-1.5 gap-y-0.5 rounded-[var(--radius-control)] border border-[var(--vui-border-subtle)] bg-[var(--vui-surface-row)] p-2 text-left text-[var(--fg-primary)] shadow-[var(--vui-shadow-hairline)] touch-none [&_small]:truncate [&_span]:truncate [&_strong]:truncate",
    nodeActive: "shadow-[var(--vui-shadow-inset-accent)]",
    nodeBindingSection: "content-start gap-2",
    nodeBound: "border-[color-mix(in_srgb,var(--state-success)_42%,var(--vui-border-subtle))]",
    nodeIcon:
      "row-span-3 inline-flex h-5 w-5 items-center justify-center text-[var(--fg-tertiary)]",
    nodeOpen: "border-dashed",
    nodeReadOnly: "cursor-pointer touch-manipulation",
    nodeRoleBadge:
      "min-h-[18px] justify-self-start rounded-full border border-[var(--node-role-border,var(--vui-border-subtle))] bg-[var(--node-role-bg,var(--vui-control-muted))] px-1.5 py-0 text-[var(--node-role-fg,var(--fg-secondary))] text-[var(--vui-font-xs)] font-semibold leading-none",
    nodeRoleBadgeAdvisor:
      "[--node-role-bg:color-mix(in_srgb,var(--accent-cool)_12%,var(--vui-surface-row))] [--node-role-border:color-mix(in_srgb,var(--accent-cool)_42%,var(--vui-border-subtle))] [--node-role-fg:var(--accent-cool)]",
    nodeRoleBadgeGeneral:
      "[--node-role-bg:var(--vui-control-muted)] [--node-role-border:var(--vui-border-subtle)] [--node-role-fg:var(--fg-secondary)]",
    nodeRoleBadgeLead:
      "[--node-role-bg:color-mix(in_srgb,var(--state-success)_11%,var(--vui-surface-row))] [--node-role-border:color-mix(in_srgb,var(--state-success)_38%,var(--vui-border-subtle))] [--node-role-fg:var(--state-success)]",
    nodeRoleBadgeOpen:
      "[--node-role-bg:var(--vui-control-muted)] [--node-role-border:var(--vui-border-subtle)] [--node-role-fg:var(--fg-tertiary)]",
    nodeRoleBadgeResearch:
      "[--node-role-bg:color-mix(in_srgb,var(--accent-warm)_10%,var(--vui-surface-row))] [--node-role-border:color-mix(in_srgb,var(--accent-warm)_34%,var(--vui-border-subtle))] [--node-role-fg:var(--fg-secondary)]",
    nodeRoleBadgeSelf:
      "[--node-role-bg:color-mix(in_srgb,var(--state-error)_9%,var(--vui-surface-row))] [--node-role-border:color-mix(in_srgb,var(--state-error)_34%,var(--vui-border-subtle))] [--node-role-fg:var(--state-error)]",
    nodeRoleBadgeStale:
      "[--node-role-bg:color-mix(in_srgb,var(--state-error)_9%,var(--vui-surface-row))] [--node-role-border:color-mix(in_srgb,var(--state-error)_40%,var(--vui-border-subtle))] [--node-role-fg:var(--state-error)]",
    nodeRoleBadgeSteward:
      "[--node-role-bg:color-mix(in_srgb,var(--state-warning)_11%,var(--vui-surface-row))] [--node-role-border:color-mix(in_srgb,var(--state-warning)_42%,var(--vui-border-subtle))] [--node-role-fg:var(--state-warning)]",
    nodeStale: "border-[color-mix(in_srgb,var(--state-error)_48%,var(--vui-border-subtle))]",
    researchCanvasPanelHidden: "!hidden",
    sourceCollectionStagePrimaryAction: "w-fit max-w-full",
    sourceCollectionStageSecondaryAction: "w-fit max-w-full",
    sourceCollectionSourceDetailActions: "flex-wrap",
    sourceCollectionPanelActions: "flex-wrap",
    sourceCollectionCandidateListShell:
      "min-h-0 content-start items-start self-start overflow-y-auto [scrollbar-gutter:stable]",
    sourceCollectionFilterBar: "grid-cols-[repeat(5,minmax(0,1fr))]",
    sourceCollectionFocusedPanel:
      "grid-cols-[minmax(0,1fr)_minmax(320px,380px)] isolate",
    sourceCollectionPagination: "select-none whitespace-nowrap [writing-mode:horizontal-tb]",
    sourceCollectionResultStatus:
      "grid-cols-[minmax(220px,1fr)_minmax(80px,112px)_minmax(150px,240px)] grid-rows-[auto_auto_auto]",
    sourceCollectionStageCardHead:
      "grid-cols-[minmax(120px,0.24fr)_minmax(0,1fr)_max-content] max-[1320px]:grid-cols-[minmax(0,1fr)] max-[1320px]:[&_.sourceCollectionStageProjection]:col-span-full max-[1320px]:[&_.sourceCollectionStageProjection]:row-start-2",
    sourceCollectionStageModules: "grid-cols-[repeat(3,minmax(0,1fr))]",
    sourceCollectionStageWorkspace: "grid-rows-[auto_auto_minmax(0,1fr)]",
    sourceCollectionTraceBody: "grid-cols-[44px_minmax(0,1fr)] [&_p]:line-clamp-2",
    teamContextActions: "!flex flex-nowrap items-center justify-end gap-1.5",
    teamContextBar:
      "mx-2 mt-1 !grid grid-cols-[minmax(0,1fr)_auto] items-center gap-2 px-2 py-1",
    teamContextChips:
      "mx-2 !grid grid-cols-[repeat(4,max-content)] justify-start gap-1.5 overflow-x-auto p-0 [scrollbar-width:thin]",
    teamSelectField:
      "grid grid-cols-[max-content_minmax(180px,300px)] items-center gap-1.5 text-[var(--vui-font-xs)] font-semibold text-[var(--fg-secondary)]",
    teamMemoryActionRail: "min-h-[44px]",
    teamMemoryIndex: "grid-cols-[repeat(auto-fit,minmax(300px,1fr))]",
    teamMemoryMemberActions: "[&_a_span]:hidden",
    teamMemoryMemberHeading: "hidden",
    toolbarActions:
      "!flex min-w-[220px] max-w-[min(100%,560px)] flex-wrap items-center justify-end gap-1.5 overflow-visible [&_a]:min-w-[72px] [&_a]:whitespace-nowrap [&_button]:min-w-[72px] [&_button]:whitespace-nowrap",
    workflowGraphFrame: "h-full overflow-hidden",
    workspace:
      "!grid min-h-0 grid-cols-[minmax(520px,1fr)_minmax(300px,380px)] gap-2 overflow-hidden px-2 pb-2 pt-1",
    workspaceResearch: "grid-cols-[minmax(0,1fr)]",
    workspaceResearchCanvas:
      "!grid h-full grid-cols-[minmax(520px,1fr)_minmax(300px,380px)] overflow-hidden",
  },
});

export default styles;
