import { describe, expect, it } from "vitest";

// @ts-expect-error Vitest runs this contract in Node; the web project intentionally omits global Node types.
import { readFileSync } from "node:fs";
import { resolveLegacyTeamsRedirect } from "./LegacyTeamsRedirect";
import routeSource from "./TeamsRoute.tsx?raw";
import routeStyles from "./TeamsRoute.module.css";
import routerSource from "../app/router.tsx?raw";

const routeStylesSource = readFileSync(new URL("./TeamsRoute.module.css", import.meta.url), "utf-8");

describe("TeamsRoute layout contract", () => {
  it("uses shell language state without loading the full app dictionary", () => {
    expect(routeSource).toContain("useShellI18n");
    expect(routeSource).toContain("const { lang } = useShellI18n()");
    expect(routeSource).not.toContain("useAppI18n");
  });

  it("is mounted as the top-level Team workspace with legacy redirects", () => {
    expect(routerSource).toContain('path: "teams"');
    expect(routerSource).toContain("lazyElement(<TeamsRoute />)");
    expect(routerSource).toContain('path: "agents/teams"');
    expect(routerSource).toContain('path: "research"');
    expect(routerSource).toContain("<LegacyTeamsRedirect />");
    expect(routeSource).not.toContain("AgentManagementNav");
    expect(routeSource).toContain("团队工作台 / 组织画布");
    expect(routeSource).toContain("Team Workspace / Canvas");
  });

  it("preserves selected Team deep links from legacy routes", () => {
    expect(resolveLegacyTeamsRedirect("")).toBe("/teams");
    expect(resolveLegacyTeamsRedirect("?team=research-core")).toBe("/teams?team=research-core");
  });

  it("uses Team APIs and Agent Center as the binding source", () => {
    expect(routeSource).toContain('fetchJson<TeamListPayload>("/api/teams")');
    expect(routeSource).toContain('fetchJson<TeamTemplateListPayload>("/api/team-templates")');
    expect(routeSource).toContain("/api/team-templates/${encodeURIComponent(templateId)}/instantiate");
    expect(routeSource).toContain("instantiateTeamTemplateMutation");
    expect(routeSource).toContain("fetchJson<Team>(`/api/teams/${encodeURIComponent(effectiveTeamId)}`)");
    expect(routeSource).toContain('fetchJson<AgentConfigWorkspace>("/api/agents/config-workspace")');
    expect(routeSource).toContain("fetchJson<Team>(`/api/teams/${encodeURIComponent(teamId)}`");
    expect(routeSource).toContain('method: "DELETE"');
    expect(routeSource).toContain("sendTeamProjectBusMessage(payload)");
    expect(routeSource).toContain("listProjectAgentBusTimeline(PROJECT_AGENT_BUS_TEAM_TIMELINE_LIMIT)");
    expect(routeSource).toContain("revokeProjectAgentBusMessage({");
    expect(routeSource).toContain("/api/teams/${encodeURIComponent(teamId)}/chat-room/sync");
    expect(routeSource).toContain("syncTeamChatRoomMutation");
    expect(routeSource).toContain("fetchJson<ChatRoomDetail>(`/api/chat-rooms/${payload.roomId}/rounds`");
    expect(routeSource).toContain("fetchJson<ChatRoomDetail>(`/api/chat-rooms/${encodeURIComponent(linkedChatRoomId)}`)");
    expect(routeSource).toContain("linkedRoomRefetchInterval(pageVisible");
    expect(routeSource).toContain("latestChatRoomRound(linkedRoomDetail)");
    expect(routeSource).toContain("fetchJson<TeamWorkflowOrchestration>(`/api/teams/${encodeURIComponent(effectiveTeamId)}/workflow-orchestration`)");
    expect(routeSource).toContain("fetchJson<TeamWorkflowCandidateListPayload>");
    expect(routeSource).toContain("fetchJson<TeamWorkflowCandidateGraphBuildPayload>");
    expect(routeSource).toContain("fetchJson<TeamWorkflowKnowledgeIngestionStatus>");
    expect(routeSource).toContain("fetchJson<TeamWorkflowOfficialModelEvidenceStatus>");
    expect(routeSource).toContain("TEAM_WORKFLOW_CANDIDATE_PREVIEW_LIMIT");
    expect(routeSource).toContain("TEAM_WORKFLOW_CANDIDATE_GRAPH_LIMIT");
    expect(routeSource).toContain("isResearchWorkflowTeam(selectedTeam)");
    expect(routeSource).toContain("researchWorkflowTeamSelected");
    expect(routeSource).toContain("teamWorkflowKnowledgeIngestionStatusQuery");
    expect(routeSource).toContain("/workflow-orchestration/knowledge-ingestion/status");
    expect(routeSource).toContain("teamWorkflowOfficialModelEvidenceStatusQuery");
    expect(routeSource).toContain("/workflow-orchestration/official-model-evidence/status");
    expect(routeSource).toContain("TeamWorkflowSourceQualityStatus");
    expect(routeSource).toContain("teamWorkflowSourceQualityStatusQuery");
    expect(routeSource).toContain("/workflow-orchestration/source-quality/status");
    expect(routeSource).toContain("/source-quality/assess");
    expect(routeSource).toContain("assessSourceQualityMutation");
    expect(routeSource).toContain("candidateSourceQualityAssessmentSummary");
    expect(routeSource).toContain("TeamWorkflowPaperNoteChunkStatus");
    expect(routeSource).toContain("teamWorkflowPaperNoteChunkStatusQuery");
    expect(routeSource).toContain("/workflow-orchestration/paper-note-chunks/status");
    expect(routeSource).toContain("/paper-note-chunks/plan");
    expect(routeSource).toContain("planPaperNoteChunksMutation");
    expect(routeSource).toContain("sourceCandidateHasCompletedExtraction");
    expect(routeSource).toContain("candidatePaperNoteChunkPlanSummary");
    expect(routeSource).toContain("ResearchStageRoundStatusPayload");
    expect(routeSource).toContain("researchStageRoundStatusQuery");
    expect(routeSource).toContain("/workflow-orchestration/stage-rounds/status");
    expect(routeSource).toContain("/workflow-orchestration/stage-rounds/start");
    expect(routeSource).toContain("startResearchStageRoundMutation");
    expect(routeSource).toContain("startSourceCollectionRunMutation");
    expect(routeSource).toContain("recordSourceCollectionOutputMutation");
    expect(routeSource).toContain("/workflow-orchestration/source-collection-runs");
    expect(routeSource).toContain("/api/data-processing/runs?limit=${SOURCE_COLLECTION_RUN_PREVIEW_LIMIT}");
    expect(routeSource).toContain("/collection-assignments/${encodeURIComponent(payload.draft.assignmentId)}/outputs");
    expect(routeSource).toContain("/source-candidate");
    expect(routeSource).toContain("sourceCollectionRunsForTeam");
    expect(routeSource).toContain("SOURCE_COLLECTION_DEFAULT_ROLES");
    expect(routeSource).toContain("candidateType=candidate_graph");
    expect(routeSource).toContain("/workflow-orchestration/candidate-graph");
    expect(routeSource).toContain("buildCandidateGraphMutation");
    expect(routeSource).toContain('source: "team_workspace"');
    expect(routeSource).toContain("teamId: payload.teamId");
    expect(routeSource).toContain("startTeamRoundMutation");
    expect(routeSource).toContain("chatWorkspaceCache.afterTeamRoomMembershipChanged(variables.teamId, room.roomId)");
    expect(routeSource).toContain("chatWorkspaceCache.afterTeamRoomMembershipChanged(team.teamId, team.linkedChatRoom.roomId)");
    expect(routeSource).toContain("teamConversationStatusLabel");
    expect(routeSource).toContain("selectedTeam?.conversation");
    expect(routeSource).toContain("isAiSearchScopeTeam(selectedTeam)");
    expect(routeSource).toContain("showAiSearchScopePanel");
    expect(routeSource).toContain("renderAiSearchSourceScopePanel");
    expect(routeSource).toContain("selectedTeam?.sourceScope");
    expect(routeSource).toContain("AI 搜索范围白名单");
    expect(routeSource).toContain("结论需一手证据");
    expect(routeSource).toContain("默认启用");
    expect(routeSource).toContain("仅信号");
    expect(routeSource).toContain("/api/teams/${encodeURIComponent(nextCanvas.teamId)}/canvas");
    expect(routeSource).toContain("成员源");
    expect(routeSource).toContain("Member source");
    expect(routeSource).toContain("Agent Center");
    expect(routeSource).toContain("team_organization_canvas");
    expect(routeSource).not.toContain("/api/research/flow-canvas");
  });

  it("can deep-link from Agent references to a selected Team", () => {
    expect(routeSource).toContain("useSearchParams");
    expect(routeSource).toContain('searchParams.get("team")');
    expect(routeSource).toContain('searchParams.get("agent")');
    expect(routeSource).toContain('searchParams.get("researchView")');
    expect(routeSource).toContain("parseResearchWorkspaceView");
    expect(routeSource).toContain("requestedAgentTeamId");
    expect(routeSource).toContain("setSearchParams({ team: team.teamId })");
  });

  it("keeps evolution system teams out of the custom Team list", () => {
    expect(routeSource).toContain("EVOLUTION_SYSTEM_TEAM_IDS");
    expect(routeSource).toContain('"self-evolution-team"');
    expect(routeSource).toContain('"supervised-evolution-team"');
    expect(routeSource).toContain("isEvolutionSystemTeam");
    expect(routeSource).toContain("team.teamKind === \"self_evolution\"");
    expect(routeSource).toContain("team.teamKind === \"supervised_evolution\"");
    expect(routeSource).toContain("team.teamSource === \"self_evolution\"");
    expect(routeSource).toContain("team.teamSource === \"supervised_evolution\"");
    expect(routeSource).toContain("const visibleTeams = useMemo(() => teams.filter((team) => !isEvolutionSystemTeam(team)), [teams])");
    expect(routeSource).toContain("const visibleTeamIds = useMemo(() => new Set(visibleTeams.map((team) => team.teamId)), [visibleTeams])");
    expect(routeSource).toContain("requestedVisibleTeamId");
    expect(routeSource).toContain("requestedVisibleAgentTeamId");
    expect(routeSource).toContain("selectedVisibleTeamId");
    expect(routeSource).toContain("fallbackVisibleTeamId");
    expect(routeSource).toContain("const hasTeams = visibleTeams.length > 0");
    expect(routeSource).toContain("visibleTeamSummary.activeTeamCount");
    expect(routeSource).toContain("{visibleTeams.map((team) => (");
    expect(routeSource).toContain("visibleTeams.find((team) => team.teamId === effectiveTeamId)");
    expect(routeSource).not.toContain("{teams.map((team) => (");
    expect(routeSource).not.toContain("teams[0]?.teamId");
  });

  it("renders a dense list canvas inspector workflow", () => {
    expect(routeSource).toContain("teamList");
    expect(routeSource).toContain("canvasPanel");
    expect(routeSource).toContain("inspector");
    expect(routeSource).toContain("hasTeams");
    expect(routeSource).toContain("styles.workspaceEmpty");
    expect(routeSource).toContain("styles.emptyCanvasPanel");
    expect(routeSource).toContain("先创建团队，再进入组织画布");
    expect(routeSource).toContain("teamNameInputRef");
    expect(routeSource).toContain("从模板创建");
    expect(routeSource).toContain("创建 Demo 团队");
    expect(routeSource).toContain("selectedTemplate.chatRoom.mode");
    expect(routeSource).toContain("styles.templatePanel");
    expect(routeSource).toContain("styles.templatePicker");
    expect(routeSource).toContain("styles.templateSelect");
    expect(routeSource).toContain("styles.templatePreview");
    expect(routeSource).not.toContain("styles.templateCard");
    expect(routeSource).toContain("先填写团队名称，再创建团队。");
    expect(routeSource).toContain("styles.formError");
    expect(routeSource).toContain("styles.formHint");
    expect(routeSource).toContain("绑定 Agent");
    expect(routeSource).toContain("styles.nodeBindingSection");
    expect(routeSource).toContain("styles.nodeBindingPlaceholder");
    expect(routeSource).toContain("正在读取团队节点");
    expect(routeSource).toContain("agentTeamMembership");
    expect(routeSource).toContain("membership.teamId !== selectedTeam?.teamId");
    expect(routeSource).toContain("disabled={ownedByOtherTeam}");
    expect(routeSource).toContain("已属于");
    expect(routeSource).toContain("接入主干");
    expect(routeSource).toContain("保存节点");
    expect(routeSource).toContain("归档");
    expect(routeSource).toContain("解绑节点");
    expect(routeSource).toContain("删除节点");
    expect(routeSource).toContain("团队任务");
    expect(routeSource).toContain("启动团队讨论");
    expect(routeSource).toContain("teamTaskTopic");
    expect(routeSource).toContain("linkedRoomBusy");
    expect(routeSource).toContain("最近团队任务");
    expect(routeSource).toContain("styles.teamRoundPanel");
    expect(routeSource).toContain("styles.teamRoundCard");
    expect(routeSource).toContain("查看完整群聊");
    expect(routeSource).toContain("styles.teamTaskForm");
    expect(routeSource).toContain("科研流程");
    expect(routeSource).toContain("TeamWorkflowOrchestration");
    expect(routeSource).toContain("teamWorkflowQuery");
    expect(routeSource).toContain("teamWorkflowCandidatesQuery");
    expect(routeSource).toContain("teamWorkflowValidationSummary");
    expect(routeSource).toContain("teamWorkflowKnowledgeIngestionStatus");
    expect(routeSource).toContain("teamWorkflowOfficialModelEvidenceStatus");
    expect(routeSource).toContain("workflowStateLabel");
    expect(routeSource).toContain("workflowQualityTone");
    expect(routeSource).toContain("workflowIngestionStatusLabel");
    expect(routeSource).toContain("workflowIngestionTone");
    expect(routeSource).toContain("styles.workflowPanel");
    expect(routeSource).toContain("styles.workflowStats");
    expect(routeSource).toContain("styles.workflowIngestionPanel");
    expect(routeSource).toContain("styles.workflowIngestionStages");
    expect(routeSource).toContain("styles.workflowIngestionBoundary");
    expect(routeSource).toContain("styles.workflowGraphPanel");
    expect(routeSource).toContain("styles.workflowGraphFrame");
    expect(routeSource).toContain("styles.workflowGraphNode");
    expect(routeSource).toContain("styles.workflowGraphBoundary");
    expect(routeSource).toContain("styles.workflowCandidateList");
    expect(routeSource).toContain("styles.workflowValidation");
    expect(routeSource).toContain("RESEARCH_WORKSPACE_NAV_ITEMS");
    expect(routeSource).toContain("ResearchWorkspaceView");
    expect(routeSource).toContain("researchWorkspaceView");
    expect(routeSource).toContain("selectResearchWorkspaceView");
    expect(routeSource).toContain("selectTeamRecord");
    expect(routeSource).toContain("renderResearchWorkspaceNav");
    expect(routeSource).toContain("renderResearchStageLauncher");
    expect(routeSource).toContain("researchWorkspaceViewLabel");
    expect(routeSource).toContain("styles.workspaceResearch");
    expect(routeSource).toContain("styles.workspaceResearchCanvas");
    expect(routeSource).toContain("styles.researchIndexPanel");
    expect(routeSource).toContain("styles.researchInspector");
    expect(routeSource).toContain("styles.researchCanvasPanelHidden");
    expect(routeSource).toContain("styles.aiSearchScopePanel");
    expect(routeSource).toContain("styles.aiSearchSourceGroups");
    expect(routeSource).toContain("styles.aiSearchSourceItem");
    expect(routeSource).toContain("!aiSearchScopeTeamSelected && (!researchWorkflowTeamSelected");
    expect(routeSource).toContain("科研三阶段索引");
    expect(routeSource).toContain("团队专属阶段页");
    expect(routeSource).toContain("三阶段");
    expect(routeSource).toContain("ResearchStageWorkspaceView");
    expect(routeSource).toContain("researchWorkspaceStageRoute");
    expect(routeSource).toContain('view: "knowledge_collection"');
    expect(routeSource).toContain('view: "experiment"');
    expect(routeSource).toContain('view: "iteration"');
    expect(routeSource).not.toContain('view: "source_collection", zh: "资料搜集"');
    expect(routeSource).toContain("组织画布");
    expect(routeSource).toContain('canvas: { zh: "组织画布", en: "Canvas" }');
    expect(routeSource).toContain("资料搜集");
    expect(routeSource).toContain("科研三阶段启动台");
    expect(routeSource).toContain("启动知识搜集");
    expect(routeSource).toContain("启动实验规划");
    expect(routeSource).toContain("启动迭代");
    expect(routeSource).not.toContain("{researchWorkflowTeamSelected ? renderResearchWorkspaceNav() : null}");
    expect(routeSource).toContain("onClick={() => selectTeamRecord(team)}");
    expect(routeSource).toContain("setResearchWorkspaceView(\"overview\")");
    expect(routeSource).toContain("{renderResearchWorkspaceNav()}");
    expect(routeSource).toContain("{renderResearchStageLauncher()}");
    expect(routeSource).toContain("researchWorkflowTeamSelected && !researchCanvasVisible");
    expect(routeSource).toContain("搜集、筛选、候选与入库边界");
    expect(routeSource).toContain("资料搜集 / 资料筛选 / 知识入库 / 候选图谱");
    expect(routeSource).toContain("实验规划 / Baseline / 指标 / 结果记录");
    expect(routeSource).toContain("复盘 / 版本化 / 改进计划 / 交付门禁");
    expect(routeSource).toContain("value === \"source_collection\"");
    expect(routeSource).toContain("return \"knowledge_collection\"");
    expect(routeSource).toContain('id="research-workflow-overview"');
    expect(routeSource).toContain('knowledge_collection: "research-workflow-knowledge-collection"');
    expect(routeSource).toContain('id="research-workflow-source-collection"');
    expect(routeSource).toContain('id="research-organization-canvas"');
    expect(routeSource).toContain('researchWorkspaceView === "canvas"');
    expect(routeSource).toContain("showNodeBindingPanel");
    expect(routeSource).toContain("showWorkflowPanel");
    expect(routeSource).toContain("showResearchSourceCollection");
    expect(routeSource).toContain("sourceCollectionAgentIdsFromCanvas");
    expect(routeSource).toContain("researchSourceCollectionRoute");
    expect(routeSource).toContain("teamWorkspaceRoute");
    expect(routeSource).toContain("sourceCollectionTraceMessages");
    expect(routeSource).toContain("renderSourceCollectionConversation");
    expect(routeSource).toContain("renderSourceCollectionControlsPanel");
    expect(routeSource).toContain("知识搜集工作台");
    expect(routeSource).toContain("搜集对话流");
    expect(routeSource).toContain("返回团队页面");
    expect(routeSource).toContain("实验规划工作台");
    expect(routeSource).toContain("迭代优化工作台");
    expect(routeSource).toContain("renderResearchStageStandalonePage");
    expect(routeSource).toContain("不自动进入下一阶段。");
    expect(routeSource).toContain("Source Quality Assessment Agent");
    expect(routeSource).toContain("知识入库状态");
    expect(routeSource).toContain("模型调用证据链");
    expect(routeSource).toContain("证据登记，不是正式知识");
    expect(routeSource).toContain("CandidateStore、Team Knowledge 和正式同步边界");
    expect(routeSource).toContain("资料搜集执行");
    expect(routeSource).toContain("启动搜集批次");
    expect(routeSource).toContain("手工回写一条搜集结果");
    expect(routeSource).toContain("回写并导入候选");
    expect(routeSource).toContain("原始位置");
    expect(routeSource).toContain("不触发外部搜索，不写正式知识/RAG/图谱");
    expect(routeSource).toContain("正式知识写入关闭");
    expect(routeSource).toContain("候选图谱");
    expect(routeSource).toContain("刷新图谱");
    expect(routeSource).toContain("CandidateStore 快照 · 正式知识/RAG/图谱写入关闭");
    expect(routeSource).toContain("paper_note 分块计划");
    expect(routeSource).toContain("资料质量筛选");
    expect(routeSource).toContain("通过筛选");
    expect(routeSource).toContain("退回补资料");
    expect(routeSource).toContain("Source Quality Assessment Agent");
    expect(routeSource).toContain("生成分块计划");
    expect(routeSource).toContain("重建分块计划");
    expect(routeSource).toContain("后续 paper_note draft 需带 chunkId");
    expect(routeSource).toContain("选择 research-team / ai科学研究团队后显示挑战杯科研流程。");
    expect(routeSource).toContain("团队广播");
    expect(routeSource).toContain("发送给团队");
    expect(routeSource).toContain("最近团队广播");
    expect(routeSource).toContain("已衔接群聊");
    expect(routeSource).toContain("to={`/chat?room=${encodeURIComponent(selectedTeamStartRoundResult.roomId)}`}");
    expect(routeSource).toContain("to={`/chat?room=${encodeURIComponent(latestTeamRound.roomId)}`}");
    expect(routeSource).toContain("styles.linkedRoomLine");
    expect(routeSource).toContain("styles.toolbarLink");
    expect(routeSource).toContain("teamBusEvents");
    expect(routeSource).toContain("isProjectAgentBusEventRevoked");
    expect(routeSource).toContain("projectAgentBusEventsForTeam");
    expect(routeSource).toContain("revokeTeamMessageMutation");
    expect(routeSource).toContain("styles.teamHistoryPanel");
    expect(routeSource).toContain("interrupt_targets");
    expect(routeSource).toContain("edges: canvas.edges.filter((edge) => edge.source !== deletedNodeId && edge.target !== deletedNodeId)");
    expect(routeStyles.templatePanel).toBeTypeOf("string");
    expect(routeStyles.templatePicker).toBeTypeOf("string");
    expect(routeStyles.templateSelect).toBeTypeOf("string");
    expect(routeStyles.templatePreview).toBeTypeOf("string");
    expect(routeStyles.nodeBindingSection).toBeTypeOf("string");
    expect(routeStyles.nodeBindingPlaceholder).toBeTypeOf("string");
    expect(routeStyles.workflowPanel).toBeTypeOf("string");
    expect(routeStyles.workflowStats).toBeTypeOf("string");
    expect(routeStyles.workflowIngestionPanel).toBeTypeOf("string");
    expect(routeStyles.workflowIngestionStages).toBeTypeOf("string");
    expect(routeStyles.workflowIngestionBoundary).toBeTypeOf("string");
    expect(routeStyles.workflowSourceQualityPanel).toBeTypeOf("string");
    expect(routeStyles.workflowSourceQualityStats).toBeTypeOf("string");
    expect(routeStyles.workflowSourceQualityQueue).toBeTypeOf("string");
    expect(routeStyles.workflowPaperNoteChunkPanel).toBeTypeOf("string");
    expect(routeStyles.workflowPaperNoteChunkStats).toBeTypeOf("string");
    expect(routeStyles.workflowPaperNoteChunkPlans).toBeTypeOf("string");
    expect(routeStyles.workflowModelEvidencePanel).toBeTypeOf("string");
    expect(routeStyles.workflowModelEvidenceStats).toBeTypeOf("string");
    expect(routeStyles.workflowModelEvidenceCoverage).toBeTypeOf("string");
    expect(routeStyles.workflowSourceCollectionPanel).toBeTypeOf("string");
    expect(routeStyles.workflowSourceCollectionForm).toBeTypeOf("string");
    expect(routeStyles.workflowSourceCollectionRuns).toBeTypeOf("string");
    expect(routeStyles.workflowSourceCollectionAssignments).toBeTypeOf("string");
    expect(routeStyles.workflowSourceCollectionOutputForm).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionPage).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionPageGrid).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionConversationPanel).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionTraceMessage).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionTraceStorage).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionControlPanel).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionStageModules).toBeTypeOf("string");
    expect(routeStyles.researchStagePage).toBeTypeOf("string");
    expect(routeStyles.researchStageHeroPanel).toBeTypeOf("string");
    expect(routeStyles.researchStageActionPanel).toBeTypeOf("string");
    expect(routeStyles.researchStageModuleGrid).toBeTypeOf("string");
    expect(routeStyles.researchStageBoundaryPanel).toBeTypeOf("string");
    expect(routeStyles.workflowGraphPanel).toBeTypeOf("string");
    expect(routeStyles.workflowGraphFrame).toBeTypeOf("string");
    expect(routeStyles.workflowGraphNode).toBeTypeOf("string");
    expect(routeStyles.workflowGraphEdge).toBeTypeOf("string");
    expect(routeStyles.workflowGraphBoundary).toBeTypeOf("string");
    expect(routeStyles.workflowCandidateList).toBeTypeOf("string");
    expect(routeStyles.workflowCandidateActions).toBeTypeOf("string");
    expect(routeStyles.workflowValidation).toBeTypeOf("string");
    expect(routeStyles.workspaceResearch).toBeTypeOf("string");
    expect(routeStyles.workspaceResearchCanvas).toBeTypeOf("string");
    expect(routeStyles.researchIndexPanel).toBeTypeOf("string");
    expect(routeStyles.researchIndexItem).toBeTypeOf("string");
    expect(routeStyles.researchIndexItemActive).toBeTypeOf("string");
    expect(routeStyles.researchInspector).toBeTypeOf("string");
    expect(routeStyles.researchCanvasPanelHidden).toBeTypeOf("string");
    expect(routeStyles.aiSearchScopePanel).toBeTypeOf("string");
    expect(routeStyles.aiSearchScopeStats).toBeTypeOf("string");
    expect(routeStyles.aiSearchSourceGroups).toBeTypeOf("string");
    expect(routeStyles.aiSearchSourceItem).toBeTypeOf("string");
    expect(routeStyles.workspaceEmpty).toBeTypeOf("string");
    expect(routeStyles.emptyCanvasPanel).toBeTypeOf("string");
    expect(routeStylesSource).toContain("height: 100%");
    expect(routeStylesSource).toContain("overflow: hidden");
  });

  it("keeps Team actions scoped to the selected Team or message event", () => {
    expect(routeSource).toContain("canvasSavePendingForTeam");
    expect(routeSource).toContain("saveCanvasMutation.variables?.teamId === teamId");
    expect(routeSource).toContain("selectedTeamSyncPending");
    expect(routeSource).toContain("syncTeamChatRoomMutation.variables === selectedTeam?.teamId");
    expect(routeSource).toContain("selectedTeamStartRoundPending");
    expect(routeSource).toContain("startTeamRoundMutation.variables?.teamId === selectedTeam?.teamId");
    expect(routeSource).toContain("selectedTeamMessagePending");
    expect(routeSource).toContain("sendTeamMessageMutation.variables?.teamId === selectedTeam?.teamId");
    expect(routeSource).toContain("revokeTeamMessageMutation.variables?.eventId === event.eventId");
    expect(routeSource).toContain("revokeTeamMessageMutation.mutate({ teamId: selectedTeam.teamId, eventId: event.eventId })");
    expect(routeSource).not.toContain("chatWorkspaceCache.afterTeamChanged(selectedTeamId || undefined)");
    expect(routeSource).not.toContain("revokeTeamMessageMutation.mutate(event.eventId)");
  });

  it("renders visible directional communication edges on the Team canvas", () => {
    expect(routeSource).toContain("<marker");
    expect(routeSource).toContain('id="team-edge-arrow"');
    expect(routeSource).toContain("key={edge.id}");
    expect(routeSource).toContain("Q ${line.cx} ${line.cy}");
    expect(routeSource).toContain("nodeBoundaryPoint");
    expect(routeSource).toContain("distanceToRectEdge");
    expect(routeSource).toContain("edgeLine(edge, canvasNodes, visibleEdges)");
    expect(routeSource).not.toContain("<line key={edge.id}");
    expect(routeSource).toContain("className={styles.edges}");
  });

  it("separates organization lines from information lines by default", () => {
    expect(routeSource).toContain("showCommunicationEdges");
    expect(routeSource).toContain("isCommunicationEdge(edge)");
    expect(routeSource).toContain("organizationEdges");
    expect(routeSource).toContain("communicationEdges");
    expect(routeSource).toContain("visibleCommunicationEdges");
    expect(routeSource).toContain("visibleCommunicationEdgeCount");
    expect(routeSource).toContain("visibleEdges");
    expect(routeSource).toContain("edge.type === \"communication\"");
    expect(routeSource).toContain("edge.type === \"collaborates_with\"");
    expect(routeSource).toContain("styles.edgeOrganization");
    expect(routeSource).toContain("styles.edgeCommunication");
    expect(routeSource).toContain("信息线");
    expect(routeSource).toContain("信息线已收起（");
    expect(routeSource).toContain("展开信息线");
    expect(routeSource).toContain("收起信息线");
    expect(routeSource).toContain("Info");
    expect(routeSource).toContain('type: "reports_to"');
    expect(routeSource).not.toContain("canvas?.edges.map((edge)");
  });

  it("centers compact Team canvases and renders function role badges", () => {
    expect(routeSource).toContain("canvasViewStyle");
    expect(routeSource).toContain("CANVAS_VIEWPORT_WIDTH");
    expect(routeSource).toContain("CANVAS_VIEWPORT_HEIGHT");
    expect(routeSource).toContain("canvasViewportStyle");
    expect(routeSource).toContain("lockedCanvasViewportStyle");
    expect(routeSource).toContain("setLockedCanvasViewportStyle(canvasViewportStyle)");
    expect(routeSource).toContain("canvasFrameSize");
    expect(routeSource).toContain("ResizeObserver");
    expect(routeSource).toContain("styles.canvasViewport");
    expect(routeSource).toContain("--canvas-offset-x");
    expect(routeSource).toContain("--canvas-scale");
    expect(routeSource).toContain("--node-x");
    expect(routeSource).toContain("roleBadgeTone");
    expect(routeSource).toContain("teamNodeFunctionLabel");
    expect(routeSource).toContain("能力管家");
    expect(routeSource).toContain("styles.nodeRoleBadge");
    expect(routeSource).toContain("styles.nodeRoleBadgeLead");
    expect(routeSource).toContain("styles.nodeRoleBadgeAdvisor");
    expect(routeSource).toContain("styles.nodeRoleBadgeSteward");
  });

  it("lets users drag canvas nodes and persist their positions", () => {
    expect(routeSource).toContain("nodePositionDrafts");
    expect(routeSource).toContain("dragStateRef");
    expect(routeSource).toContain("dragFrameRef");
    expect(routeSource).toContain("startNodeDrag");
    expect(routeSource).toContain("moveNodeDrag");
    expect(routeSource).toContain("finishNodeDrag");
    expect(routeSource).toContain("requestNodeDragFrame");
    expect(routeSource).toContain("window.requestAnimationFrame");
    expect(routeSource).toContain("window.cancelAnimationFrame");
    expect(routeSource).toContain("commitNodeDragPosition(dragState)");
    expect(routeSource).toContain("setPointerCapture(event.pointerId)");
    expect(routeSource).toContain("releasePointerCapture(event.pointerId)");
    expect(routeSource).toContain("nodes: canvas.nodes.map((node) => (node.id === dragState.nodeId");
    expect(routeSource).toContain("onPointerDown={(event) => startNodeDrag(event, node)}");
    expect(routeSource).toContain("onPointerMove={moveNodeDrag}");
    expect(routeSource).toContain("onPointerUp={finishNodeDrag}");
    expect(routeSource).toContain("edgeLine(edge, canvasNodes, visibleEdges)");
  });
});
