const styles = {
  sourceCollectionPageBody:
    "sourceCollectionPageBody min-w-0 w-full max-w-none flex-1 [font-size:var(--vui-font-sm)] leading-[var(--vui-line-readable)] text-[var(--fg-secondary)] !grid h-full min-h-0 grid-cols-[clamp(228px,14vw,278px)_minmax(520px,1fr)_clamp(270px,17vw,338px)] grid-rows-[auto_auto_minmax(0,1fr)] content-stretch gap-[var(--team-workbench-gap)] overflow-hidden p-[var(--team-workbench-gap)] [&>[data-vui-product=team-stage-command-bar]]:col-span-3 [&>[data-vui-product=team-stage-command-bar]]:col-start-1 [&>[data-vui-product=team-stage-command-bar]]:row-start-1 [&>[data-vui-product=team-stage-pipeline]]:col-start-1 [&>[data-vui-product=team-stage-pipeline]]:row-start-3 [&>[data-vui-product=team-stage-pipeline]]:grid-cols-[minmax(0,1fr)] [&>[data-vui-product=team-stage-pipeline]]:content-start max-[1020px]:h-auto max-[1020px]:grid-cols-[minmax(0,1fr)] max-[1020px]:grid-rows-[auto_auto_auto_auto] max-[1020px]:overflow-auto max-[1020px]:[&>[data-vui-product=team-stage-command-bar]]:col-span-1 max-[1020px]:[&>[data-vui-product=team-stage-pipeline]]:row-start-3",
  sourceCollectionPageBodyCompact:
    "sourceCollectionPageBody sourceCollectionPageBodyCompact min-w-0 w-full max-w-none flex-1 [font-size:var(--vui-font-sm)] leading-[var(--vui-line-readable)] text-[var(--fg-secondary)] !grid h-full min-h-0 grid-cols-[clamp(228px,14vw,278px)_minmax(520px,1fr)_clamp(270px,17vw,338px)] grid-rows-[auto_auto_minmax(0,1fr)] content-stretch gap-[var(--team-workbench-gap)] overflow-hidden p-[var(--team-workbench-gap)] [&>*]:min-w-0 [&>[data-vui-product=team-stage-command-bar]]:col-span-3 [&>[data-vui-product=team-stage-command-bar]]:col-start-1 [&>[data-vui-product=team-stage-command-bar]]:row-start-1 [&>[data-vui-product=team-stage-pipeline]]:col-start-1 [&>[data-vui-product=team-stage-pipeline]]:row-start-3 [&>[data-vui-product=team-stage-pipeline]]:grid-cols-[minmax(0,1fr)] [&>[data-vui-product=team-stage-pipeline]]:content-start max-[1020px]:h-auto max-[1020px]:grid-cols-[minmax(0,1fr)] max-[1020px]:grid-rows-[auto_auto_auto_auto] max-[1020px]:overflow-auto max-[1020px]:[&>[data-vui-product=team-stage-command-bar]]:col-span-1 max-[1020px]:[&>[data-vui-product=team-stage-pipeline]]:row-start-3",
  sourceCollectionPageGrid:
    "sourceCollectionPageGrid min-w-0 grid h-full min-h-0 max-w-full content-stretch gap-[var(--team-workbench-gap)] col-start-2 col-span-2 row-start-2 row-span-2 grid-cols-[minmax(0,1fr)] overflow-hidden max-[1020px]:col-start-1 max-[1020px]:col-span-1 max-[1020px]:row-start-4 max-[1020px]:row-span-1 max-[1020px]:!h-auto max-[1020px]:overflow-visible",
  sourceCollectionPageGridCompact:
    "sourceCollectionPageGrid sourceCollectionPageGridCompact min-w-0 grid h-full min-h-0 max-w-full content-stretch gap-[var(--team-workbench-gap)] col-start-2 col-span-2 row-start-2 row-span-2 grid-cols-[minmax(0,1fr)] overflow-hidden max-[1020px]:col-start-1 max-[1020px]:col-span-1 max-[1020px]:row-start-4 max-[1020px]:row-span-1 max-[1020px]:h-auto max-[1020px]:overflow-visible",
  sourceCollectionRunContext:
    "sourceCollectionRunContext min-w-0 grid col-start-1 row-start-2 content-start gap-2 overflow-auto [&_.sourceCollectionRunSwitcher]:!grid-cols-[minmax(0,1fr)] [&_.sourceCollectionRunSwitcherMain]:!grid-cols-[minmax(0,1fr)] [&_.sourceCollectionRunSwitcherStats]:!grid [&_.sourceCollectionRunSwitcherStats]:grid-cols-[repeat(2,minmax(0,1fr))] [&_.sourceCollectionRunSwitcherStats]:justify-stretch [&_.sourceCollectionRunSwitcherStats_span]:!whitespace-normal [&_.phaseCloseGateHeader]:!grid-cols-[minmax(0,1fr)] [&_.phaseCloseGateFacts]:!grid [&_.phaseCloseGateFacts]:grid-cols-[minmax(0,1fr)] max-[1020px]:row-start-2 max-[1020px]:overflow-visible",
} as const;

export default styles;
