import { describe, expect, it } from "vitest";

// @ts-expect-error Vitest runs this contract in Node; the web project intentionally omits global Node types.
import { readFileSync } from "node:fs";
import { resolveLegacyTeamsRedirect } from "./LegacyTeamsRedirect";
import routeSource from "./TeamsRoute.tsx?raw";
import routeStyles from "./TeamsRoute.module.css";
import routerSource from "../app/router.tsx?raw";

const routeStylesSource = readFileSync(new URL("./TeamsRoute.module.css", import.meta.url), "utf-8");

describe("TeamsRoute layout contract", () => {
  it("uses shell language state without loading the full app dictionary", () => {
    expect(routeSource).toContain("useShellI18n");
    expect(routeSource).toContain("const { lang } = useShellI18n()");
    expect(routeSource).not.toContain("useAppI18n");
  });

  it("is mounted as the top-level Team workspace with legacy redirects", () => {
    expect(routerSource).toContain('path: "teams"');
    expect(routerSource).toContain("guardedLazyElement(<TeamsRoute />)");
    expect(routerSource).toContain('path: "agents/teams"');
    expect(routerSource).toContain('path: "research"');
    expect(routerSource).toContain("<LegacyTeamsRedirect />");
    expect(routeSource).not.toContain("AgentManagementNav");
    expect(routeSource).toContain("团队工作台 / 组织画布");
    expect(routeSource).toContain("Team Workspace / Canvas");
  });

  it("preserves selected Team deep links from legacy routes", () => {
    expect(resolveLegacyTeamsRedirect("")).toBe("/teams");
    expect(resolveLegacyTeamsRedirect("?team=research-core")).toBe("/teams?team=research-core");
  });

  it("uses Team APIs and Agent Center as the binding source", () => {
    expect(routeSource).toContain('fetchJson<TeamListPayload>("/api/teams")');
    expect(routeSource).toContain("TEAM_BOOTSTRAP_REFETCH_STATUSES");
    expect(routeSource).toContain("query.state.data?.systemTeamBootstrap?.status");
    expect(routeSource).toContain("TEAM_BOOTSTRAP_ACTIVE_REFETCH_MS");
    expect(routeSource).not.toContain('fetchJson<TeamTemplateListPayload>("/api/team-templates")');
    expect(routeSource).not.toContain("/api/team-templates/${encodeURIComponent(templateId)}/instantiate");
    expect(routeSource).not.toContain("instantiateTeamTemplateMutation");
    expect(routeSource).toContain("TEAM_PICKER_TEAM_IDS");
    expect(routeSource).toContain("const TEAM_PICKER_TEAM_IDS = [AI_SEARCH_TEAM_ID, RESEARCH_TEAM_ID] as const");
    expect(routeSource).toContain("fetchJson<Team>(`/api/teams/${encodeURIComponent(effectiveTeamId)}`)");
    expect(routeSource).toContain('fetchJson<AgentConfigWorkspace>("/api/agents/config-workspace")');
    expect(routeSource).toContain("fetchJson<Team>(`/api/teams/${encodeURIComponent(teamId)}`");
    expect(routeSource).toContain('method: "DELETE"');
    expect(routeSource).toContain("sendTeamProjectBusMessage(payload)");
    expect(routeSource).toContain("kernelTaskCenterHref");
    expect(routeSource).toContain("listProjectAgentBusTimeline(PROJECT_AGENT_BUS_TEAM_TIMELINE_LIMIT)");
    expect(routeSource).toContain("revokeProjectAgentBusMessage({");
    expect(routeSource).toContain("/api/teams/${encodeURIComponent(teamId)}/chat-room/sync");
    expect(routeSource).toContain("syncTeamChatRoomMutation");
    expect(routeSource).toContain("fetchJson<ChatRoomDetail>(`/api/chat-rooms/${payload.roomId}/rounds`");
    expect(routeSource).toContain("fetchJson<ChatRoomDetail>(`/api/chat-rooms/${encodeURIComponent(linkedChatRoomId)}`)");
    expect(routeSource).toContain("linkedRoomRefetchInterval(pageVisible");
    expect(routeSource).toContain("latestChatRoomRound(linkedRoomDetail)");
    expect(routeSource).toContain("fetchJson<TeamWorkflowOrchestration>(`/api/teams/${encodeURIComponent(effectiveTeamId)}/workflow-orchestration`)");
    expect(routeSource).toContain("fetchJson<TeamWorkflowCandidateListPayload>");
    expect(routeSource).toContain("fetchJson<TeamWorkflowCandidateGraphBuildPayload>");
    expect(routeSource).toContain("fetchJson<TeamWorkflowKnowledgeIngestionStatus>");
    expect(routeSource).toContain("fetchJson<TeamWorkflowOfficialModelEvidenceStatus>");
    expect(routeSource).toContain("TEAM_WORKFLOW_CANDIDATE_PREVIEW_LIMIT");
    expect(routeSource).toContain("TEAM_WORKFLOW_CANDIDATE_GRAPH_LIMIT");
    expect(routeSource).toContain("isResearchWorkflowTeam(selectedTeam)");
    expect(routeSource).toContain("researchWorkflowTeamSelected");
    expect(routeSource).toContain("teamWorkflowKnowledgeIngestionStatusQuery");
    expect(routeSource).toContain("/workflow-orchestration/knowledge-ingestion/status");
    expect(routeSource).toContain("teamWorkflowOfficialModelEvidenceStatusQuery");
    expect(routeSource).toContain("/workflow-orchestration/official-model-evidence/status");
    expect(routeSource).toContain("TeamWorkflowSourceQualityStatus");
    expect(routeSource).toContain("teamWorkflowSourceQualityStatusQuery");
    expect(routeSource).toContain("/workflow-orchestration/source-quality/status");
    expect(routeSource).toContain("/source-quality/assess");
    expect(routeSource).toContain("assessSourceQualityMutation");
    expect(routeSource).toContain("candidateSourceQualityAssessmentSummary");
    expect(routeSource).toContain("TeamWorkflowPaperNoteChunkStatus");
    expect(routeSource).toContain("teamWorkflowPaperNoteChunkStatusQuery");
    expect(routeSource).toContain("/workflow-orchestration/paper-note-chunks/status");
    expect(routeSource).toContain("/paper-note-chunks/plan");
    expect(routeSource).toContain("planPaperNoteChunksMutation");
    expect(routeSource).toContain("sourceCandidateHasCompletedExtraction");
    expect(routeSource).toContain("candidatePaperNoteChunkPlanSummary");
    expect(routeSource).toContain("ResearchStageRoundStatusPayload");
    expect(routeSource).toContain("researchStageRoundStatusQuery");
    expect(routeSource).toContain("/workflow-orchestration/stage-rounds/status");
    expect(routeSource).toContain("/workflow-orchestration/stage-rounds/start");
    expect(routeSource).toContain("startResearchStageRoundMutation");
    expect(routeSource).toContain("seedSourceCollectionAgentSessionContextMutation");
    expect(routeSource).toContain("/source-collection-runs/${encodeURIComponent(payload.runId)}/agent-session-context");
    expect(routeSource).toContain("await seedSourceCollectionAgentSessionContextMutation.mutateAsync");
    expect(routeSource).toContain("TeamWorkflowSourceCollectionStageSessionTaskPayload");
    expect(routeSource).toContain("startSourceCollectionStageSessionTaskMutation");
    expect(routeSource).toContain("/source-collection-runs/${encodeURIComponent(payload.runId)}/stage-session-tasks");
    expect(routeSource).toContain("startSourceCollectionStageSessionTask(stageId");
    expect(routeSource).toContain("await startSourceCollectionStageSessionTaskMutation.mutateAsync");
    expect(routeSource).toContain("sourceCollectionStageTaskClickKey(stageId)");
    expect(routeSource).toContain("idempotencyKey: payload.idempotencyKey");
    expect(routeSource).toContain("idempotencyKey: sourceCollectionStageTaskClickKey(stageId)");
    expect(routeSource).toContain('memory: ["knowledge_steward", "candidate_graph"]');
    expect(routeSource).toContain("priorityByKey");
    expect(routeSource).toContain("ExperimentFullRunResultRegisterPayload");
    expect(routeSource).toContain("ExperimentResultKnowledgeIngestionPayload");
    expect(routeSource).toContain("/workflow-orchestration/experiments/plans/${encodeURIComponent(payload.plan.planId)}/full-run-result");
    expect(routeSource).toContain("/workflow-orchestration/experiments/plans/${encodeURIComponent(payload.plan.planId)}/knowledge-ingestion-request");
    expect(routeSource).toContain("registerExperimentFullRunResultMutation");
    expect(routeSource).toContain("requestExperimentKnowledgeIngestionMutation");
    expect(routeSource).toContain("登记 full-run");
    expect(routeSource).toContain("通知知识库 Agent");
    expect(routeSource).toContain("manualFullRunResult: true");
    expect(routeSource).toContain("explicitUserBoundary: true");
    expect(routeSource).toContain("stewardReviewRequired: true");
    expect(routeStylesSource).toContain(".experimentKnowledgePanel");
    expect(routeStylesSource).toContain(".experimentKnowledgeForm");
    expect(routeSource).toContain("ResearchLoopStatusPayload");
    expect(routeSource).toContain("researchLoopTemplatesQuery");
    expect(routeSource).toContain("researchLoopStatusQuery");
    expect(routeSource).toContain("/workflow-orchestration/research-loop/templates");
    expect(routeSource).toContain("/workflow-orchestration/research-loop/status");
    expect(routeSource).toContain("/workflow-orchestration/research-loop/loops");
    expect(routeSource).toContain("/workflow-orchestration/research-loop/loops/${encodeURIComponent(payload.loop.loopId)}/evidence");
    expect(routeSource).toContain("/workflow-orchestration/research-loop/loops/${encodeURIComponent(payload.loop.loopId)}/decision");
    expect(routeSource).toContain("createResearchLoopMutation");
    expect(routeSource).toContain("recordResearchLoopEvidenceMutation");
    expect(routeSource).toContain("recordResearchLoopDecisionMutation");
    expect(routeSource).toContain("renderResearchLoopPanel");
    expect(routeSource).toContain("Research Loop 模板");
    expect(routeSource).toContain("实验迭代决策");
    expect(routeSource).toContain("noSandboxRunner: true");
    expect(routeSource).toContain("noTrainingExecution: true");
    expect(routeSource).toContain("commandPreviewOnly: true");
    expect(routeSource).toContain("startSourceCollectionRunMutation");
    expect(routeSource).toContain("recordSourceCollectionOutputMutation");
    expect(routeSource).toContain("executeSourceCollectionSearchMutation");
    const executeSearchMutationSource = routeSource.slice(
      routeSource.indexOf("const executeSourceCollectionSearchMutation"),
      routeSource.indexOf("const extractSourceCollectionCandidatesMutation"),
    );
    expect(executeSearchMutationSource).toContain("researchStageRoundStatusQueryKey(variables.teamId)");
    expect(routeSource).toContain("/workflow-orchestration/source-collection-runs");
    expect(routeSource).toContain("/search/execute");
    expect(routeSource).toContain("/api/data-processing/runs?limit=${SOURCE_COLLECTION_RUN_PREVIEW_LIMIT}");
    expect(routeSource).toContain("/collection-assignments/${encodeURIComponent(payload.draft.assignmentId)}/outputs");
    expect(routeSource).toContain("/source-candidate");
    expect(routeSource).toContain("sourceCollectionRunsForTeam");
    expect(routeSource).toContain("SOURCE_COLLECTION_DEFAULT_ROLES");
    expect(routeSource).toContain("candidateType=candidate_graph");
    expect(routeSource).toContain("/workflow-orchestration/candidate-graph");
    expect(routeSource).toContain("buildCandidateGraphMutation");
    expect(routeSource).toContain('source: "team_workspace"');
    expect(routeSource).toContain("teamId: payload.teamId");
    expect(routeSource).toContain("startTeamRoundMutation");
    expect(routeSource).toContain("chatWorkspaceCache.afterTeamRoomMembershipChanged(variables.teamId, room.roomId)");
    expect(routeSource).toContain("chatWorkspaceCache.afterTeamRoomMembershipChanged(team.teamId, team.linkedChatRoom.roomId)");
    expect(routeSource).toContain("teamConversationStatusLabel");
    expect(routeSource).toContain("selectedTeam?.conversation");
    expect(routeSource).toContain("isAiSearchScopeTeam(selectedTeam)");
    expect(routeSource).toContain("showAiSearchScopePanel");
    expect(routeSource).toContain("renderAiSearchSourceScopePanel");
    expect(routeSource).toContain("selectedTeam?.sourceScope");
    expect(routeSource).toContain("AiSearchRunListPayload");
    expect(routeSource).toContain("queryKeys.teamAiSearchRuns");
    expect(routeSource).toContain("/api/teams/${encodeURIComponent(effectiveTeamId)}/ai-search-runs?limit=${AI_SEARCH_RUN_PREVIEW_LIMIT}");
    expect(routeSource).toContain("/api/teams/${encodeURIComponent(payload.teamId)}/ai-search-runs");
    expect(routeSource).toContain("startAiSearchRunMutation");
    expect(routeSource).toContain("aiSearchRunTopic");
    expect(routeSource).toContain("主题 -> 可信来源 -> 摘要/引用 -> 运行记录");
    expect(routeSource).toContain("结论需一手证据");
    expect(routeSource).toContain("默认启用");
    expect(routeSource).toContain("线索");
    expect(routeSource).toContain("白名单、去重、存储路径");
    expect(routeSource).toContain("启动一键搜索");
    expect(routeSource).toContain("最近搜索结果");
    expect(routeSource).toContain("latestAiSearchRun");
    expect(routeSource).toContain("/api/teams/${encodeURIComponent(nextCanvas.teamId)}/canvas");
    expect(routeSource).toContain("成员源");
    expect(routeSource).toContain("Member source");
    expect(routeSource).toContain("Agent Center");
    expect(routeSource).toContain("teamCanvasNodeAgentSourceRoute");
    expect(routeSource).toContain("writableTeamCanvas(nextCanvas)");
    expect(routeSource).toContain("delete writableNode.agentSourceRef");
    expect(routeSource).toContain("delete writableNode.agentProjectionEdit");
    expect(routeSource).toContain("delete writableNode.agentProjectionCanWrite");
    expect(routeSource).toContain("team_organization_canvas");
    expect(routeSource).not.toContain("/api/research/flow-canvas");
  });

  it("can deep-link from Agent references to a selected Team", () => {
    expect(routeSource).toContain("useSearchParams");
    expect(routeSource).toContain('searchParams.get("team")');
    expect(routeSource).toContain('searchParams.get("agent")');
    expect(routeSource).toContain('searchParams.get("researchView")');
    expect(routeSource).toContain("parseResearchWorkspaceView");
    expect(routeSource).toContain("requestedAgentTeamId");
    expect(routeSource).toContain("setSearchParams({ team: team.teamId })");
  });

  it("keeps only the fixed research and AI search teams in the picker", () => {
    expect(routeSource).toContain("EVOLUTION_SYSTEM_TEAM_IDS");
    expect(routeSource).toContain('"self-evolution-team"');
    expect(routeSource).toContain('"supervised-evolution-team"');
    expect(routeSource).toContain('const RESEARCH_TEAM_ID = "research-team"');
    expect(routeSource).toContain('const AI_SEARCH_TEAM_ID = "ai-search-team"');
    expect(routeSource).toContain("TEAM_PICKER_TEAM_IDS.map((teamId) => teamsById.get(teamId))");
    expect(routeSource).toContain("isEvolutionSystemTeam");
    expect(routeSource).toContain("team.teamKind === \"self_evolution\"");
    expect(routeSource).toContain("team.teamKind === \"supervised_evolution\"");
    expect(routeSource).toContain("team.teamSource === \"self_evolution\"");
    expect(routeSource).toContain("team.teamSource === \"supervised_evolution\"");
    expect(routeSource).toContain("const visibleTeamIds = useMemo(() => new Set(visibleTeams.map((team) => team.teamId)), [visibleTeams])");
    expect(routeSource).toContain("requestedVisibleTeamId");
    expect(routeSource).toContain("requestedVisibleAgentTeamId");
    expect(routeSource).toContain("selectedVisibleTeamId");
    expect(routeSource).toContain("fallbackVisibleTeamId");
    expect(routeSource).toContain("const hasTeams = visibleTeams.length > 0");
    expect(routeSource).toContain("visibleTeamSummary.activeTeamCount");
    expect(routeSource).toContain("visibleTeams.map((team) => (");
    expect(routeSource).toContain("visibleTeams.find((team) => team.teamId === event.target.value)");
    expect(routeSource).toContain("visibleTeams.find((team) => team.teamId === effectiveTeamId)");
    expect(routeSource).not.toContain("{teams.map((team) => (");
    expect(routeSource).not.toContain("teams[0]?.teamId");
  });

  it("renders a dense list canvas inspector workflow", () => {
    expect(routeSource).toContain("teamContextBar");
    expect(routeSource).toContain("teamSelectField");
    expect(routeSource).toContain("teamContextChips");
    expect(routeSource).toContain("selectedTeamContextTitle");
    expect(routeSource).toContain("成员源");
    expect(routeSource).toContain("Member source");
    expect(routeSource).not.toContain("teamPickerPanel");
    expect(routeSource).not.toContain("teamSwitcherBar");
    expect(routeSource).not.toContain("teamPickerLabel");
    expect(routeSource).not.toContain("teamPickerSummary");
    expect(routeSource).not.toContain("summaryBar");
    expect(routeSource).toContain("aria-label={lang === \"zh\" ? \"选择团队\" : \"Select team\"}");
    expect(routeSource).not.toContain("className={styles.teamPanel}");
    expect(routeSource).toContain("canvasPanel");
    expect(routeSource).toContain("inspector");
    expect(routeSource).toContain("hasTeams");
    expect(routeSource).toContain("styles.workspaceEmpty");
    expect(routeSource).toContain("styles.emptyCanvasPanel");
    expect(routeSource).toContain("选择团队后进入对应工作区");
    expect(routeSource).toContain("顶部只保留 AI 搜索范围团队和 挑战杯ai科研团队 两个入口");
    expect(routeSource).toContain("暂无可用团队。请确认 AI 搜索范围团队和 挑战杯ai科研团队 已初始化。");
    expect(routeSource).not.toContain("teamNameInputRef");
    expect(routeSource).not.toContain("从模板创建");
    expect(routeSource).not.toContain("创建 Demo 团队");
    expect(routeSource).not.toContain("selectedTemplate.chatRoom.mode");
    expect(routeSource).not.toContain("styles.templatePanel");
    expect(routeSource).not.toContain("styles.templatePicker");
    expect(routeSource).not.toContain("styles.templateSelect");
    expect(routeSource).not.toContain("styles.templatePreview");
    expect(routeSource).not.toContain("styles.templateCard");
    expect(routeSource).not.toContain("先填写团队名称，再创建团队。");
    expect(routeSource).not.toContain("styles.formError");
    expect(routeSource).not.toContain("styles.formHint");
    expect(routeSource).toContain("审核流程");
    expect(routeSource).toContain("styles.nodeBindingSection");
    expect(routeSource).toContain("styles.nodeBindingPlaceholder");
    expect(routeSource).toContain("styles.nodeSourceAuthority");
    expect(routeSource).toContain("Agent 身份只读投影");
    expect(routeSource).toContain("Read-only Agent identity");
    expect(routeSource).toContain("到 AgentDirectory 源配置修改");
    expect(routeSource).toContain("selectedNode.agentSourceRef?.owner");
    expect(routeSource).toContain("teamCanvasNodeAgentSourceRoute(selectedNode)");
    expect(routeSource).toContain("正在读取团队节点");
    expect(routeSource).toContain("agentTeamMembership");
    expect(routeSource).toContain("membership.teamId !== selectedTeam?.teamId");
    expect(routeSource).toContain("disabled={ownedByOtherTeam}");
    expect(routeSource).toContain("已属于");
    expect(routeSource).toContain("接入主干");
    expect(routeSource).toContain("保存节点");
    expect(routeSource).toContain("归档");
    expect(routeSource).toContain("function isSystemManagedTeam");
    expect(routeSource).toContain("systemManagedTeamArchiveReason");
    expect(routeSource).toContain("系统团队由工作流自动维护，不能在这里归档。");
    expect(routeSource).toContain("系统团队不可归档");
    expect(routeSource).toContain("解绑节点");
    expect(routeSource).toContain("删除节点");
    expect(routeSource).toContain("团队任务");
    expect(routeSource).toContain("启动团队讨论");
    expect(routeSource).toContain("teamTaskTopic");
    expect(routeSource).toContain("linkedRoomBusy");
    expect(routeSource).toContain("最近团队任务");
    expect(routeSource).toContain("styles.teamRoundPanel");
    expect(routeSource).toContain("styles.teamRoundCard");
    expect(routeSource).toContain("查看完整群聊");
    expect(routeSource).toContain("styles.teamTaskForm");
    expect(routeSource).toContain("科研流程");
    expect(routeSource).toContain("TeamWorkflowOrchestration");
    expect(routeSource).toContain("teamWorkflowQuery");
    expect(routeSource).toContain("teamWorkflowCandidatesQuery");
    expect(routeSource).toContain("teamWorkflowValidationSummary");
    expect(routeSource).toContain("teamWorkflowKnowledgeIngestionStatus");
    expect(routeSource).toContain("teamWorkflowOfficialModelEvidenceStatus");
    expect(routeSource).toContain("workflowStateLabel");
    expect(routeSource).toContain("workflowQualityTone");
    expect(routeSource).toContain("workflowIngestionStatusLabel");
    expect(routeSource).toContain("workflowIngestionTone");
    expect(routeSource).toContain("styles.workflowPanel");
    expect(routeSource).toContain("styles.workflowStats");
    expect(routeSource).toContain("styles.workflowIngestionPanel");
    expect(routeSource).toContain("styles.workflowIngestionStages");
    expect(routeSource).toContain("styles.workflowIngestionBoundary");
    expect(routeSource).toContain("styles.workflowGraphPanel");
    expect(routeSource).toContain("styles.workflowGraphFrame");
    expect(routeSource).toContain("styles.workflowGraphNode");
    expect(routeSource).toContain("styles.workflowGraphBoundary");
    expect(routeSource).toContain("styles.workflowCandidateList");
    expect(routeSource).toContain("styles.workflowValidation");
    expect(routeSource).toContain("RESEARCH_WORKSPACE_NAV_ITEMS");
    expect(routeSource).toContain("ResearchWorkspaceView");
    expect(routeSource).toContain("researchWorkspaceView");
    expect(routeSource).toContain("selectResearchWorkspaceView");
    expect(routeSource).toContain("selectTeamRecord");
    expect(routeSource).toContain("renderResearchStageLauncher");
    expect(routeSource).toContain("researchWorkspaceViewLabel");
    expect(routeSource).toContain("styles.workspaceResearch");
    expect(routeSource).toContain("styles.workspaceResearchCanvas");
    expect(routeSource).toContain("styles.researchInspector");
    expect(routeSource).toContain("styles.researchCanvasPanelHidden");
    expect(routeSource).toContain("styles.aiSearchScopePanel");
    expect(routeSource).toContain("styles.aiSearchSourceGroups");
    expect(routeSource).toContain("styles.aiSearchSourceItem");
    expect(routeSource).toContain('researchWorkspaceView !== "overview"');
    expect(routeSource).not.toContain("科研三阶段索引");
    expect(routeSource).not.toContain("团队专属阶段页");
    expect(routeSource).toContain("三阶段");
    expect(routeSource).toContain("ResearchStageWorkspaceView");
    expect(routeSource).toContain("researchWorkspaceStageRoute");
    expect(routeSource).toContain('view: "knowledge_collection"');
    expect(routeSource).toContain('view: "experiment"');
    expect(routeSource).toContain('view: "iteration"');
    expect(routeSource).not.toContain('view: "source_collection", zh: "资料搜集"');
    expect(routeSource).toContain("组织画布");
    expect(routeSource).toContain('canvas: { zh: "组织画布", en: "Canvas" }');
    expect(routeSource).toContain("搜索资料");
    expect(routeSource).toContain("科研控制台");
    expect(routeSource).toContain("开始知识搜集");
    expect(routeSource).toContain("搜索下一批");
    expect(routeSource).toContain("新一轮搜集");
    expect(routeSource).toContain("资料待审查");
    expect(routeSource).toContain("可进入实验");
    expect(routeSource).toContain("正在团队搜索");
    expect(routeSource).toContain("知识搜集操作台");
    expect(routeSource).toContain("sourceCollectionDecisionText");
    expect(routeSource).toContain("下一步");
    expect(routeSource).toContain("待执行");
    expect(routeSource).toContain("原始记录");
    expect(routeSource).toContain("原始资料");
    expect(routeSource).toContain("可点击来源");
    expect(routeSource).toContain("本地文件");
    expect(routeSource).toContain("缺少来源");
    expect(routeSource).toContain("SourceCollectionSourceFilter");
    expect(routeSource).toContain("SOURCE_COLLECTION_SOURCE_FILTERS");
    expect(routeSource).toContain("sourceCollectionSourceFilterLabel");
    expect(routeSource).toContain("sourceCollectionSourceFilter");
    expect(routeSource).toContain("sourceCollectionFilteredRecords");
    expect(routeSource).toContain("sourceCollectionFilteredRunCandidates");
    expect(routeSource).toContain("sourceCollectionFilterMatches");
    expect(routeSource).toContain("论文网页/DOI");
    expect(routeSource).toContain("PDF");
    expect(routeSource).toContain("sourceCollectionCandidateProvenance");
    expect(routeSource).toContain("sourceCollectionRecordProvenance");
    expect(routeSource).toContain("sourceCollectionRecordClickableSourceCount");
    expect(routeSource).toContain("sourceCollectionRecordLocalFileCount");
    expect(routeSource).toContain("sourceCollectionRecordMissingSourceCount");
    expect(routeSource).toContain("sourceCollectionRawRecordCount");
    expect(routeSource).toContain("sourceCollectionRunCandidateCount");
    expect(routeSource).toContain("sourceCollectionRunPendingScreeningCount");
    expect(routeSource).toContain("sourceCollectionPendingCandidateImportCount");
    expect(routeSource).toContain("/api/data-processing/runs/${encodeURIComponent(selectedSourceCollectionRunEffectiveId)}/records");
    expect(routeSource).toContain("还有 ${sourceCollectionPendingCandidateImportCount} 条原始记录尚未进入候选库");
    expect(routeSource).toContain('label: "DOI"');
    expect(routeSource).toContain("https://doi.org/");
    expect(routeSource).toContain("点击查看来源详情");
    expect(routeSource).toContain("sourceCollectionCandidateTrace");
    expect(routeSource).toContain("selectedSourceCollectionCandidateId");
    expect(routeSource).toContain("sourceCollectionSourceDetailPanel");
    expect(routeSource).toContain("打开论文 DOI");
    expect(routeSource).toContain("查看搜索证据");
    expect(routeSource).toContain("打开 API 原文");
    expect(routeSource).toContain("sourceCollectionIsMachineEvidenceUrl");
    expect(routeSource).toContain("仅有搜索记录，缺少可读来源");
    expect(routeSource).not.toContain("打开搜索页");
    expect(routeSource).toContain("本轮原始资料记录");
    expect(routeSource).toContain("当前过滤条件下没有原始资料记录");
    expect(routeSource).toContain("搜索问题");
    expect(routeSource).toContain("等待 Agent 审查");
    expect(routeSource).toContain("缓存");
    expect(routeSource).toContain("sourceCollectionScreeningButtonText");
    expect(routeSource).toContain("sourceCollectionScreeningDisabled");
    expect(routeSource).toContain("openSourceCollectionScreeningPanel");
    expect(routeSource).toContain("runSourceCollectionScreeningAction");
    expect(routeSource).toContain("assessSourceQualityBatchMutation");
    expect(routeSource).toContain("sourceCollectionQualityAgentId");
    expect(routeSource).toContain("source-quality/assess-batch");
    expect(routeSource).toContain("执行资料审查");
    expect(routeSource).toContain("Agent 审查中");
    expect(routeSource).toContain("sourceCollectionExpandedPanelId");
    expect(routeSource).toContain("sourceCollectionFocusedPanelId");
    expect(routeSource).toContain("sourceCollectionControlPanelRef");
    expect(routeSource).toContain("sourceCollectionPanelClassName");
    expect(routeSource).toContain("sourceCollectionStageCardKeyDown");
    expect(routeSource).toContain("container.scrollTo");
    expect(routeSource).toContain("HTMLDetailsElement");
    expect(routeSource).toContain("暂无候选");
    expect(routeSource).toContain("source-collection-screening-panel");
    expect(routeSource).toContain("sourceCollectionScreeningListShell");
    expect(routeSource).toContain("sourceCollectionScreeningScrollHint");
    expect(routeSource).toContain("资料审查候选列表，可向下滚动查看更多");
    expect(routeSource).toContain("向下滚动查看更多本页候选");
    expect(routeSource).toContain("source-collection-candidates-panel");
    expect(routeSource).toContain("source-collection-graph-panel");
    expect(routeSource).toContain("source-collection-memory-panel");
    expect(routeSource).not.toContain("researchView=candidates");
    expect(routeSource).toContain("查看提炼结果");
    expect(routeSource).toContain("openSourceCollectionCandidatePanel");
    expect(routeSource).toContain("renderSourceCollectionCandidatePanel");
    expect(routeSource).not.toContain("sourceCollectionRunCandidates.slice(0, 6)");
    expect(routeSource).not.toContain("sourceCollectionRunCandidates.slice(0, 12)");
    expect(routeSource).not.toContain("SOURCE_COLLECTION_RESULT_PREVIEW_LIMIT");
    expect(routeSource).toContain("sourceCollectionStageCard");
    expect(routeSource).toContain("detailLabel");
    expect(routeSource).toContain("module.onDetail()");
    expect(routeSource).toContain("sourceCollectionStagePrimaryAction");
    expect(routeSource).toContain("sourceCollectionStageSecondaryAction");
    expect(routeSource).not.toContain("sourceCollectionStageActionRow");
    expect(routeSource).not.toContain("module.onAgentChat");
    expect(routeSource).toContain("SourceCollectionStepState");
    expect(routeSource).toContain("SourceCollectionStageModuleId");
    expect(routeSource).toContain("SourceCollectionStageCardProjection");
    expect(routeSource).toContain("sourceCollectionStageCards");
    expect(routeSource).toContain("sourceCollectionStageCardSummary");
    expect(routeSource).toContain("sourceCollectionStageCardById");
    expect(routeSource).toContain("sourceCollectionDisplayedCandidateCount");
    expect(routeSource).toContain("sourceCollectionPrimaryDataLoading");
    expect(routeSource).toContain("sourceCollectionSourceQualityLoading");
    expect(routeSource).toContain("sourceCollectionScreeningDataLoading");
    expect(routeSource).toContain("sourceCollectionLoadingText");
    expect(routeSource).toContain("sourceCollectionLoadingSummary");
    expect(routeSource).toContain("sourceCollectionDisplayedCandidateFilterCounts");
    expect(routeSource).toContain("sourceCollectionCandidateProjectionFallbackCount");
    expect(routeSource).toContain("candidateListAwaitingRefresh");
    expect(routeSource).toContain("正在加载资料提炼结果");
    expect(routeSource).toContain("正在读取资料提炼结果");
    expect(routeSource).toContain("列表正在同步");
    expect(routeSource).toContain("sourceCollectionStageProjectionState");
    expect(routeSource).toContain("agent_done_artifact_pending");
    expect(routeSource).toContain("latestTask");
    expect(routeSource).toContain("blockingReasons");
    expect(routeSource).toContain("sourceCollectionStageBlockingReasonLabel");
    expect(routeSource).toContain("sourceCollectionStageBlockingReasonsLabel");
    expect(routeSource).toContain("sourceCollectionStageArtifactSummaryLabel");
    expect(routeSource).toContain("待 Agent 产出");
    expect(routeSource).toContain("已有输入，等待该阶段生成目标产物。");
    expect(routeSource).toContain("证据 ${evidenceCount}");
    expect(routeSource).not.toContain("candidateProjection.blockingReasons.join");
    expect(routeSource).not.toContain("{module.projection.blockingReasons[0]}</small>");
    expect(routeSource).toContain("evidenceRefCount");
    expect(routeSource).toContain("materializedSources");
    expect(routeSource).toContain("graphForSelectedSourceRun");
    expect(routeSource).toContain("parseSourceCollectionStageModuleId");
    expect(routeSource).toContain("collectionStage");
    expect(routeSource).toContain("selectedSourceCollectionStageId");
    expect(routeSource).toContain("selectSourceCollectionStage");
    expect(routeSource).toContain("renderSourceCollectionActiveStagePanel");
    expect(routeSource).toContain("researchStageAgentDirectChatRoute");
    expect(routeSource).toContain("sourceCollectionStageReturnRoute");
    expect(routeSource).toContain("sourceCollectionStageChatReturnLabel");
    expect(routeSource).toContain("params.set(\"returnTo\", normalizedReturnTo)");
    expect(routeSource).toContain("params.set(\"returnLabel\", normalizedReturnLabel)");
    expect(routeSource).toContain("openSourceCollectionStageAgentChat");
    expect(routeSource).toContain('type SourceCollectionStageAgentChatStatus = "ready" | "loading" | "error" | "repair"');
    expect(routeSource).toContain("sourceCollectionStageAgentChatState(stageId");
    expect(routeSource).toContain("workspaceQuery.isPending || workspaceQuery.isFetching");
    expect(routeSource).toContain("primaryStageAgentChatLoading");
    expect(routeSource).toContain("加载 Agent...");
    expect(routeSource).toContain('chatState.status === "repair"');
    expect(routeSource).toContain("onAction: () => void startSourceCollectionStageSessionTask(\"collection\")");
    expect(routeSource).toContain("onAction: () => void startSourceCollectionStageSessionTask(\"candidate\")");
    expect(routeSource).toContain("onAction: () => void startSourceCollectionStageSessionTask(\"screening\")");
    expect(routeSource).toContain("onAction: () => void startSourceCollectionStageSessionTask(\"graph\")");
    expect(routeSource).toContain("onAction: () => void startSourceCollectionStageSessionTask(\"memory\")");
    expect(routeSource).toContain("repairChallengeCupTeamAgentsMutation");
    expect(routeSource).toContain("/challenge-cup-agents/repair");
    expect(routeSource).toContain("修复团队 Agent");
    expect(routeSource).toContain("进入 Agent 私聊");
    expect(routeSource).toContain("Agent 私聊");
    expect(routeSource).not.toContain("window.alert(lang === \"zh\"");
    expect(routeSource).not.toContain("sourceCollectionStageChatRoute");
    expect(routeSource).not.toContain("sourceCollectionStageRoomKey");
    expect(routeSource).not.toContain("createSourceCollectionStageChatRoomMutation");
    expect(routeSource).not.toContain("sourceCollectionStageViewMode");
    expect(routeSource).not.toContain("SourceCollectionStageViewMode");
    expect(routeSource).toContain("sourceCollectionPageItems");
    expect(routeSource).toContain("renderSourceCollectionPagination");
    expect(routeSource).toContain("stopSourceCollectionPaginationEvent");
    expect(routeSource).toContain("preventSourceCollectionPanelSummaryToggle");
    expect(routeSource).toContain("onMouseDown={stopSourceCollectionPaginationEvent}");
    expect(routeSource).toContain("onClick={preventSourceCollectionPanelSummaryToggle}");
    expect(routeSource).not.toContain("sourceCollectionTraceMessagesForStage");
    expect(routeSource).not.toContain("renderSourceCollectionStageProcessPanel");
    expect(routeSource).toContain("sourceCollectionStageCardSelected");
    expect(routeSource).not.toContain("sourceCollectionStageOperationPanel");
    expect(routeSource).toContain("aria-pressed");
    expect(routeSource).toContain("<small>{module.summary}</small>");
    expect(routeSource).toContain("styles.sourceCollectionStageProjection");
    expect(routeSource).toContain("styles.sourceCollectionStageTaskSummary");
    const graphStateExpression = routeSource.slice(
      routeSource.indexOf("const sourceCollectionGraphStepState"),
      routeSource.indexOf("const sourceCollectionMemoryStepState"),
    );
    const memoryStateExpression = routeSource.slice(
      routeSource.indexOf("const sourceCollectionMemoryStepState"),
      routeSource.indexOf("const sourceCollectionCollectionActionLabel"),
    );
    expect(graphStateExpression).not.toContain("teamWorkflowCandidateGraphQuery.isFetching");
    expect(memoryStateExpression).not.toContain("teamWorkflowKnowledgeIngestionStatusQuery.isFetching");
    expect(routeSource).not.toContain("className={styles.sourceCollectionStageMiniFlow}");
    expect(routeSource).toContain("sourceCollectionStageHandoffNext");
    expect(routeSource).not.toContain("Agent过程");
    expect(routeSource).toContain("activeModule.nextLabel");
    expect(routeSource).toContain("activeModule.onAction");
    expect(routeSource).toContain("sourceCollectionStagePrimaryAgentBinding(activeModule.id)");
    expect(routeSource).toContain("配置 Agent");
    expect(routeSource).toContain("绑定 Agent");
    expect(routeSource).toContain("sourceCollectionStageModules.map");
    expect(routeSource).toContain("sourceCollectionStepClassName");
    expect(routeSource).not.toContain("下一步操作");
    expect(routeSource).toContain("步骤侧栏");
    expect(routeSource).toContain("输入");
    expect(routeSource).toContain("输出");
    expect(routeSource).toContain("styles.researchStageCardHead");
    expect(routeSource).toContain("styles.researchStageCardMetrics");
    expect(routeSource).toContain("RESEARCH_STAGE_AGENT_ROLES");
    expect(routeSource).toContain("researchStageAgentBindingsByStage");
    expect(routeSource).toContain("renderResearchStageAgentSummary(stageType)");
    expect(routeSource).toContain("renderResearchStageAgentPanel(stageType)");
    expect(routeSource).not.toContain('renderResearchStageAgentPanel("knowledge_collection", "compact")');
    expect(routeSource).toContain("SOURCE_COLLECTION_STAGE_AGENT_KEYS");
    expect(routeSource).toContain("sourceCollectionStageAgentBindings(stageId)");
    expect(routeSource).not.toContain("renderSourceCollectionStageAgentStrip");
    expect(routeSource).toContain('event.target.closest("button, a")');
    expect(routeSource).toContain("renderSourceCollectionStageAgents(activeModule.id)");
    expect(routeSource).toContain("当前步骤 Agent 配置");
    expect(routeSource).toContain("sourceCollectionStageAgentCardBody");
    expect(routeSource).toContain("sourceCollectionStageAgentCardActions");
    expect(routeSource).toContain("sourceCollectionStageAgentPanel");
    expect(routeSource).not.toContain("sourceCollectionStageAgentStrip");
    expect(routeSource).not.toContain("sourceCollectionStageAgentChips");
    expect(routeSource).not.toContain("sourceCollectionStageAgentChip");
    expect(routeSource).toContain("researchStageAgentManagementRoute(binding.agentId)");
    expect(routeSource).not.toContain("const chatRoute = researchStageAgentDirectChatRoute");
    expect(routeSource).toContain("Agent 管理");
    expect(routeSource).toContain("还需补充资料");
    expect(routeSource).toContain("sourceCollectionSearchOpenAssignmentCount");
    expect(routeSource).toContain("sourceCollectionDownstreamOpenAssignmentCount");
    expect(routeSource).toContain("SOURCE_COLLECTION_SEARCH_EXECUTION_ROLES");
    expect(routeSource).toContain("个搜索任务待执行");
    expect(routeSource).toContain("搜索已停止，还有");
    expect(routeSource).not.toContain("sourceCollectionOpenAssignmentCount > 0 ? <Search");
    expect(routeSource).toContain("条已通过");
    expect(routeSource).toContain("Agent 重新审查");
    expect(routeSource).toContain("sourceCollectionKnowledgeStewardAgentId");
    expect(routeSource).toContain("runKnowledgeIngestionPrecheckMutation");
    expect(routeSource).toContain("knowledge-ingestion/precheck");
    expect(routeSource).toContain("runSourceCollectionGraphAction");
    expect(routeSource).toContain("runSourceCollectionMemoryPrecheckAction");
    expect(routeSource).toContain("agent_approved_only");
    expect(routeSource).toContain("Agent 生成关系图");
    expect(routeSource).toContain("通知知识库 Agent");
    expect(routeSource).toContain("提炼并通知 Agent");
    expect(routeSource).toContain("资料已写入团队知识库");
    expect(routeSource).toContain("sourceCollectionPrecheckCandidateCount");
    expect(routeSource).toContain("sourceCollectionIngestCandidateCount");
    expect(routeSource).toContain("sourceCollectionCanBuildGraph");
    expect(routeSource).toContain("sourceCollectionGraphActionDisabled");
    expect(routeSource).toContain("审查并生成关系图");
    expect(routeSource).toContain("sourceCollectionMemoryActionDisabled");
    expect(routeSource).toContain("sourceCollectionMemoryActionLabel");
    expect(routeSource).toContain("maxCandidates: Math.max(1, Math.min(80, sourceCollectionIngestCandidateCount))");
    expect(routeSource).toContain("forceReview: sourceCollectionPrecheckCandidateCount <= 0 && sourceCollectionDisplayedCandidateCount > 0");
    expect(routeSource).toContain("forceReview: sourceCollectionRunApprovedCount <= 0 && sourceCollectionDisplayedCandidateCount > 0");
    expect(routeSource).toContain("可先审查再通知 Agent");
    expect(routeSource).toContain("条候选资料");
    expect(routeSource).not.toContain("onAction: refreshSourceCollectionGraph");
    expect(routeSource).not.toContain("onAction: refreshSourceCollectionMemoryPrecheck");
    expect(routeSource).toContain("forceRescreen");
    expect(routeSource).toContain("force: forceRescreen");
    expect(routeSource).toContain("sourceCollectionPanelActions");
    expect(routeSource).toContain("Source Quality Assessment Agent re-screened already assessed source_manifest candidates");
    expect(routeSource).toContain("通知知识库 Agent");
    expect(routeSource).not.toContain("待继续搜索");
    expect(routeSource).toContain("/storage/open");
    expect(routeSource).toContain("本轮产物");
    expect(routeSource).toContain("打开批次目录");
    expect(routeSource).toContain("更多证据文件");
    expect(routeSource).toContain("sourceCollectionStorageTargetForRef");
    expect(routeSource).toContain("sourceCollectionStatusLabel");
    expect(routeSource).toContain("sourceCollectionAgentRoleLabel");
    expect(routeSource).not.toContain("currentTraceMessage");
    expect(routeSource).toContain("结果");
    expect(routeSource).not.toContain("Agent 执行过程");
    expect(routeSource).not.toContain("过程</button>");
    expect(routeSource).toContain("sourceCollectionResultsPanel");
    expect(routeSource).toContain("source-collection-results");
    expect(routeSource).toContain("sourceCollectionResultList");
    expect(routeSource).toContain("sourceCollectionResultStatus");
    expect(routeSource).toContain("resultStatusLabel");
    expect(routeSource).toContain("当前过滤条件下没有候选资料");
    expect(routeSource).toContain("当前过滤条件下没有入库关系节点");
    expect(routeSource).toContain("当前过滤条件下没有入库资料");
    expect(routeSource).toContain("sourceCollectionCandidateQualityState(candidate).approved");
    expect(routeSource).toContain("source_needs_quality_revision: \"需补资料\"");
    expect(routeSource).toContain("source_screened: \"已审查\"");
    expect(routeSource).toContain("sourceCollectionCandidateListShell");
    expect(routeSource).toContain("待 Agent 审查");
    expect(routeSource).not.toContain("待质检");
    expect(routeSource).not.toContain("workflowSourceCollectionPrimaryButton");
    expect(routeSource).toContain("启动实验规划");
    expect(routeSource).toContain("启动迭代");
    expect(routeSource).not.toContain("{researchWorkflowTeamSelected ? renderResearchWorkspaceNav() : null}");
    expect(routeSource).toContain("onChange={(event) => {");
    expect(routeSource).toContain("selectTeamRecord(nextTeam)");
    expect(routeSource).toContain("setResearchWorkspaceView(\"overview\")");
    expect(routeSource).not.toContain("{renderResearchWorkspaceNav()}");
    expect(routeSource).toContain("{renderResearchStageLauncher()}");
    expect(routeSource).toContain("researchWorkflowTeamSelected && !researchCanvasVisible");
    expect(routeSource).toContain("结构索引");
    expect(routeSource).toContain("只读查看科研团队节点关系");
    expect(routeSource).toContain("查看关系图");
    expect(routeSource).toContain("researchCanvasRoute(selectedTeam?.teamId || RESEARCH_TEAM_ID)");
    expect(routeSource).toContain("搜索、提炼、审查与入库");
    expect(routeSource).toContain("搜索资料 / 资料提炼 / 资料审查 / 资料入库");
    expect(routeSource).toContain("实验规划 / Baseline / 指标 / 结果记录");
    expect(routeSource).toContain("复盘 / 版本化 / 改进计划 / 交付门禁");
    expect(routeSource).toContain("value === \"source_collection\"");
    expect(routeSource).toContain("return \"knowledge_collection\"");
    expect(routeSource).toContain('id="research-workflow-overview"');
    expect(routeSource).toContain('knowledge_collection: "research-workflow-knowledge-collection"');
    expect(routeSource).toContain('id="research-workflow-source-collection"');
    expect(routeSource).toContain('id="research-organization-canvas"');
    expect(routeSource).toContain('researchWorkspaceView === "canvas"');
    expect(routeSource).toContain('const researchCanvasReadOnly = researchWorkflowTeamSelected && researchWorkspaceView === "canvas"');
    expect(routeSource).toContain("const researchCanvasVisible = researchCanvasReadOnly");
    expect(routeSource).toContain("showNodeBindingPanel = !researchWorkflowTeamSelected || (researchCanvasVisible && !researchCanvasReadOnly)");
    expect(routeSource).toContain("renderResearchCanvasReadOnlyPanel");
    expect(routeSource).toContain("researchCanvasReadOnly ? renderResearchCanvasReadOnlyPanel() : null");
    expect(routeSource).toContain("只读组织画布");
    expect(routeSource).toContain("不会同步群聊或修改节点");
    expect(routeSource).toContain('useState<ResearchCanvasLayoutMode>("auto")');
    expect(routeSource).toContain("autoLayoutResearchCanvasNodes(canvasNodes, organizationEdges)");
    expect(routeSource).toContain("const researchCanvasAutoLayoutActive = researchCanvasReadOnly && researchCanvasLayoutMode === \"auto\"");
    expect(routeSource).toContain("const displayCanvasNodes = researchCanvasAutoLayoutActive ? autoLayoutCanvasNodes : canvasNodes");
    expect(routeSource).toContain("自动排版只改变当前显示，不保存坐标");
    expect(routeSource).toContain("原始坐标");
    expect(routeSource).toContain("canvasLayoutModeSwitch");
    expect(routeSource).toContain("RESEARCH_CANVAS_AUTO_LAYOUT_LAYER_GAP");
    expect(routeSource).toContain("RESEARCH_CANVAS_AUTO_LAYOUT_ROW_GAP");
    expect(routeSource).toContain("researchCanvasRoleLayer");
    expect(routeSource).toContain("返回三阶段");
    expect(routeSource).toContain("researchCanvasReadOnly ? undefined : (event) => startNodeDrag(event, node)");
    expect(routeSource).toContain("researchCanvasReadOnly ? undefined : moveNodeDrag");
    expect(routeSource).toContain("researchCanvasReadOnly ? undefined : finishNodeDrag");
    expect(routeSource).toContain("researchCanvasReadOnly ? styles.nodeReadOnly : \"\"");
    expect(routeSource).toContain("styles.canvasReadOnlyPanel");
    expect(routeSource).toContain("styles.canvasReadOnlyBadge");
    expect(routeSource).toContain("styles.canvasLayoutModeSwitch");
    expect(routeSource).toContain("showNodeBindingPanel");
    expect(routeSource).toContain("showWorkflowPanel");
    expect(routeSource).toContain("showResearchSourceCollection");
    expect(routeSource).toContain("sourceCollectionAgentIdsFromCanvas");
    expect(routeSource).toContain("researchSourceCollectionRoute");
    expect(routeSource).toContain("teamWorkspaceRoute");
    expect(routeSource).toContain("researchCanvasRoute");
    expect(routeSource).toContain("teamChatRoomRoute");
    expect(routeSource).toContain("返回团队页面");
    expect(routeSource).toContain("返回知识搜集");
    expect(routeSource).toContain("返回阶段页");
    expect(routeSource).toContain("renderSourceCollectionConversation");
    expect(routeSource).toContain("renderSourceCollectionControlsPanel");
    expect(routeSource).toContain("知识搜集工作台");
    expect(routeSource).toContain("researchStageAgentDirectChatRoute");
    expect(routeSource).toContain("openSourceCollectionStageAgentChat");
    expect(routeSource).not.toContain("sourceCollectionStageChatRoute");
    expect(routeSource).not.toContain("SOURCE_COLLECTION_STAGE_CHAT_PURPOSE");
    expect(routeSource).not.toContain("sourceCollectionTraceMessages");
    expect(routeSource).not.toContain("KV 缓存门禁已写入本轮搜集");
    expect(routeSource).not.toContain("执行模型：见当前步骤 Agent 配置");
    expect(routeSource).toContain("sourceCollectionPromptCacheModelDisplay");
    expect(routeSource).not.toContain("本轮使用 ${sourceCollectionPromptCachePolicy?.modelName");
    expect(routeSource).toContain("promptCachePolicy: SOURCE_COLLECTION_PROMPT_CACHE_POLICY");
    expect(routeSource).toContain('SOURCE_COLLECTION_PROMPT_CACHE_MODEL_LABEL = "configured prompt-cache model"');
    expect(routeSource).not.toContain('modelId: "houmo_qwen35_9b_agent"');
    expect(routeSource).toContain("|| selectedTeamStartResearchStageError");
    expect(routeSource).toContain("continuedSourceRunRef");
    expect(routeSource).toContain("sourceCollectionSearchExecution");
    expect(routeSource).toContain("selectedTeamInitialSourceCollectionSearchResult");
    expect(routeSource).toContain("selectedSourceCollectionSearchExecutionResult");
    const sourceCollectionBackgroundRefreshSource = routeSource.slice(
      routeSource.indexOf("const selectedSourceCollectionActiveWorkRun"),
      routeSource.indexOf("const sourceCollectionAcceptedBackgroundActive"),
    );
    expect(sourceCollectionBackgroundRefreshSource).toContain("researchStageRoundStatusQueryKey(selectedTeam.teamId)");
    expect(routeSource).toContain("sourceCollectionStageWritebackRefetchInterval");
    expect(routeSource).toContain("refetchInterval: (query) =>");
    expect(routeSource).toContain("query.state.data as ResearchStageRoundStatusPayload | null | undefined");
    expect(routeSource).toContain("sourceCollectionStageWritebackSyncActive,");
    expect(routeSource).toContain("sourceCollectionStageWritebackRefetchInterval(pageVisible, researchStageRoundStatusQuery.data, sourceCollectionStageWritebackSyncActive)");
    expect(routeSource).toContain("refetchInterval: () => sourceCollectionStageWritebackRefetchInterval(pageVisible, researchStageRoundStatusQuery.data, sourceCollectionStageWritebackSyncActive)");
    const sourceQualityStatusQuerySource = routeSource.slice(
      routeSource.indexOf("const teamWorkflowSourceQualityStatusQuery"),
      routeSource.indexOf("const teamWorkflowPaperNoteChunkStatusQuery"),
    );
    expect(sourceQualityStatusQuerySource).toContain("refetchInterval");
    expect(sourceQualityStatusQuerySource).toContain("teamWorkflowSourceQualityEnabled");
    expect(sourceQualityStatusQuerySource).toContain("sourceCollectionStageWritebackSyncActive");
    expect(routeSource).toContain("teamWorkflowSourceQualityEnabled");
    expect(routeSource).toContain("enabled: Boolean(effectiveTeamId && researchWorkflowTeamSelected)");
    expect(routeSource).not.toContain("researchStageRoundStatusQueryKey(effectiveTeamId || \"none\"),\n    queryFn: () =>\n      fetchJson<ResearchStageRoundStatusPayload>(\n        `/api/teams/${encodeURIComponent(effectiveTeamId)}/workflow-orchestration/stage-rounds/status`,\n      ),\n    enabled: Boolean(effectiveTeamId && researchWorkflowTeamSelected && teamWorkflowQuery.data)");
    expect(routeSource).not.toContain("queryKeys.teamWorkflowCandidates(effectiveTeamId || \"none\", TEAM_WORKFLOW_CANDIDATE_PREVIEW_LIMIT),\n    queryFn: () =>\n      fetchJson<TeamWorkflowCandidateListPayload>(\n        `/api/teams/${encodeURIComponent(effectiveTeamId)}/workflow-orchestration/candidates?limit=${TEAM_WORKFLOW_CANDIDATE_PREVIEW_LIMIT}`,\n      ),\n    enabled: Boolean(effectiveTeamId && researchWorkflowTeamSelected && teamWorkflowQuery.data)");
    const sourceCollectionStageReturnRefreshSource = routeSource.slice(
      routeSource.indexOf("if (!researchWorkflowTeamSelected || !pageVisible"),
      routeSource.indexOf("if (!selectedTeam?.teamId || !selectedSourceCollectionRunEffectiveId || !selectedSourceCollectionSearchAccepted"),
    );
    expect(sourceCollectionStageReturnRefreshSource).toContain("requestedSourceCollectionStage");
    expect(sourceCollectionStageReturnRefreshSource).toContain("researchStageRoundStatusQueryKey(selectedTeam.teamId)");
    expect(sourceCollectionStageReturnRefreshSource).toContain("queryKeys.teamWorkflowCandidates(selectedTeam.teamId");
    expect(sourceCollectionStageReturnRefreshSource).toContain("sourceCollectionRunRecordsQueryKey(selectedSourceCollectionRunEffectiveId)");
    expect(routeSource).toContain("skippedDuplicateCount");
    expect(routeSource).toContain("条重复跳过");
    expect(routeSource).toContain("selectedSourceCollectionSearchAccepted");
    expect(routeSource).not.toContain('collection: ["research_coordination", "data_discovery", "source_acquisition", "content_extraction"]');
    expect(routeSource).toContain('collection: ["data_discovery", "source_acquisition"]');
    expect(routeSource).toContain('candidate: ["content_extraction"]');
    expect(routeSource).not.toContain('graph: ["source_quality"]');
    expect(routeSource).toContain('graph: ["candidate_graph"]');
    expect(routeSource).toContain('return "graph";');
    expect(routeSource).toContain('SOURCE_COLLECTION_TEAM_AGENT_ROLES');
    expect(routeSource).toContain('key: "candidate_graph"');
    expect(routeSource).toContain("const sourceCollectionGraphAgentId");
    expect(routeSource).toContain("createdByAgent: sourceCollectionGraphAgentId");
    expect(routeSource).not.toContain("createdByAgent: sourceCollectionQualityAgentId");
    expect(routeSource).not.toContain("sourceCollectionStageRoomKey");
    expect(routeSource).toContain("openSourceCollectionStageAgentChat");
    expect(routeSource).toContain("repairChallengeCupTeamAgentsMutation.mutate(selectedTeam.teamId)");
    expect(routeSource).toContain("进入 Agent 私聊");
    expect(routeSource).toContain("researchStageStartFeedbackText");
    expect(routeSource).toContain("已复用正在运行的");
    expect(routeSource).not.toContain("像对话一样记录：搜索了什么");
    expect(routeSource).not.toContain("搜集批次已启动，等待功能 Agent 回写");
    expect(routeSource).not.toContain("后续接入全文下载或提炼器时");
    expect(routeSource).not.toContain("通常无需修改");
    expect(routeSource).not.toContain("一键生成搜索计划、团队分工");
    expect(routeSource).not.toContain("搜索计划、步骤记录、资料记录和候选镜像都已落盘");
    expect(routeSource).toContain("返回团队页面");
    expect(routeSource).toContain("实验规划工作台");
    expect(routeSource).toContain("experimentPlanningStatusQueryKey");
    expect(routeSource).toContain("renderExperimentPlanningLedgerPanel");
    expect(routeSource).toContain("实验计划账本");
    expect(routeSource).toContain("生成计划草稿");
    expect(routeSource).toContain("baseline-artifact");
    expect(routeSource).toContain("登记基线工件");
    expect(routeSource).toContain("reproductionCommand");
    expect(routeSource).toContain("smoke-result");
    expect(routeSource).toContain("ExperimentSmokeResultRecord");
    expect(routeSource).toContain("activeSmokeResult");
    expect(routeSource).toContain("gateDecision");
    expect(routeSource).toContain("登记 smoke 结果");
    expect(routeSource).toContain("needs_review");
    expect(routeSource).toContain("full-run 已解锁");
    expect(routeSource).toContain("readyForSmoke");
    expect(routeSource).toContain("baselineSelection");
    expect(routeSource).toContain("readyForFullRun");
    expect(routeSource).toContain("No training execution was triggered.");
    expect(routeSource).toContain("迭代优化工作台");
    expect(routeSource).toContain("renderResearchStageStandalonePage");
    expect(routeSource).toContain("不自动进入下一阶段。");
    expect(routeSource).toContain("Source Quality Assessment Agent");
    expect(routeSource).toContain("资料入库状态");
    expect(routeSource).toContain("模型调用证据链");
    expect(routeSource).toContain("证据登记，不是正式知识");
    expect(routeSource).toContain("CandidateStore、Team Knowledge 和正式同步边界");
    expect(routeSource).toContain("资料搜索执行");
    expect(routeSource).toContain("启动搜集批次");
    expect(routeSource).toContain("手工回写一条搜集结果");
    expect(routeSource).toContain("回写并导入候选");
    expect(routeSource).toContain("原始位置");
    expect(routeSource).toContain("不触发外部搜索，不写正式知识/RAG/图谱");
    expect(routeSource).toContain("正式知识写入关闭");
    expect(routeSource).toContain("入库关系图");
    expect(routeSource).toContain("Agent 生成关系图");
    expect(routeSource).toContain("CandidateStore 快照 · 正式知识/RAG/图谱写入关闭");
    expect(routeSource).toContain("paper_note 分块计划");
    expect(routeSource).toContain("资料质量筛选");
    expect(routeSource).toContain("通过筛选");
    expect(routeSource).toContain("退回补资料");
    expect(routeSource).toContain("Source Quality Assessment Agent");
    expect(routeSource).toContain("workflowCandidateListPanel");
    expect(routeSource).toContain("workflowCandidateListScroll");
    expect(routeSource).toContain("候选仓库预览");
    expect(routeSource).toContain("查看完整候选库");
    expect(routeSource).toContain("向下滚动查看更多候选，或打开完整候选库分页处理");
    expect(routeSource).toContain("生成分块计划");
    expect(routeSource).toContain("重建分块计划");
    expect(routeSource).toContain("后续 paper_note draft 需带 chunkId");
    expect(routeSource).toContain("选择 research-team / 挑战杯ai科研团队 后显示挑战杯科研流程。");
    expect(routeSource).toContain("团队广播");
    expect(routeSource).toContain("发送给团队");
    expect(routeSource).toContain("最近团队广播");
    expect(routeSource).toContain("已衔接群聊");
    expect(routeSource).toContain("teamChatRoomRoute(selectedTeamStartRoundResult.roomId");
    expect(routeSource).toContain("teamChatRoomRoute(latestTeamRound.roomId");
    expect(routeSource).toContain("teamWorkspaceRoute(selectedTeam?.teamId || RESEARCH_TEAM_ID)");
    expect(routeSource).toContain("styles.linkedRoomLine");
    expect(routeSource).toContain("styles.toolbarLink");
    expect(routeSource).toContain("teamBusEvents");
    expect(routeSource).toContain("isProjectAgentBusEventRevoked");
    expect(routeSource).toContain("projectAgentBusEventsForTeam");
    expect(routeSource).toContain("revokeTeamMessageMutation");
    expect(routeSource).toContain("selectedTeamMessageResult.kernel?.taskId");
    expect(routeSource).toContain("event.kernel?.taskId");
    expect(routeSource).toContain("styles.teamHistoryPanel");
    expect(routeStyles.kernelTraceLink).toBeTypeOf("string");
    expect(routeSource).toContain("interrupt_targets");
    expect(routeSource).toContain("edges: canvas.edges.filter((edge) => edge.source !== deletedNodeId && edge.target !== deletedNodeId)");
    expect(routeStyles.teamContextBar).toBeTypeOf("string");
    expect(routeStyles.teamTitleBlock).toBeTypeOf("string");
    expect(routeStyles.teamSelectField).toBeTypeOf("string");
    expect(routeStyles.teamContextChips).toBeTypeOf("string");
    expect(routeStyles.teamContextActions).toBeTypeOf("string");
    expect(routeStylesSource).not.toContain(".summaryBar");
    expect(routeStylesSource).not.toContain(".teamPickerPanel");
    expect(routeStylesSource).not.toContain(".teamPickerSummary");
    expect(routeStyles.nodeBindingSection).toBeTypeOf("string");
    expect(routeStyles.nodeBindingPlaceholder).toBeTypeOf("string");
    expect(routeStyles.nodeSourceAuthority).toBeTypeOf("string");
    expect(routeStyles.workflowPanel).toBeTypeOf("string");
    expect(routeStyles.workflowStats).toBeTypeOf("string");
    expect(routeStyles.workflowIngestionPanel).toBeTypeOf("string");
    expect(routeStyles.workflowIngestionStages).toBeTypeOf("string");
    expect(routeStyles.workflowIngestionBoundary).toBeTypeOf("string");
    expect(routeStyles.workflowSourceQualityPanel).toBeTypeOf("string");
    expect(routeStyles.workflowSourceQualityStats).toBeTypeOf("string");
    expect(routeStyles.workflowSourceQualityQueue).toBeTypeOf("string");
    expect(routeStyles.workflowPaperNoteChunkPanel).toBeTypeOf("string");
    expect(routeStyles.workflowPaperNoteChunkStats).toBeTypeOf("string");
    expect(routeStyles.workflowSourceCollectionStorageActions).toBeTypeOf("string");
    expect(routeStyles.workflowSourceCollectionStorageButtons).toBeTypeOf("string");
    expect(routeStyles.workflowPaperNoteChunkPlans).toBeTypeOf("string");
    expect(routeStyles.workflowModelEvidencePanel).toBeTypeOf("string");
    expect(routeStyles.workflowModelEvidenceStats).toBeTypeOf("string");
    expect(routeStyles.workflowModelEvidenceCoverage).toBeTypeOf("string");
    expect(routeStyles.workflowSourceCollectionPanel).toBeTypeOf("string");
    expect(routeStyles.workflowSourceCollectionForm).toBeTypeOf("string");
    expect(routeStyles.workflowSourceCollectionRuns).toBeTypeOf("string");
    expect(routeStyles.workflowSourceCollectionAssignments).toBeTypeOf("string");
    expect(routeStyles.workflowSourceCollectionOutputForm).toBeTypeOf("string");
    expect(routeStyles.workflowSuccess).toBeTypeOf("string");
    expect(routeStyles.workflowError).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionPage).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionPageGrid).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionRunBadge).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionConversationPanel).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionTraceMessage).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionTrace_cache).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionTraceStorage).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionResultsPanel).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionResultsHeader).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionFilterBar).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionFilterActive).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionResultStats).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionResultList).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionCandidateListShell).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionResultItem).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionResultContent).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionResultWarning).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionResultMeta).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionResultSource).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionResultSourceMissing).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionResultStatus).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionResultItemSelected).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionSourceDetailPanel).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionSourceDetailActions).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionSourceDetailFacts).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionSourceDetailNotice).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionSearchEvidence).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionSearchEvidenceBody).toBeTypeOf("string");
    expect(routeStyles.workflowCandidateItemSelected).toBeTypeOf("string");
    expect(routeStylesSource).toContain(".sourceCollectionResultStatus");
    expect(routeStylesSource).toContain(".sourceCollectionResultSource");
    expect(routeStylesSource).toContain(".sourceCollectionResultSourceMissing");
    expect(routeStylesSource).toContain(".sourceCollectionFilterBar");
    expect(routeStylesSource).toContain(".sourceCollectionFilterActive");
    expect(routeStylesSource).toContain("grid-template-columns: minmax(220px, 1fr) minmax(80px, 112px) minmax(150px, 240px)");
    expect(routeStylesSource).toContain("grid-template-rows: auto auto auto");
    expect(routeStylesSource).toContain(".sourceCollectionCandidateListShell");
    expect(routeStylesSource).toContain("overflow-y: auto");
    expect(routeStylesSource).toContain("scrollbar-gutter: stable");
    expect(routeStylesSource).toContain("align-items: start");
    expect(routeStylesSource).toContain("align-content: start");
    expect(routeStylesSource).toContain("align-self: start");
    expect(routeStylesSource).toContain("min-height: 0");
    expect(routeStylesSource).not.toContain("grid-template-rows: auto minmax(0, 1fr) auto auto");
    expect(routeStylesSource).toContain("grid-template-columns: repeat(5, minmax(0, 1fr))");
    expect(routeStylesSource).not.toContain("min-height: 122px");
    expect(routeStylesSource).not.toContain("min-height: 96px");
    expect(routeStylesSource).toContain("grid-template-columns: 44px minmax(0, 1fr)");
    expect(routeStylesSource).toContain("-webkit-line-clamp: 2");
    expect(routeStylesSource).not.toContain("grid-template-columns: 58px minmax(0, 1fr)");
    expect(routeStylesSource).not.toMatch(/\.sourceCollectionTraceBody p \{[\s\S]*?-webkit-line-clamp: 3/);
    expect(routeStylesSource).toContain("grid-template-columns: minmax(0, 1fr) minmax(320px, 380px)");
    expect(routeStylesSource).toContain("isolation: isolate");
    expect(routeStylesSource).toContain("grid-template-rows: auto auto minmax(0, 1fr)");
    expect(routeStylesSource).toContain("grid-template-columns: minmax(120px, 0.24fr) minmax(0, 1fr) max-content");
    expect(routeStylesSource).toContain("@media (max-width: 1320px)");
    expect(routeStylesSource).toContain("grid-column: 1 / -1");
    expect(routeStylesSource).toContain("grid-row: 2");
    expect(routeStylesSource).toContain("grid-template-columns: repeat(3, max-content)");
    expect(routeStylesSource).toContain("grid-template-columns: repeat(3, minmax(0, 1fr))");
    expect(routeStylesSource).toContain("user-select: none");
    expect(routeStylesSource).toContain("white-space: nowrap");
    expect(routeStylesSource).toContain("writing-mode: horizontal-tb");
    expect(routeStyles.sourceCollectionControlPanel).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionStageModules).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionStageCard).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionStageCardSelected).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionStageCardHead).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionStageProjection).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionStageTaskSummary).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionStageBlockers).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionStageMiniFlow).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionStageWorkspace).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionStageWorkspaceHeader).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionStageHandoff).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionStageHandoffNext).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionStageChatActions).toBeTypeOf("string");
    expect(routeStylesSource).not.toContain(".sourceCollectionStageTabs");
    expect(routeStylesSource).not.toContain(".sourceCollectionStageTabActive");
    expect(routeStyles.sourceCollectionTraceHandoff).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionPagination).toBeTypeOf("string");
    expect(routeStylesSource).not.toContain(".sourceCollectionStageActionRow");
    expect(routeStylesSource).not.toContain(".sourceCollectionStageOperationPanel");
    expect(routeStyles.sourceCollectionPanelActions).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionScreeningListShell).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionScreeningList).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionScreeningScrollHint).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionStagePrimaryAction).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionStageSecondaryAction).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionFocusedPanel).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionStepActive).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionStepDone).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionStepFailed).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionStepIdle).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionStepPending).toBeTypeOf("string");
    expect(routeStyles.workflowSourceCollectionStorageDetails).toBeTypeOf("string");
    expect(routeStyles.researchStagePage).toBeTypeOf("string");
    expect(routeStyles.researchStageHeroPanel).toBeTypeOf("string");
    expect(routeStyles.researchStageActionPanel).toBeTypeOf("string");
    expect(routeStyles.researchStageModuleGrid).toBeTypeOf("string");
    expect(routeStyles.researchStageBoundaryPanel).toBeTypeOf("string");
    expect(routeStyles.workflowGraphPanel).toBeTypeOf("string");
    expect(routeStyles.workflowGraphFrame).toBeTypeOf("string");
    expect(routeStyles.workflowGraphNode).toBeTypeOf("string");
    expect(routeStyles.workflowGraphEdge).toBeTypeOf("string");
    expect(routeStyles.workflowGraphBoundary).toBeTypeOf("string");
    expect(routeStyles.workflowCandidateList).toBeTypeOf("string");
    expect(routeStyles.workflowCandidateListPanel).toBeTypeOf("string");
    expect(routeStyles.workflowCandidateListHeader).toBeTypeOf("string");
    expect(routeStyles.workflowCandidateListScroll).toBeTypeOf("string");
    expect(routeStyles.workflowCandidateListScrollHint).toBeTypeOf("string");
    expect(routeStyles.workflowCandidateActions).toBeTypeOf("string");
    expect(routeStyles.workflowValidation).toBeTypeOf("string");
    expect(routeStyles.workspaceResearch).toBeTypeOf("string");
    expect(routeStyles.workspaceResearchCanvas).toBeTypeOf("string");
    expect(routeStyles.researchStageLauncher).toBeTypeOf("string");
    expect(routeStyles.researchCanvasIndex).toBeTypeOf("string");
    expect(routeStyles.researchStageCard).toBeTypeOf("string");
    expect(routeStyles.researchStageCardHead).toBeTypeOf("string");
    expect(routeStyles.researchStageCardMetrics).toBeTypeOf("string");
    expect(routeStyles.researchStageAgentSummary).toBeTypeOf("string");
    expect(routeStyles.researchStageAgentSummaryReady).toBeTypeOf("string");
    expect(routeStyles.researchStageAgentSummaryMissing).toBeTypeOf("string");
    expect(routeStyles.researchStageAgentSummaryBlocked).toBeTypeOf("string");
    expect(routeStyles.researchStageAgentPanel).toBeTypeOf("string");
    expect(routeStyles.researchStageAgentPanelCompact).toBeTypeOf("string");
    expect(routeStyles.researchStageAgentGrid).toBeTypeOf("string");
    expect(routeStyles.researchStageAgentCard).toBeTypeOf("string");
    expect(routeStyles.researchStageAgentCard_ready).toBeTypeOf("string");
    expect(routeStyles.researchStageAgentCard_warning).toBeTypeOf("string");
    expect(routeStyles.researchStageAgentCard_blocked).toBeTypeOf("string");
    expect(routeStyles.researchStageAgentCard_missing).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionStageAgentPanel).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionStageAgentHeader).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionStageAgentList).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionStageAgentCard).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionStageAgentCardBody).toBeTypeOf("string");
    expect(routeStyles.sourceCollectionStageAgentCardActions).toBeTypeOf("string");
    expect(routeStyles.researchInspector).toBeTypeOf("string");
    expect(routeStyles.researchCanvasPanelHidden).toBeTypeOf("string");
    expect(routeStyles.canvasReadOnlyBadge).toBeTypeOf("string");
    expect(routeStyles.canvasReadOnlyPanel).toBeTypeOf("string");
    expect(routeStyles.canvasLayoutModeSwitch).toBeTypeOf("string");
    expect(routeStyles.canvasReadOnlyNotice).toBeTypeOf("string");
    expect(routeStyles.canvasReadOnlyNode).toBeTypeOf("string");
    expect(routeStyles.canvasReadOnlyNodeWide).toBeTypeOf("string");
    expect(routeStyles.nodeReadOnly).toBeTypeOf("string");
    expect(routeStyles.aiSearchScopePanel).toBeTypeOf("string");
    expect(routeStyles.aiSearchScopeStats).toBeTypeOf("string");
    expect(routeStyles.aiSearchSourceGroups).toBeTypeOf("string");
    expect(routeStyles.aiSearchSourceItem).toBeTypeOf("string");
    expect(routeStyles.aiSearchRunPanel).toBeTypeOf("string");
    expect(routeStyles.aiSearchRunHeader).toBeTypeOf("string");
    expect(routeStyles.aiSearchRunStats).toBeTypeOf("string");
    expect(routeStyles.aiSearchRunCard).toBeTypeOf("string");
    expect(routeStyles.aiSearchRunRefs).toBeTypeOf("string");
    expect(routeStyles.workspaceEmpty).toBeTypeOf("string");
    expect(routeStyles.emptyCanvasPanel).toBeTypeOf("string");
    expect(routeStylesSource).toContain("height: 100%");
    expect(routeStylesSource).toContain("overflow: hidden");
    expect(routeStylesSource).toContain(".canvasLayoutModeSwitch");
  });

  it("keeps Team actions scoped to the selected Team or message event", () => {
    expect(routeSource).toContain("canvasSavePendingForTeam");
    expect(routeSource).toContain("saveCanvasMutation.variables?.teamId === teamId");
    expect(routeSource).toContain("selectedTeamSyncPending");
    expect(routeSource).toContain("syncTeamChatRoomMutation.variables === selectedTeam?.teamId");
    expect(routeSource).toContain("selectedTeamStartRoundPending");
    expect(routeSource).toContain("startTeamRoundMutation.variables?.teamId === selectedTeam?.teamId");
    expect(routeSource).toContain("selectedTeamMessagePending");
    expect(routeSource).toContain("sendTeamMessageMutation.variables?.teamId === selectedTeam?.teamId");
    expect(routeSource).toContain("revokeTeamMessageMutation.variables?.eventId === event.eventId");
    expect(routeSource).toContain("revokeTeamMessageMutation.mutate({ teamId: selectedTeam.teamId, eventId: event.eventId })");
    expect(routeSource).not.toContain("chatWorkspaceCache.afterTeamChanged(selectedTeamId || undefined)");
    expect(routeSource).not.toContain("revokeTeamMessageMutation.mutate(event.eventId)");
  });

  it("renders visible directional communication edges on the Team canvas", () => {
    expect(routeSource).toContain("<marker");
    expect(routeSource).toContain('id="team-edge-arrow"');
    expect(routeSource).toContain("key={edge.id}");
    expect(routeSource).toContain("Q ${line.cx} ${line.cy}");
    expect(routeSource).toContain("nodeBoundaryPoint");
    expect(routeSource).toContain("distanceToRectEdge");
    expect(routeSource).toContain("edgeLine(edge, displayCanvasNodes, visibleEdges)");
    expect(routeSource).toContain("sourceFanSpread");
    expect(routeSource).not.toContain("<line key={edge.id}");
    expect(routeSource).toContain("className={styles.edges}");
  });

  it("separates organization lines from information lines by default", () => {
    expect(routeSource).toContain("showCommunicationEdges");
    expect(routeSource).toContain("isCommunicationEdge(edge)");
    expect(routeSource).toContain("organizationEdges");
    expect(routeSource).toContain("communicationEdges");
    expect(routeSource).toContain("visibleCommunicationEdges");
    expect(routeSource).toContain("visibleCommunicationEdgeCount");
    expect(routeSource).toContain("visibleEdges");
    expect(routeSource).toContain("edge.type === \"communication\"");
    expect(routeSource).toContain("edge.type === \"collaborates_with\"");
    expect(routeSource).toContain("styles.edgeOrganization");
    expect(routeSource).toContain("styles.edgeCommunication");
    expect(routeSource).toContain("信息线");
    expect(routeSource).toContain("信息线已收起（");
    expect(routeSource).toContain("展开信息线");
    expect(routeSource).toContain("收起信息线");
    expect(routeSource).toContain("Info");
    expect(routeSource).toContain('type: "reports_to"');
    expect(routeSource).not.toContain("canvas?.edges.map((edge)");
  });

  it("centers compact Team canvases and renders function role badges", () => {
    expect(routeSource).toContain("canvasViewStyle");
    expect(routeSource).toContain("CANVAS_VIEWPORT_WIDTH");
    expect(routeSource).toContain("CANVAS_VIEWPORT_HEIGHT");
    expect(routeSource).toContain("canvasViewportStyle");
    expect(routeSource).toContain("lockedCanvasViewportStyle");
    expect(routeSource).toContain("setLockedCanvasViewportStyle(canvasViewportStyle)");
    expect(routeSource).toContain("canvasFrameSize");
    expect(routeSource).toContain("canvasViewStyle(displayCanvasNodes, canvasFrameSize)");
    expect(routeSource).toContain("ResizeObserver");
    expect(routeSource).toContain("styles.canvasViewport");
    expect(routeSource).toContain("--canvas-offset-x");
    expect(routeSource).toContain("--canvas-scale");
    expect(routeSource).toContain("--node-x");
    expect(routeSource).toContain("roleBadgeTone");
    expect(routeSource).toContain("teamNodeFunctionLabel");
    expect(routeSource).toContain("能力管家");
    expect(routeSource).toContain("styles.nodeRoleBadge");
    expect(routeSource).toContain("styles.nodeRoleBadgeLead");
    expect(routeSource).toContain("styles.nodeRoleBadgeAdvisor");
    expect(routeSource).toContain("styles.nodeRoleBadgeSteward");
  });

  it("keeps read-only research canvas auto layout visual-only and deterministic", () => {
    expect(routeSource).toContain("function autoLayoutResearchCanvasNodes");
    expect(routeSource).toContain("researchCanvasRoleLayer");
    expect(routeSource).toContain("RESEARCH_CANVAS_AUTO_LAYOUT_LAYER_GAP");
    expect(routeSource).toContain("RESEARCH_CANVAS_AUTO_LAYOUT_ROW_GAP");
    expect(routeSource).toContain("teamCanvasNodeSortKey");
    expect(routeSource).toContain("positions.set(node.id");
    expect(routeSource).toContain("return nodes.map((node) => ({");
    expect(routeSource).toContain("displayCanvasNodes.map((node)");
    expect(routeSource).not.toContain("saveCanvas(autoLayoutCanvasNodes");
    expect(routeSource).not.toContain("saveCanvas(displayCanvasNodes");
    expect(routeStyles.canvasLayoutModeSwitch).toBeTypeOf("string");
  });

  it("lets users drag canvas nodes and persist their positions", () => {
    expect(routeSource).toContain("nodePositionDrafts");
    expect(routeSource).toContain("dragStateRef");
    expect(routeSource).toContain("dragFrameRef");
    expect(routeSource).toContain("startNodeDrag");
    expect(routeSource).toContain("moveNodeDrag");
    expect(routeSource).toContain("finishNodeDrag");
    expect(routeSource).toContain("requestNodeDragFrame");
    expect(routeSource).toContain("window.requestAnimationFrame");
    expect(routeSource).toContain("window.cancelAnimationFrame");
    expect(routeSource).toContain("commitNodeDragPosition(dragState)");
    expect(routeSource).toContain("setPointerCapture(event.pointerId)");
    expect(routeSource).toContain("releasePointerCapture(event.pointerId)");
    expect(routeSource).toContain("nodes: canvas.nodes.map((node) => (node.id === dragState.nodeId");
    expect(routeSource).toContain("onPointerDown={researchCanvasReadOnly ? undefined : (event) => startNodeDrag(event, node)}");
    expect(routeSource).toContain("onPointerMove={researchCanvasReadOnly ? undefined : moveNodeDrag}");
    expect(routeSource).toContain("onPointerUp={researchCanvasReadOnly ? undefined : finishNodeDrag}");
    expect(routeSource).toContain("edgeLine(edge, displayCanvasNodes, visibleEdges)");
  });
});
