import {
  vuiFlatPanelClass,
  vuiOpaqueRowClass,
} from "../design/vuiSurfaceRecipes";

const styles = {
  sourceCollectionStageAgentCard: `sourceCollectionStageAgentCard min-w-0 ${vuiOpaqueRowClass} p-1.5 text-[var(--accent-cool)] !grid grid-cols-[minmax(0,1fr)_auto] items-stretch gap-1.5 max-[720px]:grid-cols-[minmax(0,1fr)] [&_a]:inline-flex [&_a]:w-fit [&_a]:max-w-full [&_a]:items-center [&_a]:justify-center [&_a]:gap-1.5 [&_a]:min-h-[28px] [&_a]:px-2.5 [&_a]:rounded-[7px] [&_a]:border [&_a]:border-[color:color-mix(in_srgb,var(--accent-cool)_32%,var(--border-soft))] [&_a]:bg-[color:color-mix(in_srgb,var(--accent-cool)_8%,var(--vui-surface-panel))] [&_a]:text-[var(--fg-primary)] [&_a]:font-[780] [&_a]:no-underline [&_a]:whitespace-nowrap [&_[data-vui=native-button]]:inline-flex [&_[data-vui=native-button]]:w-fit [&_[data-vui=native-button]]:max-w-full [&_[data-vui=native-button]]:items-center [&_[data-vui=native-button]]:justify-center [&_[data-vui=native-button]]:gap-1.5 [&_[data-vui=native-button]]:min-h-[28px] [&_[data-vui=native-button]]:px-2.5 [&_[data-vui=native-button]]:rounded-[7px] [&_[data-vui=native-button]]:border [&_[data-vui=native-button]]:border-[color:color-mix(in_srgb,var(--accent-cool)_32%,var(--border-soft))] [&_[data-vui=native-button]]:bg-[color:color-mix(in_srgb,var(--accent-cool)_8%,var(--vui-surface-panel))] [&_[data-vui=native-button]]:text-[var(--fg-primary)] [&_[data-vui=native-button]]:font-[780]`,
  sourceCollectionStageAgentCardActions:
    "sourceCollectionStageAgentCardActions min-w-0 flex flex-wrap items-center justify-end gap-1.5 text-[var(--accent-cool)] max-[720px]:justify-start [&>span]:min-w-0 [&>span]:break-words [&>span]:[font-size:var(--vui-font-xs)] [&>span]:font-semibold [&>span]:leading-tight [&_a]:w-fit [&_a]:max-w-full [&_[data-vui=native-button]]:w-fit [&_[data-vui=native-button]]:max-w-full",
  sourceCollectionStageAgentCardBody:
    "sourceCollectionStageAgentCardBody min-w-0 p-1 [font-size:var(--vui-font-sm)] leading-[var(--vui-line-readable)] text-[var(--accent-cool)] !grid grid-cols-[repeat(3,minmax(0,1fr))] gap-1.5 max-[680px]:grid-cols-[minmax(0,1fr)] [&_span]:min-w-0 [&_span]:grid [&_span]:gap-0.5 [&_small]:min-w-0 [&_small]:truncate [&_small]:text-[var(--fg-tertiary)] [&_strong]:min-w-0 [&_strong]:truncate [&_strong]:text-[var(--fg-primary)]",
  sourceCollectionStageAgentHeader:
    "sourceCollectionStageAgentHeader min-w-0 !flex flex-wrap items-center justify-between gap-2 text-[var(--accent-cool)] [&>div]:grid [&>div]:min-w-0 [&>div]:gap-0.5 [&>div_strong]:truncate [&>div_strong]:text-[var(--fg-primary)] [&>div_span]:truncate [&>div_span]:text-[var(--fg-muted)] [&_a]:inline-flex [&_a]:w-fit [&_a]:max-w-full [&_a]:items-center [&_a]:justify-center [&_a]:gap-1.5 [&_a]:min-h-[28px] [&_a]:px-2.5 [&_a]:rounded-[7px] [&_a]:border [&_a]:border-[color:color-mix(in_srgb,var(--accent-cool)_32%,var(--border-soft))] [&_a]:bg-[color:color-mix(in_srgb,var(--accent-cool)_8%,var(--vui-surface-panel))] [&_a]:text-[var(--fg-primary)] [&_a]:font-[780] [&_a]:no-underline [&_a]:whitespace-nowrap [&_[data-vui=native-button]]:inline-flex [&_[data-vui=native-button]]:w-fit [&_[data-vui=native-button]]:max-w-full [&_[data-vui=native-button]]:items-center [&_[data-vui=native-button]]:justify-center [&_[data-vui=native-button]]:gap-1.5 [&_[data-vui=native-button]]:min-h-[28px] [&_[data-vui=native-button]]:px-2.5 [&_[data-vui=native-button]]:rounded-[7px] [&_[data-vui=native-button]]:border [&_[data-vui=native-button]]:border-[color:color-mix(in_srgb,var(--accent-cool)_32%,var(--border-soft))] [&_[data-vui=native-button]]:bg-[color:color-mix(in_srgb,var(--accent-cool)_8%,var(--vui-surface-panel))] [&_[data-vui=native-button]]:text-[var(--fg-primary)] [&_[data-vui=native-button]]:font-[780]",
  sourceCollectionStageAgentList:
    "sourceCollectionStageAgentList min-w-0 grid min-h-0 content-start gap-1.5 overflow-auto text-[var(--accent-cool)]",
  sourceCollectionStageAgentPanel: `sourceCollectionStageAgentPanel min-w-0 ${vuiFlatPanelClass} p-2 text-[var(--fg-primary)]`,
} as const;

export default styles;
