import { createVuiStyleMap } from "../components/vui/styles/createVuiStyleMap";

const styleKeys = [
  "agentCompatibility",
  "agentPermissionSummaryPanel",
  "agentPolicySelect",
  "agentScopeBar",
  "bulkActionBar",
  "bulkSummary",
  "controlStrip",
  "countPill",
  "dangerButton",
  "deepLinkFocus",
  "deepLinkNotice",
  "dependencyHealthPanel",
  "detailActions",
  "detailHeader",
  "detailPanel",
  "emptyDetail",
  "emptyState",
  "eyebrow",
  "filterButton",
  "filterButtonActive",
  "filterRow",
  "header",
  "headerActions",
  "image2ModelControls",
  "image2ModelPanel",
  "image2ModelSelect",
  "image2ModelSummary",
  "listPanel",
  "managementNav",
  "metaGrid",
  "metaGridWide",
  "notice",
  "noticeError",
  "noticeSuccess",
  "paneCollapsed",
  "panelEyebrow",
  "panelHeader",
  "permissionSummaryCards",
  "permissionSummaryGrid",
  "policy_allowed",
  "policy_blocked",
  "policy_excluded",
  "policy_explicit_required",
  "policy_inherited",
  "policyDraftPanel",
  "policyDraftSummary",
  "policyHint",
  "policyMeta",
  "policyPanel",
  "policyStatePill",
  "primaryButton",
  "readiness_blocked",
  "readiness_ready",
  "readinessCard",
  "readinessPanel",
  "refreshButton",
  "resizeHandle",
  "result_attention",
  "result_ok",
  "resultCard",
  "resultSummaryGrid",
  "returnButton",
  "route",
  "rowSelect",
  "schemaDisclosure",
  "scopeCopy",
  "scopeSelect",
  "scopeStats",
  "searchBox",
  "secondaryButton",
  "segmentActive",
  "segmentActiveDanger",
  "segmentButton",
  "segmentedControl",
  "selectableToolRow",
  "sourcePill",
  "state_active",
  "state_enabled",
  "state_error",
  "state_idle",
  "stateBadge",
  "status_active",
  "status_enabled",
  "status_error",
  "status_idle",
  "statusDot",
  "subtitle",
  "summaryCard",
  "summaryGrid",
  "testArgs",
  "testPanel",
  "title",
  "toolAgentFitPanel",
  "toolBadges",
  "toolBundleApplyActions",
  "toolBundleApplyBar",
  "toolBundleDescription",
  "toolBundleGroup",
  "toolBundleHeader",
  "toolBundleItems",
  "toolBundleSelect",
  "toolBundleSummary",
  "toolButton",
  "toolButtonActive",
  "toolCopy",
  "toolDetailPanel",
  "toolList",
  "toolPermissionGroup",
  "toolPermissionGroupHeader",
  "toolPermissionGroupList",
  "toolPermissionList",
  "toolPermissionMeta",
  "toolPermissionRow",
  "unsavedPill",
  "workspace",
  "workspaceScopePanel",
] as const;

const styles = createVuiStyleMap(styleKeys, {
  extensions: {
    // Let the summary metrics fill the control strip and flow into columns
    // instead of collapsing into a narrow stacked column beside the nav.
    summaryGrid: "flex-1 grid-cols-[repeat(auto-fit,minmax(6.5rem,1fr))]",
    // Real list | resize-handle | detail split; the generic workspace rule
    // only emits a single-column grid.
    workspace:
      "!grid grid-cols-[var(--tools-left-panel-width)_auto_minmax(0,1fr)] grid-rows-[minmax(0,1fr)] overflow-hidden",
  },
});

export default styles;
