import "../design/route-css/workbench-secondary.tailwind.css";

import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { ArrowLeft, ChevronDown, ChevronRight, RefreshCw } from "lucide-react";

import { fetchUsageSummary } from "../api/usage";
import { queryKeys } from "../api/queryKeys";
import type { UsageSource } from "../api/types";
import { resolvePollingInterval, usePageVisibility } from "../app/pollingPolicy";
import { deriveQueryPresentation } from "../app/queryPresentation";
import { VButton, VLoadingValue, VRouteLinkButton, VSettingsFormPage, VStateSurface, VTabs } from "../components/vui";
import { useAppI18n } from "../i18n/useAppI18n";
import styles from "./UsageRoute.styles";

type UsageRange = "today" | "last7Days" | "allTime";
const numberText = (value: number) => new Intl.NumberFormat().format(value);
const percentage = (part: number, total: number) => (part / total * 100).toFixed(1) + "%";

export function UsageRoute() {
  const { lang } = useAppI18n({ domains: ["core"] });
  const copy = (zh: string, en: string) => lang === "zh" ? zh : en;
  const [range, setRange] = useState<UsageRange>("last7Days");
  const [diagnosticsOpen, setDiagnosticsOpen] = useState(false);
  const pageVisible = usePageVisibility();
  const usageQuery = useQuery({
    queryKey: queryKeys.usageSummary("global"),
    queryFn: () => fetchUsageSummary(),
    refetchInterval: resolvePollingInterval(pageVisible, 10_000, { backgroundMs: 60_000 }),
    refetchIntervalInBackground: false,
  });
  const summary = usageQuery.data;
  const rollup = summary?.globalTokenUsage?.[range];
  const last = summary?.lastTokenUsage;
  const presentation = deriveQueryPresentation({
    hasData: Boolean(summary), isError: usageQuery.isError,
    isFetching: usageQuery.isFetching, isPending: usageQuery.isPending,
  });
  const loading = presentation === "initial-loading";
  const ranges = [
    { id: "today", label: copy("今日", "Today") },
    { id: "last7Days", label: copy("最近 7 天", "Last 7 days") },
    { id: "allTime", label: copy("全部时间", "All time") },
  ];
  const rangeLabel = ranges.find(item => item.id === range)!.label;
  const value = (n: number | undefined) => loading
    ? <VLoadingValue label={copy("正在加载用量", "Loading usage")} />
    : n === undefined ? "—" : numberText(n);
  const cacheKnown = Boolean(rollup && rollup.cacheUsageObserved !== false);
  const sourceLabel = (source: UsageSource | undefined) => ({
    provider_usage: copy("供应商返回", "Provider usage"),
    estimated: copy("本地估算", "Estimated"),
    missing: copy("缺少用量", "Missing usage"),
    not_called: copy("尚未调用", "Not called"),
  })[source ?? ""] ?? source ?? "—";
  const tokenRows = [
    { name: copy("输入", "Input"), hint: copy("发送给模型的 Token", "Tokens sent to the model"), amount: rollup?.inputTokens },
    { name: copy("其中缓存输入", "Cached input subset"), hint: copy("已包含在输入中，不重复计入总量", "Included in input, not added again"), amount: cacheKnown ? rollup?.cachedInputTokens : undefined, subset: true },
    { name: copy("输出", "Output"), hint: copy("模型生成的 Token", "Tokens generated by the model"), amount: rollup?.outputTokens },
    { name: copy("其中推理输出", "Reasoning output subset"), hint: copy("已包含在输出中，不重复计入总量", "Included in output, not added again"), amount: rollup?.reasoningOutputTokens, subset: true },
  ];
  const sourceRows = [
    { name: copy("供应商返回用量", "Provider-reported usage"), amount: rollup ? numberText(rollup.observedCallCount) + " / " + numberText(rollup.callCount) : undefined,
      hint: rollup && rollup.callCount > 0 ? percentage(rollup.observedCallCount, rollup.callCount) + " " + copy("覆盖率", "coverage") : copy("暂无可计算比例", "No ratio available") },
    { name: copy("本地估算", "Local estimates"), amount: rollup && numberText(rollup.estimatedCallCount), hint: copy("没有供应商用量时的补充", "Used when provider usage is absent") },
    { name: copy("缺少用量", "Missing usage"), amount: rollup && numberText(rollup.missingCallCount), hint: copy("不应解读为零消耗", "Does not mean zero consumption") },
  ];
  const diagnostics = [
    [copy("服务 / 模型", "Provider / model"), [last?.provider, last?.model].filter(Boolean).join(" / ") || "—"],
    [copy("最近一次用量", "Latest usage"), last && last.source !== "missing" && last.source !== "not_called" && last.totalTokens !== undefined ? numberText(last.totalTokens) + " tokens · " + sourceLabel(last.source) : sourceLabel(last?.source)],
    [copy("记录时间", "Recorded at"), last?.recordedAt || "—"],
    [copy("账本", "Ledger"), summary?.diagnostics?.source || "—"],
    [copy("账本版本", "Schema version"), summary?.diagnostics?.schemaVersion ?? "—"],
    [copy("跳过记录", "Skipped records"), summary?.diagnostics?.skippedRecordCount ?? "—"],
    [copy("事件 ID", "Event ID"), last?.eventId || "—"],
    [copy("会话 ID", "Session ID"), summary?.rollupFilters?.sessionId || "—"],
    [copy("Agent ID", "Agent ID"), summary?.rollupFilters?.agentId || "—"],
  ];

  return <div className={styles.page}>
    <div className={styles.sheet}>
      <nav className={styles.breadcrumb} aria-label={copy("设置导航", "Settings navigation")}>
        <VRouteLinkButton to="/config" variant="ghost" icon={<ArrowLeft size={15} />}>
          {copy("设置", "Settings")}
        </VRouteLinkButton><ChevronRight size={13} aria-hidden="true" /><span>{copy("用量统计", "Usage")}</span>
      </nav>
      <VSettingsFormPage title={copy("用量统计", "Usage statistics")} ariaLabel={copy("用量统计", "Usage statistics")}
        meta={copy("查看全局模型消耗与统计来源。", "Review global model usage and its sources.")}
        className={styles.recipe} headerClassName={styles.header} bodyClassName={styles.body} aria-busy={loading}
        actions={<VButton variant="secondary" icon={<RefreshCw size={15} />} isDisabled={usageQuery.isFetching}
          onPress={() => { void usageQuery.refetch(); }}>{copy("刷新", "Refresh")}</VButton>}>
        <div className={styles.rangeRow}>
          <VTabs aria-label={copy("统计时间范围", "Usage time range")} value={range}
            onValueChange={id => setRange(id as UsageRange)} items={ranges} />
          <span role="status">{loading ? copy("正在加载统计…", "Loading usage…")
            : usageQuery.isError ? copy("更新失败", "Update failed")
              : presentation === "refreshing" ? copy("同步中", "Refreshing") : copy("自动更新", "Auto-updating")}</span>
        </div>
        {usageQuery.isError && <VStateSurface tone="error" title={summary
          ? copy("更新失败，保留上次成功读取的数据", "Update failed; showing the last successful snapshot")
          : copy("用量暂不可用", "Usage unavailable")}>
          {usageQuery.error instanceof Error ? usageQuery.error.message : copy("请点击刷新重试。", "Select Refresh to retry.")}
        </VStateSurface>}
        {loading && <span className="sr-only">{copy("正在加载 Token 用量", "Loading token usage")}</span>}
        {!loading && !usageQuery.isError && !rollup && <VStateSurface tone="unavailable" title={copy("此时间范围的统计暂不可用", "Usage for this range is unavailable")} />}
        {rollup?.callCount === 0 && <VStateSurface tone="info" title={copy("此时间范围内暂无调用", "No calls in this time range")} />}
        <section className={styles.metrics} aria-label={copy("用量概览", "Usage overview")}>
          <div className={styles.metric}><span>{copy("Token 总量", "Total tokens")}</span><strong data-testid="usage-total">{value(rollup?.totalTokens)}</strong><small>tokens · {copy("账本汇总", "Ledger total")}</small></div>
          <div className={styles.metric}><span>{copy("调用次数", "Calls")}</span><strong data-testid="usage-calls">{value(rollup?.callCount)}</strong><small>{rangeLabel} · {copy("按账本记录统计", "Ledger records")}</small></div>
          <div className={styles.metric}><span>{copy("缓存输入占比", "Cached input share")}</span><strong data-testid="usage-cache-share">{loading ? <VLoadingValue label={copy("正在加载用量", "Loading usage")} /> : cacheKnown && rollup && rollup.inputTokens > 0 ? percentage(rollup.cachedInputTokens, rollup.inputTokens) : "—"}</strong><small>{copy("缓存输入 ÷ 全部输入", "Cached input / all input")}</small></div>
        </section>
        <section>
          <div className={styles.sectionHeading}><h2>{copy("Token 构成", "Token composition")}</h2><span>{rangeLabel}</span></div>
          {rollup && rollup.inputTokens + rollup.outputTokens > 0 && <div className={styles.composition} aria-hidden="true">
            {/* Data-driven chart width, not layout styling. */}
            <span style={{ width: (rollup.inputTokens / (rollup.inputTokens + rollup.outputTokens) * 100) + "%" }} /><span className="flex-1" />
          </div>}
          <div>{tokenRows.map(row => <div key={row.name} className={row.subset ? styles.tokenRow + " " + styles.subset : styles.tokenRow}>
            <div><strong>{row.name}</strong><span>{row.hint}</span></div><span>{value(row.amount)}</span>
          </div>)}</div>
          {rollup && (rollup.cacheUsageObserved === false || rollup.cacheUsageComplete === false) && <p className={styles.note}>
            {copy("部分或全部调用未返回缓存明细；已记录的缓存输入不代表完整缓存用量。", "Some calls lack cache details; recorded cached input may be incomplete.")}
          </p>}
        </section>
        <section className={styles.sources}>
          <div className={styles.sectionHeading}><h2>{copy("统计来源", "Usage sources")}</h2><span>{copy("按调用次数，不是准确率评分", "By calls, not an accuracy score")}</span></div>
          {sourceRows.map(row => <div className={styles.sourceRow} key={row.name}><span>{row.name}</span><strong>{loading ? <VLoadingValue label={copy("正在加载用量", "Loading usage")} /> : row.amount === undefined ? "—" : row.amount + " " + copy("次", "calls")}</strong><span>{row.hint}</span></div>)}
        </section>
        <div className={styles.diagnostics}>
          <VButton variant="ghost" contentLayout="plain" className={styles.diagnosticsToggle} aria-expanded={diagnosticsOpen}
            aria-controls="usage-diagnostics" onPress={() => setDiagnosticsOpen(!diagnosticsOpen)}>
            {diagnosticsOpen ? <ChevronDown size={16} /> : <ChevronRight size={16} />}<span>{copy("最近一次调用与诊断", "Latest call and diagnostics")}</span><small>{copy("独立于上方时间范围", "Independent of the selected range")}</small>
          </VButton>
          {diagnosticsOpen && <dl id="usage-diagnostics" className={styles.details}>
            {diagnostics.map(([name, detail]) => <div key={name}><dt>{name}</dt><dd>{loading ? <VLoadingValue label={copy("正在加载用量", "Loading usage")} /> : detail}</dd></div>)}
          </dl>}
        </div>
        <p className={styles.note}>{copy("仅展示已记录的用量，不等同于供应商账单；缓存与推理 Token 是输入、输出的子项。", "Recorded usage only, not a provider invoice. Cached and reasoning tokens are subsets of input and output.")}</p>
      </VSettingsFormPage>
    </div>
  </div>;
}
