/**
 * The perception workspace keeps its inspector beside the active page on wide
 * screens and stacks it below the page on narrow screens. Width memory still
 * belongs to VSplitWorkspace's shared layout persistence.
 */
const styles = {
  workspace: [
    // Route styles can be prefetched later; keep their generic flex utilities
    // from changing this recipe's direction or its natural-height panes.
    "[&[data-vui=split-workspace]]:!flex-col !overflow-visible xl:[&[data-vui=split-workspace]]:!flex-row",
    "[&>[data-vui-layout-handle]]:hidden xl:[&>[data-vui-layout-handle]]:flex",
    "[&>main[data-vui=split-main]]:!h-auto [&>main[data-vui=split-main]]:!flex-none [&>main[data-vui=split-main]]:!overflow-visible",
    "xl:[&>main[data-vui=split-main]]:!flex-1",
    "[&>aside[data-vui=split-aside]]:!h-auto [&>aside[data-vui=split-aside]]:!w-full",
    "[&>aside[data-vui=split-aside]]:!basis-auto [&>aside[data-vui=split-aside]]:!min-w-0 [&>aside[data-vui=split-aside]]:!max-w-none [&>aside[data-vui=split-aside]]:!flex-none",
    "xl:[&>aside[data-vui=split-aside]]:!w-[var(--pane-w-runtime)]",
    "xl:[&>aside[data-vui=split-aside]]:!basis-[var(--pane-w-runtime)] xl:[&>aside[data-vui=split-aside]]:!min-w-[260px] xl:[&>aside[data-vui=split-aside]]:!max-w-[480px]",
  ].join(" "),
  mainContent: "mx-auto grid w-full max-w-5xl min-w-0 gap-3",
  runtimeAside: "grid min-w-0 gap-3 xl:min-h-0 xl:overflow-y-auto",
  panel: "grid min-w-0 gap-3 p-3 sm:p-4",
  description: "m-0 max-w-[78ch] text-vui-xs leading-5 text-vui-fg-secondary",
  stack: "grid min-w-0 gap-3",
  sectionStack: "grid min-w-0 gap-2",
  compactStack: "grid min-w-0 gap-1",
  sourceGrid: "grid min-w-0 gap-3 xl:grid-cols-2",
  minWidthZero: "min-w-0",
  scopeEmpty: "mt-2",
  scopeOption: "w-full justify-start rounded-vui-control border border-vui-border-subtle bg-vui-surface-panel px-2.5 py-2",
  scopeOptionBody: "grid min-w-0 gap-0.5 text-left",
  scopeOptionTitle: "truncate text-vui-xs font-medium text-vui-fg-primary",
  scopeOptionDetail: "truncate text-vui-xs text-vui-fg-tertiary",
  scopeOptions: "grid min-w-0 gap-1.5",
  sourceHeading: "flex min-w-0 items-start gap-2 px-4 py-3",
  sourceIcon: "mt-0.5 inline-grid size-7 shrink-0 place-items-center rounded-vui-control border border-vui-border-subtle text-vui-fg-secondary",
  sourceTitle: "m-0 text-vui-sm font-semibold text-vui-fg-primary",
  sourceHint: "mb-0 mt-1 text-vui-xs leading-5 text-vui-fg-tertiary",
  ruleText: "m-0 text-vui-xs leading-5 text-vui-fg-secondary",
  triggerList: "flex min-w-0 flex-wrap gap-x-4 gap-y-1",
  inlineControls: "flex min-w-0 flex-wrap items-center gap-2",
  topicInput: "min-w-[14rem] flex-1",
  topicList: "m-0 flex min-w-0 flex-wrap gap-1.5 p-0",
  listItem: "list-none",
  topicChip: "inline-flex max-w-full items-center gap-1",
  topicText: "max-w-[18rem] truncate",
  cardHeading: "flex min-w-0 flex-wrap items-center justify-between gap-2 px-4 py-3",
  cardTitle: "text-vui-sm text-vui-fg-primary",
  runFailureHint: "m-0 px-4 pb-2 text-vui-xs text-vui-fg-secondary",
  runIdentifier: "break-all font-mono text-vui-xs",
  smallText: "text-vui-xs",
  detailText: "text-vui-xs text-vui-fg-secondary",
  mutedText: "text-vui-xs text-vui-fg-tertiary",
  hintText: "m-0 text-vui-xs text-vui-fg-tertiary",
  paragraph: "m-0 text-vui-xs text-vui-fg-secondary",
  usageRow: "flex flex-wrap gap-x-3 gap-y-1 text-vui-xs text-vui-fg-secondary",
  updateItem: "grid min-w-0 gap-1.5 border-t border-vui-border-subtle px-4 py-3 first:border-t-0",
  rowHeading: "flex min-w-0 flex-wrap items-center justify-between gap-2",
  itemTitle: "min-w-0 truncate text-vui-xs font-semibold text-vui-fg-primary",
  updateDetails: "grid min-w-0 gap-1 text-vui-xs text-vui-fg-secondary sm:grid-cols-2",
  breakAll: "break-all",
  updateLinks: "flex min-w-0 flex-wrap items-center gap-1 break-all",
  inlineDetails: "flex min-w-0 flex-wrap items-center gap-1 text-vui-xs",
  screenReader: "sr-only",
  sourceList: "m-0 grid min-w-0 gap-1 p-0",
  sourceItem: "flex min-w-0 list-none flex-wrap items-center justify-between gap-2 text-vui-xs",
  primaryText: "text-vui-fg-primary",
  tertiaryText: "text-vui-fg-tertiary",
  section: "border-t border-vui-border-subtle px-4 py-3",
  sectionHeading: "mb-2 flex min-w-0 flex-wrap items-center justify-between gap-2",
  linkedIdentifier: "break-all font-mono text-vui-fg-tertiary",
  updateList: "m-0 min-w-0 p-0",
  saveState: "text-vui-xs font-medium text-vui-fg-secondary",
  actions: "flex flex-wrap gap-2",
} as const;

export default styles;
