/** Compact perception settings share the Agent detail pane; the save bar stays outside the content scroll. */
const styles = {
  panel: "@container h-full min-h-0 min-w-0 overflow-hidden px-3 py-2 sm:px-4 max-[600px]:[&_button]:!min-h-11 max-[600px]:[&_select]:!min-h-11 max-[600px]:[&_input:not([type=checkbox])]:!min-h-11 max-[600px]:[&_input:not([type=checkbox])]:!text-base max-[600px]:[&_select]:!text-base max-[600px]:[&_[data-vui=checkbox]]:!min-h-11 max-[600px]:[&_[data-vui=switch]]:!min-h-11 max-[600px]:[&_[data-vui=switch]]:!min-w-11 max-[600px]:[&_[data-vui=switch]_[data-slot=switch-content]]:!min-h-11 max-[600px]:[&_[data-vui=switch]_[data-slot=switch-content]]:!min-w-11 max-[600px]:[&_[data-vui=switch]_input]:!min-h-11 max-[600px]:[&_[data-vui=switch]_input]:!min-w-11",
  panelHeader: "mb-2 flex min-w-0 flex-wrap items-center justify-between gap-2",
  formHeader: "[&_[data-vui=route-header]]:!rounded-none [&_[data-vui=route-header]]:!border-0 [&_[data-vui=route-header]]:!bg-transparent [&_[data-vui=route-header]]:!px-0 [&_[data-vui=route-header]]:!py-2 [&_[data-vui=route-header]]:!shadow-none [&_h1]:!text-vui-sm max-[600px]:[&_[data-vui=route-header]]:!grid-cols-1 max-[600px]:[&_[data-vui=route-header]>div:last-child]:!justify-self-start",
  formBody: "!gap-0 pr-1 [scrollbar-gutter:stable]",
  mainContent: "mx-auto grid w-full max-w-[1440px] min-w-0 gap-3 pb-3",
  settingsFields: "m-0 grid min-w-0 gap-3 border-0 p-0 disabled:opacity-70",
  enableLine: "flex min-w-0 items-center justify-between gap-3 px-3 py-2",
  boundary: "m-0 text-vui-xs leading-5 text-vui-fg-tertiary",
  sources: "overflow-hidden",
  sourceCard: "min-w-0 border-t border-vui-border-subtle first:border-t-0",
  sourceLine: "grid min-w-0 grid-cols-[minmax(0,1fr)_112px] items-center gap-x-3 gap-y-1 px-3 py-2 @[480px]:grid-cols-[minmax(0,1fr)_140px] @[730px]:grid-cols-[minmax(180px,1fr)_208px_minmax(140px,1fr)]",
  sourceColumnHead: "hidden grid-cols-[minmax(180px,1fr)_208px_minmax(140px,1fr)] gap-3 border-b border-vui-border-subtle bg-vui-surface-rail px-3 py-1.5 text-vui-xs text-vui-fg-tertiary @[730px]:!grid",
  sourceTitleLine: "flex min-w-0 items-center gap-1",
  modeButtons: "hidden min-w-0 gap-0.5 rounded-vui-control bg-vui-surface-inset p-0.5 @[730px]:!flex [&>button]:min-w-0 [&>button]:flex-1 [&>button]:!px-2",
  modeSelect: "min-w-0 @[730px]:!hidden",
  scopeSummary: "col-span-2 flex min-w-0 items-center gap-2 @[730px]:!col-span-1",
  scopeToggle: "max-w-full !justify-start !px-1 max-[600px]:!min-h-11",
  scopeEditor: "grid min-w-0 gap-2 border-t border-vui-border-subtle bg-vui-surface-inset p-3 @[480px]:px-4",
  scopeKind: "w-full max-w-sm",
  budgetGrid: "grid min-w-0 grid-cols-2 items-start gap-3",
  backgroundFields: "grid min-w-0 gap-3",
  advancedToggle: "w-full !h-auto !justify-start gap-2 !px-0 [&>span]:break-words",
  advancedGrid: "grid min-w-0 grid-cols-2 items-start gap-3 border-l-2 border-vui-border-subtle pl-3 @[730px]:grid-cols-3",
  retainedSummary: "m-0 text-vui-xs leading-5 text-vui-fg-secondary",
  topicsSection: "grid min-w-0 gap-2",
  topicsHeading: "flex min-w-0 flex-wrap items-center justify-between gap-2",
  notificationRow: "grid min-w-0 gap-2 @[480px]:grid-cols-[minmax(0,1fr)_180px] @[480px]:items-center",
  touchControl: "max-[600px]:!min-h-11",
  helpTarget: "max-[600px]:!min-h-11 max-[600px]:!min-w-11",
  warningText: "m-0 text-vui-xs leading-5 text-[var(--vui-status-warning-fg)]",
  changeSummary: "grid min-w-0 gap-1.5",
  changeList: "m-0 pl-5 text-vui-xs leading-5 text-vui-fg-secondary",
  saveMeta: "grid min-w-0 flex-1 gap-1",
  runtimeSummary: "min-w-0 px-3 py-2",
  runtimeStrip: "flex min-w-0 flex-wrap items-center gap-x-3 gap-y-2",
  runtimeFacts: "mt-2 grid min-w-0 gap-1 text-vui-xs text-vui-fg-secondary [&>div]:flex [&>div]:min-w-0 [&>div]:flex-wrap [&>div]:gap-x-3 [&>div>strong]:font-medium [&>div>span]:break-words",
  saveBar: "!justify-between !gap-2 !bg-vui-surface-base !pt-2 !pb-0",
  description: "m-0 max-w-[78ch] text-vui-xs leading-5 text-vui-fg-secondary",
  stack: "grid min-w-0 gap-3",
  sectionStack: "grid min-w-0 gap-2",
  compactStack: "grid min-w-0 gap-1",
  minWidthZero: "min-w-0",
  scopeEmpty: "mt-2",
  scopeOption: "w-full justify-start rounded-vui-control border border-vui-border-subtle bg-vui-surface-panel px-2.5 py-2",
  scopeOptionBody: "grid min-w-0 gap-0.5 text-left",
  scopeOptionTitle: "break-words text-vui-xs font-medium text-vui-fg-primary",
  scopeOptionDetail: "break-words text-vui-xs text-vui-fg-tertiary",
  scopeOptions: "grid min-w-0 gap-1.5",
  sourceHeading: "flex min-w-0 items-start gap-2",
  sourceIcon: "mt-1 hidden shrink-0 text-vui-fg-secondary @[480px]:!inline-flex",
  sourceTitle: "m-0 text-vui-sm font-semibold text-vui-fg-primary",
  sourceHint: "mb-0 mt-0.5 text-vui-xs leading-5 text-vui-fg-tertiary",
  ruleText: "m-0 text-vui-xs leading-5 text-vui-fg-secondary",
  triggerList: "col-span-2 flex min-w-0 flex-wrap items-center gap-x-3 gap-y-0 @[730px]:!col-span-3",
  inlineControls: "flex min-w-0 flex-wrap items-center gap-2",
  topicInput: "min-w-0 flex-1",
  topicList: "m-0 flex min-w-0 flex-wrap gap-1.5 p-0",
  listItem: "list-none",
  topicChip: "inline-flex max-w-full items-center gap-1",
  topicText: "min-w-0 max-w-[28rem] whitespace-normal break-words",
  cardHeading: "flex min-w-0 flex-wrap items-center justify-between gap-2 px-4 py-3",
  cardTitle: "text-vui-sm text-vui-fg-primary",
  runFailureHint: "m-0 px-4 pb-2 text-vui-xs text-vui-fg-secondary",
  runIdentifier: "break-all font-mono text-vui-xs",
  smallText: "text-vui-xs",
  detailText: "text-vui-xs text-vui-fg-secondary",
  mutedText: "text-vui-xs text-vui-fg-tertiary",
  hintText: "m-0 text-vui-xs text-vui-fg-tertiary",
  paragraph: "m-0 text-vui-xs text-vui-fg-secondary",
  usageRow: "flex flex-wrap gap-x-3 gap-y-1 text-vui-xs text-vui-fg-secondary",
  updateItem: "grid min-w-0 gap-1.5 border-t border-vui-border-subtle px-4 py-3 first:border-t-0",
  rowHeading: "flex min-w-0 flex-wrap items-center justify-between gap-2",
  itemTitle: "min-w-0 truncate text-vui-xs font-semibold text-vui-fg-primary",
  updateDetails: "grid min-w-0 gap-1 text-vui-xs text-vui-fg-secondary sm:grid-cols-2",
  breakAll: "break-all",
  updateLinks: "flex min-w-0 flex-wrap items-center gap-1 break-all",
  inlineDetails: "flex min-w-0 flex-wrap items-center gap-1 text-vui-xs",
  screenReader: "sr-only",
  sourceList: "m-0 grid min-w-0 gap-1 p-0",
  sourceItem: "flex min-w-0 list-none flex-wrap items-center justify-between gap-2 text-vui-xs",
  primaryText: "text-vui-fg-primary",
  tertiaryText: "text-vui-fg-tertiary",
  section: "border-t border-vui-border-subtle px-4 py-3",
  sectionHeading: "mb-2 flex min-w-0 flex-wrap items-center justify-between gap-2",
  linkedIdentifier: "break-all font-mono text-vui-fg-tertiary",
  updateList: "m-0 min-w-0 p-0",
  saveState: "text-vui-xs font-medium text-vui-fg-secondary",
  actions: "flex flex-wrap gap-2 max-[600px]:w-full max-[600px]:[&>button]:!min-h-11 max-[600px]:[&>button]:flex-1",
} as const;

export default styles;
