// Explicit style baseline (Phase 0, 2026-07-02 spec) — generated by
// web/scripts/bake-style-maps.ts from the previous createVuiStyleMap output;
// classes are byte-identical to what the inference produced. Every key is an
// explicit Tailwind class string; there are no name-based defaults. Edit
// values directly. This file is transitional: it is deleted in the wave that
// componentizes AppShell.
// Includes phantom keys accessed by consumers but never declared in the old
// styleKeys; the Proxy synthesized them on demand.
import {
  vuiControlIconSmClass,
  vuiControlPillClass,
  vuiControlQuietChromeClass,
  vuiControlQuietClass,
} from "../design/vuiChromeRecipes";

import {
  vuiGlassPanelClass,
  vuiOpaqueRowClass,
  vuiStateCoolInfoClass,
  vuiStateCoolSoftClass,
  vuiStateDangerSoftClass,
  vuiStateSelectedRowClass,
  vuiToolbarFillClass,
  vuiWorkspaceFillClass,
} from "../design/vuiSurfaceRecipes";

const styles = {
  actionButton:
    `vui-app-appshell actionButton min-w-0 flex flex-wrap items-center gap-1.5 ${vuiControlQuietChromeClass}`,
  actionIconButton:
    `vui-app-appshell actionIconButton !border-0 ${vuiControlIconSmClass}`,
  activeWorkChip:
    `vui-app-appshell activeWorkChip min-w-0 ${vuiControlPillClass} ${vuiStateCoolSoftClass} ` +
    "!inline-flex !h-8 !min-h-8 !max-h-8 max-w-[min(66vw,620px)] flex-nowrap !items-center !gap-1.5 !px-2.5 !py-0 " +
    "whitespace-nowrap leading-none text-[var(--fg-secondary)] [&>*]:!self-center " +
    "[&_strong]:text-[var(--fg-primary)] [&_strong]:font-semibold [&_strong]:leading-none",
  activeWorkDetailCopy:
    "vui-app-appshell activeWorkDetailCopy min-w-0 grid gap-1 [font-size:var(--vui-font-sm)] leading-[var(--vui-line-readable)] text-[var(--fg-secondary)] [&_p]:m-0 [&_p]:min-w-0 [&_p]:[overflow-wrap:anywhere] [&_code]:block [&_code]:min-w-0 [&_code]:truncate [&_code]:rounded-[var(--radius-control)] [&_code]:bg-[color-mix(in_srgb,var(--vui-control-muted)_88%,transparent)] [&_code]:px-1.5 [&_code]:py-0.5 [&_code]:[font-size:var(--vui-font-xs)] [&_code]:text-[var(--fg-tertiary)]",
  activeWorkDetailHeader:
    "vui-app-appshell activeWorkDetailHeader min-w-0 flex flex-wrap items-center justify-between gap-1.5 border-b border-[color-mix(in_srgb,var(--accent-cool)_22%,transparent)] px-0.5 pb-1.5 text-[var(--accent-cool)] [&_strong]:[font-size:var(--vui-font-sm)] [&_strong]:font-semibold [&_span]:[font-size:var(--vui-font-xs)] [&_span]:text-[var(--fg-tertiary)]",
  activeWorkDetailItem:
    "vui-app-appshell activeWorkDetailItem min-w-0 grid grid-cols-[max-content_minmax(0,1fr)] items-start gap-2 rounded-[var(--radius-control)] border border-[color-mix(in_srgb,var(--accent-cool)_18%,var(--vui-border-subtle))] bg-[var(--vui-surface-row)] px-2.5 py-2",
  activeWorkDetailList:
    "vui-app-appshell activeWorkDetailList m-0 grid min-h-0 max-h-[260px] list-none content-start gap-1.5 overflow-y-auto p-0",
  activeWorkDetailLink:
    "vui-app-appshell activeWorkDetailLink block min-w-0 rounded-[var(--radius-control)] text-inherit no-underline outline-none transition-colors hover:text-[var(--fg-primary)] focus-visible:ring-2 focus-visible:ring-[color-mix(in_srgb,var(--accent-cool)_45%,transparent)] focus-visible:ring-offset-2 focus-visible:ring-offset-[var(--vui-surface-panel)]",
  activeWorkDetailPanel:
    "vui-app-appshell activeWorkDetailPanel min-w-0 grid gap-2 p-2.5",
  activeWorkDetailTitle:
    "vui-app-appshell activeWorkDetailTitle min-w-0 [font-size:var(--vui-font-sm)] font-semibold leading-tight text-[var(--fg-primary)]",
  activeWorkInlineDetails:
    "vui-app-appshell activeWorkInlineDetails min-w-0",
  activeWorkInlineItem:
    "vui-app-appshell activeWorkInlineItem min-w-0",
  activeWorkItemToneChip:
    "vui-app-appshell activeWorkItemToneChip !min-h-5 max-w-[7rem] shrink-0 truncate !px-1.5 !text-[10px]",
  activeWorkKicker:
    "vui-app-appshell activeWorkKicker min-w-0 shrink-0 [font-size:var(--vui-font-xs)] font-medium text-[var(--fg-tertiary)]",
  activeWorkMore:
    "vui-app-appshell activeWorkMore min-w-0 shrink-0 [font-size:var(--vui-font-xs)] font-semibold text-[var(--accent-cool)]",
  activeWorkPopoverContent:
    "vui-app-appshell activeWorkPopoverContent z-[95] w-[min(420px,calc(100vw-2rem))] max-w-[min(420px,calc(100vw-2rem))] border-[color-mix(in_srgb,var(--accent-cool)_22%,var(--border-strong))] bg-[var(--shell-panel)] p-0 shadow-[var(--vui-shadow-soft)]",
  activeWorkStatus:
    "vui-app-appshell activeWorkStatus min-w-0 shrink-0 rounded-full border border-[color-mix(in_srgb,var(--state-warning)_28%,var(--vui-border-subtle))] bg-[color-mix(in_srgb,var(--state-warning)_10%,transparent)] px-1.5 py-0.5 [font-size:var(--vui-font-xs)] font-medium text-[var(--state-warning)]",
  activeWorkToneChip:
    "vui-app-appshell activeWorkToneChip !min-h-5 max-w-[6.5rem] shrink-0 truncate !px-1.5 !text-[10px]",
  activeWorkSummary: `vui-app-appshell activeWorkSummary min-w-0 ${vuiGlassPanelClass} p-2 ${vuiStateSelectedRowClass}`,
  brandBlock:
    "vui-app-appshell brandBlock min-w-0",
  brandGate:
    "vui-app-appshell brandGate min-w-0",
  // Git mini-panel styles live in AppShellUtilityMenu.styles (VUI composition).
  lifecycleMenuCluster:
    "vui-app-appshell lifecycleMenuCluster min-w-0",
  lifecycleMenuClusterOpen:
    `vui-app-appshell lifecycleMenuClusterOpen min-w-0 ${vuiStateCoolSoftClass}`,
  lifecycleMenuDangerItem: `vui-app-appshell lifecycleMenuDangerItem min-w-0 ${vuiOpaqueRowClass} p-2 ${vuiStateDangerSoftClass}`,
  lifecycleMenuItem: `vui-app-appshell lifecycleMenuItem min-w-0 ${vuiOpaqueRowClass} p-2`,
  lifecycleMenuPanel: `vui-app-appshell lifecycleMenuPanel min-w-0 ${vuiGlassPanelClass} p-2`,
  lifecycleProofCard: `vui-app-appshell lifecycleProofCard min-w-0 ${vuiGlassPanelClass} p-2`,
  lifecycleProofHeader:
    "vui-app-appshell lifecycleProofHeader min-w-0 flex flex-wrap items-center gap-1.5",
  lifecycleProofItem: `vui-app-appshell lifecycleProofItem min-w-0 ${vuiOpaqueRowClass} p-2`,
  lifecycleProofList:
    "vui-app-appshell lifecycleProofList min-w-0 grid min-h-0 content-start gap-1.5 overflow-auto",
  lifecycleProofMeta:
    "vui-app-appshell lifecycleProofMeta min-w-0 flex flex-wrap items-center gap-1.5",
  lifecycleProofName:
    "vui-app-appshell lifecycleProofName min-w-0 [font-size:var(--vui-font-title)] font-semibold leading-tight text-[var(--fg-primary)]",
  mainArea:
    "vui-app-appshell mainArea min-w-0 w-full",
  mobileNav: `vui-app-appshell mobileNav hidden max-[639px]:flex min-w-0 items-center rounded-[var(--radius-control)] border border-[var(--vui-border-subtle)] ${vuiToolbarFillClass} px-2 py-1`,
  mobileNavLabel:
    "vui-app-appshell mobileNavLabel min-w-0 truncate [font-size:var(--vui-font-sm)] font-semibold text-[var(--fg-primary)]",
  mobileRouteLink:
    "vui-app-appshell mobileRouteLink min-w-0 rounded-[var(--radius-control)] px-2 py-1.5 [font-size:var(--vui-font-sm)] font-semibold text-[var(--fg-secondary)] hover:bg-[var(--vui-control-muted-hover)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--accent-cool)]",
  mobileRouteLinkActive:
    `vui-app-appshell mobileRouteLinkActive ${vuiStateSelectedRowClass}`,
  mobileRouteMenu:
    "vui-app-appshell mobileRouteMenu hidden max-[639px]:grid min-w-0 w-full gap-1 rounded-[var(--vui-radius-panel-soft)] border border-[var(--vui-border-subtle)] bg-[var(--vui-surface-panel)] p-2",
  nav: `vui-app-appshell nav min-w-0 max-[639px]:hidden`,
  navLink:
    "vui-app-appshell navLink relative z-[2] inline-flex min-h-[30px] min-w-0 cursor-pointer items-center justify-center rounded-[var(--radius-control)] px-2.5 [font-size:var(--vui-font-sm)] font-semibold text-[var(--fg-primary)] no-underline select-none",
  navLinkActive:
    `vui-app-appshell navLinkActive relative z-[2] inline-flex min-h-[30px] min-w-0 cursor-pointer items-center justify-center rounded-[var(--radius-control)] border ${vuiStateSelectedRowClass} px-2.5 [font-size:var(--vui-font-sm)] font-semibold text-[var(--accent-cool)] no-underline select-none`,
  navLinkDisabled:
    "vui-app-appshell navLinkDisabled relative inline-flex min-h-[30px] min-w-0 cursor-not-allowed items-center justify-center rounded-[var(--radius-control)] px-2.5 [font-size:var(--vui-font-sm)] font-semibold text-[var(--fg-tertiary)] opacity-55 select-none pointer-events-none",
  returnButton:
    `vui-app-appshell returnButton min-w-0 ${vuiControlQuietClass}`,
  shell: `vui-app-appshell shell min-w-0 grid h-full min-h-0 content-start overflow-hidden ${vuiWorkspaceFillClass} text-[var(--fg-primary)]`,
  shutdownCancelButton:
    `vui-app-appshell shutdownCancelButton min-w-0 ${vuiControlQuietClass}`,
  shutdownCopy:
    "vui-app-appshell shutdownCopy min-w-0 [font-size:var(--vui-font-sm)] leading-[var(--vui-line-readable)] text-[var(--fg-secondary)]",
  shutdownIconSpin:
    "vui-app-appshell shutdownIconSpin min-w-0 shrink-0 text-[var(--fg-tertiary)] animate-spin",
  shutdownIconStill:
    "vui-app-appshell shutdownIconStill min-w-0 shrink-0 text-[var(--fg-tertiary)]",
  shutdownOverlay:
    "vui-app-appshell shutdownOverlay min-w-0",
  shutdownPanel: `vui-app-appshell shutdownPanel min-w-0 ${vuiGlassPanelClass} p-2`,
  startupCopy:
    "vui-app-appshell startupCopy min-w-0 [font-size:var(--vui-font-sm)] leading-[var(--vui-line-readable)] text-[var(--fg-secondary)]",
  startupKicker:
    "vui-app-appshell startupKicker min-w-0",
  startupOverlay:
    "vui-app-appshell startupOverlay min-w-0",
  startupPanel: `vui-app-appshell startupPanel min-w-0 ${vuiGlassPanelClass} p-2`,
  startupSpinner:
    "vui-app-appshell startupSpinner min-w-0 animate-spin",
  statusBadge:
    `vui-app-appshell statusBadge min-w-0 ${vuiControlPillClass}`,
  statusBadgeLabel:
    "vui-app-appshell statusBadgeLabel inline-flex min-w-0 shrink-0 items-center [font-size:var(--vui-font-xs)] font-semibold leading-none text-[var(--fg-tertiary)] whitespace-nowrap",
  statusBadgeValue:
    "vui-app-appshell statusBadgeValue inline-flex min-w-0 shrink-0 items-center [font-size:var(--vui-font-xs)] font-semibold leading-none text-[var(--fg-primary)] whitespace-nowrap",
  statusChipRow: `vui-app-appshell statusChipRow min-w-0 ${vuiOpaqueRowClass} p-2`,
  statusCluster:
    "vui-app-appshell statusCluster min-w-0 shrink-0",
  // Fixed square + flex-none: no border/baseline so dots share the pill mid-line with text.
  statusDot:
    "vui-app-appshell statusDot block h-2 w-2 shrink-0 grow-0 self-center rounded-full border-0 bg-current p-0 leading-none",
  statusGuideCard: `vui-app-appshell statusGuideCard min-w-0 ${vuiGlassPanelClass} p-2`,
  statusGuideCardHeader:
    "vui-app-appshell statusGuideCardHeader min-w-0 flex flex-wrap items-center gap-1.5 px-0.5 pb-1",
  statusGuideGrid:
    "vui-app-appshell statusGuideGrid min-w-0 grid gap-2 grid-cols-[repeat(auto-fit,minmax(9rem,1fr))]",
  statusGuideHeader:
    "vui-app-appshell statusGuideHeader min-w-0 flex flex-wrap items-center gap-1.5",
  statusGuideList:
    "vui-app-appshell statusGuideList min-w-0 grid min-h-0 content-start gap-1.5 overflow-auto",
  statusGuideListItem: `vui-app-appshell statusGuideListItem min-w-0 grid min-h-0 content-start gap-1.5 overflow-auto ${vuiOpaqueRowClass} p-2`,
  statusGuidePanel: `vui-app-appshell statusGuidePanel min-w-0 ${vuiGlassPanelClass} p-2`,
  statusGuidePopoverContent:
    "vui-app-appshell statusGuidePopoverContent z-[95] w-[min(640px,calc(100vw-40px))] max-w-[min(640px,calc(100vw-40px))] border-[var(--border-strong)] bg-[var(--shell-panel)] p-0 shadow-[var(--vui-shadow-soft)]",
  statusGuideStateLabel:
    "vui-app-appshell statusGuideStateLabel min-w-0 [font-size:var(--vui-font-xs)] leading-tight text-[var(--fg-tertiary)]",
  // Rigid pill geometry: fixed height, zero vertical padding, shared leading-none mid-line.
  statusSummaryChip:
    "vui-app-appshell statusSummaryChip min-w-0 " +
    "!inline-flex !h-8 !min-h-8 !max-h-8 !border-0 flex-nowrap !items-center !justify-center !gap-1.5 !px-2.5 !py-0 " +
    "whitespace-nowrap leading-none [&>*]:!self-center [&>*]:leading-none",
  statusSummaryDot:
    "vui-app-appshell statusSummaryDot block h-1.5 w-1.5 shrink-0 grow-0 self-center rounded-full border-0 bg-current p-0 leading-none",
  statusSummaryLabel:
    "vui-app-appshell statusSummaryLabel min-w-0 max-w-[12rem] truncate [font-size:var(--vui-font-xs)] font-semibold leading-none text-[var(--fg-primary)] whitespace-nowrap",
  status_active:
    `vui-app-appshell status_active min-w-0 ${vuiStateSelectedRowClass}`,
  status_blocked:
    "vui-app-appshell status_blocked min-w-0 border-[color-mix(in_srgb,var(--state-warning)_36%,transparent)] bg-[color-mix(in_srgb,var(--state-warning)_10%,transparent)] text-[var(--state-warning)]",
  status_caution:
    "vui-app-appshell status_caution text-[var(--state-warning)]",
  status_danger:
    `vui-app-appshell status_danger min-w-0 ${vuiStateDangerSoftClass}`,
  status_done:
    "vui-app-appshell status_done min-w-0",
  status_error:
    `vui-app-appshell status_error min-w-0 ${vuiStateDangerSoftClass}`,
  status_failed:
    "vui-app-appshell status_failed text-[var(--state-error)]",
  status_idle:
    "vui-app-appshell status_idle text-[color-mix(in_srgb,var(--fg-tertiary)_74%,transparent)]",
  status_info:
    `vui-app-appshell status_info min-w-0 ${vuiStateCoolInfoClass}`,
  status_mental:
    "vui-app-appshell status_mental min-w-0",
  status_missing:
    "vui-app-appshell status_missing min-w-0",
  status_muted:
    "vui-app-appshell status_muted min-w-0 [font-size:var(--vui-font-xs)] leading-tight text-[var(--fg-tertiary)]",
  status_neutral:
    "vui-app-appshell status_neutral min-w-0",
  status_ok:
    "vui-app-appshell status_ok min-w-0 border-[color-mix(in_srgb,var(--state-success)_32%,transparent)] bg-[color-mix(in_srgb,var(--state-success)_9%,transparent)] text-[var(--state-success)]",
  status_pending:
    "vui-app-appshell status_pending min-w-0",
  status_ready:
    "vui-app-appshell status_ready min-w-0 border-[color-mix(in_srgb,var(--state-success)_32%,transparent)] bg-[color-mix(in_srgb,var(--state-success)_9%,transparent)] text-[var(--state-success)]",
  status_running:
    "vui-app-appshell status_running text-[var(--state-success)]",
  status_status:
    "vui-app-appshell status_status min-w-0",
  status_success:
    "vui-app-appshell status_success min-w-0 border-[color-mix(in_srgb,var(--state-success)_32%,transparent)] bg-[color-mix(in_srgb,var(--state-success)_9%,transparent)] text-[var(--state-success)]",
  status_thought:
    "vui-app-appshell status_thought min-w-0",
  status_warn:
    "vui-app-appshell status_warn min-w-0",
  status_warning:
    "vui-app-appshell status_warning min-w-0 border-[color-mix(in_srgb,var(--state-warning)_36%,transparent)] bg-[color-mix(in_srgb,var(--state-warning)_10%,transparent)] text-[var(--state-warning)]",
  toolCluster:
    "vui-app-appshell toolCluster min-w-0 shrink-0 flex flex-nowrap items-center gap-1.5",
  topActions: "vui-app-appshell topActions min-w-0 flex flex-nowrap items-center gap-3.5",
  // Display/layout + Electron drag policy for topBar live in workbench-shell.css.
  // Do not add Tailwind flex/grid or pointer-events here — they fight the fixed 3-column grid / hit targets.
  topBar:
    "vui-app-appshell topBar min-w-0",
  topBarRestoreButton:
    "vui-app-appshell topBarRestoreButton min-w-0 flex flex-wrap items-center gap-1.5 inline-flex min-h-[var(--vui-control-height-sm)] w-fit max-w-full justify-center rounded-[var(--radius-control)] border border-[var(--vui-border-subtle)] bg-[var(--vui-control-muted)] px-2 py-1 [font-size:var(--vui-font-xs)] font-semibold leading-tight text-[var(--fg-secondary)] hover:border-[var(--vui-control-hover-border)] hover:bg-[var(--vui-control-hover-bg)] hover:text-[var(--vui-control-hover-fg)] disabled:cursor-default disabled:opacity-55",
  utilityButton:
    `vui-app-appshell utilityButton min-w-0 w-full max-w-full ${vuiControlQuietChromeClass} hover:border-[var(--vui-control-hover-border)] hover:bg-[var(--vui-control-hover-bg)] hover:text-[var(--vui-control-hover-fg)]`,
  utilityButtonActive:
    `vui-app-appshell utilityButtonActive min-w-0 ${vuiStateSelectedRowClass}`,
  utilityButtonGrid:
    "vui-app-appshell utilityButtonGrid min-w-0",
  utilityChevron:
    "vui-app-appshell utilityChevron min-w-0",
  utilityCluster:
    "vui-app-appshell utilityCluster relative min-w-0 shrink-0",
  utilityClusterOpen:
    "vui-app-appshell utilityClusterOpen min-w-0",
  utilityPopoverContent:
    "vui-app-appshell utilityPopoverContent z-[95] w-[min(520px,calc(100vw-40px))] max-h-[min(78vh,760px)] overflow-auto border-[var(--border-strong)] bg-[var(--shell-panel)] p-0 shadow-[var(--vui-shadow-soft)]",
  utilityPopoverBody:
    "vui-app-appshell utilityPopoverBody grid min-w-0 gap-2 p-2",
  utilityFileButton:
    `vui-app-appshell utilityFileButton min-w-0 ${vuiControlQuietClass} grid [&_[data-slot=vui-button-content]]:w-full [&_[data-slot=vui-button-label]]:grid [&_[data-slot=vui-button-label]]:w-full [&_[data-slot=vui-button-label]]:grid-cols-[minmax(0,1fr)_auto] [&_[data-slot=vui-button-label]]:items-center [&_[data-slot=vui-button-label]]:gap-2`,
  utilityFileButtonActive:
    `vui-app-appshell utilityFileButtonActive min-w-0 ${vuiStateSelectedRowClass} grid [&_[data-slot=vui-button-content]]:w-full [&_[data-slot=vui-button-label]]:grid [&_[data-slot=vui-button-label]]:w-full [&_[data-slot=vui-button-label]]:grid-cols-[minmax(0,1fr)_auto] [&_[data-slot=vui-button-label]]:items-center [&_[data-slot=vui-button-label]]:gap-2`,
  utilityFileChildren:
    "vui-app-appshell utilityFileChildren min-w-0",
  utilityFileDir:
    "vui-app-appshell utilityFileDir min-w-0",
  utilityFileHeader:
    "vui-app-appshell utilityFileHeader min-w-0 flex flex-wrap items-center gap-1.5",
  utilityFilePanel: `vui-app-appshell utilityFilePanel min-w-0 ${vuiGlassPanelClass} p-2`,
  utilityFileSearch:
    "vui-app-appshell utilityFileSearch min-w-0",
  utilityFileState:
    "vui-app-appshell utilityFileState min-w-0",
  utilityFileTree:
    "vui-app-appshell utilityFileTree min-w-0 grid min-h-0 content-start gap-1.5 overflow-auto",
  utilityPanel: `vui-app-appshell utilityPanel min-w-0 ${vuiGlassPanelClass} p-2`,
  utilityPanelHeader:
    "vui-app-appshell utilityPanelHeader min-w-0 flex flex-wrap items-center gap-1.5 px-0.5 pb-1",
  utilityTrigger:
    "vui-app-appshell utilityTrigger min-w-0 h-[var(--vui-control-height-sm)] !border-0 flex-nowrap [&_[data-slot=vui-button-content]]:flex-nowrap [&_[data-slot=vui-button-content]]:whitespace-nowrap [&_[data-slot=vui-button-icon]]:shrink-0 [&_[data-slot=vui-button-label]]:inline-flex [&_[data-slot=vui-button-label]]:items-center [&_[data-slot=vui-button-label]]:gap-1.5 [&_[data-slot=vui-button-label]]:whitespace-nowrap [&_[data-slot=vui-button-trailing-icon]]:shrink-0",
  utilityTriggerLabel:
    "vui-app-appshell utilityTriggerLabel min-w-0 [font-size:var(--vui-font-xs)] leading-tight text-[var(--fg-tertiary)] whitespace-nowrap",
} as const;

export default styles;
