import { createVuiStyleMap } from "../components/vui/styles/createVuiStyleMap";

const styleKeys = [
  "actionButton",
  "actionIconButton",
  "activeWorkChip",
  "activeWorkDetailCopy",
  "activeWorkDetailHeader",
  "activeWorkDetailItem",
  "activeWorkDetailList",
  "activeWorkDetailPanel",
  "activeWorkDetailTitle",
  "activeWorkKicker",
  "activeWorkMore",
  "activeWorkStatus",
  "brand",
  "brandBlock",
  "brandCopy",
  "brandSubtle",
  "gitBranchName",
  "gitChip",
  "gitCommitItem",
  "gitCommitList",
  "gitCount",
  "gitCountGrid",
  "gitFileItem",
  "gitFileList",
  "gitHeadline",
  "gitMetaGrid",
  "gitMiniHeader",
  "gitMiniPanel",
  "gitQuietState",
  "gitSection",
  "gitSectionHeader",
  "gitSignalGrid",
  "gitWorktreeItem",
  "gitWorktreeList",
  "lifecycleMenuCluster",
  "lifecycleMenuClusterOpen",
  "lifecycleMenuDangerItem",
  "lifecycleMenuItem",
  "lifecycleMenuPanel",
  "lifecycleProofCard",
  "lifecycleProofHeader",
  "lifecycleProofItem",
  "lifecycleProofList",
  "lifecycleProofMeta",
  "lifecycleProofName",
  "mainArea",
  "nav",
  "navLink",
  "navLinkActive",
  "navLinkDisabled",
  "returnButton",
  "shell",
  "shutdownCancelButton",
  "shutdownCopy",
  "shutdownIconSpin",
  "shutdownIconStill",
  "shutdownOverlay",
  "shutdownPanel",
  "startupCopy",
  "startupKicker",
  "startupOverlay",
  "startupPanel",
  "startupSpinner",
  "status_caution",
  "status_failed",
  "status_idle",
  "status_running",
  "statusBadge",
  "statusBadgeLabel",
  "statusBadgeValue",
  "statusChipRow",
  "statusCluster",
  "statusDot",
  "statusGuideCard",
  "statusGuideCardHeader",
  "statusGuideGrid",
  "statusGuideHeader",
  "statusGuideList",
  "statusGuideListItem",
  "statusGuidePanel",
  "statusGuideStateLabel",
  "statusSummaryChip",
  "statusSummaryCount",
  "topActions",
  "topBar",
  "topBarRestoreButton",
  "topClock",
  "utilityButton",
  "utilityButtonActive",
  "utilityButtonGrid",
  "utilityChevron",
  "utilityCluster",
  "utilityClusterOpen",
  "utilityFileButton",
  "utilityFileButtonActive",
  "utilityFileChildren",
  "utilityFileDir",
  "utilityFileHeader",
  "utilityFilePanel",
  "utilityFileSearch",
  "utilityFileState",
  "utilityFileTree",
  "utilityPanel",
  "utilityPanelHeader",
  "utilityTrigger",
  "utilityTriggerLabel",
  "versionPill",
] as const;

const styles = createVuiStyleMap(styleKeys, {
  baseClassName: "vui-app-appshell",
  includeKeyClass: true,
  overrides: {
    status_caution: "text-[var(--state-warning)]",
    status_failed: "text-[var(--state-error)]",
    status_idle: "text-[color-mix(in_srgb,var(--fg-tertiary)_74%,transparent)]",
    status_running: "text-[var(--state-success)]",
    statusDot:
      "inline-block h-2 w-2 shrink-0 rounded-full border border-[color-mix(in_srgb,currentColor_38%,transparent)] bg-current p-0 align-middle",
  },
  extensions: {
    statusBadgeLabel: "whitespace-nowrap",
    statusBadgeValue: "whitespace-nowrap",
    statusCluster: "shrink-0",
    statusSummaryChip: "h-8 min-h-8 flex-nowrap gap-1.5 whitespace-nowrap",
    topClock: "flex shrink-0 items-center gap-1.5 whitespace-nowrap text-[var(--vui-font-xs)] leading-none text-[var(--fg-secondary)]",
    topActions: "min-w-0 flex-nowrap",
    utilityCluster: "shrink-0",
    utilityFileButton:
      "[&_[data-slot=vui-button-content]]:w-full [&_[data-slot=vui-button-label]]:grid [&_[data-slot=vui-button-label]]:w-full [&_[data-slot=vui-button-label]]:grid-cols-[minmax(0,1fr)_auto] [&_[data-slot=vui-button-label]]:items-center [&_[data-slot=vui-button-label]]:gap-2",
    utilityFileButtonActive:
      "[&_[data-slot=vui-button-content]]:w-full [&_[data-slot=vui-button-label]]:grid [&_[data-slot=vui-button-label]]:w-full [&_[data-slot=vui-button-label]]:grid-cols-[minmax(0,1fr)_auto] [&_[data-slot=vui-button-label]]:items-center [&_[data-slot=vui-button-label]]:gap-2",
    utilityTrigger:
      "h-8 min-h-8 flex-nowrap [&_[data-slot=vui-button-content]]:flex-nowrap [&_[data-slot=vui-button-content]]:whitespace-nowrap [&_[data-slot=vui-button-icon]]:shrink-0 [&_[data-slot=vui-button-label]]:inline-flex [&_[data-slot=vui-button-label]]:items-center [&_[data-slot=vui-button-label]]:gap-1.5 [&_[data-slot=vui-button-label]]:whitespace-nowrap [&_[data-slot=vui-button-trailing-icon]]:shrink-0",
    utilityTriggerLabel: "whitespace-nowrap",
  },
});

export default styles;
