import {
  vuiFlatPanelClass,
} from "../design/vuiSurfaceRecipes";

const styles = {
  surface: "grid min-h-[min(520px,calc(100dvh_-_96px))] w-full p-3 sm:p-4",
  surfaceDefault: "place-items-center",
  surfaceStructured: "content-start",
  panel: [
    "w-[min(360px,100%)] rounded-[var(--radius-panel)] border border-vui-border-subtle bg-vui-surface-glass",
    "px-[18px] py-4 text-vui-fg-primary shadow-none backdrop-blur-md",
  ].join(" "),
  structuredPanel: [
    "grid min-h-[min(540px,calc(100dvh_-_120px))] w-full gap-3 overflow-auto rounded-[var(--radius-panel)] md:overflow-hidden",
    "border border-vui-border-subtle bg-vui-surface-panel p-3 text-vui-fg-primary shadow-none",
  ].join(" "),
  loadingHeader: "flex min-w-0 items-center gap-2.5",
  spinnerFrame: [
    "grid size-8 shrink-0 place-items-center rounded-[var(--radius-control)] border",
    "border-[color-mix(in_srgb,var(--accent-cool)_28%,var(--vui-border-subtle))] bg-[color-mix(in_srgb,var(--accent-cool)_8%,var(--vui-surface-row))] text-[var(--accent-cool)]",
  ].join(" "),
  spinner: "animate-spin motion-reduce:animate-none",
  loadingCopy: "grid min-w-0 gap-0.5",
  title: "block [font-size:var(--vui-font-chat)] font-bold leading-[1.35]",
  meta: "block [font-size:var(--vui-font-xs)] leading-[1.35] text-vui-fg-tertiary",
  skeletonLine: [
    "block h-2.5 w-full max-w-[340px] animate-pulse rounded-full",
    "bg-[color-mix(in_srgb,var(--accent-cool)_18%,var(--vui-border-subtle))] motion-reduce:animate-none",
  ].join(" "),
  skeletonLineCompact: [
    "block h-2.5 w-[58%] max-w-[210px] animate-pulse rounded-full",
    "bg-[color-mix(in_srgb,var(--accent-cool)_18%,var(--vui-border-subtle))] motion-reduce:animate-none",
  ].join(" "),
  configGrid: "grid min-h-0 grid-cols-1 gap-3 md:grid-cols-[minmax(168px,0.24fr)_minmax(0,1fr)]",
  chatGrid: "grid min-h-0 flex-1 gap-2 md:grid-cols-[minmax(240px,300px)_minmax(0,1fr)]",
  chatIndexPanel: "grid min-h-0 content-start gap-2 overflow-hidden rounded-[var(--radius-control)] border border-vui-border-subtle bg-vui-surface-row p-2.5",
  chatSearch: "block h-8 animate-pulse rounded-[var(--radius-control)] border border-vui-border-subtle bg-vui-surface-panel motion-reduce:animate-none",
  chatActions: "grid grid-cols-2 gap-2 [&_span]:h-8 [&_span]:animate-pulse [&_span]:rounded-[var(--radius-control)] [&_span]:bg-[color-mix(in_srgb,var(--accent-cool)_13%,var(--vui-border-subtle))] motion-reduce:[&_span]:animate-none",
  chatIndexGroup: "grid gap-1.5 rounded-[var(--radius-control)] border border-vui-border-subtle bg-vui-surface-panel p-1.5",
  chatGroupHeading: "flex min-h-6 items-center justify-between gap-2 px-1",
  chatGroupCount: "block size-4 animate-pulse rounded-full bg-[color-mix(in_srgb,var(--accent-cool)_18%,var(--vui-border-subtle))] motion-reduce:animate-none",
  chatIndexRow: "grid min-h-11 grid-cols-[28px_minmax(0,1fr)] items-center gap-2 px-1",
  chatAvatar: "block size-7 shrink-0 animate-pulse rounded-full bg-[color-mix(in_srgb,var(--accent-cool)_18%,var(--vui-border-subtle))] motion-reduce:animate-none",
  chatIndexCopy: "grid min-w-0 gap-2",
  chatWorkspace: `grid min-h-[390px] grid-rows-[minmax(0,1fr)_auto] overflow-hidden rounded-[var(--radius-control)] border border-vui-border-subtle ${vuiFlatPanelClass}`,
  chatTranscript: "grid content-start gap-7 overflow-hidden px-[clamp(18px,7vw,100px)] py-7",
  chatMessage: "grid max-w-[720px] grid-cols-[28px_minmax(0,1fr)] items-start gap-3",
  chatMessageCopy: "grid min-w-0 gap-2 pt-1",
  chatComposer: `mx-auto mb-3 grid w-[min(calc(100%_-_28px),900px)] gap-2 ${vuiFlatPanelClass} p-3 shadow-[var(--vui-shadow-hairline)]`,
  chatComposerInput: "block h-10 animate-pulse rounded-[var(--radius-control)] bg-[color-mix(in_srgb,var(--accent-cool)_12%,var(--vui-surface-row))] motion-reduce:animate-none",
  chatComposerToolbar: "flex items-center justify-between [&_span]:block [&_span]:h-6 [&_span]:w-20 [&_span]:animate-pulse [&_span]:rounded-full [&_span]:bg-[color-mix(in_srgb,var(--accent-cool)_16%,var(--vui-border-subtle))] motion-reduce:[&_span]:animate-none",
  navigationPanel: [
    "grid content-start gap-2 rounded-[var(--radius-control)] border border-vui-border-subtle",
    "bg-vui-surface-row p-2.5",
  ].join(" "),
  navigationRow: "block h-8 rounded-[var(--radius-control)] border border-vui-border-subtle bg-vui-surface-panel",
  navigationRowActive: [
    "block h-8 rounded-[var(--radius-control)] border",
    "border-[color-mix(in_srgb,var(--accent-cool)_32%,var(--vui-border-subtle))] bg-[color-mix(in_srgb,var(--accent-cool)_9%,var(--vui-surface-row))]",
  ].join(" "),
  contentPanel: "grid min-h-0 content-start gap-3 rounded-[var(--radius-control)] border border-vui-border-subtle bg-vui-surface-row p-3",
  sectionHeading: "flex min-w-0 items-start justify-between gap-3 border-b border-vui-border-subtle pb-3",
  headingCopy: "grid min-w-0 flex-1 gap-2",
  headingAction: "block h-8 w-20 shrink-0 rounded-[var(--radius-control)] border border-vui-border-subtle bg-vui-surface-panel",
  configCards: "grid min-w-0 grid-cols-1 gap-2 sm:grid-cols-2",
  configCard: "grid min-h-28 content-start gap-3 rounded-[var(--radius-control)] border border-vui-border-subtle bg-vui-surface-panel p-3",
  teamsStack: "grid min-h-0 gap-3",
  statusStrip: "grid grid-cols-2 gap-2 sm:grid-cols-4",
  statusItem: "grid h-10 content-center rounded-[var(--radius-control)] border border-vui-border-subtle bg-vui-surface-row px-2.5",
  teamsGrid: "grid min-h-0 grid-cols-1 gap-3 lg:grid-cols-[minmax(0,1fr)_minmax(250px,0.32fr)]",
  canvasPanel: "grid min-h-[390px] content-start gap-3 rounded-[var(--radius-control)] border border-vui-border-subtle bg-vui-surface-row p-3",
  canvasBoard: [
    "grid min-h-[300px] grid-cols-2 content-center items-center gap-3 rounded-[var(--radius-control)] border border-dashed",
    "border-vui-border-subtle !bg-[var(--vui-surface-panel)] p-4 sm:grid-cols-3",
  ].join(" "),
  canvasNode: "flex min-w-0 items-center gap-2 rounded-[var(--radius-control)] border border-vui-border-subtle bg-vui-surface-panel p-2.5",
  nodeAvatar: "block size-8 shrink-0 animate-pulse rounded-full bg-[color-mix(in_srgb,var(--accent-cool)_18%,var(--vui-border-subtle))] motion-reduce:animate-none",
  nodeCopy: "grid min-w-0 flex-1 gap-2",
  inspectorPanel: "grid min-h-[240px] content-start gap-3 rounded-[var(--radius-control)] border border-vui-border-subtle bg-vui-surface-row p-3",
  inspectorRow: "grid gap-2 rounded-[var(--radius-control)] border border-vui-border-subtle bg-vui-surface-panel p-2.5",
} as const;

export default styles;
