import { createContext } from "react";

/**
 * Generated by VFieldRow so child form controls can pick up an accessible
 * name via `htmlFor` without every call site passing an explicit id.
 */
export const FieldRowIdContext = createContext<string | undefined>(undefined);
