import { createVuiStyleMap } from "../vui/styles/createVuiStyleMap";

const styleKeys = [
  "agentInboxMessageBody",
  "agentInboxPreview",
  "agentInboxSection",
  "agentInboxToggle",
  "agentInboxTurn",
  "answerOnlyProcessDetails",
  "answerOnlyProcessGroup",
  "answerOnlyProcessGroup_failed",
  "answerOnlyProcessIcon",
  "answerOnlyProcessMeta",
  "answerOnlyProcessPreview",
  "answerOnlyProcessStatic",
  "answerOnlyProcessTitle",
  "answerOnlyProcessToggle",
  "assistantCard",
  "assistantTurn",
  "assistantTurnContinuation",
  "attachButton",
  "auxiliaryBlock",
  "auxiliaryBlock_mental",
  "auxiliaryPanel",
  "auxiliaryPanel_mental",
  "auxiliaryPanel_thought",
  "backToBottomButton",
  "cliAgentLifecycleIcon",
  "cliAgentLifecycleMeta",
  "cliAgentLifecycleText",
  "cliAgentLifecycleTime",
  "cliAgentLifecycleTurn",
  "composer",
  "composerAttachmentChip",
  "composerAttachmentTray",
  "composerError",
  "composerField",
  "composerFieldDragActive",
  "composerGuidance",
  "composerGuidanceIcon",
  "composerModeNotice",
  "composerModeNoticeIcon",
  "composerReferenceChip",
  "composerReferenceCopy",
  "composerReferenceIcon",
  "composerReferenceTray",
  "composerRoundButton",
  "composerRoundButtonPrimary",
  "computerUseActions",
  "computerUseError",
  "computerUseHeader",
  "computerUsePanel",
  "computerUseScreenshot",
  "computerUseSteps",
  "computerUseSummary",
  "conversationCellTimeline",
  "emptyState",
  "executionRequestSummary",
  "executionTraceGroup",
  "eyebrow",
  "groupTranscriptBody",
  "groupTranscriptTurn",
  "header",
  "headerControls",
  "hiddenAttachmentInput",
  "imageArtifact",
  "imageArtifactFooter",
  "imageArtifactFrame",
  "imageArtifactMeta",
  "imageArtifactPrompt",
  "imageDownloadButton",
  "imagePreview",
  "imagePreviewActions",
  "imagePreviewButton",
  "imagePreviewCloseButton",
  "imagePreviewDialog",
  "imagePreviewLarge",
  "imagePreviewOverlay",
  "imagePreviewToolbar",
  "inlineCode",
  "inlineLink",
  "inlineStrong",
  "input",
  "markdownBlockquote",
  "markdownBody",
  "markdownBodyWithTable",
  "markdownDivider",
  "markdownHeading",
  "markdownHeading1",
  "markdownHeading2",
  "markdownHeading3",
  "markdownHeading4",
  "markdownImage",
  "markdownImageCaption",
  "markdownImageFigure",
  "markdownImageLink",
  "markdownTable",
  "markdownTableWrap",
  "mentalBodyList",
  "mentalBodyRow",
  "mentalIntervention",
  "mentalMetaGrid",
  "mentalMetaItem",
  "mentalSnapshot",
  "mentalSummary",
  "mentalWhisper",
  "messageBody",
  "messageCard",
  "messageMeta",
  "metaStack",
  "nextStateSignalEvent",
  "nextStateSignalItem",
  "nextStateSignalKind",
  "nextStateSignalList",
  "nextStateSignalMeta",
  "nextStateSignals",
  "nextStateSignalsCount",
  "nextStateSignalsSummary",
  "nextStateSignalsToggle",
  "nextStateSignalText",
  "operationChevron",
  "operationDetailLabel",
  "operationDetailRow",
  "operationDetails",
  "operationDetails_thought",
  "operationDetailToggle",
  "operationDetailValue",
  "operationDuration",
  "operationGroup",
  "operationIcon",
  "operationIcon_mental",
  "operationIcon_thought",
  "operationIcon_tool",
  "operationItem",
  "operationItem_status",
  "operationItem_thought",
  "operationItem_tool",
  "operationItemActive",
  "operationItemTool",
  "operationItemWrap",
  "operationName",
  "operationStatus",
  "operationStatusLead",
  "operationStatusLine",
  "operationStatusMeta",
  "operationSummary",
  "operationSummaryCount",
  "operationSummaryPreview",
  "operationSummaryText",
  "operationText",
  "operationTimeline",
  "operationTimelineTrimmed",
  "phase",
  "reActOperationBody",
  "reActOperationGroup",
  "reActOperationGroup_done",
  "reActOperationGroup_failed",
  "reActOperationGroup_pending",
  "reActOperationGroup_running",
  "reActOperationList",
  "reActOperationMeta",
  "reActOperationSection",
  "reActOperationSectionLabel",
  "reActOperationSummary",
  "reActOperationTitle",
  "reActResultItem",
  "reActResultItem_failed",
  "reActResultLabel",
  "reActResultList",
  "reActResultToggle",
  "reActResultValue",
  "reActThoughtStack",
  "reActThoughtText",
  "reActToolDetailToggle",
  "reActToolItem",
  "reActToolLine",
  "reActToolList",
  "reActToolName",
  "reActToolStatus",
  "reActToolSummary",
  "researchOrgChip",
  "researchOrgChip_intent",
  "researchOrgChip_meta",
  "researchOrgChip_wake",
  "researchOrgChipRow",
  "responseBlock",
  "responseBody",
  "responseLabel",
  "responseSection",
  "responseSegment",
  "responseSegment_answer",
  "responseSegment_code",
  "responseSegment_commit",
  "responseSegment_files",
  "responseSegment_logs",
  "responseSegment_status",
  "responseSegment_verification",
  "responseSegmentHeader",
  "responseSegmentLabel",
  "responseSegmentList",
  "responseSegmentMeta",
  "responseSegmentPre",
  "responseToggle",
  "sectionBlock",
  "sectionPanel",
  "sectionToggle",
  "sendButton",
  "sessionMeta",
  "statPill",
  "statRow",
  "statusRunningDot",
  "statusSpinner",
  "stopButton",
  "streamingCodeBlock",
  "streamingResponseText",
  "summaryCard",
  "summaryGrid",
  "summaryLabel",
  "summaryValue",
  "supplemental",
  "surface",
  "surfaceCompact",
  "thoughtMetaPill",
  "thoughtMetaRow",
  "thoughtSectionHeader",
  "thoughtSectionLabel",
  "thoughtText",
  "thoughtTextBlock",
  "timeline",
  "timelineAssistantTextCell",
  "timelineCellDetailButton",
  "timelineCellHeader",
  "timelineCellMeta",
  "timelineCellPreview",
  "timelineCommandError",
  "timelineCommandList",
  "timelineCommandRow",
  "timelineHistoryButton",
  "timelineHistoryGate",
  "timelineOperationCell",
  "timelineOperationCell_failed",
  "timelineOperationResult",
  "timelineThoughtCell",
  "timelineThoughtText",
  "title",
  "toolPill",
  "toolRow",
  "toolsBlock",
  "toolsLabel",
  "turnAvatar",
  "turnAvatarImage",
  "turnContent",
  "turnEditBadge",
  "turnEditing",
  "turnError",
  "turnErrorDetail",
  "turnErrorLabel",
  "turnErrorNotice",
  "turnErrorNoticeBody",
  "turnErrorNoticeIcon",
  "turnErrorNoticeMeta",
  "turnErrorNoticeText",
  "turnErrorReasonList",
  "turnErrorReasonRow",
  "turnErrorText",
  "turnErrorType",
  "turnIconButton",
  "turnIconButtonActive",
  "turnMeta",
  "turnMetaActions",
  "turnMetaIdentity",
  "turnSpeaker",
  "updateLine",
  "userAttachment",
  "userAttachmentGrid",
  "userAttachmentImage",
  "userAttachmentMeta",
  "userCard",
  "userMessageBody",
  "userTurn",
] as const;

const styles = createVuiStyleMap(styleKeys, {
  baseClassName: "vui-components-conversationview",
  extensions: {
    answerOnlyProcessStatic:
      "[&_[data-slot=vui-button-label]]:grid [&_[data-slot=vui-button-label]]:grid-cols-[14px_auto_auto] [&_[data-slot=vui-button-label]]:items-center [&_[data-slot=vui-button-label]]:gap-1.5",
    answerOnlyProcessToggle:
      "border-0 bg-transparent p-0 text-[var(--fg-secondary)] hover:border-transparent hover:bg-transparent [&_[data-slot=vui-button-content]]:contents [&_[data-slot=vui-button-label]]:inline-grid [&_[data-slot=vui-button-label]]:max-w-full [&_[data-slot=vui-button-label]]:grid-cols-[14px_auto_auto_minmax(0,1fr)_14px] [&_[data-slot=vui-button-label]]:items-center [&_[data-slot=vui-button-label]]:gap-1.5",
    agentInboxTurn: "[&_.turnContent]:w-[min(100%,920px)] [&_.turnContent]:p-0 [&_.turnContent]:border-l-0",
    assistantTurn: "[&_.turnContent]:w-[min(100%,920px)] [&_.turnContent]:p-0 [&_.turnContent]:border-l-0",
    cliAgentLifecycleMeta: "[&_time]:flex-none",
    cliAgentLifecycleTurn: "bg-[color-mix(in_srgb,var(--surface-panel)_72%,transparent)]",
    composer: "gap-[7px] bg-[color-mix(in_srgb,var(--surface-panel)_74%,transparent)] px-2.5 py-2 backdrop-blur-[6px]",
    executionTraceGroup: "border-0 bg-transparent",
    groupTranscriptTurn: "[&_.turnContent]:w-[min(100%,920px)] [&_.turnContent]:p-0 [&_.turnContent]:border-l-0",
    inlineCode: "whitespace-normal break-words",
    markdownBody: "max-w-[min(100%,76ch)]",
    markdownBodyWithTable: "max-w-full",
    markdownTable: "table-fixed",
    messageBody: "whitespace-pre-wrap [overflow-wrap:anywhere] max-w-[min(100%,76ch)]",
    operationDetails: "border-0 bg-transparent",
    operationItem: "w-[min(100%,72ch)] grid grid-cols-[22px_minmax(0,1fr)_auto_auto_16px] items-start gap-1.5",
    operationItemTool: "max-w-full",
    operationStatus: "justify-self-start",
    operationText: "max-w-full",
    reActOperationGroup: "border-l-0 bg-transparent",
    reActOperationSummary: "inline-grid w-fit border-0 bg-transparent",
    reActResultItem: "border-0 bg-transparent",
    reActResultToggle: "border-0 bg-transparent",
    reActThoughtText: "border-l-0 bg-transparent",
    responseLabel: "text-[var(--vui-font-md)]",
    responseSegment_answer: "[&_.markdownBody]:max-w-[min(100%,76ch)] [&_.responseSegmentHeader]:hidden",
    responseToggle:
      "border-0 bg-transparent p-0 text-[var(--fg-secondary)] hover:border-transparent hover:bg-transparent [&_[data-slot=vui-button-content]]:contents [&_[data-slot=vui-button-label]]:inline-flex [&_[data-slot=vui-button-label]]:gap-[7px]",
    sendButton: "bg-[color-mix(in_srgb,var(--accent-cool)_14%,var(--surface-card))] shadow-none hover:translate-y-0",
    streamingResponseText: "text-[var(--vui-font-chat)] leading-[var(--vui-line-readable)]",
    surfaceCompact: "bg-[color-mix(in_srgb,var(--surface-panel)_72%,transparent)] [&_.timeline]:bg-[color-mix(in_srgb,var(--surface-page)_14%,transparent)] [&_.timeline]:px-3 [&_.timeline]:pt-[9px] [&_.timeline]:pb-[11px] [&_.composer]:gap-[7px] [&_.composer]:px-2.5 [&_.composer]:pt-1.5 [&_.composer]:pb-2",
    timeline: "bg-[color-mix(in_srgb,var(--surface-page)_18%,transparent)]",
    timelineAssistantTextCell: "max-w-[min(100%,920px)]",
    timelineCellHeader:
      "items-start [&_[data-slot=vui-button-content]]:contents [&_[data-slot=vui-button-label]]:contents",
    timelineCellPreview: "whitespace-normal break-words [overflow-wrap:anywhere] line-clamp-2",
    timelineThoughtText: "border-0 bg-transparent",
    turnSpeaker: "text-[var(--vui-font-md)]",
    userCard: "bg-[color-mix(in_srgb,var(--accent-cool)_8%,var(--surface-panel))]",
  },
  overrides: {
    surface:
      "relative flex h-full max-h-full min-h-0 w-full min-w-0 flex-col overflow-hidden rounded-[var(--radius-panel)] border border-[var(--vui-border-subtle)] bg-[var(--vui-surface-glass)] shadow-[var(--vui-shadow-hairline)]",
    surfaceCompact:
      "rounded-[var(--radius-panel)] border border-[var(--vui-border-subtle)] bg-[color-mix(in_srgb,var(--surface-panel)_72%,transparent)] backdrop-blur-[6px] [&_.timeline]:bg-[color-mix(in_srgb,var(--surface-page)_14%,transparent)] [&_.timeline]:px-3 [&_.timeline]:pt-[9px] [&_.timeline]:pb-[11px] [&_.composer]:gap-[7px] [&_.composer]:px-2.5 [&_.composer]:pt-1.5 [&_.composer]:pb-2",
    timeline:
      "grid min-h-0 min-w-0 flex-1 content-start gap-[10px] overflow-auto bg-[color-mix(in_srgb,var(--surface-page)_18%,transparent)] px-5 py-4 [scrollbar-gutter:stable]",
    composer:
      "grid flex-none grid-cols-[minmax(0,1fr)_auto_auto_auto] items-end gap-2 border-t border-[color-mix(in_srgb,var(--border-soft)_82%,transparent)] bg-[color-mix(in_srgb,var(--surface-panel)_74%,transparent)] px-[11px] py-[7px] pb-[9px] backdrop-blur-[6px] shadow-none",
    markdownTable:
      "min-w-full table-fixed",
    markdownTableWrap:
      "max-w-full overflow-x-auto overflow-y-hidden [scrollbar-gutter:stable]",
    agentInboxTurn:
      "grid w-full min-w-0 grid-cols-[34px_minmax(0,1fr)] gap-x-3 justify-self-stretch [&_.turnContent]:w-[min(100%,920px)] [&_.turnContent]:p-0 [&_.turnContent]:border-l-0",
    assistantTurn:
      "grid w-full min-w-0 grid-cols-[34px_minmax(0,1fr)] gap-x-3 justify-self-stretch [&_.turnContent]:w-[min(100%,920px)] [&_.turnContent]:p-0 [&_.turnContent]:border-l-0",
    assistantTurnContinuation:
      "grid w-full min-w-0 grid-cols-[34px_minmax(0,1fr)] gap-x-3 [&_.turnAvatar]:bg-transparent [&_.turnContent]:gap-1",
    groupTranscriptTurn:
      "grid w-full min-w-0 grid-cols-[34px_minmax(0,1fr)] gap-x-3 justify-self-stretch [&_.turnContent]:w-[min(100%,920px)] [&_.turnContent]:p-0 [&_.turnContent]:border-l-0",
    turnAvatar:
      "mt-0.5 grid size-8 shrink-0 place-items-center overflow-hidden rounded-full bg-[var(--vui-control-muted)] text-[var(--fg-tertiary)]",
    turnAvatarImage:
      "block h-full w-full rounded-[inherit] object-cover",
    turnContent:
      "grid min-w-0 gap-[5px]",
    turnMeta:
      "inline-flex min-w-0 items-center justify-start gap-2 text-[var(--vui-font-xs)] leading-tight text-[var(--fg-tertiary)]",
    turnMetaActions:
      "inline-flex min-w-0 items-center justify-start gap-2 text-[var(--vui-font-xs)] leading-tight text-[var(--fg-tertiary)]",
    turnMetaIdentity:
      "flex min-w-0 items-center gap-2",
    turnSpeaker:
      "min-w-0 truncate text-[var(--vui-font-md)] font-semibold leading-tight text-[var(--fg-primary)]",
    userTurn:
      "grid w-full min-w-0 grid-cols-[minmax(0,1fr)_34px] gap-x-3 justify-self-stretch [&_.turnAvatar]:col-start-2 [&_.turnAvatar]:row-start-1 [&_.turnContent]:col-start-1 [&_.turnContent]:row-start-1 [&_.turnContent]:justify-self-end [&_.turnContent]:w-[min(82%,860px)] [&_.turnMeta]:justify-self-end [&_.turnMeta]:justify-end [&_.turnMeta]:text-right [&_.turnMetaActions]:justify-end [&_.turnMetaIdentity]:justify-end [&_.turnSpeaker]:hidden",
  },
});

export default styles;
