export default {
  root: "my-3 grid min-w-0 gap-2",
  summaryRow:
    "flex min-w-0 cursor-pointer select-none items-center gap-2 rounded-xl px-2 py-1 text-left transition-colors hover:bg-vui-surface-row-hover",
  chevron: "shrink-0 text-vui-fg-tertiary transition-transform",
  chevronExpanded: "shrink-0 text-vui-fg-tertiary transition-transform rotate-90",
  caption: "m-0 min-w-0 text-vui-xs text-vui-fg-tertiary",
  workspaceNote: "m-0 shrink-0 text-vui-xs text-vui-fg-tertiary",
  diffStat: "shrink-0 font-mono text-vui-xs text-vui-fg-tertiary",
  headerActions: "ml-auto flex shrink-0 items-center gap-1",
  fileList: "grid min-w-0 max-h-[360px] gap-2 overflow-y-auto pr-1",
  group: "m-0 grid min-w-0 gap-2",
  groupCaption: "m-0 text-vui-xs font-medium text-vui-fg-secondary",
  groupNote: "m-0 text-vui-xs text-vui-fg-tertiary",
  card: "flex min-w-0 flex-wrap items-center gap-2 rounded-xl border border-vui-border-soft",
  cardMuted: "flex min-w-0 flex-wrap items-center gap-2 rounded-xl border border-vui-border-soft opacity-70",
  path: "min-w-0 flex-1 break-all text-vui-sm text-vui-fg-primary",
  actions: "flex flex-wrap items-center gap-1",
  dialog: "!w-[min(96vw,72rem)]",
  dialogContent: "min-h-0 !overflow-hidden",
  preview: "h-[65dvh] min-h-0 min-w-0",
} as const;
