"""Team registry and organization canvas service."""

from __future__ import annotations

import threading
from pathlib import Path
from typing import Any

from .runtime_scene_service import record_runtime_scene_event
from .team.canvas_primitives import (
    EDGE_TYPES,
    NODE_TYPES,
    TeamCanvasValidationError,
    _SAFE_ID_FRAGMENT,
    _issue,
    _normalize_edge as _normalize_edge_pure,
    _safe_float,
    _safe_token,
)
from .team.kind_helpers import (
    AI_SEARCH_TEAM_ID as _KIND_AI_SEARCH_TEAM_ID,
    KNOWLEDGE_EXPANSION_TEAM_ID as _KIND_KNOWLEDGE_EXPANSION_TEAM_ID,
    TEAM_ID_TO_KIND as _KIND_TEAM_ID_TO_KIND,
    TEAM_KIND_DEFAULTS as _KIND_TEAM_KIND_DEFAULTS,
    TEAM_SOURCE_TO_KIND as _KIND_TEAM_SOURCE_TO_KIND,
    TEMPLATE_MEMBER_PREFIX_TO_TEMPLATE_ID as _KIND_TEMPLATE_MEMBER_PREFIX_TO_TEMPLATE_ID,
    DERIVED_TEAM_KINDS as _KIND_DERIVED_TEAM_KINDS,
    _infer_team_kind,
    _infer_team_template_id,
    _team_default_chat_room_purpose,
    _team_kind_allows_member_agent_cascade,
)
from .team.ai_search_ranking import (
    _ai_search_source_page_keywords,
    _clean_ai_search_source_text,
    _rank_ai_search_source_page_references,
)
from .team import system_bootstrap as _system_bootstrap
from .team import system_teams as _system_teams
from .team import chat_room_links as _chat_room_links
from .team import canvas_normalize as _canvas_normalize
from .team import ai_search as _ai_search
from .team import research_organization as _research_organization
from .team import team_crud as _team_crud
from .team import team_repair as _team_repair
from .team import team_projection as _team_projection
from .team import team_membership as _team_membership
from .team import team_member_messages as _team_member_messages
from .team import team_logging as _team_logging
from .team import team_store as _team_store
from .team import team_constants as _team_constants


PROJECT_ROOT = Path(__file__).resolve().parents[3]
SCHEMA_VERSION = _team_constants.SCHEMA_VERSION
CANVAS_KIND = _team_constants.CANVAS_KIND
RESEARCH_TEAM_DISPLAY_NAME = _team_constants.RESEARCH_TEAM_DISPLAY_NAME
AI_SEARCH_TEAM_ID = _KIND_AI_SEARCH_TEAM_ID
AI_SEARCH_TEAM_DISPLAY_NAME = _team_constants.AI_SEARCH_TEAM_DISPLAY_NAME
KNOWLEDGE_EXPANSION_TEAM_ID = _KIND_KNOWLEDGE_EXPANSION_TEAM_ID
KNOWLEDGE_EXPANSION_TEAM_DISPLAY_NAME = _team_constants.KNOWLEDGE_EXPANSION_TEAM_DISPLAY_NAME
DEFAULT_TEAM_STATUS = _team_constants.DEFAULT_TEAM_STATUS
TEAM_STATUSES = _team_constants.TEAM_STATUSES
_TEAM_LOCK = threading.RLock()
_TEAM_SYSTEM_BOOTSTRAP_LOCK = threading.Lock()
_TEAM_SYSTEM_BOOTSTRAP_THREAD: threading.Thread | None = None
_TEAM_SYSTEM_BOOTSTRAP_STATE: dict[str, Any] = {
    "schemaVersion": SCHEMA_VERSION,
    "status": "idle",
    "requiredSteps": [],
    "reason": "",
    "startedAt": "",
    "finishedAt": "",
    "lastError": "",
    "elapsedMs": 0,
    "attempt": 0,
    "checkedAtMonotonic": 0.0,
}
_TEAM_DETAIL_LOG_LOCK = threading.Lock()
_TEAM_DETAIL_LOG_STATE: dict[str, dict[str, Any]] = {}
TEAM_DETAIL_LOG_SLOW_THRESHOLD_MS = _team_constants.TEAM_DETAIL_LOG_SLOW_THRESHOLD_MS
TEAM_DETAIL_LOG_ROLLUP_REPEAT_THRESHOLD = _team_constants.TEAM_DETAIL_LOG_ROLLUP_REPEAT_THRESHOLD
TEAM_DETAIL_LOG_ROLLUP_WINDOW_SECONDS = _team_constants.TEAM_DETAIL_LOG_ROLLUP_WINDOW_SECONDS
TEAM_SYSTEM_BOOTSTRAP_READY_CACHE_TTL_SECONDS = _team_constants.TEAM_SYSTEM_BOOTSTRAP_READY_CACHE_TTL_SECONDS
AI_SEARCH_SOURCE_PAGE_TIMEOUT_SECONDS = _team_constants.AI_SEARCH_SOURCE_PAGE_TIMEOUT_SECONDS
AI_SEARCH_SOURCE_PAGE_MAX_BYTES = _team_constants.AI_SEARCH_SOURCE_PAGE_MAX_BYTES
AI_SEARCH_SOURCE_PAGE_USER_AGENT = _team_constants.AI_SEARCH_SOURCE_PAGE_USER_AGENT
EVOLUTION_SYSTEM_TEAM_IDS = _team_constants.EVOLUTION_SYSTEM_TEAM_IDS
EVOLUTION_SYSTEM_TEAM_SPECS = _team_constants.EVOLUTION_SYSTEM_TEAM_SPECS
TEAM_KIND_DEFAULTS = _KIND_TEAM_KIND_DEFAULTS
DERIVED_TEAM_KINDS = _KIND_DERIVED_TEAM_KINDS
TEAM_SOURCE_TO_KIND = _KIND_TEAM_SOURCE_TO_KIND
TEAM_ID_TO_KIND = _KIND_TEAM_ID_TO_KIND
RESEARCH_TEAM_MEMBER_ROLE_KEYS = _team_constants.RESEARCH_TEAM_MEMBER_ROLE_KEYS
CHALLENGE_CUP_RESEARCH_TEAM_ID = _team_constants.CHALLENGE_CUP_RESEARCH_TEAM_ID
CHALLENGE_CUP_RESEARCH_TEAM_AGENT_CREATED_BY = _team_constants.CHALLENGE_CUP_RESEARCH_TEAM_AGENT_CREATED_BY
CHALLENGE_CUP_RESEARCH_TEAM_ROLES = _team_constants.CHALLENGE_CUP_RESEARCH_TEAM_ROLES
KNOWLEDGE_EXPANSION_TEAM_AGENT_CREATED_BY = _team_constants.KNOWLEDGE_EXPANSION_TEAM_AGENT_CREATED_BY
KNOWLEDGE_EXPANSION_TEAM_ROLES = _team_constants.KNOWLEDGE_EXPANSION_TEAM_ROLES
TEMPLATE_MEMBER_PREFIX_TO_TEMPLATE_ID = _KIND_TEMPLATE_MEMBER_PREFIX_TO_TEMPLATE_ID
AI_SEARCH_SYSTEM_ROLES = _team_constants.AI_SEARCH_SYSTEM_ROLES
AI_SEARCH_SOURCE_SCOPE_SCHEMA_VERSION = _team_constants.AI_SEARCH_SOURCE_SCOPE_SCHEMA_VERSION
AI_SEARCH_SOURCE_SCOPE_CURATED_AT = _team_constants.AI_SEARCH_SOURCE_SCOPE_CURATED_AT
AI_SEARCH_SOURCE_SCOPE_GROUPS = _team_constants.AI_SEARCH_SOURCE_SCOPE_GROUPS


class TeamServiceError(ValueError):
    """Raised when a team request is invalid."""


class TeamNotFoundError(TeamServiceError):
    """Raised when a team does not exist."""


utc_now_iso = _team_store.utc_now_iso
_perf_counter = _team_store._perf_counter
_elapsed_ms = _team_store._elapsed_ms
_try_acquire_team_lock = _team_store._try_acquire_team_lock
_release_team_lock_if_acquired = _team_store._release_team_lock_if_acquired
_load_index = _team_store._load_index
_save_index = _team_store._save_index
_read_json = _team_store._read_json
_write_json = _team_store._write_json
_teams_root = _team_store._teams_root
_teams_index_path = _team_store._teams_index_path
_team_canvas_path = _team_store._team_canvas_path
_project_root = _team_store._project_root
_sync_project_bus_root = _team_store._sync_project_bus_root
_relative_path = _team_store._relative_path
_find_team = _team_store._find_team
_normalize_required_id = _team_store._normalize_required_id
_format_validation_error = _team_store._format_validation_error

request_system_team_bootstrap = _system_bootstrap.request_system_team_bootstrap
_run_system_team_bootstrap_discovery = _system_bootstrap._run_system_team_bootstrap_discovery
_system_team_bootstrap_required_steps = _system_bootstrap._system_team_bootstrap_required_steps
_system_team_bootstrap_state_snapshot_locked = _system_bootstrap._system_team_bootstrap_state_snapshot_locked
_run_system_team_bootstrap = _system_bootstrap._run_system_team_bootstrap
_record_system_team_bootstrap_event = _system_bootstrap._record_system_team_bootstrap_event

evolution_system_teams_missing = _system_teams.evolution_system_teams_missing
challenge_cup_research_team_agents_need_repair = _system_teams.challenge_cup_research_team_agents_need_repair
_challenge_cup_research_team_agent_direct_session_available = _system_teams._challenge_cup_research_team_agent_direct_session_available
ensure_challenge_cup_research_team_agents = _system_teams.ensure_challenge_cup_research_team_agents
knowledge_expansion_team_agents_need_repair = _system_teams.knowledge_expansion_team_agents_need_repair

list_archived_team_linked_chat_room_ids = _chat_room_links.list_archived_team_linked_chat_room_ids
sync_team_chat_room = _chat_room_links.sync_team_chat_room
_remove_team_member_agents_from_chat_rooms = _chat_room_links._remove_team_member_agents_from_chat_rooms
_team_chat_room_title = _chat_room_links._team_chat_room_title
_team_participant_contexts_by_agent_id = _chat_room_links._team_participant_contexts_by_agent_id
_sync_chat_room_root = _chat_room_links._sync_chat_room_root
_team_chat_room_purpose_for_update = _chat_room_links._team_chat_room_purpose_for_update
_ensure_team_chat_room_link = _chat_room_links._ensure_team_chat_room_link
_find_existing_team_chat_room_id = _chat_room_links._find_existing_team_chat_room_id
_find_historical_team_chat_room_id = _chat_room_links._find_historical_team_chat_room_id
_historical_team_chat_room_ids = _chat_room_links._historical_team_chat_room_ids
_ensure_historical_team_chat_room_links = _chat_room_links._ensure_historical_team_chat_room_links
_archive_duplicate_team_chat_rooms = _chat_room_links._archive_duplicate_team_chat_rooms
repair_archived_team_chat_rooms = _chat_room_links.repair_archived_team_chat_rooms
_repair_archived_team_linked_chat_room = _chat_room_links._repair_archived_team_linked_chat_room
_delete_team_linked_chat_rooms = _chat_room_links._delete_team_linked_chat_rooms
_team_chat_room_needs_sync = _chat_room_links._team_chat_room_needs_sync
_team_chat_room_participant_contexts_need_sync = _chat_room_links._team_chat_room_participant_contexts_need_sync
_normalized_participant_context_value = _chat_room_links._normalized_participant_context_value
_historical_team_chat_room_needs_sync = _chat_room_links._historical_team_chat_room_needs_sync
_sync_compact_team_chat_room_metadata = _chat_room_links._sync_compact_team_chat_room_metadata
_compact_chat_room = _chat_room_links._compact_chat_room
_record_compact_chat_room_sync_skipped_busy = _chat_room_links._record_compact_chat_room_sync_skipped_busy

get_team_canvas = _canvas_normalize.get_team_canvas
_team_canvas_with_validation = _canvas_normalize._team_canvas_with_validation
save_team_canvas = _canvas_normalize.save_team_canvas
_normalize_canvas = _canvas_normalize._normalize_canvas
_normalize_node = _canvas_normalize._normalize_node
_source_authority_ref = _canvas_normalize._source_authority_ref
_projection_edit_contract = _canvas_normalize._projection_edit_contract
_validate_canvas = _canvas_normalize._validate_canvas
_normalize_members = _canvas_normalize._normalize_members
_ensure_members_can_join_team = _canvas_normalize._ensure_members_can_join_team
_members_without_cross_team_conflicts = _canvas_normalize._members_without_cross_team_conflicts
_remove_agent_from_team_canvas = _canvas_normalize._remove_agent_from_team_canvas
_sync_members_from_canvas = _canvas_normalize._sync_members_from_canvas
_default_canvas_for_team = _canvas_normalize._default_canvas_for_team
_ai_search_canvas_for_team = _canvas_normalize._ai_search_canvas_for_team
_ai_search_canvas_edges = _canvas_normalize._ai_search_canvas_edges
_ai_search_canvas_needs_sync = _canvas_normalize._ai_search_canvas_needs_sync
_default_nodes_for_members = _canvas_normalize._default_nodes_for_members
_default_edges_for_team = _canvas_normalize._default_edges_for_team
_edges_from_role_chain = _canvas_normalize._edges_from_role_chain
_edges_from_role_links = _canvas_normalize._edges_from_role_links
_default_canvas_edges_missing_for_team = _canvas_normalize._default_canvas_edges_missing_for_team
_canvas_summary_for_team = _canvas_normalize._canvas_summary_for_team
_canvas_path_summary = _canvas_normalize._canvas_path_summary

list_ai_search_source_scope_runs = _ai_search.list_ai_search_source_scope_runs
start_ai_search_source_scope_run = _ai_search.start_ai_search_source_scope_run
_default_ai_search_source_scope = _ai_search._default_ai_search_source_scope
_ai_search_source_scope_needs_sync = _ai_search._ai_search_source_scope_needs_sync
_ensure_ai_search_source_scope_file = _ai_search._ensure_ai_search_source_scope_file
_load_ai_search_source_scope = _ai_search._load_ai_search_source_scope
_ai_search_source_scope_api_fields = _ai_search._ai_search_source_scope_api_fields
_select_ai_search_sources = _ai_search._select_ai_search_sources
_ai_search_query_for_source = _ai_search._ai_search_query_for_source
_execute_ai_search_query_card = _ai_search._execute_ai_search_query_card
_run_ai_web_search = _ai_search._run_ai_web_search
_run_ai_source_page_fallback = _ai_search._run_ai_source_page_fallback
_fetch_ai_search_source_page = _ai_search._fetch_ai_search_source_page
_parse_ai_search_source_page = _ai_search._parse_ai_search_source_page
_AiSearchSourcePageParser = _ai_search._AiSearchSourcePageParser
_ai_search_result_is_error = _ai_search._ai_search_result_is_error
_web_search_summary_text = _ai_search._web_search_summary_text
_references_from_web_search_result = _ai_search._references_from_web_search_result
_new_ai_search_run_id = _ai_search._new_ai_search_run_id
_load_ai_search_runs_index = _ai_search._load_ai_search_runs_index
_upsert_ai_search_run_summary = _ai_search._upsert_ai_search_run_summary
_ai_search_source_scope_path = _ai_search._ai_search_source_scope_path
_ai_search_runs_root = _ai_search._ai_search_runs_root
_ai_search_runs_index_path = _ai_search._ai_search_runs_index_path
_ai_search_run_path = _ai_search._ai_search_run_path

ensure_research_team_from_organization = _research_organization.ensure_research_team_from_organization
_members_from_research_organization = _research_organization._members_from_research_organization
_sync_research_team_member_agent_roles = _research_organization._sync_research_team_member_agent_roles
_canvas_from_research_organization = _research_organization._canvas_from_research_organization
_organization_reporting_edges = _research_organization._organization_reporting_edges
_resolve_report_to_agent_id = _research_organization._resolve_report_to_agent_id
_research_org_role = _research_organization._research_org_role
_normalize_report_to_reference = _research_organization._normalize_report_to_reference
_research_member_function_label = _research_organization._research_member_function_label
_research_member_responsibilities = _research_organization._research_member_responsibilities
_responsibility_values = _research_organization._responsibility_values

list_teams = _team_crud.list_teams
list_teams_compact = _team_crud.list_teams_compact
list_team_graph_references = _team_crud.list_team_graph_references
create_team = _team_crud.create_team
get_team = _team_crud.get_team
get_team_light = _team_crud.get_team_light
assert_team_exists = _team_crud.assert_team_exists
update_team = _team_crud.update_team
remove_agent_from_teams = _team_crud.remove_agent_from_teams
remove_agents_from_teams = _team_crud.remove_agents_from_teams
restore_removed_agents_to_teams = _team_crud.restore_removed_agents_to_teams
archive_team = _team_crud.archive_team
_archive_team_in_state = _team_crud._archive_team_in_state
_finalize_archived_team_in_state = _team_crud._finalize_archived_team_in_state
_reject_system_or_unsupported_team_archive = _team_crud._reject_system_or_unsupported_team_archive
send_team_message = _team_crud.send_team_message
list_agent_team_references = _team_crud.list_agent_team_references
_find_reusable_empty_team = _team_crud._find_reusable_empty_team
_new_team_id = _team_crud._new_team_id
_normalized_team_dedupe_key = _team_crud._normalized_team_dedupe_key
_summary = _team_crud._summary

_ensure_team_member_agents_can_archive = _team_repair._ensure_team_member_agents_can_archive
_cascade_archive_member_agents_unlocked = _team_repair._cascade_archive_member_agents_unlocked
_archive_team_member_agents = _team_repair._archive_team_member_agents
_repair_archived_team_member_agents = _team_repair._repair_archived_team_member_agents
_repair_archived_team_member_agents_for_team = _team_repair._repair_archived_team_member_agents_for_team
_prune_missing_archived_team_members = _team_repair._prune_missing_archived_team_members
_repair_index_state = _team_repair._repair_index_state
_repair_index_shape = _team_repair._repair_index_shape
_repair_index_compact_contracts = _team_repair._repair_index_compact_contracts
_repair_team_contract_only = _team_repair._repair_team_contract_only
_repair_team = _team_repair._repair_team
_prune_unavailable_derived_team_members = _team_repair._prune_unavailable_derived_team_members
_stale_member_agent_ids = _team_repair._stale_member_agent_ids
_repair_members = _team_repair._repair_members

_team_to_api = _team_projection._team_to_api
_team_to_compact_reference = _team_projection._team_to_compact_reference
_team_to_graph_reference = _team_projection._team_to_graph_reference
_team_detail_to_api = _team_projection._team_detail_to_api
_team_to_api_without_canvas_summary = _team_projection._team_to_api_without_canvas_summary
_members_to_api = _team_projection._members_to_api
_get_team_record = _team_projection._get_team_record
_agent_reference_maps = _team_projection._agent_reference_maps
_load_lightweight_agent_references = _team_projection._load_lightweight_agent_references
_agent_reference_maps_from_agents = _team_projection._agent_reference_maps_from_agents
_merged_agent_reference_maps = _team_projection._merged_agent_reference_maps
_agent_reference = _team_projection._agent_reference

_find_active_team_for_agent = _team_membership._find_active_team_for_agent
_find_active_team_for_agent_in_state = _team_membership._find_active_team_for_agent_in_state
_unique_active_member_agent_ids = _team_membership._unique_active_member_agent_ids
_active_member_agent_ids = _team_membership._active_member_agent_ids
_active_member_session_ids = _team_membership._active_member_session_ids
_member_direct_session_kind = _team_membership._member_direct_session_kind
_ensure_active_member_direct_sessions = _team_membership._ensure_active_member_direct_sessions
build_team_roster_context_lines = _team_membership.build_team_roster_context_lines
_apply_team_contract = _team_membership._apply_team_contract
list_team_member_messages = _team_member_messages.list_team_member_messages
record_team_member_message = _team_member_messages.record_team_member_message
shared_active_team_for_agents = _team_member_messages.shared_active_team_for_agents

_record_team_event = _team_logging._record_team_event
_team_detail_log_fields = _team_logging._team_detail_log_fields
_team_detail_log_signature = _team_logging._team_detail_log_signature
_emit_team_detail_loaded = _team_logging._emit_team_detail_loaded
_emit_team_detail_rollup = _team_logging._emit_team_detail_rollup
_record_team_detail_loaded = _team_logging._record_team_detail_loaded
_record_team_membership_conflict = _team_logging._record_team_membership_conflict
_record_team_archive_rejected = _team_logging._record_team_archive_rejected
_record_archived_team_member_cascade_repaired = _team_logging._record_archived_team_member_cascade_repaired
_record_system_team_membership_conflict = _team_logging._record_system_team_membership_conflict
_record_system_team_sync_failed = _team_logging._record_system_team_sync_failed

_knowledge_expansion_team_agent_direct_session_available = _system_teams._knowledge_expansion_team_agent_direct_session_available
ensure_knowledge_expansion_team_agents = _system_teams.ensure_knowledge_expansion_team_agents
ensure_evolution_system_teams = _system_teams.ensure_evolution_system_teams
ai_search_system_team_missing = _system_teams.ai_search_system_team_missing
ensure_ai_search_system_team = _system_teams.ensure_ai_search_system_team
_ensure_evolution_system_agents = _system_teams._ensure_evolution_system_agents
_ensure_ai_search_system_agents = _system_teams._ensure_ai_search_system_agents
_ensure_challenge_cup_research_team_role_agents = _system_teams._ensure_challenge_cup_research_team_role_agents
_ensure_challenge_cup_research_team_role_agent = _system_teams._ensure_challenge_cup_research_team_role_agent
_ensure_knowledge_expansion_team_role_agents = _system_teams._ensure_knowledge_expansion_team_role_agents
_ensure_knowledge_expansion_team_role_agent = _system_teams._ensure_knowledge_expansion_team_role_agent
_agent_direct_session_available = _system_teams._agent_direct_session_available
_find_challenge_cup_research_team_agent = _system_teams._find_challenge_cup_research_team_agent
_find_knowledge_expansion_team_agent = _system_teams._find_knowledge_expansion_team_agent
_challenge_cup_research_team_role_metadata = _system_teams._challenge_cup_research_team_role_metadata
_knowledge_expansion_team_role_metadata = _system_teams._knowledge_expansion_team_role_metadata
_challenge_cup_research_team_members_from_agents = _system_teams._challenge_cup_research_team_members_from_agents
_knowledge_expansion_team_members_from_agents = _system_teams._knowledge_expansion_team_members_from_agents
_challenge_cup_research_team_bound_agent_ids = _system_teams._challenge_cup_research_team_bound_agent_ids
_challenge_cup_research_team_duplicate_agent_ids = _system_teams._challenge_cup_research_team_duplicate_agent_ids
_knowledge_expansion_team_bound_agent_ids = _system_teams._knowledge_expansion_team_bound_agent_ids
_knowledge_expansion_team_duplicate_agent_ids = _system_teams._knowledge_expansion_team_duplicate_agent_ids
_purge_knowledge_expansion_team_agents = _system_teams._purge_knowledge_expansion_team_agents
_purge_challenge_cup_research_team_agents = _system_teams._purge_challenge_cup_research_team_agents
_purge_challenge_cup_research_team_agent = _system_teams._purge_challenge_cup_research_team_agent
_delete_orphan_agent_workspace = _system_teams._delete_orphan_agent_workspace
_safe_agent_workspace_name = _system_teams._safe_agent_workspace_name
_ensure_ai_search_role_agent = _system_teams._ensure_ai_search_role_agent
_find_agent_by_ai_search_role = _system_teams._find_agent_by_ai_search_role
_ai_search_role_metadata = _system_teams._ai_search_role_metadata
_ai_search_members_from_agents = _system_teams._ai_search_members_from_agents
_ensure_evolution_system_team_in_state = _system_teams._ensure_evolution_system_team_in_state
_system_members_from_agents = _system_teams._system_members_from_agents
