export const challengeCupTeamCanvasPreviewStyles = {
  page: "tcc-page",
  header: "tcc-header",
  eyebrow: "tcc-eyebrow",
  subtitle: "tcc-subtitle",
  analogs: "tcc-analogs",
  analog: "tcc-analog",
  analogRank: "tcc-analog-rank",
  scenes: "tcc-scenes",
  note: "tcc-note",
  frame: "tcc-frame",
  frameNarrow: "tcc-frame-narrow",
  current: "tcc-current",
  currentRail: "tcc-current-rail",
  currentTeam: "tcc-current-team !grid",
  currentTeamActive: "tcc-current-team-active !grid",
  currentMain: "tcc-current-main",
  currentToolbar: "tcc-current-toolbar",
  currentFlow: "tcc-current-flow",
  currentFlowCta: "tcc-current-flow-cta",
  currentStages: "tcc-current-stages",
  currentStage: "tcc-current-stage",
  currentCanvasHint: "tcc-current-canvas-hint",
  proposed: "tcc-proposed h-full min-h-0",
  toolbar: "tcc-toolbar w-full min-w-0 !flex !flex-nowrap items-center gap-3 overflow-hidden",
  toolbarSwitch: "tcc-toolbar-switch min-w-0 max-w-[22rem] shrink",
  toolbarMeta: "tcc-toolbar-meta shrink-0",
  toolbarActions: "tcc-toolbar-actions ml-auto shrink-0 !flex-nowrap",
  rail: "tcc-rail",
  nextCard: "tcc-next-card",
  nextKicker: "tcc-next-kicker",
  nextTitle: "tcc-next-title",
  nextBody: "tcc-next-body",
  stageList: "tcc-stage-list",
  stageItem: "tcc-stage-item",
  stageItemActive: "tcc-stage-item-active",
  nodeIndex: "tcc-node-index",
  nodeIndexItem: "tcc-node-index-item !grid",
  nodeIndexItemActive: "tcc-node-index-item-active !grid",
  canvasHost: "tcc-canvas-host",
  canvas: "tcc-canvas",
  edges: "tcc-edges",
  node: "tcc-node !absolute !grid w-[172px] h-[108px] overflow-hidden",
  nodeActive: "tcc-node-active !absolute !grid w-[172px] h-[108px] overflow-hidden",
  nodeIcon: "tcc-node-icon",
  inspector: "tcc-inspector",
  inspectorHeader: "tcc-inspector-header",
  inspectorEmpty: "tcc-inspector-empty",
  inspectorGrid: "tcc-inspector-grid",
  issue: "tcc-issue",
} as const;
