export const launcherLayoutPreviewStyles = {
  page: "min-h-screen w-full bg-vui-surface-workspace text-vui-fg-primary",
  topbar: "flex flex-wrap items-start justify-between gap-x-6 gap-y-2 px-6 pt-5 pb-1",
  eyebrow: "mb-1 text-xs font-bold uppercase tracking-widest text-vui-fg-tertiary",
  title: "m-0 text-2xl font-semibold tracking-tight text-vui-fg-primary",
  subtitle: "mt-2 max-w-2xl text-sm leading-relaxed text-vui-fg-secondary",
  topActions: "flex shrink-0 flex-wrap items-center gap-2",
  mockBadge:
    "inline-flex items-center gap-1 rounded-full border border-dashed border-vui-border-subtle px-2.5 py-1 text-xs font-semibold text-vui-fg-tertiary",
  scenarioBar:
    "mx-6 mt-3 flex flex-wrap items-center gap-2 rounded-lg border border-vui-border-subtle bg-vui-surface-panel px-2 py-1.5",
  scenarioLabel: "px-1 text-xs font-semibold uppercase tracking-widest text-vui-fg-tertiary",
  layout: "grid min-w-0 grid-cols-1 gap-4 px-6 pb-2 pt-3 lg:grid-cols-[minmax(0,1fr)_minmax(250px,0.32fr)] lg:items-start",
  main: "min-w-0",
  rail: "min-w-0",
  sectionHeader: "flex flex-wrap items-center justify-between gap-x-4 gap-y-2",
  sectionTitle: "m-0 text-lg font-semibold text-vui-fg-primary",
  sectionHint: "mt-0.5 text-xs text-vui-fg-tertiary",
  count: "ml-1 rounded-full bg-vui-control-muted px-1.5 text-xs font-semibold text-vui-fg-secondary",
  toolbar: "flex flex-wrap items-center gap-2 pt-3",
  search: "w-full max-w-xs",
  riskSelect: "w-40",
  rowCount: "ml-auto text-xs text-vui-fg-tertiary",
  branchCell: "flex min-w-0 items-center gap-2",
  branchName: "truncate font-medium text-vui-fg-primary",
  branchKind: "truncate text-xs text-vui-fg-tertiary",
  rowActions: "flex items-center gap-1",
  runtimeCell: "flex min-w-0 flex-col gap-0.5",
  runtimeLine: "truncate text-xs leading-tight text-vui-fg-secondary",
  card: "p-3",
  cardHeader: "flex items-center justify-between gap-2",
  cardTitle: "m-0 text-sm font-semibold text-vui-fg-primary",
  summary: "mt-2 grid gap-1.5",
  summaryRow: "flex flex-wrap items-center gap-1.5 text-xs text-vui-fg-secondary",
  summaryValue: "font-semibold text-vui-fg-primary",
  settingsFields: "mt-3 grid gap-2",
  field: "grid gap-1 text-xs font-medium text-vui-fg-secondary",
  mockNote: "mt-2 text-xs leading-relaxed text-vui-fg-tertiary",
  maintenanceRows: "mt-2 grid gap-1",
  maintenanceRow: "flex items-start justify-between gap-2 text-xs text-vui-fg-secondary",
  maintenanceKey: "shrink-0 text-vui-fg-tertiary",
  maintenanceValue: "min-w-0 text-right font-medium text-vui-fg-primary",
  footer: "px-6 pb-6 pt-4 text-xs leading-relaxed text-vui-fg-tertiary",
} as const;
