const styles = {
  page: "page",
  intro: "intro",
  eyebrow: "eyebrow",
  compare: "compare",
  bench: "bench",
  current: "is-current",
  proposed: "is-proposed",
  chrome: "chrome",
  topbar: "topbar",
  nav: "nav",
  navActive: "nav is-active",
  status: "status",
  body: "body",
  rail: "rail",
  railLabel: "rail-label",
  session: "session",
  sessionActive: "session is-active",
  thread: "thread",
  turn: "turn",
  userTurn: "turn is-user",
  assistantTurn: "turn is-assistant",
  thought: "thought",
  answer: "answer",
  composer: "composer",
  srOnly: "sr-only",
  footnote: "footnote",
} as const;

export default styles;
