export const researchWorkflowToolbarPreviewStyles = {
  page: "rwt-page",
  header: "rwt-header",
  eyebrow: "rwt-eyebrow",
  subtitle: "rwt-subtitle",
  scenes: "rwt-scenes",
  compare: "rwt-compare",
  column: "rwt-column",
  columnLabel: "rwt-column-label",
  frame: "rwt-frame",
  frameNarrow: "rwt-frame-narrow",
  rail: "rwt-rail",
  railItem: "rwt-rail-item",
  railItemActive: "rwt-rail-item-active",
  main: "rwt-main",
  strip: "rwt-strip",
  canvas: "rwt-canvas",
  canvasHint: "rwt-canvas-hint",
  current: "rwt-current",
  currentContext: "rwt-current-context",
  currentPrimary: "rwt-current-primary",
  currentTruncated: "rwt-current-truncated",
  currentNext: "rwt-current-next",
  currentActions: "rwt-current-actions",
  currentSelect: "rwt-current-select",
  proposed: "rwt-proposed w-full min-w-0 !flex-nowrap !grid grid-cols-[minmax(12rem,1fr)_auto_max-content] items-center gap-x-3 overflow-x-auto",
  proposedSwitcher: "rwt-proposed-switcher min-w-0",
  proposedStatus: "rwt-proposed-status",
  proposedStatusLabel: "rwt-proposed-status-label",
  proposedStatusEmpty: "rwt-proposed-status-empty",
  proposedEmpty: "rwt-proposed-empty",
  proposedActions: "rwt-proposed-actions",
  proposedNav: "rwt-proposed-nav !flex-nowrap",
  inspector: "rwt-inspector",
  inspectorTitle: "rwt-inspector-title",
  inspectorBody: "rwt-inspector-body",
  note: "rwt-note",
} as const;
