export const teamWorkflowCardPreviewStyles = {
  page: "twc-page",
  header: "twc-header",
  eyebrow: "twc-eyebrow",
  subtitle: "twc-subtitle",
  scenes: "twc-scenes",
  note: "twc-note",
  compare: "twc-compare",
  column: "twc-column",
  columnLabel: "twc-column-label",
  stage: "twc-stage",
  stageHead: "twc-stage-head",
  stageIndex: "twc-stage-index",
  stageTitle: "twc-stage-title",
  stageChip: "twc-stage-chip",
  flow: "twc-flow",
  step: "twc-step",
  arrow: "twc-arrow",
  gallery: "twc-gallery",
  galleryLabel: "twc-gallery-label",
  borrow: "twc-borrow",
  borrowItem: "twc-borrow-item",
} as const;
